### ISSUE TITLE
How to add .shp files to the map 

### ISSUE THREAD

**Issue by jahongir9779** [graphhopper/graphhopper#1003]
I managed to load map with .map and .osm.pbf files, but i need to add .shp files so that the buildings' shapes would look more nice and realistic. I have downloaded all files from http://download.geofabrik.de/    
Is it possible to add those files to the project? 

this is what i got  

![screenshot_20170324-115956](https://cloud.githubusercontent.com/assets/12813066/24285662/037e1ea6-1093-11e7-8968-afedad58e6cb.png)

this is what i want 

![screenshot_20170324-115950](https://cloud.githubusercontent.com/assets/12813066/24285671/0f03e292-1093-11e7-8797-8da3ae773dbd.png)

thanx

**Comment by devemux86** [comment]
GraphHopper uses [VTM](https://github.com/mapsforge/vtm) OpenGL vector map library with [Mapsforge](https://github.com/mapsforge/mapsforge) maps in the sample.
Map related questions could be better handled in Mapsforge / VTM [forum](https://groups.google.com/group/mapsforge-dev).

**Comment by jahongir9779** [comment]
thanx
