### ISSUE TITLE
Estimate delays at crossings / traffic lights for pedestrians

### ISSUE THREAD

**Issue by kvlahromei** [graphhopper/graphhopper#1005]
Similar like #75 this issue focus on pedestrians. 

Currently the engine prefers a route across a major road (which will take minutes waiting at the traffic light), instead of using an direct way:
http://www.openstreetmap.org/directions?engine=graphhopper_foot&route=54.09235%2C12.10083%3B54.09311%2C12.09967#map=19/54.09274/12.10012&layers=N
(you can force the routing, if you move start on the tunnel / bridge)

So corresponding on the road class, an traffic light crossing should get extra penalty to get the fastest possible route.

**Comment by karussell** [comment]
No separate issue is necessary I think. Also if you print alternatives then the user is able to apply local knowledge because steps could also take long time for certain users and you never know how fast such a traffic light is for walking.

**Comment by karussell** [comment]
Forgot the link to [the alternatives](https://graphhopper.com/maps/?point=54.09235%2C12.10083&point=54.093024%2C12.099241&vehicle=foot&algorithm=alternative_route&ch.disable=true)
