### ISSUE TITLE
Improve problem found in #1000

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1006]
Add integration test which would have shown this and move load method into the Runnable?

Improvement for #1000

**Comment by boldtrn** [comment]
How would we write an IT for this? In GraphHopperIT, load a Graph with LM and Monaco. Stop the server. Start the server again using the created graph?

**Comment by karussell** [comment]
We could use a similar test like in GraphHopperStorageTest.testSave_and_fileFormat to check that the gh storage loads. We could call gh.importOrLoad()+gh.close()+new GraphHopper().importOrLoad() again
