### ISSUE TITLE
Many InvocationTargetExceptions in pt branch

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1008]
E.g. InvocationTargetException for field 'weight' of com.graphhopper.routing.VirtualEdgeIteratorState instance

**Comment by karussell** [comment]
Thanks!

Should we fix the problem that the VirtualEdgeIterator throws exceptions (which one)?

**Comment by michaz** [comment]
Hmm, not sure if it's a problem. For a getter, throwing an exception to mean "not available" is not very common, but it's not.. as such.. _wrong_. The code now does what it should: Not include the attribute when the getter throws. And I'm just serializing these things for debugging, anyway. Not sure if this will even be there when we merge.

I'd be ok with just leaving it until we think it may be a problem for the _second_ time. :-)

**Comment by michaz** [comment]
(I just stuffed the class into a JSON-Serializer which just scrapes off all the getters which were probably not even meant for that, so.. it's not the class's fault.)
