### ISSUE TITLE
Instructions Exception "Couldn't find the edges for..."

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#1010]
We throw an exception when we cannot find the other edges. It happens for some routes that these cannot be found.

We should make the code more robust and maybe just return the calculated sign?

**Comment by karussell** [comment]
This depends. Is this a bug then an exception is appropriated or is this just a warning then we could return an unknown instruction - something that we would also need for our clients to support and fallback if a new instruction is unknown

**Comment by boldtrn** [comment]
> This depends. Is this a bug?

In a way, yes, but it is weird from a user perspective.Logging with an error and simply returning the sign might be ok in this situation. On the other hand throwing an exception would help us identifying issues.

**Comment by karussell** [comment]
> On the other hand throwing an exception would help us identifying issues.

I'm always for this strict behavior (if it is a bug) as it helps us to improve GH in the long term.

**Comment by karussell** [comment]
Is this error only happening with at least one via point or did it happen also for just one start and one destination?

**Comment by boldtrn** [comment]
> Is this error only happening with at least one via point or did it happen also for just one start and one destination?

I happened only close to via points. But I think this was related to #1013, so we might be able to simply close this once #1013 is fixed.

**Comment by brunoban** [comment]
Not sure if this is something I should post here, but I think it could be related. I had the "Couldn't find the edges for..." exception popping up in a map I had already downloaded entirely (in this case, the Hamburg map) for a route that is working on the GraphHopper hosted map but it's not working locally.

https://graphhopper.com/maps/?point=53.555691%2C9.95036&point=53.556287%2C9.950358&point=53.543104%2C10.002367&point=53.541534%2C10.002655&locale=en-US&vehicle=car&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale

The route is

Start:    53.555691,9.95036
Point 1: 53.556287,9.950358
Point 2: 53.543104,10.002367
End:      53.541534,10.002655

It's happening with other routes as well, but I am not sure if this is something we should account for as not working all the time or if it can be something that I am not doing correctly. Can anyone shed some light?

**Comment by boldtrn** [comment]
@brunoban we are currently working on this issue. This was created with the improved instructions recently. If you are looking for a fast solution, have a look at this [PR](https://github.com/graphhopper/graphhopper/pull/1014). I expect it to get merged soon.
