### ISSUE TITLE
Potential problem for private access

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1012]
See discussion [here](https://discuss.graphhopper.com/t/pedestrian-routing-through-private-ways/1689) and the osm way [here](http://www.openstreetmap.org/way/467642849)

**Comment by boldtrn** [comment]
Yes, seems to be [created by the sidewalk tag](https://github.com/graphhopper/graphhopper/blob/196aac2dc8b113071be627adcd3572ed0b5b0140/core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java#L224). We might want to check for restrictions first.

**Comment by karussell** [comment]
Thanks for this catch - will fix!
