### ISSUE TITLE
Instructions should ignore VirtualEdges created during lookup

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#1013]
When during the lookup phase of a route request a new virtual edge is generated for StartPoint -> FirstRoute, we have to ignore these VirtualEdges. They lead to a wrong number of turns or might be interpreted as turns, which shouldn't be the case. Here is one example case, the requested point is place very close to Edge2:

```
  Edge3      NewVirtualEdge
        \   /
Edge 1   \ /         Edge 2
__________  ______________
```

When routing from NewVirtualEdge via Edge two, the Instructions are Continue -> Turn Sharp Left.

I think we should ignore the newly created VirtualEdges/VirtualNodes in this case?

**Comment by karussell** [comment]
Not sure if this has something to do with this but do you return a weight smaller than 1e-3 in Weighting.calcWeight? Currently we do not check weight boundaries for CH but we could to do so e.g. in CHGraphImpl.setWeight also there you see the WEIGHT_FACTOR=1000

**Comment by karussell** [comment]
Can we close here and is the real underlying reason same as #1022?

**Comment by boldtrn** [comment]
I think so, yes.

**Comment by karussell** [comment]
Done
