### ISSUE TITLE
unreachable sanity check

### ISSUE THREAD

**Issue by mitjap** [graphhopper/graphhopper#1021]
In TurnCostExtension there is a sanity check if `i > 1000`. But `i` will be at most exactly `1000` so this condition will never evaluate to `true`.

https://github.com/graphhopper/graphhopper/blame/3f9cdf5a2c4a55d9264edfe1ce1bc8fd836cfc5a/core/src/main/java/com/graphhopper/storage/TurnCostExtension.java#L181

**Comment by karussell** [comment]
Thanks for catching this!
