### ISSUE TITLE
Large distant searches by foot result in connection not found

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1022]
[This route is ok](https://graphhopper.com/maps/?point=39.629651%2C118.173934&point=44.402392%2C85.166016&point=53.792689%2C9.980813&vehicle=foot) but when you remove the via point then [the connection is not found](https://graphhopper.com/maps/?point=39.629651%2C118.173934&point=53.792689%2C9.980813&vehicle=foot). But it is found with vehicle=car. Also it should be okay without CH and so it is highly likely a duplicate of #1013 (too big edge weight) as time gets too big for vehicle=foot. (It can happen for car too, see below)

**Comment by asdzxcasd** [comment]
Here is an example of a [shorter route](https://graphhopper.com/maps/?point=47.330941%2C87.933154&point=40.769622%2C113.155489&point=40.768842%2C113.150597&locale=en-us&vehicle=foot&weighting=fastest&elevation=true&use_miles=false), which shows this behavior.

**Comment by asdzxcasd** [comment]
Also there are unnecessary parts of [route](https://graphhopper.com/maps/?point=19.13414%2C37.312489&point=18.116405%2C31.596594&locale=en-us&vehicle=foot&weighting=fastest&elevation=true&use_miles=false), which go along the river and then back, adding 275km to the shortest route. It seems to be related to this issue.

**Comment by karussell** [comment]
[This car route](https://graphhopper.com/maps/?point=35.101934%2C134.296875&point=41.804078%2C125.771484) over ferries (7 days) also does not work, but if you split it into two parts ([1.](https://graphhopper.com/maps/?point=35.101934%2C134.296875&point=37.753344%2C127.990723) and [2.](https://graphhopper.com/maps/?point=37.753344%2C127.990723&point=41.804078%2C125.771484)) then they'll work.

**Comment by karussell** [comment]
Most routes except the [first reported route](https://graphhopper.com/maps/?point=39.629651%2C118.173934&point=53.792689%2C9.980813&profile=foot) do work now. The first route seems to be even worse and you now need more via point.
