### ISSUE TITLE
Support multiple profiles if pt enabled

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1023]
Currently we support public transit (`pt`) **or** road network based FlagEncoder like `car`. It should be possible to specify `graph.flag_encoders=pt,car` and being able to route through car or pt. And for the other encoders all speed up algorithms should be available, so nothing complex like multi modal. Just reusing the graph data structure.

As a start we should throw an exception telling that "pt,car" is not yet supported.

**Comment by constantin42** [comment]
what is the status of the problem, I need the feature for a project. could you please solve the problem.

**Comment by michaz** [comment]
Meanwhile, this works.
Enable PT by `gtfs.file=...`. (Currently) don't mention pt anywhere in `flag_encoders` or `profiles`, it'll just work.

**Comment by karussell** [comment]
Ah, this is great, thanks!

**Comment by amrshah** [comment]
any updates on this? I want to know if multi modal plans can be generated by graph hopper latest version(s)?
