### ISSUE TITLE
shape reader does not create graph truly 

### ISSUE THREAD

**Issue by shadi-attarha** [graphhopper/graphhopper#1024]
Hello
when the shape reader want to create graph from the shape file, it adds all the components as the highway. it does not define the type for roundabout and can not define the roundabout and threat like a highway.
when i debug the OSMShapeFileReader in addEdge class i saw 
Object type = road.getAttribute("fclass");
        if (type != null) {
            way.setTag("highway", type.toString());
        }

so it seams we must define the roundabout type and complete this condition.

**Comment by karussell** [comment]
Please do not post questions here. Furthermore you already posted on the forum [here](https://discuss.graphhopper.com/t/shape-reader-can-not-create-graph-truly/1755).
