### ISSUE TITLE
Consider flattening the web server

### ISSUE THREAD

**Issue by michaz** [graphhopper/graphhopper#1030]
I think we may have (at least) one layer too much in ``web``:

```
jetty
  servlet
    guice-servlet
```

I think the Servlet layer exists because we want to support Servlet deployment on other servers. I think the GuiceServlet layer exists because the pure Servlet API is ugly to program against.

But I also think I picked up somewhere that we are not sure if we want to support WAR-deployment, or Servlet-deployment in general, anymore.

((Not an expert, but to me, the industry looks like _all of this_ (Java-based containers) is going away and all that remains are simple ``main()`` methods which open a port, and Docker.))

Perhaps we can pull that through and flatten the server to

```
jetty
  guice
```

and then perhaps even to

```
jetty
```

Leading to more linear code.

(I just had to write something really ugly into ``GHServer``, and the reason was mainly because I thought maybe I shouldn't use ``Runtime`` or Jetty things directly, because we are a well-behaved Java web application in a container. But perhaps we can be more bad-ass about that.)

**Comment by karussell** [comment]
ElasticSearch does this. And they use netty. Or maybe we switch to something like dropwizard or Spring boot to really reduce the web code to glue code to our Java API

**Comment by michaz** [comment]
Superseded by PR #1108
