### ISSUE TITLE
Webclient can't handle '.' in parameter names, so pt parameter names remain without '.'

### ISSUE THREAD

**Issue by michaz** [graphhopper/graphhopper#1034]
Following up on #1018 - the attempted fix didn't work. It would only work _once_, but just moving one of the markers would break it. I reverted the parameter renaming and the change in the web client.

If we still want to rename the parameters to 'pt.*', we have to try again.

**Comment by boldtrn** [comment]
Could you describe the problem a bit more? I think I did this in the web client. I think the trick was create an object in the json array in GHRequest. I think it should look something like this pt : { parameter : abc}. Or maybe we are talking about something different?

**Comment by michaz** [comment]
Commit 4d680abed3793dc2a003185e538123952ea591b0 renames the request parameters from <something> to pt.<something>.

But the web client can't handle that.

Commit 4828b13815e4cd5a9f9ee89aad55519d015929b1 wanted to tell the web client about the new parameter names, but it wouldn't work for anything but the first request (move one of the markers: crash). Reason seems to be that the web client does something with the parameter strings which doesn't like ``.``.

**Comment by michaz** [comment]
(My suggestion would be to just not rename the parameters.)

**Comment by karussell** [comment]
The intention is to provide a more or less consistent naming via URL parameters that will later also be made available via JSON. And normally it should be supported already as @boldtrn mentioned but I had to change a few things. IMO this is a client issue that we should fix instead of influencing the parameter naming

**Comment by michaz** [comment]
Okay, sure! (Was just suggesting a shortcut opportunity. :) )

**Comment by boldtrn** [comment]
@michaz Could you provide me some more details on how to reproduce this issue? I just tried two things:

- Add the parameter to the url, like `pt.xyz=PT`
- In GHRequest: `this.api_params = {"locale": "en", "vehicle": "car", "weighting": "fastest", "elevation": false, "key": api_key, "pt.abc": "ptRocks"};`

Both parameters work for me. I can move markers, create via-points, I can reload the parameters via the url.

**Comment by michaz** [comment]
@boldtrn If you would just reapply those two commits and run: That's what wasn't working for me.

**Comment by michaz** [comment]
I don't know the web client well though. Maybe my diagnosis wasn't very good. I only wanted to note that _this_ didn't work.

**Comment by karussell** [comment]
Passing a dotted parameter just worked.

But here it is necessary to parse the URL parameter into a JS object recursively and create the flat&dotted parameter list from this recursive parameter object again. And the first step (URL param->JS object) was missing from the previous commits I did. Will think about and/or implement it.

**Comment by karussell** [comment]
Should be fixed with #1057
