### ISSUE TITLE
Replace JTS with EPLicense version from LocationTech

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1039]
After gtfs addition we need to update the [NOTICE file](https://github.com/graphhopper/graphhopper/blob/master/NOTICE.md) and use the [EDL version](https://github.com/locationtech/jts) for jts once released:

```xml
<groupId>org.locationtech.jts</groupId>
<artifactId>jts</artifactId>
<version>1.15.0</version>
```

Include elevation data attribution and GTFS attribution in the NOTICE file or somewhere else.

**Comment by karussell** [comment]
So for this move we need [this new dependency](https://github.com/graphhopper/graphhopper/pull/1230#issuecomment-359590077) and a [new gtfs-lib](https://github.com/conveyal/gtfs-lib/issues/97)

**Comment by willcohen** [comment]
Re gtfs-lib -- since they've got some moving pieces on their own end to work with before they can release an updated version, would you prefer to wait on their release for this change or use a forked version without geotools (it's already in a PR in that repo) and an updated JTS pending that? Updating their jackson dependency to use the new JTS should also be pretty simple.

**Comment by karussell** [comment]
Good question. Waiting for their changes reduces a bit our own work :)

**Comment by willcohen** [comment]
Okay! If you decide you'd like to give the fork a go, let me know and I can put together PRs for those dependencies.

**Comment by karussell** [comment]
@michaz It seems that the team behind gtfs-lib won't use the latest JTS soon due to their internal stuff, see [this comment](https://github.com/conveyal/gtfs-lib/issues/97#issuecomment-370706124). Should we use the forked gtfs-lib maybe with help of @willcohen or avoid future hassle and stay on JTS 1.14 for now?

**Comment by willcohen** [comment]
I know Geotools is a big holdup for them to transition their other software, but 20 should be out any day now. If getting from whatever Geotools version they're currently using in other projects to 20 ends up being super complicated it may drag this out out, but if it's not too hard an upgrade then they may be able to get gtfs-lib up to speed quicker.

**Comment by michaz** [comment]
No. They are apparently moving to using an actual database as a backend, and the part I am using is _specifically_ the one they are going to remove.

**Comment by willcohen** [comment]
Would you all prefer to ask them to keep GTFSFeed in and migrate JTS up, or just fork the older version and stick to that?

**Comment by michaz** [comment]
Right now I think I would just "inline" the bits I am using and drop the binary dependency.

**Comment by michaz** [comment]
(Upstream seems to go in a somewhat different direction anyway, so I think I don't think I have to keep future developments mergeable.)
