### ISSUE TITLE
Test data contain invalid geometries

### ISSUE THREAD

**Issue by michaz** [graphhopper/graphhopper#1043]
``countries.geo.json`` contains self-intersecting Multipolygons, which is illegal. GeoJSON obviously doesn't care about that, but JTS doesn't accept them, and neither would e.g. PostGIS.

I would suspect that the tool which was used to simplify the geometry didn't care about topology. 

<img width="350" alt="screen shot 2017-04-27 at 16 06 52" src="https://cloud.githubusercontent.com/assets/520916/25487177/b93539ec-2b63-11e7-8145-44c60153a8b9.png">

This is a bit mean because it prevents me from experimenting with standard geometric algorithms. ,-)

**Comment by karussell** [comment]
> I would suspect that the tool which was used to simplify the geometry didn't care about topology.

According to #926 douglas peucker was used and could indeed produce these problem:

> As the file would be 25mb, is reduced it to 10% using DP.

**Comment by karussell** [comment]
Maybe this could help to be applied on the original data? https://www.jasondavies.com/simplify/

**Comment by boldtrn** [comment]
You can try to use the original 25 MB data set. It is referenced in the readme next to the countries file. Maybe we can simplify the countries without self intersection.

**Comment by devemux86** [comment]
Also JTS contains simplifiers ensuring that results are valid geometries.

**Comment by boldtrn** [comment]
> Test data contain invalid geometries

Well self intersecting polyons are not invalid just because JTS cannot handle them ;). But your are right, we should rather use simple polygons, as they might actually make things simpler.

> Maybe this could help to be applied on the original data? https://www.jasondavies.com/simplify/

I also tried the Visvalingam algorithm (actually both, there are two different implementations using effective or weighted area). Getting a comparable reduction of points (10% of the original size), resulted in a lot worse area boundaries (IMHO). I used [mapshaper](http://www.mapshaper.org/) for the task which provides a nice UI so you can see what's happening. The reason why I didn't care about self-intersecting polygons, and we did consider it when implementing the SpatialRuleLookup, is that the ray casting algorithm for the [point in polygon check](https://en.wikipedia.org/wiki/Point_in_polygon) works well with self-intersecting polygons.

> Also JTS contains simplifiers ensuring that results are valid geometries.

Do they also use Visvalingam or a different algorithm?

**Comment by devemux86** [comment]
> Do they also use Visvalingam or a different algorithm?

I think they have [several](https://locationtech.github.io/jts/javadoc/org/locationtech/jts/simplify/package-summary.html).

**Comment by michaz** [comment]
> Well self intersecting polyons are not invalid just because JTS cannot handle them ;).

Oh, come on. ;-) I'm not a specification lawyer, but I understand GeoJSON is meant to represent geometries and features as GIS people use them, where Polygon _always_ means "simple" and Multipolygon means "non overlapping". It's actually an _ISO standard_:

http://portal.opengeospatial.org/files/?artifact_id=25355

**Comment by michaz** [comment]
<img width="698" alt="screen shot 2017-04-28 at 16 08 10" src="https://cloud.githubusercontent.com/assets/520916/25532232/f496c3b0-2c2c-11e7-8e9e-a6ba76d2d8b6.png">

**Comment by michaz** [comment]
That's why I was cringing a bit when we started implementing our own geometry data-types. This stuff is _super-complicated_ and while it may be easy and tempting and perhaps even _faster_ to get your specific use case working without using a library, you will _never_ get the _general_ case right. These docs are hundreds of pages for a reason.

**Comment by karussell** [comment]
BTW: What exactly does not work in GraphHopper or are you currently exploring this for a new feature?

**Comment by michaz** [comment]
I have another branch where I took the Jackson-stuff further, replaced GraphHopper-``Geometry`` with JTS-``Geometry`` and noticed that JTS says those aren't valid ``MultiPolygon``s.

**Comment by michaz** [comment]
@boldtrn And that's not an argument against your _algorithm_, because as you say, it's _more_ general (can handle self-intersecting stuff). Only against the custom data-types, because those words (``MultiPolygon``, ``intersects``, ``contains``) are standardised and the exact semantics is super-complicated.

**Comment by michaz** [comment]
(And maybe against that simplification website, because it shouldn't output invalid geometries (in the GIS sense <g>)).

**Comment by boldtrn** [comment]
> I think they have several.

Oh nice, this looks interesting.

> And that's not an argument against your algorithm

Never thought it was, no worries :). I was just complaining about the invalid geometries part ;).

BTW: Something else we might consider is to remove the countries geojson out of the repo and provide it as external URL. So if GH is configured to use it, it could simply download it (similar to elevation data). That way we could provide the full and very exact country bondaries.

**Comment by michaz** [comment]
> BTW: Something else we might consider is to remove the countries geojson out of the repo and provide it as external URL. So if GH is configured to use it, it could simply download it (similar to elevation data). That way we could provide the full and very exact country bondaries.

+1

**Comment by karussell** [comment]
> That way we could provide the full and very exact country boundaries

@boldtrn it might mean a slow down for the "is-in-polygon" checks as we currently do this (or a bigger spatial index when using a 'proper geometry lib'). Would you mind to compare the import times?

**Comment by boldtrn** [comment]
> @boldtrn it might mean a slow down for the "is-in-polygon" checks as we currently do this (or a bigger spatial index when using a 'proper geometry lib'). Would you mind to compare the import times?

Not a problem at all. I can do this. Generally speaking, as the data is about 10 times as big, the is in polygon check will take 10 times as long. The ray casting algorithm does a simple intersection check for every edge, so it should scale well enough. As the in polygon check only happens for border tiles, the impact shouldn't be too big. But I can run a couple of measurements to make sure that it actually behaves like that.

**Comment by boldtrn** [comment]
Ok, I did a quick speed comparison for importing Germany.

With the current master and the minified geo.json it took 8:50 minutes until the server started.
Using the original geo.json it took 14:23. As I could not believe the result, I reran it with a similar result.

When looking closer the time consumption is mostly created by way parsing, which makes sense. With the minified geo.json it takes 3:08 minutes to parse the ways. With the original geo.json it takes 8:38.

**Comment by michaz** [comment]
https://www.jasondavies.com/simplify/koch/

**Comment by otbutz** [comment]
Fixed by #2188
