### ISSUE TITLE
Instructions: Missing instruction when turning onto road with separated one way lanes

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#1048]
We do not show turn instructions if the turn we are currently performing is the only valid turn. This is very useful in a lot of situations to remove unnecessary and misleading instructions. In rare cases this leads to missing instructions. Here is an example:

https://graphhopper.com/maps/?point=52.508392%2C13.326287&point=52.509456%2C13.325692

**Comment by boldtrn** [comment]
Should we instead of checking all reachable roads, check all surrounding roads? We will see more instructions, but maybe it's better to show more instructions than missing one?

This is also important for generating a u-turn instructions as currently proposed in #1073.

**Comment by karussell** [comment]
Probably we should take into account oneways like here, but considering all ways might be not so good. Assume there is a junction or roundabout with foot-only ways which could produce confusing instructions for car.

**Comment by boldtrn** [comment]
Yes I would only use roads that are accessible by that encoder.

**Comment by boldtrn** [comment]
@karussell in #1252 provided some more examples where this happens. Relevant for this issue are only the first two red circles.

With the improved instructions I would have expected instructions at the red circles in [this route](https://graphhopper.com/maps/?point=42.507034%2C1.531906&point=42.509581%2C1.532421&layer=OpenStreetMap) in Andorra:

 1. left
 2. right

![missing-instructions](https://user-images.githubusercontent.com/129644/34416877-e382327e-ebf5-11e7-999c-300be3398f6b.png)
