### ISSUE TITLE
Allow decoupling of normal graph weights when using CH

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1067]
When edge weights update then CH still uses them although shortcuts are not updated. So after an update a recalculation of the shortcuts is necessary **or** a separate storage of the base graph edge weights is necessary. The last option requires more RAM (~4bytes*edges) but could also speed up CH routing as the Weighting.calcWeight method must not be called and instead something like the edge.getWeight could be used where a frozen value is stored.

See discussion [here](https://discuss.graphhopper.com/t/estimated-ram-needed-to-instantiate-two-graphhoppers-simultaneously/1939) and related to #240.

**Comment by easbar** [comment]
Another (big I think) advantage of a separate storage for the base graph is that we can disconnect edges leading to or coming from lower levels, but this requires not only a separate storage for the weights, but rather for the edge connection information (nextA/nextB).

**Comment by karussell** [comment]
Yes, this would be interesting. For a world wide graph caching the weights would add 0.5GB (per CH profil as we have around 100M edges) to currently 6-8GB and having nextA+nextB would add 3*0.5GB, which might be worth it if the speed is >20% (which tests indicates it is)

**Comment by karussell** [comment]
Can we close here?

**Comment by easbar** [comment]
> When edge weights update then CH still uses them although shortcuts are not updated.

Do we even update edge weights anywhere? 

> Another (big I think) advantage of a separate storage for the base graph is that we can disconnect edges leading to or coming from lower levels, but this requires not only a separate storage for the weights, but rather for the edge connection information (nextA/nextB).

We already did this, but only to some extent as we learned that the combined storage also has some benefits.

As far as I am concerned we can close here yes.

**Comment by boldtrn** [comment]
> Do we even update edge weights anywhere?

Would be a really cool feature for stuff like live traffic 👍  But I think we are dreaming about this for some years now :)

**Comment by karussell** [comment]
> Do we even update edge weights anywhere?

Not anymore. We had an endpoint for this purpose once, but we removed it. So the mistake could be done only if manually implemented, but then the responsibility would not be on our side and one needs to update the CH preparation.
