### ISSUE TITLE
Issue with Parameter Flatting and Heading

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#1072]
Currently, there is a bug in JS. If you pass a heading, it is converted to an array in the `url.js#mergeParamIntoObject`. In `GHRequest#flatParameter` we recognize this as array but we run into an infinite loop, because we always pass an array into the flatParameter method again. When fixing this, the parameter gets flatted in the form `heading.0=123`. Which is not recognized by the server. 

I am not entirely sure what we should do about this. Obviously the issue was introduced due to the flattening. We could create a special rule to flat the heading differently or we could try to change the handling of the heading parameter on the server side.

The bug was introduced here: https://github.com/graphhopper/graphhopper/commit/02a10a96493b0a3918fea28cbc5efd6c3e043b8d#diff-fc1dc9e1722e4b003037f95e5f87921aR223

I think the line should be:
`url += this.flatParameter(key + "."+ keyIndex, objKey);`

But then we would pass `heading.0=123` to the server, which is not recognized.

**Comment by karussell** [comment]
We should do the same like we do for "point" as it works there too I think and is also an 'array'. Will have a look into it...

**Comment by karussell** [comment]
`point` worked as it was a special case (not in api_params) but when I just fix the flatParameter method it works for me. See my PR
