### ISSUE TITLE
Bug in LMApproximator?

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1083]
[This example](https://graphhopper.com/maps/?point=45.57928%2C9.15844&point=45.580471379265035%2C9.16833400748146&vehicle=racingbike&ch.disable=true) results in a server error: 

```
java.lang.IllegalStateException: At least one direction of edge (213228906 129526659-130331358) should be accessible but wasn't!
        at com.graphhopper.routing.lm.LMApproximator.<init>(LMApproximator.java:99)
        at com.graphhopper.routing.lm.PrepareLandmarks.getDecoratedAlgorithm(PrepareLandmarks.java:160)
        at com.graphhopper.routing.lm.LMAlgoFactoryDecorator$LMRAFactory.createAlgo(LMAlgoFactoryDecorator.java:263)
        at com.graphhopper.routing.template.ViaRoutingTemplate.calcPaths(ViaRoutingTemplate.java:111)
        at com.graphhopper.GraphHopper.calcPaths(GraphHopper.java:1048)
```

This route fails for `mtb` and `racingbike` but strange enough it works for `bike`!? (If the opposite I would have a hint what goes on ;))

Somehow the location index selects an edge which is not allowed being used for graph traversal or something.

**Comment by karussell** [comment]
Hi @ratrun it looks like this was edited from you :)

https://www.openstreetmap.org/way/484824850#map=17/45.58215/9.16874

I guess the problem is maxspeed=0, normally speed=0 should result in inaccessibility while the import

**Comment by karussell** [comment]
This issue is highly related to #831. So if #831 is fixed, this will be fixed two as another start or end edge will be selected.

**Comment by boldtrn** [comment]
I just found a similar issue for car.

This [way](https://www.openstreetmap.org/way/290775580#map=19/47.91673/8.63603&layers=D) has `maxspeed:forward=1`, which results in a similar exception for cars (not for the hosted API). Without LM (speed or flexible mode) the way is seen as inaccessible, while with LM it will result in ```java.lang.IllegalStateException: At least one direction of edge (745 405-509) should be accessible but wasn't!```.

While importing, GraphHopper will set access=false and speed=0 for this edge via `AbstractFlagEncoder#setLowSpeed`.

During the LM preparation, the weight is correctly calculated as Double.Infinitive. In the LMApproximator the Weight is calculated correctly as Infinite. So I am not sure if the exception itself is needed?

If I remove these lines:
``` 
if (reverseWeight >= Integer.MAX_VALUE)
                        throw new IllegalStateException("At least one direction of edge (" + edge + ") should be accessible but wasn't!");
```

GraphHopper behaves the same for LM as for the speed and flex mode. Also all tests still succeed.

Is there a reason for these lines or could we simply remove them?

**Comment by karussell** [comment]
> Is there a reason for these lines or could we simply remove them?

If the weights in both directions is infinity then one of the query nodes is not accessible which should result in a "path not found" but currently would result in an exception in the Weighting class that the edge is accessible although speed is 0. So the real fix is #831.

**Comment by boldtrn** [comment]
But this is true for all three different modes, CH, hybrid, and flex? Also we throw an exception anyway, wouldn't it make more sense to throw it for all three modes at the same point in the code?

If not, I think we should write a test for this so that we cannot simply uncomment this line, if it's important :). Maybe I am missing something here?

**Comment by karussell** [comment]
I think I wrote this exception because I had this problem once and it was hard to trace back to this place. I don't think we should write a separate test but we should also not remove it until #831 is fixed.

**Comment by karussell** [comment]
Closing in favour of the nicely numbered #1234 ;)
