### ISSUE TITLE
link is broken 

### ISSUE THREAD

**Issue by jsroyal** [graphhopper/graphhopper#1089]
Changelog link is [broken](https://github.com/graphhopper/graphhopper/blob/0.9/core/files/changelogs.txt)
Please fix it.

**Comment by karussell** [comment]
Where do you find this link?

**Comment by jsroyal** [comment]
In the docs of the readme file.
![image](https://user-images.githubusercontent.com/10773353/27078575-be924bec-5051-11e7-8fe5-aab9efaf0baf.png)

**Comment by karussell** [comment]
Done
