### ISSUE TITLE
reader-osm pom should use test scope for slf4j-log4j12 and log4j: it's up to the user to chose logging implemenation

### ISSUE THREAD

**Issue by mlarue** [graphhopper/graphhopper#1092]
Hi,

I think there should not be a compile/runtime dependency to a logging implementation in https://github.com/graphhopper/graphhopper/blob/master/reader-osm/pom.xml

Please also look at: https://github.com/graphhopper/graphhopper/issues/250

**Comment by karussell** [comment]
Ah, yes. We need to change this also in reader-gtfs & reader-shp. Maybe you can provide a PR?
