### ISSUE TITLE
Unstable docs need to update

### ISSUE THREAD

**Issue by jsroyal** [graphhopper/graphhopper#1096]
I see both the docs are the same content and also in the change log do not mention about it.

**Comment by karussell** [comment]
What do you mean?

**Comment by jsroyal** [comment]
This is stable version
>0.9.0 latest stable: announcement, docs, zip, Android APK

It is updated

>unstable: docs, zip, Android APK

But the change log and content are same

**Comment by karussell** [comment]
Still do not understand what you are referring to. Do you mean commit messages or documentation entries or what exactly?

**Comment by jsroyal** [comment]
>documentation entries 

Is there any diff docs content? 
Means update docs or same entry which is the previous version 0.9.
Still not then ..
