### ISSUE TITLE
test case vehicule access restriction seems not to be taken into account

### ISSUE THREAD

**Issue by serpico** [graphhopper/graphhopper#1097]
For this [routing](https://graphhopper.com/maps/?point=Rue%20du%20G%C3%A9n%C3%A9ral%20Leclerc%2C%2076960%2C%20Notre-Dame-de-Bondeville%2C%20France&point=49.434377%2C1.092957&locale=en-us&vehicle=car&weighting=fastest&elevation=true&use_miles=false&layer=OpenStreetMap) event though cars are not allowed through [Avenue Champlain](http://www.openstreetmap.org/way/81568424#map=18/49.43401/1.09244) graphhopper advise me to take it.
Thanks

**Comment by karussell** [comment]
Thanks a lot. This is a bug!

**Comment by karussell** [comment]
Ah. No. The problem is access=no but motor_vehicle=designated, so at the end the car is allowed
