### ISSUE TITLE
bike routing uses blocked bridge

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1098]
see this route for `bike` https://graphhopper.com/maps/?point=51.130653%2C7.025601&point=51.129593%2C7.024748&vehicle=bike

and this detour which is only used for `foot`

https://graphhopper.com/maps/?point=51.130653%2C7.025601&point=51.129593%2C7.024748&vehicle=foot

The `bicycle` access is `no` for both bridges

http://www.openstreetmap.org/way/27224191
http://www.openstreetmap.org/way/501124295

**Comment by karussell** [comment]
For the 'hike' encoder there is a bug I have already fixed, see commit.

But the problem is the tagging for bike. Because `bicycle=no` is kind of opposite to `highway=cycleway`, see #870. Would you mind to have a look at this @ratrun? See your comment 'Sensless tagging: JOSM does create a warning here. We follow the highway tag' in the [tests](https://github.com/graphhopper/graphhopper/blob/master/core/src/test/java/com/graphhopper/routing/util/BikeFlagEncoderTest.java#L303). What about if there is a construction on the cycleway? Is there a special construction tagging that we already support and should be used here?

**Comment by karussell** [comment]
If there is a contruction it should be `highway=construction` and so this tagging does indeed make less sense. Not a bug IMO.

**Comment by karussell** [comment]
Reading more about this a road under construction could be tagged with 
`access:conditional=no @ (from-to)` and so we can get `highway=cycleway` and `access=no` or `bicycle=no`

**Comment by ratrun** [comment]
Sorry, I missed this issue so far. I did now a small survey with overpass for `highway=cycleway` and `access=no` and on the few usages there the creators seem to expect all kind of meanings. Based on this I agree with you that our implementation for using this tag combination is not a bug. Construction should be tagged according to https://wiki.openstreetmap.org/wiki/Key:construction with `highway=construction` and `construction=cycleway`. I therefore believe that this issue can be closed.
