### ISSUE TITLE
SpatialIndex not created on Import

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#1099]
I just saw that the SpatialIndex is not created when using the import function instead of the web function.

Obviously the reason for this is that the SpatialIndex creation part is in the web module but Import does not use the web module.

A reasonable solution could be to move the package `com.graphhopper.spatialrules` to the tools. We would further need to create a dependency from web to tools.

Another solution could be to move the package `com.graphhopper.spatialrules` to the core, which would result in no additional dependencies.

WDYT?

**Comment by karussell** [comment]
> Another solution could be to move the package com.graphhopper.spatialrules to the core, which would result in no additional dependencies.

ok, if this is possible then this is probably the best solution. Another solution could be to move the Import class into the web module

**Comment by boldtrn** [comment]
> ok, if this is possible then this is probably the best solution. Another solution could be to move the Import class into the web module

This might be a good solution as well. We could try to completely reuse the GraphHopperModul code? 

Not sure if somebody gets issues because the import suddenly requires the web module and all its dependencies?

**Comment by michaz** [comment]
> Another solution could be to move the package com.graphhopper.spatialrules to the core, which would result in no additional dependencies.

Also sounds good to me.

I kind of like the web/tools distinction: For me (and for some other people, I think I saw this in some Apache project..) "tool" implies "things with main methods which I can run", and "web" implies "goes into some web framework which runs it". And both means "do not include me, I am not a library, the library is somewhere else".

**Comment by devemux86** [comment]
> I kind of like the web/tools distinction

:+1: 
Better avoid different modules / dependencies mix as much as we can.
BTW  `core` got lately fatter causing problems on Android dex size. :slightly_smiling_face:

**Comment by michaz** [comment]
> BTW core got lately fatter causing problems on Android dex size.

Tell me more.. You want to get rid of JTS again? Can you roughly estimate how important that would be? ,-) Because JTS _not_ being there would mean hand-rolled geometry processing popping up again, which I'm militantly against.

Maybe at some point we need another split into _real_ core, and "more library stuff which isn't quite core".

**Comment by michaz** [comment]
> which I'm militantly against

.. but other's don't agree that much. Just wanted to point out the controversy. ,-)

**Comment by boldtrn** [comment]
> .. but other's don't agree that much. Just wanted to point out the controversy. ,-)

Don't get me wrong, I totally agree here, if we need more than just point in polygon :).

**Comment by devemux86** [comment]
> Tell me more.. You want to get rid of JTS again?

I meant the mandatory JSON (3) dependencies.
Would be nice to be optional, so that regular routing clients won't have to include them.
e.g. I integrated recently GeoJSON tile decoding in VTM via extra [vtm-json](https://github.com/mapsforge/vtm/issues/367) module.

**Comment by michaz** [comment]
> I meant the mandatory JSON (3) dependencies.

Hmm, I may have tomatoes on my eyes, but:

<img width="420" alt="screen shot 2017-06-28 at 13 27 29" src="https://user-images.githubusercontent.com/520916/27634962-a441ad68-5c05-11e7-8277-e775aa07c760.png">

The last four are test-only, and the jackson-thing upstairs is just annotations.

**Comment by karussell** [comment]
Strange, somehow we seem to get databind into it:

![deps](https://user-images.githubusercontent.com/129644/27635595-f5557002-5c07-11e7-8d65-fdd5bdfab263.png)

**Comment by karussell** [comment]
Sorry. It should be just annotations which is just 54kb.

The jts is a bit big (750kb) but I wouldn't roll our own solution, we could try to reduce this with maven shade or something but in days where apps are hundreds of MB I wouldn't concentrate on this (yet) :)

**Comment by devemux86** [comment]
> Strange, somehow we seem to get databind into it

GraphHopper requires client to have (other in diagram are optional):
```gradle
compile 'com.carrotsearch:hppc:0.7.2'
compile 'com.fasterxml.jackson.core:jackson-annotations:2.8.4'
compile 'com.fasterxml.jackson.core:jackson-core:2.8.4'
compile 'com.fasterxml.jackson.core:jackson-databind:2.8.4'
compile 'com.vividsolutions:jts:1.13'
compile 'org.slf4j:slf4j-api:1.7.25'
```

**Comment by karussell** [comment]
> GraphHopper requires client to have (other in diagram are optional):

The other two jackson deps are test dependencies, see the pom: https://github.com/graphhopper/graphhopper/blob/master/core/pom.xml#L69-L74

Or will GH break at runtime without them?

**Comment by devemux86** [comment]
Sorry, `directions-api-java-client` requires the 3 jackson, false alarm (edited above)! :slightly_smiling_face:

**Comment by michaz** [comment]
> Sorry, directions-api-java-client requires the 3 jackson, false alarm (edited above)! 

Aha, but also good to know that that's an issue. Thx. I guess Android libraries are expected to use Android-platform facilities wherever possible, right?

**Comment by devemux86** [comment]
There is the famous Android [64K reference limit](https://developer.android.com/studio/build/multidex.html) that makes dependencies there very important to watch. Workarounds exist, but each with its own impact.
Also Android [org.json package](https://developer.android.com/reference/org/json/package-summary.html) is not so advanced as Gson or Jackson.

**Comment by michaz** [comment]
> Also Android org.json package

Perfect, now I get where the org.json stuff came from.
