### ISSUE TITLE
app crashes

### ISSUE THREAD

**Issue by jasmeetsahni** [graphhopper/graphhopper#1105]
on click of ok button app crashes. can anyone suggest me what can be the problem

**Comment by devemux86** [comment]
I suppose it's about the Android sample?
Better discuss first in [forum](https://discuss.graphhopper.com/) with more information, like the exception log.

**Comment by karussell** [comment]
Please include a step by step guide what you did, including the GH version and Android version.

**Comment by jasmeetsahni** [comment]
i simply run this graphhopper android sample example . it is showing europe cities. can anyone tell me how could i add some other country names to list so as to download their maps in this app
