### ISSUE TITLE
About coding style

### ISSUE THREAD

**Issue by tianyin** [graphhopper/graphhopper#1109]
I read `.github/CONTRIBUTING.md` and https://github.com/graphhopper/graphhopper/issues/770, and it states that the line width is required to be `100` chars. 

However, this requirement is largely violated in the current code base.

I run `CheckStyle` with `LineLength` as `100` and there are `1056` violations 
It seems that `120`-char is more accepted.
(running `CheckStyle` with `LineLength` as `120` reduces #violations to `353`).

A more general question is "shall we use `CheckStyle` or something alike to enforce the code style as a part of integration testing? 
Relying on the description in `CONTRIBUTING.md` seems not very effective.

btw, I see the use of `CheckStyle` being commented out in the current `pom.xml`.
Is there a reason that we intentionally try to avoid `CheckStyle`?

Thanks!

**Comment by karussell** [comment]
> It seems that 120-char is more accepted.

Ok, lets change the contributing guide to 120 :)

> shall we use CheckStyle or something alike to enforce the code style as a part of integration testing

Yes, would be nice. Especially with findbugs :)

> Is there a reason that we intentionally try to avoid CheckStyle?

I just didn't get it working ;) - maybe you can make it working as part of the integration test? And with findbugs it would be even more cool :)

**Comment by tianyin** [comment]
@karussell for sure! I can create a PR for the `checkstyle.xml` configs (and the corresponding `pom.xml`).
The only problem is that it will create some violations (so we perhaps need to refactor some of the code).

For findbug, I see you've already integrated it in the current `pom.xml`.
```
<plugin>
  <groupId>org.codehaus.mojo</groupId>
  <artifactId>findbugs-maven-plugin</artifactId>
  <version>3.0.4</version>
</plugin>
``` 
What exactly do you need?

**Comment by karussell** [comment]
> The only problem is that it will create some violations (so we perhaps need to refactor some of the code).

Yes, I can have a look at it then.

> What exactly do you need?

That it will be executed when the integration tests run and maybe a few rules adapted as they don't make much sense or are not so important

**Comment by ammagamma** [comment]
I added a basic checkstyle & findbugs configuration here:
https://github.com/ammagamma/graphhopper/tree/issue_1109
Right now there are 361 checkstyle violations (it only checks for the line length to be 120 at the moment).
Findbugs finds 5 bugs with severity 7 or lower (lower means more severe) and for demonstration I configured `findbugs-exclude.xml` to exclude some of them. Rules can be excluded by rule type or only for certain classes/methods etc.
Both tools are configured so they run in the maven integration-test phase and fail the build if there are any violations. 
Right now we can make `mvn install` run successfully for example if we adjust the line length limit to 500 (yes there are some very long lines) and if we set the `maxRank` configuration of the findbugs maven plugin to 4 (which means it only checks for the 'scariest' bugs). 
To use more strict settings some of the current code needs to be adjusted...

**Comment by karussell** [comment]
Cool, thanks!

**Comment by karussell** [comment]
Would you mind to create a pull request with this and a version that does not break the build? Then we can make the rules tighter, step by step and improve the code accordingly (?)

**Comment by karussell** [comment]
This is now integrated although I don't find the checkstyle plugin too useful at the moment. Have not adapted the contributing guide, so over time we should migrate to the 100 columns but accept more like 120 for now.

Closing here.
