### ISSUE TITLE
issue with graphhopper map and Open source code

### ISSUE THREAD

**Issue by jsroyal** [graphhopper/graphhopper#1111]
I would to request to please see through this [link post on discuss](https://discuss.graphhopper.com/t/find-bug-in-graphhopper-map-with-different-fleet/2180) 
I have been tested two three-times same thing happing.

**Comment by jsroyal** [comment]
@karussell could you please ref. why it is closed.

**Comment by karussell** [comment]
It was [already said](https://github.com/graphhopper/graphhopper/blob/master/.github/ISSUE_TEMPLATE.md) when you posted the issue *'For general questions or discussion about GraphHopper, please use our forum.'*

**Comment by jsroyal** [comment]
Sorry but I think I already following rule ->  [link post on discuss forum](https://discuss.graphhopper.com/t/find-bug-in-graphhopper-map-with-different-fleet/2180)
