### ISSUE TITLE
Bike should go straight though the park

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1113]
[This route](https://graphhopper.com/maps/?point=51.03454%2C13.771749&point=51.038102%2C13.760977&point=51.04161%2C13.753145&vehicle=bike) consists of bicycle=yes and highway=pedestrian and should be chosen directly (?)

**Comment by Nakaner** [comment]
The following only applies to Germany:

`highway=footway` + `bicycle=yes` (not `designated`) is used to indicate the German traffic sign 239 + 1220. This means that you may use this way as a cyclist but in case of an accident with a pedestrian you are always the looser and your speed limit is walking speed (for routing engines: 7 km/h). Cyclists are not required to use such ways if they are parallel and next to a road. Ask your local cycling activists for more information. :-)

But, to be honest, I doubt that all `highway=footway` + `bicycle=yes` are correctly tagged. :-)

**Comment by karussell** [comment]
But something is wrong here: with the via point it takes longer with bike than by foot which makes only sense for a very fat bike ;)

**Comment by ratrun** [comment]
The way is tagged as `highway=pedestrian` + `bicycle=yes` without a `segregated=yes`. We classify the way with `speed=PUSHING_SECTION_SPEED` and `priority=AVOID_IF_POSSIBLE`. I think that this is OK for that combination alone. But currently we do not consider the set tags `width` and `maxspeed`.

**Comment by karussell** [comment]
Thanks for investigating this. And do you think that the speed for pushing section should be smaller than with walking?

**Comment by ratrun** [comment]
The pushing section speed is defined as 4 km/h, while the walking speed is defined as 5 km/h. The argument here is that there are occasions (e.g. uphill) where you really are slower compared between pushing a bike and to walking. But maybe we should  better define these values with the same speed.

**Comment by karussell** [comment]
I think we can close here: the detour is faster with a bike and difference in walking speeds make sense.
