### ISSUE TITLE
issue with private=access on ferries

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1122]
We got a bug report via email:

> I'm curious how access=private is handled in Graphhopper because when
trying to use your engine on OpenStreetMap I was routed via a ferry
(which at that time was unspecified). However, after adding a tag saying
it is access=private I am still routed over it.
> See: https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=64.4893%2C19.3299%3B64.5037%2C19.2600#map=13/64.4941/19.2954
> and the ferry way: https://www.openstreetmap.org/way/221099681

**Comment by boldtrn** [comment]
Seems to be related to #1119
