### ISSUE TITLE
Map disappears after a while of running the android app

### ISSUE THREAD

**Issue by omartaha1003** [graphhopper/graphhopper#1125]
Hello dears,

I have an issue where I developed an android app using graphopper, just as menssioned here [https://github.com/graphhopper/graphhopper/blob/master/docs/android/index.md](url), it seems to work fine on multiple devices, but when I run it on my tablet, which I want to run the app on, first the app starts normall, but after a while the map disappears, and white screen shows, I checked the console on android studio, I didn't see error or exceptions, and I don't know how to debug this issue, the android version on the tables is 4.4.2
when I closes the application and starts it again, the map shows again, and disappears again the same.

This is a screenshot when the app runs normally on the tablet:
![screenshot1](https://user-images.githubusercontent.com/12015687/28813362-ac0f0016-76a1-11e7-8dcf-a9e07a86e4fc.png)

And this is how the map disappers:
![screenshot2](https://user-images.githubusercontent.com/12015687/28813379-b5c9e652-76a1-11e7-9249-d89942a9608d.png)

This is the piece of code I'm using in my app:

`

     org.oscim.android.MapView mapView = (MapView)findViewById(R.id.map);
      mapView.map().layers().add(new MapEventsReceiver(mapView.map()));

     String currentArea = "israel_and_palestine";

     File mapsFolder = new 
       File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS),
				"/graphhopper/maps/");

		final File areaFolder = new File(mapsFolder, currentArea + "-gh");

		MapFileTileSource tileSource = new MapFileTileSource();
		tileSource.setMapFile(new File(areaFolder, currentArea + ".map").getAbsolutePath());
                tileSource.setPreferredLanguage("ar");
		 l = mapView.map().setBaseMap(tileSource);
                 mapView.map().setTheme(VtmThemes.DEFAULT);
	

		mapView.map().layers().add(new BuildingLayer(mapView.map(), l));
		mapView.map().layers().add(new LabelLayer(mapView.map(), l));

        
`

Any Ideas?

**Comment by devemux86** [comment]
[Topic](https://groups.google.com/forum/#!topic/mapsforge-dev/036jFPLU6Is) in Mapsforge / VTM forum.
