### ISSUE TITLE
block_area does not work if start and/or end are on the same edge

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1127]
See [this route](https://graphhopper.com/maps/?point=50.17016%2C14.63381&point=50.17286%2C14.64287&block_area=50.17147%2C14.63683%2C100&ch.disable=true) vs. [this route](https://graphhopper.com/maps/?point=50.169037%2C14.631515&point=50.17393%2C14.64735&block_area=50.17147%2C14.63683%2C100&ch.disable=true) where the block_area parameter is identical and so it is expected that the point in the middle of the road section should be avoided in both cases. Or properly document the limitation of block_area.

**Comment by boldtrn** [comment]
Thanks for reporting this, will investigate what's happening and if we can fix it.

**Comment by boldtrn** [comment]
Ok, so I debugged this issue a bit. Currently, we find edges in the graph using the LocationIndex. When we place a waypoint on an edge, we don't traverse on that edge, but we use a VirtualEdge, which is not included in the LocationIndex.

A possible solution would be to get all QueryResuls from the QueryGraph and check if we found a blockingEdge here, if yes, we have to find the corresponding VirtualEdges, which should be possible. Then we could check if the blocked point/circle/BBox intersects with this edge, if yes we block the edge.

I outlined this approach [here](https://github.com/graphhopper/graphhopper/compare/master...boldtrn:debug_1127?expand=1). I don't like the added overhead, but right now I don't know a better solution? Also I think that the 10 meters are a bit heuristic and can match more than one VirtualEdge, which sometimes might be not ideal.

**Comment by pa5cal** [comment]
> See [this route](https://graphhopper.com/maps/?point=50.17016%2C14.63381&point=50.17286%2C14.64287&block_area=50.17147%2C14.63683%2C100&ch.disable=true) vs. [this route](https://graphhopper.com/maps/?point=50.169037%2C14.631515&point=50.17393%2C14.64735&block_area=50.17147%2C14.63683%2C100&ch.disable=true) where the block_area parameter is identical and so it is expected that the point in the middle of the road section should be avoided in both cases. 

Can't reproduce the described bug. The blocked section is avoided by both routes.

**Comment by karussell** [comment]
> Can't reproduce the described bug. The blocked section is avoided by both routes.

Yes, maybe there was a new junction introduced in OSM but the bug wasn't fixed in GH core.

**Comment by karussell** [comment]
I think this is a duplicate of #1324.
