### ISSUE TITLE
Cannot enable change graph feature from config.properties

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#1132]
Per default, the change graph feature is disabled.

You can enable it by passing `web.change_graph.enabled=true`. The problem is that we call the method `CmdArgs.readFromConfigAndMerge(args, "config", "graphhopper.config");` in the `GraphHopperModule` after the servlets have been set up.

Moving this earlier, breaks the WebTests as they rely on the args. I tried moving the method `CmdArgs.readFromConfigAndMerge(args, "config", "graphhopper.config");` in the `GHServer` class, however the tests failed, as this method probably breaks the references to the args and we cannot specify the port anymore. (Currently we do this after initializing the GHServer in the BaseServletTester).

**Comment by karussell** [comment]
Thanks for finding this, this sounds ugly. Maybe #1108 already fixes this?

**Comment by michaz** [comment]
> Maybe #1108 already fixes this?

Yes, I think it shoud.

**Comment by boldtrn** [comment]
> Did you test this with master or 0.9?

I tested this with the latest master. I would assume that 0.9 should have the same issues?

> Maybe #1108 already fixes this?

This could be very well possible, yes :).

**Comment by karussell** [comment]
> I tested this with the latest master. I would assume that 0.9 should have the same issues?

There were some changes in master that could have introduced this.

**Comment by karussell** [comment]
@boldtrn would you try if this is fixed in recent master? (Please note that this issue was related to #1133)

**Comment by karussell** [comment]
Closing due to major refactoring that mades this likely obsolete. Please reopen if it remains an issue.
