### ISSUE TITLE
"mvn package" does not build with-dep.jar

### ISSUE THREAD

**Issue by justinmk2** [graphhopper/graphhopper#1134]
graphhopper version: 09d5fdaf6963 (but using the latest version of `./graphhopper.sh`).

```
$ ./graphhopper.sh clean
$ ./graphhopper.sh web berlin-latest.osm.pbf
## using java 1.8.0_131 (64bit) from
## using existing osm file berlin-latest.osm.pbf
## building graphhopper jar: tools/target/graphhopper-tools-0.9-SNAPSHOT-jar-with-dependencies.jar
## using maven at /usr/local/Cellar/maven/3.5.0/libexec
## now web. JAVA_OPTS=-Xmx1000m -Xms1000m -server
Error: Unable to access jarfile ./web/target/graphhopper-web-0.9-SNAPSHOT-with-dep.jar
```

Notice that `./graphhopper.sh web` calling the `package` maven-phase, like this:

    execMvn --projects web -am -DskipTests=true package

AFAICT the `install` maven-phase is required to generate the `*-with-dep.jar`.

I'm not a maven expert, is there some phase other than `install` that can be called to generate the `*-with-dep.jar` ? Seems weird to need to "install" in order to get artifacts. Is a change needed to the `pom.xml` configuration so that `package` will generate the `*-with-dep.jar` ?

More generally: going forward, does `graphhopper.sh` continue to be the recommended way of working with graphhopper?

Thanks.

**Comment by karussell** [comment]
I'm not sure what your problem is here (`mvn clean package` builds all necessary artifacts and so does the `graphhopper.sh` script). Also questions should go to [our forum](https://discuss.graphhopper.com/)

> More generally: going forward, does graphhopper.sh continue to be the recommended way of working with graphhopper?

To develop with graphhopper sources the recommended way is a Java IDE like Netbeans or IntelliJ

**Comment by karussell** [comment]
> graphhopper version: 09d5fda (but using the latest version of ./graphhopper.sh).

We only support the latest master or a previous stable version. No mix or something, although I'm not sure what the problem could be here.
