### ISSUE TITLE
avoid manual parsing in GraphHopperWeb

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1137]
Make it possible to just write:

GHResponse res = objectMapper.readValue(str, GHResponse.class);

and this will also simplify or remove the code in SimpleRouteSerializer.

(We need further custom serialize code for the polyline encoding stuff)

**Comment by michaz** [comment]
What is the general plan for the client? [Elsewhere](https://github.com/graphhopper/graphhopper/issues/1104) I was suggesting to remove it, but only because it's duplicated in another project.

In general, it can of course be a good idea to have the (same-language) client in the same repository, precisely because serialization code and representations can be shared. Dropwizard recommends it. It should go into a different JAR, of course, so rather than being in "web", it should be in a "client" module. Client code can then include the client JAR and that's it..

So maybe we move the "hand-coded" client over here? In general?

**Comment by karussell** [comment]
Yes, this might be a good solution to move the hand-coded into a new `client` maven module. The only problem is that we would either have to split the hand-coded matrix part and keep it externally or put it here, which would mix the open source with the API which I would like to avoid to reduce confusion.

**Comment by karussell** [comment]
> which would mix the open source with the API which I would like to avoid to reduce confusion.

Hmmh, this is kind of 'violated' already as the GraphHopperWeb points to the commercial offering per default. So moving the hc client into this repo sounds good to me and we can finally avoid duplicate code.

**Comment by michaz** [comment]
Related: What is the plan for the Swagger spec? Is it just a side-project, or do we want to make it more authoritative by reviewing it, adding documentation and perhaps eventually generate the official API docs from it?

**Comment by karussell** [comment]
> Is it just a side-project

Definitely not. Why do you think so?

> Related: What is the plan for the Swagger spec?

The swagger spec and clients generated are already working. Also there is a bit documentation for this already inside the spec. But a few bigger issues remain (limitation of either the codegen or swagger spec itself) like https://github.com/graphhopper/directions-api-clients/issues/1

**Comment by michaz** [comment]
> Definitely not. Why do you think so?

Just asking. For example, it does not generate the official API documentation, but duplicates it.

**Comment by michaz** [comment]
> So moving the hc client into this repo sounds good to me and we can finally avoid duplicate code.

I could do that on the Dropwizard-PR. Would fit nicely there because of close connections to "doing more with Jackson" and "sharing representations".

**Comment by karussell** [comment]
> I could do that on the Dropwizard-PR. Would fit nicely there because of close connections to "doing more with Jackson" and "sharing representations".

I'm more for smaller PRs :) maybe a second PR based on the Dropwizard branch?

**Comment by michaz** [comment]
Okay, sure.

**Comment by boldtrn** [comment]
I thought the approach would be the other way around? Move the GraphHopperWeb file into the hc part and use this as a test dependency? The GraphHopperWeb is only used for testing purposes.

**Comment by karussell** [comment]
The problem then will be that we have a circular dependency of the repositories: test web module (GH repo) -> hc client (other repo) -> core (GH repo) which might be too complex (?)

**Comment by michaz** [comment]
Depndencies aside, the argument for having client and server in the same repository is that they can (easily) share the same representation objects and serialization/deserialization code.

What are the arguments for having it in a separate repository?

"A user may only want the client" -- okay, but they will usually use a Maven dependency, not check out the source code.

**Comment by michaz** [comment]
Note: I _also_ really like the Swagger stuff and auto-generated clients, but I think _those_ are a different story, and would perhaps be better off if they are in their repository alone, without the "hand-coded" stuff. The whole repository could basically be auto-generated by Swagger.

**Comment by boldtrn** [comment]
> What are the arguments for having it in a separate repository?

Well it depends, if we put the client into it's own package, I don't see a good reason against this, besides some users might be a bit confused that suddenly the location of the client changed. If we leave the client (GraphHopperWeb) in the web client the downside is that anybody using the client would end up with all the dependencies of the web module.

> I also really like the Swagger stuff and auto-generated clients, but I think those are a different story, and would perhaps be better off if they were in their repository alone, without the "hand-coded" stuff. That whole repository could basically be auto-generated by Swagger.

Yes, I am fine with that. We should also note that right now the hc client cannot solve all functions of the API (e.g. geocoding).

**Comment by devemux86** [comment]
> the downside is that anybody using the client would end up with all the dependencies of the web module.

Agreed that wouldn't be nice.

**Comment by michaz** [comment]
> Agreed that wouldn't be nice.

Yeah, it would go in its own module, of course.
