### ISSUE TITLE
add more path details

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1140]
already possible:

 - [x] street_name (important for navigation)
 - [x] time (nice for ETA predictions e.g. if parts of the route were already travelled)
 - [x] edge_id or traversal_key

later when more stuff is stored as edge properties:

 - [x] max_speed (very important for navigation)
 - [x] surface
 - [x] highway type ("road_class")
 - [x] ferry,toll,.. ("road_environment"?)
 - [x] weight, height, ...
 - [ ] inner vs. outer city

**Comment by boldtrn** [comment]
Adding the Street Name is an excellent idea :+1:

**Comment by karussell** [comment]
(The idea came to me while navigating with locus maps (via graphhopper) from @asamm :))

**Comment by karussell** [comment]
Will keep this open at least for highway type (incl. ferry?), toll, fords vs. tunnel vs. bridge (transport_environment?), surface and max_speed

**Comment by sebalis** [comment]
How about opening hours for gates? Remembering https://twitter.com/SebaLis/status/681440331754270720 :-)

**Comment by carlos-mg89** [comment]
I just bumped into this matter when searching for surface information on each segment. I guess that not many progress or none has been done in this matter. However, I'd like to ask if anyone knows a way of obtaining surface information. I'd like to put some time into this matter, but would need a bit of information here. Perhaps it's quite complex to include this data in GraphHopper, but it would be wonderful.

**Comment by karussell** [comment]
There is great of progress happening here but unfortunately not yet linked: https://github.com/graphhopper/graphhopper/pull/1548

**Comment by carlos-mg89** [comment]
That's nice @karussell ! Thank you for pointing me out to the WIP :) Looking forward!

**Comment by karussell** [comment]
Most of them are implemented now. Further details will get their own issue.
