### ISSUE TITLE
Memory usage seems high after long time without restart

### ISSUE THREAD

**Issue by HarelM** [graphhopper/graphhopper#1143]
I'm running graph hopper on my server using the jetty servlet and I see that the memory consumption of GH is around 3Gb after 10 days for working without restart.
When starting the process the memory (after loading the graph) is around 300Mb.
The only request that this server is getting are routing requests.
I have added a rebuild servlet and thought that the rebuild is the cause of the memory leak but I have disabled the rebuild and I still see high memory consumption.
It might be a small memory leak but still...
Please let me know if there's anything I can do to help debug it, I'm not a Java wiz but with proper instructions I can probably help some...

Using GH 0.10-Shapshot from around June.
java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)

**Comment by karussell** [comment]
How do you measure "memory consumption"? Do you get any exceptions? If not, then this is highly likely because just no GC kicks in. Try to reduce the memory usage to a smaller value and you'll probably see that the GC kicks in and reduces memory usage.

**Comment by HarelM** [comment]
Thanks for the super fast response!
I measure it by looking at the windows' task manager relevant Java process.
Shouldn't the GC kick in once in a while? the process is running for a week+...
I don't get any exceptions, the server is very powerful so I have enough memory for now.
By reducing the memory usage you are referring to the java process flag I should use when running GH 
 (`-Xmx`)?

**Comment by karussell** [comment]
> I measure it by looking at the windows' task manager relevant Java process.

Ok, then it is not really an issue

> Shouldn't the GC kick in once in a while? the process is running for a week+...

This isn't time dependent, just dependent on its config and memory usage etc

> By reducing the memory usage you are referring to the java process flag I should use when running GH (-Xmx)?

Yes. You reserve a certain amount that the JVM can use and will use if request. I suggest exploring the memory usage with a java profiler (yourkit,netbeans) or VisualVM.

**Comment by karussell** [comment]
If it would be a memory leak you'll see that the GC kicks in and despite this the memory usage will increase until the maximum and a memory related exception or error will be thrown (OutOfMemory, GC related etc)

**Comment by HarelM** [comment]
Thanks you very much! 
I'll set the flag and monitor for exceptions and process' memory.
In case I'll see anything special I'll reopen this issue.
