### ISSUE TITLE
Building Android package via maven fails

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1144]
It seems that [since the update](https://github.com/graphhopper/graphhopper/pull/1114) to mapsforge/vtm 0.8.0 we can no longer build the Android demo (at least via maven). The problem is the class clash of two different jts jars: one older 1.13 (from gh-core) and the 1.14 `jts-core` from mapsforge `vtm-jts` - see [this change](https://github.com/mapsforge/vtm/commit/0cd6c48b168aa0df95feab82e54cfb44dc4cde59#diff-d702bdb87f3cb09ed0db9812b12db364).

The cleanest way would be to upgrade to 1.14 for gh-core. @michaz what blocking issues are there to do so? I remember it was GeoJSON related but as mapsforge does also related stuff - maybe @devemux86 can help?

 - [ ] fix dep problem or workaround the issue for now via some dep exclusion
 - [ ] the NetBeans graph dependency viewer shows a clash for `slf4j-api`: 1.7.12 vs. 1.7.21 ... In GH we usually use 1.7.25 and now there is also a more recent `slf4j-android` so we should be able to update this.

BTW: The error message when executing `mvn -P include-android -DskipTests=true clean install` was a bit cryptic:

```
[ERROR] Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.4.3:dex (default-dex) on project graphhopper-android: : MojoExecutionException: ANDROID-040-001: Could not execute: Command = ...
```

Executing the listed command showed me the problem:

```
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/vividsolutions/jts/JTSVersion;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/vividsolutions/jts/algorithm/Angle;
...
```

Excluding one or the other jts library does not fix the problem or causes others.

**Comment by karussell** [comment]
Switching to vtm 0.7.0 did not fix the error. Switching to 0.6.0 causes some other cryptic error message: Uncaught translation error: com.android.dx.cf.code.SimException: signature-polymorphic method called without --min-sdk-version >= 26

Still failing after setting platform to 26 and updating the maven android plugin to 4.5.0. Now I'm confused. Do I really have to setup the Android SDK from scratch everytime there is a problem :( ?

**Comment by karussell** [comment]
Reinstalling the android-sdk didn't help.

**Comment by karussell** [comment]
When executing `./gradlew build` I get the same error about the SimException and min sdk version.

**Comment by devemux86** [comment]
Hmm indeed the build command fails, though the Sample work fine and can run!

FYI
My use on Gradle is to always disable transitive dependencies, wanting to have complete control of what gets in the apps (Android or Desktop).
Doing so with VTM + GraphHopper libs, I have to explicitly declare JTS dependency and works with both 1.13 and 1.14.

So I suppose here Maven still manages somehow to get JTS from some library?

BTW how do you build Android apps with Maven, with [maven-android-sdk-deployer](https://github.com/simpligility/maven-android-sdk-deployer)?

**Comment by karussell** [comment]
> Hmm indeed the build command fails, though the Sample work fine and can run!

How do you normally produce an apk with gradle? Or do you mean that just the sample started via gradle or IntelliJ works fine?

> So I suppose here Maven still manages somehow to get JTS from some library?

I think the clash comes from the different versions of graphhopper-core vs. vtm-jts. There is no other jts involved. But even if I exclude one or the other it does not work.

> BTW how do you build Android apps with Maven, with maven-android-sdk-deployer?

Normally, yes. But I'm open to switch to gradle for the Android demo.

**Comment by devemux86** [comment]
I meant that the Sample "runs" via Android Studio in the emulator or in the device.
When perform a Gradle build, then we see the issue.

So I tested all ways and run + build can work with everyone:

1. Exclude JTS from VTM and remove its explicit declaration, let it come from GraphHopper:
```gradle
    compile('org.mapsforge:vtm-jts:0.8.0') {
        exclude group: 'com.vividsolutions', module: 'jts-core'
    }
//    compile 'com.vividsolutions:jts-core:1.14.0'
```

2. Exclude JTS from GraphHopper and remove its explicit declaration, let it come from VTM:
```gradle
    compile(group: 'com.graphhopper', name: 'graphhopper-core', version: '0.10-SNAPSHOT') {
        ...
        exclude group: 'com.vividsolutions', module: 'jts'
    }
//    compile 'com.vividsolutions:jts-core:1.14.0'
```

3. Exclude JTS from both VTM + GraphHopper and declare one of its versions explicitly:
```gradle
    compile(group: 'com.graphhopper', name: 'graphhopper-core', version: '0.10-SNAPSHOT') {
        ...
        exclude group: 'com.vividsolutions', module: 'jts'
    }
    compile('org.mapsforge:vtm-jts:0.8.0') {
        exclude group: 'com.vividsolutions', module: 'jts-core'
    }
```
and
```gradle
    compile 'com.vividsolutions:jts:1.13'
```
or
```gradle
    compile 'com.vividsolutions:jts-core:1.14.0'
```

**Comment by devemux86** [comment]
I prefer the 3rd method, to clearly see what dependencies each lib introduces.
But since VTM doesn't have issues with JTS 1.13, we can use the 1st solution in GraphHopper sample?

**Comment by karussell** [comment]
Thanks! (For the moment I would also use the 1st solution)

And finally got it working with gradle and also maven.

A further problem in maven qA with the SimException was due to the latest build tools!? After I did:

sdkmanager --uninstall "build-tools;26.0.0"
sdkmanager --uninstall "build-tools;26.0.1"

The maven stuff worked too! And you see the same problem in gradle when you edit build.gradle and set:

```
    compileSdkVersion 26
    buildToolsVersion "26.0.1"
```

**Comment by karussell** [comment]
Found the solution via the commit after this comment https://github.com/groovy/groovy-android-gradle-plugin/issues/145#issuecomment-316052626

**Comment by devemux86** [comment]
Always work with latest Android tools and don't have such issues.
e.g. my tests were with build tools 26.0.1

But didn't send a PR since you told me to not change all the time the Sample when Android advances its versions.

**Comment by karussell** [comment]
> Always work with latest Android tools and don't have such issues.

This is strange as I installed the android sdk and gradle all from scratch :(
I'll keep the build.gradle then with the 26er version


> But didn't send a PR since you told me to not change all the time the Sample when Android advances its versions.

No problem, will commit the necessary changes also to the pom.xml

**Comment by karussell** [comment]
> e.g. my tests were with build tools 26.0.1

BTW: the issue remains if I used 26.0.0 ...

**Comment by devemux86** [comment]
> BTW: the issue remains if I used 26.0.0 ...

Well I recommend to not keep Sample on old Android versions.
The tools advance for a reason, also fixing things besides improvements, so trying to solve issues with old versions only consumes our time? :slightly_smiling_face:

**Comment by karussell** [comment]
Not sure what you mean :) ... for me it does not work for 26.0.1 **and** also not for 26.0.0. Only with 25.0.0 I got it build successfully.

**Comment by devemux86** [comment]
That's very strange, working with 26.0.1 from its start without issues..
Of course with all environment aligned, Android Studio 2.3.3, Gradle 3.3, Android plugin 2.3.3, Android SDK 26 (fully updated), etc.

**Comment by michaz** [comment]
> @michaz what blocking issues are there to do so?

The issue is that two other dependencies (gtfs-lib, and, more importantly, the Jackson bindings for JTS) use JTS 1.13, which in itself is not bad, but they switched from _one_ jar to _several_ jars between them (jts -> jts-core, ... ), which means that Maven doesn't know that one supersedes the other.

So I updated to jts-core 1.14.0 now and excluded the monolithic JTS from the dependencies.

This means that only tests can prevent ClassNotFoundExceptions in case one of the dependencies tries to use something which is in jts but not in jts-core. :-}

But should be fine.

**Comment by karussell** [comment]
Thanks!

It looks like 1.15 is around the corner ([see slide 5 here](http://osgeo.getinteractive.nl/resources/state-jts-2017/)) and if that will be the case I'll ask/help those dependencies to upgrade so we reduce potential license problems when using GH in iOS or Android (due to the LGPL).

**Comment by karussell** [comment]
I'm again getting this problem https://travis-ci.org/graphhopper/graphhopper/jobs/341884687#L1924

@devemux86 is this required? https://github.com/mapsforge/vtm/blob/master/.travis.yml#L20

**Comment by devemux86** [comment]
VTM Travis config line is for installation of Android platform.

GH Travis error is about (again) mixed dependencies in Android dex process. 🙁 
It was fixed at some tools version, let me check that again..

**Comment by karussell** [comment]
Ok, thanks. Excluding helped: https://travis-ci.org/graphhopper/graphhopper/builds/341896715

**Comment by devemux86** [comment]
My local builds work, can you try:
```groovy
implementation('org.mapsforge:vtm-jts:0.9.2') {
    exclude group: 'com.vividsolutions', module: 'jts'
}
```

**Comment by devemux86** [comment]
BTW I integrated JTS (LocationTech) in VTM lately in https://github.com/mapsforge/vtm/issues/484.

**Comment by karussell** [comment]
Yes, good to know. We have a bit problems with used dependencies: https://github.com/graphhopper/graphhopper/issues/1039#issuecomment-363378126

The android build [works now](https://travis-ci.org/graphhopper/graphhopper/builds/341900309). Now I need to enable auto deployment...
