### ISSUE TITLE
Use junction=circular

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#1149]
Similar to junction=roundabout there is a tag called `junction=circular`. It is not very commonly used, but from time to time. I think for us the right way to handle this would be to set it as roundabout, as the only difference is the right of way.

[Overpass Query](http://overpass-turbo.eu/s/roI).
[GH Maps Example](https://graphhopper.com/maps/?point=51.310258%2C3.121136&point=51.309742%2C3.120579)
[Google Maps Route](https://goo.gl/maps/qBJPbBM8CfQ2)
[OSM Wiki](https://wiki.openstreetmap.org/wiki/Tag:junction%3Dcircular)

Since they are slightly different from roundabouts, some people might be mislead by the roundabout instruction?

WDYT?

**Comment by karussell** [comment]
Tags under 1K are not worth the effort IMO: https://taginfo.openstreetmap.org/search?q=junction%3Dcircular

Why are they no roundabouts?

**Comment by boldtrn** [comment]
> Why are they no roundabouts?

Because of a different right of way. For roundabouts the cars inside the roundabout have the right of way, whereas the cars outside of the roundabout have to yield. There are some examples where this is not true.

> Tags under 1K are not worth the effort IMO

Yes maybe, especially since most of them seem to be turning areas :). On the other hand, for us internally it would be easy to match all tags with either junction=roundabout or junction=circular to roundabouts.

**Comment by devemux86** [comment]
> On the other hand, for us internally it would be easy to match all tags with either junction=roundabout or junction=circular to roundabouts.

If that's possible, then any such enhancement would improve routing responses and user experience.

**Comment by oschlueter** [comment]
Based on the suggestions made here I've submitted a _work-in-progress_ PR as basis for further discussions. The details are in the PR description. 

Would love to hear your feedback!

**Comment by karussell** [comment]
Fixed via #1185
