### ISSUE TITLE
Make normal algorithms work on graph prepared for CH

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#116]
It could be useful to prepare the graph for CAR but still have FOOT and BIKE vehicles or just CAR with other weighting available. I.e. it would be nice to have the possibility to run CH and normal algorithms (e.g. via setting edge filters)

The work in the branch shows that if we use the filter then CH-queries and preparation are 20% slower compared to disconnecting shortcuts and edges. Unsurprisingly is the number of normal edges going in the wrong direction (downwards) also 20%, i.e. iterating/loading them is waste of time.

This issue will allow us:

 * to improve turn instructions if CH is enabled and for this it is necessary to iterate over original edges only (very important, no space efficient workaround to my knowledge)
 * to support turn costs for CH it could be necessary to run normal algorithm while path extraction (important, but there exists a workaround via storing 'loops' at via point elsewhere)
 * running normal algorithms on a prepared graph (minor importance)

To make this issue complete we do in a [separate branch](https://github.com/graphhopper/graphhopper/tree/issue_116):
 - [x] removed LocationIndexTreeSC
 - [x] graph.getOriginalGraph (make sure no confusion with QueryGraph exists) or another technique to avoid a special edge filter e.g. to use LocationIndexTree with a graph containing shortcuts
 - [x] QueryGraph needs a getOriginalGraph method too (e.g. in Path but also in normal algorithms)
 - [x] make enabling multiple vehicles possible even if CH is enabled. But define which single vehicle should be used for CH -> done via new defaultVehicle which is also used if no vehicle was specified
 - [x] see if we can fix #288
 - [x] an efficient StopEdgeFilter which knows that original edges come before shortcuts and allow an efficient way to iterate over original edges. Does not help much as this is not often the case that there are 0 normal edges
 - [x] later think about reverse approach: always use base graph except level graph uses special 'graph for algorithm' in algo and path
 - [ ] Remove the necessity to do the CH preparation before the index creation. The location index had to be created AFTER the preparation but sometimes we need to change edges based on an location index (traffic data) BEFORE preparation.
 - [ ] after branch is merged (separate issue?): rename LevelGraph stuff to ShortcutGraph as we no longer need to store the levels, just if an edge is up- or downwards -> for the LevelEdgeFilter and only for normal edges as shortcuts are always upwards!

**Comment by Svantulden** [comment]
Do you have any idea when this issue will get some progress? I need roundabout instructions (#185) for my use case and would like to use Graphhopper for routing. I am willing to contribute as much as I can, though I don't have much experience with graphs and routing algorithms so maybe I can help out in another area.

**Comment by martinsauvage** [comment]
Hi Peter,

Same thing for me, any update about this issue to support later #185 ? I know you don't provide timeframe but are you close to release 0.4, is it matter of months? 

Thanks,
Martin

**Comment by karussell** [comment]
I know progress is very important and we'll recover and push more out in the next few weeks/months compared to the last months, but again: we can't give you a time estimate for specific issues as this depends on community contributions and customer requests which can slow down this issue or make it happen in a few days.

**Comment by martinsauvage** [comment]
OK thanks for your reply, so this issue/feature is not abandoned just postponed. It is not easy to be informed about the priority and activity of an open source project, maybe you have a blog or something else to communicate about progress?

**Comment by karussell** [comment]
This issue requires some substantial refactoring: separating a 'base graph' and a 'routing graph' and managing this from one enity e.g. 'GraphStorage'. Currently `GraphStorage` is too tightly coupled with the `Graph` interface. The plan is to accept the slow down for now, and make everything working including the roundabout instructions. And in 0.5 to prepare for the refactoring. With #111 this would also then allow for multiple CH profiles in one graph storage.

**Comment by karussell** [comment]
See the new, already working, trials in https://github.com/graphhopper/graphhopper/tree/issue_116_3, will update the todo-list here

**Comment by karussell** [comment]
Closing in favor of #338
