### ISSUE TITLE
Setup Continuous Performance Measurement

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#1163]
Due to the latest performance impact, see #1162. I just thought that it would be really cool to have a continuous performance measurement, similar to CI.

Apparently it is not too hard too hard to build a custom CI server, see [here](https://developer.github.com/v3/guides/building-a-ci-server/) or [here](https://developer.github.com/v3/guides/building-a-ci-server/).

Essentially this would require a small server (big enough to build Germany or at least Bavaria) that would run gh measurement for every PR (or every PR that has been approved?) and compares the measures to the current master. 

Would be a pretty fancy feature :). WDYT?

**Comment by karussell** [comment]
We already have something like this for current master: https://graphhopper.com/measurement/

Comparing performance stuff is not that simple. Sometimes you need to see the pattern to see if it is significant difference or just noise.

**Comment by boldtrn** [comment]
> We already have something like this for current master: https://graphhopper.com/measurement/

I know :). I just thought it would be super if we could check this on a PR base and before merging. This would make finding the reason for the slowdown easier and we could avoid deploying a change that might slow down our production environment.

> Sometimes you need to see the pattern to see if it is significant difference or just noise.

This is certainly a big issue, I thought about that as well. I had hoped if we get a small dedicated server that runs every build in a container (Docker, Kubernetes, etc.) could reduce the noise to a minimum.

**Comment by karussell** [comment]
If you find some bash magic to checkout the correct branch after an git pull or update we can implement this already. The problem currently is if there are multiple commits. Currently it is just:

```
cd /install/graphhopper_test/
git fetch
git checkout master

RET=`git pull | grep Already | cut -d' ' -f2`
if [[ "$RET" = "up-to-date." ]]; then
 exit
fi
```

**Comment by boldtrn** [comment]
> Currently it is a cronjob that runs a bash script

GitHub provides webhooks, similar to any CI, after a push, GitHub will ping some url and will provide some information what was pushed and where. 

Here is a simple script showing the basic idea:
```
post '/event_handler' do
  @payload = JSON.parse(params[:payload])

  case request.env['HTTP_X_GITHUB_EVENT']
  when "pull_request"
    if @payload["action"] == "opened"
      process_pull_request(@payload["pull_request"])
    end
  end
end

helpers do
  def process_pull_request(pull_request)
    puts "It's #{pull_request['title']}"
  end
end
```

So we would have a server waiting receiving the hook, that would then spin up a container and run the performance test in the container.

We could even provide a result similar to a regular CI solution. Showing either green or red, depending on the performance impact. This is simple to for GitHub, the actual measurement is something different though:
```
def process_pull_request(pull_request)
  @client.create_status(pull_request['base']['repo']['full_name'], pull_request['head']['sha'], 'pending')
  sleep 2 # do busy work...
  @client.create_status(pull_request['base']['repo']['full_name'], pull_request['head']['sha'], 'success')
  puts "Pull request processed!"
end
```

Every time the master is changed, we will do a performance measurement for the master as well, to be able to compare the numbers.

This is certainly not a trivial thing to do, but at least something I think would be pretty awesome and help GraphHoppper.

**Comment by karussell** [comment]
> So we would have a server waiting receiving the hook, that would then spin up a container and run the performance test in the container.

I would not want to have multiple runs at the same time. Even in a container I doubt it cannot really be independent if resources are smaller. So if no cronjob we need a queue that also somehow is able to disregard commits or pushs if this would be too much or unneeded.

> This is certainly not a trivial thing to do, but at least something I think would be pretty awesome and help GraphHoppper.

Yeah, and the UI (see [here](https://github.com/graphhopper/graphhopper/pull/894)) needs the ability to filter for branches.

**Comment by boldtrn** [comment]
> So if no cronjob we need a queue that also somehow is able to disregard commits or pushs if this would be too much or unneeded.

Yes, I think so too. We have to queue the pushs and only test the performance of one at a time.

> Yeah, and the UI (see here) needs the ability to filter for branches.

Yes, or we a measurement result file for every commit, referenced to the SHA of the commit.

**Comment by easylite376** [comment]
Sounds like a jenkins server with independent slave machines or a master with only one job running at a time.

**Comment by boldtrn** [comment]
@easylite376, this sounds interesting. Yes I think one master running jobs in sequence and not parallel would be enough in the beginning, that way it would be probably quite easy to host as well. Can you provide some more details?

**Comment by easylite376** [comment]
@boldtrn Jenkins is a big field and I'm also in the middle of learning many things. Could you please create one or two questions, so I know were you want to go with "more details/information"?

**Comment by karussell** [comment]
(Would you mind moving the discussion into the forum? Also I'm sure that something like this is a project on its own that then could be used for GraphHopper. But it is probably not an issue of GH core - WDYT?)

**Comment by easylite376** [comment]
Sure :) I created a topic [here](https://discuss.graphhopper.com/t/setup-continuous-performance-measurement/2785)

**Comment by karussell** [comment]
This is now done via some gitlab runners on dedicated hardware and https://github.com/graphhopper/graphhopper/tree/master/benchmark
