### ISSUE TITLE
Set visibility modifier of OSMReader#addEdge to protected

### ISSUE THREAD

**Issue by jtheuer** [graphhopper/graphhopper#1165]
I would like to extend the current OSMReader at the [addEdge](https://github.com/graphhopper/graphhopper/blob/91ca93d8520480f3d103a79962ecabad35f72c78/reader-osm/src/main/java/com/graphhopper/reader/osm/OSMReader.java#L677) method. Would it be possible to increase the visibility to `protected` so I can overwrite & extend the method in a subclass?

**Comment by karussell** [comment]
Not likely. What is your use case?

**Comment by jtheuer** [comment]
I would like to smooth / filter the PointList before adding it to the graph. addEdge would be a good extension point (any other callback in the method would work, too).
Another option would be to open the existing simplification to other implementation.

I tried to just copy'n'paste the contents of the reader but that only means I would have to re-implement parts of the turn restrictions code because it is [tied to the OSMReader](https://github.com/graphhopper/graphhopper/blob/0abc0fc4531baa5a9127d75d50228e0033c0226c/reader-osm/src/main/java/com/graphhopper/reader/osm/OSMTurnRelation.java#L61) or also [package protected](https://github.com/graphhopper/graphhopper/blob/0abc0fc4531baa5a9127d75d50228e0033c0226c/reader-osm/src/main/java/com/graphhopper/reader/osm/OSMTurnRelation.java#L45-L51)
so I couldn't use it in a custom OSMReader.

Do you have other ideas?

**Comment by karussell** [comment]
We could add a setSimplification(DouglasPeucker) method to OSMReader?

**Comment by jtheuer** [comment]
If I could pass a custom simplification implementation (not only a DouglasPeucker class) and move it before the distance calculation, then it would work! (rationale: The existing "free" elevation data is too noisy for an accurate distance calculation)

**Comment by karussell** [comment]
> If I could pass a custom simplification implementation (not only a DouglasPeucker class)

All methods and the DouglasPeucker class itself are not final so you could extend it

> (rationale: The existing "free" elevation data is too noisy for an accurate distance calculation)

Couldn't you then use a different ElevationProvider with already smoothed data?

**Comment by boldtrn** [comment]
> Couldn't you then use a different ElevationProvider with already smoothed data?

But then you still see issues with the resolution of the elevation provider. If I understand this correctly, this seems related to #517, and my comment [in this issue](https://github.com/graphhopper/graphhopper/issues/517#issuecomment-322093062)?

**Comment by jtheuer** [comment]
> All methods and the DouglasPeucker class itself are not final so you could extend it
Sure. Alternatively, add an interface with the method ```public int simplify(PointList points)``` 

> Couldn't you then use a different ElevationProvider with already smoothed data?
That would be better and I guess there are 3D simplifying algorithms out there. The file boundaries need special attention, of course. It turned out that it is more practical to do it for each way.

**Comment by karussell** [comment]
This would be cool if you could contribute it as @boldtrn pointed out is an open issue.

**Comment by karussell** [comment]
Closing in favour of #1370
