### ISSUE TITLE
High memory usage in latest master due to new instruction creation (PointList.copy)

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1166]
There is something wrong with the new instruction creation - probably the reduceLength method. We saw for a normal CH request the following OOM, and this was after a 10GB memory increase.

```
java.lang.OutOfMemoryError: Java heap space
        at com.graphhopper.util.PointList.<init>(PointList.java:154)
        at com.graphhopper.util.PointList.copy(PointList.java:433)
        at com.graphhopper.util.PathSimplification.reduceLength(PathSimplification.java:158)
        at com.graphhopper.util.PathSimplification.simplify(PathSimplification.java:102)
        at com.graphhopper.util.PathMerger.doWork(PathMerger.java:142)
```

**Comment by karussell** [comment]
One problem I found is that we create a new PointList with `size` and not with `end-from`

**Comment by karussell** [comment]
(Issue #1162 is not fixed with the recent change.)

**Comment by karussell** [comment]
So this seems to solve the issue (will reopen in the next days if not).

Still it is a bit ugly that the GC G1 does not seem to handle this high RAM utilization well. Highly likely because the size is >100GB but it should handle it better as the majority of it is static

**Comment by boldtrn** [comment]
Thanks for the update. I also proceeded in #1162, but I still need to make sure that everything works as expected and that we see the performance improvement that we want to see. Have a look [here](https://github.com/graphhopper/graphhopper/compare/master...boldtrn:issue_1162?expand=1), if you want to peek :).
