### ISSUE TITLE
Tests in client-hc module do not run with JDK9

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1167]
There seems to be a cert issue:
```
javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at com.graphhopper.api.GraphHopperWebIT.testMatrix(GraphHopperWebIT.java:232)
Caused by: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
```

BTW: Also there is a problem for a maven plugin regarding JDK9 (findbugs -> issue [here](https://github.com/spotbugs/spotbugs/issues/412)). Looks like the new 'spotbugs' maven plugin is not yet released on maven central. With RC4 the version problem disappears but still one warning.

**Comment by karussell** [comment]
This is highly likely just an installation problem as I just fetched the JDK for linux from http://jdk.java.net/9/, without a proper linux integration or without the certs (?)

**Comment by aaron-haskins** [comment]
Seems to be related to [this issue](https://github.com/docker-library/openjdk/issues/145) if you use a docker container, otherwise have a look at this [stackoverflow answer](https://stackoverflow.com/questions/6784463/error-trustanchors-parameter-must-be-non-empty).

**Comment by karussell** [comment]
I did not use docker there, but thanks for the link. The comment says 'The cacerts file that comes with 181 is empty.' ... so this is a packaging problem for this specific jdk9
