### ISSUE TITLE
PathDetailsBuilderFactory is not changeable

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1168]
To add custom PathDetails there has to be a way to overwrite the PathDetailsBuilderFactory creation. The normal way would be via yet another method createPathDetailsBuilderFactory in GraphHopper, but maybe there is a better way? Maybe the factory should be without arguments and the createPathDetailsBuilders method should instead? Then we could use a setter and the factory would be also thread safe. The problem then is that the `List<String> pathDetails` have to be passed parallel to the factory inside the PathMerger and then a second time inside the createPathDetailsBuilders method, which is ugly.

**Comment by boldtrn** [comment]
Indeed I haven't considered this yet. Shouldn't we follow the current GH approach and provide a setter in GraphHopper so everyone could set a different Factory?

**Comment by karussell** [comment]
Well there is also no WeightingFactory and we allow customization via overloading the method. But I also prefer the factory appraoch in general. The problem here is: we would have to pass the factory and the details list all the way down to the Path object ... I'll see how and if I can avoid this

**Comment by karussell** [comment]
But I do not see another better solution, so have implemented it.

One thing we have to keep in mind the weighting could theoretically change per Path and now this change considers this but it could introduce other problems later.
