### ISSUE TITLE
Measurement: Make Weighting+Vehicle Configureable

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#1174]
Currently the measurement is a bit too static. It is hard to change the weighting or the vehicle. The weighting "fastest" is hardcoded in the measurement class and also in the graphhopper.sh file. It would great if we would make the weighting and vehicle easier configurable.

Maybe we could even consider running Measurement with multiple weightings? Would be nice to compare the performance of weightings, but might be a bit too customized?

**Comment by easbar** [comment]
Now its possible to change the vehicle/encoder and the weighting. We can even run the measurement with a custom model/weighting as it is done here: https://github.com/graphhopper/graphhopper/blob/efabfeb6000cd81d629022486d06238a3153a0ff/benchmark/benchmark.sh#L137-L138
