### ISSUE TITLE
GH Maps - Make PathDetails visible

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#1177]
Currently GH Maps uses [this elevation plugin](https://github.com/MrMufflon/Leaflet.Elevation), which seems to be not maintained anymore (last change was in 2016, 8 open PRs). 

I have just seen this [repo](https://github.com/GIScience/Leaflet.Heightgraph). Essentially, they do more or less the same as the current elevation plugin, but they also allow to visualize additional information in the height graph, like surface, as shown in the [example](https://giscience.github.io/Leaflet.Heightgraph/).

**Comment by karussell** [comment]
BTW: why has this issue this name :) ?

**Comment by boldtrn** [comment]
> BTW: why has this issue this name :) ?

Good question :). Because it could make the PathDetails easily visible on the frontend without requiring debug=true. For me using the updated elevation plugin has two benefits: a) switching to an actively developed elevation plugin and b) it is more powerful and could allow to show the PathDetails more easily.

Should I rename it? I only addressed one of the two issues in the title.

**Comment by karussell** [comment]
Ah, you mean you would show the path details in the elevation view - interesting! How would you show multiple details like street name and max speed?

**Comment by boldtrn** [comment]
> How would you show multiple details like street name and max speed?

Have a look at their [example](https://giscience.github.io/Leaflet.Heightgraph/), they included a way to switch between multiple types in the bottom-right.

**Comment by karussell** [comment]
Ah, didn't see this in the first place. This is really cool work from @TimMcCauley and @Kinas and better than our current solution with hidden parameters and blue dots!
