### ISSUE TITLE
Translation Improvement - Arrive At Road name

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#1178]
As discussed in #1071. Other routing engines add the name of the road in addition to the arrive at instruction. Like "arrive at main road". I think this would be a nice addition for GH as well.

**Comment by karussell** [comment]
Ok ... although one can have this now with the path details

**Comment by boldtrn** [comment]
Oh, you are right. Mhm not sure, for the user having it in the instruction would be probably easier?

**Comment by karussell** [comment]
Yes. BTW: we added somewhere the street name separately: this is no longer necessary. Or did we not yet merge the change?

**Comment by devemux86** [comment]
> we added somewhere the street name separately

I think, not added, just allowed to have the street names instead of full text instructions, if requested.

> this is no longer necessary

Not agreed here, should not limit a library features!
Flexibility is nice as many would prefer to handle the instructions, instead of based on ready texts.

**Comment by devemux86** [comment]
@karussell probably is #946.

**Comment by boldtrn** [comment]
>  BTW: we added somewhere the street name separately: this is no longer necessary.

Oops, sorry you are right. We return the street name as extra field in the instructions, then it's easy to add this on the client side :+1:.
