### ISSUE TITLE
Connections Not Found - Turn Restrictions

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#1187]
I have just seen [this](https://graphhopper.com/maps/?point=52.378615%2C13.539491&point=52.378399%2C13.54007&ch.disable=true) route. For some reason it creates a connections not found error. It works with ch, but does not with `ch.disabled=true`. That's why I expect that the issue is created by turn restrictions. The issue is the start point, if you [slightly move](https://graphhopper.com/maps/?point=52.378615%2C13.539501&point=52.378399%2C13.54007&ch.disable=true) the start it works.

I am not 100% sure if this is due to incorrect OSM tags or maybe that GH evaluates them in an unexpected way?

Here are the tagged turn restrictions: [1](http://www.openstreetmap.org/relation/2473380), [2](http://www.openstreetmap.org/relation/5254535), [3](http://www.openstreetmap.org/relation/5254536). Here is the [corresponding overpass query](http://overpass-turbo.eu/s/skK).

**Comment by karussell** [comment]
This is more a data issue: [this way](http://www.openstreetmap.org/way/136089841#map=16/52.3840/13.5322&layers=N) is tagged as motor_vehicle:private and so with turn restrictions there is no solution.
