### ISSUE TITLE
Create a GHException for "maximum nodes exceeded"

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#1188]
To make it easy for the frontend to parse the "maximum nodes exceeded" exception, it would be nice to have this exception as as GHException also returning its class.

**Comment by Hasankib** [comment]
Hi, does this issue still need fixing?

**Comment by otbutz** [comment]
@boldtrn #2464

**Comment by boldtrn** [comment]
Thanks for the ping, I totally missed this
