### ISSUE TITLE
Avoid sidewalks completely when routing in bike

### ISSUE THREAD

**Issue by imscreed** [graphhopper/graphhopper#1196]
Is there a way to avoid sidewalks from the suggested route when using bike? This is creating unnecessary turns. For example, https://graphhopper.com/maps/?point=43.661209%2C-79.36657&point=43.66235%2C-79.365143&locale=en-US&vehicle=bike&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale

In the above route, it makes no sense to go away from the destination and then take a U-turn. This is just sidewalk and there are no other roads. 

We just want to make the starting of this route similar to car. Or in other words, do not use sidewalks in the route.

**Comment by karussell** [comment]
Yes, this is possible via passing a custom EdgeFilter to the LocationIndex. This is related to #82.

For further questions please use our forum.
