### ISSUE TITLE
Method calling itself causing stackoverflow (tools/ui)

### ISSUE THREAD

**Issue by JoseAlcerreca** [graphhopper/graphhopper#1197]
https://github.com/graphhopper/graphhopper/blob/c3505fd1bed046819ccf25079a01933fae4504eb/tools/src/main/java/com/graphhopper/ui/GraphicsWrapper.java#L128

Probably should be `plotNode(g2, loc, c, size, "");`

Also, https://github.com/graphhopper/graphhopper/blob/c3505fd1bed046819ccf25079a01933fae4504eb/tools/src/main/java/com/graphhopper/ui/GraphicsWrapper.java#L131

is weird. Forcing the size to 4. But no idea if that's WAI.

**Comment by karussell** [comment]
Ups, thanks for spotting this :)
