### ISSUE TITLE
Import does not work with PT

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#1206]
As mentioned [here](https://discuss.graphhopper.com/t/including-offline-public-transport-routing-into-android-app/2566/10?u=boldtrn), `./graphhopper.sh import` does not work with PT.

**Comment by karussell** [comment]
Running the script ./graphhopper.sh does not work as we need to specify two input files, which will be improved also in #1108 

It should work like described here: https://github.com/graphhopper/graphhopper/tree/master/reader-gtfs

**Comment by boldtrn** [comment]
> Running the script ./graphhopper.sh does not work as we need to specify two input files

Shouldn't this be possible by adding the gtfs file as java argument? In the end this results in the same call as described in the above mentioned config?

**Comment by karussell** [comment]
This is possible now and the argument for the GTFS file is `--gtfs.file`
