### ISSUE TITLE
RealtimeIt#testExtraTrip fails for some local time zones

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#1210]
I just ran the tests for the current master using the time one `UTC+10:00` and the test `RealtimeIt#testExtraTrip` failed. If I change my time zone to Shanghai `UTC+08:00` it works. If I change my time zone to Perth `AWST` (same time as `UTC+08:00` right now), it fails.

Maybe @michaz you have an idea what might be happening here? In the test we define the time zone, but maybe the server itself runs on a different time zone?

**Comment by michaz** [comment]
Haha, nice. I probably left some debug or mock thing in there which uses the "current" time zone. Good that we are a global team. :)

**Comment by michaz** [comment]
(Will look at it today)

**Comment by karussell** [comment]
As we stumbled over this recently #1209 maybe we should use something like the policeman tools?

https://github.com/policeman-tools/forbidden-apis/wiki
http://blog.thetaphi.de/2012/07/default-locales-default-charsets-and.html

**Comment by boldtrn** [comment]
> maybe we should use something like the policeman tools?

I second that! I think this is a good idea :). I created a PR #1213 testing the policeman tools.

**Comment by boldtrn** [comment]
Any updated on this @michaz? Could we ignore this test until the problem is solved?

**Comment by michaz** [comment]
Just a second..

**Comment by michaz** [comment]
That was a really helpful ticket, thanks for reminding me!

**Comment by boldtrn** [comment]
Thanks so much for fixing this @michaz!
