### ISSUE TITLE
graphHopper maps offline

### ISSUE THREAD

**Issue by rehanhammer** [graphhopper/graphhopper#1211]
Can graphhopper maps can be used offline on localhost just like google maps?

**Comment by karussell** [comment]
Question should go to our forum

**Comment by rehanhammer** [comment]
Let me know if any decision has made. It will be helpful
Thank you !

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
