### ISSUE TITLE
Blocking motorways fails

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1214]
When using a rather small block_area this blocks only one of the directions as the ID search stops when going outside of the boundary and just adds one edgeId. We could either make the current 1km² setting changable or properly find all edgeIds in this bounding box.

The shape method has additionally the disadvantage that if the junction nodes are outside of the bounding box (but the edge is still crossing the bbox that happens frequently with motorways or tunnels) the edge is **not** skipped. But fetching the edge geometry could be too expensive.

**Comment by boldtrn** [comment]
Could you add an example?

Another issue for motorways could be that we use BFS to find "all" edges in a shape. If there is no connection from one edge to another in the shape, our current approach might fail.

At the time of creating the block feature, we haven't had the `findNClosest` method in the `LocationIndexTree`. Maybe we could use this method in combination with an EdgeFilter that filters Edges that lie outside of the shape?

**Comment by karussell** [comment]
Yeah, an example is important :)

[This](https://graphhopper.com/maps/?point=42.533698%2C1.520147&point=42.522945%2C1.560659&block_area=42.527848,1.531649,42.522408,1.539545&ch.disable=true) should block via edge ids and [this route](https://graphhopper.com/maps/?point=42.533698%2C1.520147&point=42.522945%2C1.560659&block_area=42.527848,1.531649,42.522408,1.539545&ch.disable=true&block_area.edge_id_max_area=0) via shape but both do not work at the moment. 

[This route](https://graphhopper.com/maps/?point=42.533698%2C1.520147&point=42.522945%2C1.560659&block_area=42.530283,1.520448,42.529737,1.521145&ch.disable=true) is properly blocked where the edge id search is or [this route](https://graphhopper.com/maps/?point=42.533698%2C1.520147&point=42.522945%2C1.560659&block_area=42.530283,1.520448,42.529737,1.521145&ch.disable=true&block_area.edge_id_max_area=0) that includes the tower node in the block_area.


I'm unsure why [this route](https://graphhopper.com/maps/?point=42.533698%2C1.520147&point=42.522945%2C1.560659&block_area=42.523483,1.544008,42.521775,1.546068&ch.disable=true) fails even for the opposite direction as the edge id search should find at least one of the two edges.

> If there is no connection from one edge to another in the shape, our current approach might fail.

Yes, that was what I meant :)

> Maybe we could use this method in combination with an EdgeFilter that filters Edges that lie outside of the shape?

How do we detect if an edge is outside of a shape? If one or two tower nodes are outside of the shape the edge could be still inside and if we fetch the whole geometry we have to take care of the performance. Maybe a good compromise is: if the shape is small call fetchWayGeometry and if the shape is big assume there will be at least one tower node of every edge inside the shape. And we do a performance comparison in a city (as it is an edge-dense area) which area size should be used as new default.

**Comment by boldtrn** [comment]
> Maybe a good compromise is: if the shape is small then call fetchWayGeometry and if the shape is big then assume there will be at least one tower node of every edge inside the shape and use the shape contains method. And we do a performance comparison in a city (as it is an edge-dense area) which area size should be used as new default.

How about, if the road is longer than half the shape length, then we fetch the geometry (or something like this)?

**Comment by karussell** [comment]
We have to see if distance calculation is really faster then fetching the full way geometry ;)

**Comment by karussell** [comment]
I think there are currently 3 very similar things in GH but handled completely different with their own limitations and especially the block_area has this bug and #1127 so it might be interesting to think about this again:

 * spatial rules creates an index before import to handle country specific speeds and access properties (also polygons are supported but resolution is per default not too fine)
 * the ChangeGraphHelper uses a JSON from a request to change speeds and access properties (bbox, line, multiple points)
 * this `block_area` parameter changes access properties (currently only bbox, point and circle)

**Comment by karussell** [comment]
Closing in favor of #1324
