### ISSUE TITLE
Add Geocoding to HC Client

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#1221]
Currently, if one wants to use the GraphHopper routing and geocoding API, a user either has to only the swagger client (no points encoded etc.) or has to mix the hc client with the swagger client. I think it would be a nice addition to the hc client to be able to use geocoding as well.

**Comment by devemux86** [comment]
It appears that we don't have here the useful [GeocodingLocation.getOsmKey](https://github.com/graphhopper/directions-api-clients/blob/master/java/src/main/java/com/graphhopper/directions/api/client/model/GeocodingLocation.java#L125-L132)?
