### ISSUE TITLE
list of path details should be possible via semicolon

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1241]
Multiple path details are possible via details=time&details=street_name but should be also possible via `details=time;street_name` similar to the block_area feature? Or at least document this properly.

Probably semicolon is better than comma as we could use this for a potential point list in the future too.

**Comment by boldtrn** [comment]
I think if we do this, we should do this for all array types, including points, point_hint, header, etc.? Otherwise it would feel a bit inconsistent.

**Comment by karussell** [comment]
True, maybe time to create the new JSON POST endpoint :)

**Comment by boldtrn** [comment]
> True, maybe time to create the new JSON POST endpoint :)

Yes :). Should I create a PR in the meantime allowing `;` for array parameters?

I think this would be nice and makes it easier to write urls by hand.

**Comment by karussell** [comment]
Ok

**Comment by karussell** [comment]
BTW: Should we keep the singular like `block_area` in those cases or use `block_areas`? Using plural has the advantage that we then can have a 1:1 mapping between the URL and a potential JSON array parameter. The disadvantages are probably that we need to create several new URL keys and probably some more.

**Comment by boldtrn** [comment]
> Should we keep the singular like block_area in those cases or use block_areas?

Probably `block_areas` makes more sense then. 

> The disadvantages are probably that we need to create several new URL keys and probably some more.

What do you mean here?

**Comment by karussell** [comment]
>> The disadvantages are probably that we need to create several new URL keys and probably some more.
> What do you mean here?

block_area vs. block_areas and point vs. points and so forth. So a lot more URL parameters.

**Comment by boldtrn** [comment]
> So a lot more URL parameters

Ah yes true, that is indeed not ideal. Keeping it as point but adding multiple points to it doesn't seem to be a nice idea either.

**Comment by michaz** [comment]
.. but why don't we leave it as it is, to keep it consistent with ``point``? Why two different array styles in the same API, for the same parameter? Why syntactic sugar in URLs?

**Comment by karussell** [comment]
> they are reserved for matrix parameters

What do you mean here?

> But Jersey/Dropwizard wants us to do it like we're doing it with point

Yeah, probably because of the underlaying jetty thing

> Why two different array styles in the same API, for the same parameter? Why syntactic sugar in URLs?

The problem is that we need special handling for these variables in JS. But also for other programming languages it was reported that multiple identical keys in an URL are problematic. 

But probably it is better to support multiple block_area keys instead and wait until we support posting JSON where this is clear.
