### ISSUE TITLE
Translate error message "Connection between locations not found"

### ISSUE THREAD

**Issue by fbonzon** [graphhopper/graphhopper#1248]
Would be nice to have this error message translated in the API response, according to the given `locale` parameter.

**Comment by karussell** [comment]
That is not an option as we would have to translate many exceptions for no real additional benefit. But we could assign specific exceptions a specific code to make this more end user friendly.

**Comment by igagrock** [comment]
I have been developing Rest applications. I want to contribute.
Could u assist me with the scenario

**Comment by karussell** [comment]
@igagrock please use our forum to ask questions and see our [contributing guide](https://github.com/graphhopper/graphhopper/blob/master/.github/CONTRIBUTING.md) as well as issues tagged with "good first issue"

**Comment by boldtrn** [comment]
> But we could assign specific exceptions a specific code to make this more end user friendly.

I think it should be quite easy to do already. For example we return the class of the exception and sometimes we add some details to some exceptions. This should be enough to translate the error on the client side?

**Comment by devemux86** [comment]
> For example we return the class of the exception and sometimes we add some details to some exceptions.

Indeed the `GHResponse` errors list can be checked for the class type and each class provides additional info for the specific error. Then clients can create proper messages with all that, according to their needs.

**Comment by boldtrn** [comment]
I will close this for now. Please reopen if there are any issues with translating this exception on the client side.
