### ISSUE TITLE
Does not consider turn restriction no_straight_on

### ISSUE THREAD

**Issue by polarbearing** [graphhopper/graphhopper#1249]
In [this case](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=52.45550%2C13.46015%3B52.45344%2C13.46141#map=18/52.45447/13.46079), going from the exit ramp to the entry ramp is forbidden. This is modelled with [turn restriction no_straight_on](https://www.openstreetmap.org/relation/6775545) with the 'via' role being the middle way on the junction. 

GH still routes straight, while OSRM and Mapzen find allowed routes. 

Same problem on the [other ramps](https://www.openstreetmap.org/relation/6775546). 

![gh_example](https://user-images.githubusercontent.com/8266355/34323341-5b18430a-e845-11e7-840f-424a501bfffe.png)

**Comment by karussell** [comment]
It is not yet implemented. See #446

**Comment by polarbearing** [comment]
ok sorry for the dup. I had seen #446 but it was talking about _multiple_ ways as _via_, while this case is a _single_ way as _via_. Hope it gets implemented soon.

**Comment by karussell** [comment]
Have changed the title there ;) thanks!
