### ISSUE TITLE
Strange behavior for bicycle routing on one way streets

### ISSUE THREAD

**Issue by sandsturm** [graphhopper/graphhopper#1255]
I have an open forum thread to correctly tag one way streets which are open for bicycles in both directions.
https://forum.openstreetmap.org/viewtopic.php?pid=679382#p679382
The tagging is now clarified. 

I wanted to check navigation for cycling the street in the **opposite direction** and saw this strange behavior of graphhopper:
**OSM** http://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=47.36370%2C8.53172%3B47.36006%2C8.53396#map=17/47.36202/8.53262
and
**graphhopper** https://graphhopper.com/maps/?point=Sportsbar%201904%2C%208002%2C%20Z%C3%BCrich%2C%20Schweiz&point=L%27Altro%2C%208002%2C%20Z%C3%BCrich%2C%20Schweiz&locale=de&vehicle=bike&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale

**Mapzen** navigates correctly: http://www.openstreetmap.org/directions?engine=mapzen_bicycle&route=47.36370%2C8.53172%3B47.36006%2C8.53396#map=17/47.36196/8.53284

**Graphhopper** navigation **following** the one way is correct as well: http://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=47.36006%2C8.53396%3B47.36370%2C8.53172

**Comment by ammagamma** [comment]
Do you mean this extra turn ?
![image](https://user-images.githubusercontent.com/17603532/34498677-0572ce5a-f003-11e7-9ee3-76e9821f19fa.png)

I just checked with the current master and latest map from [here](http://download.geofabrik.de/europe/switzerland.html) and it does not occur:

![image](https://user-images.githubusercontent.com/17603532/34498785-736e3f7a-f003-11e7-8ca9-325e2c840fae.png)

So probably the OSM data has just not been updated on the server yet ?

**Comment by sandsturm** [comment]
Yes, I was referring to this extra turn.
Could be. I am not aware of the required synchronization.

Best regards
Martin

**Comment by karussell** [comment]
Thanks @sandsturm for the report and @ammagamma for investigation. This sounds strange, maybe some elevation glitch where some improvements are indeed not yet deployed to the API. But it is probably not an OSM data problem as this is usually updated every day (see '+' button at the end of a route) and in this area there weren't many changes recently IMO.

**Comment by sandsturm** [comment]
Yes @karussell I changed a tag of this street yesterday. This was the discussion in the forum mentioned in the first post of this issue. As suggested by the forum, I changed `cycleway=opposite` to `oneway:bicycle=no`.

Maybe the change is not reflected in the current API, but did you change something relevant?

**Comment by karussell** [comment]
Both should be supported but I think this is unrelated and related to elevation stuff, which could be already fixed in master (but for the API we have to do other tests before using the latest master)

**Comment by karussell** [comment]
The latest update with elevation smoothing did not seem to improve the situation. Bad.

**Comment by karussell** [comment]
Debugging it with path details([this](https://graphhopper.com/maps/?point=47.361742%2C8.532686&point=47.360768%2C8.53303&point=47.360194%2C8.533716&vehicle=bike&weighting=fastest&elevation=true&debug=true&details=average_speed&use_miles=false) vs. [this](https://graphhopper.com/maps/?point=47.361742%2C8.532686&point=47.360194%2C8.533716&vehicle=bike&weighting=fastest&elevation=true&debug=true&details=average_speed&use_miles=false)) I can see that this is an elevation problem: 10km/h for the detour and 2km/h without leading to 0.5s faster tour GH think at least. Maybe we should rethink about our speed calculation based on the elevation.

**Comment by karussell** [comment]
So this yet another elevation issue. Closing in favour of 384
