### ISSUE TITLE
Too small duration for ferry

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1256]
[This ferry](http://www.openstreetmap.org/directions?engine=graphhopper_car&route=52.0163%2C4.6358%3B51.9010%2C4.6856) should not be used and probably instead [this alternative](https://graphhopper.com/maps/?point=52.0163%2C4.6358&point=51.985488%2C4.752359&point=51.901%2C4.6856). See [osm way](http://www.openstreetmap.org/way/7301827)

**Comment by boldtrn** [comment]
Do you think this is a general ferry problem, so that we should increase the ferry duration globally or should we fix this in osm?

**Comment by karussell** [comment]
I think this is only necessary for short distance ferries. But the problem is that a time offset is not that easy and reducing the speed is the only option although this is already at 4km/h (this was easy to find out, due to the new path details feature :)). So let's try if distance<500m speed=minimum or something

**Comment by karussell** [comment]
Currently we do

```java
if (durationInHours == 0) {
 return UNKNOWN_DURATION_FERRY_SPEED;
```

What if we do a slight reduction (if possible) for short ferries?

```java
if (Math.round(estimatedLength) < 300)
  return speedEncoder.factor / 2;
else
  return UNKNOWN_DURATION_FERRY_SPEED;
```

**Comment by boldtrn** [comment]
> What if we do a slight reduction (if possible) for short ferries?

For the default car profile with speed factor of 5 and `UNKNOWN_DURATION_FERRY_SPEED` of 5, this would not change anything. If we would change the speed factor or use a different encoder this would fix the issue.

I created a PR that shows how it could look #1264.
