### ISSUE TITLE
OSRM json format

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1265]
The mapbox SDK seems to be frequently used and is open source (as far as I can see for several languages) and so we should consider implementing an alternative json format of `/route` via a different end point like `/route-osrm` or parameter like `format=osrm`

http://project-osrm.org/docs/v5.5.1/api/

Dependency: #1108

**Comment by michaz** [comment]
Would suggest a new endpoint, which then emulates the OSRM API both ways.

**Comment by karussell** [comment]
Ok. What do you mean with "both ways"?

**Comment by michaz** [comment]
That the endpoint's requests are also like OSRMs. Not only the responses, like you were hinting at with ``format=osrm``.

**Comment by karussell** [comment]
Ah, makes sense. Now the endpoint makes also more sense, yes.

**Comment by boldtrn** [comment]
When we merge #1422, should we create smaller issues per feature that we want to add to this endpoint and close this issue?

**Comment by karussell** [comment]
Yes, sure.

**Comment by karussell** [comment]
This will go into a separate repository https://github.com/graphhopper/graphhopper-navigation

And we won't support OSRM but only mapbox (they seem to be incompatible and OSRM seems not to work with the navigation SDK)
