### ISSUE TITLE
Foot routing ignores Pedestrian area's  

### ISSUE THREAD

**Issue by zayuim** [graphhopper/graphhopper#1266]
With OSM it is possible to make a pedestrian street into an area or multi-polygon. However GraphHopper seems to ignore them for foot routing. Infact I just took a look at the map you are using and it appears that they don't even render, this still shouldn't stop the OSM data from being used though.

[Here is an example](https://www.openstreetmap.org/directions?engine=graphhopper_foot&route=-27.46917%2C153.02586%3B-27.47064%2C153.02396#map=19/-27.47007/153.02544)

**Comment by boldtrn** [comment]
Thanks for the report. 

I think the underlying issue why the area is completely ignored for routing is that the tags are added to the [relation](https://www.openstreetmap.org/relation/7781404) and not the [way](https://www.openstreetmap.org/way/544524547). I would assume that if you transfer the tags of the relation to the way the foot routing should work. The data for the routing is updated periodically, so after changing the tags it might be a couple of hours (I think usually within 24?) before the area becomes routable.

This is also related to #82. Usually GraphHopper would route along the edges of an area and not through the area.

**Comment by karussell** [comment]
I think it is a dup of #82.

**Comment by boldtrn** [comment]
> I think it is a dup of #82.

But then it should route along the edges of the area? So I actually think this is because the tags are on the relationship and not the way?

**Comment by karussell** [comment]
> But then it should route along the edges of the area? 

An area is completely ignored at the moment and #82 would fix it.
