### ISSUE TITLE
Are isolated roads not token into consideration?

### ISSUE THREAD

**Issue by BranZhang** [graphhopper/graphhopper#1271]
I am using offline routing function on my device.
roads data is converted from openstreetmap by your script.(./graphhopper.sh import my_osm_file)
I find that isolated roads are not token into consideration, and this situation is existing on your web too.
like:

![image](https://user-images.githubusercontent.com/10242480/35132699-794159f8-fd07-11e7-85c3-c7f61916bb1c.png)

link:https://graphhopper.com/maps/?point=23.112575%2C108.852367&point=23.068519%2C108.865242&locale=En&vehicle=car&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale

**Comment by boldtrn** [comment]
Isolated roads get removed by default. You can change that behavior [here](https://github.com/graphhopper/graphhopper/blob/master/config-example.properties#L60).

Set it to:
```
prepare.min_network_size=0
prepare.min_one_way_network_size=0
``` 

Is this road really isolated in reality? If not, it would be great to improve the OSM data :).
