### ISSUE TITLE
SRTM import is broken

### ISSUE THREAD

**Issue by g3rb3n** [graphhopper/graphhopper#1274]
Currently we are unable to build graphs with height profiles for the whole world and for North America.

The srtm height profile file names at http://srtm.kurviger.de/SRTM3/North_America/index.html sometimes do have the format:
N56W071hgt.zip
and not
N56W071.hgt.zip
The last format is assumed in com.graphhopper.reader.dem.SRTMProvider. 

This line fails:
downloader.downloadFile(zippedURL, file.getAbsolutePath());
with zippedURL being: 
http://srtm.kurviger.de/SRTM3//North_America/N56W071.hgt.zip
which should be:
http://srtm.kurviger.de/SRTM3/North_America/N56W071hgt.zip

I have tried to update core/src/main/resources/com/graphhopper/reader/dem/North_America_names.txt with the correct names but this does not solve the problem. The filenames are parsed at the init routine of the SRTMProvider and converted to coordinates. For downloading the coordinates are converted to an url.

It might be a temporary problem at srtm.kurviger.de.

**Comment by karussell** [comment]
Indeed, the problem is highly likely that something changed at the download servers @boldtrn ?

**Comment by g3rb3n** [comment]
For now we have a workaround bash script which downloads all srtm zip files and renames them where needed.
 
wget -O - http://srtm.kurviger.de/SRTM3/North_America/index.html | grep -o \".*.zip\" | grep -o [^\"]*.zip[^\"]* | sed -e 's/^/http:\/\/srtm.kurviger.de\/SRTM3\/North_America\//g' > srtm.urls
wget -nc -i srtm.urls
rename 's/hgt.zip/.hgt.zip/g' *[!\.]hgt.zip

**Comment by boldtrn** [comment]
Interesting, thanks for reporting.

> Indeed, the problem is highly likely that something changed at the download servers @boldtrn ?

I didn't change anything on the server. The same seems to happen also for the [original SRTM server](https://dds.cr.usgs.gov/srtm/version2_1/SRTM3/North_America/).

Do you use the latest master? We changed the [srtm provider a bit ~2 weeks ago](https://github.com/graphhopper/graphhopper/commit/2463090f22f206886c7abdc7ecede3f574c49a66).

In the old SRTMProvider, we used `String zippedURL = baseUrl + "/" + fileDetails + ".hgt.zip";`. So I think we did not introduce this issue in this change though.

Did the import work before and stopped working now? 

We could introduce a fallback behavior if  `name.hgt.zip` could not be found, we try downloading `namehgt.zip`?

**Comment by karussell** [comment]
I can remember such an issue from some earlier days. Do you update the data automatically? If not, then this does not make sense.

@g3rb3n which version are you using?

**Comment by g3rb3n** [comment]
I am using 0.9.0.

The current SRTMProvider in master still uses the same pattern to build the file names / urls. It is assumed that the files are always named according to this pattern: [NS][0-9]{2}[EW][0-9]{3}.hgt.zip

**Comment by boldtrn** [comment]
> Do you update the data automatically?

AFAIK old SRTM data is not updated anymore. The provided data is the data recorded on a space shuttle flight some years ago. But I might be wrong? Currently the srtm.kurviger.de server does not have an automatic update mechanism.

**Comment by karussell** [comment]
But then this is really strange. Maybe just rename the files on your server :D 

https://stackoverflow.com/q/1086502/194609

**Comment by g3rb3n** [comment]
This worked for me:

rename 's/hgt.zip/.hgt.zip/g' *[!.]hgt.zip

**Comment by boldtrn** [comment]
> But then this is really strange. Maybe just rename the files on your server

Yes sure I can do this. But then the SRTMProvider would still not work with the original SRTM data. Also I would need to update the index files as well. 

I think I would prefer to solve this in GraphHopper and not on my server, but it's your call, I don't mind.

**Comment by boldtrn** [comment]
WDYT @karussell?

**Comment by karussell** [comment]
Before we do something, we need to understand what went wrong. How can it be that the file names on your server are no longer working with the file names expected in code?

**Comment by boldtrn** [comment]
> Before we do something, we need to understand what went wrong

The files on the srtm.kurviger.de server didn't change. I also think that the files on the original srtm server didn't change.

It could be that the elevation data for this area never worked before but maybe we didn't throw an exception before? This issue popped up after we changed something in the ElevationProvider.

**Comment by karussell** [comment]
ok, then a code change is good for me.

**Comment by karussell** [comment]
> It  could be that the elevation data for this area never worked before but  maybe we didn't throw an exception before? This issue popped up after we  changed something in the ElevationProvider.

Then why don't we change the URL to the 'new' naming schema instead of the fall back? I don't like trying and fall back especially since #1300 is not that simple to behave efficient.
