### ISSUE TITLE
Turn restrictions for bicycle in oneway street with cycleway=opposite

### ISSUE THREAD

**Issue by Lukas458** [graphhopper/graphhopper#1283]
Hello,
I have a complex issue concerning GraphHopper's bicycle routing. I have a oneway street which is open to cyclists on both ways. But if you are a cyclist and cycle the oneway street onto the opposite side, you have to respect a turn rstriction at the end of the street. This turn restriction is implemented (I thought correctly), but GraphHopper isn't taking care about. Please look here:
https://graphhopper.com/maps/?point=51.247804%2C7.145163&point=51.248805%2C7.149337&locale=de-DE&vehicle=bike&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale
The street "Pfalzgrafenstraße" is open into both directions for cyclists, but there is this turn restriction: https://www.openstreetmap.org/relation/7684184

**Comment by karussell** [comment]
You can consider turn costs in your own setup. We do not consider them for our API as you can always get off the bike and act as a pedestrian.
