### ISSUE TITLE
Improved release cycle

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1285]
Our aim should be more frequent releases. The best thing would be if we could tag certain commits and everything else is done from e.g. travis. A new release is then also automatically created on github.

This is possible with this procedure (completely without the release plugin) stolen from [here](https://axelfontaine.com/blog/dead-burried.html):

 * use `${revision}` in version field for all pom.xml files and use 
`<revision>0.10-SNAPSHOT</revision>` in properties as default
 * make it possible for travis to deploy to maven central if a commit is tagged. If we make gpg working this should be easy, see e.g. [here](https://dracoblue.net/dev/uploading-snapshots-and-releases-to-maven-central-with-travis/).
 * specify `-Drevision=0.9.$TRAVIS_BUILD_NUMBER` when deploying to maven central to overwrite the snapshot. Or we could use the git tag of the commit: `-Drevision=$TRAVIS_TAG`!
 
It was a bit tricky but it [seems to work](https://travis-ci.org/graphhopper/graphhopper/jobs/341437512).

**Comment by devemux86** [comment]
I had made Mapsforge / VTM to deploy snapshots to Sonatype OSS Repository Hosting with each successful commit in `master`.
If you're interested can check [.travis.yml](https://github.com/mapsforge/vtm/blob/master/.travis.yml) and [deploy.gradle](https://github.com/mapsforge/vtm/blob/master/deploy.gradle), though it's Gradle!
It was straightforward as Travis calls the same command, like when publish regular releases to Maven Central.

**Comment by karussell** [comment]
We already publish snapshots: https://github.com/graphhopper/graphhopper/blob/master/.travis.yml#L55

**Comment by karussell** [comment]
A minor tweak in your IDE might be necessary. E.g. I saw this:

![intellij-maven-report](https://user-images.githubusercontent.com/129644/36344458-cc48427c-141a-11e8-93dc-54dfe4570cfd.png)


See [this unresolved issue](https://youtrack.jetbrains.com/issue/IDEA-67322).

Ignore this via File->Settings->Editor->Inspections->Maven->Usage of properties in parent description

![ignore-report-parent-description](https://user-images.githubusercontent.com/129644/36344455-c347d6a6-141a-11e8-8b2f-3ab7c7f4fc16.png)

**Comment by karussell** [comment]
Although we solved most issues I have still trouble to get downstream dependencies working. They still report about missing SNAPSHOT versions like:

Could not find artifact com.graphhopper:graphhopper-reader-osm:jar:0.11-20180226.110244-2 in sonatype-snapshots

and so I'll try to avoid the revision variable and instead set the version explicitly before deployment via:

mvn versions:set -DnewVersion=$TRAVIS_TAG -DgenerateBackupPoms=false

**Comment by karussell** [comment]
This works: https://travis-ci.org/graphhopper/graphhopper/jobs/346514608

Advantages: no IntelliJ warning necessary and no downstream tooling problems expected

Disadvantages: none compared to the "revision"-approach IMO. But similarly to the "revision" approach we do not store the version in the pom.xml directly, only via a tag and so all versions of a freshly cloned repo are X-SNAPSHOT.

**Comment by boldtrn** [comment]
Nice this looks a lot cleaner!

**Comment by karussell** [comment]
merged
