### ISSUE TITLE
Cannot use dependency due to new release management

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1288]
Introduced in #1286

We now get:

```
Failed to collect dependencies at com.graphhopper:graphhopper-reader-osm:jar:0.10-SNAPSHOT: Failed to read artifact descriptor for com.graphhopper:graphhopper-reader-osm:jar:0.10-SNAPSHOT: Failure to find com.graphhopper:graphhopper-parent:pom:${revision} in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```

for all projects trying to use the dependencies at e.g. maven central. Which is ugly and could be fixed with a 'flat' pom: https://maven.apache.org/maven-ci-friendly.html

Related: http://blog.kiwitype.com/2017/maven-versioning-in-a-continuous-delivery-pipeline/

**Comment by karussell** [comment]
Nice, this plugin seems to fix the problem!

**Comment by cojalvo** [comment]
any idea how to fix it in android? when using gradle?

**Comment by karussell** [comment]
@cojalvo this is currently discussed, please join if you have an idea :) https://discuss.graphhopper.com/t/gradle-project-sync-failed-in-android-studio-3-0-1/2845/7
