### ISSUE TITLE
Docker is broken

### ISSUE THREAD

**Issue by legraina** [graphhopper/graphhopper#1289]
I've pulled the latest docker image, and it doesn't work anymore.
Here the error I have:
Error: Unable to access jarfile ./web/target/graphhopper-web-${revision}-with-dep.jar

**Comment by karussell** [comment]
Probably related to #1286

**Comment by karussell** [comment]
Ah, we have to adapt graphhopper.sh script too https://github.com/graphhopper/graphhopper/commit/b8574f1caef42709983b2cb46bff44fb75282a96

**Comment by legraina** [comment]
If you need help to fix the docker, do not hesitate to ask :)

**Comment by karussell** [comment]
With this fix it should work. The dockerfile is updated automatically I think and you have access to dockerhub repo, right (?)

**Comment by legraina** [comment]
No I don't, but I will pull the latest Docker

**Comment by karussell** [comment]
Strange, you should have some collaborating advantages ;)

![image](https://user-images.githubusercontent.com/129644/36285784-43cd595a-12ad-11e8-897f-a4fe34de5d17.png)

**Comment by legraina** [comment]
Yes, you're right I have some advantages. Also, I've tested the docker image and it works perfectly well now. Thanks

**Comment by karussell** [comment]
Great!
