### ISSUE TITLE
Cannot run builds via graphhopper.sh

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#1299]
I am seeing an issue with the new release management and graphhopper.sh. 

Running `mvn clean test verify` works as usual. 
Running `./graphhopper.sh build` or `mvn --projects tools -am -DskipTests=true package`.
Running `mvn DskipTests=true package` works.

The error message is:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.0.0:single (make-assembly) on project graphhopper-tools: Failed to create assembly: Unable to resolve dependencies for assembly 'jar-with-dependencies': Failed to resolve dependencies for assembly: Unable to get dependency information for com.graphhopper:graphhopper-tools:jar:0.11-SNAPSHOT: Failed to process POM for com.graphhopper:graphhopper-tools:jar:0.11-SNAPSHOT: Non-resolvable parent POM for com.graphhopper:graphhopper-tools:0.11-SNAPSHOT: Could not find artifact com.graphhopper:graphhopper-parent:pom:0.11-SNAPSHOT and 'parent.relativePath' points at wrong local POM
```

I guess we cannot just change the ./graphhopper.sh to just use mvn package without selecting projects?

**Comment by karussell** [comment]
I think the problem here is more the switch to 0.11-SNAPSHOT. Building just tools does not build the parent and when you tried this there might be no parent in version 0.11-SNAPSHOT, now this works fine for me

> I guess we cannot just change the ./graphhopper.sh to just use mvn package without selecting projects?

This will take longer but will be done in #1108

**Comment by karussell** [comment]
I'm trying to reproduce this issue - can you help? 

The following does **not** fail for me:

rm -rf ~/.m2/repository/com/graphhopper/graphhopper-parent/
rm -rf ~/.m2/repository/com/graphhopper/graphhopper-tools*
mvn --projects tools -am -DskipTests=true clean package

Even adding `-U` in the last step succeeds. Which maven version do you use? I have 3.5.0 locally.

**Comment by boldtrn** [comment]
Even this fails for me:
```
mvn -DskipTests=true clean package  <-- (builds successful)
mvn --projects tools -am -DskipTests=true clean package  <-- (fails)
```

I run Maven 3.3.9, installed via apt on Ubuntu 16.04. I tried this on multiple machines with the same setup, it fails on all machines.

**Comment by karussell** [comment]
Ok, we'll switch to a deployment method that should leave the rest of the build process unaffected but has the same advantages of the simple deployment process: https://github.com/graphhopper/graphhopper/issues/1285#issuecomment-368661130

Can you try if this branch works for you?

**Comment by karussell** [comment]
This should be fixed now ;)
