### ISSUE TITLE
Restriction no_entry not working.

### ISSUE THREAD

**Issue by AllroadsNL** [graphhopper/graphhopper#1302]
Not working.
Not often used method for some traffic signs, but

restriction:motorcar | no_entry

The only one in the Netherlands
http://overpass-turbo.eu/s/wy6 

I saw this situation.
[Situation routing failure](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=52.09649%2C5.42403%3B52.09700%2C5.42025)

[relation](https://www.openstreetmap.org/relation/3478910)

**Comment by karussell** [comment]
Couldn't this simply be modelled as a oneway or as multiple normal turn restrictions? I do not understand why there has to be another OSM tag for this, especially since it is used so rarely I fear we would not have a high priority to implement this.

**Comment by AllroadsNL** [comment]
It could, .......................but the possibility to tag this way, as it is done, shall always be there.
High  ... low priority, it is a issue.

The need to take it in the development flow of all other restriction, graphhopper decide when.

**Comment by boldtrn** [comment]
> Couldn't this simply be modelled as a oneway or as multiple normal turn restrictions?

It shouldn't be modeled as a oneway IMHO. There are regular roads that you are not allowed to access from one side, but you can turn around and drive back at any time (which would not be allowed on oneways). For example at 48.887114, 7.665231; also see [Google Streeview](https://goo.gl/maps/B6Cv7qfz3DA2). It is tagged as oneway in Google Maps, but not in OSM. OSM tagged the restriction with no_entry, which I think reflects the local situation.

It could be replaced with turn restrictions though. This would make it easier for routers. 

This tags seems not to be heavily used ([about 500-600 times](https://taginfo.openstreetmap.org/search?q=restriction%3Dno_entry)). There is also the restriction no_exit which is [used about 200 times](https://taginfo.openstreetmap.org/search?q=restriction%3Dno_exit).

**Comment by AllroadsNL** [comment]
> Couldn't this simply be modelled

> It shouldn't be modeled as a oneway IMHO

It is not a oneway, the undersign says that people with a (permit, licence) can entry_in, use it in this direction. (both direction)
It could be done with *:forward=no, on 10 meter of way or on a node with direction key, tagging the traffic_sign.

From the other side you can drive the road with a motorcar and turn the car on road and drive back, close to back of this traffic_sign.

this traffic_sign, means, motorvehicle with more than two wheels, by law mofa, moped is not a motorvehicle.

we should even change [the access to](https://wiki.openstreetmap.org/wiki/Proposed_features/License) *:forward=

> during discussion on the talk list some people proposed access=permit
others raised the concern that this is to similar to access=permissive and proposed access=permit_required


[undersign situation](https://www.mapillary.com/map/im/Dc20ONm-r3BdY-O12A0Nkgl)
