### ISSUE TITLE
Add distance path detail

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1305]
We already have time and to avoid client side distance calculation we could easily offer this

**Comment by jguthrie100** [comment]
Is distance not already included?

`{distance=92.254, heading=208.42, sign=0, interval=[0, 3], text=Continue onto Eichborndamm, time=7377, street_name=Eichborndamm}`

**Comment by karussell** [comment]
distance as path details which means even greater detail not just per turn instruction

**Comment by karussell** [comment]
Fixed via #1339
