### ISSUE TITLE
NPE for public transit

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1311]
See discussion here: https://discuss.graphhopper.com/t/2913

`{"vehicle":"pt","weighting":"short_fastest","point":["42.4448765,-76.4808143","42.4301429,-76.5082167"],"points_encoded":false,"pt.arrive_by":false,"ch.disable":true,"pt.walk_speed":3,"pt.earliest_departure_time":"2018-03-15T14:49:15.303Z","pt.profile":true,"pt.limit_solutions":6}`

```
java.lang.NullPointerException\n\tat com.graphhopper.reader.gtfs.Label$1$1.next(Label.java:120)\n\tat 
com.graphhopper.reader.gtfs.Label$1$1.next(Label.java:105)\n\tat 
java.lang.Iterable.forEach(Iterable.java:74)\n\tat 
com.graphhopper.reader.gtfs.TripFromLabel.getTrip(TripFromLabel.java:130)\n\tat 
com.graphhopper.reader.gtfs.GraphHopperGtfs$RequestHandler.parseSolutionsAndAddToResponse(GraphHopperGtfs.java:219)\n\tat 
```

**Comment by michaz** [comment]
Argh, that's a tough one that goes all the way down to graph construction.
I somehow manage to create a graph which has an edge from A to B, and an edge _with the same number_ from B to C. Reproducibly. In the datastore.

Tracing this now.

**Comment by michaz** [comment]
Apparently, during graph constructing, we cannot add transit _after_ having removed disconnected network components.

I'm doing that as the _last_ step now instead, which is _probably OK in most cases_.

Closing this, as the NPE is definitely gone, and will keep an eye on whether the change matters in unexpected ways.

**Comment by karussell** [comment]
Thanks!

> Apparently, during graph constructing, we cannot add transit after having removed disconnected network components.

This should be allowed or did you mean that adding transits should not be allowed after this step? If that is the case you could call `graphHopperStorage.freeze()` to ensure this.

**Comment by michaz** [comment]
No, this: #1313
