### ISSUE TITLE
Method name AllEdgesIterator.getMaxId() does not describe intention

### ISSUE THREAD

**Issue by michaz** [graphhopper/graphhopper#1321]
The comment says:
```
the maximum edgeId in the graph which is roughly the number of edges
```

I think "roughly" refers to the possibility of edges being marked for deletion.
I also think this is the reason why this method was named like it was, and not e.g. ``size()`` or ``nEdges()``.

However, the maximum edgeId in the graph is precisely what this method does _not_ return. It returns maximum edgeId + 1. This is relied upon in ``QueryGraph``, where ``getMaxId()`` is in fact the first edge id ``QueryGraph`` thinks it can use.

Hence, when I implement ``Graph``, take the method's name literally (which I did), and use a ``QueryGraph`` on it, I get a duplicate edge id.

Would recomment ``size()`` or ``length()``, see ``java.util.BitSet``.

**Comment by karussell** [comment]
`size` would be confusing as well IMO, length is better. It was `count` at some point: https://github.com/graphhopper/graphhopper/issues/466
