### ISSUE TITLE
Reimplement block_area with LocationIndexTree instead of graph traversal

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1324]
There are several limitations with the current approach and so we should use a better node search

Discussed partially in https://github.com/graphhopper/graphhopper/pull/1306#discussion_r177076643

Failing examples likely caused by this bug: https://discuss.graphhopper.com/t/4747 and https://discuss.graphhopper.com/t/3415 and https://discuss.graphhopper.com/t/3680

Also what should happen if the area is outside of the graph - should we silently ignore this, because the area does just not contain any graph or is this a "bad request"?

**Comment by michaz** [comment]
Subtask: ``LocationIndexTree`` needs a ``query(Envelope envelope)`` or ``query(BBox bbox)`` method to get everything within a bounding box.

Also required for getting the isochrones right.

**Comment by VanDerLars** [comment]
A fast fixing would be appreciate ;)

**Comment by karussell** [comment]
Have now a [working prototype](https://github.com/graphhopper/graphhopper/compare/loc_idx_changes) and will try to condense this in a clean pull request. Have still to test it world wide.
