### ISSUE TITLE
Disabling CH does not work after dropwizard changes.

### ISSUE THREAD

**Issue by ammagamma** [graphhopper/graphhopper#1337]
Uncommenting the `prepare.ch.weightings: no` line in `config.yml` should disable CH preparation, but somewhere during the parsing of the file the 'no' gets turned into a 'false' string (in the configuration passed to the `GraphHopperManaged` constructor) causing an `IllegalArgumentException` `weighting false is not supported` in `GraphHopper#createWeighting`.

**Comment by michaz** [comment]
Welcome to issue number ``1337`` by the way.
