### ISSUE TITLE
how to change graphhopper logging level for dropwizard

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1342]
As discussed in #1330 it is important to know how to configure logging for com.graphhopper package. When I use:

```yml
logging:
  level: DEBUG
  loggers:
    com.graphhopper: DEBUG
```

in the config.yml and add the following to GraphHopperDebugApplication.initialize:

```java
Logger logger = LoggerFactory.getLogger(getClass());
logger.warn("test warn");
logger.info("test info");
logger.debug("test debug");
```

and then grep starting the server against "test" via 
`./graphhopper.sh webdebug ~/Downloads/berlin-latest.osm.pbf | grep test`

I'm just getting the same which I get for the unchanged config:

WARN  [2018-04-13 08:26:37,700] com.graphhopper.http.GraphHopperDebugApplication: test warn

I would have expected an output for info and debug too.

**Comment by michaz** [comment]
I would guess that during ``Application.initialize`` is approximately the only place where you ``can't`` log yet because the config isn't even parsed yet.

**Comment by karussell** [comment]
Hmmh, that could make sense. But why is `com.graphhopper` only WARN and the rest is INFO?

```
WARN  [2018-04-15 11:58:34,897] com.graphhopper.http.GraphHopperApplication: test warn
INFO  [2018-04-15 09:58:35,605] org.eclipse.jetty.util.log: Logging initialized @1541ms to org.eclipse.jetty.util.log.Slf4jLog
INFO  [2018-04-15 09:58:35,713] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
```

**Comment by michaz** [comment]
Are you still talking about what happens during ``Application.initialize``? I have no idea, as far as I am concerned, it's unspecified what happens there.
