### ISSUE TITLE
Strange bike routing - does not use foot/bike path

### ISSUE THREAD

**Issue by omicron81** [graphhopper/graphhopper#1352]
I see a very strange bike route where the combined foot/cycle path is not used:
https://graphhopper.com/maps/?point=51.508632%2C7.388681&point=51.508656%2C7.38925&point=51.509213%2C7.390779&locale=de&vehicle=bike&weighting=fastest&elevation=true&use_miles=false&layer=TF%20Cycle

I would expect a straight line from the start point to point 1. (Yellow line in the screenshot)
![screenshot-2018-4-25 graphhopper maps - driving directions](https://user-images.githubusercontent.com/8233992/39258857-4a63ca9a-48b5-11e8-8346-9fd5e50a5d3d.png)

I've seen this also on [osm.org](https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=51.50864%2C7.38863%3B51.50926%2C7.39098) and in the Android app "Komoot".

I don't know since when this happens, but a few months ago it worked as expected.

**Comment by karussell** [comment]
It is a data issue (path not reachable due to missing street part nearby the one-way). Obvious as other routers have the same problem

**Comment by ratrun** [comment]
I just fixed the data issue.

**Comment by karussell** [comment]
Thanks @ratrun!
