### ISSUE TITLE
should the DouglasPeucker be used for the whole geometry instead of only pillar nodes?

### ISSUE THREAD

**Issue by zhiqiangZHAO** [graphhopper/graphhopper#1353]
I found in the OSMReader, 
simplifyAlgo.simplify(pillarNodes);

I feel it's better to apply DouglasPeucker to the whole edges.
Guess it could reduce more unnecessary points.

**Comment by boldtrn** [comment]
> I feel it's better to apply DouglasPeucker to the whole edges.
Guess it could reduce more unnecessary points.

Interesting, I think you are right. DouglasPeucker should not remove the first and last point, so we would only simplify pillar nodes, but consider the whole geometry including tower nodes, which could save up to two coordinates per edge.

**Comment by karussell** [comment]
Indeed, this could work. Still we would have to check all of the failing tests.

**Comment by zhiqiangZHAO** [comment]
I found this problem when I found a very rare case: duplicated lat/lon of the first node and second node . (anything could be true for OSM, 🤷‍♂️ ) Then I am curious why the DouglasPeucker doesn't remove the second node.

**Comment by zhiqiangZHAO** [comment]
another question about DouglasPeucker, if the road is a z shape line.
__________________________
                                        /_________________________
It seems DouglasPeucker will remove the z structure. 
Might not be a concern for road networks.

**Comment by boldtrn** [comment]
Douglas Peucker can remove details from a road, yes, but this should be only minimal, also see the [Wiki about DP](https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm). If you think our implementation of DP is erroneous, it would be great if you could provide a sample test case (in a different issue :) or in our forum).
