### ISSUE TITLE
OSM data sometimes contains zero weight loops

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#1355]
OSM sometimes contains loop edges with zero distance leading to warnings like this:

     `Setting weights smaller than 0.001 is not allowed in CHGraphImpl#setWeight. You passed: 0.0 for the edge 10723709 from 51.439458536493596,7.000066310168795 to 51.439458536493596,7.000066310168795`

For edge-based CH #1247 this can be problematic and since these edges have no real meaning for routing (?) the best option might be to remove them during the graph import.

**Comment by karussell** [comment]
Yes, for OSM 'bugs' removing is an option but still you can have Weightings that somehow make this 'mistake'. So it is also related to the fact that we should use a list of Weightings where possible instead of a list of FlagEncoders. E.g. for subnetwork removal and things like LocationIndex #729.

**Comment by karussell** [comment]
>> So it is also related to the fact that we should use a list of Weightings where possible instead of a list of FlagEncoders

> Hmm, not sure what you mean here ? Is this related to the ongoing encoder refactoring ?

Kind of, yes. I meant the fact that we currently use FlagEncoder everywhere where the Weighting would make more sense, as different Weightings could apply different accessibility.

> Ok, but this does not make any sense, right ?

What was again the problem with weight==0 for CH @boldtrn? A zero weight should be ok for Dijkstra as it would be just 'a neutral hop'? The only problem I found was that through rounding errors a value>0 could end up as value==0. But still then the question is: what is the problem with that?

**Comment by boldtrn** [comment]
> What was again the problem with weight==0 for CH @boldtrn?

This is related to #1032 and #1013.

I have seen very odd results with weight=0 and CH. I remember an issue with VirtualEdges and Instructions.

**Comment by ammagamma** [comment]
> A zero weight should be ok for Dijkstra as it would be just 'a neutral hop'? The only problem I found was that through rounding errors a value>0 could end up as value==0. But still then the question is: what is the problem with that?

Yes I think normal Dijkstra handles this without a problem except that the route can randomly include or exclude the neutral loop. The problem I am having is very specific to the contraction in edge-based CH, e.g. [here](https://github.com/ammagamma/graphhopper/blob/360ef034d093eb9de779d06f7c060405d70a5e8f/core/src/test/java/com/graphhopper/routing/ch/EdgeBasedNodeContractorTest.java#L1141) (note that this assumes even two zero distance loops at the same node)

**Comment by karussell** [comment]
Understood. 

When we completely forbid this, then we would make current workarounds like [this](https://github.com/graphhopper/graphhopper/blob/master/reader-osm/src/main/java/com/graphhopper/reader/osm/OSMReader.java#L383) impossible (barriers via zero length edges)

The problem in your case *might be* that t=s/v and if v==0 we get t=infinity and all is fine (as this is usually handled in the Weighting), but if 0/0 this will lead to NaN, see https://github.com/graphhopper/graphhopper/issues/432#issuecomment-107996025

**Comment by ammagamma** [comment]
Ah ok, I did not know about this workaround and was hoping we can simply exclude the zero distance loops. I will see if I can come up with another solution and we can see if this is still an issue when turn cost enabled CH gets merged.

**Comment by karussell** [comment]
We could also artificially set the distance to a small value in case of these barriers (like an elevation difference)

**Comment by karussell** [comment]
I was wrong regarding the barriers: they are implemented as zero-**distance** edges but we block access for all vehicles. So they should not make an issue here if access is tested via EdgeFilter.

**Comment by easbar** [comment]
Edge-based CH was adjusted to handle zero weight loops. Closing for now.
