### ISSUE TITLE
Server launch Java help

### ISSUE THREAD

**Issue by jskidd3** [graphhopper/graphhopper#1369]
`java -jar *.jar jetty.resourcebase=webapp config=config-example.properties osmreader.osm=great-britain-latest.osm.pbf`

How can I modify this command so that my Ubuntu server does not stop the server once the terminal is closed (or shortly after)?

**Comment by karussell** [comment]
Question should go to our forum. If you want to run the master branch please note that the call has changed: https://github.com/graphhopper/graphhopper/pull/1365/files#diff-c498980ed840c21ad4280a3687578c7aR44
