### ISSUE TITLE
API key usage in client-hc

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1373]
There was likely some misusage or heavy usage of the API key and with hiding in the travis settings this can be avoided: https://github.com/graphhopper/graphhopper/commit/50e975bd079fe22058052574fb8e82c3e83c27e9

But now the build always fails locally without this parameter

**Comment by karussell** [comment]
Not sure if this is the best solution. Will revert if it makes problems.

**Comment by devemux86** [comment]
Does it mean that now cannot build locally the `client-hc` module, like installing in local Maven repository?

**Comment by karussell** [comment]
You can build it like:

```
mvn -P include-client-hc clean install -Dkey=<API_KEY>
```

or without api key (no tests!):

```
mvn -P include-client-hc  clean install -DskipTests=true
```

**Comment by devemux86** [comment]
Thanks, will need to find a way to include it then in IDEA process when building an instance of whole GraphHopper.
(no tests needed at that time)

**Comment by karussell** [comment]
To avoid calling the command line? You can see here https://stackoverflow.com/q/24760387/194609

But if this makes more problems then helps we have to find a different solution

**Comment by karussell** [comment]
Probably it is cleaner to just skiping the tests? https://stackoverflow.com/q/772735/194609

**Comment by devemux86** [comment]
Skipping Maven tests in IDEs is straightforward, as all usually provide UI buttons for that.

Will need to see how can automate the explicit inclusion of `client-hc` now, so not having to remember command lines or worse build GraphHopper and forget some modules with older version. :slightly_smiling_face:

**Comment by karussell** [comment]
This needs a different fix as it causes problems in the IDE and elsewhere.
