### ISSUE TITLE
drop jsonp support?

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1375]
Either document that we dropped jsonp support (and remove the [remaining code](https://github.com/graphhopper/graphhopper/search?utf8=%E2%9C%93&q=jsonp)) or implement it fully again after the dropwizardification.

**Comment by michaz** [comment]
In favor of dropping it from _this_ code, and if we really really want to keep it on the production API, somehow implement it "from outside".

**Comment by karussell** [comment]
Yes, let's remove it.
