### ISSUE TITLE
Foot routing doesn't use crossing and ignores foot=no

### ISSUE THREAD

**Issue by Discostu36** [graphhopper/graphhopper#1377]
https://graphhopper.com/maps/?point=54.325611%2C10.115705&point=54.32631%2C10.114567&locale=de&vehicle=foot&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale

The routing algorithm doesn't consider the crossings at the sides of the intersection. The middle of the intersection is even tagged as "foot=no" but this seems to be ignored.

Correct routing would be like this:
https://graphhopper.com/maps/?point=54.325611%2C10.115705&point=54.326004%2C10.115259&point=54.32631%2C10.114567&locale=de&vehicle=foot&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale

**Comment by Discostu36** [comment]
https://graphhopper.com/maps/?point=54.325597%2C10.115694&point=54.326263%2C10.114616&locale=de&vehicle=foot&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale

Well.... at least it doesn't route over the foot=no anymore. But I don't understand why it doesn't route here at all now.

**Comment by karussell** [comment]
Wörthstraße is not connected to [the paths](https://www.openstreetmap.org/directions?engine=graphhopper_foot&route=54.32583%2C10.11528%3B54.32581%2C10.11530#map=19/54.32568/10.11614).

**Comment by Discostu36** [comment]
OK, so this was the problem the whole time. Sorry.
