### ISSUE TITLE
Reduce usages of DefaultEdgeFilter(encoder, true, false)

### ISSUE THREAD

**Issue by ammagamma** [graphhopper/graphhopper#1380]
We often do something like 
``` java
graph.createEdgeExplorer(new DefaultEdgeFilter(encoder, false, true));
```
(about 35 times in the current master). I've done this myself quite a few times and everytime I need to check if I got the flags right. Therefore I would suggest to add two or three static factory methods to `DefaultEdgeFilter`: `DefaultEdgeFilter.inEdges(FlagEncoder)`, `DefaultEdgeFilter.outEdges(FlagEncoder)` and optionally `DefaultEdgeFilter.allEdges(FlagEncoder)`. The last one is what the default constructor does, but would be more readable in my opinion.

**Comment by karussell** [comment]
Yes, please - this is a good idea. This would also solve the ugliness in #1112 where I swapped the booleans (as fwd,bwd is more intuitive) but this would brake all usages without being noticed.
