### ISSUE TITLE
Real edge ids in path details

### ISSUE THREAD

**Issue by michaz** [graphhopper/graphhopper#1384]
May I request the "breaking" change that the ``edge_id`` path detail contain real edge ids, also for the first/last split edges?

Something like

```
if (edge instanceof VirtualEdgeIteratorState) {
   edgeId = GHUtility.getEdgeFromEdgeKey(((VirtualEdgeIteratorState) edge).getOriginalTraversalKey());
} else {
   edgeId = edge.getEdge();
}
```

**Comment by michaz** [comment]
I think that would be totally consistent with everything, since the path details API is specifically about "things which are true between some point and some other point on a path", and in this case, this is "the real edge I am on". It cannot be mistaken for the claim that the whole link is travelled, so it's okay to return a real edge id even though we travel only a part of it.

**Comment by karussell** [comment]
Ok, sounds acceptable to me too :)
