### ISSUE TITLE
android build broken

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1385]
There is a problem because of #1378. After https://github.com/graphhopper/graphhopper/commit/04514f24ba479538dc6a0de8c072fd108eb1a557 the Android apk fails to build.

There are two new dependencies jaxws-api and javax.ws.rs-api in `android` now and IMO this results in problems. With:

```
cd android/app
mvn package android:deploy
```

you will get:

```
...
[INFO] --- android-maven-plugin:4.5.0:dex (default-dex) @ graphhopper-android ---
[INFO] Convert classes to Dex : /home/peter/Documents/quell/graphhopper/android/app/target/classes.dex
[INFO] 
[INFO] PARSE ERROR:
[INFO] unsupported class file version 53.0
[INFO] ...while parsing META-INF/versions/9/javax/xml/bind/ModuleUtil.class
[INFO] trouble processing "javax/xml/soap/AttachmentPart.class":
....
```

It seems that these dependencies are compiled with JDK 9 [which is not possible when using Android](https://stackoverflow.com/a/47627603/194609) at the moment. Android does [not even support all 8 features](https://developer.android.com/studio/write/java8-support).

btw: I wonder what [this openjdk Android port](http://openjdk.java.net/projects/mobile/android.html) is about.

**Comment by michaz** [comment]
https://firebase.google.com/docs/test-lab/

:-)

**Comment by michaz** [comment]
Or maybe a Travis build would be enough for starters:

https://docs.travis-ci.com/user/languages/android/

**Comment by karussell** [comment]
Travis has problems with mixing recent JDKs and Android: https://github.com/travis-ci/travis-ci/issues/8513 (it looks only closed - it is not fixed!)

But as we have our own magic to fetch openjdk10 etc we could probably try `language:android` ...

**Comment by karussell** [comment]
Compiles now - thanks! Will try to resurrect our Android deployment on a dedicated server and see if this is also runnable on Android.

As it now gets a bit crowded module-wise :) ... would you mind to add a (different) description and name to these modules and can you roughly explain why we need two api modules?

**Comment by michaz** [comment]
This is what we were just talking about, the JSON representation going in its own module.

**Comment by devemux86** [comment]
From a quick look there are javax dependencies also in client-hc and in its transitive web-api module. So if using client-hc on Android, could fail again like @karussell reported?

**Comment by michaz** [comment]
Argh yes, but it doesn't really need to be there, will fix tomorrow.
