### ISSUE TITLE
Traveling on water / getting to a ferry takes too much time

### ISSUE THREAD

**Issue by CottageCheesee** [graphhopper/graphhopper#1387]
We are using graphhoper to learn the distance for travelling from one point to another and we encountered this scenario when duration needed to travel is enormously high when moving via water. 

In this example, travelling 144km takes more than a day and mainly because of two points taking 10-20hours each. Both points seem to be the first steps when departing from an island to a ferry.

link:
https://graphhopper.com/maps/?point=Mykonos%20Island%20National%20Airport%2C%2084600%2C%20Klouvas%2C%20Greece&point=Santorini%2C%20Greece&locale=en-us&vehicle=car&weighting=fastest&elevation=false&use_miles=false&layer=Omniscale

I was searching for already open issue tickets regarding this situation, so maybe I'm not duplicating it right now. :) Thanks for the help!

**Comment by boldtrn** [comment]
If there is [no duration](https://www.openstreetmap.org/way/184793322) tagged on ferries, there is no way to provide accurate travel times. GraphHopper assumes a slow speed ferry then. For general discussions or questions, please use our [forum](https://discuss.graphhopper.com/).
