### ISSUE TITLE
Longitude-latitude order suggestion

### ISSUE THREAD

**Issue by araichev** [graphhopper/graphhopper#1394]
In the Graphhopper web API, i think it would be more natural to specify geographic coordinates in longitude-latitude order, rather than the latitude-longitude order currently required.
This would match the GeoJSON specification and hence the coordinate order output in Graphhopper GeoJSON responses, e.g. in the isochrone responses.

**Comment by karussell** [comment]
We plan to introduce a GeoJSON request schema via POST with an **array** [lon,lat]. The URL request will remain a **string** lat,lon
