### ISSUE TITLE
Public transport performance

### ISSUE THREAD

**Issue by JanJakes** [graphhopper/graphhopper#1396]
Hi, I've been playing with public transport routing and I've tried to import a large dataset (Europe) from OSM with three cities in GTFS (Berlin, Prague, Rome). Then I've tried two nearby (max. a few km) points in one of the cities but the performance was very poor - response times about `1 minute` and always `1000000` visited nodes.

Here's a query example: `/route?point=50.015461,14.442215&point=50.10203,14.26482&pt.earliest_departure_time=2018-06-15T07%3A14%3A39Z&arrive_by=false&pt.max_walk_distance_per_leg=1000&pt.limit_solutions=5&locale=en-US&vehicle=pt&elevation=false&use_miles=false&points_encoded=false&pt.profile=true`

Here's my import command:
```
java -Xmx80g -Xms80g
    -jar graphhopper-web-0.10.0-with-dep.jar
        datareader.file=/data/europe-latest.osm.pbf
        gtfs.file=/data/berlin_gtfs.zip,/data/prague_gtfs.zip,/data/rome_gtfs.zip
        graph.flag_encoders=pt
        prepare.ch.weightings=no
        graph.location=/data/graph-cache
        import
```

This was taken from the docs. Is the `prepare.ch.weightings=no` any important for the performance here? I just copy-pasted the docs...

Also, when I remove `pt.profile=true` I get `java.lang.NullPointerException` on every request.

Thanks!
Jan

**Comment by michaz** [comment]
Is this about performance, or about getting it to work in the first place?I 

1000000 visited nodes looks like

**Comment by JanJakes** [comment]
Yes, I did. I mean, I didn't really look that much into the returned results but it was definitely able to find public transport route between the two points in a city. I've already shut down the instance I was running this experiment on but I can run it again if you need more info.

Btw. there's a link to public transport demo on the [blog](https://www.graphhopper.com/blog/2018/05/16/real-time-public-transit-routing/) and looking at the calls (i.e. http://graphhopper-trimet.eu-central-1.elasticbeanstalk.com/route?point=45.5138%2C-122.576&point=45.5679096098613%2C-122.5552797317505&weighting=fastest&pt.earliest_departure_time=2018-06-17T17%3A20%3A07Z&arrive_by=false&pt.max_walk_distance_per_leg=1000&pt.limit_solutions=5&locale=en-US&vehicle=pt&elevation=false&use_miles=false&points_encoded=false&pt.profile=true) there are also high numbers of visited nodes. Now, if you remove `pt.profile=true` you get to even higher numbers and the response is pretty slow.

I'm running these experiments because I know Graphopper is incredibly fast even when working with full planet, so I wanted to test how it works with large areas and public transport.

**Comment by michaz** [comment]
Thanks for pointing out that the default query is currently the slowest. I'd better change that, I guess.

**Comment by JanJakes** [comment]
Thanks for the explanation. From the README it wasn't clear to me that public transport is rather experimental at the moment.

**Comment by michaz** [comment]
The core of it is actually pretty stable and I'm confident about it. It's "just" the user-facing part, like using sensible defaults, that's unfinished. Your input was a very helpful reminder.

**Comment by karussell** [comment]
@michaz as you fixed this in the code can we close here?

**Comment by michaz** [comment]
@karussell Yes, this

> At the moment, it's indeed almost always super-slow. Previously, it was bounded by the time it would take to walk, but that's not in at the moment.

is fixed, which was the root problem of this ticket.

I'm still leaving cut-offs or heuristics out of the code which may lead to unexpected runtimes.
