### ISSUE TITLE
display timestamp of indexed osm-data

### ISSUE THREAD

**Issue by ghost** [graphhopper/graphhopper#140]
I miss a timestamp on http://graphhopper.com/maps/ of the user osm-data. Could be useful to see it. Regards Johannes

**Comment by jojo4u** [comment]
Is there now some timestamp of routing data on https://graphhopper.com/maps/ ? I can't fine one.

**Comment by karussell** [comment]
It is in GraphHopper but not yet available in the UI or on GH Maps. And the import process had some minor import issues lately (which we [fixed](https://github.com/graphhopper/graphhopper/commit/9e74b26c6073bd8e373d28c67ab0a6a7c4790623)) but therefor the data is 5 days old. Normally you can assume 24h
