### ISSUE TITLE
Shortcut ignored / Weird routing (perturbation from a turning restriction?)

### ISSUE THREAD

**Issue by Codain** [graphhopper/graphhopper#1402]
I found strange routing at following junction: https://graphhopper.com/maps/?point=47.908144%2C-122.292863&point=47.912114%2C-122.292219&locale=fr&vehicle=car&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale

Shortcut is ignored in all modes (car, foot, bike) on GH online website.

On OSM website the routing with GH is even more strange:
https://www.openstreetmap.org/directions?engine=graphhopper_car&route=47.89912%2C-122.29123%3B47.91643%2C-122.29258#map=18/47.90985/-122.29273

The only thing I can observe in the mapping is that this node as a turning restriction:
https://www.openstreetmap.org/node/4795528254

I would expect GH to respect the turning restriction (i.e. don't propose to turn right) and to propose to use the shortcut (i.e. exit WA 525 sooner on right).

**Comment by karussell** [comment]
This is likely more a data issue. If you turn on showing the average speed: https://graphhopper.com/maps/?point=47.90654%2C-122.292713&point=47.91023%2C-122.292928&point=47.912114%2C-122.292219&details=average_speed&debug=true you see that the link is at 32km/h which is very low. Is this correct?

The difference to openstreetmap.org comes from the fact that per default they consider turn restrictions and GH maps does not. So this strange loop is used which seems to be still faster than the slow shortcut. If the speed of the shortcut is mapped correctly then I ask you to create an issue here: https://github.com/graphhopper/directions-api as we need to tweak speed calculation in our commercial layer.

Please report those problems first on our forum: https://discuss.graphhopper.com/c/graphhopper and if they turn out to be a problem either in GH core or in our commercial layer we create certain issues.
