### ISSUE TITLE
Isochrone bad request due to bucketing approach

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1411]
Currently the isochrone component has this bucketing approach which makes problems e.g. for this:

/isochrone?point=48.58792,2.44357&time_limit=900&buckets=3&vehicle=foot

or here

/isochrone?point=45.74087770,4.81895470&time_limit=120&vehicle=foot

Where the bucket 0 has too few entries to calculate the polygon. 

> message: Too few points found for bucket 0. Please try a different 'point', a smaller 'buckets' count or a larger 'time_limit'. And let us know if you think this is a bug!

**Comment by michaz** [comment]
Cannot reproduce anymore with these examples, but this one fails, and probably any other one with a small enough z-value:

/isochrone?vehicle=foot&type=geojson&point=45.74087770,4.81895470&time_limit=10

**Comment by michaz** [comment]
Only occurs in the extreme case where the time limit is so small that we really just traverse one single node, and IMO it's okay for now to throw then.

Doesn't have anything to do with buckets anymore.
