### ISSUE TITLE
Avoid building jar if --jar is provided

### ISSUE THREAD

**Issue by Damian-Badura** [graphhopper/graphhopper#1419]
I notice when I pass param **--jar graphhopper.jar**, script doesn't produce graphhopper.jar.
 ` execMvn --projects web -am -DskipTests=true package`
this is called from the script and there is no param to override .jar name.

**Comment by karussell** [comment]
The --jar parameter is used to use a custom location for the jar file and not `web/target/graphhopper-web-$VERSION.jar`

But you are right that we can skip calling packageJar in this case.
