### ISSUE TITLE
Choose foot route, when it's faster than public transport route

### ISSUE THREAD

**Issue by emfataliev** [graphhopper/graphhopper#1426]
In a case when a foot route is faster then a route on a public transport how to get the faster one? (foot route)

For example, in this case
![2018-07-24 20 09 22](https://user-images.githubusercontent.com/11090312/43154620-a2a557aa-8f7d-11e8-8ee4-a0b0388bd705.png)

What magic parameters need to be added to the query? :) Can you tell me, where I can read about the parameters of requests for routing on public transport?

**Comment by karussell** [comment]
Please use our forum for questions. (fast answer: it should usually provide the faster foot route as alternative but something forbids this in this case)
