### ISSUE TITLE
The route can not cross the bridge

### ISSUE THREAD

**Issue by elettrogandalf** [graphhopper/graphhopper#1430]
In Reggio Emilia (via Bartolo da Sassoferrato), the route can not cross the bridge over the torrent "Modolena".
This problem occurs with any vehicle: car, bicycle, on foot ...

[graphhopper](https://graphhopper.com/maps/?point=44.681924%2C10.586915&point=44.680955%2C10.589377&locale=it-IT&vehicle=car&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale) or [openstreetmap](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=44.68173%2C10.58733%3B44.68099%2C10.58924#map=16/44.6786/10.5897)

The map on openstreetmap seems correct to me, is it a bug?
Thank you!

**Comment by boldtrn** [comment]
The data was changed 2 days ago. Maybe the update needs a bit longer. I had a look at the data and could not find an issue.
