### ISSUE TITLE
Wrong edge returned in map matching result

### ISSUE THREAD

**Issue by INRIX-Trang-Nguyen** [graphhopper/graphhopper#1434]
Hallo alle,

I've submitted a question on the forum but am unsure if this is a bug in the map matching result and am raising this as an issue:
https://discuss.graphhopper.com/t/wrong-edge-returned-in-map-matching-result/3340
If this is an error on the usage, please go ahead and close this.

Thanks,
Trang

**Comment by karussell** [comment]
Please avoid creating issues if you are unsure. Also this is the wrong repo: https://github.com/graphhopper/map-matching (that's the reason we ask to submit everything into our forum first)

**Comment by INRIX-Trang-Nguyen** [comment]
Apologies for that. I see your response in the forum and will post the GPX entries. Thanks.
