### ISSUE TITLE
Could the snapped point is pillar nodes?

### ISSUE THREAD

**Issue by zhiqiangZHAO** [graphhopper/graphhopper#1439]
https://github.com/graphhopper/graphhopper/blob/1e6209b90b255171a44f57acdba8964ba6c5f6b9/core/src/main/java/com/graphhopper/routing/QueryGraph.java#L407

if the currSnapped point is the same as the point at the wayIndex, adding the currSnapped point will create a duplicate point

**Comment by karussell** [comment]
It looks like this could be the case, indeed. Which problems are caused from this and do you have a fix :) ?

**Comment by zhiqiangZHAO** [comment]
Could it be the following?
    if (!currSnapped.equals(lastPointAdded)) {
      basePoints.add(currSnapped.lat, currSnapped.lon, currSnapped.ele);
    }

**Comment by easbar** [comment]
I think this is the same as #1552 ? Was fixed in #1556. @zhiqiangZHAO can you confirm this is fixed in 0.12 ?
