### ISSUE TITLE
Allow user to adjust routes that he intends to share

### ISSUE THREAD

**Issue by jidanni** [graphhopper/graphhopper#1446]
[Here](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=24.19250%2C120.83940%3B24.18150%2C120.86580#map=16/24.1839/120.8689) we see the unnamed road has been chosen, with no way available to the
user to share the way via the named road.
![0](https://user-images.githubusercontent.com/1230959/44617638-c9dd0280-a898-11e8-90de-61bdf2eda153.jpg)

**Comment by karussell** [comment]
What is your question? Please note, that for discussion you should use our forum.

**Comment by karussell** [comment]
Ok, please use our forum for discussion.

**Comment by jidanni** [comment]
OK I made https://discuss.graphhopper.com/t/allow-influencing-route-chosen/3403 .
