### ISSUE TITLE
Routing API optimize=true incorrect result set 

### ISSUE THREAD

**Issue by naveed-butt** [graphhopper/graphhopper#1452]
Hi,

I posted this in Graphhopper forum and there was no satisfactory response from the forum on this, so here I am going to ask the question again, because it may be suited to this area rather than the forum...

I have setup graphhopper open source setup locally using [this guide](https://github.com/graphhopper/graphhopper/blob/0.10/docs/core/quickstart-from-source.md). The graphhopper instance is running smoothly on my local environment and I can call the Routing API.

But when I try to call the Routing API with `optimize=true`, it is not returning the `paths[0].points_order`, as mentioned in the [docs here](https://graphhopper.com/api/1/docs/routing/#output). I have even tried to call the same API using Postman (REST client) and the result is same, no points_order in the resulting JSON.

Here is my code to call the routing API…

```
$(document).ready(function (e) {
    jQuery.support.cors = true;

        //
        // Sign-up for free and get your own key: https://graphhopper.com/#directions-api
        //
        var defaultKey; 

        // create a routing client to fetch real routes, elevation.true is only supported for vehicle bike or foot
        _ghRouting = new GraphHopper.Routing({
            key: defaultKey, 
            host: _graphhopperHost, 
            graphhopper_maps_host: _graphhopperHost, 
            vehicle: "car", 
            optimize: true,
            instructions: false,
            elevation: false
        });
        _routingMap = createMap('routing-map');
        setupRoutingAPI();
    });
    function setupRoutingAPI() {
        //somewhere in Copenhagn
        _routingMap.setView([55.637613, 11.959697], 12);

        _routingMap.on('click', addPointOnMap);

        _routingLayer = L.geoJson().addTo(_routingMap);
        _routingLayer.options = {
            style: {color: "#00cc33", "weight": 5, "opacity": 0.6}
        };
    }

```

Can anyone tell me what am I doing wrong here?

**Comment by karussell** [comment]
Questions should go to the forum.

**Comment by naveed-butt** [comment]
This is not a question. This is a problem in the Routing API, it is not returning the correct result
