### ISSUE TITLE
bicycle=use_sidepath not recognized; preference for cycleways is off

### ISSUE THREAD

**Issue by jengelh** [graphhopper/graphhopper#1454]
https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=51.51773%2C9.94051%3B51.52776%2C9.93919#map=18/51.52173/9.94200
I'm not sure if they have their own graphhopper (and what version) or whether it is delegated to an external instance. I hope it does not matter.

The route so determined includes e.g. way 262459057, which is not allowed for bicycles due to `bicycle=use_sidepath`. Even so, the routing engine IMO should even prefer highway=cycleway over highway=primary if the time difference is miniscule.

https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=51.51659%2C9.94031%3B51.52776%2C9.93919#map=16/51.5231/9.9442
This routing result is also a strange one. Seems like a cycle road is given (unnecessarily) higher preferrence over a cycleway.

**Comment by karussell** [comment]
Thanks for reporting. So in the second case you'd prefer something like [this](https://graphhopper.com/maps/?point=51.5166%2C9.9403&point=51.517249%2C9.94039&point=51.518123%2C9.940594&point=51.520947%2C9.94091&point=51.522326%2C9.940492&point=51.526401%2C9.939516&point=51.526832%2C9.93944&point=51.5278%2C9.9392&locale=en&vehicle=bike&weighting=fastest&elevation=true&use_miles=false&layer=TF%20Cycle)?

We should have a look why this is not used. But there is one segment (marker 3) where there seems to be a data issue and the segment is completely forbidden (could be road connectivity issues, a barrier or an access tag)

**Comment by jengelh** [comment]
Yes, I would prefer a simple northbound route like that.

>a data issue and the segment is completely forbidden

Not saying there isn't a problem, but I am confident it's error free. Why - because adding waypoints was enough. A vetoed segment would always be routed around, I would argue. (Unless your definition of "completely forbidden" is still "it's allowed, with a preference of -2147483648". ;-) )
