### ISSUE TITLE
If heading is provided change EdgeFilter for LocationIndexTree

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1463]
The issue can be reproduced with oneway streets like [this](https://graphhopper.com/maps/?point=51.211414%2C14.566305&point=51.211521%2C14.561906&ch.disable=true&heading=270), ie. the heading does not work. Expected is the snapping to the other side of the motorway but it is unclear if the heading should already be applied at the snapping step. (The ordinary case works like [here](https://graphhopper.com/maps/?point=51.192725%2C14.56094&point=51.192819%2C14.567678&ch.disable=true&heading=270))

**Comment by pdrum** [comment]
I'll create a pull request for this.

**Comment by easbar** [comment]
We could use the heading while snapping similar to the street hint: First try to find a snap that works with the requested heading in a certain radius, and if nothing is found do normal snapping without heading. This way we could make sure that if a heading is requested we do not snap to e.g. the opposite lane. On the other hand there might be cases where we snap to some point that is rather far away even though a closer snap with the wrong heading would have been preferred. But as long as we use a small radius for the snapping with heading this  should not be such a big problem?
