### ISSUE TITLE
Collapse/Uncollapse sets of directions to stay on the same path/road

### ISSUE THREAD

**Issue by DavidBelmares** [graphhopper/graphhopper#1464]
I think to help clean up navigation on OSM, it would be nice to have it so that a sequence of directions for staying on a single path (maybe not in terms of ways, but in terms of name) could collapse into one step for viewing longer trips with other routes, for example. See below, where it gives detailed steps on where to turn or stay right/left, etc. The user should have the option to collapse it all into one step if he/she wishes, into something like "Turn onto Los Gatos Creek Trail and continue for 13km" for example.

Edit: to clarify, the example below is the cycling directions

Links and screenshots illustrating the issue
https://camo.githubusercontent.com/e103a17e63753b8314209db98d995b73396200ff/68747470733a2f2f692e696d6775722e636f6d2f544e46415651542e706e67

**Comment by karussell** [comment]
There are other issues open that will improve this. Please ask on our forum before creating an issue.
