### ISSUE TITLE
Avoid parameter not detected?

### ISSUE THREAD

**Issue by goransleko** [graphhopper/graphhopper#1477]
I am hosting Graphhopper on our own server. Routing API seems to be working, but I want to avoid motorways or ferries. In order to do so I have added “ch.disable=true” and “avoid=motorway” to the request, but the server returns the same directions as if it were without avoid parameter. I have tried the same parameters and points on https://graphhopper.com/api/1//route? API, and it will return correctly - different route with avoid parameter. I have also tried other parameters, like weighting or heading, and that seems to be working perfectly.

Example parameters: route?point=46.658391%2C16.165009&point=46.575383%2C15.830612&ch.disable=true&avoid=motorway

Are there any settings I have to change to get it working with avoid parameter?

**Comment by karussell** [comment]
Please use our forum
