### ISSUE TITLE
barriers with access:conditional block routing

### ISSUE THREAD

**Issue by eliboni** [graphhopper/graphhopper#1478]
On the open source graphhopper, barriers  with `access:conditional= no @ (Nov-Apr)` like the one below

https://www.openstreetmap.org/node/4550696272

block routing (we're in october now)

However using the online API it looks fine:

https://graphhopper.com/maps/?point=46.209517%2C11.425613&point=46.208411%2C11.421912&locale=en-US&vehicle=car&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale

Another example with the following barrier: https://www.openstreetmap.org/node/3165754680

**Comment by boldtrn** [comment]
I think the reason is that the tags for both nodes did not contain a clear access declaration. I updated the OSM data.

The online API assumes gates are accessible by default. The open source version does not IIRC. 

BTW: questions should be asked in our [forum](https://discuss.graphhopper.com/)

**Comment by eliboni** [comment]
Many thanks for the feedback, I thought `access:conditional= no @ (Nov-Apr)` implicitly means `access = yes` outside the condition - this is what happens in highways. Let's see what happens after your edit, I'll follow up in the forum if needed. Thanks again for your attention
