### ISSUE TITLE
Create edges with custom Edge ID

### ISSUE THREAD

**Issue by Azbesciak** [graphhopper/graphhopper#1495]
Curently there is no option to add edge to the graph, with own custom ID. There is only

````java
Graph.edge(int nodeA, int nodeB)
````
and 
````java
Graph.edge(int a, int b, double distance, boolean bothDirections)
````
 which is a little bit narrow API IMO. My propose is to add a method 
````java
Graph.edge(int edgeID, nodeA, int nodeB)
````
### Why it could be helpful?
- Edges have their meaning for user
- Data connected - can reuse ID from source
- Easier to debug
- Easier to implement plug-in architecture

I think it is even compatibile with current API, for example in [`BaseGraph`](https://github.com/graphhopper/graphhopper/blob/f39ff4b863ae4775dabf07d308f40ef95238e8c8/core/src/main/java/com/graphhopper/storage/BaseGraph.java#L488) edge ID is created by next sequence Id, which in case of check fail will be not used anyway... so the new layout could be even like this [`BaseGraph`]:
```java
public EdgeIteratorState edge(int edgeId, int nodeA, int nodeB) {
    if (isFrozen())
        throw new IllegalStateException("Cannot create edge if graph is already frozen");

    ensureNodeIndex(Math.max(nodeA, nodeB));
    edgeAccess.internalEdgeAdd(edgeId, nodeA, nodeB);
    EdgeIterable iter = new EdgeIterable(this, edgeAccess, EdgeFilter.ALL_EDGES);
    boolean ret = iter.init(edgeId, nodeB);
    assert ret;
    if (extStorage.isRequireEdgeField())
        iter.setAdditionalField(extStorage.getDefaultEdgeFieldValue());

    return iter;
}

public EdgeIteratorState edge(int nodeA, int nodeB) {
    return edge(nextEdgeId(), nodeA, nodeB);
}
```
Other proposal would be to change `edgeID` from `int` to `long`... IMO max int can be too small in some use cases...
### Why do I need this?
I have data from other than OSM source. Also, I need to preprocess it, but it is not important - just a place when I can give edges my own meaning.
I also don't (and actually cannot due to data specification) save all data into edge as flags, so I have to extract it. I need to know ID's of all edges - of course I can use those generated from `Graph.edge()` but then I would have to create index for each graph (I have much more than one) - which is a little bit... no sense, when I can have the same meaning for each.

What do you think?

**Comment by karussell** [comment]
This won't happen unless major refactoring of the underlying data storage is done as adjacent OSM ID is important. Instead I suggest to have a look into OSM ID mapping issue and go down this route: #917

**Comment by Azbesciak** [comment]
But... As I said:
- I am not using OSM (good to know they have id related problems anyway...)
- it would be just an option - not must have; then user should manage his IDs
- I don't want to create separate edges mapping registry

It is possible to set own `nodeID`, so why not allow to set own `edgeID` also?

**Comment by karussell** [comment]
> It is possible to set own nodeID, so why not allow to set own edgeID also?

It is not intended to create arbitrary nodeIDs as they should be consecutive as well and the PointAccess API is suboptimal in this regard

**Comment by Azbesciak** [comment]
> It is not intended to create arbitrary nodeIDs as they should be consecutive as well and the PointAccess API is suboptimal in this regard

What about [shp reader](https://github.com/graphhopper/graphhopper-reader-shp/blob/193a702a0d9ab80941f2d1023adcb87a778d0a50/src/main/java/com/graphhopper/reader/shp/OSMShapeFileReader.java#L121) then?

**Comment by karussell** [comment]
What do you mean? The created nodeIDs are consecutive.

**Comment by Azbesciak** [comment]
My generated edges also may be - I didn't say it will UUID in Int version :).
Also, small gaps won't cause big performace isues... probably (lets say that 10% of edges will be removed from original graph).

**Comment by Azbesciak** [comment]
Also, is it better to have suboptimal feature or don't have it at all? It is rather my responsibility in that way.

**Comment by zhiqiangZHAO** [comment]
Not quite sure the question. Just thought a thing might help: if you want your own ID, you can create an extend storage for  external ID. When you output the route, you can also output the external ID.

**Comment by Azbesciak** [comment]
I know that I can map edge ID to my own, but it is overhead, which I want to avoid. Also, I am not sure but own graph extension is not so easy to inject because it is hardcoded in Graphhopper onLoad as I remember (NoOp or turnCost).
I already implemented solution which has mapping for each graph, but this caused my code looks more like spaghetti than I would like and generates much more data than it should also... 😣
