### ISSUE TITLE
Instruction "get off the bike" is missing

### ISSUE THREAD

**Issue by Lukas458** [graphhopper/graphhopper#1498]
Please look at this route: https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=51.25745%2C7.14858%3B51.25727%2C7.14617

The cyclists are routed over a pedestrians way here, which has no bicycle=yes or any allowing value (I mean this: https://www.openstreetmap.org/way/180247410). But the default bicycle-Value for highway=pedestrian is "no", isn't it?

**Comment by karussell** [comment]
Bicycle is not forbidden as we can force it into "get off the bike", so we assume a speed of 6km/h. 

But still an information about this in the instructions is missing.

**Comment by mghildiy** [comment]
is RacingBikeFlagEncoder.java the file which needs to be changed?

**Comment by karussell** [comment]
This is fixed (GraphHopper Maps)

**Comment by zdila** [comment]
> But still an information about this in the instructions is missing.

Is this actually available? I could not find it in the response.

**Comment by karussell** [comment]
It is no longer part of the instruction text, but you can fetch it via the path detail `get_off_bike`.

**Comment by zdila** [comment]
I tried to find it also in the path detail but I was not successful. Could you please show me an URL which returns it? Thank you!

**Comment by karussell** [comment]
`details=get_off_bike` should do this for the API or GH Maps:

https://graphhopper.com/maps/?point=51.439644%2C14.245191&point=51.439387%2C14.244938&vehicle=bike&elevation=true&details=get_off_bike
