### ISSUE TITLE
Avoid round6 in routing request of client-hc

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1499]
In GraphHopperWeb.createRequest a rounding to 6 decimal points is done which should be configurable (on/off) to avoid differences between this and the matrix client due to rounding issues.

**Comment by mghildiy** [comment]
Method signature for createRequest needs to be changed, with additional boolean argument to make the decision for rounding on/off.
If this approach is acceptable, I can create a PR.

**Comment by karussell** [comment]
We can now submit POST requests towards the /route endpoint without this limitation.
