### ISSUE TITLE
Wrong usage of reverse argument in calcWeight 

### ISSUE THREAD

**Issue by ATofighi** [graphhopper/graphhopper#1501]
Hi,

I think usage of `reverse` in this lines is wrong:
 - https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/routing/weighting/FastestWeighting.java#L61
 - https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/routing/weighting/AbstractWeighting.java#L43-L46

I read the usages of `calcWeight` and `calcMillis` and I think `reverse` is always false in non-bidirectional algorithms and is always false in `calcMillis`.

So we should use something like `edgeState == edgeState.detach(true)` instead of `reverse` for determine to use speed or reversedSpeed.

**Comment by karussell** [comment]
Please use the forum for discussion and questions
