### ISSUE TITLE
Install SSL / HTTPS in GraphHooper .jar

### ISSUE THREAD

**Issue by nyoakaway** [graphhopper/graphhopper#1503]
Hello friends, my servers run with SSL, and this causing them not to communicate with GraphHopper because it runs in HTTP, I would like to know how to set up an SSL Certificate for the GraphHopper files, I use the .jar version of it running only car.

**Comment by karussell** [comment]
Not an issue of GraphHopper. Please consult the dropwizard documentation for this. For questions also please use our forum.
