### ISSUE TITLE
Foot routes across ferry ways

### ISSUE THREAD

**Issue by nathanwaters** [graphhopper/graphhopper#1504]
Example: https://graphhopper.com/maps/?point=-33.839695%2C151.240282&point=-33.855734%2C151.27367&locale=en-AU&vehicle=foot&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale

Seems to be following the ferry ways.

**Comment by nathanwaters** [comment]
Yep foot=yes is set on the ferry routes which is encouraged in the OSM wiki. IMO ferries should be omitted from a walking route.

**Comment by karussell** [comment]
If it is the shortest path then using the ferry for walking routes is not wrong. With #2209 one can soon exclude ferries or other roads depending on personal preferences. See [these examples](https://www.graphhopper.com/blog/2020/05/31/examples-for-customizable-routing/).
