### ISSUE TITLE
move Android example into separate repo

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1506]
The Android example is currently not build via travis due to some travis problems (not easy to combine Android and latest JDK) and furthermore for Android development gradle and not maven is used and we already do not include the Android app in the default build process. 

So moving this into a separate repository with gradle instead of maven might be the best solution so that we get fresh apk snapshots again.

Related: #1940.

**Comment by devemux86** [comment]
In case has been forgotten, GraphHopper & Android sample as is now require Android 7 Nougat (API 24).
Seems because of latest JTS, see https://github.com/graphhopper/graphhopper/pull/1469#issuecomment-434980330.

That's why I could update sample to latest [VTM release](https://github.com/mapsforge/vtm/releases) yet. :slightly_smiling_face:

**Comment by karussell** [comment]
Ah, ok. This was lost in issues I guess. We could downgrade to 1.15.1 - would this solve the problem?

**Comment by karussell** [comment]
What error message do you get?

**Comment by devemux86** [comment]
"Gradle project sync failed."
Obviously after updating Android / Gradle to latest working versions.

**Comment by karussell** [comment]
Ok. I was able to build it via maven.

Can you try this apk: https://oss.sonatype.org/content/repositories/snapshots/com/graphhopper/graphhopper-android/0.12-SNAPSHOT/

**Comment by devemux86** [comment]
I fixed the build error (manifest needed changes too).
Can PR sample to a newer build system after JTS fix.

Confirmed that `org.locationtech.jts:jts-core:1.15.1` works on older Android too.

**Comment by karussell** [comment]
Great to hear! And would appreciate a PR to downgrade & fix build errors.

**Comment by devemux86** [comment]
Sure, let me double check everything and will PR soon. :slightly_smiling_face:

**Comment by devemux86** [comment]
See #1507.
