### ISSUE TITLE
Size of graphhopper directory when using GTFS

### ISSUE THREAD

**Issue by feldob** [graphhopper/graphhopper#1512]
Hi,

When running the gtfs demo (Brandenburg) I noticed that the graph-cache folder becomes pretty big (5+GB). It is the edges folder that makes up for the largest part. Are there ways to mitigate/reduce the size other than reducing the geographical area of interest and/or reducing the offerings in the gtfs? Could something be improved in the code/ on a conceptual level?

I was considering to integrate the public transport search as an offline feature (mobile app), but given the area I am interested in, the size of the directory is about 7 GB, which unfortunately is not practically feasible.

Thank you for your work on graphhopper.

Regards
Felix

**Comment by karussell** [comment]
For questions and discussion please use our forum: https://discuss.graphhopper.com/c/graphhopper/public-transit
