### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by aoles** [graphhopper/graphhopper#1522]
The link to [storage layout](http://karussell.files.wordpress.com/2013/08/wiki-graph.png) in https://github.com/graphhopper/graphhopper/blob/master/docs/core/technical.md#2-the-graph returns *Not Found*.

**Comment by karussell** [comment]
Uhm, strange. I thought I had fixed this in #1496. Will see what's wrong this time.

**Comment by karussell** [comment]
Ups, fixed it only in the 0.10 branch will apply to master.

**Comment by karussell** [comment]
Done
