### ISSUE TITLE
Q: Z-order when searching source/destination points

### ISSUE THREAD

**Issue by bedla** [graphhopper/graphhopper#1528]
Hi,
I am using GH routing for some analytics preprocessing and I am curious if it is possible to say that I dont want to start and end route in tunnels or bridges but on ground, see 
https://graphhopper.com/maps/?point=50.097018%2C14.424142&point=50.06534%2C14.430502&locale=cs-CZ&vehicle=car&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale (but I want to route through them).
I did not find how to currently achieve this, but thinking about somehow use custom EdgeFilter but I am not sure if I am on right track.
Thx for answer
Ivos

**Comment by karussell** [comment]
For questions please use our forum. (e.g. [here](https://discuss.graphhopper.com/t/how-to-declare-a-non-stop-way/2699) but you can easily start a new topic)

> but thinking about somehow use custom EdgeFilter but I am not sure if I am on right track.

Yes, right track

**Comment by bedla** [comment]
ahh, sorry i did not find forum :] ... and thx for pointing me out, i will investigate it
