### ISSUE TITLE
Error: Specify at least 2 points

### ISSUE THREAD

**Issue by TimoRuetten** [graphhopper/graphhopper#1529]
Hey!

I am a bit confused. I am pretty sure I have done similiar requests before but today I got the error that I have to specify at least 2 points.

My request object:

// Request Object
```json
{
   "vehicles":[
      {
         "vehicle_id":"vehicle1",
         "start_address":{
            "location_id":"r8SvLjPsCxedseLBS",
            "lon":8.4573,
            "lat":47.18206
         },
         "type_id":"vehicle_type_1"
      }
   ],
   "vehicle_types":[
      {
         "type_id":"vehicle_type_1",
         "profile":"car"
      }
   ],
   "services":[
      {
         "id":"3MoDrkrjRXdFgKQ6S",
         "name":"Born Hansruedi_Niederbipp_Hansruedi Born_3.71ha_20WP",
         "address":{
            "location_id":"field-3MoDrkrjRXdFgKQ6S",
            "lon":7.71862,
            "lat":47.25543
         }
      },
      {
         "id":"WQ3Nv4KtPBNHvZGR7",
         "name":"Born Hansruedi_Niederbipp_Hansruedi Born_1.41ha_6WP",
         "address":{
            "location_id":"field-WQ3Nv4KtPBNHvZGR7",
            "lon":7.71651,
            "lat":47.26037
         }
      },
      {
         "id":"xMKGdQ3S4aXft8nk3",
         "name":"Feld 1_aesch_regina nu_3.92ha_0WP",
         "address":{
            "location_id":"field-xMKGdQ3S4aXft8nk3",
            "lon":47.48199,
            "lat":7.57499
         }
      }
   ]
}
```

After init the gh routing class in nodejs I am doing:

```javascript
ghRouting.doRequest(requestObject)
```

this will return the error I wrote above. As far as I can see I have 3 points (if the errors references to the list of services) I am confused. Am I missing here something?

**Comment by karussell** [comment]
Please use [our forum](https://discuss.graphhopper.com/c/directions-api) or [support](https://www.graphhopper.com/contact-form/). This issue list is about the GraphHopper routing engine.

**Comment by TimoRuetten** [comment]
Oh, thanks @karussell - it seems that I missed that comment in the other issue. Thanks for clarifying!

**Comment by TimoRuetten** [comment]
I will reopen the issue in the correct github repository. Because here, you are fully right, is the wrong place.
