### ISSUE TITLE
Not an issue regarding the codes but A question to all XD

### ISSUE THREAD

**Issue by Aikahjmjm** [graphhopper/graphhopper#1530]
Hi guys, i am student who uses GraphHopper in my project. However, in my report, my lecturer ask me to find the flowchart of how GraphHopper's algorithm work. Can anyone tell me where can i find such flowchart?

**Comment by Aikahjmjm** [comment]
wow, i thought at least there is a person who can give me an idea on how to find such information, but @karussell decided that my question is not worthy enough to be asked here T-T. I'm sorry for being to stupid in your eyes T-T

**Comment by easbar** [comment]
Its not about anyone thinks you are stupid, but basically there is a question that should rather go to our forum every day. Maybe we need a more prominent statement saying this when an issue is created.

**Comment by karussell** [comment]
Before one creates a new issue there is a statement clearly saying that asking questions should not happen here. 

> I'm sorry for being to stupid in your eyes T-T

Who said that you are stupid? This is a friendly community here and you are welcome too. Just read the introductory text more carefully next time.
