### ISSUE TITLE
Cannot create Exception Resonse for type=gpx

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#1537]
When requesting a GPX that would result in an exception, GraphHopper won't return a valid response.

![screenshot from 2019-02-07 11-05-12](https://user-images.githubusercontent.com/1553525/52404023-4b7fc000-2ac8-11e9-93e1-aabb053c0d12.png)

In this case I requested a non exiting vehicle. The same also applies if I request a point that cannot be snapped, etc.

Related to #1390.

Unfortunately, it's a bit hard to debug. The code goes through `MultiExceptionGPXMessageBodyWriter` and a GPX documented is generated. As far as I can tell the generated GPX looks correct (from debugging), but the GPX is not returned or not correctly returned.

**Comment by boldtrn** [comment]
One way to approach this would be return the regular error Json for cases when the GPX file cannot be created. This would be a breaking API change though. On the other hand it would make the error handling easier for applications that both request json and gpx.

Right now when sending a failing request with `type=gpx` to the Directions API, it simply fails with a json response:
```json
{
message: "Bad Request"
}
```

So instead of simply returning bad request, we could return something like:
```json
{
message: "Bad Request",
hints: [
{
message: "Cannot find point 0: 49.15297,-30.585937",
details: "com.graphhopper.util.exceptions.PointNotFoundException",
point_index: 0,
}
],
}
```

**Comment by karussell** [comment]
Return JSON in this case is not an option without knowing the underlying reason. 

There is something unexpected happening here as usual errors should be fine according to RouteResourceTest.testGPXWithError

**Comment by boldtrn** [comment]
> Return JSON in this case is not an option without knowing the underlying reason.

Yes I agree.

> There is something unexpected happening here as usual errors should be fine according to RouteResourceTest.testGPXWithError

Yes this is really unexpected. I created two tests using a not existing vehicle. Both succeed:

```java
    @Test
    public void testGPXIncorrectVehicle1() {
        final Response response = app.client().target("http://localhost:8080/route?point=42.554851,1.536198&point=42.510071,1.548128&type=gpx&vehicle=notexisting").request().buildGet().invoke();
        assertEquals(400, response.getStatus());
        String str = response.readEntity(String.class);
        assertFalse(str, str.contains("<html>"));
        assertFalse(str, str.contains("{"));
        assertTrue("Expected error but was: " + str, str.contains("<message>Vehicle not supported: notexisting. Supported are: car</message>"));
        assertTrue("Expected error but was: " + str, str.contains("<hints><error details=\"java"));
    }

    @Test
    public void testGPXIncorrectVehicle2() {
        GraphHopperAPI hopper = new com.graphhopper.api.GraphHopperWeb();
        assertTrue(hopper.load("http://localhost:8080/route"));

        GHRequest request = new GHRequest();
        request.addPoint(new GHPoint(42.554851,1.536198));
        request.addPoint(new GHPoint(42.510071,1.548128));
        request.setVehicle("notexisting");
        request.getHints().put("type", "gpx");
        String str = ((GraphHopperWeb) hopper).export(request);
        System.out.println(str);
        assertTrue("Expected error but was: " + str, str.contains("<message>Vehicle not supported: notexisting. Supported are: car</message>"));
        assertTrue("Expected error but was: " + str, str.contains("<hints><error details=\"java"));
    }
```

I also ran a test with Firefox, Firefox complaints about a FileNotFound:

![screenshot from 2019-02-09 11-28-26](https://user-images.githubusercontent.com/1553525/52519637-aba86a80-2c5e-11e9-84f7-973727a259ce.png)

I finally understand the issue. It is a "Browser Issue". For failing responses codes like 4XX and 5XX, it's not allowed to respond with a file download / attachment. The browser seems to block this internally.

If I change the response code to 200, the file is downloaded as expected.

So I see two possible options:
- Change the response code to 200 for GPX exports, even if there is an exception (probably preferred, as this was probably the behavior before Dropwizard)
- Switch to JSON

**Comment by karussell** [comment]
If this is a client issue I do not see why we should change our code even it is was working differently before. Can we remove the bug label?

IMO the most frequent use case is that people create routes and then download this route, i.e. there won't be an error. If there is an error and if the client asks for GPX response via the API we should not return JSON. (I can see how the GH Directions API violates this at the moment as we have a proxy before the routing engine)

**Comment by boldtrn** [comment]
> If this is a client issue I do not see why we should change our code even it is was working differently before. Can we remove the bug label?

It doesn't work with Firefox and Chrome. I also had troubles with wget and curl. 

I haven't done the appropriate research, but  I assume that there might be some specification that forbids file downloads for failing requests.

**Comment by boldtrn** [comment]
> the most frequent use case is that people create routes and then download this route, i.e. there won't be an error

I agree, but there might errors that occur during the export. For example when exporting a route with alternative routes, which is not yet supported.

**Comment by boldtrn** [comment]
I double checked for wget. Wget has an option `--content-on-error`. This allows to download the content of the response for failing requests.

**Comment by boldtrn** [comment]
I asked this question on [StackOverflow](https://stackoverflow.com/questions/54617629/why-isnt-it-possible-to-download-a-file-for-status-code-4xx-and-5xx) (also added a bounty because so far no one replied). It is really bugging me why Chrome and Firefox behave so differently and why there is a difference to other clients like curl or wget.

**Comment by boldtrn** [comment]
I think I understand the history of this issue now. There is a good answer on [Super User](https://superuser.com/a/719647/182140) and I also wrote a brief summary [here](https://stackoverflow.com/a/54764043/1548788).

It remains a bit unclear what the correct behavior would be.

[Here](https://cs.chromium.org/chromium/src/content/browser/frame_host/navigation_request.cc?type=cs&q=ERR_INVALID_RESPONSE&sq=package:chromium&g=0&l=1209) is the code of Chromium that is probably responsible for this behavior. [This](https://bugzilla.mozilla.org/attachment.cgi?id=219401&action=diff) is the change that introduced this behavior in Firefox. According to the comments in the Chromium code, they followed Firefox's logic there. There is an [open issue](https://bugzilla.mozilla.org/show_bug.cgi?id=426961) from 2008 that considers improving the error message.

Since we won't be able to change how browsers handle this, I'd vote to change the status code for failing gpx exports to `200`. WDYT?

**Comment by karussell** [comment]
The main usage is from API clients and not from browsers. Maybe if you have more users via browser you can intercept the error handling with a custom MultiExceptionGPXMessageBodyWriter?

**Comment by boldtrn** [comment]
> The main usage we expect is from API clients and not from browsers.

This currently doesn't [work for the Directions API](https://graphhopper.com/api/1//route?point=48.922499%2C-16.875&point=48.69096%2C7.03125&type=gpx&gpx.route=false&gpx.track=true&gpx.waypoints=false&locale=en-AU&vehicle=car&weighting=fastest&elevation=true&key=[KEY]). It doesn't work for clients nor browsers.

> Maybe if you have more users via browser you can intercept the error handling with a custom MultiExceptionGPXMessageBodyWriter?

Yes, I will do something like this :).

**Comment by karussell** [comment]
> This currently doesn't [work for the Directions API](https://graphhopper.com/api/1//route?point=48.922499%2C-16.875&point=48.69096%2C7.03125&type=gpx&gpx.route=false&gpx.track=true&gpx.waypoints=false&locale=en-AU&vehicle=car&weighting=fastest&elevation=true&key=%5BKEY%5D). It doesn't work for clients nor browsers.

Our Directions API has a layer between to keep backward compatibility.

> It doesn't work for clients 

The tests pass, so this should work with every sane client like the Java client. Or what did you mean?

**Comment by boldtrn** [comment]
> The tests pass, so this should work with every sane client like the Java client. Or what did you mean?

I just wanted to state that won't work for the Directions API right now, independently from the client.

**Comment by karussell** [comment]
(The GPX export via the Directions API should work via the browser as we return 200 for backward compatibility reasons. But this shouldn't matter here ;) ) 

The routing service should work with every proper client that allows to return content for errors (obviously not browsers). If this is the case - can we close here?

**Comment by boldtrn** [comment]
Sure, if you don't think that this is an issue. I will close the issue.
