### ISSUE TITLE
GH: An error happened while creating graph:length=0; regionStart=1; regionLength=-2

### ISSUE THREAD

**Issue by PankajSavaliya** [graphhopper/graphhopper#1543]
First I have tested your [APK](https://graphhopper.com/public/releases/graphhopper-android-0.10.0.apk) that is working fine in my real device. After I have installed your android code in the android studio and run it.  In App, download specific area from the remote and open map from locally. After I got an issue in the map I can't tap to set a pin for getting a distance. I showed you log below 

 E/GH: loading graph (0.12) 
com.graphhopper.android E/o*.o*.r*.GLUtils: glCreateProgram: glError 1280
com.graphhopper.android E/GH: An error happened while creating graph:length=0; regionStart=1; regionLength=-2

After that, I got toast "Finished loading graph. Long press to define where to start and end the route."

So please let me know what's the problem?

**Comment by karussell** [comment]
Please post such issues to our forum. Make sure you can reproduce this behaviour with our sample APK and then we can create an issue here, if it is really an issue with the core routing engine.
