### ISSUE TITLE
Elevation data not created

### ISSUE THREAD

**Issue by hasi05** [graphhopper/graphhopper#1545]
Hello,

I am currently having trouble with the elevation data.
Only SRTM is working as elevation provider, when I choose multi or cgiar no elevation data is being created.

Current config (several other combinations are also not working): 
`graph.elevation.provider: multi
 graph.elevation.calc_mean: true
 graph.elevation.smoothing: true`

I use the web service jar of version 0.11.0

What is a bit strange is that http://srtm.csi.cgiar.org/SRT-ZIP/SRTM_V41/SRTM_Data_GeoTiff is responding with Page not found and when I try to use the different link mentioned in this doku https://github.com/graphhopper/graphhopper/blob/master/docs/core/elevation.md the error "Can't decode strm_37_04.tif" occures.

Am I doing something wrong or is it related to the page not found problem?
I'd like to use the multi - provider as it seems to be the most current provider according to the other articles here. 

Can you please help? 
Thanks.

**Comment by karussell** [comment]
For questions please use our forum first.

**Comment by karussell** [comment]
It looks like there is indeed something wrong. (Next time still start on forum :D )

**Comment by karussell** [comment]
Have fixed it in latest master

**Comment by hasi05** [comment]
Thanks for the fast help and I'll start in the forum next time :)

**Comment by karussell** [comment]
Thanks for raising the issue! Do not hesitate to reopen if something is wrong, as I tested it just for a limited region.
