### ISSUE TITLE
An error happened while creating graph: Encoder car was used in version 1, but current version is 2

### ISSUE THREAD

**Issue by dd9k** [graphhopper/graphhopper#1561]
After I have installed your android code in the android studio and run it. In App, download specific area from the remote and open map from locally. After that, I got toast "An error happened while creating graph: Encoder car was used in version 1, but current version is 2".

I found this issue happend when run code from line 161 to 163 in EncodingManager at graphholder jar library.
`if (configuration.has("version") && fe.getVersion() != configuration.getInt("version", -1)) {
throw new IllegalArgumentException("Encoder " + entry + " was used in version " + configuration.getLong("version", -1L) + ", but current version is " + fe.getVersion());
                    }`

So please let me know what's the problem?

**Comment by karussell** [comment]
Please use our forum for questions.

BTW: did you get [this message](https://github.com/graphhopper/graphhopper/blob/master/.github/ISSUE_TEMPLATE.md) before creating this issue?

**Comment by Aleksa-Smolovic** [comment]
I too get this message. @dd9k did you find the solution?
