### ISSUE TITLE
Cant route over ferry bicycle/foot=designated

### ISSUE THREAD

**Issue by stevensnoeijen** [graphhopper/graphhopper#1562]
See: https://www.openstreetmap.org/way/164231365
When you routeover this by bike or foot it wont route over the ferry, the ferry tags look fine to me. When I look in the graphhopper code for foot/bicycle-flagencoder https://github.com/graphhopper/graphhopper/blob/0.11/core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java#L239 1 , the flagencoder will check the bicycle tag if its “yes”, but in this case the bicycle tag is designated which looks like a valid value in the osm wiki.

So it looks like the BikeFlagEncoder should also check if the value is “designated” (or even better; intendedValues). The same for the FootFlagEncoder.

If this is correct I would like to create a pullrequest to fix this problem.

discussing: https://discuss.graphhopper.com/t/cant-route-over-ferry-bicycle-foot-designated/4181

**Comment by karussell** [comment]
> If this is correct I would like to create a pullrequest to fix this problem

This would be really nice! As this is likely a small change it is merged fast :)
(If you do, please include a test that fails without the fix)

**Comment by stevensnoeijen** [comment]
> > If this is correct I would like to create a pullrequest to fix this problem
> 
> This would be really nice! As this is likely a small change it will be merged fast :)
> (If you do, please include a test that fails without the fix)

Yes, sure. I will do this, I'm eager to learn and contribute to graphhopper :) 
Expect a pullrequest this week

**Comment by stevensnoeijen** [comment]
created a pullrequest: https://github.com/graphhopper/graphhopper/pull/1568
