### ISSUE TITLE
Elevation polyline bug on the maps page

### ISSUE THREAD

**Issue by Azbesciak** [graphhopper/graphhopper#1573]
When you manipulate elevation control at [maps page](https://graphhopper.com/maps) red polyline is not removed after route change:
![image](https://user-images.githubusercontent.com/17334466/54673571-ccd06680-4afa-11e9-92dd-b265f9264ce0.png).

**Comment by boldtrn** [comment]
Thanks for reporting this.

Related to this issue - https://github.com/GIScience/Leaflet.Heightgraph/issues/39

I fixed this in https://github.com/graphhopper/graphhopper/pull/1569/commits/922160ef9f41c4a2e5b5d8be2e1c4024e006b201.

**Comment by boldtrn** [comment]
Should be fixed now :+1:
