### ISSUE TITLE
Route pedestrians over highway=platform

### ISSUE THREAD

**Issue by SelfishSeahorse** [graphhopper/graphhopper#1580]
Please allow pedestrians to be routed over `highway=platform`. (This tag should be treated the same as `highway=footway`.) Currently, they are diverted onto the street, see e.g. [here](https://graphhopper.com/maps/?point=46.94326%2C7.44836&point=46.943963%2C7.448967&locale=en-us&vehicle=foot&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale).

**Comment by karussell** [comment]
Thanks - maybe you have some time to create a pull request :) ?

**Comment by mprins** [comment]
Would that be as simple as adding a line `safeHighwayTags.add("platform");`  to this list?
https://github.com/graphhopper/graphhopper/blob/d18a80c9c65fcbd7a3f077065621f6f1f40e6488/core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java#L103-L111

**Comment by karussell** [comment]
We need this for bike too and then this should be a "pushing section" (off the bike). Plus we need some simple tests :)
