### ISSUE TITLE
Edge-based bidirectional algorithms do not agree with Dijkstra when there is a loop and turn restrictions.

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#1592]
Here is a graph involving a loop and some turn restrictions for which the edge-based bidirectional algorithms do not agree with Dijkstra / do not find the optimal path:

https://github.com/graphhopper/graphhopper/blob/fe8df1d7e56ac6052571eaf2bfc675ba1cd6415e/core/src/test/java/com/graphhopper/routing/EdgeBasedRoutingAlgorithmTest.java#L162-L185

**Comment by easbar** [comment]
The problem here is that the forward and backward seach uses different edge keys when they discover the loop edge 1-1. This is because of the `reverse` parameter here: https://github.com/graphhopper/graphhopper/blob/7b71a24919ab6f043942b89303c7dbb1bb6e4bfe/core/src/main/java/com/graphhopper/util/GHUtility.java#L461-L470

The forward search uses `createEdgeKey(1,1,4,false)`=8 while the backward search uses `createEdgeKey(1,1,4,true)`=9. For non-loop edges it has to be this way to differentiate the two possible directions of an edge, but for a loop the `reverse` parameter changes the edge key simply  depending on which search (fwd/bwd) found it. Because of the different edge keys the according `SPTEntry` is not found by the opposite search and the best path is not updated for the loop edge (here the traversalId is the edge key):
https://github.com/graphhopper/graphhopper/blob/7b71a24919ab6f043942b89303c7dbb1bb6e4bfe/core/src/main/java/com/graphhopper/routing/AbstractBidirAlgo.java#L240-L243

In principle this would not be a problem because when the search continues one step further the best path will be updated for the next edge, but in the present case the search stops before this happens, because the (suboptimal) path 0-6-4-3 is found just before and the search ends.

So the bug requires:

* edge-based routing
* a bidirectional algorithm
* a loop edge (our OSM import prevents this #1531) 
* a turn restriction or something like a forced start/target direction such that the loop has to be considered

I wonder if we could make `createEdgeKey` independent of the `reverse` parameter in case the two node ids are equal ?

**Comment by easbar** [comment]
> I wonder if we could make createEdgeKey independent of the reverse parameter in case the two node ids are equal ?

This would both 'directions' of the loop be treated equal, but there is no way to differentiate the two directions anyway #1525 which is why we started to exclude the loop edges during the import already #1531.

**Comment by easbar** [comment]
Ok adjusting `createEdgeKey` such that it returns the same value for loops regardless of the `reverse` flag is part one of the puzzle. The second problem is here: 
https://github.com/graphhopper/graphhopper/blob/7b71a24919ab6f043942b89303c7dbb1bb6e4bfe/core/src/main/java/com/graphhopper/routing/AbstractBidirAlgo.java#L251-L257
If `entry.adjNode == entryOther.adjNode` the best path is not updated, because this situation is interpreted as being a u-turn. However this can happen in two different cases:

1) there is in fact a u-turn and we have been using `TraversalMode.EDGE_BASED_1DIR`
2) we have encountered a loop edge at the meeting point (the situation discussed here)

The best path may only be rejected in the first case.

**Comment by karussell** [comment]
So we can simplify code just by throwing away 1DIR? If I understand this correctly, then let's remove this (#1520)

**Comment by easbar** [comment]
Yes the first case is specific to 1DIR and if we remove this TraversalMode we no longer need special handling for it in AbstractBidirAlgo.

**Comment by easbar** [comment]
Do you mean we should remove 1DIR in the PR for this issue already ?

**Comment by easbar** [comment]
Not so many changes needed at least in core repo, just tried it:
https://github.com/easbar/graphhopper/commit/81d14b5b79adba28199cd78cf02378c3b1c6acf8

**Comment by karussell** [comment]
This sounds good.

Maybe we could even remove EDGE_BASED_2DIR_UTURN too, i.e. fix #1520 and then fix this here?

**Comment by easbar** [comment]
> This sounds good.

Ok will add to the PR.

> Maybe we could even remove EDGE_BASED_2DIR_UTURN

Hmm I think this requires a little more thought, I would prefer doing this separately.

**Comment by easbar** [comment]
Or maybe to put it another way I think u-turns should be handled by using infinite turn costs instead of doing explicit u-turn checks at several different places. Simply removing EDGE_BASED_2DIR_UTURN might be possible, but I think it would be nicer to do this together with the above mentioned u-turn cleanup and also this is not related to the present issue.

**Comment by karussell** [comment]
Ok :+1:
