### ISSUE TITLE
Edge-based CH does not handle u-turns with virtual edges correctly

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#1593]
This test fails with an exception: abf35b0a7443f2f131c912abd98776d370ee6881

```java
    @Test
    public void test_Issue1592() {
        //      6   5
        //   1<-x-4-x-3
        //  ||    |
        //  |x7   x8
        //  ||   /
        //   2---
        NodeAccess na = graph.getNodeAccess();
        na.setNode(0, 49.407117, 9.701306);
        na.setNode(1, 49.406914, 9.703393);
        na.setNode(2, 49.404004, 9.709110);
        na.setNode(3, 49.400160, 9.708787);
        na.setNode(4, 49.400883, 9.706347);
        EdgeIteratorState edge0 = graph.edge(4, 3, 194.063000, true);
        EdgeIteratorState edge1 = graph.edge(1, 2, 525.106000, true);
        EdgeIteratorState edge2 = graph.edge(1, 2, 525.106000, true);
        EdgeIteratorState edge3 = graph.edge(4, 1, 703.778000, false);
        EdgeIteratorState edge4 = graph.edge(2, 4, 400.509000, true);
        // cannot go 4-2-1 and 1-2-4 (at least when using edge1, there is still edge2!)
        addRestriction(edge4, edge1, 2);
        addRestriction(edge1, edge4, 2);
        // cannot go 3-4-1
        addRestriction(edge0, edge3, 4);
        graph.freeze();
        LocationIndexTree index = new LocationIndexTree(graph, new RAMDirectory());
        index.prepareIndex();
        List<GHPoint> points = Arrays.asList(
                // 8 (on edge4)
                new GHPoint(49.401669187194116, 9.706821649608745),
                // 5 (on edge0)
                new GHPoint(49.40056349818417, 9.70767186472369),
                // 7 (on edge2)
                new GHPoint(49.406580835146556, 9.704665738628218),
                // 6 (on edge3)
                new GHPoint(49.40107534698834, 9.702248694088528)
        );


        List<QueryResult> queryResults = new ArrayList<>(points.size());
        for (GHPoint point : points) {
            queryResults.add(index.findClosest(point.getLat(), point.getLon(), EdgeFilter.ALL_EDGES));
        }

        RoutingAlgorithmFactory pch = automaticPrepareCH();
        QueryGraph queryGraph = new QueryGraph(chGraph);
        queryGraph.lookup(queryResults);
        RoutingAlgorithm chAlgo = pch.createAlgo(queryGraph, AlgorithmOptions.start()
                .traversalMode(TraversalMode.EDGE_BASED_2DIR)
                .build());
        Path path = chAlgo.calcPath(5, 6);
        // there should not be a path from 5 to 6, because first we cannot go directly 5-4-6, so we need to go left
        // to 8. then at 2 we cannot go on edge 1 because of another turn restriction, but we can go on edge 2 so we
        // travel via the virtual node 7 to node 1. From there we cannot go to 6 because of the one-way so we go back
        // to node 2 (no u-turn because of the duplicate edge) on edge1. And this is were the journey ends: we cannot
        // go to 8 because of the turn restriction from edge1 to edge4 -> there should not be a path!
        assertFalse("there should not be a path, but found: " + path.calcNodes(), path.isFound());
    }
```

**Comment by easbar** [comment]
This is the error message

```
java.lang.IllegalStateException: Edge 5 not found with adjNode:1. found edges were:3->5, 5->3

	at com.graphhopper.routing.QueryGraph.getEdgeIteratorState(QueryGraph.java:564)
	at com.graphhopper.routing.ch.Path4CH.getEdge(Path4CH.java:98)
	at com.graphhopper.routing.ch.Path4CH.processEdge(Path4CH.java:47)
	at com.graphhopper.routing.PathBidirRef.extract(PathBidirRef.java:90)
	at com.graphhopper.routing.AbstractBidirAlgo.extractPath(AbstractBidirAlgo.java:297)
	at com.graphhopper.routing.AbstractBidirAlgo.calcPath(AbstractBidirAlgo.java:95)
	at com.graphhopper.routing.ch.CHTurnCostTest.test_Issue1593(CHTurnCostTest.java:728)
```

but the error is simply that `QueryGraph#lookup` is run before the CH contraction, which does not make much sense anyway (and is never done in production code). Maybe we could throw an error if a virtual edge is encountered during the graph contraction (requires some instanceof check or adding an `isVirtual()` method to `EdgeIteratorState` interface or we have to find out the exact reason for this error and make sure that in principle the CH preparation also works when it is run after `QueryGraph#lookup`).

After fixing this (I have adjusted the previous comment accordingly), the test shows the real routing problem: CH finds a path that should not be found, because it takes a forbidden u-turn at node 1. The u-turn check here:

https://github.com/graphhopper/graphhopper/blob/7df1bbab1c07b6835c2a49c5b79b9eeed44dba5a/core/src/main/java/com/graphhopper/routing/AbstractBidirectionEdgeCHNoSOD.java#L150-L157

fails, because the u-turn is checked by comparing the first/last orig edge ids of the virtual edge 7-1 and the shortcut edge 1-4 and the virtual edge state returns the virtual edge id as first/last orig edge:

https://github.com/graphhopper/graphhopper/blob/7df1bbab1c07b6835c2a49c5b79b9eeed44dba5a/core/src/main/java/com/graphhopper/routing/VirtualEdgeIteratorState.java#L285-L293

The virtual edge id obviously does not match the (real) first/last orig edge id of the shortcut.

**Comment by easbar** [comment]
Fixing this is not so trivial and what bothers me here once again is that we even do these u-turn checks. They are separated from the calculation of the edge weights, which already include the turn costs via the `prevOrNextEdgeId` parameter in `calcWeight` and IMO would be the right place to apply the u-turn costs/restrictions also. For me this has caused many problems in the past (in retrospective I might say maybe 70% of the routing issues I found for edge-based CH where related to this) and the u-turn prevention should really be included in `calcTurnWeight`. The `TurnWeighting` would then be the place where we configure the default u-turn costs (no need for two different `TraversalModes`s). However, since this requires quite a bit of refactoring I think here we should just do some hacky quick fix (even though I haven't really figured it out yet). Related to #1520.

**Comment by easbar** [comment]
And with u-turns I mean turning onto the same edge we came from. I am not talking about more complex 'u-turns' where we switch to the opposite lane (another edge in the routing graph) as they are handled in the instructions. Handling these on the level of the routing algorithms would be much more involved.

**Comment by easbar** [comment]
I think I found a fix that is not too much of a hack :)  -> #1596.

**Comment by karussell** [comment]
Thanks for finding and fixing this. But this fix does not move the U-turn check into the `calcWeight` method - did I understand this correctly?

**Comment by karussell** [comment]
Ok, removed my comment as I understood it wrong. So thanks again for finding and fixing this :D
