### ISSUE TITLE
I Want to make changes in routing algorithm

### ISSUE THREAD

**Issue by vinayrachapalli** [graphhopper/graphhopper#1599]
Hello, I'm new to graphhopper and open source projects. Currently implemented algorithm gives optimal time travel path. I want to calculate optimal Fuel Path.

    1.So now I want to change the edge weights(time to fuel). Which part of the code I need to focus on.
    2.For calculating Fuel consumption for each edge, I need to use elevation along the road. So which api I need to use. Please Help me.

Thanks

**Comment by karussell** [comment]
Submit a new issue only if you are sure it is a missing feature or a bug. For questions or if you are unsure discuss the topic in our forum https://discuss.graphhopper.com
