### ISSUE TITLE
Error on launching the application in IntelliJ in Windows

### ISSUE THREAD

**Issue by mghildiy** [graphhopper/graphhopper#1604]
I am following [this](https://github.com/graphhopper/graphhopper/blob/0.12/docs/core/quickstart-from-source.md#start-development).

I cloned the [repo](https://github.com/graphhopper/graphhopper), and configured in IntelliJ as per the instructions in first link.

On launching the application, I get error:
 
Error:Android Pre Dex: [main2] Android SDK is not specified

I am not targeting Android development. I am in Windows.

How to get rid of this error?

**Comment by mghildiy** [comment]
Any inputs here?

**Comment by karussell** [comment]
Will hopefully have time at the end of this week for this. 

Usually there is no need to set up Android so you should be able to ignore the error regarding Android. Did you open the project and followed the "run->edit configuration" step?

**Comment by mghildiy** [comment]
Yes, I did.

**Comment by easbar** [comment]
I had a similar problem (but not under Windows). In the maven panel on the right you can choose maven profiles: 

![image](https://user-images.githubusercontent.com/17603532/57842574-1ffa2900-77cd-11e9-9d75-062bb671ab4e.png)

Maybe try enabling the include-android checkbox and then disable it again. You might see this prompt:

![image](https://user-images.githubusercontent.com/17603532/57842673-4cae4080-77cd-11e9-993f-0494fe455ecd.png)

After clicking 'Yes' the android module should be excluded from the build and no Android SDK should be needed. Alternatively you can right-click the `android->app` folder in Project view and choose `Remove module`.

You should also try `Build->Rebuild Project`, `mvn clean` (via console) and maybe right-clicking the `android` folder in Project view and choosing `Mark directory as->excluded`. 

Does this help ?

**Comment by mghildiy** [comment]
I tried it, but didn't work. I didn't see 'Remove module' option though..
