### ISSUE TITLE
Isochrones always uses car, ignoring vehicle parameter

### ISSUE THREAD

**Issue by nilsnolde** [graphhopper/graphhopper#1609]
Hi guys,
was just (ab)using GH to improve a little on ORS isochrone geometry builder and found that `vehicle` is currently ignored, e.g. the following request for `car` and `bike` gives the exact same geometry:

https://graphhopper.com/api/1/isochrone?profile=bike&time_limit=200&point=49.420159%2C8.68156&key=key&buckets=1

https://graphhopper.com/api/1/isochrone?profile=car&time_limit=200&point=49.420159%2C8.68156&key=key&buckets=1

I don' really see any red flag in the code, unless you're running smth else than `master`.

**Comment by karussell** [comment]
I think we do not use "profile=bike" but "vehicle=bike" :)

BTW: for questions, especially since this is for the Directions API, please use our forum: https://discuss.graphhopper.com/c/directions-api

**Comment by nilsnolde** [comment]
oops, crap. Yeah there was a typo in our `routingpy` library. Sorry for the confusion
