### ISSUE TITLE
Geocoding deferRequestBy a bit low

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#1615]
I noticed that we curently use 'deferRequestBy: 5`. The value is given in ms ["Number of miliseconds to defer Ajax request"]. 5 ms seemse pretty low, maybe a value like 200-500 ms would be more appropriate to reduce the usage of the API key?

**Comment by karussell** [comment]
Yes, good idea. 200ms should be completely fine. 

It looks there is also some duplication of the libraries (?)

https://github.com/graphhopper/graphhopper/search?q=deferRequestBy&unscoped_q=deferRequestBy
