### ISSUE TITLE
FlagEncoder used for mobile GraphHopper instance

### ISSUE THREAD

**Issue by calvinkehl** [graphhopper/graphhopper#1616]
https://github.com/graphhopper/graphhopper/blob/e455be79a8fe4cf78e96599fecc67577f2967493/core/src/main/java/com/graphhopper/GraphHopper.java#L791

Instead of using the FlexModel, GraphHopper.load() still tries to create a FlagEncoder. What has to be done in order to use the FlexModel on Android?

**Comment by karussell** [comment]
For questions please use our forum: https://discuss.graphhopper.com/

**Comment by calvinkehl** [comment]
Well, technilcally it's an issue with the flex model branch, because flex models should be used on android as well. I just don't know exactly where to make the changes.

**Comment by karussell** [comment]
It is really important that you post questions on our forum first. Even if you think they are issues - just to reduce the traffic here on github. 

As often there are ways to get it done and it is just not obvious at the first glance. And if something works on the server it should work on Android. Additionally the flex mode branch is still experimental and so even technically there cannot be an issue with it ;)

**Comment by calvinkehl** [comment]
Seems logical.

> And if something works on the server it should work on Android. 

That's why I directly created an issue ;)
