### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by mghildiy** [graphhopper/graphhopper#1618]
I did fresh pull from upstream, and with no local changes I ran 'mvn clean install'. I get test failures:

[ERROR] Errors: 
[ERROR]   GraphHopperDataFlagEncoderSpatialRulesTest.com.graphhopper.http.GraphHopperDataFlagEncoderSpatialRulesTest ╗ Runtime
[ERROR]   GraphHopperLandmarksTest.com.graphhopper.http.GraphHopperLandmarksTest ╗ Runtime
[ERROR]   IsochroneResourceTest.com.graphhopper.http.isochrone.IsochroneResourceTest ╗ Runtime
[ERROR]   ChangeGraphResourceTest.com.graphhopper.http.resources.ChangeGraphResourceTest ╗ Runtime
[ERROR]   I18nResourceTest.com.graphhopper.http.resources.I18nResourceTest ╗ Runtime jav...
[ERROR]   NearestResourceTest.com.graphhopper.http.resources.NearestResourceTest ╗ Runtime
[ERROR]   NearestResourceWithEleTest.com.graphhopper.http.resources.NearestResourceWithEleTest ╗ Runtime
[ERROR]   RouteResourceIssue1574Test.com.graphhopper.http.resources.RouteResourceIssue1574Test ╗ Runtime
[ERROR]   RouteResourceTest.com.graphhopper.http.resources.RouteResourceTest ╗ Runtime j...
[ERROR]   RouteResourceWithEleTest.com.graphhopper.http.resources.RouteResourceWithEleTest ╗ Runtime

**Comment by mghildiy** [comment]
I closed all other applications, and it worked fine.

**Comment by karussell** [comment]
Please use our forum to ask questions: https://discuss.graphhopper.com/c/graphhopper
