### ISSUE TITLE
SimpleIntEncodedValue can't simply encode an int

### ISSUE THREAD

**Issue by michaz** [graphhopper/graphhopper#1619]
I have a variable which is an `int` and uses the entire range of that type, and I'd like to put it in a `SimpleIntEncodedValue`. So I create one with 32 bit, which is allowed. But then I can't put in an `int` because `SimpleIntEncodedValue` doesn't allow negative values. 

In fact, it wastes the 32nd bit because of that. I think that's why this caught me by surprise.

**Comment by karussell** [comment]
Yes, if we continue to force positive values we could optimize this (or support negative values). The bigger advantage I see in implementing reordering the EncodedValues. E.g. if you have two EVs with 18 bits and two with 10 bits this would require 3 bytes (18 and 18+10 and 10) although with reordering (18+10 and 18+10) only two bytes are required.

**Comment by michaz** [comment]
> (or support negative values)

That, or at least rename the thing. An `int` is an `int`, I was very disappointed when I couldn't put my `int` into the `IntEncodedValue`. ;-)

`UnsignedIntegralEncodedValue` or something.
