### ISSUE TITLE
QueryGraph edge-explorer cache does not work for edge-based CH.

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#1623]
We can do 
```java
queryGraph.setUseEdgeExplorerCache(true);
```
and 
```java
queryGraph.createEdgeExplorer(edgeFilter)
```
will return the same edge-explorer instance for all subsequent calls of `DefaultEdgeFilter.inEdges`, `DefaultEdgeFilter.outEdges`, `DefaultEdgeFilter.allEdges` and `EdgeFilter.ALL_EDGES` (for each of these filters there will be a separate edge-explorer instance).

The problem is that in some cases we explicitly need to create two different instances for the same filter. This is not needed very often, but for example here: 

https://github.com/graphhopper/graphhopper/blob/d24173a188f4574b6eb9e7c6ff641eaec9029208/core/src/main/java/com/graphhopper/routing/AbstractBidirectionEdgeCHNoSOD.java#L46-L48

there is a nested loop over edge iterators where the 'inner' explorer must be different to the 'outer' one.

Because of this using the edge-explorer cache with edge-based CH fails at the moment.

I started adding a test for the query graph behavior here: https://github.com/graphhopper/graphhopper/commit/58e7ac1777c2382d5a42dd7c9153c2de65e31a28, but so far it does not show much, obviously if we use the same instance of the edge explorer within an inner loop the outer loop will be messed up.

**Comment by easbar** [comment]
Was about to add the 'bug' label, but at least the query graph cache is described as an 'experimental' feature at the moment :)

**Comment by easbar** [comment]
Maybe add a second parameter to `createEdgeExplorer` that is used as an 'id' to identify the explorer ? 
```
EdgeExplorer createEdgeExplorer(EdgeFilter filter) {
    return createEdgeExplorer(filter, DEFAULT_ID);
}

EdgeExplorer createEdgeExplorer(EdgeFilter filter, int explorerId) {
}
```
Not very pretty thats for sure, but we would need a way to express that we want another instance (and ideally this other instance would still be cached / we do not want another instance for every call).

**Comment by karussell** [comment]
> but at least the query graph cache is described as an 'experimental' feature at the moment :)

Ups, you are right. (please remove whenever you like :) )

> The problem is that in some cases we explicitly need to create two different instances for the same filter

Did you mean the same edge explorer for two different filters? (Because we [should return two different instances](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/routing/QueryGraph.java#L573) for the two different filters "inEdges" and "outEdges")

**Comment by easbar** [comment]
> please remove

no no its fine ;)

> Did you mean the same edge explorer for two different filters?

No I mean two different explorers for the same filter. Sure there are different instances if we first use an inEdge and then an outEdge filter. But here the problem is that for example we need two different explorers for the inEdge filter.

```java
EdgeExplorer exp1 = graph.createEdgeExplorer(DefaultEdgeFilter.inEdges());
EdgeExplorer exp2 = graph.createEdgeExplorer(DefaultEdgeFilter.inEdges());

EdgeIterator outerIter = exp1.setBaseNode(base);
while (outerIter.next()) {
    EdgeIterator innerIter = exp2.setBaseNode(outerIter.getAdjNode());
    while (innerIter.next()) {
          // whatever
    }
}
```

Obviously if `exp1==exp2` this will fail / do something very unexpected.

**Comment by karussell** [comment]
What about instead of two methods DefaultEdgeFilter.acceptsForward/acceptsBackward ... using just one hashCode()? Then for these special cases we could overload them or do

```java
EdgeExplorer exp1 = graph.createEdgeExplorer(DefaultEdgeFilter.inEdges(1));
EdgeExplorer exp2 = graph.createEdgeExplorer(DefaultEdgeFilter.inEdges(2 /* forces different EdgeExplorer instance*/));
```

We could then also make this independent of the DefaultEdgeFilter via a CachableEdgeFilter interface or something.

**Comment by easbar** [comment]
Yeah, I like the idea. So two things basically:

* if query graph cache is enabled `createEdgeExplorer` returns the same instance for all filters that are equal in the `equals`/java sense. This caching mechanism will become independent of `DefaultEdgeFilter` etc.

* provide creator, hashCode and equals methods for `DefaultEdgeFilter` as you suggested so it is easy to create equal instances of the different default edge filter at different code locations.

**Comment by karussell** [comment]
Much clearer for me now due to your explanation, but yes :+1:
