### ISSUE TITLE
Docker build should support isochrone

### ISSUE THREAD

**Issue by abudden** [graphhopper/graphhopper#1633]
The docker implementation is great and makes it really easy to get a basic graphhopper router up and running quickly.

I'm interested in using graphhopper for a route planning website and wanted to experiment with isochrones.  However, if I access `localhost:port/isochrone`, I just get 404.  I've been trying to work out what needs to be done to `graphhopper.sh` to enable this, but so far my attempts have failed (I'm not very experienced with java).

Is there any documentation that I've missed that explains how to enable/disable features in the docker container?  Particular ones that would be interesting:

* `/isochrone` endpoint
* Disable the web UI and just support `/route`, `/isochrone` and `/geocode`
* Enable API keys to "safely" allow cross server requests

**Comment by karussell** [comment]
The /isochrone endpoint is available if you can reach /route. There is no /geocode endpoint and also no need to use API keys. 

For more questions please use [our public forum](https://discuss.graphhopper.com/c/graphhopper).
