### ISSUE TITLE
Google Distance Matrix tests fail

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1653]
Either because they changed something in their policies or we use too many credits above their free limit. Will for now ignore this test and later we should remove the entire class.

**Comment by easbar** [comment]
I put `@Ignore` on it.

**Comment by karussell** [comment]
:+1: (https://github.com/graphhopper/graphhopper/commit/33e2736885cadfc5483ffa19922b6910d6a4443a)
