### ISSUE TITLE
Do not show height graph again if closed

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1658]
(for desktop)

reported in #1654 from @easbar 

> Just a minor issue, but if I close the height graph (say because I want to see more of the map) and then drag one of the route markers it pops up again.

**Comment by boldtrn** [comment]
Good catch! We could save the state of the height graph as url parameter or cookie. WDYT?

**Comment by karussell** [comment]
Better just temporary in some JavaScript object to avoid complexity. Or we just use elevation=false :) ?

**Comment by boldtrn** [comment]
> Better just temporary in some JavaScript object to avoid complexity.

Sure we can certainly do that as well :+1: 

> Or we just use elevation=false :) ?

But then we can't easily enable it anymore, unless we change the URL to elevation=true.

**Comment by boldtrn** [comment]
BTW: this requires a change in the Leaflet.Heightgraph, I created an issue there: https://github.com/GIScience/Leaflet.Heightgraph/issues/57

**Comment by boldtrn** [comment]
I released a new version of Leaflet.Heightraph that offers the option to pass a callback function to remember the expand state.

**Comment by karussell** [comment]
Thx, will update the version!

> But then we can't easily enable it anymore, unless we change the URL to elevation=true

What do you mean here? If I currently load it on a phone I cannot force it to display the widget.

**Comment by boldtrn** [comment]
> What do you mean here? If I currently load it on a phone I cannot force it to display the widget

If we close the widget and set elevation=false, then no widget will be shown anymore at all. Unless someone understands the url parameters they can't enable the widget anymore.

On a phone the widget is not shown at all in general.

**Comment by karussell** [comment]
When rethinking about this. The best solution would be to hide the widget per default ("click the close button") on smaller display sizes, so that the user has a chance to see it even on mobile.

**Comment by karussell** [comment]
Would be nice, yes and somehow storing the state (in the elevation parameter?) so that it stays closed.
