### ISSUE TITLE
GraphHopperGeocodingIT#testExtent fails

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#1659]
These assertions fail: 

https://github.com/graphhopper/graphhopper/blob/6289fe5d2da5b1942de35c48141a4ae83c7b9faa/client-hc/src/test/java/com/graphhopper/api/GraphHopperGeocodingIT.java#L36-L45

The values returned from the API are:
```
minLon: -74.25909, maxLon: -73.7001809, minLat: 40.477399, maxLat: 40.9161785
```

**Comment by easbar** [comment]
This is what was expected so far:

![image](https://user-images.githubusercontent.com/17603532/60805083-693c7880-a17f-11e9-902f-b2b6838a797a.png)

And this is what we are getting now:

![image](https://user-images.githubusercontent.com/17603532/60805167-a0ab2500-a17f-11e9-931a-85b81f7145da.png)

I guess it is the difference between New York state and New York City.

**Comment by karussell** [comment]
Good catch - thanks! We should probably avoid such a error-prone query here and use a city like seattle?

extent:

> 0 | -122.459696
> 1 | 47.7341357
> 2 | -122.224433
> 3 | 47.4810022

**Comment by easbar** [comment]
Ok yes, but the only thing I do not understand is why is it:
```java
assertTrue(extent.minLon < -79); 
assertTrue(extent.maxLon > -72); 
```

so it checks that the left end of the box is left of -79 and the right end is right of -72, i.e. it passes also if the box is way too large (like minLon = -150 and maxLon = +200) ? This is why it fails if NYC is resolved (NYC's box is contained in the box for NY state).

Anyway I will change to seattle and use lower+upper limit for the box size.

**Comment by karussell** [comment]
> Ok yes, but the only thing I do not understand is why is it:

Yeah, indeed this looks wrong

> Anyway I will change to seattle and use lower+upper limit for the box size.

Thanks!
