### ISSUE TITLE
Why do we use Class<> to retrieve graphs from GraphHopperStorage ?

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#1668]
What is the reasoning behind `GraphHopperStorage#getGraph(Class<T> clazz)` ? 
There is already `GraphHopperStorage#getBaseGraph()`, which is the same as `GraphHopperStorage#getGraph(Graph.class)`, but to get the/a CH graph we need to do `GraphHopperStorage#getGraph(CHGraph.class)`. 

Would it not be more obvious to have `GraphHopperStorage#getCHGraph()` and `GraphHopperStorage#getCHGraph(Weighting)` ?

**Comment by karussell** [comment]
Good question, likely we can remove it. Either I wanted to have it too generic for other algorithms (would be bad) or I had it more generic for other stuff before it was like this (also bad ;)).

**Comment by easbar** [comment]
Ok. But either case I would not call it bad, its just the way code changes over time :)

**Comment by karussell** [comment]
The second case: yes. The first case is kind of "premature generalization" which is a trap I fell into too often (and is 'bad' or at least not good) but surely have learned from it :)
