### ISSUE TITLE
Wrong left turn instruction where it is forbidden

### ISSUE THREAD

**Issue by CarlosBrys** [graphhopper/graphhopper#1673]
At this point: 
(https://graphhopper.com/maps/?point=-27.378517%2C-55.899038&point=-27.377484%2C-55.900084&locale=es-419&vehicle=car&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale)

The router indicates to make a left turn, when there is a relationship that prohibits it, 
(https://www.openstreetmap.org/relation/3903260)

and the labels on the track indicate that it cannot be turned in that lane.
(https://www.openstreetmap.org/way/293799993)

Thanks for your attention.

**Comment by easbar** [comment]
You need to set `edge_based=true`. https://graphhopper.com/maps/?point=-27.378517%2C-55.899038&point=-27.377484%2C-55.900084&locale=es-419&vehicle=car&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale&edge_based=true
