### ISSUE TITLE
PBF-Less Docker Container?

### ISSUE THREAD

**Issue by Binternet** [graphhopper/graphhopper#1675]
I want to create a docker image which is not tied to a specific OSM extract (PBF), yet when I run the `Dockerfile` during the build process it requires for a PBF file.

Can I create a docker image without providing a PBF and only provide that upon container creation? and by that have a "dynamic" service that can change the PBF source without re-building the docker image?

**Comment by karussell** [comment]
This is not yet possible. If you want such a feature a pull request is appreciated. Still I'll close here as we have the Dockerfile as just "nice to have" and don't use it ourselves (yet).
