### ISSUE TITLE
SpatialRuleLookup issue with Polygons with holes

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#1680]
When creating Polygons from geojson in the `SpatialRuleLookupBuilder`, we call the method `Polygon#create(org.locationtech.jts.geom.Polygon polygon)`.

The create method uses the method `org.locationtech.jts.geom.Polygon#getNumPoints`, which returns all points of the Polygon, including the points for the holes. Therefore, the holes and the connection to the whole become part of the Polygon, which can lead false positive contain results, even for points outside of the polygon.

A quick-fix could be to only use the shell:
```
Coordinate[] shell = polygon.getExteriorRing().getCoordinates();

        double[] lats = new double[shell.length];
        double[] lons = new double[shell.length];

        for(int i = 0; i < shell.length; ++i) {
            lats[i] = polygon.getCoordinates()[i].y;
            lons[i] = polygon.getCoordinates()[i].x;
        }

        return new Polygon(lats, lons);
``` 

The proper solution would be to correctly read holes as holes and use them in the contains lookup.

**Comment by karussell** [comment]
Was fixed with #1680.
