### ISSUE TITLE
Ran the code without any changes, no map

### ISSUE THREAD

**Issue by tulssinep** [graphhopper/graphhopper#1685]
Downloaded the repo today and the web interface is missing a few items. 
<img width="1201" alt="Screenshot 2019-08-09 at 23 52 51" src="https://user-images.githubusercontent.com/11710965/62811136-dc2f6b00-bb00-11e9-8b56-1a21111cae9e.png">

I didn't change anything in it at all. The 
```
git clone git://github.com/graphhopper/graphhopper.git
cd graphhopper; git checkout master
# fetches main.js, can be omitted if no UI is needed
cd web/src/main/resources/ && ZFILE=/tmp/gh.jar && wget -O $ZFILE "https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=com.graphhopper&a=graphhopper-web&v=LATEST" && unzip $ZFILE assets/js/main.js && rm $ZFILE && cd ../../../..
./graphhopper.sh -a web -i europe_germany_berlin.pbf
# now go to http://localhost:8989/ and you should see something similar to GraphHopper Maps: https://graphhopper.com/maps/
```

works without any issues but as soon as I run it out of IntelliJ IDEA I suddenly see what the screenshot shows.

Is this a known issue for beginners?

All I did was to open the Project in IntelliJ and under run configurations set
```
Main class: com.graphhopper.http.GraphHopperApplication
VM options: -Xms1g -Xmx1g -server -Dgraphhopper.datareader.file=[your-area].osm.pbf -Dgraphhopper.graph.location=./[your-area].osm-gh
Program arguments: server config.yml
```

as described in https://github.com/graphhopper/graphhopper/blob/master/docs/core/quickstart-from-source.md

I eventually want to use Jsprit with OSM for a mTSP service so I thought GraphHopper might be a good start.

**Comment by karussell** [comment]
This should not be. What does the browser log say?

Make sure there is the file `assets/js/main.js`

**Comment by easbar** [comment]
I had the same problem and then I went into the `web` folder and ran  `npm run build` to create `main.js`. But you should already have it if you ran the CLI commands you pasted above ? Maybe try refreshing the browser (shift+reload in firefox or right click reload while in dev mode in chrome) ?

**Comment by tulssinep** [comment]
Thank you that has fixed it. Maybe adding this as a note to the instructions might help others. Gotta admit it's my fault for not checking Chrome's console tho

**Comment by karussell** [comment]
The command

```
cd web/src/main/resources/ && ZFILE=/tmp/gh.jar && wget -O $ZFILE "https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=com.graphhopper&a=graphhopper-web&v=LATEST" && unzip $ZFILE assets/js/main.js && rm $ZFILE && cd ../../../..
```

Should fetch the main.js. Can you try it command by command and tell us what went wrong, so that we can improve the docs? Maybe unzip or wget is not installed?

**Comment by mLupine** [comment]
I'm facing the exact same issue, and although the main.js file does exist in its directory, the server returns a 404 error when trying to access it.

**Comment by karussell** [comment]
Can you try executing
./graphhopper.sh clean
And then start the service again?

We probably should include downloading the main.js file inside the graphhopper.sh script to workaround some issues like downloading issues or not installed unzip tool.

**Comment by mLupine** [comment]
Yep, it cleaning the projects does indeed help. Thanks!
