### ISSUE TITLE
Isochrone reverse flow gives strange results in some cases

### ISSUE THREAD

**Issue by jesse-amano** [graphhopper/graphhopper#1692]
GraphHopper version: 0.11.0
OpenStreetMap version: http://download.geofabrik.de/north-america-140101.osm.pbf

A request like:
```
http://graphhopper.local:8989/isochrone?point=30.4859,-91.0827&time_limit=400&vehicle=car&buckets=4
```
gives a pretty reasonable-looking isochrone:
![image](https://user-images.githubusercontent.com/10690170/63555242-116e8c80-c4f5-11e9-8d83-63a7c30540ae.png)
(Visualized using geojson.io )

However, in reverse flow mode, the smaller time windows look a lot less realistic:
```
http://graphhopper.local:8989/isochrone?point=30.4859,-91.0827&time_limit=400&vehicle=car&buckets=4&reverse_flow=true
```
![image](https://user-images.githubusercontent.com/10690170/63555350-69a58e80-c4f5-11e9-9a9e-e80bae2bdd31.png)

In particular, the first isochrone bucket shows an area that doesn't include the point in question, and the second barely reaches it. Requests with a time limit less than 90 seconds fail as Bad Requests. All of this is noticeably different from the behavior of requests when `reverse_flow` is not set to `true`.

**Comment by michaz** [comment]
Thanks! Already tracking this at #1686
