### ISSUE TITLE
Edge-based routing without turn cost supporting encoder

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#1695]
When we specify `edge_based=true` but the encoder does not have `|turn_costs=true` we get an edge-based algorithm, but the weighting will not be wrapped by `TurnWeighting`. U-turns will then not be prevented properly. 

Should we throw an error if `edge_based=true`, but `!encoder.supports(TurnWeighting.class)` ?

**Comment by karussell** [comment]
> Should we throw an error if edge_based=true

Yes, sounds fine.
