### ISSUE TITLE
GraphHopper API offline

### ISSUE THREAD

**Issue by drnextgis** [graphhopper/graphhopper#170]
I've deployed GraphHopper using *.war file and Jetty. But if context path is not "/"
("/graphopper" for example) I get error message:

```
GraphHopper API offline? http://localhost:8085
```

Is it possible to change API URL or if I don't want use "/" I have to modify source code and build custom *.war file?

**Comment by rehanhammer** [comment]
Hello! i am getting same error graphhopper api offline
how do i solve this problem any idea?
