### ISSUE TITLE
execute npm as part of the maven cycle

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1700]
See #1641 why we removed main.js from the repo.

Now sometimes one can forget to create the main.js and sometimes one forgets to call `npm install`. Should this be done from the maven cycle? https://github.com/eirslett/frontend-maven-plugin

**Comment by michaz** [comment]
I think most Maven users rightly expect that a POM completely describes the build process and that there's nothing to forget. So I'd clearly say yes.
