### ISSUE TITLE
warning with JDK9 and bigger

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1734]
We need protobuf 3.7.0 to get rid of:

> Illegal reflective access by com.google.protobuf.UnsafeUtil

See
https://github.com/openstreetmap/osmosis/blob/master/gradle.properties#L21 and 
https://github.com/protocolbuffers/protobuf/issues/3781

Related to #1317

**Comment by carlos-mg89** [comment]
There's Protobuf 3.10 and 3.9 that seem to include speed improvements and bug fixes too. I guess you're aware of that anyway, but just in case. It's definitely great that you're working on a solution for these annoying warnings :+1:

**Comment by karussell** [comment]
Unfortunately there is no new osmosis release for the latest protobuf versions. It is still at 3.6.1
