### ISSUE TITLE
Public Transit instructions

### ISSUE THREAD

**Issue by safe-bug** [graphhopper/graphhopper#1739]
Hello,
I want to run graphhopper to get public transit routing but the instructions written in the docs lead me to something like car routing instructions. There is no Bus instructions like this demo (https://www.graphhopper.com/blog/2018/05/16/real-time-public-transit-routing/)
How can I have something like this? Is there any wiki doc?

**Comment by mprins** [comment]
> How can I have something like this? Is there any wiki doc?

https://github.com/graphhopper/graphhopper/blob/master/reader-gtfs/README.md

**Comment by safe-bug** [comment]
Thanks for the reply @mprins, I used these instructions and could get routes but as you see in the image the returned results aren't Bus instructions, they are like car instructions.

https://camo.githubusercontent.com/543db460a703a28a79b20e42ef794d48e71b4793/68747470733a2f2f7777772e6772617068686f707065722e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031372f30312f677466732d707265766965772e706e67

**Comment by karussell** [comment]
Thanks @safe-bug for raising this question. It is just a different UI. The instructions are taken from the /route endpoint. BTW: in the future please use our forum for questions: https://discuss.graphhopper.com/

**Comment by safe-bug** [comment]
Thanks @karussell, sure!
