### ISSUE TITLE
Path simplification is very slow compared to routing

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#1764]
For example for 50 random locations in Germany `PathSimplification.simplify` takes about 80% of the time needed for calculating the route (`GraphHopper.route(request)` for node-based CH), something like: 600 of 720ms.
Apparently, for more locations this gets even worse, e.g. for 500 locations the path simplification takes 55s out of the 57s it takes to calculate the route (>95%). This is maybe expected, because for longer routes CH does not get so much slower, while the path contains a lot more points that need to be simplified.

I added a little measurement file in the `performance_via_routing` branch.

**Comment by karussell** [comment]
Thanks, there is indeed something wrong.

When I disable instructions via `request.getHints().put("instructions", false)` then simplification gets much faster (5x for my simple tests). Although I would have expected that looping over smaller paths will only add a small slowdown.

**Comment by boldtrn** [comment]
Maybe this is due to the class PathSimplification? There is a short cut if you don't simplify. Also DouglasPeucker itself is quite computation heavy.

**Comment by karussell** [comment]
> Also DouglasPeucker itself is quite computation heavy

Yes, but why should several calls to parts of the path being much slower than one call for the full path? It should be even faster for the smaller parts as we keep certain points and do not throw them away.

**Comment by boldtrn** [comment]
That's true as well. That's indeed a bit weird. Are you using any PathDetails? That slows down the simplification as well.

**Comment by easbar** [comment]
The problem is that when there are path details or instructions we are calling `DouglasPeucker#simplify` many times on the different intervals and every time it is called we do a full `compressNew` on the `PointList`.  For my example via-route through Germany with 50 points this means moving the lat/lon/ele arrays with more than 100.000 points in memory for thousands of times. In `DouglasPeucker#approx=true` we do something similar, but in this case its no problem because even though we are calling `subSimplify` many times there is only a single call to `compress` at the end.

So the problem occurs if: 

* path simplification is enabled (`GraphHopper.forServer()`)
* the route has many points
* there are instructions and/or path details

**Comment by easbar** [comment]
Had to revert #1782 in 6cc92dfb1ab36057354f16524160e84554d21f63, because of incompatibility with the navigation SDK.
