### ISSUE TITLE
Does GraphHopper-0.13 from GitHub Contain Route Optimization API via jsprit?

### ISSUE THREAD

**Issue by miandai** [graphhopper/graphhopper#1770]
The [GraphHopper Official website]( https://docs.graphhopper.com/#tag/Route-Optimization-API) contain the Route Optimization API.

I am not sure whether the source code of GraphHopper-0.13 from Github contains Route Optimization API via jsprit. Does anyone know it?

Thanks very much!

**Comment by karussell** [comment]
This repository is about the routing engine only. For jsprit see https://github.com/graphhopper/jsprit and https://www.graphhopper.com/open-source/

For questions please use our public forum: https://discuss.graphhopper.com/
