### ISSUE TITLE
wrong fileListURL?

### ISSUE THREAD

**Issue by Beuthmaster** [graphhopper/graphhopper#1771]
Is it possible, that the fileListURL inside the mainActivity is wrong?
After instantly after opening the app I receive this error message: "Are you connected to the internet? Problem while fetching remote area list:"
Seems like the url is not up to date anymore...
![Screenshot_2019-10-29-11-58-49-303_com graphhopper android 15789](https://user-images.githubusercontent.com/57135722/67761474-a042dc80-fa43-11e9-89ff-8d7887be0ef0.png)

**Comment by karussell** [comment]
Have changed the server side so that it should work for the latest snapshot (1.0)

Can you switch to the latest stable 0.13 branch? 

Also for questions please use our public forum: https://discuss.graphhopper.com/

**Comment by Beuthmaster** [comment]
Thank you, greetings from Beuth HS/Roland Wagner!
