### ISSUE TITLE
Remove the `GraphExtension` interface

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#1772]
I think this abstraction is not very helpful. So far there is only `TurnCostExtension` implementing it and the functionality is rather limited. In many (currently 6 in production and 26 in tests) cases we need to cast the extension to `TurnCostExtension`. 

I can imagine all kinds of meta/additional data one likes to store for nodes/edges, but why would we use a `GraphExtension` for this ? Maybe we prefer a simple `int[]`, use an independent `DataAccess`, fetch data from disk etc., this can easily be done by using the node/edge ids, I see no real advantage of storing the `additionalNode/Edge` field right in the graph and for example for `TurnCostExtension` we already use this field only to store a reference to another `DataAccess`. 

Maybe I am missing something, but as far as I am concerned we can just keep the `TurnCostExtension` (without the interface) in `BaseGraph` (probably make it optional/can be null instead of using `NoOpExtension`).

**Comment by karussell** [comment]
Yes, we should definitely do this! Maybe before this I have to make this branch production ready that allows storing arbitrary key value pairs like OSM tags or translated road names etc https://github.com/graphhopper/graphhopper/commits/string_index
