### ISSUE TITLE
Problem GraphHopper Export PBF

### ISSUE THREAD

**Issue by nyoakaway** [graphhopper/graphhopper#1777]
I have a problem when I try to run GraphHooper to extract the PBF information. He gets this information and nothing else happens. Already has a PBF running on another server that he did all the process normally, but after 1 year when I went to upgrade, it is on this screen and nothing happens. I left it for over 13 hours thinking that something would happen but nothing. Any idea what it might be?

![image](https://user-images.githubusercontent.com/42919302/68024772-d07bbc80-fc89-11e9-9009-11a4c1829831.png)

**Comment by karussell** [comment]
Please avoid asking questions on the issues. Instead use our public forum: https://discuss.graphhopper.com/c/graphhopper/public-transit

Also if you post there: never use screenshots when you can paste the logs as text. Explain step by step what you did. You did exactly the same on another server, then it is very unlikely a software problem.
