### ISSUE TITLE
Request fails when not setting the weighting and/or the vehicle with CH and finite u-turn costs

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#1788]
If we specify something like `prepare.ch.weightings=fastest|u_turn_costs=40` in the configuration and then do not specify a weighting in `GHRequest`, GH tries to determine the weighting by looking at the `CHProfile(s)`. This leads to:

```
java.lang.IllegalArgumentException: Cannot find CH profile for weighting map {edge_based=true, weighting=fastest|u_turn_costs=40, vehicle=car} in entries: [fastest|car|edge_based=true|u_turn_costs=40.
```

**Comment by easbar** [comment]
This is very ugly. We already have this complex logic to determine the `CHProfile` when `edge_based=true/false` or `u_turn_costs` is not given on the request. Handling the case(s) where also the vehicle and/or the weighting is missing makes this even worse.

I think the easiest solution (for us of course) would be to just throw an error if CH is requested but the vehicle and weighting is not given, so we force the client to pass this information with the request.

In the mid/long run I think every `CHProfile` should just have a name/id and to use it this name/id has to be passed along with the request, #1708.

**Comment by karussell** [comment]
> (Update: no the vehicle is set to "car" by default if missing sigh)

I think it uses the first flag encoder if missing. I.e. if no car is given it should still work.

> In case we use multiple weightings we basically pick one at random which makes no sense

Oh, really random?

> I think the easiest solution (for us of course) would be to just throw an error if CH is requested but the vehicle and weighting is not given, so we force the client to pass this information with the request

Hmmh, yeah. This would break backward compatibility as currently the minimal request needs just two points. Couldn't it pick the first CHProfile as default settings for vehicle+weighting and the order is defined as

```
flag_encoders=vehicle1,vehicle2,...
ch.weightings=weighting1,weighting2,...
=>
ch profile 1 = vehicle1 + weighting1
ch profile 2 = vehicle2 + weighting1
...
ch profile ? = vehicle1 + weighting2
...
```

IMO it makes sense to not specify these parameters, because if you just have one vehicle and one weighting defined you would not expect to be forced to specify them in the request.

**Comment by easbar** [comment]
> I think it uses the first flag encoder if missing. I.e. if no car is given it should still work.

Yes if vehicle is missing on the request its set to the first encoder here (somewhat random):

https://github.com/graphhopper/graphhopper/blob/c0e129cd1880a4d56938af53e48da5009cb96bea/core/src/main/java/com/graphhopper/GraphHopper.java#L986-L990


> Oh, really  random?

Well not 'random' but it depends on the order the profile string are in this list (so in a sense its random)

https://github.com/graphhopper/graphhopper/blob/c0e129cd1880a4d56938af53e48da5009cb96bea/core/src/main/java/com/graphhopper/routing/ch/CHAlgoFactoryDecorator.java#L232-L234

> Hmmh, yeah. This would break backward compatibility

Yeah I am working on this. Its doable, and with some cleanup its maybe not that bad...
