### ISSUE TITLE
Move setting of segment size into `DataAccess` constructors

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#1792]
Have not really looked into this, but it seems many `Storable` implementations have this method anyway (I guess because most of them use some `DataAccess` underneath), for example:

- `CHGraphImpl`
- `LocationIndex`
- `TurnCostExtension`
- `GraphStorage`
- `NameIndex`
- all `DataAccess`es

**Comment by karussell** [comment]
Yes, would make sense. What is the reason you stumbled over this?

**Comment by easbar** [comment]
I was checking where we are using `CHGraphImpl` instead of `CHGraph` and one of the reasons we do this e.g. in `GraphHopperStorage` was because of `setSegmentSize()`. It was similar when we discussed about using an interface for `TurnCostExtension`.

**Comment by easbar** [comment]
Does it make sense to call `setSegmentSize` after a `DataAccess` has been used (written to) ? Or can this even be a wrong thing to do ? If it must never be called after writing to the `DataAccess` I wonder if we should rather remove it from the `DataAccess` interface and add a `segmentSize` parameter to the constructors of the objects that need it ?

**Comment by easbar** [comment]
So if `setSegmentSize` may not be called after the first writes to the `DataAccess` its probably a bad idea to even expose it in `Storable` and I think it should rather be more hidden than exposed ?

**Comment by karussell** [comment]
> Or can this even be a wrong thing to do ?

Yes, this can be even wrong (stumbled over this ugliness for the StringIndex again).

> I think it should rather be more hidden than exposed ?

Yes. The only current use case is to reduce the storage size for small data. E.g. for tests (small graph data) but also for they DataAccess `keys` in StringIndex or StorableProperties.

In early days I was experimenting with this setting and was hoping that there is a sweet spot regarding performance. But it wasn't and so I picked a size of ~1MB so that the smallest possible graph is not too big and a very big graph has not too many segments (although it still can be X-thousand)

**Comment by easbar** [comment]
So something like `dir.find("nodes", daType, segmentSize)` ? This would mean that if the `segmentSize` parameter is given and the `.find()` call creates a new `DataAccess` it uses this `segmentSize` to do so. If `.find()` finds something it would just ignore the parameter. And then we have four overloads for `Directory.find` (with/without DAType and with/without segmentSize).

**Comment by karussell** [comment]
Yes, sounds good. Probably we should rename to findOrNew? Otherwise ignoring the segmentSize is a bit ugly... or doing a similar comparison like we do for daType?

https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/storage/GHDirectory.java#L83-L84

**Comment by easbar** [comment]
Ok I think I would rename it (anyway) *and* do this comparison ?

**Comment by karussell** [comment]
Yes

**Comment by easbar** [comment]
I tried briefly but its not so straight-forward because of `copyTo` etc. For now I'm happy with #1794, but at some point we should do this.

**Comment by easbar** [comment]
Interestingly, we always use `Directory#find` only to create something, never to return something that exists. `GHDirectory` keeps references to created objects and `find` would return the already created object, **but** we never use this feature. Ok, we use it **once** in `LineIntIndex`, but I think this is just an accident and can be fixed. So actually instead of adding `segmentSize` to `dir.find("nodes", daType, segmentSize)` I would rather remove the map of created DataAccess in `GHDirectory` entirely and rename `find` to `create`. Code that creates a DataAccess in Directory will use a reference to the created DataAccess anyway, so why should there be a `Directory` that keeps references to all the `DataAccess`es?

Ok this was still a bit simplified :) `GHDirectory` uses the map also for `getAll`, but, ..., this is never used. It also uses the map for `close` and `clear`, and they are even used in production, but, ... only once for elevation providers. And these elevation providers just temporarily create a directory to 'abuse' the map instead of simply using their own map.

Honestly, I feel like we do not need `Directory` at all.
