### ISSUE TITLE
Documentation not correct at  graphhopper/docs/core/location-index.md 

### ISSUE THREAD

**Issue by AzureIP** [graphhopper/graphhopper#1793]
Hi,
In your Documentation at the location index code example the code is not totally correct:
```
GraphHopper hopper = new GraphHopper();
hopper.set...
hopper.importOrLoad();

LocationIndex index = hopper.getLocationIndex();

//  now you can fetch the closest edge via:
QueryResult qr = findClosest(lat, lon, EdgeFilter.ALL_EDGES );
EdgeIteratorState edge = qr.getClosestEdge();
```

Yout have to call the function findClosest on the index object you have created before.
So it has to be `QueryResult qr = index.findClosest(lat, lon, EdgeFilter.ALL_EDGES );`.
I would advise to change this.

Thanks!

**Comment by karussell** [comment]
Thanks! Yes, we'll probably create some code in the repository (to keep those examples up to date) that we then reference in our documentation.

**Comment by AzureIP** [comment]
Hello karussell,
Thanks for the reply. I have a furthure question to that code. What do I get exactly?
![Screenshot (15)](https://user-images.githubusercontent.com/32673190/68776346-383dea00-0630-11ea-9b25-91a293bd7fca.png)

I asked for the closesd way/road to the point in the lake. (Simply the first point in my dataset)
```
QueryResult qr = index.findClosest(location.lat, location.longd, EdgeFilter.ALL_EDGES );
            EdgeIteratorState edge = qr.getClosestEdge();
            PointList ghPoint3DS = edge.fetchWayGeometry(0);
            for (int i = 0; i < ghPoint3DS.size(); i++) {
                System.out.println("got point " + i + " along: " + ghPoint3DS.getLat(i) + ", " + ghPoint3DS.getLon(i));
            }
```

And I get some Points close to it in some kind of a line. But not points of the closest road where the navigation would begin. What are there three points, and how do I get points from the closest road?

**Comment by karussell** [comment]
For questions please use our public forum (create a new topic): https://discuss.graphhopper.com/
