### ISSUE TITLE
Method for getting a route as GPX Track not available.

### ISSUE THREAD

**Issue by AzureIP** [graphhopper/graphhopper#1796]
Hello,

In the simple routing example at docs/core/routing.md it is mentioned that you can call a method createGPXList() on an object of InstructionList.

So:
```
InstructionList il = path.getInstructions();
List<GPXEntry> list = il.createGPXList();
```

But there is no method createGPXList() available. And the class "GPXEntry" is unknown and an import is not an option in the context actions of IntelliJ.

So I can't get the GPX track the way it is described in the documentation.

**Comment by karussell** [comment]
Yes, this was refactored in #1595

See now: GpxFromInstructions.createGPXList

This documentation issue will be fixed with #1793. So closing now here.
