### ISSUE TITLE
Replace Weighting.matches(HintsMap) with a different hook

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1800]
See #1797. We need one place where we:

 1. convert request parameters into a Weighting (createWeighting) and
 2. pick the correct CH/LMProfile 

Is a new hook in GraphHopper required, so that it can be used in GH core, map matching & isochrone?

**Comment by easbar** [comment]
I guess when we start using the `profile` parameter we'll do this in mm,isochrone&navigation as well?
