### ISSUE TITLE
Some potential ArrayIndexOutOfBound Exception

### ISSUE THREAD

**Issue by JulyChen728** [graphhopper/graphhopper#1801]
Hi all,
Our bug scanner has reported some potential ArrayIndexOutOfBound Exception.

The first one is at [BBox.java#L50](https://github.com/graphhopper/graphhopper/blob/1.0-pre4/api/src/main/java/com/graphhopper/util/shapes/BBox.java#L50) since the length of the parameter `coords` may not be greater than 3. A similar situation is at [GHPoint.java#L53](https://github.com/graphhopper/graphhopper/blob/1.0-pre4/api/src/main/java/com/graphhopper/util/shapes/GHPoint.java#L53) .

The second is at [PointList.java#L569-570](https://github.com/graphhopper/graphhopper/blob/1.0-pre4/api/src/main/java/com/graphhopper/util/PointList.java#L569) since the constant index may be larger than the array`s bound. 

Thanks.

**Comment by ITWOI** [comment]
Hi @michaz, may I ask are these true bugs or false positives? 
Thanks.
