### ISSUE TITLE
GHGeocodingEntry uses wrong JsonProperty

### ISSUE THREAD

**Issue by calvinkehl** [graphhopper/graphhopper#1825]
**Describe the bug**
The class `GHGeocodingEntry` uses "`house_number`" as JsonProperty:
```
@JsonProperty("house_number")
public void setHouseNumber(String houseNumber) {
    this.houseNumber = houseNumber;
}
```
The geocoding API response (https://graphhopper.com/api/1/geocode) sends property as "`housenumber`". Therefore all hits contain `houseNumber = null`.

**To Reproduce**
Make an API call as follows:
```
...
GraphHopperGeocoding graphHopperGeocoding = new GraphHopperGeocoding();
boolean reverse = true;
GHPoint point = new GHPoint(location.getLatitude(), location.getLongitude());
GHGeocodingRequest req = new GHGeocodingRequest(point, "de", 20);
graphHopperGeocoding.setKey(KEY);
GHGeocodingResponse resp = graphHopperGeocoding.geocode(req);
for (GHGeocodingEntry hit : resp.getHits()) {
    hit.getHouseNumber(); // always null!
}
```
`hit.getHouseNumber()` will always be `null`, no matter what location you put in.

**Expected behavior**
`hit.getHouseNumber()` should return the actual housenumber ;-)

**System Information**
JAVA 1.8, directions-api-client-hc-0.10.0.jar (Code of `GHGeocodingEntry` is the same on master).

**Comment by karussell** [comment]
Are you sure that this fails? We include both properties: https://github.com/graphhopper/geocoder-converter/pull/57

**Comment by calvinkehl** [comment]
I'm not using the geocoder-converter, I'm using `graphhopper/client-hc`!

**Comment by karussell** [comment]
Sorry, I meant a different thing. But yes, this does not apply to the default geocoding provider. Will fix this.

**Comment by karussell** [comment]
Thanks for reporting this!
