### ISSUE TITLE
Routes going straight through motorway junction can route via "motorway_link" instead of staying on "motorway"

### ISSUE THREAD

**Issue by cheweytoo** [graphhopper/graphhopper#1836]
**Describe the bug**

Routes following a motorway straight through a motorway junction occasionally leave the motorway to follow a parallel "motorway_link" before rejoining the motorway at exactly the same junction.

**To Reproduce**

Minimal cases reproducing this on osm.org  and graphhopper.com right now:

case 1:
https://www.openstreetmap.org/directions?engine=graphhopper_car&route=49.4177%2C8.5474%3B49.4011%2C8.5448#map=15/49.4094/8.5464

https://graphhopper.com/maps/?point=49.41477%2C8.547868&point=49.403814%2C8.545475&locale=en-US&vehicle=car&weighting=fastest&elevation=true&turn_costs=true&use_miles=false&layer=Omniscale

case 2:
https://www.openstreetmap.org/directions?engine=graphhopper_car&route=49.1543%2C8.5640%3B49.1385%2C8.5541#map=15/49.1464/8.5590

https://graphhopper.com/maps/?point=49.154787%2C8.564261&point=49.138958%2C8.554337&locale=en-US&vehicle=car&weighting=fastest&elevation=true&turn_costs=true&use_miles=false&layer=Omniscale

**Expected behavior**
In such a case, routes should obviously never leave the motorway in the first place.

**System Information**
"Car (GraphHopper)" used via openstreetmap.org; graphhopper.com directly

**Comment by karussell** [comment]
The problem is likely to be a data issue. E.g. this motorway_link

https://www.openstreetmap.org/way/38480541

is tagged maxspeed=100. And the motorway is tagged 80 km/h

https://www.openstreetmap.org/way/61479090
