### ISSUE TITLE
Issue RoadClassEncoder via EncodedValueLookup when using mtb and motorway

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#1843]
When I set multiple vehicles in the config, including mtb, for example: 
```
graph.flag_encoders: car, mtb
```

My config looks like this:
```
graph.encoded_values: road_class,road_class_link,road_environment,max_speed,road_access
graph.bytes_for_flags: 8
```

If I lookup an encoded value in `InstructionsFromEdges` via `evLookup.getEnumEncodedValue(RoadClass.KEY, RoadClass.class);` I get an EncodedValue as expected.

For motorways this seems returns "other" instead of "motorway". Other road classes seem to be fine. If I only use car it works fine. 

I cross tested with `graph.flag_encoders: car, bike` and this particular issue did not exist. I don't think it's necessarily related to the EncodedValueLookup, but that's how I discovered this.

An example route where this happens is this (I think it happens for all motorways): http://localhost:8989/maps/?point=49.303926%2C8.627148&point=49.302688%2C8.626859

Maybe something is wrong with the number of bits reserved by the mtb encoder?

**Comment by karussell** [comment]
Uh, this looks ugly. Thanks for the report.

btw: this is no longer necessary: `graph.bytes_for_flags: 8`

**Comment by boldtrn** [comment]
Thanks for the fast fix :tada:. 

> btw: this is no longer necessary: graph.bytes_for_flags: 8

Thanks, I missed that change!
