### ISSUE TITLE
Roundabout instructions

### ISSUE THREAD

**Issue by martinsauvage** [graphhopper/graphhopper#185]
Hello,

Graphhopper is a great routing engine but I am surprised there is no exit direction in any roundabout.

Example:
http://graphhopper.com/maps/?point=47.931512%2C-2.38869&point=47.931814%2C-2.388325

How to get "take exit 3 on the roundabout" direction?

Is it something you plan to implement in the future or maybe there is an option to use?

Thanks,
Martin

**Comment by karussell** [comment]
We've decided to implement roundabout instruction already in #316. #116 will follow later to make them always working for CH too.

**Comment by karussell** [comment]
Works now for CH and on GH Maps too

**Comment by martinsauvage** [comment]
Great !
