### ISSUE TITLE
Initialization with example config should work like the default Java settings

### ISSUE THREAD

**Issue by develar** [graphhopper/graphhopper#1862]
I am author of https://graphhopper.develar.org/ and contributor of [locus-addon-graphhopper](https://github.com/asamm/locus-addon-graphhopper).

I working on updating to `1.0-pre18`, as latest release 0.13 version is not usable (see https://github.com/asamm/locus-addon-graphhopper/pull/4#issuecomment-577033241)

I regenerated all maps, but now I get error  ""Encoded values do not match:"" 
![image](https://user-images.githubusercontent.com/350686/72975013-595d4c80-3dd0-11ea-8cc1-9184e092d91c.png)

problem is that last shift `24` (config) is not equal to `27` (27).

I do not understand the error and what I should do to fix it. Looks like that check is too strict.

Android version: 8.1.0
Java version to generate routing data: 13.0.1+9-jre
gh config to build routing data: https://github.com/develar/gh-routing-data/blob/c0fe3f5a396c5a03a47bd8268c2691460291f56c/internal/builder/builder.go#L158

Android java code to create is very simple  (and it worked for 0.11):

```
GraphHopper gh = new GraphHopper().forMobile();
gh.setAllowWrites(false);
gh.setCHEnabled(true);
gh.setElevation(true);
boolean load = gh.load(routingItem.getAbsolutePath());
```

**Comment by karussell** [comment]
We certainly can improve to make this easier, but if there is a difference then it **will break** somewhere and there is nothing 'too strict' about it.

The problem is likely that you used a config and standard Java to import the data and then try to access it via a Java configurated GraphHopper. Currently GraphHopper won't help or guide you with this.

Can you check if it works if you do the import with a config where the whole line with `graph.encoded_values` is removed?

> as latest release 0.13 version is not usable

Please note that then every release before was also "not usable". It is "just" an improvement regarding memory usage, there was no regression introduced and then fixed.

**Comment by develar** [comment]
> Can you check if it works if you do the import with a config where the whole line with graph.encoded_values is removed?

No `graph.encoded_values` line in my config. Looks it it the problem and I must to specify it?

**Comment by develar** [comment]
I tried to add surface

```
GHÄÄgraph.encoded_values=surface|version=322840198|bits=4|index=0|shift=0|store_both_directions=false,road_class|version=891942665|bits=5|index=0|shift=4|store_both_directions=false,road_class_link|version=146178506|bits=1|index=0|shift=9|store_both_directions=false,road_environment|version=-437928439|bits=3|index=0|shift=10|store_both_directions=false,max_speed|version=-643590495|bits=5|index=0|shift=13|store_both_directions=true,road_access|version=-1878573729|bits=4|index=0|shift=23|store_both_directions=false,roundabout|version=149974905|bits=1|index=0|shift=27|store_both_directions=false,get_off_bike|version=127393434|bits=1|index=0|shift=31|store_both_directions=false
graph.flag_encoders=bike2|speed_factor=2.0|speed_bits=4|turn_costs=false|version=3,mtb|speed_factor=2.0|speed_bits=4|turn_costs=false|version=2,racingbike|speed_factor=2.0|speed_bits=4|turn_costs=false|version=2,hike|speed_factor=1.0|speed_bits=4|turn_costs=false|version=3,car|speed_factor=5.0|speed_bits=5|turn_costs=false|version=2
```

the same error.

> problem is likely that you used a config and standard Java to import the data and then try to access it via a Java configurated GraphHopper. Currently GraphHopper won't help or guide you with this.

How else do you can generate routing data for Android ;)?

I will try to read GraphHopper source code more closely or just will prepare some pathed version.

**Comment by karussell** [comment]
> How else do you can generate routing data for Android ;)?

Instead of the initialization via the config, you can do the same initialization that you do on Android via Java, see ImportCommand. But surely the example config should work with the default Java settings. Have renamed this issue accordingly.

**Comment by develar** [comment]
> Instead of the initialization via the config, you can do the same initialization that you do on Android via Java, see ImportCommand. But surely the example config should work with the default Java settings. Have renamed this issue accordingly.

Please note — neither generator, neither Android app do some custom initialization. Android app doesn't set `EncodingManager`. Instead, GraphHopper loads `properties` file and creates whatever suitable configuration.

So, for me not clear why it is broken in 1.x version. And why GraphHopper cannot simply configure itself using `properties` as it was before.

I continue investigation myself. Thanks for quick answers, at least I am sure that it is not some stupid error on my side or known regression in 1.x :)

**Comment by karussell** [comment]
> And why GraphHopper cannot simply configure itself using properties as it was before.

It never "configured itself". It always relied on certain, matching defaults.

> So, for me not clear why it is broken in 1.x version

There is no 1.x version yet. Only previews :)

**Comment by develar** [comment]
Shouldn't be `get_off_bike` in `DefaultTagParserFactory`? .... In my case  the only diff:

```
get_off_bike|version=2140540190|bits=1|index=0|shift=27|store_both_directions=false
```

vs 

```
get_off_bike|version=-1500205055|bits=1|index=0|shift=24|store_both_directions=false
```

version `2140540190` is not equal to `-1500205055`.

What I suspect — GraphHopper adds `get_off_bike` automatically when `bike` is requested, and at this moment state for `getVersion` implementation differs from state when we do init `EncodingManager` to load graph (reader app).

Easily to reproduce on java 8 or java 11 on desktop (for austria: https://d.graphhopper.develar.org/2019-01-21/austria-18-50.osm-gh.zip):

```
class Routing {
  companion object {
    @JvmStatic
    fun main(args: Array<String>) {
      val gh = GraphHopper().forMobile()
      gh.isAllowWrites = false
      val ghDataDir = "/Volumes/data/Downloads/austria.osm-gh"
      val dir = RAMDirectory(ghDataDir, true)
      val properties = StorableProperties(dir)
      if (!properties.loadExisting()) {
        throw IllegalStateException("Cannot load properties to fetch EncodingManager configuration at: ${dir.location}")
      }

      val builder = EncodingManager.Builder()
      properties.get("graph.encoded_values")?.let {
        builder.addAll(gh.encodedValueFactory, it)
      }
      // GraphHopper doesn't expose flagEncoderFactory, but it is - stateless DefaultFlagEncoderFactory is used.
      properties.get("graph.flag_encoders")?.let {
        builder.addAll(DefaultFlagEncoderFactory(), it)
      }

      gh.encodingManager = builder.build()

      gh.isCHEnabled = (properties.get("prepare.ch.done") == "true")
      gh.setElevation(properties.get("prepare.elevation_interpolation.done") == "true")

      gh.load(ghDataDir)
    }
  }
}
```

**Comment by develar** [comment]
btw, no difference between java 13 and java 8 (I generated with the same config using java 8 and compared `properties` file). So, looks like it is not java version dependent issue.

**Comment by karussell** [comment]
Thanks for investigating this!

Can you post the complete error message as string? I.e. what is configured vs. what is in the graph.

> Shouldn't be get_off_bike in DefaultTagParserFactory?

There should be no need as get_off_bike is added as soon as [a BikeFlagEncoder is found](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/routing/util/EncodingManager.java#L336).

> So, looks like it is not java version dependent issue.

Yes, this should no longer be a problem.

**Comment by develar** [comment]
> Can you post the complete error message as string? I.e. what is configured vs. what is in the graph.

Error from my desktop test app (code is the same as for Locus app, see above):

```
Exception in thread "main" java.lang.IllegalStateException: Encoded values do not match:
Graphhopper config: road_class|version=887801716|bits=5|index=0|shift=0|store_both_directions=false,road_class_link|version=146044462|bits=1|index=0|shift=5|store_both_directions=false,road_environment|version=-448080443|bits=3|index=0|shift=6|store_both_directions=false,max_speed|version=2003990561|bits=5|index=0|shift=9|store_both_directions=true,road_access|version=717676379|bits=4|index=0|shift=19|store_both_directions=false,roundabout|version=544120317|bits=1|index=0|shift=23|store_both_directions=false,get_off_bike|version=-1500205055|bits=1|index=0|shift=24|store_both_directions=false
Graph: road_class|version=887801716|bits=5|index=0|shift=0|store_both_directions=false,road_class_link|version=146044462|bits=1|index=0|shift=5|store_both_directions=false,road_environment|version=-448080443|bits=3|index=0|shift=6|store_both_directions=false,max_speed|version=2003990561|bits=5|index=0|shift=9|store_both_directions=true,road_access|version=717676379|bits=4|index=0|shift=19|store_both_directions=false,roundabout|version=544120317|bits=1|index=0|shift=23|store_both_directions=false,get_off_bike|version=2140540190|bits=1|index=0|shift=27|store_both_directions=false
Change configuration to match the graph or delete /Volumes/data/Downloads/austria.osm-gh--2/
	at com.graphhopper.storage.GraphHopperStorage.loadExisting(GraphHopperStorage.java:255)
	at com.graphhopper.GraphHopper.load(GraphHopper.java:780)
	at Routing$Companion.main(Routing.kt:35)
	at Routing.main(Routing.kt)
```

> Instead of the initialization via the config, you can do the same initialization that you do on Android via Java, see ImportCommand. 

Thanks for the hint. I will try it as my next step, since I am out of and for me totally unclear for now what field and why in  `SimpleBooleanEncodedValue.getVersion` (produced by `GetOffBike`) implementation `staticHashCode(val, fwdDataIndex, bwdDataIndex, bits, maxValue, fwdShift, bwdShift, fwdMask, bwdMask)`  differs (generator vs reader).

**Comment by develar** [comment]
Ok, I see that indeed problem is that 

> What I suspect — GraphHopper adds get_off_bike automatically when bike is requested, and at this moment state for getVersion implementation differs from state when we do init EncodingManager to load graph (reader app).

I wrote my own importer in java and I added `encodingManagerBuilder.add(OSMGetOffBikeParser())` explicitly. And... boo! I got `version=2140540190|bits=1|index=0|shift=27` exactly as reader expected. And loading was successful. https://github.com/develar/graphhopper-importer/blob/18a61c3ea1cf02ee9f00635c96be63c4d9a16967/src/org/develar/gh/Generator.kt#L26

Not yet checked on mobile phone, but should work as on desktop.

**Comment by karussell** [comment]
In #1876 I did not yet found the cause, but improved things, so that an import via config.yml is possible and then in Android you only need to do (no encoded value setup for the default case):

```
encodingManager = new EncodingManager.Builder().add(new CarFlagEncoder()).add(new BikeFlagEncoder()).build();
hopper = new GraphHopper().setEncodingManager(encodingManager);
hopper.load(defaultGraphLoc);
```

The goal is:

```
hopper = new GraphHopper();
hopper.load(defaultGraphLoc);
```

**Comment by karussell** [comment]
@develar can you try the latest version of #1876. This should work now as expected and no special Java code is required on Android side if the default config.yml is used for import. There were a few things to fix and now GraphHopper is better thanks to your report and time! I would appreciate your feedback and if it really fixed your problems.

**Comment by develar** [comment]
@karussell I can confirm that explisint using of `OSMGetOffBikeParser` is not required anymore.  I removed also explicit building of `EncodingManager`, loading works without error.

The only addition to `gh.load(ghDataDir)`, it is configuring of `setCHEnabled` and `setElevation`.

```kotlin
      val dir = RAMDirectory(ghDataDir, true)
      val properties = StorableProperties(dir)
      if (!properties.loadExisting()) {
        throw IllegalStateException("Cannot load properties at: ${dir.location}")
      }

      gh.isCHEnabled = (properties.get("prepare.ch.done") == "true")
      gh.setElevation(properties.get("prepare.elevation_interpolation.done") == "true")

      gh.load(ghDataDir)
```

but it is responsibility of client. (the same was for 0.11 version).

Thanks for quick fix.

**Comment by karussell** [comment]
Thanks for the update and report again!
