### ISSUE TITLE
RandomizedRoutingTest.randomGraph_withQueryGraph fails

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1864]
It fails for seed 115606809083L. See https://travis-ci.org/graphhopper/graphhopper/jobs/641008521

The reason seems that the path contains the node "42" twice. Don't ask - I always thought that 42 is the answer to everything ;) !

```
refPath: [50, 36, 28, 32, 49, 42,     8, 38, 11, 13, 19, 27, 51] 
path:    [50, 36, 28, 32, 49, 42, 42, 8, 38, 11, 13, 19, 27, 51]
```

This happens only for edge-based CH (CH_ASTAR and CH_DIJKSTRA).

**Comment by easbar** [comment]
> too many strict violations: 12 / 50

This is more of a false positive than a bug. There is a loop with zero weight at node 42, so both paths including and excluding the loop are 'solutions' to the shortest path problem. This is why a limited number of such 'strict' violations are allowed in the test. But occasionally there are too many. Not doing the strict checks would mean there is a higher risk of not spotting a real error, so not sure what to do :) I thought about this many times and so far this error occurred so rarely that I felt like its fine. But anyway I increased the strict limit to make this less likely :)

**Comment by karussell** [comment]
Ah, ok. This is indeed tricky. Maybe instead of increasing the count should we better change the check of nodes and allow e.g. a difference of 1 or even throwing out 0 weight edges before comparing? Hmmh, but it could also happen that a completely different path is returned ...

**Comment by easbar** [comment]
Yes I think you are right. I changed it such that paths that only differ in some duplicate consecutive nodes no longer count as strict violations. In turn I made the tests more strict such that they fail as soon as there are more than three strict violations. With this setting the test ran 1000 times without an error.

dd8d342667c73a8c5ab8e3ec92dec3c81c75fd1a

**Comment by easbar** [comment]
>  Hmmh, but it could also happen that a completely different path is returned ...

Yes this is why we introduced strict violations in the first place, but the special case of zero weight loops just happens too frequently so I now think its worth handling it differently.

**Comment by karussell** [comment]
Ok, thanks! Maybe we should double check that the edge weight that is removed is really 0?

**Comment by easbar** [comment]
> Ok, thanks! Maybe we should double check that the edge weight that is removed is really 0?

I do not think this is necessary. If the total weight of the path is not equal the whole test fails anyway.

**Comment by karussell** [comment]
Ah, yes, you are right! Thanks!

**Comment by karussell** [comment]
It seems tests still fail (under different circumstance): https://ci.appveyor.com/project/graphhopper/graphhopper/builds/30391928

```
[ERROR] Tests run: 18, Failures: 1, Errors: 0, Skipped: 9, Time elapsed: 5.968 s <<< FAILURE! - in com.graphhopper.routing.RandomCHRoutingTest
[ERROR] random[EDGE_BASED, u-turn-costs=-1](com.graphhopper.routing.RandomCHRoutingTest)  Time elapsed: 0.219 s  <<< FAILURE!
java.lang.AssertionError: 
Too many strict violations: 8/100
wrong distance 48->54, expected: 3269.0704281928233, given: 3271.4953561149755
wrong distance 23->6, expected: 3137.4350720778475, given: 3139.86
wrong distance 48->40, expected: 2976.4950720778475, given: 2978.92
wrong distance 48->47, expected: 4058.2259226288684, given: 4060.650850551021
wrong distance 23->15, expected: 2194.8310720778472, given: 2197.2560000000003
wrong distance 68->51, expected: 4054.3094835646043, given: 4056.7339945699523
wrong distance 48->62, expected: 3540.8934664438952, given: 3543.3180130217856
wrong distance 48->39, expected: 3076.247058086556, given: 3078.671986008709
	at com.graphhopper.routing.RandomCHRoutingTest.runRandomTest(RandomCHRoutingTest.java:195)
	at com.graphhopper.routing.RandomCHRoutingTest.random(RandomCHRoutingTest.java:91)
```

**Comment by easbar** [comment]
Hm looking at the error message the difference between expected and given distance is exactly the same for all 8 errors: 2.424928. So I guess somewhere there are two edges with different distance, but equal weight (different distance&different speed) and the test can fail for all paths using this edge... Should be very rare I just ran the test 1873 times without an error :)

**Comment by karussell** [comment]
Yes, I also think it is a false positive. The problem with this is that over time we could tend to ignore such problems and just hit "rebuild" (just analyzing my own behaviour). But softening the limits is also bad... ugly

**Comment by easbar** [comment]
> The problem with this is that over time we could tend to ignore such problems and just hit "rebuild" (just analyzing my own behaviour).

Yes this shouldn't be, but it also depends how often this happens. Lets say it happened once now and lets wait how long it takes until it happens again.

**Comment by karussell** [comment]
It happened again - so once a year ;) ?

```
[ERROR]   RandomizedRoutingTest.randomGraph_withQueryGraph:265 Too many strict violations: 9 / 50, seed: 613703450790941
```

**Comment by easbar** [comment]
In this case there is a 'loop' consisting of nodes 36,31,48,15 that can be used in both directions (equal weight and distance but different nodes).

```md
expected: [51, 30, 43, 25, 46, 33, 29, 36,**31, 48, 15,**36, 29, 33, 28, 1, 9, 11, 50]
given:    [51, 30, 43, 25, 46, 33, 29, 36,**15, 48, 31,**36, 29, 33, 28, 1, 9, 11, 50], 
```

This can happen, but at the same time its so rare I do not think it justifies adding extra code that handles this situation.
