### ISSUE TITLE
PathDetails Country, DEU / AUT switched

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#1875]
I just tried the new SpatilRule PR #1853

I am not yet sure if it's related to the PR or not.

If I set the config to:

```
graph.encoded_values: country
```

And request a route, the resulting PathDetails are switched. Germany is AUT and Austria is DEU.

![Screenshot from 2020-01-28 14-57-19](https://user-images.githubusercontent.com/1553525/73270276-a1b8a800-41de-11ea-8e98-96ab11f7b29a.png)
![Screenshot from 2020-01-28 14-57-14](https://user-images.githubusercontent.com/1553525/73270277-a1b8a800-41de-11ea-9d4d-05fe01fb5563.png)

**Comment by karussell** [comment]
Thanks for trying this out!

Do you mean PR #1829? 

> I am not yet sure if it's related to the PR or not.

And can you try without it? Maybe we introduced a bug earlier :(

**Comment by boldtrn** [comment]
> Do you mean PR #1829?

Sorry I meant #1853 :). I tried the current master after #1853 was merged.

**Comment by otbutz** [comment]
The SpatialRuleParser encodes the id of the rule but the PathDetailsBuilderFactory interprets the value as the ordinal of the Country enum. So everything depends on the rules being added in the "right" order.

**Comment by otbutz** [comment]
...which entirely depends on the order in the JSON feature collection

**Comment by boldtrn** [comment]
The same issue also exists with #1829.

**Comment by otbutz** [comment]
Makes sense as i didn't touch the encoding.

**Comment by otbutz** [comment]
We would need to change how the PathDetailsBuilderFactory obtains its String values. We would need to use the SpatialRulesLookup in order to fix this once and for all.

**Comment by boldtrn** [comment]
I think there are a few options to solve this.

- My favorite option would be to store the used ids in the graph properties somehow. Something like: used_spatial_rules=aut,deu. This would fix the order and IDs - maybe we should combine this with the approach to also configure the used SpatialRules in the config (below).

Other options could be:
- Make the used SpatialRules configurable. For example define the order and possible SpatialRules in the config and use the this to translate IDs.
- Always load the SpatialRulesLookup, during import and during the runtime and to lookup the IDs. I don't like that option that much to be honest, I think this could become problematic for environments like Android.
- Fix the IDs of a country. We could always apply ID 1 to Germany, ID 2 to Austria, etc. (or use telephone codes 49 for Germany, 43 for Austria (seems like a massive waste of bits though)).

**Comment by otbutz** [comment]
> My favorite option would be to store the used ids in the graph properties somehow

> configure the used SpatialRules in the config

If we add support for #1808 there might be a lot of rules. Encoding them as bitset would require quite some storage. If we only encode the ID of the last ruled which got applied, we would still need to keep track of the loaded IDs and their order somewhere. Doing this manually by adding all these IDs to the config file seems clunky and error prone

> Always load the SpatialRulesLookup, during import and during the runtime and to lookup the IDs. I don't like that option that much to be honest, I think this could become problematic for environments like Android.

This would be my preferred solution ATM. But i've no idea about the restrictions on Android.

> Fix the IDs of a country

Users might want to add rules for states, cities or arbitrary areas.

**Comment by karussell** [comment]
> Doing this manually by adding all these IDs to the config file seems clunky and error prone

Yeah, this sounds a bit clunky and parsing of the JSON would be better.

Would it be sufficient to parse the spatial rules once and only store the mapping of String to int in e.g. a StringIndex (or the StorageProperties)? Then, "on load" we do not need to parse the JSON again as the mapping can be quickly loaded from disk.

**Comment by boldtrn** [comment]
> Doing this manually by adding all these IDs to the config file seems clunky and error prone

Yes, I forgot to mention, the default could be to simply load all defined SpatialRules :). And we would only need to configure them if we need a subset.

> Would it be sufficient to parse the spatial rules once and only store the mapping of String to int in e.g. a StringIndex (or the StorageProperties)?

Yes, that's what I mean with the graph properties :). That would be my favorite solution.

**Comment by otbutz** [comment]
> Would it be sufficient to parse the spatial rules once and only store the mapping of String to int in e.g. a StringIndex (or the StorageProperties)? Then, "on load" we do not need to parse the JSON again as the mapping can be quickly loaded from disk.

Are you referring to the `StorableProperties` of the `GraphHopperStorage`? Looks like a good solution but we would need to properly mask the IDs as the user might give us arbitrary Strings here. A simple schema like `1=DE,2=AT` might break if the user defines a rule with an ID that contains  `=` or `,`.

**Comment by karussell** [comment]
> Are you referring to the StorableProperties of the GraphHopperStorage? 

Yes

>A simple schema like 1=DE,2=AT might break if the user defines a rule with an ID that contains = or ,

I would use a comma separated value `DE,AT` and then the default is 0, DE=1, AT=2 implicitly. And once the import is done the config.yml is used only to compare with the list from the StorableProperties ([same way we do this for encoded values or FlagEncoders](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java#L254))

**Comment by otbutz** [comment]
> config.yml is used only to compare with the list from the StorableProperties

What would be the content of the config to compare against?

**Comment by karussell** [comment]
@otbutz did this work in #1799?

Have created: https://github.com/graphhopper/graphhopper/pull/1911 - WDYT?
