### ISSUE TITLE
Improve graphhopper.sh input file documentation

### ISSUE THREAD

**Issue by HarelM** [graphhopper/graphhopper#1878]
**Describe the bug**
When using graphhopper.sh I'm unable to make it download the file I want.

**To Reproduce**
I've tried running the following:
graphhopper.sh web asia/israel-and-palestine-latest.osm.pbf -fd
graphhopper.sh web /asia/israel-and-palestine-latest.osm.pbf -fd
graphhopper.sh web /asia/israel-and-palestine.pbf -fd
graphhopper.sh web israel-and-palestine.pbf -fd
But none of them seems to download the file I need when starting up as the address the script is trying to use is incorrect.

**Expected behavior**
I should be able to download the file I need.
I think it has to do with some replace code in the sh file.

**System Information**

I'm using docker and I would like to avoid adding a file to the volume.

**Screenshots & Logs**

If applicable, add screenshots and log output.
It should be easy to reproduce and fix, let me know if you need my help.

**Comment by karussell** [comment]
You should be able to use:
```
./graphhopper.sh import asia_israel-and-palestine.pbf
```

(Please ask on our forum before creating an issue here)

**Comment by HarelM** [comment]
The problem, the way I see it, is with the documentation of the command line.
I don't see how I should've guessed I should use `asia_` instead of `asia/`
This is what is says:
`-i | --input <file>       path to the input map file or name of the file to download`
I also tried using full http address and it didn't work.
It would help if you could reopen and fix the documentation...

**Comment by karussell** [comment]
Sure. Would you have time to contribute this change?

**Comment by HarelM** [comment]
No problem, I'll send a pull request tomorrow-ish.

**Comment by HarelM** [comment]
I have created the following PR: #1884

**Comment by karussell** [comment]
Fix was merged.
