### ISSUE TITLE
Cant load map - CH profile error

### ISSUE THREAD

**Issue by andreddosantos** [graphhopper/graphhopper#1881]
**Describe the bug**
While implementing the same logic to load maps as the available android version

```
GraphHopper tmpHopp = new GraphHopper().forMobile();
tmpHopp.load(new File(mapsFolder, areaToLoad).getAbsolutePath() + "-gh");
hopper = tmpHopp;
return null;
```
It used to used to load the maps without any issue

Today when testing the application i'm now receiving an error

**To Reproduce**

Steps to reproduce the behavior. For examples:

1. checkout recent and stable version of GraphHopper
2. download a certain.pbf
3. generate map
4. run the app
4. load the maps

**Expected behavior**
Graph loads with no issues

**System Information**

group: 'com.graphhopper', name: 'graphhopper-core', version: '1.0-pre18'

**Screenshots & Logs**

<img width="388" alt="Captura de ecrã 2020-01-29, às 16 18 34" src="https://user-images.githubusercontent.com/4041944/73377114-70131000-42b6-11ea-90f8-2b3c91c23624.png">

Kind regards
Awesome library

**Comment by easbar** [comment]
Hm, I cannot reproduce this. Can you be a bit more specific about what you did? How did you 'run the app'? Which configuration did you use?

**Comment by develar** [comment]
@andreddosantos To save your time — you can grab data for 1.0-pre18 from https://graphhopper.develar.org/ Tested and proven to work with `1.0-pre18` :)

**Comment by karussell** [comment]
@develar saying "1.0-pre18 and higher' is a bit risky as we might and will likely break the format before the 1.0 release. Also for next releases: we currently have the policy to allow us format changes to make development faster. I understand that this is ugly for the offline routing use case and maybe someone with mobile experience could have an eye on this aspect :) ?

**Comment by develar** [comment]
> I understand that this is ugly for the offline routing use case and maybe someone like you with mobile experience could have an eye on this aspect 

I don't see anything wrong with that. If some app recommends to use http://graphhopper.develar.org/ (or any other resource) as source of map, then author of such app simply ensures that there are compatible routing data for used version of graphhopper. As recently a new version of addon for Locus Map was released. Data for several graphhopper versions (i.e. different versions of some apps/addons) can be provided.

For end users it is not important to use recent version of graphhopper library. What's important — are data is actual (generated using latest OSM) and is routing correct :)

I will remove "and higher".

BTW — I am in no way want to simplify maintaining of self-hosted graphhopper server, the only reason why I decided to share routing data to simplify life of mobile app users (as here there is a simple reason — no online access to graphhopper server and not possible to use https://www.graphhopper.com/pricing/).

**Comment by karussell** [comment]
> BTW — I am in no way want to simplify maintaining of self-hosted graphhopper server, the only reason why I decided to share routing data

This is really appreciated and I really hope mobile usage increases some time a bit more :)

And no worries: we have a robust business (model) ;D

**Comment by andreddosantos** [comment]
Hello guys thank you so much for your help, but i'm still having this issue.

I'm new to the technology and i don't understand some parts of what i was reading in the link suggested by @easbar.

* My implementation for loading graphs has the same code of the android sample app (literally copy paste) as referred on the opening comment of this issue. It used to work until i tested yesterday.

* I've generated the graphs as indicated[ in the sample app documentation](https://github.com/graphhopper/graphhopper/blob/master/docs/android/index.md#maps) (generated new graph yesterday)

I've tried to used the provided maps by @develar link, and I've also found an error while loading, anyway the ideia is that i can i generate my own maps as suggested on the documentation. 

So i'm confused regarding what i should do, to have the previous behavior. Should i makes changes to the loadgraph procedure or to the graph generation?

Thanks for help

**Comment by karussell** [comment]
Let's move discussion to our forum: https://discuss.graphhopper.com/c/graphhopper

**Comment by easbar** [comment]
> i don't understand some parts of what i was reading in the link suggested by @easbar

Yes sorry this link wasn't really meant to help you but more as a reminder for the devs that there was a similar issue. Feel free to open an issue in the forum as @karussell suggested, because this seems more usage related
