### ISSUE TITLE
Issue with calculating turn instructions with turn_costs=true and ch

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#1883]
Something seems to be wrong with the instructions when setting `turn_costs=true`.

Just compare the two examples, [with turn costs](https://graphhopper.com/maps/?point=48.450155%2C8.768463&point=49.667628%2C9.775085&locale=de-de&vehicle=car&weighting=fastest&elevation=false&turn_costs=true&debug=true&use_miles=false&layer=OpenStreetMap), [without turn costs](https://graphhopper.com/maps/?point=48.450155%2C8.768463&point=49.667628%2C9.775085&locale=de-de&vehicle=car&weighting=fastest&elevation=false&turn_costs=false&debug=true&use_miles=false&layer=OpenStreetMap).

![Screenshot from 2020-01-29 18-42-18](https://user-images.githubusercontent.com/1553525/73382045-1cf58900-42c7-11ea-964b-4e3150c91637.png)
![Screenshot from 2020-01-29 18-42-07](https://user-images.githubusercontent.com/1553525/73382046-1cf58900-42c7-11ea-80c3-059a6079fe2b.png)

**Comment by easbar** [comment]
Did this use to work or did you never try before?

**Comment by boldtrn** [comment]
> Did this use to work or did you never try before?

I never tried this before with turn costs, so I don't know if it ever worked before, I guess it didn't. But I think this is something we should look at. I just noticed this when working on #1047 when comparing results with my local instance and was wondering about the differences.

**Comment by easbar** [comment]
Under what condition are you skipping the instructions?

**Comment by boldtrn** [comment]
One important criteria for skipping instructions are the surrounding edges. If they seem like a turn alternative, then an instruction is created to make sure the is notified about the turn. If there are no alternatives an instruction can be skipped.

**Comment by boldtrn** [comment]
Maybe I opened the issue too fast. I cannot reproduce the issue on my local master using:

```
graph.flag_encoders: car|turn_costs=true
prepare.ch.weightings: fastest
prepare.ch.edge_based: edge_and_node
``` 

But it does exist for the directions API. Maybe I am missing something? Or should we move this issue over to the directions API?

**Comment by karussell** [comment]
Yes, this is a deployment problem and our edge-based setup is a bit older (we had an issue that we need to fix)
