### ISSUE TITLE
Feature Request: "Extend end to..."

### ISSUE THREAD

**Issue by jeffrey-friedl** [graphhopper/graphhopper#1887]
I would find it convenient to be able to build a route by clicking on the starting point, then the next place I want to go, then on to the next waypoint, etc. This is a pretty standard way of building routes and lines.

To do this in Graphhopper would require a new item in the right-click menu, "Extend end to..."
which would be functionally equivalent to turning the current end point into the final intermediary      point, and then adding a new ending point.

BTW, let me thank you so much for recent changes (adding numbers to the left-side list of intermediate points, and turning off the auto-zoom when adding intermediate points).... they make route building soooooo much easier. Appreciated!!

**Comment by easbar** [comment]
Yes this would be useful, and there is already an open issue for it here: #1360.

**Comment by jeffrey-friedl** [comment]
Oops, sorry for not having noticed that. Yes, that's exactly the same request.

**Comment by easbar** [comment]
No problem and thanks for reporting.
