### ISSUE TITLE
remove or improve RoutingAlgorithmFactoryDecorator

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1889]
See #1823 and #1708. 

Additionally there is a bug if only LM preparation is done, then lm.disable=true/false does not work (was introduced [here](https://github.com/graphhopper/graphhopper/pull/1085/files)).

Also see big usage problems described in #1401.

**Comment by easbar** [comment]
Afaik the decorators currently provide two features: 

1) its an abstraction/pluggable layer that allows adding more algorithms to `GraphHopper`
2) we can (in theory) combine multiple algorithms (like LM+CH)

Regarding 1) I am wondering whether or not anyone is using this at the moment. If not we should remove it for now and if need be add it back later when it becomes more clear what the future of the `GraphHopper` class really looks like :) Possibly it should be refactored to the point where it provides easy access to the underlying components and no longer contains any real logic. In this case anyone who likes to add another algorithm could just use these components in some custom way without needing the `GraphHopper` class at all. The other possibility would be that `GraphHopper` still provides certain mechanisms and hooks to extend its behavior, but I feel like its not really ready for this and we should add this later.

Regarding 2) I think we only ever did this to combine LM+CH and even this is currently disabled, so I would rather remove it for now and if we want to put it back we can add it again in a less generic way maybe.

**Comment by easbar** [comment]
And what about this:

https://github.com/graphhopper/graphhopper/blob/75a8a61bc80296fe8e643ae981192d2c21ba00c1/core/src/main/java/com/graphhopper/routing/lm/LMAlgoFactoryDecorator.java#L237-L243

It seems inconsistent with CH: For CH we throw an error if no preparation is available for the given vehicle+weighting, but for LM we fall back to the simple factory. Should there not also be an error for LM in this case?

**Comment by karussell** [comment]
> I think we should remove it for now and if need be add it back later when it becomes more clear what the future of the GraphHopper class really looks like 

:+1: 

> In this case anyone who likes to add another algorithm could just use these components in some custom way without needing the GraphHopper class at all.

Yeah, this was the intention: make everything easy with the GraphHopper class (create GraphHopperStorage, LocationIndex, OSMReader, CH+LM preparation). 

But currently it feels ugly to set everything up without the GraphHopper class as you loose the handling in GraphHopper.route. So maybe a first step would be to remove the decorators and make this possible via a simple list of chPreparations etc and in a follow up issue move the `route` method into a new GraphHopperQuery class that uses the storage, index etc. (??)

> Regarding 2) I think we only ever did this to combine LM+CH and even this is currently disabled

I think it will still work (it is not disabled IMO), but we do not use this feature as it does not give us faster routes for node-based traversal.

> Should there not also be an error for LM in this case?

Yeah, not sure why we have it like this. An exception makes sense at least if lm.disable=false.

**Comment by easbar** [comment]
> I think it will still work (it is not disabled IMO)

I think its disabled: 
https://github.com/graphhopper/graphhopper/blob/75a8a61bc80296fe8e643ae981192d2c21ba00c1/core/src/main/java/com/graphhopper/routing/lm/LMAlgoFactoryDecorator.java#L226-L227
