### ISSUE TITLE
Replace Measurement with a JMH benchmark

### ISSUE THREAD

**Issue by otbutz** [graphhopper/graphhopper#1890]
https://www.baeldung.com/java-microbenchmark-harness

As for now i'd create a benchmark for the SpatialRuleLookup.

**Comment by easbar** [comment]
Can we just add a JMH benchmark to the `Measurement` class so we can start to get a feeling about how it compares to the current approach?

**Comment by otbutz** [comment]
I'll have a go at it :wink:

**Comment by otbutz** [comment]
@easbar i've created a benchmark for the SpatialRulesLookup: https://github.com/graphhopper/graphhopper/compare/master...otbutz:jts_measurement

Run `mvn clean install` and launch it as a Java application if you want to test it.

Porting the rest of the Measurement class would be a bigger effort. We would need to provide one or more state objects to provide Graphhopper instances for the benchmarks. The tricky part is that all parameters need to be present as annotated fields in order to properly pass them as command line arguments.

**Comment by karussell** [comment]
What would be the benefits?

I see the advantages of JMH for people starting from scratch to avoid beginners mistakes like forgetting the warm up, simple report etc, but in our case we already have what we want and it is easily extendable and results go into a file etc. Additionally Measurement is not really about microbenchmarks.

**Comment by otbutz** [comment]
> Additionally Measurement is not really about microbenchmarks.

That's one of the reasons i'd like to use JMH at least for the rules lookup.

**Comment by otbutz** [comment]
@karussell better? https://github.com/graphhopper/graphhopper/compare/master...otbutz:lookup_benchmark
