### ISSUE TITLE
Cannot pass cache location using VM variable -Dgraphhopper.graph.location=

### ISSUE THREAD

**Issue by MathStPierre** [graphhopper/graphhopper#1897]
When you specify the graph location using the VM variable **-Dgraphhopper.graph.location** the following statement will return empty folder string : 

`String graphHopperFolder = args.get("graph.location", "");`

The use of **-Dgraphhopper.graph.location** was working in 1.0-pre20, so it seems to be a regression.

**Comment by easbar** [comment]
Yes this 'feature' of passing command line arguments was / is being removed. What do you use this for? If you start the GH server you can instead use `-Ddw.graphhopper.graph.location=xyz`.

**Comment by MathStPierre** [comment]
For debugging purpose this is nice to be able to create different run configurations with different parameters. So -Ddw.graphhopper.graph.location is replacing -Dgraphhopper.graph.location? What is the preferred way to setup the cache location? Adding an entry in the config.yml file?

**Comment by easbar** [comment]
Yes. GH server is using Dropwizard for its configuration. So the default way is reading the `config.yml` file. Using `-Dgraphhopper.graph.location` was a bit of a workaround because it was used to manually overwrite the configuration after it was read from `config.yml`. Using `-Ddw.graphhopper.graph.location` is the Dropwizard way of overwriting single configuration properties of `config.yml`.

To support different run configurations I suggest using a dedicated local `config.yml` file.

**Comment by MathStPierre** [comment]
Thanks -Ddw..... is working fine.

**Comment by ratrun** [comment]
After a git pull on master I have now a similar problem with `-Dgraphhopper.datareader.file=` , here I get 
`java.lang.IllegalArgumentException: If no graph.location is provided you need to specify an OSM file.`
Using `-Ddwgraphhopper.datareader.file=` does not help and both are still used in graphhopper.sh.

**Comment by easbar** [comment]
> -Ddwgraphhopper.datareader.file=

Are you missing the dot after `dw` maybe?

> still used in graphhopper.sh
This script needs to be adjusted yes

**Comment by ratrun** [comment]
Sorry, I meant `-Ddw.graphhopper.datareader.file=` does not help for me, I had this typo just here on the issue.

**Comment by easbar** [comment]
I think this could be a dropwizard issue. If there is no `graphhopper.datareader` node in the configuration yet we cannot add this property this way. Can you try putting

```yaml
datareader.file=xyz
```

in your `config.yml` (in the `graphhopper` section)? This way you should be able to overwrite `xyz` with you desired file location.

**Comment by ratrun** [comment]
Thanks, the config.yml way works fine. But this is a little bit inconvinient for automation.

**Comment by easbar** [comment]
Ok so this way you could overwrite the value in `config.yml` with the command line argument? What kind of automation use case are you using this for?

**Comment by ratrun** [comment]
I have a simple script similar to `graphhopper.sh` which I pass my OSM filename.
Thank you. I can confirm that following works: Put something into `config.yml`: `datareader.file=xyz`, then use `-Ddw.graphhopper.datareader.file=pqr`, here `pqr` gets used.
So the trick is just to put some `datareader.file` into `config.yml` and overwrite it with `-Ddw.graphhopper.datareader.file=`. As this is a litte bit confusing it should be documented.

**Comment by karussell** [comment]
Yeah, this is ugly. Or we should fix this problem in dropwizard: https://github.com/dropwizard/dropwizard/issues/3145

**Comment by easbar** [comment]
Should we throw an error (or print a message) if the system properties contain something like `graphhopper.datareader...`?

**Comment by karussell** [comment]
Ok, have done this.

BTW: this is related to https://github.com/graphhopper/graphhopper/pull/1879
