### ISSUE TITLE
Number of visited nodes depends on vehicles, even when they are not used?

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#1910]
In `GraphHopperIT` we are using `"car,bike"` as encoders, but then we only use "car" for routing. Strangely, the number of visited nodes strongly depends on whether or not we add "bike" to the list of encoders, even though we are not using it.

9173f050dcd4d81c3966855a8150ab906e4018c3

**Comment by karussell** [comment]
This is IMO not a problem and just the fact that a bike network creates additional junction/tower nodes in the car network. I.e. if we could count the "visited pillar nodes" this should be constant (although much higher).

**Comment by easbar** [comment]
Ah yes that makes sense, good to keep in mind, thanks! Btw these extra 'junctions' lead to this problem: #1858.
