### ISSUE TITLE
strange hike route

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1919]
The tour is 9min vs. 1min and still being picked: https://graphhopper.com/maps/?point=59.912966%2C10.866337&point=59.913536%2C10.867946&locale=nb&vehicle=hike

Maybe some bug in our tagging processing for [this way](https://www.openstreetmap.org/way/113662058)?

**Comment by otbutz** [comment]
Wrong way: https://www.openstreetmap.org/way/78470272

I think our road access parser is picking up `motor_vehicle=private` here which might cause this behavior.

**Comment by karussell** [comment]
Ok, so was a duplicate of #1831 and seem to be fixed now.
