### ISSUE TITLE
/bin/sh: 1: cd: can't cd to web 

### ISSUE THREAD

**Issue by JeongJun-Lee** [graphhopper/graphhopper#1926]
**Describe the bug**
A clear and concise description of what the bug is. If you are unsure if this is really a bug, please create a new topic in [our forum](https://discuss.graphhopper.com/c/graphhopper).

If you have an Android application that uses GraphHopper, please always post to the [forum](https://discuss.graphhopper.com/c/graphhopper/graphhopper-ios-and-android) before and include logs and the version of
your Android system.

**To Reproduce**
From docker install:
docker build -t graphhopper:master .

Instead of a manual reproduction it would be even better to have a unit or integration test reproducing the issue.

**Expected behavior**

**System Information**
MacOS: 10.13.6
Graphhopper: currnet master branch

**Screenshots & Logs**
Sending build context to Docker daemon  130.7MB
Step 1/12 : FROM openjdk:8-jdk
 ---> e890fe39c302
Step 2/12 : ENV JAVA_OPTS "-server -Xconcurrentio -Xmx1g -Xms1g -XX:+UseG1GC -Ddw.server.applicationConnectors[0].bindHost=0.0.0.0 -Ddw.server.applicationConnectors[0].port=8989"
 ---> Running in 49e576c39825
Removing intermediate container 49e576c39825
 ---> b6aba0ffeed7
Step 3/12 : RUN mkdir -p /data && mkdir -p /graphhopper
 ---> Running in f2d89aa8e702
Removing intermediate container f2d89aa8e702
 ---> 6121096d45a8
Step 4/12 : RUN apt-get install -y wget        && curl -sL https://deb.nodesource.com/setup_11.x | bash -        && apt-get install -y nodejs
 ---> Running in 5eea9c34f3c3
Reading package lists...
Building dependency tree...
Reading state information...
wget is already the newest version (1.20.1-1.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

================================================================================
================================================================================

                              DEPRECATION WARNING                            

  Node.js 11.x is no longer actively supported!

  You will not receive security or critical stability updates for this version.

  You should migrate to a supported version of Node.js as soon as possible.
  Use the installation script that corresponds to the version of Node.js you
  wish to install. e.g.

   * https://deb.nodesource.com/setup_10.x — Node.js 10 LTS "Dubnium" (recommended)
   * https://deb.nodesource.com/setup_12.x — Node.js 12 LTS "Erbium"

  Please see https://github.com/nodejs/Release for details about which
  version may be appropriate for you.

  The NodeSource Node.js distributions repository contains
  information both about supported versions of Node.js and supported Linux
  distributions. To learn more about usage, see the repository:
    https://github.com/nodesource/distributions

================================================================================
================================================================================

Continuing in 20 seconds ...

## Populating apt-get cache...

+ apt-get update
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:2 http://deb.debian.org/debian buster InRelease [122 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [49.3 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [181 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7907 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [7380 B]
Fetched 8331 kB in 10s (825 kB/s)
Reading package lists...

## Installing packages required for setup: lsb-release...

+ apt-get install -y lsb-release > /dev/null 2>&1

## Confirming "buster" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_11.x/dists/buster/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
Warning: apt-key output should not be parsed (stdout is not a terminal)
OK

## Creating apt sources list file for the NodeSource Node.js 11.x repo...

+ echo 'deb https://deb.nodesource.com/node_11.x buster main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src https://deb.nodesource.com/node_11.x buster main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease
Hit:3 http://deb.debian.org/debian buster-updates InRelease
Get:4 https://deb.nodesource.com/node_11.x buster InRelease [4584 B]
Get:5 https://deb.nodesource.com/node_11.x buster/main amd64 Packages [768 B]
Fetched 5352 B in 6s (967 B/s)
Reading package lists...

## You may also need development tools to build native addons:
     sudo apt-get install gcc g++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
     echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
     sudo apt-get update && sudo apt-get install yarn

Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  nodejs
0 upgraded, 1 newly installed, 0 to remove and 13 not upgraded.
Need to get 16.2 MB of archives.
After this operation, 77.9 MB of additional disk space will be used.
Get:1 https://deb.nodesource.com/node_11.x buster/main amd64 nodejs amd64 11.15.0-1nodesource1 [16.2 MB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 16.2 MB in 6s (2593 kB/s)
Selecting previously unselected package nodejs.
(Reading database ... 13255 files and directories currently installed.)
Preparing to unpack .../nodejs_11.15.0-1nodesource1_amd64.deb ...
Unpacking nodejs (11.15.0-1nodesource1) ...
Setting up nodejs (11.15.0-1nodesource1) ...
Removing intermediate container 5eea9c34f3c3
 ---> 325f82b7cc3b
Step 5/12 : COPY . /graphhopper/
 ---> dfa31141b23a
Step 6/12 : WORKDIR /graphhopper
 ---> Running in af68a3ddf3d3
Removing intermediate container af68a3ddf3d3
 ---> f1ea61fd7fb3
Step 7/12 : RUN cd web && npm install && npm run bundleProduction && cd ..
 ---> Running in b313039ab76f
/bin/sh: 1: cd: can't cd to web
The command '/bin/sh -c cd web && npm install && npm run bundleProduction && cd ..' returned a non-zero code: 2

**Comment by karussell** [comment]
> From docker install:
> docker build -t graphhopper:master .

If you execute this command from the root of this repository it works. (Still I have upgraded the node version). Also prefer fetching the docker image from docker hub or create it from a stable branche like 0.13 instead of master.
