### ISSUE TITLE
nodeA nodeB ordering

### ISSUE THREAD

**Issue by naser13** [graphhopper/graphhopper#1932]
there is this statement in the [docs](https://github.com/graphhopper/graphhopper/blob/master/docs/core/technical.md):

> (nodeA-nodeB where nodeA is always smaller than nodeB)

however in current master i cant find anything ensuring this and indeed there are edges that baseNode is greater than adjNode.

is this behaviour intended? docs are outdated?

**Comment by karussell** [comment]
The technical document describe the underlying storage mechanism. See [here](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/storage/EdgeAccess.java#L30).

Please post questions to the forum first. When you are then sure it is an issue you or we'll create an issue.
