### ISSUE TITLE
Web feature request: center-map-at input box

### ISSUE THREAD

**Issue by jeffrey-friedl** [graphhopper/graphhopper#1933]
On https://graphhopper.com/maps/, it'd be convenient to have a "center at" input box down in one corner, where one could put a lat/lon pair and have the map then centered on that location (or, perhaps, a new right-click menu "center map at...." option). 

(To be clear, this is related only to the display, and not any part of any route.... I know that for the route, I can just enter the lat/lon directly into the boxes at left.)

Thanks!

**Comment by easbar** [comment]
#1433

**Comment by karussell** [comment]
Closing as duplicate

**Comment by jeffrey-friedl** [comment]
Oh wow, I'm ashamed.... it's a dup of a request I myself made a year and a half ago. My appologies

**Comment by karussell** [comment]
No problem. I once found a helpful stackoverflow answer and then I was puzzled that the author was me ;)
