### ISSUE TITLE
RuntimeException: Time was negative

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1938]
Error:
```
2020-02-28 15:25:52.374 [dw-4182 - GET /route?turn_costs=true&type=json&locale=en_US&weighting=fastest&<redacted>&vehicle=car] ERROR i.d.j.errors.LoggingExceptionMapper - Error handling a request: fec09cafb194a822
java.lang.RuntimeException: Time was negative -9223372036852055154 for index 0. Please report as bug and include:<redacted> (Hints:{turn_costs=true, instructions=true, edge_based=true, way_point_max_distance=1.0, calc_points=true, type=json, locale=en_US, weighting=fastest, vehicle=car})
        at com.graphhopper.routing.template.ViaRoutingTemplate.calcPaths(ViaRoutingTemplate.java:182)
        at com.graphhopper.GraphHopper.calcPaths(GraphHopper.java:1087)
        at com.graphhopper.GraphHopper.route(GraphHopper.java:962)
        at com.graphhopper.resources.RouteResource.doGet(RouteResource.java:143)
```

Unfortunately I cannot reproduce this problem on the server using the still running same version and the exact same request parameters (14 via points in the Netherlands, point 3 == point 4)

There are more of these bugs in the last days but none of them is reproducible. The smallest one still had 2 via points. But it only occurred for the edged based CH it seems.

**Comment by easbar** [comment]
What version was this?

**Comment by karussell** [comment]
1.0-pre23(.2)

**Comment by karussell** [comment]
Ok, this is very likely a concurrency bug and the problem is the reusage of IntsRef in DefaultTurnCostProvider or the change of it in TurnCostStorage.get

**Comment by easbar** [comment]
I wonder if this is related to #1916, because maybe it can not only happen when two requests are running concurrently, but also when certain requests happen in a certain order (because one request changes the intsref in a certain way and then another request that executed afterwards is affected by this change)

**Comment by easbar** [comment]
Hm, maybe not, because `TurnCostStorage#get` always sets

```java
tcFlags.ints[0] = 0;
```

initially and a problem can only arise if this method is executed concurrently

**Comment by karussell** [comment]
Indeed.

btw: the `TurnCostStorage#get` method changes the `tcFlag.ints[0]` in TurnCostStorage.nextCostFlags. The additional 0 init is only to avoid issues for a potential the QueryGraph call.

**Comment by easbar** [comment]
What exactly is the issue with query graph?

**Comment by karussell** [comment]
It seems to be no longer necessary. Before there was a special implementation for the turn cost calculation (QueryGraphTurnExt.java) for the QueryGraph and this implementation had a code path where the intsRef is never touched returning potentially wrong none 0 tcFlags, see https://github.com/graphhopper/graphhopper/pull/1775/files#diff-6c90581206dfca533bb5863d74b17516. So e.g. the first read returns a turn cost X, then readFlags is called for the query graph but at this point there are no turn costs and without the 0 init it will return turn cost X and not the correct 0. But again, it seems this is no longer necessary.

btw: can we remove QueryGraph#getOriginalEdgeFromVirtNode? Looks like it is never used.

**Comment by easbar** [comment]
Ok yes whatever `QueryGraphTurnExt` used to do is now done with `QueryGraphWeighting`. Apparently the last usage of `QueryGraph#getOriginalEdgeFromVirtNode` was in #1749 and yes looks like this can be removed

**Comment by easbar** [comment]
>  then readFlags is called for the query graph 

Maybe we can make readFlags private or at least package private?

**Comment by karussell** [comment]
The probability is already reduced (~20x) due to removing the zero-setting.

Have now fixed the problem in the second commit and create the IntsRef on every call, interestingly this is better than synchronized and not slower than before. `synchronized` is also only slower for many parallel requests (e.g. 20% for 50qps; it has same perf for 10qps).
