### ISSUE TITLE
Failed to parse configuration at: graphhopper.datareader; Cannot deserialize instance of `java.lang.String` out of START_OBJECT token  at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.graphhopper.http.GraphHopperServerConfiguration["graphhopper"]->java.util.LinkedHashMap["datareader"])

### ISSUE THREAD

**Issue by JeongJun-Lee** [graphhopper/graphhopper#1939]
**Describe the bug**
A clear and concise description of what the bug is. Before creating an issue please create a new topic in [our forum](https://discuss.graphhopper.com/c/graphhopper).

If you have an Android application that uses GraphHopper, use [this forum category](https://discuss.graphhopper.com/c/graphhopper/graphhopper-ios-and-android) and include logs and the version of
your Android system.

**To Reproduce**

Steps to reproduce the behavior. 
Refer to https://github.com/graphhopper/graphhopper/blob/master/docs/web/quickstart.md

1. download jar of 0.13 version
2. download a berlin-latest-osm.pbf
3. download config-example.yml 
4. java -Ddw.graphhopper.datareader.file=berlin-latest.osm.pbf -jar *.jar server config-example.yml

Instead of a manual reproduction it would be even better to have a unit or integration test reproducing the issue.

**Expected behavior**

**System Information**
Operating system: Mac OS 10.13.6
JVM: 1.8.0_121_b13
GraphHopper: 0.13

**Screenshots & Logs**

If applicable, add screenshots and log output.

![image](https://user-images.githubusercontent.com/11474775/75565485-d636b280-5a6f-11ea-8522-6b7b368f0a7d.png)

In case of a routing problem include a link to [GraphHopper Maps](https://graphhopper.com/maps/). Also tell us your expected routing result via additional markers and screenshots.

**Comment by karussell** [comment]
> java -Ddw.graphhopper.datareader.file=berlin-latest.osm.pbf -jar *.jar server config-example.yml

Please use the documentation of 0.13 not master. See also https://github.com/graphhopper/graphhopper/issues/1921#issuecomment-592583206

Please use our forum for questions.
