### ISSUE TITLE
Wrong routes for car: routing doesn't relates to real city roads, routing through buildings 

### ISSUE THREAD

**Issue by Bendor** [graphhopper/graphhopper#1948]
Hi! First of all thanks for your great work!
I faced a big problem: route for car is wrong on my localhost. I have use last master source and default config, there is my request:
http://localhost:8989/route?point=53.890572%2C27.551188&point=53.91953%2C27.582458&type=json&locale=en-us&vehicle=car&weighting=fastes
but result is wrong for car type:
![image](https://user-images.githubusercontent.com/4973472/76171988-392bf600-61a2-11ea-9693-aeec9096e044.png)
![image](https://user-images.githubusercontent.com/4973472/76171997-4d6ff300-61a2-11ea-9187-a07a90786619.png)
![image](https://user-images.githubusercontent.com/4973472/76172016-67113a80-61a2-11ea-8cd5-80665e73b5a1.png)
Looks like the route doesn't relates to real city roads.
The same request for graphhopper.com API return correct route:
![image](https://user-images.githubusercontent.com/4973472/76172121-91172c80-61a3-11ea-8add-bddf0d55d312.png)

There is my log for request: 
 GET /route?point=53.890572%2C27.551188&point=53.91953%2C27.582458&type=json&locale=en-us&vehicle=car&weighting=fastest&turn_costs=true] INFO  c.g.resources.RouteResource - point=53.890572%2C27.551188&point=53.91953%2C27.582458&type=json&locale=en-us&vehicle=car&weighting=fastest&turn_costs=true 127.0.0.1 en_US Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36 [53.890572,27.551188, 53.91953,27.582458], took:0.108413294, , fastest, car, alternatives: 1, distance0: 5288.8512784180475, weight0: 386.10698618930724, time0: 6min, points0: 45, debugInfo: tmode:EDGE_BASED; idLookup:0.0499004s; , algoInit:2.615E-4s, dijkstrabi|ch|edge_based|no_sod-routing:0.0417764s, path extraction: 6423 micros;visited nodes sum: 242;, algoInit:2.615E-4s, dijkstrabi|ch|edge_based|no_sod-routing:0.0417764s, path extraction: 6423 micros;visited nodes sum: 242, simplify (147->147)

I try to configure default config but all changes doesn't solve the problem.
What wrong with it? As it work properly on https://graphhopper.com/maps/  I believe that it's problem with configuration. Could you please help me what should I change to solve this problem/ Thanks

**Comment by Azbesciak** [comment]
Did you try to use OSM tiles? Different providers might have different geocordinates and streets data

**Comment by karussell** [comment]
Please create a new topic in the forum: https://discuss.graphhopper.com/
Thanks!

**Comment by Bendor** [comment]
Sorry, no problem? it's my fail! see:
https://discuss.graphhopper.com/t/route-for-car-is-absolutely-wrong/5297/5
