### ISSUE TITLE
isochrone returns 2d and 3d coordinates mixed

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1957]
config enables elevation (CGIAR) then this request:

> /isochrone?point=24.982444,55.133875&time_limit=900&buckets=3&vehicle=bike2

returns response with 2D coordinates in last bucket.

Also the parameter elevation=false/true does not seem to work for /isochrone

**Comment by michaz** [comment]
Oh, that's not elevation. `/isochrone` does not use elevation.

I wasn't even aware a z coordinate is in there. I think it comes out of the triangulation, and it's the z-value we are getting the isoline for. (Time or distance). So it would be the same in every bucket if it were a perfect isoline.

We should probably throw it out.

**Comment by michaz** [comment]
Fixed by 6a7d45a

**Comment by karussell** [comment]
Cool, thanks!
