### ISSUE TITLE
Randomized tests fail for MotorCycleEncoder when turn costs are enabled 

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#1972]
See: dfa19a686c6efb44d5373a00059eff151a563704

This could be a duplicate of #1631 (and/or #1916?), but here its clear that the (or a) problem exists for all algorithms.

**Comment by easbar** [comment]
Apparently this does not occur if we exclude loop edges (in `GHUtility.buildRandomGraph` set `allowLoops` to false for this test).

**Comment by karussell** [comment]
(Maybe related to #1234)

**Comment by easbar** [comment]
> One particular case that fails (and only fails for edge_based CH) is seed 36679795286008 in randomGraph_withQueryGraph when turning off the random turn costs and using motorcycle encoder. 8a24e31)

Unfortunately I cannot reproduce this anymore. Maybe I pasted the wrong hash?
