### ISSUE TITLE
problem for GTFS

### ISSUE THREAD

**Issue by Datn1298** [graphhopper/graphhopper#1973]
Hello Graphhopper Team

I follow all below step: 
wget -O gtfs-vbb.zip http://transitfeeds.com/p/verkehrsverbund-berlin brandenburg/213/latest/download
wget http://download.geofabrik.de/europe/germany/brandenburg-latest.osm.pbf
./graphhopper.sh build

java -Xmx8g -Xms8g \
  -Ddw.graphhopper.datareader.file=brandenburg-latest.osm.pbf \
  -Ddw.graphhopper.gtfs.file=gtfs-vbb.zip \
  -Ddw.graphhopper.graph.flag_encoders=pt \
  -Ddw.graphhopper.graph.location=./graph-cache \
  -jar web/target/graphhopper-web-*.jar server config.yml

Then i get problem:
java.lang.IllegalArgumentException: entry in encoder list not supported pt
	at com.graphhopper.routing.util.DefaultFlagEncoderFactory.createFlagEncoder(DefaultFlagEncoderFactory.java:60)
	at com.graphhopper.routing.util.EncodingManager.parseEncoderString(EncodingManager.java:393)
	at com.graphhopper.routing.util.EncodingManager$Builder.addAll(EncodingManager.java:190)
	at com.graphhopper.GraphHopper.createEncodingManager(GraphHopper.java:572)
	at com.graphhopper.GraphHopper.init(GraphHopper.java:517)
	at com.graphhopper.http.GraphHopperManaged.<init>(GraphHopperManaged.java:90)
	at com.graphhopper.http.GraphHopperBundle.run(GraphHopperBundle.java:201)
	at com.graphhopper.http.GraphHopperBundle.run(GraphHopperBundle.java:55)
	at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:200)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at com.graphhopper.http.GraphHopperApplication.main(GraphHopperApplication.java:36)

Pls help me

**Comment by karussell** [comment]
Ah, this is ugly. Thanks for reporting. There seems to be multiple issues:

 * remove the option ` -Ddw.graphhopper.graph.flag_encoders=pt `
 * like #1921: you can specify the `gtfs.file` in the config.yml as a workaround

**Comment by karussell** [comment]
The best idea is always to use the latest stable release 0.13 plus its documentation: https://github.com/graphhopper/graphhopper/tree/0.13/reader-gtfs (make sure you switch to the 0.13 git branch and run `./graphhopper.sh clean` before)

**Comment by easbar** [comment]
And better remove the `graph-cache` folder as well

**Comment by michaz** [comment]
Fixed by 07009b0d

I think the answer was in the code comment already: We shouldn't require a profile. At least not when using transit. 

Transit just isn't included in the profiles concept so far. In the current state, `pt` isn't a profile, and it doesn't use profiles. It can route (internally) via `foot` because `foot` is a `FlagEncoder`, not because it is a profile.

As long as FlagEncoders still exist, we shouldn't pretend we need a profile when we really don't.

I see that `pt` _will_ have something to do with profiles in the future, but at the moment it is less wrong if we don't require a profile to be there.

**Comment by michaz** [comment]
Oh, and the README was wrong. Pt isn't a flag encoder. That was loooong ago..

**Comment by karussell** [comment]
The [quickstart](https://github.com/graphhopper/graphhopper/tree/1.0/reader-gtfs#quick-start) still needs a change (see [discussion](https://discuss.graphhopper.com/t/reader-gfts-problem-please-help-me/5638)):

 * remove profiles section
 * remove profiles_ch section
 * include `gtfs.file: ""` (we can do that change permanently)

**Comment by karussell** [comment]
> remove profiles section
> remove profiles_ch section

Or is there a way we can overwrite it via a command line argument? Like `-Ddw.graphhopper.profiles=[]`?

**Comment by michaz** [comment]
Let's just provide an example config for transit.

**Comment by RJHCarto** [comment]
Hi, wondering what the progress is with the GTFS reader support in V1.0.0.
Is there any further documentation that addresses the bugs above? Is the plan to integrate this as a routing profile, so that it can be used much like any other mode of transport? Any info would be great.

**Comment by michaz** [comment]
Updated the README
