### ISSUE TITLE
Isochrones with turn costs

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#1978]
The /isochrone and /spt endpoints currently do not support turn costs. We need to run the algorithm edge-based to support this.

To make things a bit less complicated these endpoints currently *can* be used also for profiles with `turn_costs: false` and the turn costs are simply disabled silently, c.f. this discussion: #1967

**Comment by michaz** [comment]
I already have this on a branch. Coming up.

**Comment by michaz** [comment]
- [ ] /isochrone

- [ ] /spt

**Comment by michaz** [comment]
Finished, up to the fact that for /spt, edge based traversal really is something different than just respecting turn restrictions. You get a different kind of tree, where you get every node several times.
How to make it clear that this happens iff your profile has turn restrictions?
Maybe I can also want this if it has _no_ turn restrictions?

**Comment by easbar** [comment]
Cool thanks!

> You get a different kind of tree, where you get every node several times.

Hm this seems to depend on the requested columns? For example if all I want are the coordinates, times and distances (the default) we should probably use the minima for every node? But if also the (previous) edge_ids etc. are requested we could just return all the entries of the shortest path tree? Or maybe that is what we do already?

> How to make it clear that this happens iff your profile has turn restrictions?
Maybe I can also want this if it has no turn restrictions?

This is indeed ugly and here (and maybe only here?) it would make sense to differentiate between `edge_based` and `turn_costs` (#1702)? In one case I might be interested in the edge-based tree and in another I might be interested in the node-based tree. But in which case would I be interested in the edge-based tree without turn costs? The calculation is probably not faster when we skip the turn costs, but the routing becomes less accurate (if we neglect OSM turn restrictions this way)?

A few more minor things:

* Don't you think there should be an error when `ch/lm.disable=false` since the speed modes are not supported for /isochrone and /spt?

* We now get an internal server error for something like this: `/spt?point=xyz`. Might be the same as in #1995. Taking into account that we also get 404 when parameters have the wrong type I wonder if we should put all query parameters as strings and do the parsing manually (maybe not so elegant but at least then we can control the error codes). Or maybe this is just a minor bug that can be fixed still using the framework mechanisms.

* Should it be allowed to use dashes in profile names, like `car-with-turncosts`? Right now its only allowed for some legacy reasons where something like `-1` (minus one) had to be included, but this will no longer be the case after fixing #1999. See here: https://github.com/graphhopper/graphhopper/pull/1922#discussion_r383033522

**Comment by michaz** [comment]
> Should it be allowed to use dashes in profile names, like car-with-turncosts?

Why not? I don't know the legacy of this, but in my mind, it's just a string, a resource name. I don't want to interpret it in any way.

> 404 [..] Or maybe this is just a minor bug that can be fixed still using the framework mechanisms.

Will check, but if it isn't -- I want to to as little as possible of this manually, and I want to _release_ control about this and give it to conventions / frameworks. For me, that's the point.

> For example if all I want are the coordinates, times and distances (the default) we should probably use the minima for every node? But if also the (previous) edge_ids etc. are requested we could just return all the entries of the shortest path tree? Or maybe that is what we do already?

Noooo, a tree is a tree, it can't suddenly change its structure depending on the columns I request.

**Comment by easbar** [comment]
> Why not? I don't know the legacy of this, but in my mind, it's just a string, a resource name. I don't want to interpret it in any way.

The legacy was that we sometimes had `utc-1` in the profile names to indicate infinite u-turn costs. Otherwise you are right a dash is not a problem as a url, yaml or file name, but being a bit more restrictive also sometimes can make things easier. Here I do not see a real reason to *allow* dash, because one can also just use underscore.

> Noooo, a tree is a tree, it can't suddenly change its structure depending on the columns I request. (That it does so depending on the profile is questionable, but depending on the columns -- no.) That would mean that there are meaning-of-the-tree-changing columns and other columns.

Ok I agree changing the columns should better not lead to another result, I was just speculating about what a user expects and came to the conclusion that this might depend on the requested columns. For example if we always return *the* (edge-based) tree (and the default columns are just the coordinates, times and distances) there are duplicate rows (same coordinates, different times) which I guess is not expected. If on the other hand we remove these 'duplicates' we will be 'missing' some rows when we include the parent edges for example. So maybe for an edge-based tree it just makes no sense to ask for the coordinates of the *nodes*? If we would list the (road network) edges it would be more clear: Every node of the shortest path tree corresponds to exactly one (directed) edge and every (directed) edge appears at most once in the tree. But sure, what if one asks for 'the' tree including turn costs (not even knowing about edge-based etc.) then things are less clear.

**Comment by easbar** [comment]
> I was just speculating about what a user expects

There seem to be multiple different questions one might ask related to the shortest path tree. Not sure which ones our endpoint is supposed to answer:

1) Give me 'the' shortest path tree (all the nodes with their distances and times from the center point) 

2) Like 1), but pay respect to turn restrictions

3) Give me the edge-based shortest path tree (for every road of the graph I want to know the time/distance it takes from the center point, for both directions of the road).

4) Like 3) but this time I want to ignore turn restrictions
