### ISSUE TITLE
NaN value for motorcycle-curvature not allowed

### ISSUE THREAD

**Issue by airzope** [graphhopper/graphhopper#1981]
**Describe the bug**
Can you help me see what is going on?I want to use all possible encoders.
On a 256G memory workstation,I follow the quick start instructions:
**https://github.com/graphhopper/graphhopper/blob/0.13/docs/web/quickstart.md**

I modified the configuration file as follows:
**graph.flag_encoders: car,foot,bike,bike2,mtb,racingbike,motorcycle
graph.bytes_for_flags: 64**
I tested everything OK on a map of Berlin.

Then I downloaded the Planet map and checked md5.
Executed the following command:

**java -Dgraphhopper.datareader.file=planet-200323.osm.pbf -jar -XX:MaxHeapSize=245000M *.jar server planet-config.yml**

But some errors happened :
**NaN value for motorcycle-curvature not allowed!**

After repeating it a few times, I'm a bit frustrated.
Is there any configuration I have missed?

**System Information**
Centos7.7 x64
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
graphhopper-web-0.13.0.jar

**Screenshots & Logs**
2020-04-03 03:01:45.750 [main] ERROR io.dropwizard.cli.ServerCommand - Unable to start server, shutting down 
java.lang.RuntimeException: Couldn't process file planet-200323.osm.pbf, error: NaN value for motorcycle-curvature not allowed!

**Comment by karussell** [comment]
Can you have a look if #1234 causes your issue and the fix

> if(speed==0) return Double.POSITIVE_INFINITIVE.

in the CurvatureWeighting avoids your problems?

**Comment by karussell** [comment]
Since 2 weeks no response I think we can close here as duplicate of #1234.
