### ISSUE TITLE
exception for Accept=xml and default type parameter

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1982]
The following request

```
curl -H "Accept: application/xml" "http://localhost:8989/route?point=42.507145%2C1.537174&point=42.511368%2C1.539116&vehicle=car"
```

causes

```
InvalidDefinitionException: Direct self-reference leading to cycle (through reference chain: com.graphhopper.util.shapes.BBox["bounds"])
```

We should remove the "produce xml" annotation as we rely only on the type parameter.

**Comment by michaz** [comment]
Since 3b53d57, no exception anymore, but JSON response. But not sure if this is the correct behavior, I think we should maybe return GPX in this case, see Slack.

**Comment by karussell** [comment]
Thanks! For now this is good for me too. Let's reopen if some other problem arise and then we could introduce a /route_gpx endpoint or something :)
