### ISSUE TITLE
Add profiles.md to explain new profile stuff

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#1987]
Document how to use profiles (also custom profiles), and explain how to migrate to 1.0 with this regard

(mention https://github.com/karussell/snake_case)

**Comment by easbar** [comment]
We should also improve the error messages (list available profiles and maybe rather point to the (to be written) documentation than random github issues).

**Comment by easbar** [comment]
The isochrone docs also seem outdated: https://discuss.graphhopper.com/t/isochrone-developer-guide/5537

**Comment by easbar** [comment]
> We should also improve the error messages (list available profiles and maybe rather point to the (to be written) documentation than random github issues).

What should we report when some profile is not found etc.? Should we list all available profiles? And should we point to the docs in `core/docs`? Or rather to the online docs of graphhopper.com? Or (some) github issue(s)? Either way its a bit weird depending on the user group unfortunately...

**Comment by karussell** [comment]
> The isochrone docs also seem outdated: https://discuss.graphhopper.com/t/isochrone-developer-guide/5537

This is not related to this issue IMO. (probably more to #774?)

> What should we report when some profile is not found etc.? Should we list all available profiles? And should we point to the docs in core/docs?

Yes, I would also list all profiles and then link to the docs.

> And for gh.com api users it would be best to point to the online api docs

No worries as we do the profile limitation differently there.

**Comment by easbar** [comment]
> This is not related to this issue IMO. (probably more to #774?)

Ah ok. But we should at least fix the mention of the `Isochrone` class that is removed in `1.0` (or maybe just renamed to `ShortestPathTree` (?).

> Yes, I would also list all profiles and then link to the docs.
> No worries as we do the profile limitation differently there.

Ok, perfect. :+1:

**Comment by easbar** [comment]
I fixed the isochrone docs here: 268ec1df74c8f28b12424b9fb692d1bd642e1495
