### ISSUE TITLE
EncodedDoubleValue allowZero check does not work for small numbers

### ISSUE THREAD

**Issue by jtheuer** [graphhopper/graphhopper#199]
The zeroCheck is implemented using Math.round(value) and the check in the superclass, I think for double values it should either be rewritten or be unsupported.

Test case to reproduce:

```
public class EncodedDoubleValueTest
{
    @Test
    public void testSetSmallDoubleValue()
    {
        EncodedDoubleValue instance = new EncodedDoubleValue("test", 6, 32, 0.001, 1, 1, false);
        assertEquals(0.1, instance.getDoubleValue(instance.setDoubleValue(0, 0.1)), 1e-4);
    }

   ...
```

**Comment by karussell** [comment]
The same applies also to the negativity check. If we set a negative value that is rounded to 0 it will be accepted. I'll try to have this in mind for the new EncodedValue stuff in #1112 and potentially see if we have a fix that is backportable.
