### ISSUE TITLE
/isochrone and /spt return 404 when point is missing

### ISSUE THREAD

**Issue by mc51** [graphhopper/graphhopper#1991]
**Describe the bug**
The http://localhost:8989/isochrone endpoint is missing in my local server. I get a 404 response. The /route endpoint works flawlessly.

**To Reproduce**
I followed this guide:
https://github.com/graphhopper/graphhopper/blob/0.13/docs/web/quickstart.md
I use the exact same config as here: https://github.com/graphhopper/graphhopper/blob/0.13/config-example.yml

**Expected behavior**
I'd expect the endpoint to be available for requests and not return 404. 

**System Information**

I used this jar version:
https://graphhopper.com/public/releases/graphhopper-web-0.13.0.jar
I'm on Windows 10 and Java is this:

```
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
```
**Screenshots & Logs**

There are no logs from the server.

**Comment by karussell** [comment]
Indeed we return a different 400 message for missing parameters. This could be more consistent.

But you only need to specify at least the point parameter: http://localhost:8989/isochrone?point=43.733647%2C7.415686 and see that it will work.

**Comment by easbar** [comment]
I just had the same problem with `/spt`. Returning 404 seems very wrong as it makes it look the whole endpoint is missing and we are not shown the intended error message (no point specified). There is also another problem for /spt: Since it returns `text/csv` the serialization of exceptions to json does not work and we are getting 500 errors instead of the error messages in json format.

**Comment by easbar** [comment]
@karussell don't you think this should be fixed? If not feel free to close again.

**Comment by easbar** [comment]
With 7df3192d137d025e3cd32a5c9eb99379207ee6b6 we now get 400 when the point is missing. Also I made sure that for /spt (which normally returns csv) we get a json error message. Not sure if we could achieve the same with framework features, so anybody who can do better please go ahead (@michaz?).

@mc51 for 0.13 you still get 404 if you do not specify the point, but obviously you need to specify a point anyway

**Comment by karussell** [comment]
Thanks!
