### ISSUE TITLE
Unknown vehicle 'car' in profile: name=car|vehicle=car|weighting=fastest|turnCosts=false|hints={}. Make sure all vehicles used in 'profiles' exist in 'graph.flag_encoders'

### ISSUE THREAD

**Issue by mmorelo** [graphhopper/graphhopper#1992]
**Describe the bug**
Following exactly the instructions in the Readme, leads to 

2020-04-16 14:18:06.781 [main] ERROR io.dropwizard.cli.ServerCommand - Unable to start server, shutting down
java.lang.IllegalArgumentException: Unknown vehicle 'car' in profile: name=car|vehicle=car|weighting=fastest|turnCosts=false|hints={}. Make sure all vehicles used in 'profiles' exist in 'graph.flag_encoders'

**To Reproduce**

Steps to reproduce the behavior are the ones in the project landing page.

**Comment by karussell** [comment]
What readme did you follow? Please use the lastest stable version not master: https://github.com/graphhopper/graphhopper#get-started

(For master we already have #1987)

**Comment by mmorelo** [comment]
ok thanks

**Comment by mmorelo** [comment]
If I check out and follow instructions in v0.13 I get this:

java -Xmx8g -Xms8g \
>   -Dgraphhopper.datareader.file=brandenburg-latest.osm.pbf \
>   -Dgraphhopper.gtfs.file=gtfs-vbb.zip \
>   -Dgraphhopper.graph.flag_encoders=pt \
>   -Dgraphhopper.prepare.ch.weightings=no \
>   -Dgraphhopper.graph.location=./graph-cache \
>   -jar web/target/graphhopper-web-*.jar server config.yml
invalid choice: 'web/target/graphhopper-web-1.0-SNAPSHOT.jar' (choose from 'server', 'check', 'import')
usage: java -jar graphhopper-web-0.13-SNAPSHOT.jar
       [-h] [-v] {server,check,import} ...

positional arguments:
  {server,check,import}  available commands
