### ISSUE TITLE
remove gpx export support for POST request?

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#2006]
We should support GPX only for historic reasons and remove it for the `POST /route` endpoint (and also for `POST /custom`)

**Comment by boldtrn** [comment]
> We should support GPX only for historic reasons

Why is that? Is there no interest in GPX anymore?

**Comment by karussell** [comment]
It should be done on the client side (like any other format like KML, ...). It makes maintenance on our side rather expensive. And the idea could be (if others agree) that it won't be removed for GET (at least not soon). And because the `POST /route` endpoint was introduced only after 0.13 nobody should complain about its removal.

**Comment by boldtrn** [comment]
Ah ok I see. Thanks for the explanation.

Maybe it would make sense to transfer it into a different module like graphhopper-gpx and give it a separate endpoint, like `/gpx`. Then the maintenance could be easier, GET and POST would be equal.

**Comment by karussell** [comment]
The goal would be to "fade out" this feature somehow. A separate endpoint would be one way, but no new features would be added (like POST-support).

**Comment by karussell** [comment]
Thanks @michaz.
