### ISSUE TITLE
[REGRESSION] Public transit routing not able to transfer from one trip to another. 

### ISSUE THREAD

**Issue by MathStPierre** [graphhopper/graphhopper#2007]
This commit by @michaz is causing a regression : https://github.com/graphhopper/graphhopper/commit/31ae1e1534849099f24e45d53c96340a7c6a5197

Before this commit three possible routes were returned, including one with one transfer. 

![image](https://user-images.githubusercontent.com/49801955/79784565-71316780-8310-11ea-967a-878f6994a1d9.png)

Now with 1.0-pre33.4 only 2 routes are returned, the one with 0 transfer and the walk only route. 

How to reproduce : 

The following tests in the branch https://github.com/MathStPierre/graphhopper/tree/Output-generated-GTFS-graph-to-graphml can be used to reproduce the problem. 

https://github.com/graphhopper/graphhopper/blob/59d4ff0b2ad8e609387d42bed211ea93366dad2a/web/src/test/java/com/graphhopper/http/resources/GtfsSimpleRailRoadStopsSameLocationWithTransferFile.java

https://github.com/graphhopper/graphhopper/blob/59d4ff0b2ad8e609387d42bed211ea93366dad2a/web/src/test/java/com/graphhopper/http/resources/GtfsSimpleRailRoadStopsSameLocationTest.java

**Comment by michaz** [comment]
Yep. Turned out that the patch we applied was correct, *but* also caused *unintended* transfers to be inserted, and the graph size would explode in some situations.

Remember when we talked about transfers and I said that transfers from station to station that are *at the same coordinate* are possible only by accident? That had something to do with it, alas.

I "fixed" that and now your use case is broken, sorry. :-(

I think I can easily put in a "feature flag" for you that inserts those transfers, I think it's really just a small loop, let me check.. (thanks for the tests..)

**Comment by michaz** [comment]
I think you may find increased performance after this.

**Comment by MathStPierre** [comment]
`Remember when we talked about transfers and I said that transfers from station to station that are at the same coordinate are possible only by accident?`

Ah yes, I remember that now. It should work if the transfers.txt file is specifying a transition from one trip to another at a given stop though. 

With the transfers.txt file that is used in the test case https://github.com/graphhopper/graphhopper/blob/59d4ff0b2ad8e609387d42bed211ea93366dad2a/web/src/test/java/com/graphhopper/http/resources/GtfsSimpleRailRoadStopsSameLocationWithTransferFile.java it doesn't work. 

But after double checking I think this is expected because even though SB2 and SR1 are at the same location there is no row in the transfers file that says SB2,SR1.

```
from_stop_id,to_stop_id,transfer_type,min_transfer_time
SB1,SB1,2,10
SB2,SB2,2,10
SR1,SR1,2,10
SR2,SR2,2,10
```

If I modify the dataset to merge SB2 and SR1 together the transfer does occurs has expected :)

```
from_stop_id,to_stop_id,transfer_type,min_transfer_time
SB1,SB1,2,10
SBR1,SBR1,2,10
SR2,SR2,2,10
```

**Comment by MathStPierre** [comment]
> I think I can easily put in a "feature flag" for you that inserts those transfers and gets the exact same graph and behavior back (without the bug), I think it's really just a small loop, let me check.. (thanks for the tests..)

Thanks for the suggestion. Our official dataset seems to specify a lot of transfers, so I think if the from_stop_id/to_stop_id transfers specified in the transfers.txt file are still working (and it appears so) then no need for the feature flag.

**Comment by MathStPierre** [comment]
Bottom line is that by fixing the unintended transfers there are now even more cases when a user could have walked to a nearby station after exiting a previous station that will not be handled by GTFS routing algorithm (_pt->walk->pt_ problem).

So in term of routing precision it seems to be a bit of a regression, not sure to what extent though

**Comment by MathStPierre** [comment]
> I think you may find increased performance after this. (Even when the transfers are back.)

Didn't run our benchmarks but objectively it still seems quite long.

**Comment by MathStPierre** [comment]
If you decide to merge this [test](https://github.com/graphhopper/graphhopper/blob/59d4ff0b2ad8e609387d42bed211ea93366dad2a/web/src/test/java/com/graphhopper/http/resources/GtfsSimpleRailRoadStopsSameLocationWithTransferFile.java) below is the modified GTFS dataset : 

[simple-bus-rail-with-transfers-shared-stop-txt.zip](https://github.com/graphhopper/graphhopper/files/4506441/simple-bus-rail-with-transfers-shared-stop-txt.zip)

**Comment by michaz** [comment]
> then no need for the feature flag

Thanks so much for letting me know. In that case, I'll postpone this to a time for a more general approach to transfer "auto-detection".

> Our official dataset seems to specify a lot of transfers

.. exactly. All the datasets I'm working with specify *all* the transfers, so I'm kind of biased to be satisfied with just allowing those. ,-)

> Didn't run our benchmarks but objectively it still seems quite long.

I know. That's next up. Let me get back to you when I can start working on this (as discussed).

**Comment by MathStPierre** [comment]
> I know... :-/ That's next up. Let me get back to you when I can start working on this (as discussed).

@michaz we already have a solution (well more like some heuristic) that gives us a very good speedup. It's not perfect but in the very short term it suits us. It would be nice if we could have a call together to discuss our public transit routing speed optimization with you so that eventually it is part of an official GraphHopper release, well if the optimization makes sense to you ;)

**Comment by MathStPierre** [comment]
@michaz finally after discussing with my colleagues it seems that it would be best for us to have the a flag to reactivate the unintended adding of transfer edges between stops connecting to same OSM node. The reason is that we sometime needs to merge to GTFS dataset together coming from different agencies. Since it is not possible to have pt->walk->pt sequence with the removal of the unintended transfer edge transfers between different merged agencies is not possible. 

We could have modifies our GTFS merging tool but it is easier to just add a flag in the short term.  

I did create a PR that includes the flag that seems to fix the regression : https://github.com/graphhopper/graphhopper/pull/2012
