### ISSUE TITLE
exception in landmark preparation

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#2020]
The problem is since we allowed multiple rules. See https://github.com/graphhopper/graphhopper/pull/1903#discussion_r414630805

The stacktrace is:

```
Caused by: java.lang.IndexOutOfBoundsException: Index: 0
        at java.util.Collections$EmptyList.get(Collections.java:4456)
        at java.util.Collections$UnmodifiableList.get(Collections.java:1311)
        at com.graphhopper.routing.lm.LandmarkStorage.findBorderEdgeIds(LandmarkStorage.java:467)
        at com.graphhopper.routing.lm.LandmarkStorage.createLandmarks(LandmarkStorage.java:263)
```

So, we probably need some test code to cover this scenario too. @otbutz do you have an idea what could go wrong and why we expected this not to happen for landmarks? Should we just do:

```java
SpatialRuleSet set = ruleLookup.lookupRules(nodeAccess.getLatitude(adjNode), nodeAccess.getLongitude(adjNode));
SpatialRule ruleAdj = set.getRules().isEmpty() ? null : set.getRules().get(0);

int baseNode = allEdgesIterator.getBaseNode();
set = ruleLookup.lookupRules(nodeAccess.getLatitude(baseNode), nodeAccess.getLongitude(baseNode));
SpatialRule ruleBase = set.getRules().isEmpty() ? null : set.getRules().get(0);
...
```
?

**Comment by otbutz** [comment]
That should fix it. I was under the impression that the landmark areas file would cover the whole globe and therefor yield an applicable ID for each point.

![mapgeojson](https://user-images.githubusercontent.com/22315436/80385640-98ef7500-88a6-11ea-80a8-01c62b23202e.png)

**Comment by karussell** [comment]
Ok, thanks for confirmation. Yes, we could provide one globally, but should still prepare for the general (user provided) case and approach this more defensive.

**Comment by otbutz** [comment]
Would it be worth to take a look at the current area definitions in order to improve landmark based routing?

**Comment by karussell** [comment]
What do you mean? The area splitting makes it impossible to route between the defined areas but improves speed within the areas significantly, so further reducing the area might not be of much use.
