### ISSUE TITLE
keep left and keep right when vehicle=foot?

### ISSUE THREAD

**Issue by siadat** [graphhopper/graphhopper#2024]
**Describe the bug**
I get instructions to keep left and keep right when I set `vehicle=foot`. I was wondering if it is the expected behavior or if I have misconfigured anything.

If keep left and keep right are valid instructions when `vehicle=foot`, then [this translation](https://github.com/graphhopper/graphhopper/blob/22e566256f926b180be0d00c4874149c9a1016e6/core/src/main/resources/com/graphhopper/util/fa.txt#L11) should be rephrased to represent all possible vehicles. At the moment the literal translation is "drive to the left" which assumes that the user is driving and will not match the requested `vehicle=foot`.

**To Reproduce**

Set `vehicle=foot`, make a request, and search for "Keep right" or "Keep left" (when `local=en`) or "برانید" (with `locale=fa`):

    curl 'http://localhost/route?instructions=true&locale=fa&point=35.744833%2C51.438810&point=35.710562%2C51.434661&type=json&vehicle=foot'

**Comment by siadat** [comment]
Hi, I was wondering if you could have a look at this question. Thanks!

**Comment by easbar** [comment]
You mean `keep_left` should rather be translated to something like `keep left` or `stay on the left` (instead of `drive to the left`)? Currently it seems like the wording does not depend on the vehicle. See this document to find out how you can fix the translation: https://github.com/graphhopper/graphhopper/blob/master/docs/core/translations.md

**Comment by siadat** [comment]
> You mean keep_left should rather be translated to something like keep left or stay on the left (instead of drive to the left)?

Yes.

> Currently it seems like the wording does not depend on the vehicle.

So, that means that keep_left is a valid vehicle=foot instruction and it should be translated in a vehicle-agnostic way.

This answers my question and I can close this issue because I can dynamically change the translations of keep_left and keep_right to match the vehicle. The remainder of this comment is suggestions for GH.

---

> See this document to find out how you can fix the translation

My suggestion is that GH should not generate keep_left and keep_right when vehicle=foot unless it does add value to pedestrians, in which case I could tentatively suggest the following translations that is generic enough to apply to any vehicle at the cost of being a bit vague for drivers:

keep_left: `از سمت چپ حرکت کنید`
keep_right: `از سمت راست حرکت کنید`
translation: "move from the left/right side"

For drivers, I would say:

keep_left: `در منتهی‌الیه چپ برانید`
keep_right: `در منتهی‌الیه راست برانید`
translation: "drive on the left/right extreme end"
