### ISSUE TITLE
docs/core/routing.md documentation is outdated

### ISSUE THREAD

**Issue by NoamDev** [graphhopper/graphhopper#2030]
GHRequest#setWeighting does not exist in the latest master.

Btw, I myself do not know what's its replacement.. would appreciate any help.

**Comment by NoamDev** [comment]
ok I noticed now the following line in the changelog:
> removed vehicle,weighting and edge_based from GraphHopper class, replaced with new profile parameter, #1958

However, it should still be updated in the docmentation.

**Comment by easbar** [comment]
This has already been fixed here, maybe you were looking at `1.0-pre41` still?
