### ISSUE TITLE
Lack of documentation on curbside and turn costs

### ISSUE THREAD

**Issue by NoamDev** [graphhopper/graphhopper#2033]
When trying to use curbside parameter I get an error claims I have to enable turn costs for the profile.
After doing that, I get another error:
```
The profile 'car' was configured with 'turn_costs=true', but the corresponding vehicle 'car' does not support turn costs.
You need to add `|turn_costs=true` to the vehicle in `graph.flag_encoders`
```

The isn't very helpful when using the open source engine with java.

1. What am I supposed to do?

2. This requires documentation.

**Comment by NoamDev** [comment]
The documentation and error message are targeted only those who use a config file....

**Comment by karussell** [comment]
Isn't this helpful :) ?

> You need to add `|turn_costs=true` to the vehicle in `graph.flag_encoders`

-> 

`graph.flag_encoders=car|turn_costs=true`

**Comment by NoamDev** [comment]
> `graph.flag_encoders=car|turn_costs=true`

Where am I supposed to write this line?
Am I supposed to write it in some config.yml file I don't have? 😐

**Comment by NoamDev** [comment]
Currently I define flag encoders with the following line:
`hopper.setEncodingManager(EncodingManager.create("car,foot"));`

**Comment by karussell** [comment]
In Java you should be able to do the same:
```java
 hopper.setEncodingManager(EncodingManager.create("car|turn_costs=true,foot"));
```

(it wouldn't make sense to support both environments in the exception, so we decided to print the help for the most common which is using GraphHopper as server that has a config.yml)

**Comment by NoamDev** [comment]
Thank you!
I agree you can't make the excpetion too long.
In that case I for one would search in the docs.
If that explanation you gave me would be included in the docs of turn costs it would be great!
