### ISSUE TITLE
[Feature Proposal] progress updates for graphhopper importing and processing.

### ISSUE THREAD

**Issue by NoamDev** [graphhopper/graphhopper#2034]
When importing a pbf file with ch, the process takes a considerable amount of time.
I believe it would be helpful (especially for android), to have progress updates while importing.

**Comment by karussell** [comment]
There is already progress in the logs for the import. On Android we do not support doing the importing.

**Comment by NoamDev** [comment]
Well, I'm not really using android 😅
Could you refer me to the issue/pr?
Is there such?

**Comment by karussell** [comment]
> Well, I'm not really using android sweat_smile

As you said

> I believe it would be helpful (especially for android)

I had this impression. 

What is your use case? Like a progressbar for a desktop application? (we certainly won't support this use case as we would have to add it in many places like import and landmark preparation for a very low benefit as we cannot estimate exactly on how long it will take)

**Comment by NoamDev** [comment]
I'm importing the pbf file in the build process of a stateless container.
I just need it to log it.
It takes a lot of time, I need to make sure it actually working.
And that it isn't stuck because of some stupid mistake of mine.

When using edge based ch it takes eternity to postProcess :)
I'll admit, it's not much of a use case, but it would be nice to have some logs while importing to make you feel something is actually hapenning.

(I mentioned android as an excuse, searched for a better use case than mine ;)

**Comment by karussell** [comment]
You can increase the number of logs for CH in the code only. See PrepareContractionHierarchies.Params -> forTraversalMode (logMessagesPercentage)

**Comment by easbar** [comment]
You can actually do this via the config file as well: `prepare.ch.log_messages: 20`. Please ask such usage related questions in the [forum](https://discuss.graphhopper.com/) instead.

**Comment by NoamDev** [comment]
You right, I thought about it more as a feature request than as a usage related question.
