### ISSUE TITLE
Add new FlagEncoder

### ISSUE THREAD

**Issue by nhuutai79** [graphhopper/graphhopper#2043]
Hi,
I have a problem with graphhopper core (for developer).
I want to custom a new flagencoder for water_way, i has created new class and extend from AbstractFlagEncoder (WaterFlagEncoder extends AbstractFlagEncoder)
When i rebuild project with walter_way encoder flag, it's failed with message: "graph is empty after in-place removal but was..."
But when i set up parametters';
(//args.putObject("prepare.min_network_size",0);//args.putObject("prepare.min_one_way_network_size", 0);
---> It's build success, but when i put 2 point to find route ---> failed with messages (Cannot find point 0: 10.834154,106.708236, com.graphhopper.util.exceptions.PointNotFoundException: Cannot find point 1: 10.81784,106.726905])
Please help me customize an flag_encoder for my service, how can do that?
thank you

**Comment by karussell** [comment]
For questions please use our public forum: https://discuss.graphhopper.com/
