### ISSUE TITLE
Codespell report for "GraphHopper" (on fossies.org)

### ISSUE THREAD

**Issue by jschleus** [graphhopper/graphhopper#2045]
The FOSS server [fossies.org](https://fossies.org) - now supporting also "[GraphHopper](https://fossies.org/linux/graphhopper)" - offers a feature "[Source code misspelling reports](https://fossies.org/features.html#codespell)". Such reports are normally only generated on request, but as Fossies administrator I have just created for testing purposes such a [codespell](https://github.com/codespell-project/codespell) based analysis for the new GraphHopper release 1.0:

&nbsp;https://fossies.org/linux/misc/graphhopper/codespell.html

That version-independent (not linked) URL should redirect always to the last report (if available).

Although after a first review some obviously wrong matches ("False Positives" = FPs) are already filtered out (ignored) please inform me if you find more of them so that I can force a new improved check if applicable. Just for information there are also two supplemental pages showing some used "codespell" [configuration details](https://fossies.org/linux/misc/graphhopper/codespell_conf.html) and all obvious [False Positives](https://fossies.org/linux/misc/graphhopper/codespell_fps.html).

Ok, most errors are "only" in comments and are therefore not directly visible or relevant for users, but some are found in output strings and one error regards the source code itself ("lenght" instead of "length" in the file web/src/main/resources/assets/js/graphhopper/GHRoute.jsrc/shared/sysctl-util.h at line [79](https://fossies.org/linux/misc/graphhopper-1.0.tar.gz/graphhopper-1.0/web/src/main/resources/assets/js/graphhopper/GHRoute.js?M=79#l_79) and [91](https://fossies.org/linux/misc/graphhopper-1.0.tar.gz/graphhopper-1.0/web/src/main/resources/assets/js/graphhopper/GHRoute.js?M=91#l_91) but I'm not sure if it's a real bug since I'm not a JavaScript expert).

**Comment by karussell** [comment]
Interesting, thanks for this. Have fixed the obvious bugs in the JS code already.
