### ISSUE TITLE
ch is not longer enabled by default. so documentation is needed

### ISSUE THREAD

**Issue by NoamDev** [graphhopper/graphhopper#2046]
according the [changelog](https://github.com/graphhopper/graphhopper/blob/master/core/files/changelog.txt):

>     GraphHopper class no longer enables CH by default, #1914

If so, documentation is needed for how to enable it.

cc @easbar

**Comment by NoamDev** [comment]
Maybe a migration guide is also needed, one that would be based on the changelog between 0.17 to 1.0 .

**Comment by easbar** [comment]
Its 'enabled by default' when using `config-example.yml` and also it is enabled in the example in `routing.md`. Migration can be done using the converter tool: https://github.com/karussell/snake_case. What do you think is missing?

**Comment by NoamDev** [comment]
OH, I'm sorry. I hope I didn't bother too much.
closing.
