### ISSUE TITLE
Seperate WebDependencies and GTFS-Read

### ISSUE THREAD

**Issue by hegerdes** [graphhopper/graphhopper#2052]
**Request**
GH is build modular but if you want to use the GH-GTFS module you also have to use the GH-Web-API module.
If you want to use GH as a library, you have to deal with all these dependencies and WebStuff.

The only direct dependency that GTFS-Module has to GH_Web-API is *PtRouteResource* with *com.graphhopper.http.webHelper*.

Other than that GH-GTFS also has dependencys for Dropwizard and webjars. How much work is it to refactor this in separate modules?

Our project really just needs GH-core, GH-OSM, GH-API, GH-GTFS and the resulting GH Graph with these transit routes.  Eventually other projects also want to use the GTFS capabilities of GH in their own project without Web support or their own WebStack. 

btw. Version1.0 is great

**Comment by michaz** [comment]
> btw. Version1.0 is great

Thanks!

I sympathize with this request. Luckily, thanks to a kind supporter, most of the work was already done, so... 

> How much work is it to refactor this in separate modules?

..probably not much more.

Still, I can't really promise to prioritize it.

**Comment by hegerdes** [comment]
Oh, that's great news. 

Thanks for the response and the work you are putting in the wohle project
