### ISSUE TITLE
Measurement results are not stable against changes in Measurement class

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#2056]
There seems to be some strange behavior of our `Measurement` class as for example adding via-routing measurements here: 9eb65586ebb55aca603e1aba4788d16581a678ec changed the measured time for `routingCH(_edge)_full` even though this measurement runs *before* the new via-routing measurement. Ideally the performance / JVM optimizations (?) should not alter the measurement results like this when adding or skipping parts of the measurements.

A similar problem arose when I tried adding some more edge-traversal tests, see the `potential_jdk_issue` branch...

Another thing I was not able to explain was that in this commit: 6f07e5ce7ed0b72d35e3f38a182cdd1e2ef0788a the `routingCH_alt.mean` time increased by about 15% (I was not able to reproduce this consistently and I was wondering if the reason I could not reproduce it was that the slow down depends on some *other* code running before the test...).

**Comment by easbar** [comment]
Some discussion of this issue here: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8247618

Maybe the first thing we can do would be changing `MiniPerfTest` such that we can pass in the method that shall be tested instead of subclassing and overriding it. I think this would be cleaner anyway.

**Comment by karussell** [comment]
Ah, this is a good idea. Will do that.
