### ISSUE TITLE
Wrong weight for edge-based CH when using AStar

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#2061]
cacd3d7cdeef8eb1480ca592a2d888f8637d53ec

This caused [the build](https://travis-ci.org/github/graphhopper/graphhopper/builds/695750595?utm_source=github_status&utm_medium=notification) to fail in #2060:

**Comment by easbar** [comment]
Unfortunately #2054 introduced a bug and there seem to be cases where AStar finds a worse path than Dijkstra. Therefore I made Dijkstra the default again for now here: f738fdfc4371477dfe39f433b7802f9f6348627a. We should also revisit why not more of our tests failed because of this.

**Comment by michaz** [comment]
Not sure if the same thing, but I just looked at [today's failing test](https://travis-ci.org/github/graphhopper/graphhopper/jobs/699730514) in the debugger, and it doesn't look very wrong to me.

The test complains about a "wrong distance" -- however, we are not optimizing for distance, but for travel time. The travel time difference between the reference route and the testee route is just 1 millisecond. This could be a rounding error.

**Comment by easbar** [comment]
> The test complains about a wrong distance -- however, we are not optimizing for distance, but for travel time. The travel time difference between the expected route and the actual route is just 1 millisecond. This could be a rounding error. Meaning there are multiple best paths. Meaning no problem.

This can **also** happen, but was not the problem here. If there are equal weight paths that have different time/distance/nodes that is only counted as 'soft validation' and the tests will only fail when this happens too many times (normally it does not).
