### ISSUE TITLE
Support interpolated stop times

### ISSUE THREAD

**Issue by michaz** [graphhopper/graphhopper#2095]
Uncommonly used feature in Germany, but quite common elsewhere. See discussion at #2089.

GTFSlib can do this, but I removed support for it when I wanted to thin out library use and had other things on my plate.

**Comment by gcheval** [comment]
The PR: https://github.com/graphhopper/graphhopper/pull/2096

**Comment by michaz** [comment]
Thanks! And does it solve the issue for you?

Now I wonder why it was removed in the first place. Or maybe I'm making this up and it was never there, and only added to GTFSlib later. Mysterious.

**Comment by gcheval** [comment]
It looks like it has! :D
