### ISSUE TITLE
PtRouteResource - Cannot overwrite route method

### ISSUE THREAD

**Issue by MathStPierre** [graphhopper/graphhopper#2097]
While the latest version of **PtRouteResource** is now very similar to **RouteResource** there is still the fact that **RouteResource** is using the interface **GraphHopperAPI** to abstract the routing while **PtRouteResource** is using **[PtRouter](https://github.com/graphhopper/graphhopper/blob/c3740f71ed552e41dc7e9324e44ed7b7c571d20c/reader-gtfs/src/main/java/com/graphhopper/gtfs/PtRouter.java)** which is not an interface but instead a public final class which cannot be extended. 

Thus, the method of **PtRouter** class` public GHResponse route(Request request)` cannot be overridden while the method of **GraphHopperAPI** class `public GHResponse route(final GHRequest request)` can be overridden. 

So it would be nice if the **PtRouter** code could be modified so that we could override the **route** method which would allow derived applications to modify the behaviour of the route method, for example for error handling.

**Comment by michaz** [comment]
It was not really my goal here to create any public interfaces below PtRouteResource -- it executes a concrete algorithm.

Not sure I agree with the premise that _everything_ should be object-oriented-ly extendable, because where does it stop? There always comes a point where you have to start forking/copying code unless literally everything is a public interface, which is not maintainable. :-/

(Though _this_ one may not be a good example for that discussion, maybe let's just put it behind an interface.)

**Comment by MathStPierre** [comment]
@michaz well it seems that more and more efforts have been made during the last few months to make the _PtRouteResource_ code having an architecture similar to the _RouteResource_ code. Which is why I opened this issue as it seems this little remaining discrepancy could have been overlooked (and also if modify it would help us coding the same error handling logic for both the **car** and **pt** profile 😉 ).

**Comment by michaz** [comment]
> and also if modify it would help us coding the same error handling logic for both the car and pt profile 😉

Just for context, may I ask how you're doing that? Is your error-handling code a wrapper that checks something, then delegates to the original class, and then checks something again?

Or are you copying the original class and modifying it?

**Comment by michaz** [comment]
Done.

**Comment by MathStPierre** [comment]
> > and also if modify it would help us coding the same error handling logic for both the car and pt profile 😉
> 
> Just for context, may I ask how you're doing that? Is your error-handling code a wrapper that checks something, then delegates to the original class, and then checks something again?
> 
> Or are you copying the original class and modifying it?

Thanks for the fix 👍 

Basically we have a class that extents the `GraphHopper` class which is overriding the following method : 

```
public GHResponse route(final GHRequest request) {
		return graphHopperRouteExceptionLogger.checkException(super.route(request));
	}
```
So we call the GraphHopper's route method then we potentially create a new modified `GHResponse` in `checkException` and return this modified response.

**Comment by michaz** [comment]
> So we call the GraphHopper's route method then we potentially create a new modified GHResponse in checkException and return this modified response

I see, thanks. Almost like an Aspect.
