### ISSUE TITLE
Error 500 in Routing API

### ISSUE THREAD

**Issue by drjoju** [graphhopper/graphhopper#2102]
**Describe the bug**
when we call the Routing api with POST method and add the optimize parameter, the server returns a 500 error. 
Whether the parameter is true or false is independent.

`
<body>
    <h2>HTTP ERROR 500 java.lang.ClassCastException</h2>
    <table>
        <tr>
            <th>URI:</th>
            <td>/api/1/route</td>
        </tr>
        <tr>
            <th>STATUS:</th>
            <td>500</td>
        </tr>
        <tr>
            <th>MESSAGE:</th>
            <td>java.lang.ClassCastException</td>
        </tr>
        <tr>
            <th>SERVLET:</th>
            <td>com.graphhopper.service.http.InvalidRequestServlet-3ac8cf9b</td>
        </tr>
        <tr>
            <th>CAUSED BY:</th>
            <td>java.lang.ClassCastException</td>
        </tr>
    </table>
    <h3>Caused by:</h3>
    <pre>java.lang.ClassCastException
</pre>
    <hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.28.v20200408</a>
    <hr />
</body>
</html>
`

**To Reproduce**

Using postman and our key we send this json body
`
{
    "points": [
            [
                2.102723,
                        41.3225
                    ],
                    [
                        2.104601,41.325497
                    ]
    ],
    "vehicle": "car",
    "locale": "es_ES",
    "points_encoded" : false,
    "optimize": true
}
`
If we remove the "optimize" param works perfectly. Whether the parameter is true or false is independent.
Changing "optimize": false to "optimize": "false", works but this is not the correct way to insert the value, according the API documentation

**Expected behavior**
Return the path between both points

**System Information**
The online system
 'https://graphhopper.com/api/1/'

**Comment by karussell** [comment]
> System Information The online system
> 'https://graphhopper.com/api/1/'

Please note that this repository is about the open source GraphHopper routing engine not the commercial GraphHopper Directions API. To get your problem solved [post it in our forum or send it to our support](https://www.graphhopper.com/contact-form/).
