### ISSUE TITLE
Unify GHRequest and Request

### ISSUE THREAD

**Issue by hegerdes** [graphhopper/graphhopper#2109]
**Unify GHRequest and Request**
Right now there are several Reuest classes. For normal OSM routes and for PublicTransit Routes. First rename Request to PTRequest to make it clear it is a PublicTransit reutest. 

Also make them inherit from a general abstract Request class or make them implement a Request interface. Also it would be nice to unify the constructor so that both can take `GHPoints` or `List<GHpoints>`. Right now one takes `List<GHLocation>` an the other `List<GHpoints>`.

**Unify Profile and InfoResource.Info.Profile**
Make a separate 'normal' Profile for PT. So that you can do `new Request().setProfile("pt"). Make the request fail if GHStorage is no GTFS_Storage.

**Background Info**

I'm using gh as a lib in my own java project. We need pretty low level access and are not providing any of WebInterface. So we are not communicating through the web-api. 

We do normal foot, car, bike and bus routing that approximates real transit only with OSM-data. But if GTFS data is available we want to use them.  It is not as easy as it could be to switch between PTRouter and normal Router at least if you are only using native GH java calls. 

For example you should overwrite the route method in GraphhopperGTFS to use the PTRouter this would make the usage of GH for developers much easier.

btw. thanks for all the work you put into this project

**Comment by michaz** [comment]
Thanks!

I think I won't be going forward with this at the moment. We have one layer where I try to be "facade-y", that's the web layer -- after that, we "fan out" and call different algorithms that have different sets of parameters, hence different signatures.

I realize there are applications like yours, where one wants to call GH _like_ a web service but not _as_ a web service, but it's not a priority for us at the moment. Below the web layer, it gets "low-level", and that's okay.

**Comment by michaz** [comment]
> For example you should overwrite the route method in GraphhopperGTFS to use the PTRouter this would make the usage of GH for developers much easier.

*That* should happen at some point -- *or* we get rid of the GraphHopper class entirely. (It's not our favorite class.) Maybe that's why it looks so undecided at the moment.

**Comment by michaz** [comment]
I'm writing so much because I just discussed all this with @easbar  --

I think in the case you are describing, putting the request using the "bus" profile and the request using PT behind the same interface, if useful, should happen on _your_ side of the application. The decision that "routing on a road network when we have no schedule" and "routing on a schedule when we have a schedule" are substitutes for each other is happening in your application, and probably only applies in your use case.

On our side, they are totally different things.

**Comment by michaz** [comment]
> For example you should overwrite the route method in GraphhopperGTFS to use the PTRouter this would make the usage of GH for developers much easier.

But I totally agree on that.

**Comment by hegerdes** [comment]
Thanks for this long answer and some insights.

I already handle PT requests and normal requests on my side and present a unified interface to the outside. But right now I'm not happy with the results of PT routing. Maybe because I handelnd the request wrong, missing some information or just have bad gtfs files. (But I have a backup plan to emulate bus routing, which works kind of great if you can dispense real time scheduling). I can totally understand that all this is low level and not supported officially. Working with the web-api is much easier. 

But I'm happy how active the development is and have my eyes on it. Maybe some day we the gtfs low level stuff gets more accessible. 

If so desired, I will look at a few issus from time to time and try to contribute something.
