### ISSUE TITLE
Getting PointNotFound error for start location

### ISSUE THREAD

**Issue by swetarani** [graphhopper/graphhopper#2116]
**Describe the bug**
I am serving Montana(US) area with following commands:
./graphhopper.sh -a web -i montana-latest.osm.pbf -o montana-gh

I am trying to find route between below locations:
Start: 47.0838,-109.729
End: 46.07748,-109.731295
It throws error: Cannot find point 1: 47.0838,-109.729

But if I change end point to 46.079639,-109.650807, it gives a successful route. How is changing end point resolving issue of PointNotFound for start?

**To Reproduce**

Steps to reproduce the behavior. For examples:

1. checkout recent and stable version of GraphHopper
2. download a montana-latest.osm.pbf
3. run `./graphhopper.sh -a web -i montana-latest.osm.pbf -o montana-gh`
4. error: Cannot find point 1: 47.0838,-109.729

**Expected behavior**
get a successful route for Start: 47.0838,-109.729 and End: 46.07748,-109.731295

**Comment by karussell** [comment]
Please ask questions on our forum: https://discuss.graphhopper.com/

Such errors occur if the location is too far away from the road network

**Comment by swetarani** [comment]
I have already raised this question in forum also without getting any respose.
https://discuss.graphhopper.com/t/getting-pointnotfound-error-for-start-position-but-route-works-when-end-location-is-moved/5951
https://discuss.graphhopper.com/t/getting-pointnotfound-error-for-46-0838-109-729-in-gh-master-latest-code/5872

**Comment by c56kevin** [comment]
> Please ask questions in our forum: https://discuss.graphhopper.com/
> 
> Such errors occur if the location is too far away from the road network

Is there any parameter for the distance between a point to the nearest road network?
