### ISSUE TITLE
unable to get route from 46.0838,-109.729 to 46.079639,-109.650807 via car in North America pbf

### ISSUE THREAD

**Issue by swetarani** [graphhopper/graphhopper#2117]
**Describe the bug**
I am trying to setup graphhopper for USA from geofabrikhttp://download.geofabrik.de/north-america/us.html. I have added foot endcoder in config-example.yml. But I am unable to get route from 46.0838,-109.729 to 46.079639,-109.650807 via car. While https://graphhopper.com/maps/ gives successful route for same location.

**To Reproduce**

Steps to reproduce the behavior. For examples:

1. checkout recent and stable version of GraphHopper (master branch)
2. download from geofabrikhttp://download.geofabrik.de/north-america/us.html
3. run `./graphhopper.sh -a web -i us-latest.osm.pbf -o us-latest-gh`
4. PointNotFound for 46.0838,-109.729

Instead of a manual reproduction it would be even better to have a unit or integration test reproducing the issue.

**Expected behavior**
get successful route from 46.0838,-109.729 to 46.079639,-109.650807

**Comment by karussell** [comment]
Please ask questions on our forum: https://discuss.graphhopper.com/

Such errors occur if the location is too far away from the road network.

**Comment by swetarani** [comment]
I have already raised this question in forum but didn't get any response.
https://discuss.graphhopper.com/t/getting-pointnotfound-error-for-start-position-but-route-works-when-end-location-is-moved/5951
https://discuss.graphhopper.com/t/getting-pointnotfound-error-for-46-0838-109-729-in-gh-master-latest-code/5872
