### ISSUE TITLE
Few locations are not found in large map, although they work properly in small maps

### ISSUE THREAD

**Issue by swetarani** [graphhopper/graphhopper#2123]
**Describe the bug**
Although following 2 locations are working fine in respective State map but gives PointNotFoundError in North-America map.
- 46.0838,-109.729 (Montana)
- 38.0299,-81.235 (West virginia)

Learning from discussion on forum (https://discuss.graphhopper.com/t/connection-between-locations-not-found/3477/7)
I tried both following ways:
- increased prepare.min_network_size to 20000 and re prepared the cache. Still no route
- decreased prepare.min_network_size to 0 so that no networks are removed in PreparingSubNetwork. Still no route.

**To Reproduce**

1. checkout master branch of GraphHopper
2. download montana.pbf (https://download.geofabrik.de/north-america/us/montana.html)
3. run `./graphhopper.sh -a web -i montana.pbf -o montana-gh`
4. Search for route from any nearby point in montana to `46.0838,-109.729` using car. It will give successful route.
5. Now, download north_america.pbf (https://download.geofabrik.de/north-america.html)
6. run `./graphhopper.sh -a web -i north_america.pbf -o north_america-gh`
7. Search for route from any nearby point in montana to `46.0838,-109.729` using car. It will give error: PointNotFound for `46.0838,-109.729`

**Expected behavior**
With change in prepare.min_network_size to 0, it should be able to find route to `46.0838,-109.729` in North America map.

**Screenshots & Logs**
It works fine in graphhopper.com/maps:
https://graphhopper.com/maps/?point=46.0838%2C-108.729&point=46.0838%2C-109.729&locale=en-us&vehicle=car&weighting=fastest&elevation=true&turn_costs=true&use_miles=false&layer=Omniscale

**Comment by karussell** [comment]
A difference for different maps is expected for very large distances to the road network and how the LocationIndex currently works. Have a look into your locations: they are ~2km away from the nearest road. At some point we have to throw an exception and currently this distance is large but not strictly defined. Is there a use case to enforce a stricter handling?

You could enforce always the same behaviour via adapting LocationIndexTree.prepareAlgo and make it independent on the map boundaries. This method has a simple heuristic to adapt the "cells" the location index uses to the map size. Please note that changing it might have arbitrary bad effects like a very slow lookup, an unnecessary large LocationIndex, memory waste or similar.

**Comment by swetarani** [comment]
@karussell thanks for responding.

In LocationIndexTree.prepareAlgo, I see cells are restricted to 9. I am understanding cells are map tiles around the location. Let me know if my understanding is correct. Could you explain what would it mean if I increase cells to say 12.

Also, there is mention of radius till which it searched for closest nodes. How can I change this radius? Is it P_RADIUS in GraphEdgeIdFinder class?
