### ISSUE TITLE
Add ability to parse OSM BoundingBox again

### ISSUE THREAD

**Issue by hegerdes** [graphhopper/graphhopper#2133]
**Add OSM BBox parsing**
It would be great if the OSMReader would support the OSM-Header-BoundingBox. Especially because osmosis lib supports this already. 

I know that you don't use the OSM BBox for the GH graph. The OSM BBox almost always has ways and relation that intercept the BBox and have nodes in- and outside the BBox. This can cause problems. But it would be nice if the Reader supports it for people who want to customize the Reader.

You already had the feature but disabled it: 
https://github.com/graphhopper/graphhopper/blob/c0aaffae8631efb8fa23c6ab5cf26e27027efd08/reader-osm/src/main/java/com/graphhopper/reader/osm/pbf/PbfBlobDecoder.java#L97-L116

I would like to reimplement this and add it to GH.

**Comment by michaz** [comment]
What would you suggest should be GraphHopper‘s behavior when reading this bounding box? What should it do with it?

(I‘m not familiar with the commented-out code, so I don‘t know its history or original purpose..)

**Comment by hegerdes** [comment]
For those how want to use GH as a library. Or for those how want hard Graph BB edges that are identical with the OSM BB. 

I know that the GH BB is calculated differently.
Couldn't find anything either to the old code. Just one old init commit

**Comment by easbar** [comment]
> For those how want to use GH as a library. Or for those how want hard Graph BB edges that are identical with the OSM BB.

What do you mean? What are users who want to use GH as a library supposed to do with the OSM BB?
