### ISSUE TITLE
Allow flexible OTM calculations for users of the library

### ISSUE THREAD

**Issue by otbutz** [graphhopper/graphhopper#2137]
GraphHopper ships with the `DijkstraOneToMany` algorithm which can be used for simple one-to-many routing when running in flexible mode....at least in theory.

At the moment the usage of the `RoutingAlgorithmFactorySimple` is hardcoded which prohibits any reuse of previously created algorithm instances:
https://github.com/graphhopper/graphhopper/blob/b3deab42904026dfc693fc838c9a23da17a595ab/core/src/main/java/com/graphhopper/routing/Router.java#L273-L283

It would be nice to be able to pass in an external implementation of the `RoutingAlgorithmFactory` to the `GraphHopper` instance to be used in the flexible mode.

e.g:

```java
// ...
graphHopper.setFlexibleRoutingAlgoFactory(new CachingRoutingAlgorithmFactory());
List<GHResponse> otmResponses = new ArrayList<>();
for (GHRequest request : otmRequests) {
    otmResponses.add(graphHopper.route(request));
}
```

**Comment by otbutz** [comment]
@karussell i can draft a PR if you're willing to accept it

**Comment by easbar** [comment]
Have you considered using this approach: https://github.com/graphhopper/graphhopper/pull/2106#issuecomment-688914649? I think right now we are still in the process of reducing the capabilities of the GraphHopper class so I would rather not add more functionalities to it currently.

BTW: DijkstraOneToMany is useful to calculate many paths with different targets and the same origin. But note that (compared to the other algorithms) it allocates memory for every node of the graph. This can be useful to speed up the path calculation, but would probably not be suitable in a server-like scenario with concurrent requests (unless you either use a very small map, have lots of RAM or maybe use multiple thread-local instances of DijkstraOneToMany).

**Comment by easbar** [comment]
Btw I think *if* we decided to add extension points I definitely agree that passing some factories (via setter or constructor) should probably be the way this is done. I just don't know if the RoutingAlgorithmFactory is really one of the (central) things (yet) for which such a mechanism should exist. For example until recently it had a very problematic signature that forced us to 'know' what kind of graph the returned algorithm will use.

**Comment by otbutz** [comment]
I would already be happy if we could change the visibility of `Router.createFlexiblePathCalculator()` from private to protected.

**Comment by easbar** [comment]
I am sorry to ask again, but if you need it to be protected why do you not set it to protected in your fork? #2106 (comment)

**Comment by otbutz** [comment]
Closing as a fork seems unavoidable
