### ISSUE TITLE
Reduce GPS precision of Isochrone and SPT endpoints

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#2192]
The precision for lon/lat is much higher than needed, e.g.

```
# prev_lon,prev_lat,lon,lat,distance,time
13.333260193465506,52.481962982162,13.333316445350269,52.48153271112292,5364,538638
13.395117150137956,52.532971148184785,13.396832460094224,52.53357129246528,5046,591984
13.341373130858834,52.53416901530703,13.341338858187322,52.5326990157224,3941,512785
13.333260193465506,52.481962982162,13.333247713742727,52.48261919206275,5389,596566`
```

**Comment by easbar** [comment]
E.g. for /route we use `Helper.round6`, probably we should do the same for /spt and /isochrone?

**Comment by karussell** [comment]
Sounds good! For spt this is easy. For isochrone we would have to make the jts-jackson integration configurable somehow: https://github.com/graphhopper/jackson-datatype-jts/blob/master/src/main/java/com/bedatadriven/jackson/datatype/jts/serialization/GeometrySerializer.java#L170

**Comment by karussell** [comment]
Or we change the doubles in the geometry directly, hmmh ... for isochrone this is not that easy as it could corrupt the polygon.

**Comment by easbar** [comment]
Ok for /spt its more critical anyway

**Comment by michaz** [comment]
> For isochrone we would have to make

Yeah, we just reverted this. #2161

**Comment by michaz** [comment]
Btw. could we store lat/lons with fixed precision (6 places) in our storage? That way, OSM coords (6 places) would come out of the store the same as they go in, and we wouldn't create bogus decimal places only to remove them again later...

**Comment by michaz** [comment]
Just like this?

```
public class Helper {
    public static final Charset UTF_CS = Charset.forName("UTF-8");
    public static final TimeZone UTC = TimeZone.getTimeZone("UTC");
    public static final long MB = 1L << 20;
    // OSM has six decimal places
    private static final double DEGREE_FACTOR = 1e6d;

```

**Comment by karussell** [comment]
Tricky topic.

[OSM uses 7 decimal places](https://github.com/graphhopper/graphhopper/blob/master/reader-osm/src/main/java/com/graphhopper/reader/osm/pbf/PbfBlobDecoder.java#L240) I think.

And currently we use `Integer.MAX_VALUE / 400` to get a slightly higher precision than 1e6 (i.e. close to 1e6), but clearly this has the disadvantage of more decimal places. (1e7 is not possible in an `int` without a special encoding like SpatialKeyAlgo)

I quickly tried to lower precision to 1e6 but some unit tests fail that I wasn't able to fix properly & quickly :) https://github.com/graphhopper/graphhopper/commit/14c1cd0ee0086d65f8f24008bcb4ab8fe4f439eb

I also tried to use round7 or round8 for Helper.intToDegree, but also here some unit tests like DirectionResolverOnQueryGraphTest.duplicateCoordinatesAtBaseOrAdjNode fail which doesn't look right.

**Comment by michaz** [comment]
> OSM uses 7 decimal places, I think.

:-}

**Comment by michaz** [comment]
Okay, next attempt at preventing old problems from ever coming back: Can we (perspectively) just store coordinates as doubles? That would double the size of `geometry`, and (not quite) double the size of `node`. Would that be bad?

**Comment by karussell** [comment]
We can try to increase the bytes from 4 to 5 (i.e. 10 for lat,lon) and increase the precision to 1e8 which will likely help, but with high precision like that or even `double` we might still need rounding (?)

I would not want to increase the memory footprint by this large. Another idea could be to offload the geometry into an explicit mmap storage, but ...

> Isn't geometry "just a database" anyway, i.e. not really touched during routing but only used to build the response?

... we use geometry also for snapping which must be very fast and I would try hard to avoid hiccups which could be caused by mmap (or a naive usage of that).
