### ISSUE TITLE
Reduce node id lookups in OSMReader

### ISSUE THREAD

**Issue by otbutz** [graphhopper/graphhopper#2194]
According to my recent benchmarks the OSMReader spends about 25% of its execution time looking up node ids:

![GHLongIntBTree](https://user-images.githubusercontent.com/22315436/100441054-2184fc80-30a6-11eb-8990-fb8cc3047876.png)

It should be enough to avoid some unnecessary lookups like here:

https://github.com/graphhopper/graphhopper/blob/ec53afeb4e37a0e8f30d4506e96c56123ecdb094/reader-osm/src/main/java/com/graphhopper/reader/osm/OSMReader.java#L256-L265

https://github.com/graphhopper/graphhopper/blob/ec53afeb4e37a0e8f30d4506e96c56123ecdb094/reader-osm/src/main/java/com/graphhopper/reader/osm/OSMReader.java#L479-L481

https://github.com/graphhopper/graphhopper/blob/ec53afeb4e37a0e8f30d4506e96c56123ecdb094/reader-osm/src/main/java/com/graphhopper/reader/osm/OSMReader.java#L496-L497

We could pass the internal node id through and avoid the additional lookups.

**Comment by otbutz** [comment]
Tried to reduce the lookups and even switched to a LongIntHashMap but no significant difference.

A BloomFilter could probably help a lot if we create it based on the nodes in the preprocess step.

**Comment by easbar** [comment]
I think since #2448  and https://github.com/graphhopper/graphhopper/commit/5a369778fd3d6b98ea16dcde63c475d8edf67005 there is not really potential to further reduce the number of lookups. Closing for now, but of course feel free to open again if you think otherwise.
