### ISSUE TITLE
Use PbfFieldDecoder for DenseNodes

### ISSUE THREAD

**Issue by otbutz** [graphhopper/graphhopper#2197]
Citing the OSM wiki:

> In addition to granularity, the primitive block also encodes a latitude and longitude offset value. These values, measured in units of nanodegrees, **must** be added to each coordinate.
> 
> ```
> latitude = .000000001 * (lat_offset + (granularity * lat))
> longitude = .000000001 * (lon_offset + (granularity * lon))
> ```
> 
> Where latitude is the latitude in degrees, granularity is the granularity given in the PrimitiveBlock, lat_offset is the offset given in the PrimitiveBlock, and **lat/lon is encoded in a Node or delta-encoded in a DenseNode**. The explanation of the equation for longitude is analogous. 

The PbfBlobDecoder ignores the offset and granularity completely for DenseNodes:
https://github.com/graphhopper/graphhopper/blob/c03a54c212da1719c901d82526a644bc6a39b1c2/reader-osm/src/main/java/com/graphhopper/reader/osm/pbf/PbfBlobDecoder.java#L240

**Comment by easbar** [comment]
I'm just curious. (Where) does this make a difference in practice / GraphHopper?

**Comment by otbutz** [comment]
I couldn't see any differences so far but i don't know for which elements this kind of encoding is used in OSM :man_shrugging: 
It's still a good idea to follow the spec in order to avoid any pitfalls.
