### ISSUE TITLE
Conflicting protobuf-java versions

### ISSUE THREAD

**Issue by otbutz** [graphhopper/graphhopper#2207]
The situation at the moment:

* reader-osm: protobuf-java **3**.11.4 as a dependency of osmosis-osm-binary
* reader-gtfs: protobuf-java **2**.6.1as dependency of gtfs-realtime-bindings

This causes problems in my draft PR (#2205) as protobuf v3 classes are not available.

We should probably move to a newer version of the gtfs-realtime-bindings to avoid this.

**Comment by otbutz** [comment]
![grafik](https://user-images.githubusercontent.com/22315436/101611165-752e0900-3a09-11eb-8e0f-ddf46f24bab4.png)

**Comment by karussell** [comment]
Thanks for pointing this out. Unfortunately gtfs realtime 0.0.7 seems to use only [protobuf 3.6.1](https://github.com/MobilityData/gtfs-realtime-bindings/blob/master/java/pom.xml). And protobuf 3.14.0 seems to be the most recent version.

But maybe 3.x is compatible from a Java standpoint? Can you try if 0.0.7 passes tests and still makes the problems you mentioned?

**Comment by otbutz** [comment]
Switching to gtfs-realtime-bindings 0.0.7 provided by io.mobilitydata.transit while excluding the transient dependency on protobuf 3.6.1 seems to fix the issue. At least the unittests in my draft PR pass now.

Should i create a separate PR for the fix or can i add this to my existing POM cleanup PR? https://github.com/graphhopper/graphhopper/pull/2200

**Comment by karussell** [comment]
Let's wait what @michaz says :)

**Comment by michaz** [comment]
Oh, please go ahead, as long as it works. There's nothing special happening there.

**Comment by otbutz** [comment]
Fixed by #2200
