### ISSUE TITLE
ArrayIndexOutOfBoundsException in Landmark Preparation

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#2208]
I just saw an error during a landmark preparation for the latest planet file using GraphHopper 2.2. I was running 4 LM preparations in parallel. It worked with yesterdays planet file, it did not work with todays planet file, no code changes.

My guess would be that there might be some infrequent issue with concurrent preparation of LM. Here is the relevant stack trace:

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 13513 out of bounds for length 13513
	at com.graphhopper.storage.RAMDataAccess.setInt(RAMDataAccess.java:192)
	at com.graphhopper.routing.lm.LandmarkStorage.createLandmarks(LandmarkStorage.java:317)
	at com.graphhopper.routing.lm.PrepareLandmarks.doSpecificWork(PrepareLandmarks.java:120)
```

Do you have any idea why this might happen?

**Comment by karussell** [comment]
Hmmh, these problems with planet are hard to tackle down without a reproducer. Can you reproduce this with the latest master and an inbuilt vehicle? 

fyi: we have a few planet-wide imports going on and none of them had a problem today or yesterday, but we use nearly HEAD of master and update the planet file via osmupdate before.

**Comment by boldtrn** [comment]
The error did not occur again today (no code changes, only updated OSM file, I also use osmupdate). So my feeling is still that it is related to concurrency but this is even harder to track down.

I am currently at: https://github.com/graphhopper/graphhopper/commit/598ecb0ff519a86112686e8a97adbfe9c3148aa7 - so almost HEAD. 

Since I don't have more information on how to repro it, we can close this issue until it shows up again? Or we leave it open to have some visibility for it?

**Comment by karussell** [comment]
There is no concurrency happening :) The data structures are completely independent and the graph storage is read-only.

To me this looks more like a rare "plus 1" error somewhere.

> we can close this issue until it shows up again? Or we leave it open to have some visibility for it?

Yeah, not sure how to handle this, in general we tend to keep them open but not sure if this helps :D

**Comment by boldtrn** [comment]
Ah yes, you are right, we have one DataAccess per profile and not one for all. Ok, so it's probably some rare error, let's close this issue for now. If I see it again, I will report it :).
