### ISSUE TITLE
Remove the "disabling allowed" concept

### ISSUE THREAD

**Issue by michaz** [graphhopper/graphhopper#2224]
I think it was originally meant as a stop-gap to prevent a server from accidentally taking too much time for requests, potentially allowing users to "DOS" it.

However, this is a confusing feature for library code: I am programmatically setting up a router. It's _my_ router. It processes requests that I send it. Why do I have to _allow_ it something? Why do I have to _allow_ it to _disable_ something?

This should be handled by web code, or even by a proxy, instead. The Java router should just do what it's told.

Also, it's probably superceded by the profiles concept -- if I don't want to do non-accelerated routing, just make sure I have no non-accelerated profiles.

**Comment by boldtrn** [comment]
I think moving this concept to the web code would make sense.

Moving it to a proxy doesn't sound right to me. The proxy should not need to know about GraphHopper parameters, but handle stuff like cache and sending requests to correct server etc.

One potential corner case I see here would be roundtrips. For roundtrips I need to disable CH, but still use the "same profile" - arguably I could create a second profile for non-ch requests. But I am not sure how you want to change the code - so maybe that is not an issue.

**Comment by easbar** [comment]
Currently we cannot achieve the same effect using profiles. Dijkstra/AStar are always allowed for all profiles. The profiles aren't really related to the algorithm they are used with. `profiles_ch/lm` only controls which preparations are calculated.

**Comment by michaz** [comment]
> Do we need to keep the 'setDisablingAllowed' functionality at all?

Yeah, that was what I was trying to ask. Sorry for being obtuse. :-)
