### ISSUE TITLE
DefaultEncodedValueFactory

### ISSUE THREAD

**Issue by innodeltech** [graphhopper/graphhopper#2227]
ERROR: An error happened while creating graph:DefaultEncodedValueFactory cannot find EncodedValue foot_network

**Comment by karussell** [comment]
Can you add more details what you did and include a full stack trace? Please also use the latest stable release (2.3) and the config-example.yml or a minimal modified one and see if it still occurs.

**Comment by innodeltech** [comment]
i want to create nodes_ch_fastest_bike_node and CityNode.txt file.


![asia_india](https://user-images.githubusercontent.com/44992121/103409221-c609cb00-4b8b-11eb-8759-1ccce27345be.png)

**Comment by karussell** [comment]
I do not think this is an issue with GraphHopper. Please post what you tried in our forum and include more details: used GraphHopper version, operating system, the config file, what you did, what you expect.
