### ISSUE TITLE
Truck profile

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#223]
Create a truck profile which is configurable
- warn the user if the FlagEncoder is configured differently than what is stored in the graph. Or load what is stored in the graph. See #285
- create a simple profile for bus which we could use without configuration. E.g. it could be the following: length 12m, 2.6 m wide, 3.6m height, 10 t empty, 14 t filled (persons+luggage), EU emission standard 5, 2 axis, no hazard material, ... taken from http://www.omnibusrevue.de/celeris-midi-c3-man-14-290-hocl-970670.html Furthermore there could be an option to allow/disallow psv

See [this discussion](https://discuss.graphhopper.com/t/bus-flag-encoder-on-graphhopper-com/796)

**Comment by sanga** [comment]
Any news on this? You have this (or something like it) internally I suppose, and I think I read somewhere that implied that it might get open sourced (here I guess it was: https://discuss.graphhopper.com/t/bus-flag-encoder-on-graphhopper-com/796/5)

**Comment by karussell** [comment]
No, but it will get easy/easier after we finish the work with configurable vehicle profiles #730 

Regarding what is open source and what will be you can also read #131 and https://graphhopper.com/#os-comparison

**Comment by sanga** [comment]
OK, understood. Thanks for the quick response.

**Comment by karussell** [comment]
Parts of this are implemented in PR #936

**Comment by tmnguyen-swin** [comment]
There is one comment I forgot to mention in PR #936 in relation to having multiple configuration flags for road attributes. In my view, I don't think all clients need the full set of encoders. Needs will vary depending on client's usage. As such, most of the encoders (like highwayEncoder, surfaceEncoder, transportModeEncoder, accessEncoder) in DataFlagEncoder should be make configurable independently. Clients will be able to enable/disable encoders for their respective purpose.

**Comment by karussell** [comment]
> As such, most of the encoders (like highwayEncoder, surfaceEncoder, transportModeEncoder, accessEncoder) in DataFlagEncoder should be make configurable independently. Clients will be able to enable/disable encoders for their respective purpose.

This is fully configurable with #1548
