### ISSUE TITLE
Publishing GitHub packages fails with 409 error

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#2234]
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project hmm-lib-external:
Failed to deploy artifacts:
Could not transfer artifact com.graphhopper:hmm-lib-external:jar:sources:13b7d337e28ec02c4f4b5f8da06e3f24207dc454 from/to github (https://maven.pkg.github.com/graphhopper/graphhopper):
Transfer failed for https://maven.pkg.github.com/graphhopper/graphhopper/com/graphhopper/hmm-lib-external/13b7d337e28ec02c4f4b5f8da06e3f24207dc454/hmm-lib-external-13b7d337e28ec02c4f4b5f8da06e3f24207dc454-sources.jar 409 Conflict -> [Help 1]
```

I think I saw this error a few times before but recently it happened for 3/4 commits in master :(

**Comment by karussell** [comment]
Maybe this is because of the release version which cannot be overwritten? We could try to either move hmm-lib in a separate repo (like we did for the jts jackson bridge) or set the version to the GH project version too.

**Comment by michaz** [comment]
What release version?

**Comment by michaz** [comment]
I would say this happens whenever a commit that has already been built once is built again, e.g. in a different branch or a tag. It has the same commit has, so it has the same version number, so it already exists, so it is a conflict, so it fails.

**Comment by easbar** [comment]
> Has nothing to do with hmm-lib in particular, that's just a coincidence. I've seen it fail for other artifacts. I think it's whatever gets uploaded first, or, if two builds are concurrent, the first where it clashes.

Yes

> I would say this happens whenever a commit that has already been built once is built again, e.g. in a different branch or a tag. It has the same commit hash, so it has the same version number, so it already exists, so it is a conflict, so it fails.

Yes I think this happens when the version number is the same, but I think it also happened when this was not the case. For example here: https://github.com/graphhopper/graphhopper/runs/1694170423

Hm, but since we have no idea what we can do and it no did not happen for some time I'll close here, let's see when it happens the next time...

**Comment by Huluvu424242** [comment]
@michaz I had the same problem every time in my maven build if i had:
1. attach sources  and javadoc additional to the jar (in release profile of pom.xml)
and
2. more targets e.g. ./mvnw -U -Prelease clean site install deploy

Now i use only deploy target in my release workflow and its works fine
```
    - name: Deploy to Github Package Registry
      run: ./mvnw -U -Prelease deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by easbar** [comment]
@Huluvu424242 Thanks, that is good to know. I remember at some point we used multiple targets (similar to `install deploy`) for the Maven command (probably accidentally).
