### ISSUE TITLE
GraphHopper doesn't consider chains when car routing

### ISSUE THREAD

**Issue by FinixFighter** [graphhopper/graphhopper#2236]
**Describe the bug**
The route suggested by GraphHopper isn't correct. It says that I should go through a street but I can't because there's a chain that block access to cars. I'm sure about that because my parents live on that street.

**To Reproduce**
To reproduce the bug, you can go to openstreetmap.org and set the route using the coordinates that you can see in the screenshots. Then see the difference between the routing method "Car (GrapHopper)" and the "Car (OSRM)". OSRM is the correct way of going from A to B by car.

**Expected behavior**
GraphHopper should show the same routing than OSRM (in this case).

**Screenshots & Logs**
![GraphHopper](https://user-images.githubusercontent.com/19877271/106175534-82a87980-6196-11eb-934a-d0ba6dbc50df.png)
![OSRM](https://user-images.githubusercontent.com/19877271/106175537-84723d00-6196-11eb-8622-549f2c48ec35.png)
As you can see below, there's a chain on the street that blocks access to motor vehicles.
![photo_3](https://user-images.githubusercontent.com/19877271/106175546-86d49700-6196-11eb-82ac-8b28467aadd7.png)

**Comment by karussell** [comment]
Uh, indeed. There is even motor_vehicle:no https://www.openstreetmap.org/node/7602143350
