### ISSUE TITLE
Specify direction for start and end

### ISSUE THREAD

**Issue by crowmagnumb** [graphhopper/graphhopper#225]
I have a case in which the starting direction on the street, as well as the starting point, is effectively known.  If I use the route tool this starting direction is not taken into account when I try to go from this point to another point. The directions will just start off saying "Continue On ..." when in fact they would preferably say "Turn Around".  However, I don't always *want* them to have to turn around as driving around the block to get going the other way is usually preferable (especially if it's a big truck). Is there a way to pass in the preferable starting direction.

**Comment by jansoe** [comment]
I created a branch (#434) that addresses this feature. Unfortunately it is limited to the non-CH case (flexibility mode). Anyhow there are some conventions to be made, where I would appreciate your feedback. 
I implemented it such that one can specify the  ```heading``` parameter for start/stopover/end points as north based clockwise angle measured in radian (0, 2pi).  Are there preferences or reasons for different angle conventions (e.g. degree (0, 360) or (-180, 180), east-based, ...)?
Or even other suggestions?

**Comment by devemux86** [comment]
I would suggest to follow the common bearing guidelines, e.g. like Android describes in ```Location``` class:
http://developer.android.com/reference/android/location/Location.html#getBearing()

**Comment by devemux86** [comment]
BTW how do you think will the arrival ```heading``` parameter will work with the via points and end point ?

**Comment by karussell** [comment]
is the bearing north based?

**Comment by devemux86** [comment]
http://en.wikipedia.org/wiki/Bearing_(navigation)#Bearing_measurement
Yes, though the reference direction of 0° can be the magnetic of true north.

You can see also her:
http://en.wikipedia.org/wiki/Course_(navigation)

**Comment by jansoe** [comment]
thanx, so I'll probably change to to degree.
 
> BTW how do you think the arrival heading parameter will work with the via points and end point ?

Sorry I do not really understand the question, but I'll try to answer:  if general ```heading=0``` means that the head of the car is pointing north, as well at start or via/end points.

**Comment by karussell** [comment]
@devemux86 maybe if it helps: there are two options for via points (or end point). The first one tries to avoid a u-turn at via points and the second one enforces a heading e.g. to make sure that a truck arrives at a via point from a specific direction (e.g. otherwise it would be harder for the truck to enter a gate etc)

**Comment by jansoe** [comment]
An implementation of this feature is now available by #434.

Nonetheless, it currently works only in the 'flexibility mode', i.e. without CH.

Furthermore, the heading enforcement happens after the location lookup. Therefore headings are ignored on one-way streets, but an improvement could be, already  to select in the lookup only streets which comply to the favored heading.

**Comment by devemux86** [comment]
:+1: 

>Furthermore, the heading enforcement happens after the location lookup. Therefore headings are ignored on one-way streets, but an improvement could be, already to select in the lookup only streets which comply to the favored heading.

I imagine you're referring to via,end points heading?
Because for start point heading, a car is supposed to be already in the needed street (e.g. oneway) and wants to proceed following the street (or lane) direction.

**Comment by jansoe** [comment]
Actually I'm mainly referring to the start point in the case there are two separated lanes for the forward and backward direction. Your (latitude, longitude) value might be a bit erroneous and you are located on the wrong side. In this case , the heading value could be a good indicator that your position is actually on the other road. Does this makes sense?

**Comment by devemux86** [comment]
Ok now I see what you mean, thanks for the clarification.
Indeed the GPS accuracy can confuse the situation here and the aforementioned improvement would be valuable.

**Comment by devemux86** [comment]
@jansoe @karussell 
Played with the direction feature in navigation and works well. :+1: 
More thorough tests are to be done (regarding the accuracy too).

**Comment by karussell** [comment]
Closing here for now, although without CH support but this is rather an algorithmic limitation. Feel free to create new separate issues if you don't think so or found a problem.
