### ISSUE TITLE
mapmatching: findCandidateSnapsInBBox may fail to find relevant tower node snaps.

### ISSUE THREAD

**Issue by skywave** [graphhopper/graphhopper#2262]
**Describe the bug**

In a situation where a GPS trace "overshoots" an intersection as in this[ example ](https://ibb.co/t8DZFFN), the relevant tower node of the intersection is not returned by findCandidateSnapsInBBox but only snaps on the irrelevant roads of this intersection. 
This leads to detours.

**To Reproduce**

So far i have been unable to reproduce this error in a smaller datasets as it could even differ over multiple OSM imports. I now suspect that a whole lot depends on the import order.

**Potential fix**
I fixed this problem in my own modded mapmatching code, by removing `seenNodes.add(node)`  from line 241 and instead move this to line 252 to only mark nodes as seen that were included in a Snap.

https://github.com/graphhopper/graphhopper/blob/7cbb2484019f76967255aaa15509956266bc3f81/map-matching/src/main/java/com/graphhopper/matching/MapMatching.java#L241

**Comment by michaz** [comment]
Whoa! This was very helpful, thanks.
