### ISSUE TITLE
Bicycle routing through private ways

### ISSUE THREAD

**Issue by sebastienaubry** [graphhopper/graphhopper#2263]
Hello,
I have noticed that the routing sometimes takes private ways.
Here is [an example](https://graphhopper.com/maps/?point=43.514759%2C1.349516&point=43.508114%2C1.345482&locale=en-US&vehicle=bike&weighting=fastest&elevation=true&turn_costs=false&use_miles=false&layer=Omniscale).
The way "Chemin de la Pasquerie" is partly tagged as: access=private; bicycle=yes; highway=unclassified; name=Chemin de Pasquerie
I suspect the "bike=yes" tag may be the cause of the routing though this private way.
Thanks

**Comment by karussell** [comment]
If it is tagged with bicycle=yes then we see ignore the access restriction. If bicycle are not allowed too, why would there be a bicycle=yes tag?

( https://www.openstreetmap.org/way/22911601 )

**Comment by sebastienaubry** [comment]
Thank you, you are right. I assume that "bike=yes" was meaning that the bikes were usable on that surface or were allowed before the interdiction. I will now remove this tag.
