### ISSUE TITLE
Routing gives impossible combination of ferry and underpassed bridge

### ISSUE THREAD

**Issue by wonderb0lt** [graphhopper/graphhopper#2264]
**Describe the bug**
When requesting a routing for bikes on [this route](https://graphhopper.com/maps/?point=Dresden%20Mitte%2C%2001067%2C%20Germany&point=Fl%C3%BCgelwegbr%C3%BCcke%2C%2001139%2C%20Dresden%2C%20Germany&locale=en&vehicle=bike&weighting=fastest&elevation=true&turn_costs=false&use_miles=false&layer=Omniscale) (choosing the first result for the bridge, which is of type `man_made` - which is what happens if you search for this route in OSM), you're instructed to jump off the ferry mid-ride when you reach the bridge. It doesn't stop there.

**To Reproduce**

-

**Expected behavior**
Being routed not via the ferry but streets, like when you request a routing for the street. I think it should only consider ferry points where it is connected to anything a bike can drive on (like [Brücke 1](https://www.openstreetmap.org/way/124190406), where we get on the ferry in the first place.

**System Information**

n/a

**Screenshots & Logs**

## Given route

![image](https://user-images.githubusercontent.com/1413052/112056416-453de800-8b58-11eb-999e-a612c0dc91f3.png)

## Correct route

![image](https://user-images.githubusercontent.com/1413052/112056521-643c7a00-8b58-11eb-85ea-01112ad521b5.png)

**Comment by karussell** [comment]
We should include snap_prevention=ferry for GH Maps UI by default:

https://graphhopper.com/maps/?point=Dresden%20Mitte%2C%2001067%2C%20Germany&point=51.06423%2C13.68977&vehicle=bike&snap_prevention=ferry

See similar issue: https://github.com/graphhopper/graphhopper/issues/322

We will consider this for [our rewrite](https://github.com/graphhopper/gh-maps/issues/35).
