### ISSUE TITLE
test fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [graphhopper/graphhopper#2282]
[jw@cn05 graphhopper]$ mvn install
...
[INFO] Running com.graphhopper.search.StringIndexTest
StringIndexText.testRandom seed:706433408928903799
[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.505 s - in com.graphhopper.search.StringIndexTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   GraphHopperStorageCHTest.testSave_and_Freeze:243->GraphHopperStorageTest.testSave_and_Freeze:116  NoSuchMethod
[ERROR]   GraphHopperStorageCHTest>GraphHopperStorageTest.testSave_and_fileFormat:94  NoSuchMethod
[ERROR]   GraphHopperStorageTest.testSave_and_Freeze:116  NoSuchMethod java.nio.ByteBuf...
[ERROR]   GraphHopperStorageTest.testSave_and_fileFormat:94  NoSuchMethod java.nio.Byte...
[ERROR]   GraphHopperStorageWithTurnCostsTest>GraphHopperStorageTest.testSave_and_Freeze:116  NoSuchMethod
[ERROR]   GraphHopperStorageWithTurnCostsTest.testSave_and_fileFormat:82  NoSuchMethod ...
[ERROR]   GraphStorageViaMMapTest>AbstractGraphStorageTester.testClone:272  NoSuchMethod
[ERROR]   GraphStorageViaMMapTest>AbstractGraphStorageTester.testCopyProperties:284  NoSuchMethod
[ERROR]   GraphStorageViaMMapTest>AbstractGraphStorageTester.testCopyTo:323  NoSuchMethod
[ERROR]   GraphStorageViaMMapTest>AbstractGraphStorageTester.testDetachEdge:815  NoSuchMethod
[ERROR]   GraphStorageViaMMapTest>AbstractGraphStorageTester.testDontGrowOnUpdate:796  NoSuchMethod
[ERROR]   GraphStorageViaMMapTest>AbstractGraphStorageTester.testEnabledElevation:778  NoSuchMethod
[ERROR]   GraphStorageViaMMapTest>AbstractGraphStorageTester.testPillarNodes:606  NoSuchMethod
[ERROR]   GraphStorageViaMMapTest>AbstractGraphStorageTester.testStringIndex:692  NoSuchMethod
[ERROR]   MMapDataAccessTest>DataAccessTest.testCopy:166  NoSuchMethod java.nio.ByteBuf...
[ERROR]   MMapDataAccessTest>DataAccessTest.testSet_GetByte:274  NoSuchMethod java.nio....
[ERROR]   MMapDataAccessTest>DataAccessTest.testSet_GetBytes:249  NoSuchMethod java.nio...
[INFO]
[ERROR] Tests run: 2028, Failures: 0, Errors: 17, Skipped: 11
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for GraphHopper Parent Project 3.0-SNAPSHOT:
[INFO]
[INFO] GraphHopper Parent Project ......................... SUCCESS [  1.979 s]
[INFO] GraphHopper API .................................... SUCCESS [  4.722 s]
[INFO] GraphHopper Web API ................................ SUCCESS [  4.399 s]
[INFO] GraphHopper Core ................................... FAILURE [01:17 min]
[INFO] GraphHopper Reader for OpenStreetMap Data .......... SKIPPED
[INFO] GraphHopper Isochrone .............................. SKIPPED
[INFO] GraphHopper Reader for Gtfs Data ................... SKIPPED
[INFO] GraphHopper Tools .................................. SKIPPED
[INFO] hmm-lib ............................................ SKIPPED
[INFO] GraphHopper Map Matching ........................... SKIPPED
[INFO] GraphHopper Directions API hand-crafted Java Client. SKIPPED
[INFO] GraphHopper Dropwizard Bundle ...................... SKIPPED
[INFO] GraphHopper Navigation ............................. SKIPPED
[INFO] GraphHopper Web .................................... SKIPPED
[INFO] GraphHopper Example ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:29 min
[INFO] Finished at: 2021-04-15T12:25:54+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project graphhopper-core: There are test failures.
[ERROR]
[ERROR] Please refer to /data/jw/graphhopper/core/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :graphhopper-core
[jw@cn05 graphhopper]$

**Comment by karussell** [comment]
Which java version are you using?

**Comment by LutzWeischerFujitsu** [comment]
Java 1.8

**Comment by karussell** [comment]
This problem is unrelated to GraphHopper (see e.g. our travis job running with java 8) and it likely occurs when a different java version is used for compilation and running the test.

Also make sure you are using the latest java 8 version e.g. get it from adopt JDK.
