### ISSUE TITLE
Large query distance when snapping to subnetwork

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#2306]
![image](https://user-images.githubusercontent.com/17603532/117352426-48dec180-aeaf-11eb-9485-73ba7f6a660f.png)

The green marker is located in a small subnetwork, but instead of snapping next to it the location snaps to a location far north

**Comment by easbar** [comment]
I added a unit test showing the issue here: https://github.com/graphhopper/graphhopper/commit/3d64e7c8bcf7c5e6a7f1464b8ebe484e3444441b

**Comment by michaz** [comment]
Ah, we just need a higher `maxRegionSearch` here to get the correct snap.

That we got a _wrong_ (distant) snap (rather than no snap) was something that only happens in tests or small scenarios -- the point was at the bottom of the grid, and the grid was a torus, so we would walk back in at the top.

(This still happens the other way round (added a TODO, didn't have the max grid coordinate handy at the moment..))

**Comment by easbar** [comment]
Thanks for the quick fix! Maybe we should resurrect #2225 at some point? Maybe a simple way to do this would be just checking that for every snap the query distance is below some threshold or something.

**Comment by michaz** [comment]
> Maybe a simple way to do this would be just checking that for every snap the query distance is below some threshold or something

Nah, the max grid coordinate is explicitely in there somewhere.

**Comment by karussell** [comment]
I think what @easbar means is that a random test can check if the result is within a certain distance. But I'm also unsure if the random test case would have caused this problem and how useful the random test can be. At least we would not need to mostly duplicate the LocationIndex code in the random test like I had to do and only check that the snap is close enough?

**Comment by easbar** [comment]
We would have found the problem in the present issue this way (queryDistance was > 20km in an urban area), I just don't know what *other* errors we can find this way :) I probably only works as long as the radius we enforce is somewhat 'small' (at least small compared to the extent of the test map). Counting the number of invalid snaps could also be an indicator for regression errors.

Another idea could be running some kind of local SPT and counting the number of edges that are close to the query point that are accepted by the edge filter. This number should be small as well.
