### ISSUE TITLE
Foot and bike routing avoid certain paths without obvious reason

### ISSUE THREAD

**Issue by Discostu36** [graphhopper/graphhopper#2331]
**Describe the bug**
Foot and bike routing avoid certain paths without any obvious reason. The bug could have something to do with `mtb:scale` or `sac_scale` tags, but I am not sure.

**To Reproduce**
1. Make a [route from 48.216045,11.328937 to 48.216227,11.331089](https://graphhopper.com/maps/?point=48.216045%2C11.328937&point=48.216227%2C11.331089&locale=de&elevation=true&profile=foot&use_miles=false&selected_detail=Elevation&layer=Omniscale)
2. Try different foot and bike profiles
3. See that it is not possible to route to [this path](https://www.openstreetmap.org/way/23438165).

**Expected behavior**
The router should lead onto the path because it is allowed for foot and bicycle.

**Screenshots & Logs**
![grafik](https://user-images.githubusercontent.com/30999326/119147584-0808b000-ba4c-11eb-819e-838d05b04e90.png)

**Comment by otbutz** [comment]
The way is not properly tagged. The OSM wiki has a list of possible values for `sac_scale`: https://wiki.openstreetmap.org/wiki/Key:sac_scale#Values

The way should be tagged with `sac_scale=hiking` instead.

**Comment by otbutz** [comment]
But we should probably refactor the code so that i can handle tagging mistakes.

**Comment by Discostu36** [comment]
> But we should probably refactor the code so that i can handle tagging mistakes by using a blacklist approach.

I don't know how the routing engine interprets `sac_scale` but shouldn't it just use the correct values and ignore everything else? Or will Graphhopper also avoid a way tagged with `surface=sauerkraut`?

**Comment by otbutz** [comment]
```java
    boolean isSacScaleAllowed(String sacScale) {
        // other scales are nearly impossible by an ordinary bike, see http://wiki.openstreetmap.org/wiki/Key:sac_scale
        return "hiking".equals(sacScale);
    }
```

**Comment by otbutz** [comment]
I think it's only the sac_scale handling which needs to be fixed

**Comment by karussell** [comment]
> but shouldn't it just use the correct values and ignore everything else? Or will Graphhopper also avoid a way tagged with surface=sauerkraut?

IMO sac_scale has to be special and we use the safest & strictest approach here i.e. an explicit list of allowed values. IMO we should keep it as it is as those issues are easy enough to identify and fix (?)

**Comment by DStillingfleet** [comment]
Hi

Let me start with a big thumbs up on a great product. 

Could you let me know how was this issue resolved?  

I use an number of products that use graphhopper for routing, and they appear to ignore paths with a sac-scale / hiking difficulty rating of T2 or above.  This is a particular problem as I find OSM contributors applying the scale inconsistently.  Though when plotting routes, I would still like to plot those with T2, T3, & T4 ratings, but that's likely personal. 

Kind regards

Derek

**Comment by karussell** [comment]
This should work. Do you have an example that is not working? (any mistagged sac_scale will be excluded!)

For foot we allow T1-T3 and for hike we allow all: T1-T6

**Comment by DStillingfleet** [comment]
That's good information.  I use the GPX Studio website, and 3D Maps Pro on iOS.  Do you know what mode GPX Studio uses for it's running setting?  3D Maps Pro is possibly using foot.  

Using OSM, I recently edited the data for the paths that were causing me problems.  They had been incorrectly scaled as T4, maybe wishful thinking on the part of the contributor.  How much time would it take for those changes to be seen by Grapphopper?

**Comment by karussell** [comment]
Don't know. And if they are a customer of our commercial service the update takes around 1-2 days for outdoor profiles.
