### ISSUE TITLE
Graph sorting produces wrong routes after GraphHopper restart

### ISSUE THREAD

**Issue by otbutz** [graphhopper/graphhopper#2336]
Just tested our current master with `graph.do_sort: true` and got "interesting" results after i restarted GraphHopper.

Testcase: http://localhost:8989/maps/?point=GraphHopper%20M%C3%BCnchen&point=48.748945%2C11.451874&profile=car

Routing is perfectly fine if i test directly after importing:

![after_import](https://user-images.githubusercontent.com/22315436/120177986-46029280-c209-11eb-9f48-f3bfdb96062a.png)

If i restart GH and try the same route:

![after_restart](https://user-images.githubusercontent.com/22315436/120178133-6fbbb980-c209-11eb-88ff-12e75766a66e.png)

The route seems to target completely different start/end points.

**Comment by otbutz** [comment]
Maybe related to #2323 ?

**Comment by karussell** [comment]
The problem seems to be if graph.do_sort is enabled it is done on import and on every restart.

We should introduce something like `hasSorted` like we have for the interpolation. Strange that this wasn't a problem earlier.

**Comment by otbutz** [comment]
Fixed by https://github.com/graphhopper/graphhopper/commit/48d2c93916c2364baa6d4c3cdc1299a4a7d0056d
