### ISSUE TITLE
Duplicate elevation parameter produces strange routes

### ISSUE THREAD

**Issue by otbutz** [graphhopper/graphhopper#2337]
Stumbled upon this while trying to reproduce #2336. The URL was the result of a copy&paste error.

https://graphhopper.com/maps/?point=GraphHopper%20M%C3%BCnchen&point=48.748945%2C11.451874&elevation=true&elevation=true&profile=car

![grafik](https://user-images.githubusercontent.com/22315436/120185393-6edb5580-c212-11eb-938f-ae494067df32.png)

**Comment by easbar** [comment]
This was just an issue of the web UI: When there were multiple parameters `elevation=true`, `api_params.elevation` became an array and our `hasElevation` method returned false.  Obviously the point decoding doesn't work correctly when decoding with `is3D=false` while elevation was encoded on the server-side, resulting in this strangely looking route.
