### ISSUE TITLE
Move Jackson into core and maybe remove the web-api module?

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#2354]
For a long time we tried to avoid Jackson in core due to Android compatibility, but now we do not have this restriction anymore we can finally add the Jackson dependency to core? This way we should be able to avoid some ugly workarounds like the `jsonFeatureCollection` argument in the `GraphHopper` class and the Jackson mixins. To me it looks like we can just make core a depend on the web-api module, but probably we can then just as well move the entire module into core?!

**Comment by otbutz** [comment]
100% agree

**Comment by easbar** [comment]
Should we do this now/before #2353? For #2353 we have to make a choice: Either we add `countries.geojson` to the `web-bundle` just like landmark splitting collection and inject the custom areas via the GraphHopper constructor in `GraphHopperManaged`. This seems really odd because we (only) need the custom areas for a core class (OSMReader) and the entire reason we cannot read the custom areas at the place we need them would be that we restrict ourselves to not having Jackson in core. Or we fix this issue first, then we can move `countries.geojson` into core. Honestly, so far I do not see a single reason not to have Jackson in core. In core we already have file IO, so if we read and write files why should we not read/write serialize/deserialize json files? We parse OSM in binary format, so why can we not read json files? Also for XML we would probably not hesitate to use it since it is included in java already? So just because Jackson is used at the web interface that does not mean Jackson is something that is strictly related to web-stuff and we should keep it out of core because we are trying to keep web-stuff out of core. Jackson is *also* used at the web interface, but we just as well need it to read custom areas, custom models, landmark splitting collections and would probably even use it for more things like base graph properties etc. if we did not have this restriction in the past. 

Regarding the `web-api` module I don't have a strong opinion, but also I do not see a real reason to keep it at the moment.

**Comment by otbutz** [comment]
IMHO the whole injection solution is just a dirty workaround and i would be happy if we could use core as-is without doing the injection thing manually.

**Comment by easbar** [comment]
There is one place where we use web-api, but not core: client-hc

**Comment by otbutz** [comment]
We could switch the jackson dependencies from transitive to explicit ones in the client-hc project.

**Comment by easbar** [comment]
I think I want to do this the minimal invasive way, otherwise there will be just too much to discuss :) So I think I want to keep the web-api module and only add Jackson dependencies to core. Like I said I see no reason why core should not depend on Jackson, because it is simply something used to do disk I/O which we do a lot in core.

client-hc not only needs the Jackson dependencies, but also things like `GHPointSerializer` etc., so if we moved web-api into core client-hc would have to depend on the entire core moduley, which is probably something that needs discussion and seems to be another issue.

**Comment by otbutz** [comment]
I've opened #2365 to delete all remaining workarounds.
