### ISSUE TITLE
Make ford check including checking depth == 0

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#236]
As the [wiki says](http://wiki.openstreetmap.org/wiki/Ford) a ford can have `depth=0` so we should include this in our check for all vehicles. Additionally we could use InstructionAnnotation to warn the user about this possible problem. What about `intermittent=yes` or `seasonal=yes`?

Which will fix e.g. this possible bus route:
![bus-route](https://cloud.githubusercontent.com/assets/129644/3564662/fbaeaa7e-0a91-11e4-9c9c-2fbafb81c5f9.png)

http://graphhopper.com/maps/?point=Kulgera%2C%20Australia&point=Alice%20Springs%2C%20Australia

**Comment by karussell** [comment]
Probably we tag this route segment as potential dangerous (via instruction annotation). Also I got a report [in france](https://graphhopper.com/maps/?point=43.473843%2C6.882076&point=43.473999%2C6.882784&vehicle=foot&elevation=true&layer=TF%20Cycle) that this should be passable.

**Comment by malenki** [comment]
I'd vote for make fords routable with graphhopper. If the weren't passable the one or other way they wouldn't have been mapped as ford. You may warn users for fords (not the way between them), but there are less developed countries where routing with graphhopper will get you nowhere because of fords:
https://graphhopper.com/maps/?point=benje-novosele&point=40.299871%2C20.467808

**Comment by MarkCupitt** [comment]
Suggestion: Maybe in the Turn Instructions, list specifically that it is a Ford and may not be passable ..

**Comment by scaidermern** [comment]
Maybe we should try to give fords just a penalty instead of avoiding them altogether.

**Comment by pyrog** [comment]
@malenki :+1: 
> I'd vote for make fords routable with graphhopper. If the weren't passable the one or other way they wouldn't have been mapped as ford. You may warn users for fords 

@scaidermern :+1: 
> Maybe we should try to give fords just a penalty instead of avoiding them altogether.

See an [example in France](https://graphhopper.com/maps/?point=47.055863,5.993144&point=47.07094,6.014199&point=47.071145,6.014585&point=47.068909,6.041054&vehicle=foot&locale=fr&elevation=true&layer=TF%20Outdoors):  I use intermediates to force the algorithm to use this itinerary.

We could have the same problem with [mountain pass](http://wiki.openstreetmap.org/wiki/Key:mountain_pass) in winter :wink:
:bulb: Add an option to avoid mountain pass, ford, toll…

**Comment by engaric** [comment]
You may want to look at some of the code I have done in engaric / graphhopper specifically the avoidance decorator hierarchy. Unfortunately I haven't managed to clear the contributor license with program management yet so cannot yet contribute it to upstream.

Sent from my BlackBerry 10 smartphone on the EE network.
From: pyrog
Sent: Friday, 12 June 2015 20:53
To: graphhopper/graphhopper
Reply To: graphhopper/graphhopper
Subject: Re: [graphhopper] Make ford check including checking depth == 0 (#236)


@malenki :+1:
> I'd vote for make fords routable with graphhopper. If the weren't passable the one or other way they wouldn't have been mapped as ford. You may warn users for fords

@scaidermern :+1:
> Maybe we should try to give fords just a penalty instead of avoiding them altogether.

See an [example in France](https://graphhopper.com/maps/?point=47.055863,5.993144&point=47.07094,6.014199&point=47.071145,6.014585&point=47.068909,6.041054&vehicle=foot&locale=fr&elevation=true&layer=TF%20Outdoors):  I use intermediates to force the algorithm to use this itinerary.

We could have the same problem with [mountain pass](http://wiki.openstreetmap.org/wiki/Key:mountain_pass) in winter :wink:
:bulb: Add an option to avoid mountain pass, ford, toll…

---

**Comment by malenki** [comment]
engaric schrieb
am Fri, 12 Jun 2015 13:22:17 -0700:

> We could have the same problem with [mountain
> pass](http://wiki.openstreetmap.org/wiki/Key:mountain_pass) in
> winter :wink: :bulb: Add an option to avoid mountain pass, ford, toll…

I wouldn't simply avoid mountain passes but only roads not cleared or
even closed in winter. gritting= and winter_service= do exist, though I
don't if roads closed in winter get mapped differently.

Now you just need to define "winter".

**Comment by pyrog** [comment]
@malenki 
> I wouldn't simply avoid mountain passes but only roads not cleared or even closed in winter.

You're right :smile: I see your proposed feature [winter_service](http://wiki.openstreetmap.org/wiki/Proposed_features/Key:winter_service).

> Now you just need to define "winter".

We could compute it with the date and our position on the earth, but we could simply use [conditional restrictions](http://wiki.openstreetmap.org/wiki/Conditional_restrictions).
Another solution is to use [TMC](http://wiki.openstreetmap.org/wiki/TMC) datas ?

**Comment by pyrog** [comment]
`depth=*` is never used in France.

Also the value `ford=stepping_stones` is used (814 in [TagInfo](http://taginfo.openstreetmap.org/tags/ford=stepping_stones)).
Cars, horses and maybe bicycles can't use theses fords :wink: 
Only foot ?

As @malenki, @scaidermern and @MarkCupitt, I'd vote for make **fords routable with graphhopper**.

**Comment by karussell** [comment]
Ok, this is important but without route instructions warnings not good/safe IMO. Postponing for now

**Comment by pyrog** [comment]
> without route instructions warnings... 
  
Currently, does GH can display route instructions warnings ? 
  
  
> ...not good/safe IMO. 
  
As an experienced backpacker and rider, I prepare carefully my treks using différents sources. (Digitals) maps and automatic routers are one of them. 
  
Using only a digital router/map is dangerous, even if warnings are displayed. World is continually changing, (espacially weather) and any maps could up to date. 
  
> Postponing for now 
  
IMHO this issue should be fixed now, and a safety tips should be displayed like : 
  
"Hiking [...] contains inherent risks which no amount of care, caution or expertise can eliminate. This site is no substitute for topo maps, route finding skill, compass, physical condition, sense of humor or good judgement" 
Source: http://www.toddshikingguide.com/Warning/Warning.htm

**Comment by karussell** [comment]
> Currently, does GH can display route instructions warnings ?

We can add annotations to instructions, which should be marked as warning then.

> IMHO this issue should be fixed now, and a safety tips should be displayed like :

postponing only for the upcoming release

> Hiking [...] contains inherent risks which no amount of care, caution or expertise can eliminate.

Sure, for example we have this in our terms. But as this is not really a big effort and of great help we should include it before enabling this for all.

Also if you really need this you can already enable routing through fords.

**Comment by zstadler** [comment]
I also think routing through fords should be the default. 
As said above, the routing program is not responsible for weather conditions.

Given that fords are used in many different places in the world, any assumptions on access implications will be incorrect in a different climate or culture.

IMO, any routing implications or restrictions should be tagged separately using access, width, weight, and similar tags.

**Comment by karussell** [comment]
I was pointed to https://wiki.openstreetmap.org/wiki/Key:flood_prone which says *unlike flood prone areas, fords may be safe to cross if there is water across the roadway*. So can/should we just assume fords are safe? And block/warn only flood_prone? Or is this dependent on the mapper/geographic region?

**Comment by boldtrn** [comment]
Are there any news on this issue? Is this still something we want to do?

A way I see to fix this would be to:

- Allow routing through fords, [optionally] add a penalty?
- Safe a flag per edge, to remember if the edge is a ford (ugly to spend one bit for < .01% roads (number is guessed)).
- When routing over a ford, create an InstructionAnnotation that notifies about crossing a ford
- Show the annotation in the web interface?

So probably it would make sense to make this change in the DataflagEncoder. Could be also added to other Encoders, but not sure if this would take about to much storage in the graph?

**Comment by pyrog** [comment]
> A way I see to fix this would be to:
> * Allow routing through fords, [optionally] add a penalty?
> * When routing over a ford, create an InstructionAnnotation that notifies about crossing a ford
> * Show the annotation in the web interface?

👍

**Comment by karussell** [comment]
> Are there any news on this issue?
no
> Is this still something we want to do?
yes, sure :)

> So probably it would make sense to make this change in the DataflagEncoder. Could be also added to other Encoders, but not sure if this would take about to much storage in the graph?

Yes, maybe for now DataFlagEncoder and then the [storage requirement is less than one bit](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/routing/util/DataFlagEncoder.java#L129) :)

**Comment by karussell** [comment]
A note regarding a ford can now be given in the instructions, still for the DataFlagEncoder only.

To make this less of an issue what about the following:

 * use `access=yes` as new default for all encoders based on car on roads like primary&motorway&trunk&(secondary&tertiary) and also enable it for `hike`
 * additionally check regarding [flood_prone=*](https://wiki.openstreetmap.org/wiki/Key:flood_prone). 
 * for the foot encoder I'm still unsure if we should allow this

See also the discussion on the [OSM forum](https://forum.openstreetmap.org/viewtopic.php?id=58238)

**Comment by bohwaz** [comment]
Seems that the fords are still regarded as unpassable.

eg. https://graphhopper.com/maps/?point=-39.233217%2C175.509124&point=-39.233284%2C175.510883&locale=en-NZ&vehicle=foot&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale

Graphhopper doesn't want to cross the river, as a result the route is not making any sense.

Here in NZ it is very common to have to cross rivers on a hiking track, you can't really avoid them.

**Comment by mprins** [comment]
@bohwaz it does when you use the "hike" profile: https://graphhopper.com/maps/?point=-39.233217%2C175.509124&point=-39.233284%2C175.510883&locale=en-NZ&vehicle=hike&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale

**Comment by bohwaz** [comment]
Ah great! Though I don't understand how you made all those new buttons appear ^^

**Comment by mprins** [comment]
@bohwaz there's a button like "..."  next to the bike

**Comment by bohwaz** [comment]
Oh my! Thanks! Didn't look like a button though.

Sorry then, thanks for your help :)

**Comment by IknowJoseph** [comment]
Fords are now routable? For instance: http://www.openstreetmap.org/directions?engine=graphhopper_car&route=-1.2329%2C37.4654%3B-1.2346%2C37.4666#map=17/-1.23424/37.46722

**Comment by scaidermern** [comment]
> Fords are now routable? For instance: http://www.openstreetmap.org/directions?engine=graphhopper_car&route=-1.2329%2C37.4654%3B-1.2346%2C37.4666#map=17/-1.23424/37.46722

This is a [way](https://www.openstreetmap.org/way/546604754) tagged as ford=yes. I guess this gets handled differently or not at all.

**Comment by IknowJoseph** [comment]
Good spot, yes :)

Also applies to nodes tagged as ford=yes:

http://www.openstreetmap.org/directions?engine=graphhopper_car&route=1.19272%2C35.74388%3B1.18673%2C35.74231#map=17/1.18975/35.74259
http://www.openstreetmap.org/node/4401108509

**Comment by karussell** [comment]
Yes, we now use the block_fords=false option that was already there and will see if this gets better feedback or worse as the current state gave us too many reports (similar to our still conservative behaviour for ferries and gates)

**Comment by karussell** [comment]
There is now a prominent warning for all vehicles due to #1811, so we've finally made `block_fords=false` the default for all FlagEncoders.

Additionally there is a bug fix to still block fords if explicitly tagged.
