### ISSUE TITLE
Better support for osm file download on graphhopper.sh

### ISSUE THREAD

**Issue by HarelM** [graphhopper/graphhopper#2360]
**Describe the bug**
This is more of a feature request than a bug, I'll report it as though it was a bug, but I believe it's more of a feature request.
General motivation:
I have written a small docker container to serve up-to-date osm pbf files.
This docker and code can be found here:
https://github.com/IsraelHikingMap/OSMPbfWebAPI
It's very basic, it simply wraps the osm-c-tools with a RESTful web api service.
Now that I have this, I would like to point graphhopper import (or any other command that uses the -i flag) to use a file hosted in this container.
To cut a long story short: I would like to be able to specify any address (assuming it starts with `http`) to the -i flag so that graphhopper.sh will download a file and use it.
Having said that, I don't want to break backward compatibility (although I think the logic of file import is confusing when it comes to geofabrik, I needed to read this part a few times to understand it... if you want I can simplify the LINK variable logic with this issue as well, let me know...)

**To Reproduce**

Steps to reproduce the behavior. For examples:

1. Try and run the following command: `graphhopper.sh import http://www.example.com/my.osm.pbf`

Instead of a manual reproduction it would be even better to have a unit or integration test reproducing the issue.

**Expected behavior**
I expect the file to be downloaded and used by the import process

**System Information**

Any

**Screenshots & Logs**

N/A

I'll be happy to send a PR to resolve this. Please let me know what you decide.

**Comment by karussell** [comment]
The graphhopper.sh is something convenient I introduced in the early days to reduce the installation hassle to one line. But we do no longer use this and we think it belongs to some admin tooling outside of the scope of this project. Especially when new features like this arise I think this is more true. E.g. same applies for planet pbf or the new cool torrent feature.

I.e. we will remove graphhopper.sh script in the near future, but it is still available to everyone in git and we are happy to point to some externally maintained version of it.

**Comment by HarelM** [comment]
Thanks for the info. We will adjust accordingly, the only request I have is that you remove this and update the version number accordingly as this is a breaking change...
Thanks for the quick response!

**Comment by karussell** [comment]
Yes, this won't happen for 3.x
