### ISSUE TITLE
Cleanup ElevationProvider interface

### ISSUE THREAD

**Issue by otbutz** [graphhopper/graphhopper#2374]
The ElevationProvider interface carries methods which only make sense for certain implementations. We should move all methods except for `getEle(double, double)` into a fitting abstract baseclass for file/tile based providers.

**Comment by otbutz** [comment]
Based on @easbar draft in https://github.com/graphhopper/graphhopper/pull/2373#issuecomment-887282112

```java
public interface ElevationProvider {

    double getEle(double lat, double lon);

    default double getEle(ReaderNode node) {
         return getEle(node.getLat(), node.getLon());
    }

    boolean isInterpolating();
}
```

**Comment by easbar** [comment]
Yes. We might need `void release()` as well. Maybe `canInterpolate` instead of `isInterpolating`? And regarding the other setters I wonder why they even should be setters, they could just be constructor parameters. Anyway the most important part is cleaning up the interface.

**Comment by otbutz** [comment]
I'd rather replace `release()` with extending the `AutoCloseable` interface.

**Comment by easbar** [comment]
Ok, but maybe this is something for another issue, because we do not do this for our other resources (DataAccess etc.) yet either.
