### ISSUE TITLE
Increase coordinate precision

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#2393]
We currently use this conversion factor to read/write lat/lon coordinates to storage:

```java
    // +- 180 and +-90 => let use use 400
    private static final float DEGREE_FACTOR = Integer.MAX_VALUE / 400f; // this is around 5 million
```

Using the following experiment:

```java
        double[] vals = {-180, 180, 0, 0.1, 0.12, 0.123, 0.1234, 0.12345, 0.123456, 0.1234567, 0.002};
        for (double val : vals) {
            double res = Helper.intToDegree(Helper.degreeToInt(val));
            System.out.printf("%+013.8f\t%+013.8f\t%+013.8f\n", val, res, res - val);
        }
```

we get:

```shell
-180.00000000	-180.00000000	+000.00000000
+180.00000000	+180.00000000	+000.00000000
+000.00000000	+000.00000000	+000.00000000
+000.10000000	+000.09999983	-000.00000017 !
+000.12000000	+000.11999999	-000.00000001 !
+000.12300000	+000.12299996	-000.00000004 !
+000.12340000	+000.12339987	-000.00000013 !
+000.12345000	+000.12344998	-000.00000002 !
+000.12345600	+000.12345594	-000.00000006 !
+000.12345670	+000.12345668	-000.00000002 !
+000.12345678	+000.12345668	-000.00000010 !
+000.00200000	+000.00199992	-000.00000008 !
```

We see that for some values we do not receive the same value we put in. This might be unexpected in some cases. For example I ran into a failing unit test that depended on whether or not I flushed and loaded a test graph to/from disk or not before I used it. This is because BaseGraph keeps the map bounds in a `BBox` object and only writes to storage when we flush the graph. I wonder why we do not simply use 

```java
    private static final float DEGREE_FACTOR = 10_000_000;
```

instead. This will increase the precision and guarantee that the 7th decimal digit of the number we put in will be kept. I think this is a lot more intuitive and is also in line with the OSM convention that seven decimal digits are used: https://wiki.openstreetmap.org/wiki/Node. We can still cover the full range of possible values [-180, 180].

Using this factor we get:

```shell
-180.00000000	-180.00000000	+000.00000000
+180.00000000	+180.00000000	+000.00000000
+000.00000000	+000.00000000	+000.00000000
+000.10000000	+000.10000000	+000.00000000
+000.12000000	+000.12000000	+000.00000000
+000.12300000	+000.12300000	+000.00000000
+000.12340000	+000.12340000	+000.00000000
+000.12345000	+000.12345000	+000.00000000
+000.12345600	+000.12345600	+000.00000000
+000.12345670	+000.12345670	+000.00000000
+000.12345678	+000.12345670	-000.00000008  !
+000.00200000	+000.00200000	+000.00000000
```

So there is only a deviation between the input and output values for the eighth decimal place, which is not relevant in practice anyway.

**Comment by michaz** [comment]
Boah, danke. Irgendwie war die Tradition bei uns immer, das ginge überhaupt nicht.
