### ISSUE TITLE
Urban encoded value

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#2395]
It would be very useful to be able to determine whether or not a road is within city limits or not. Very unclear how we should do this yet, but maybe we can discuss this here. See, e.g. this and the following comments: https://github.com/graphhopper/graphhopper/issues/2392#issuecomment-925699492

**Comment by FranciscoBastos** [comment]
Hi,

My colleague Ana Rita and I are students at masters in software engineering at FEUP (https://paginas.fe.up.pt/~estudar/mesw/). As part of evaluating one of the curriculum units, we need to choose an open-source project and fix an issue. We would like to know if we could help with this issue?

**Comment by otbutz** [comment]
I'm not part of the GraphHopper team but contributions are always welcome :wink:

That being said, I expect the work on this particular ticket to be quite research intensive (which is not a bad thing).

**Comment by otbutz** [comment]
@easbar i think you *might* have linked the wrong issue :stuck_out_tongue_winking_eye:
