### ISSUE TITLE
Routing ignores `barrier=yes` with `access=no`

### ISSUE THREAD

**Issue by zstadler** [graphhopper/graphhopper#2400]
**Describe the bug**
The routing seems to ignore nodes with [`barrier=yes`](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dyes) and `access=no`. 

**To Reproduce**

Open [this graphhopper.com foot route](https://graphhopper.com/maps/?point=49.868827%2C8.477014&point=49.868426%2C8.473713&locale=en&elevation=true&profile=foot&use_miles=false&selected_detail=Elevation&layer=Omniscale) 
![image](https://user-images.githubusercontent.com/1304610/134823570-50880bd6-e653-4223-bd9a-3963a067fc9b.png)

Note that there [are two  `barrier=yes` `access=no` nodes](https://overpass-turbo.eu/s/1bvM) along this route.
![image](https://user-images.githubusercontent.com/1304610/134823606-abef294e-1603-4187-85b6-b1db02ba930a.png)

**Expected behavior**
No routing should go though any `barrier` node with `access=no`, unless applicable specific permissions are also present.

**System Information**
Graphhopper site

**Comment by karussell** [comment]
Yes, we should consider barrier=yes. Will do.

(but removed the bug label as this is not really a bug. A barrier=yes should be replaced by a more specific value, especially when it can be said that foot access is forbidden, i.e. someone must have more knowledge than satellite images.)

**Comment by zstadler** [comment]
Thanks for accepting this issue.

I think the description may have been unclear and an inaccurate title was used.

The request is for Graphhopper to 

1. Consider all nodes with a `barrier` tag
2. When the value of the `barrier` tag is known to Graphhopper, it would use the implied access characteristics. For example, according to [the wiki](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dbollard), a `barrier=bollard` tag implies `access=no`, `foot=yes`, and `bicycle=yes`.
3. Otherwise the `block_barriers` value will determine an `access=yes` or an `access=no` default.
4. The access characteristics would be updated according to the node's access-related tags, such as `access`, `bicycle`, `foot`, 'motor_vehicle`, etc.

This behavior is especially important given the above-mentioned request that mappers will refine `barrier=yes` tags with a more specific value. If the specific barrier on the ground does not fit any standard barrier value, the mapper may choose a user-defined value - unknown to Graphhopper. As a result, current Graphhopper will ignore the barrier regardless of `access=no` or any other access-related tags the node may have. 

To some extent, this has already happened. In #1468 `barrier=fence` nodes describe real-life situations, while [the wiki](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dfence) still says that a `barrier=fence` tag can only be used as a linear barrier.

**Comment by karussell** [comment]
> When the value of the barrier tag is known to Graphhopper, it would use the implied access characteristics.

We already do that. Some barriers block by default and some not. And which ones depends on car, foot and bike. E.g. for bollard we do not block by default for bike and foot, so this is fine.

> Otherwise, the block_barriers value will determine an access=yes or an access=no default.

What do you mean here? We removed the block_barriers config option when we introduced the simpler approach above.

**Comment by zstadler** [comment]
Thanks for the prompt response! I was not aware of that.

Please help me understand how the current approach handles unknown/user-defined `barrier` values.

What does Graphhopper do when it encounters a node on a highway that has an `access=no` and an unknown `barrier` value, such as `barrier=foobar`? 
What does Graphhopper do with a node that has just `barrier=foobar` and `motor_vehicle=no`?

**Comment by karussell** [comment]
For `foot` GraphHopper only has the fence barrier where it "blocks by default". This means if there are no access tags it will assume `access=no`. For all the other barriers it will be assumed `access=yes`. 

(For bike and car the barrier tags that assume "block by default" are different)

> What does Graphhopper do when it encounters a node on a highway that has an access=no and an unknown barrier value, such as barrier=foobar?

As soon as there is explicit tagging it will use that, i.e. in this case it would block access for foot.

> What does Graphhopper do with a node that has just barrier=foobar and motor_vehicle=no?

This depends on the vehicle. For `foot` it will not block. See all the tests in FootFlagEncoderTest.java.

**Comment by zstadler** [comment]
Thank you @karussell for the explanation and the fix!
