### ISSUE TITLE
API returning status code 0 

### ISSUE THREAD

**Issue by bencz** [graphhopper/graphhopper#2452]
**Describe the bug**
I performed a stress test on the API, after a certain number of requests the API stops working 

**To Reproduce**

Steps to reproduce the behavior. For examples:

1. checkout recent version of GraphHopper  ( i have used from the master branch )
2. link to your OSM pbf: https://download.geofabrik.de/south-america/brazil-latest.osm.pbf
3. include the config.yml you are using ( I'm using the default version from 'master' )
4. run I just changed the parameters `-Xmx and -Xms` inside graphhopper.sh to `-Xmx10000m -Xms10000m`, command used to run: `./graphhopper.sh --host 0.0.0.0 web brazil-latest.osm.pbf`

I build a small C# program ( in attachment  ) with a codebase with geo-locations, just start the GraphHopper on localhost in port 8989 and execute the C# program, after a while, the API will start to return status code 0

[TesteStressGraphHopper.zip](https://github.com/graphhopper/graphhopper/files/7444812/TesteStressGraphHopper.zip)

**Expected behavior**
Return some error code != 0, if has some real error

**System Information**
GraphHopper version, commit: https://github.com/graphhopper/graphhopper/commit/b62d16131b20c6896e2974a4e389796026d8a63c

JVM: 
```
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode)
```

OS:
```
hostnamectl
   Static hostname: instance-20211004-1143
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 54e45f38866f41108af019b3b298aa32
           Boot ID: 500fd52e9ff74171adbc5a253bb407ae
    Virtualization: kvm
  Operating System: Ubuntu 20.04.3 LTS
            Kernel: Linux 5.11.0-1019-oracle
      Architecture: arm64
``

**Comment by karussell** [comment]
What does the graphhopper log say? Are you sure we return an http error code of 0? If you reduce parallelism will the error codes disappear?
