### ISSUE TITLE
EdgeIteratorStateImpl::set appears to not actually encode/bit-shift the values when used with RAMDirectory/procedurally-generated graph

### ISSUE THREAD

**Issue by ahelmbock** [graphhopper/graphhopper#2459]
EdgeIteratorStateImpl::set appears to not actually encode/bit-shift the values when used with RAMDirectory/procedurally-generated graph.  I am running a unit test (see below for code) that creates a RAMDirectory, creates a GraphHopperStorage, grabs the first edge encoder, and creates a filter.  I then create a couple of edges, and attempt to set one edge to RoadClass.MOTORWAY and one to RoadClass.TERTIARY.  When I look at the EnumEncodedValue<RoadClass>, I see an encoded enum with all the values I expect (including the bit-shifting information), but when I set the flags on the edge, the encoding doesn't encode -- it merely places the ordinal number in the flags.  (In my case it sets the flags to "2," rather than to the bit-shifted value of 2 bit-shifted by what's in the enum's data.  As a result, when I later call filter.accept() on an edge that should be rejected, it sees the "2" instead of the correct value, and accepts the edge, rather than rejecting it.

**To Reproduce**

The code (as a DOCX as JAVA is not accepted for attachment)....
[GraphHopperBug.docx](https://github.com/graphhopper/graphhopper/files/7499785/GraphHopperBug.docx)

Contained in this text are the test java, the filter java, the properties java, and the application yml that sets the properties java.

I think the issue is that in the EnumEcodedValue class that this code isn't right:

    public final void setEnum(boolean reverse, IntsRef ref, E value) {
        int intValue = value.ordinal();
        super.setInt(reverse, ref, intValue);
    }

I think this isn't bit-shifting....

Or maybe I am mis-reading the system, but it seems that the following code should set it bit-shifted and not raw:

        Directory dir = new RAMDirectory();
        graph = new GraphHopperStorage(dir, EncodingManager.create(new CarFlagEncoder()), false).create(100);

        encoder = graph.getEncodingManager().fetchEdgeEncoders().get(0);
        filter = new GeoIngestionGraphHopperFilter(EdgeFilter.ALL_EDGES,
                encoder.getEnumEncodedValue(RoadClass.KEY, RoadClass.class),
                encoder.getEnumEncodedValue(RoadEnvironment.KEY, RoadEnvironment.class),
                geoIngestionProperties.getFilterAvoidances());

        EnumEncodedValue<RoadClass> encodedRoadValues = filter.getRoadClassEncodedValues();

        edge0 = graph.edge(0, 1).setName("motorway");
        edge0.set(encodedRoadValues, RoadClass.MOTORWAY);

And that edge0, should be set to "motorway"....

Anyway, I am not blocked by this -- I can load the data from an OSM file instead and test the filtering on that data, it just appears that flag-setting a procedurally-generated (using the low-level API) graph appears to not work correctly.

(And yes, this is very obscure/deep-in-the-weeds, and unlikely to be used by anyone doing routing or isochrones).

**Comment by easbar** [comment]
Can you fork the repository, commit the code that you think is not working and link to it here?

**Comment by ahelmbock** [comment]
Note we are using 4.x GraphHopper branch

**Comment by ahelmbock** [comment]
I am unsure of the right solution for fixing this (although I could try and figure out how it works correctly for "loaded from OSM file" but not from "created on the fly."

**Comment by easbar** [comment]
If you don't know how to fork the repo and create a branch, maybe just upload the code you put into this docx file as a gist: https://gist.github.com/ ?
