### ISSUE TITLE
Requests with custom model for turn_costs enabled profiles take a long time

### ISSUE THREAD

**Issue by IldarKhayrutdinov** [graphhopper/graphhopper#2476]
### Description

Request with custom model took a very long time.

URL: https://graphhopper.com/maps/?point=59.832395%2C30.193429&point=55.938433%2C37.491875&locale=ru-RU&elevation=true&profile=car&use_miles=false&selected_detail=distance&layer=Omniscale

Distance between way points about 700 km.

Without custom model the request is very fast. But, when enabling this simply custom model request took about 10 seconds:
```
{
 "priority": [
  {
   "if": "toll != NO",
   "multiply_by": 0.0
  }
 ]
}
```

  <details>
    <summary>Screenshot </summary>

![image](https://user-images.githubusercontent.com/29858598/142715723-e3fa21af-b74f-4359-8f88-57e0f35993a9.png)

  </details>

### My investigation

I did local tests for `LM` profiles with `custom weighting`:
1. tests profiles with enabled and disabled `turn_costs`
2. requests with `custom model` and without
3. distance between test way points about 500 - 800 km.

I found out that:
1. requests without `custom model` don't take a long time, both enabled and disabled `turn_costs`
2. requests with `custom model` don't take a long time for disabled `turn_costs`
2. requests with `custom model` and enabled `turn_costs` take a very long time

I tried different settings, increase `routing.lm.active_landmarks`, `prepare.lm.threads`, `prepare.lm.landmarks` but it didn't get better.

### Summary

So, requests over 500 km with `custom model` (on request body) can take a very long time for `turn_costs` enabled profiles.

**Comment by karussell** [comment]
> requests with custom model and enabled turn_costs take a very long time

Can you share your config.yml, the JVM version (incl. java parameters), GH version, and the exact POST request that takes long? How long exactly?

And you mean when you disabled turn_costs (and still specify the same custom model) it was fast again? How fast exactly?

**Comment by IldarKhayrutdinov** [comment]
@karussell Sure, I'll answer you later. The problem also is reproduced on graphhopper.com/maps:

https://graphhopper.com/maps/?point=59.832395%2C30.193429&point=55.938433%2C37.491875&locale=ru-RU&elevation=true&profile=car&use_miles=false&selected_detail=distance&layer=Omniscale

Custom model:
```

{
 "priority": [
  {
   "if": "toll != NO",
   "multiply_by": 0.0
  }
 ]
}
```

**Comment by karussell** [comment]
And you get a fast response for this route when the turn_costs is disabled?

The problem here is probably more that the custom model leads to a route that deviates too much from the original route (for which the LM preparation was made). I.e. it has to visit more nodes and is slower. To fix this you could include the custom model in the LM preparation or create multiple LM preparations.

**Comment by IldarKhayrutdinov** [comment]
> And you get a fast response for this route when the turn_costs is disabled?

Sorry, yes, when disabled `turn_costs` the response is fast. 

> The problem here is probably more that the custom model leads to a route that deviates too much from the original route (for which the LM preparation was made). I.e. it has to visit more nodes and is slower. To fix this you could include the custom model in the LM preparation or create multiple LM preparations.

Maybe, a picture with overlaying with `custom model` and without:

  <details>
    <summary>spoiler</summary>
 
![22](https://user-images.githubusercontent.com/29858598/142724921-759caf01-55d9-473f-b1fe-90da24242175.png)

  </details>

**Comment by easbar** [comment]
Can you try `lm.disable=true`? I wonder if in this case A* would be faster than LM.

**Comment by IldarKhayrutdinov** [comment]
I provided new tests on local machine Windows 10 16Gb RAM.

1. Download latest stable release [graphhopper-web/4.0](https://mvnrepository.com/artifact/com.graphhopper/graphhopper-web/4.0).
2. Download [openjdk11](https://adoptium.net/releases.html?variant=openjdk11&jvmVariant=hotspot) JRE Windows x64.
3. Download [russia-latest.osm.pbf](https://download.geofabrik.de/russia.html) (~3Gb).
4. Download [4.0/config-example.yml](https://github.com/graphhopper/graphhopper/blob/4.0/config-example.yml) as basis. 
My modified config: [config-example.zip](https://github.com/graphhopper/graphhopper/files/7595583/config-example.zip)
5. Run `jdk-11.0.13+8-jre\bin\java.exe -Xms3G -Xmx12G -jar graphhopper-web-4.0.jar server config-example.yml`

<details>
<summary>Shortly, the profiles definition: </summary>

```
profiles:
- name: car
  vehicle: car
  weighting: fastest
  turn_costs: false
  
- name: car_with_turn_costs
  vehicle: car
  weighting: fastest
  turn_costs: true
  
- name: custom_car
  vehicle: car
  weighting: custom
  custom_model_file: empty
  turn_costs: false
  
- name: custom_car_with_turn_costs
  vehicle: car
  weighting: custom
  custom_model_file: empty
  turn_costs: true
```
</details>


#### Test requests:

  <details>
    <summary> 1) empty `custom_model` </summary>

```
{
    "points": [
        [
            30.38269,
            60.116882
        ],
        [
            38.309326,
            52.809403
        ]
    ],
    "points_encoded": false,
    "profile": "custom_car", // car, car_with_turn_costs, custom_car, custom_car_with_turn_costs (see different rows)
    "ch.disable": true,
    "lm.disable": false
}
```

</details>
<details>
<summary>2) `custom_model` with `road_class` statement</summary>

```
{
    "points": [
        [
            30.38269,
            60.116882
        ],
        [
            38.309326,
            52.809403
        ]
    ],
    "custom_model": {
        "priority": [
            {
                "if": "road_class == TRUNK",
                "multiply_by": 0.8
            },
            {
                "if": "road_class == PRIMARY",
                "multiply_by": 0.7
            },
            {
                "if": "road_class == SECONDARY",
                "multiply_by": 0.6
            }
        ]
    },
    "points_encoded": false,
    "profile": "custom_car",    // see different rows
    "ch.disable": true,
    "lm.disable": false
}
```
</details>

<details>
<summary>3) `custom_model` with `toll` statement</summary>

```

{
    "points": [
        [
            30.38269,
            60.116882
        ],
        [
            38.309326,
            52.809403
        ]
    ],
    "custom_model": {
        "priority": [
            {
                "if": "toll != NO",
                "multiply_by": 0.0
            }
        ]
    },
    "points_encoded": false,
    "profile": "custom_car", // see different rows
    "ch.disable": true,
    "lm.disable": false
}
```

</details>

#### Results table:

| profile \ request                                  | 1) empty `custom_model` | 2) `custom_model` with `road_class` statement | 3) `custom_model` with `toll` statement |
|----------------------------------------------------|-------------------------|------------------------------------------|-----------------------------------------|
| `car`                                              | 50 - 60 ms              | -                                        | -                                       |
| `car_with_turn_costs`                              | 80 - 95 ms              | -                                        | -                                       |
| `custom_car`                                       | 50 - 70 ms              | 330 - 360 ms                             | 1200 - 1400 ms                          |
| `custom_car_with_turn_costs`                       | 80 - 100 ms             | 750 - 800 ms                             | 3300 - 4500 ms                          |
| `custom_car_with_turn_costs` and `lm.disable=true` |                         |                                          | 4500 - 5000 ms                          |

The `road_class` statement is milder than `toll`.

The new test route is longer than the one for which I opened the issue, but it's closer to my real production.  
On `graphhopper` demo server the requests with custom model is aborted at timeout:
https://graphhopper.com/maps/?point=60.116882%2C30.38269&point=52.809403%2C38.309326&locale=ru-RU&elevation=true&profile=car&use_miles=false&selected_detail=Elevation&layer=Omniscale

**Comment by IldarKhayrutdinov** [comment]
It would be useful to be able to set a timeout for requests, so that the `graphhopper` would stop calculating the route after timeout. The client can set a timeout for http request, but `graphhopper` doesn't stop calculating and it's a heavy load on server.

**Comment by karussell** [comment]
Thanks for the details!

And a longer computation time for ch.disable=true and turn_costs=true is expected. It can be up to 2x slower.

> It would be useful to be able to set a timeout for requests, so that the graphhopper would stop calculating the route after timeout. The client can set a timeout for http request, but graphhopper doesn't stop calculating and it's a heavy load on server.

Yes, see #2349. 

> The road_class statement is milder than toll.

I think, the reason here is what I stated above: the road_class change will cause the route to deviate more from the optimum so that the precomputed LM preparation isn't properly used.

My suggestion here is to use separate LM preparations. E.g. one for "car" and one for "car_avoid_motorway" that includes the necessary custom_model. Then the car_avoid_motorway profile can still be further modified via a custom_model at query time.

**Comment by IldarKhayrutdinov** [comment]
Thanks, @karussell!

Then it's within the norm. 
The solution with separate LM profiles is works, I have already tried it, but it's requires more memory (the more profiles, the more memory).

**Comment by IldarKhayrutdinov** [comment]
@karussell could you give advice on profiles?

From config-example about Hybrid mode:

```
  # Advanced usage: It is possible to use the same preparation for multiple profiles which saves memory and preparation
  # time. To do this use e.g. `preparation_profile: my_other_profile` where `my_other_profile` is the name of another
  # profile for which an LM profile exists. Important: This only will give correct routing results if the weights
  # calculated for the profile are equal or larger (for every edge) than those calculated for the profile that was used
  # for the preparation (`my_other_profile`)
```

I have `CustomProfile1` profile also I want a custom profile `CustomProfile1WithToll` which is `CustomProfile1` + `toll statement`.
How can I configure these 2 profiles as written in `Advanced usage`?

**Comment by easbar** [comment]
What is it that you do not understand here? Or do you want to do this using the Java API? For the latter see this example:

https://github.com/graphhopper/graphhopper/blob/b65d9413e2dc29b662a1bb2db146b536471167a9/web/src/test/java/com/graphhopper/http/resources/RouteResourceTurnCostsTest.java#L52-L80

**Comment by IldarKhayrutdinov** [comment]
@easbar thanks, yes, it looks like this is what I need. Can I do this in the config file?

**Comment by easbar** [comment]
Yes :)

> To do this use e.g. `preparation_profile: my_other_profile` where `my_other_profile` is the name of another
  # profile for which an LM profile exists.
