### ISSUE TITLE
Issue while try running on android this app

### ISSUE THREAD

**Issue by red0bear** [graphhopper/graphhopper#2479]
Am trying using your snaphot 5.0 on android but it gives error; Am already did a example on netbeans but trying do something on android with package graphhopper-tools-5.0-SNAPSHOT-jar-with-dependencies.jar. Am aware you already not giving support more to android , may be i could using those packages more simple with a work around.   

Errors: 
I/art: Rejecting re-init on previously-failed class java.lang.Class<com.graphhopper.GraphHopper$$ExternalSyntheticLambda0>

W/art: Failed to open zip archive '/system/framework/qcom.fmradio.jar': I/O Error
W/System.err: log4j:ERROR Could not parse url [jar:file:/data/app/com.expertise.appmapstreetview-2/base.apk!/log4j.xml].
    javax.xml.parsers.ParserConfigurationException: No validating DocumentBuilder implementation available
W/System.err:     at org.apache.harmony.xml.parsers.DocumentBuilderFactoryImpl.newDocumentBuilder(DocumentBuilderFactoryImpl.java:61)

**Comment by karussell** [comment]
Please use our [public forum](https://discuss.graphhopper.com/) for questions and be more specific what you want to achieve. Also see #1940.
