### ISSUE TITLE
Routing on highway emergency exit without access tag

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#2484]
Instead of going to the next official exit, GH is taking an emergency exit: 
https://graphhopper.com/maps/?point=45.400303%2C5.464877&point=45.400156%2C5.464169

The wiki suggests an access=no in the wiki and this tag is missing: https://www.openstreetmap.org/way/745661088

But as this is a bit dangerous tagging mistake and similar mistakes are already made in the same area (and other routing engines assume access=no by default it seems) we should probably also assume a "block access of this road by default".

**Comment by otbutz** [comment]
Judging from the wiki information we should treat the combination `highway=service`+`service=emergency_access` as `access=no`.

> Consider adding access permissions to the highway, such as `access=no` and `emergency=designated`, **in case a data consumer understands access tags but not `service=emergency_access`.**
