### ISSUE TITLE
Isochrone shapes depend on distance_limit vs. time_limit selection

### ISSUE THREAD

**Issue by Rikuoja** [graphhopper/graphhopper#2488]
**Describe the bug**
Isochrone triangulation in areas with sparse/unaccessible network may return wildly different shapes depending on the selection of `distance_limit` vs. `time_limit`, with all other parameters being identical.

-Isochrones calculated with `distance_limit` may extend far into unaccessible areas, so it seems some nodes outside the area are omitted when doing the triangulation for the final isochrone shape.

-Isochrones calculated with `time_limit` more closely correspond to desired shapes, so it seems more nodes outside the area are included when doing the triangulation for the final isochrone shape.

**To Reproduce**

Select a point with sparse road network around it. An airport terminal is a good candidate. Calculate isochrones with hiking profile

```
    - name: hike
      vehicle: hike
      ch.disable: true
      weighting: shortest
```

 using both `distance_limit` and `time_limit`, e.g. with distances from 100 to 1000 meters (10 buckets) and time limit 1 to 10 minutes (10 buckets).

**Expected behavior**
Isochrone shapes should look similar.

**System Information**

Ubuntu 20.04.3 LTS 
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
graphhopper-web-4.0.jar

**Screenshots & Logs**

Example hiking isochrones from Helsinki Airport railway station underground entrances with distances from 100 to 1000 meters (10 buckets) and time limit 1 to 10 minutes (10 buckets).

Red isochrones = time limit 1 to 10 minutes. Blue isochrones = distance limit 100 to 1000 meters.

![image](https://user-images.githubusercontent.com/9367712/145560787-704826a2-b670-4874-a4ec-a430c8367634.png)

**Comment by Rikuoja** [comment]
Most likely this is because the shortestPathTree distance limit depends on the limit type? https://github.com/graphhopper/graphhopper/blob/master/web-bundle/src/main/java/com/graphhopper/resources/IsochroneResource.java#L120

**Comment by Rikuoja** [comment]
Perhaps a quick fix for me is to manually adjust the distance limit.

**Comment by Rikuoja** [comment]
Adjusting the distance limit so that the distance walked more closely corresponds to the time walked (i.e. 2000 -> 200) solves the problem.

Wonder if the distance limit should be dependent on the profile? The profile speed surely determines how far you can travel in given time, and the current default of 
`shortestPathTree.setDistanceLimit(limit + Math.max(limit * 0.14, 2_000))`
probably corresponds to automobile speeds?

That results in ugly isochrones for lower speed modes such as walking.

**Comment by michaz** [comment]
Those terms (`+ Math.max(limit * 0.14, 2_000)` and `+ Math.max(limit * 0.14, 200_000)`) are just slack -- we need to build the shortest path tree up to a somewhat _higher_ value than the value we want to draw the isoline for.

You can safely try to add a higher value there. It could improve corner cases, but shouldn't falsify any results that were already good.

In general: Yes, isochrones and "isolines by distance" (not really isochrones) can have different shapes. I'd expect distance-isolines to be "rounder".

**Comment by Rikuoja** [comment]
@michaz My point here is that in this case, *lowering* those values improves corner cases.

The default distance value here is selected on the assumption that the user wants to see isodistance lines that look like isochrones at automotive speed; i.e. looking at the shortest path tree a bit further than they would when walking.

So perhaps this should be considered as an example that a larger shortest path tree is not always better, as it will inevitably result in more isodistance lines/isochrones encroaching on areas that cannot be accessed.

**Comment by Rikuoja** [comment]
In general, on automotive speeds, obviously, larger errors are to be allowed in isochrone boundaries than on a lower speed. It is a question of scale.

An airport or a water body belonging to an isochrone does not matter much with automotive distances, as the isochrones are much bigger; with walking distances and human scale, an isochrone extending far into a water body or other inaccessible area is a more glaring error, as the rest of the polygon can be very small in comparison. So it is good to know that currently, the isodistance lines are optimized for larger polygons and may contain larger errors at the boundaries.

**Comment by michaz** [comment]
> So it is good to know that currently, the isodistance lines are optimized for larger polygons and may contain larger errors at the boundaries than walking isochrones.

Yes, that's definitely true.

You're not 100% right about what that particular parameter does, though. If your isoline gets better by reducing it, it's.. maybe not a _coincidence_, but it doesn't naturally follow from what the code is for.

**Comment by Rikuoja** [comment]
> You're not 100% right about what that particular parameter does, though. If your isoline gets better by reducing it, it's.. maybe not a coincidence, but it doesn't naturally follow from what the code is for.

Ah yeah, I guess in this case the isoline boundary is limited by the last accessible node in a given direction, if no nodes could be found in the SPT further in the same direction? So in cases where the area past the last accessible node is always inaccessible, that makes the isoline correspond to reality.
