### ISSUE TITLE
Connection not found when query point snaps to tower node with curbside constraint

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#2502]
This route yields 'connection not found':

https://graphhopper.com/maps/?point=28.772512%2C-81.611509&point=28.7809%2C-81.630349&locale=en-US&elevation=true&profile=car&curbside=right&curbside=right&use_miles=false&selected_detail=Elevation&layer=Omniscale

It works the other way around:

https://graphhopper.com/maps/?point=28.7809%2C-81.630349&point=28.772512%2C-81.611509&locale=en-US&elevation=true&profile=car&curbside=right&curbside=right&use_miles=false&selected_detail=Elevation&layer=OpenStreetMap

The query point at the end of Town Hill Blvd is a tower snap and for some reason the curbside constraint restricts the routing algorithm in a way such that no path is found.

**Comment by easbar** [comment]
This is a rather special case:

![image](https://user-images.githubusercontent.com/17603532/146600081-d94c69ac-fcaf-4028-9e51-fd0050c427bb.png)

There is a one-way road that ends at a gate after a few meters. We prevent snapping to this little one-way dead end but for some reason it is not excluded by the subnetwork removal.

**Comment by easbar** [comment]
The subnetworks aren't removed, but we forgot considering the subnetwork EV when evaluating the curbside constraints.

**Comment by karussell** [comment]
Thanks! Maybe the subnetwork handling is a bit too loosely coupled.

**Comment by easbar** [comment]
Yes, it should probably go into weighting just like access flags (#1835)

**Comment by karussell** [comment]
Yes. Also related: #2343.

Still it is a bit nice (performance-wise?) that we do not need to consider them in the routing at the moment :)

But yes, having it directly in the Weighting would have the additional benefit of switching it off (per request) to explicitly route in a subnetwork. At least for debugging this would be nice to have.

**Comment by easbar** [comment]
Yes, this is true. Currently we do not check for subnetworks in the routing algorithms, because either they are not reachable at all and the algorithms do not even explore the corresponding edges (real subnetworks), or they are reachable from one side, but won't lead anywhere (one way subnetworks). We should check how critical this is for performance and decide whether it is worth the complexity not to include the check in the weighting directly.
