### ISSUE TITLE
In some scenario snap_prevention=ferry does not work

### ISSUE THREAD

**Issue by altair86** [graphhopper/graphhopper#2510]
**Describe the bug**
In some scenario snap_prevention=ferry does not work

**To Reproduce**
Example:
https://graphhopper.com/maps/?point=50.088649%2C82.266312&point=50.250718%2C82.356262&locale=ru&elevation=true&vehicle=bike&snap_prevention=ferry&use_miles=false&selected_detail=Elevation&layer=Omniscale

**Expected behavior**
We need to route through Ust-Kamenogorsk

**Comment by karussell** [comment]
snap_prevention is not avoid excluding ferry from the way. Please read the documentation about custom_model where this is possible.
