### ISSUE TITLE
Do not remove waypoints when instructions are disabled

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#2515]
Currently the snapped waypoint coordinates might be removed by the path simplification when instructions are disabled.

https://discuss.graphhopper.com/t/all-snapped-waypoints-is-not-present-in-points/7092/13

**Comment by easbar** [comment]
Fixed in #2742 @bdDavin, @IldarKhayrutdinov, and @navhaxs

**Comment by IldarKhayrutdinov** [comment]
@easbar thanks!
