### ISSUE TITLE
Headings are ignored apparently

### ISSUE THREAD

**Issue by calvinkehl** [graphhopper/graphhopper#2529]
When I use headings and heading_penalty in my request, it doesn't change anything. Both in the POST request from our app and in the map i.e. https://graphhopper.com/maps/?point=48.863176%2C9.177833&point=48.856118%2C9.176395&locale=de-DE&elevation=true&profile=car&headings=[10]&heading_penalty=3600&ch_disable=true&use_miles=false&selected_detail=Elevation&layer=Omniscale
In my app I use `GHRequest.setHeadings(headings);` and `GHRequest.putHint("heading_penalty", headingPenalty);`

Is this a known issue or user failure?

**Comment by karussell** [comment]
For a GET request you need to use `heading`: https://graphhopper.com/maps/?point=48.863176%2C9.177833&point=48.856118%2C9.176395&profile=car&heading=10&heading_penalty=3600&ch.disable=true

For questions please use [our forum](https://discuss.graphhopper.com/).

**Comment by calvinkehl** [comment]
Thank you for the quick answer and correcting my GET request test.

Still, the POST request doesn't work apparently (that's why I filed an issue). I looked into the `GraphHopperWeb.setPostRequest(true).route(myReq);` method and couldn't find anything heading related.

**Comment by easbar** [comment]
This is because of #2009

**Comment by calvinkehl** [comment]
Ah, thank you. I see this exists since 2 years without anyone working on it, is there a possibility to increase the priority of that bug? Because one of our customers has massive problems with the navigation and often due to this.

**Comment by easbar** [comment]
I'll fix it

**Comment by calvinkehl** [comment]
Thank you so much!

**Comment by easbar** [comment]
The fix will be included in the 5.0-pre2 release and later releases of course.
