### ISSUE TITLE
Location index snaps to the opposite border of the map

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#2556]
The coordinate of the green marker snaps to the location of the red marker.

![image](https://user-images.githubusercontent.com/17603532/162438555-fe0cc0e3-59c9-4a5f-82c3-adfe3992c997.png)

Using `bayern-190101.osm.pbf` from Geofabrik: https://download.geofabrik.de/europe/germany/bayern-190101.osm.pbf

**Comment by easbar** [comment]
This screenshot makes it a bit more clear:

![image](https://user-images.githubusercontent.com/17603532/162438868-5a2d6219-f959-4349-b4ec-44dacc7b0b45.png)

**Comment by michaz** [comment]
Ah yes, I think this was me. Short answer: The LocationIndex is a torus, and this needs an extra "if".

**Comment by easbar** [comment]
Thanks!
