### ISSUE TITLE
LMApproximator does not yield feasible heuristic

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#2584]
The A* heuristic (h) must fulfill two properties so we can use it the way we use it:

1) The heuristic must be 'admissible', i.e. it must never overestimate the distance to the target
2) The heuristic must be 'feasible' (or 'consistent' or 'monotone'), i.e. the triangle inequality must be fulfilled: For every edge `u->v` it must hold that `w(u,v) + h(v) >= h(u)`. This is because running A* with modified tentative weights, where we add the heuristic to the weight of each entry in the priority queue, is equivalent to running Dijkstra with a modified weighting `w_red(u,v) := w(u,v) - h(u) + h(v)`. And since Dijkstra requires the weighting to be positive we have `w_red >= 0`. 

The first property follows from the second, but not the other way around! I added a test that shows that 1) seems to be OK, but the `LMApproximator` violates 2) in some cases, see [here](https://github.com/graphhopper/graphhopper/blob/6fe4bffff6d49645c74b7c22ee1990ab7b9e77b9/core/src/test/java/com/graphhopper/routing/lm/LandmarkStorageTest.java#L247-L278)
This is most likely due to the rounding of the LM weights and we need to make sure that 2) still holds true after the rounding.

Very likely this is related to #1971.

**Comment by michaz** [comment]
Writing down what we already discussed on Slack:
It's true that LMApproximator _by itself_ is not 'feasible'. But my impression when I was working on this was that it's just not possible to make it 'feasible' without exact arithmetic.

With limited-precision numbers, I think the code that calls LMApproximator must account for its precision, and give all those inequalities some slack. (Like you would do in a JUnit test with `double` numbers.)

`LMApproximatorTest` does this, and the part in our A* routing where that inequality is used does it, too.

**Comment by michaz** [comment]
It's still infeasible though.

**Comment by easbar** [comment]
Let `u` be any node, `t` the target node and `LM` a landmark node. Then according to the triangle inequality we have for the distances between these nodes:

```
d(u, t) + d(t, LM) >= d(u, LM)
```

and it follows that 

```
d(u, t) >= d(u, LM) - d(t, LM) =: h(u)
```

The heuristic `h(u)` is feasible as:

```
d(u1, u2) + h(u2) = d(u1, u2) + d(u2, LM) - d(t, LM) >= d(u1, LM) - d(t, LM) = h(u1)
```

Now let `v` be a virtual node on an edge `A-B`. Again according to the triangle inequality:

```
d(v, t) + d(t, LM) >= d(v, LM)
```

Ignoring turn costs between the virtual edges at `A` and `B` we can split the distance `d(v, LM)` into a short distance from the virtual node to `A` or `B` and the shortest path distance from `A/B` to the landmark:

```
d(v, LM) = min(d(v, A)+d(A, LM), d(v, B)+d(B, LM))
```

so it follows that:

```
d(v,t) >= min(d(v, A)+d(A, LM), d(v, B)+d(B, LM)) - d(t, LM) =: h(v)
```

This heuristic for `v` is feasible. Assume the first term is minimal for node A (it it's not we can do the same for B):

```
h(v) = d(v, A) + d(A, LM) - d(t, LM) = d(v, A) + h(A)
```

So for virtual nodes we need to first find the neighbor real node for which `d(v, .) + d(., LM)` is minimal and then subtract `d(t, LM)` from this. Note that if `LM == t` we have:

```
h(v) = min(d(v, A) + d(A, t), d(v, B) + d(B, t))
h(A) = d(A, t)
h(B) = d(B, t)

==> h(v) = min(d(v, A) + h(A), d(v, B) + h(B))
```

i.e. the heuristic of the virtual node would be just the minimum sum of the distance from the virtual node to the neighbor real node and the heuristic of the neighbor real node. But in general (`t != LM`) this is wrong and we have to determine the heuristic of the virtual node as I wrote above.

**Comment by easbar** [comment]
Btw, I think the old implementation is wrong because it sets `h(v)=0` which means it is not feasible as `d(A, v) + h(v) = d(A, v)` and `d(A, v) >= h(A)` is certainly not always fulfilled, e.g. when `d(A, v)` is a short virtual edge and `h(A)` is rather large (far away from the target).

The fix in https://github.com/graphhopper/graphhopper/commit/6d05d52da46e68b4a4cdc0129785eb57822515a3 is sometimes right as it takes the closer of the two nodes A and B (say it is A) and sets `h(v) = d(v, A) + h(A)`. This is right when `d(v, A) + d(A, LM) < d(v, B) + d(B, LM)` and wrong otherwise.
