### ISSUE TITLE
Partial mapmatching

### ISSUE THREAD

**Issue by otbutz** [graphhopper/graphhopper#2621]
Currently mapmatching is either hit or miss as we fail the request once we detect a broken sequence:

https://github.com/graphhopper/graphhopper/blob/83be9d61164c0f947674b2dc7b9095e4c4dfb8d6/map-matching/src/main/java/com/graphhopper/matching/MapMatching.java#L363-L365

But it would be nice to have an additional best-effort mapmatching endpoint. If the sequence is broken at point X just restart the mapmatching from the next point. The resulting GPX would have one or multiple routes.

Glimpsing over the code i noticed that it might be possible to get the sequence up until the point where it's broken:

https://github.com/graphhopper/graphhopper/blob/83be9d61164c0f947674b2dc7b9095e4c4dfb8d6/hmm-lib/src/main/java/com/bmw/hmm/ViterbiAlgorithm.java#L239-L248

**Comment by michaz** [comment]
Ok there isn't such a thing as a broken sequence anymore, there's just maxVisitedNodes

**Comment by otbutz** [comment]
What happens for a route that spans two isolated subgraphs? Wouldn't we just throw an exception? Ideally, I would like to get two partial matches, one for each subgraph.

**Comment by michaz** [comment]
Ok I see. I'm just doing a map-matching round, will keep it in mind.

**Comment by otbutz** [comment]
> will keep it in mind.

Did you? :smile:
