### ISSUE TITLE
Path is not really optimal for bicycle/foot

### ISSUE THREAD

**Issue by iampradip** [graphhopper/graphhopper#2641]
In straight paths it goes to select streets instead.

[https://i.imgur.com/Y0svtei.png](https://i.imgur.com/Y0svtei.png)

**Comment by easbar** [comment]
That really depends on your definition of 'optimal'. Is it optimal to take the shortest path? Or is it optimal to avoid the main road as a pedestrian/cyclist? Do you have local knowledge about this particular street? Can you share a direct link to this route on graphhopper.com/maps/? This makes it easier to understand the issue.

**Comment by iampradip** [comment]
https://graphhopper.com/maps/?point=22.461666%2C70.049633&point=22.465245%2C70.052433&locale=en-US&elevation=true&profile=foot&use_miles=false&selected_detail=Elevation&layer=Omniscale

Local knowledge - yes. Everyone on foot uses straight path on this road.

**Comment by iampradip** [comment]
I think algorithm is trying to avoid main road but it's common here to use such roads for foot or bicycle travel.

**Comment by easbar** [comment]
Ok, thanks. The road is tagged as `secondary` while the other one is `residential` and you are right that the router is trying to avoid the `secondary` road. In most cases this also makes sense, doesn't it? If this `secondary` road is still safe for pedestrians it probably has sidewalks? But the road is not tagged accordingly. Would you suggest changing the algorithm or do you think this is rather a special case (in your region)?

**Comment by iampradip** [comment]
It's pretty much same all over city, maybe other cities and states in India also. A checkbox/flag to not avoid any roads (except highway) might be nice.

**Comment by iampradip** [comment]
And there is no sidewalk made but there is often some 1 meter empty space in both sides of road so it's pretty much safe to walk.

**Comment by easbar** [comment]
> And there is no sidewalk made but there is often some 1 meter empty space in both sides of road so it's pretty much safe to walk.

Ok you should check the OSM wiki/community how this should be tagged then.

> It's pretty much same all over city, maybe other cities and states in India also. A checkbox/flag to not avoid any roads (except highway) might be nice.

If this really was something specific for India we could account for this in IndiaCountryRule maybe (not yet, but maybe in the future). Regarding the checkbox: There is actually a much more powerful feature, see the 'custom' button and here: https://github.com/graphhopper/graphhopper/blob/master/docs/core/custom-models.md

**Comment by iampradip** [comment]
Cool
