### ISSUE TITLE
Graph after reading OSM is empty

### ISSUE THREAD

**Issue by wuzhijin98** [graphhopper/graphhopper#2643]
After reading the OSM file, it displays: java.lang.runtimeexception: graph after reading OSM must not be empty.

I also noticed a line: c.g.reader.osm WaySegmentParser - pass1 - finished, processed ways: 1? 963, accepted ways: 0, way nodes: 0, relations: -1, totalMB:227, usedMB:94

Does it mean that osmreader filters out all the roads when reading the map?

**Comment by easbar** [comment]
Yeah apparently, but it is also impossible to tell as long as you do not provide more details about the map data you used, your configuration and GraphHopper version.

Also please use our forum such questions about using GraphHopper. Closing here.
