### ISSUE TITLE
web interface: permalink URL not updated when change in layer

### ISSUE THREAD

**Issue by stephan75** [graphhopper/graphhopper#266]
when watching the map via graphhopper.com/maps/ I can change the map layer in the upper right corner from Lyrk to osm.org, osm.de and others.

When doing so, the permalink in the browser's URL row does NOT change, it remains at layer=lyrk !!

Same is with the little symbol for permalink under the place search fields on the left screen.

PS: It seems that Lyrk layer is a bit outdated? any information from that tile provider??

**Comment by oskopek** [comment]
@drnextgis @karussell So, is this fixed? Probably a good idea to close the issue.

**Comment by karussell** [comment]
No it is not fixed. And the pull request would only solve it partially.
