### ISSUE TITLE
Many warnings 'Multiple countries found for way'

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#2663]
I think since #2658 we get these errors. It seems to be mainly a Great Britain issue - could it be an issue of an overlapping border of GBR for the JOSM boundaries.osm data @westnordost?

Omitted many duplicates:

Multiple countries found for way [2783749](https://www.openstreetmap.org/way/2783749): JEY, GBR
Multiple countries found for way [4066366](https://www.openstreetmap.org/way/4066366): GGY, GBR
Multiple countries found for way [4965566](https://www.openstreetmap.org/way/4965566): DNK, FRO
Multiple countries found for way [10229296](https://www.openstreetmap.org/way/10229296): GIB, GBR
Multiple countries found for way [14143304](https://www.openstreetmap.org/way/14143304): FLK, GBR
Multiple countries found for way 17782588: NIU, NZL
Multiple countries found for way 22058615: CYM, GBR
Multiple countries found for way 22333039: AIA, GBR
Multiple countries found for way 23087382: SHN, GBR
Multiple countries found for way 23376204: GGY, GBR
Multiple countries found for way 23565589: GBR, VGB
Multiple countries found for way 23893198: NZL, COK
Multiple countries found for way 25969150: TCA, GBR
Multiple countries found for way 25986080: IMN, GBR
Multiple countries found for way 58659323: IOT, GBR
Multiple countries found for way 59638034: BMU, GBR
Multiple countries found for way 86379854: GRL, DNK

**Comment by westnordost** [comment]
I wouldn't call it an issue. Jersey ( `JE`) is simply a part of the United Kingdom. The ISO Code for the United Kingdom is `GB`

**Comment by westnordost** [comment]
And to take into account country subdivisions, whether they have their own ISO-3166-1 alpha-2 (or 3) code (like `GB` or `GBR`, respectively) or "just" a ISO-3166-2 code (like `GB-SCT`) is something that you would likely want to do anyway because speed limits (and other rules) may vary even in country subdivisions.

E.g. each state in the United States, Canada and Australia has completely disjunct speed limit restrictions. Scotland has slightly different speed limit restrictions. All three regions of Belgium have different speed limit restrictions. Until very recently, each state in India had own speed limit laws. Et cetera.

**Comment by westnordost** [comment]
Look out for `FX`, then

**Comment by otbutz** [comment]
Judging from the different shades of blue, there are quite a few overlapping boundaries:

https://github.com/graphhopper/graphhopper/blob/master/core/src/main/resources/com/graphhopper/countries/countries.geojson

This also seems to include non country boundaries e.g `EU`

**Comment by otbutz** [comment]
Greenland seems to be also part of Denmark which is IMHO wrong. Greenland is part of the [Kingdom of Denmark](https://en.wikipedia.org/wiki/Danish_Realm) which is a different thing.

**Comment by otbutz** [comment]
@karussell could we remove non-country boundaries from the geojson for now? If we want to add subdivisions and others later on it's probably cleaner to keep them i a separate files. As for overlapping country polygons...that's a different story.
