### ISSUE TITLE
map match very short

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#2677]
See [discussion here](https://discuss.graphhopper.com/t/matched-route-stops-before-end-of-trip/7531). Using the profile=foot with gps_accuracy=50 I can reproduce the strange matching result:

![grafik](https://user-images.githubusercontent.com/129644/196182761-bcc386d1-07fa-4be5-a938-ce14258a1cf7.png)

Using the following GPX file

```
<?xml version="1.0" encoding="UTF-8"?>
<gpx xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd" version="1.1" creator="gpx.py -- https://github.com/tkrajina/gpxpy">
  <trk>
    <trkseg>
      <trkpt lat="48.86400042111182" lon="2.3607843371469666">
      </trkpt>
      <trkpt lat="48.86400042111182" lon="2.3607843371469666">
      </trkpt>
      <trkpt lat="48.86355691455583" lon="2.3547411840491885">
      </trkpt>
      <trkpt lat="48.86073482698218" lon="2.3530194642553046">
      </trkpt>
      <trkpt lat="48.862741253038955" lon="2.335490834124835">
      </trkpt>
      <trkpt lat="48.86689310416586" lon="2.323124376331279">
      </trkpt>
      <trkpt lat="48.86671810266022" lon="2.323062929002894">
      </trkpt>
    </trkseg>
  </trk>
</gpx>
```

I also tried different gps_accuracy parameter (5-50) without success.

I would have expected [this route](https://graphhopper.com/maps/?point=48.863938%2C2.360752&point=48.864461%2C2.355269&point=48.861542%2C2.352099&point=48.865788%2C2.322493&profile=foot).

For bike this seems to be fine:

![grafik](https://user-images.githubusercontent.com/129644/196182906-3a962c8b-cac2-47da-a833-c650442c1f01.png)

(The zig zag here probably comes from one ways)

**Comment by michaz** [comment]
Ah yes. The "broken sequence" error message got lost (is back now).

To get a good matched path here: Increase max_visited_nodes.

I removed the (low) default value.
