### ISSUE TITLE
mvn package fails while skipping tests

### ISSUE THREAD

**Issue by lukasalexanderweber** [graphhopper/graphhopper#2678]
**Describe the bug**
I'm not able to package the project after a mvn clean while skipping the tests. Packaging `graphhopper-reader-gtfs` leads to a 

`Could not resolve dependencies for project com.graphhopper:graphhopper-reader-gtfs:jar:7.0-SNAPSHOT: Could not find artifact com.graphhopper:graphhopper-core:jar:tests:7.0-SNAPSHOT`

Without skipping it works, but since I only work on core and testing core accordingly I wouldn't want to run all tests all the time I package graphhopper. Have you any ideas on how to deal with that?

**To Reproduce**
```
mvn clean
mvn package -Dmaven.test.skip
```

**Expected behavior**
should not lead to an error

**System Information**

Windows 10
openjdk version 1.8.0_342
GraphHopper 6.0

**Comment by easbar** [comment]
Did you try `mvn clean package -DskipTests`?
And I'm not sure I understand what you are trying to achieve? Do you want to build the single reader-gtfs module? Or would you like to run only the core tests?

**Comment by lukasalexanderweber** [comment]
> Do you want to build the single reader-gtfs module? Or would you like to run only the core tests?

None of them. I want to create `graphhopper-web-7.0.jar` without running all tests. 

This snapshot might help:

![image](https://user-images.githubusercontent.com/32765578/196190345-46873fb8-c9d4-48b8-aaca-0493e119168f.png)

@karussell your link might be the sollution since in the screenshot can be seen that packaging test-jar is skipped

**Comment by easbar** [comment]
>  I want to create graphhopper-web-7.0.jar without running all tests.

`mvn clean package -DskipTests` does this. Or does this not work either? I remember `-Dmaven.test.skip` did not work for me (at some point, in some context).

And why do you (frequently?) want to build the jar? For development I recommend running GraphHopper from IntelliJ (or some other IDE).

**Comment by easbar** [comment]
Btw adding `-Pskip-tools-jar` to your `mvn` command might also speed it up a bit (if you only need the web-, but not the tools jar...)

**Comment by lukasalexanderweber** [comment]
`mvn clean package -DskipTests`

works, sorry for the inconvenience

**Comment by easbar** [comment]
No worries I think I also ran into this problem at some point, because `maven.test.skip` also skips the *compilation* of the tests and then this test-jar is missing or something.
