### ISSUE TITLE
Question about a "use_living_streets" costing option

### ISSUE THREAD

**Issue by FranckRobin** [graphhopper/graphhopper#2690]
I am discovering GraphHopper mostly evaluating the routing engine yet. I am used to Valhalla routing and expecting to make some comparison, notably about costing options.
Would Graphhopper propose anything equivalent to the "use_living_streets" costing option allowing to avoid or favor living streets in route?

**Comment by easbar** [comment]
Yes you have all kinds of options to avoid/favor different types of routes. Take a look at GraphHopper's custom model feature. But please ask usage-related questions in our forum.
