### ISSUE TITLE
Add footway encoded value?

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#2692]
The key footway=* refines the tag highway=footway: https://wiki.openstreetmap.org/wiki/Key%3Afootway

This would be useful for pedestrian routing: https://discuss.graphhopper.com/t/adding-additional-footway-information-to-details-on-route-endpoint/7565

**Comment by natedx** [comment]
This would be very useful, mostly in order to know whether a footway is a sidewalk, a path or a crossing !

**Comment by MonfretAugustin** [comment]
This info would be really useful for my app too ! In order to create really precise itineraries.
