### ISSUE TITLE
When visited on localhost:8989/maps, Map is not showing up. 

### ISSUE THREAD

**Issue by azeem110201** [graphhopper/graphhopper#2696]
**Describe the bug**
When I ran the server and opened localhost:8989/maps, it shows the blank page for map. Also it is not showing the inputs for source and destination.

![image](https://user-images.githubusercontent.com/55446681/202426022-9d8b9fd4-50fd-400b-b057-2f8fe18a2d48.png)

And this is what the console shows

![image](https://user-images.githubusercontent.com/55446681/202426146-015a77c1-4d1a-4579-a139-8f2fd54c8a54.png)

and once you click on search button, we are getting redirected here.

![image](https://user-images.githubusercontent.com/55446681/202426741-d02c5a7e-da9d-4073-a71a-e981034d87ed.png)

and once you start typing in the fields, you are getting the following error.

![image](https://user-images.githubusercontent.com/55446681/202426927-f8dfe435-4d1f-4ad8-86e7-d194a71932f7.png)

**To Reproduce**

1. Followed all the steps mentioned in [this](https://github.com/graphhopper/graphhopper/blob/master/docs/core/quickstart-from-source.md) README
2. Started the server which is running at port 8989
3.  Shows the blank map page

The App is expected to open at localhost:8989/maps and take inputs (source and destination name) and calculated the path between those two points

**Comment by otbutz** [comment]
Did you previously run the old version? Looks like the first part was from your browser cache.

**Comment by azeem110201** [comment]
Even I tried out this on a different PC though. It is still showing the same error

**Comment by azeem110201** [comment]
Nope. It's still not working

**Comment by azeem110201** [comment]
It is actually hitting /geocode even though we don't have that endpoint in our application

![image](https://user-images.githubusercontent.com/55446681/202439880-81b9cedf-f573-4dfe-ad04-8b0d38e2aec0.png)

**Comment by easbar** [comment]
> It is actually hitting /geocode even though we don't have that endpoint in our application

Yes, this is because the new maps app does not allow setting a different url for routing and geocoding, yet. I opened an issue here: https://github.com/graphhopper/graphhopper-maps/issues/290

**Comment by azeem110201** [comment]
Yes clicking right and choosing From/To works fine.

**Comment by easbar** [comment]
Ok, we will disable the address search, see https://github.com/graphhopper/graphhopper-maps/pull/291

**Comment by easbar** [comment]
It is now disabled: 43eef6d3db0d1e6eb4a8a7834e7baca411ff274b
