### ISSUE TITLE
Cars and trucks are unable to go through this residential road

### ISSUE THREAD

**Issue by zstadler** [graphhopper/graphhopper#2704]
**Describe the bug**
Cars and trucks are unable to go through [this residential road](https://www.openstreetmap.org/way/37173383).

**To Reproduce**

Open [this link](https://graphhopper.com/maps/?point=32.07567%2C35.103735&point=32.074533%2C35.102619&profile=car&layer=Omniscale) to the GraphHopper site.

**Expected behavior**

Cars and trucks should be able to go through that residential road.

**System Information**

GraphHopper web site.

**Screenshots & Logs**

![image](https://user-images.githubusercontent.com/1304610/204849677-59ee8b49-a707-47b9-bb94-439adb1e4bd0.png)

**Comment by zstadler** [comment]
> Also this roads does not look like it is only 2m wide.

Unfortunately, this width was entered by a humanitarian NGO that wanted to help, but created a lot of mapping issues....

**Comment by easbar** [comment]
Then it is probably best to try to contact them.

**Comment by zstadler** [comment]
The NGO is has not responded to comments about much more severe mapping issues.
From time to time some brave soul cleans up part of the mess.

**Comment by easbar** [comment]
But it looks like they haven't been active for many years: https://www.openstreetmap.org/user/JumpStart%20International/history ?
