### ISSUE TITLE
'undefined' in location. GraphHopper Maps

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#272]
Very rarely there occures 'undefined' in the location input. It was happening after (right) click something on the markers or so.

**Comment by sebalis** [comment]
There’s a very clear way of triggering this: change the transport mode by clicking on Foot or Bicycle etc. while the input fields for start and destination are still empty. This causes the fields to be filled with the string 'undefined'. Unfortunately there are some map objects that actually have this name. So when one of the two fields (say, start) is filled in with actual data, the web interface thinks that the other field has also been set, to a place in Zimbabwe. Example: Change to foot routing while the fields are empty, enter „Harare“ in the start field, choose the Harare (Zimbabwe) item that is offered – you are given a route before you entered your destination.

**Comment by karussell** [comment]
This should be fixed with #1180 - will deploy it in a few minutes.
