### ISSUE TITLE
Gist: Graphhopper weekly update script for Windows Task-Scheduler

### ISSUE THREAD

**Issue by rbraband** [graphhopper/graphhopper#273]
https://gist.github.com/rbraband/cb81602dec33774daea6

**Comment by karussell** [comment]
Hmmh, I think this is too use case specific. E.g. there is a huge downtime when you download the pbf. But for some usecases the parallel import (to the running instance) might be also wrong. 

Also I would like to handle these many cases directly in Java, if at all.
