### ISSUE TITLE
point_hint limit not large enough

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#2732]
There are certain cases [like this](https://graphhopper.com/maps/?point=47.345537%2C8.722726&point=47.34535%2C8.72485&profile=car) where the point_hint limit needs to be increased (related #1935). Unfortunately I do not see the original requesters real world example that failed (@samruston?).

**Comment by samruston** [comment]
@karussell I can't remember the original example, but 100m was chosen rather arbitrarily at the time but seemed good enough for most use cases. The issue we were originally having was it snapping a considerable distance, say 1km, so 170m still seems like a good limit to me
