### ISSUE TITLE
Unknown vehicle 'bike' in profile: Default vehicle profiles not generated? 

### ISSUE THREAD

**Issue by larsschwarz** [graphhopper/graphhopper#2758]
I installed the Routing API server as per the docs and modified the config-example.yml by replacing car with bike here:

`graph.flag_encoders: bike`

According to the inline comments this should be fine ("More options: foot,hike,bike,bike2,mtb,racingbike,motorcycle,wheelchair (comma separated)")

I also replaced the default car profile with

```
profiles:
    - name: bike
      vehicle: bike
      weighting: fastest
```

and added

```
profiles_ch:
    - profile: bike
```

Running 

`java -Ddw.graphhopper.datareader.file=oldenburg.osm.pbf -jar *.jar server config-example.yml`

however returns

```
[main] ERROR io.dropwizard.cli.ServerCommand - Unable to start server, shutting down
java.lang.IllegalArgumentException: Unknown vehicle 'bike' in profile: name=bike|vehicle=bike|weighting=fastest|turnCosts=false|hints={}. Available vehicles: car
```
running the same command with `import `instead of `server `returns

`Unknown vehicle 'bike' in profile: name=bike|vehicle=bike|weighting=fastest|turnCosts=false|hints={}. Available vehicles: car`

I tried the docs, but I cannot seem to find an option to generate that profile, even guessing by the inline comments bike seems to be a standard profile included? 

Seems like for older version of Graphhopper this was done by running `./graphhopper.sh import <>` instead?

It would be really helpful if vehicle types mentioned in the example config would at least return a more dedicated error response or maybe even trigger the required import/generation automatically?

**Comment by otbutz** [comment]
Shouldn't this trigger an error if the graph doesn't fit to the configuration? At least for encoded values we're checking for consistency.

**Comment by easbar** [comment]
Yes, this is because we run `checkProfilesConsistency`, for the *loaded* EncodingManager, which gets the 'car' vehicle from the -gh folder as it is loaded from disk. We have another check, that makes sure the profiles in the config file match the ones in the -gh folder, but this only runs afterwards. I think we only need to change the order of the checks.
