### ISSUE TITLE
get_off_bike should differ between city vs rural

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#2777]
Currently we show "get off bike" for paths e.g. [here](https://graphhopper.com/maps/?point=50.960465%2C10.38916&point=50.961132%2C10.437039&point=50.945161%2C10.489244&profile=mtb&layer=OpenStreetMap) although it is probably not required to get off the bike here. In general we should probably mark "get_off_bike" as true only if it is legally required. Similar problem [here](https://graphhopper.com/maps/?point=49.613602%2C11.519951&point=49.609576%2C11.518068&point=49.611473%2C11.510671&profile=mtb&layer=OpenStreetMap). The reason is that we do not set the speed to walking speed for path in case of mtb vehicle but for the other bike profiles we do.

Is it required for highway=path @ratrun ? (I found [this issue](https://github.com/graphhopper/graphhopper/issues/412) where you say so and [in the wiki](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dpath) they even say 'Actual usage of highway=footway vs highway=path differs between mappers and areas. ')

**Comment by ratrun** [comment]
As far as I can tell there is no common understanding for ways just tagged as `highway=path`. There are endless discussions on the OSM forum about that issue. This is documented on the [english wiki ](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dpath) where they say "Usage of this tag varies regionally, and paths without any additional tags are common. Consequently, paths require careful interpretation by data consumers to avoid causing map users inconvenience, or worse."
What I can tell is that it is definitely not required to get off the bike on such ways when we are talking about the international level. So I agree to remove the `path` from the `GET_OFF_BIKE` list in OSMGetOffBikeParser.

**Comment by bt90** [comment]
@karussell we still treat `highway=footway` as a pushing section in the avg speed and priority parsers:

https://github.com/graphhopper/graphhopper/blob/94a5602fd269a523c00300bbaf00fa82d560f198/core/src/main/java/com/graphhopper/routing/util/parsers/BikeCommonPriorityParser.java#L50

https://github.com/graphhopper/graphhopper/blob/94a5602fd269a523c00300bbaf00fa82d560f198/core/src/main/java/com/graphhopper/routing/util/parsers/BikeCommonAverageSpeedParser.java#L35

**Comment by bt90** [comment]
My point is that we should standardize the handling of such ways across parsers. The changes from https://github.com/graphhopper/graphhopper/commit/402976482c3dbe76cb1d3beda0404435ec0b4155 indicate that the cyclist is able to drive on these ways without getting off his bike. The priority and speed should reflect this.

**Comment by bt90** [comment]
> But we want a low speed for footway (?)

IMHO, this is up for discussion. The OSM wide consensus seems to be that `highway=path` should be treated the same as `highway=footway`. We should rather check tags with a well established definition. e.g:

https://github.com/graphhopper/graphhopper/blob/94a5602fd269a523c00300bbaf00fa82d560f198/core/src/main/java/com/graphhopper/routing/util/parsers/BikeCommonPriorityParser.java#L162
