### ISSUE TITLE
FlagEncoder versioning

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#281]
If the access of a weight or something in the flags changed we have only the choice to increase the edge version which is ugly as people not using the one flagEncoder will also be forced to reindex it. So introduce a getVersion method and store this into the graph somehow.

Reading an older, different graph version is not the goal of this issue and is also a lot more complex but probably won't happen before 1.0

**Comment by andreaswolf** [comment]
Do I understand this right that effectively a version should be stored for each flag (or rather, one version for the "bag of flags" of one encoder)? So a hypothetic structure could be:

```
[{
flag1: foo, flag2: bar, version: 1
},
{
flag3: baz, version: 3
}]
```

I think one byte should suffice for the version number, right?

**Comment by karussell** [comment]
We could use a more fine grain solution but just one version per used encoder is sufficient for now. If the encoder version changes we throw an exception.

**Comment by andreaswolf** [comment]
Ah, thought about it again… the used encoder versions can be stored once in the graph, right? My first draft was for each edge, but that does not make sense for a start.

**Comment by karussell** [comment]
The purpose is entirely protecting the user from garbage data and so yes, once in the graph or in the properties would be sufficient. Maybe related to #313 and #285

**Comment by karussell** [comment]
Fixed via #401

**Comment by devemux86** [comment]
:+1:

**Comment by devemux86** [comment]
Why not using the compatible encoders and skip the others [here](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/routing/util/EncodingManager.java#L167-L170)?

**Comment by karussell** [comment]
But when you load the graph sucessfully where only one encoders' version mismatches - how should the routing behave with the failing encoder?

Failing early is a lot better IMO

**Comment by karussell** [comment]
The issue just makes sure that e.g. if the CarFlagEncoder is not used at all and there was a version increment happening we don't force the user with an edge version increment to refeed the data.

**Comment by devemux86** [comment]
Thanks for the clarification Peter, I understand what you mean here.

**Comment by devemux86** [comment]
@karussell I see that now if we try to load with the latest GH a graph created with GH just prior this PR, there is failure from [GraphHopperStorage](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java#L1407-L1411) with messages like:
```
WARNING: Encoding does not match:
Graphhopper config: car|speedFactor=5.0|speedBits=5|turnCosts=true|version=1
Graph: car|speedFactor=5.0|speedBits=5|turnCosts=true
```

Considering that we have not any changes in graphs structure besides the introduction of ```version``` attribute, shouldn't  the checks pass or is it a necessary inconvenience for the 1st time?

**Comment by devemux86** [comment]
I mean in [EncodingManager](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/routing/util/EncodingManager.java#L166-L171) the version check takes place only if the graph configuration has a version.

**Comment by karussell** [comment]
> is it a necessary inconvenience for version's 1st time

Yes, should only be 1st time. Feel free to create a PR to avoid this :)

**Comment by devemux86** [comment]
Peter I think now we could proceed without the additional [check](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java#L1407-L1411) in ```GraphHopperStorage``` since it takes always place before in ```EncodingManager```?

**Comment by karussell** [comment]
In encoding manager we just check the version of every flagencoder, in storage we check against the correct configuration of the loaded graph vs. encodingmanager

**Comment by devemux86** [comment]
Then at GraphHopperStorage we need to analyse where exactly is the fail at the comparison of the whole graph configuration (i.e. if it is only in version sub-string).

**Comment by karussell** [comment]
Not sure what you mean. Do you mean the duplicate version check in storage and encodingmanager?

**Comment by devemux86** [comment]
I mean that as you said in GraphHopperStorage there is check for the whole graph configuration as one ```String```, e.g. ```car|speedFactor=5.0|speedBits=5|turnCosts=true,foot|speedFactor=1.0|speedBits=4|turnCosts=false,bike|speedFactor=2.0|speedBits=4|turnCosts=false```

There should we analyse and check the lack of version individually?

**Comment by karussell** [comment]
Why? What would we do with e.g. the information that only one profile does not match?

**Comment by devemux86** [comment]
There is probably only one case where we "could" let the check to be successful.
Right now with the introduction of the ```version``` where the graph structure didn't change and the version is 1.
I'm still thinking if it's worth the effort or simply make users rebuild their graphs.

**Comment by devemux86** [comment]
I mean that if the configuration has only as difference the addition of ```version=1``` and only that.

**Comment by karussell** [comment]
Probably we'll decide before 0.5 release, because if there are other changes then this tweak is not worth the effort
