### ISSUE TITLE
barrier = cattle_grid

### ISSUE THREAD

**Issue by MotoUKRider** [graphhopper/graphhopper#2816]
Hello - Cruiser user here (both Android and Desktop) with Mapsforge maps.

Graphhopper will not route me over a `barrier` = `cattle_grid`, eg:
https://www.openstreetmap.org/node/2923770193

This route, with Cruiser Desktop using offline Graphhopper takes me on a very interesting reroute when I (a motorcycle) could easily ride over it.  This is with default "car", "fast" options and no avoidances - stock routing options.  Same results on the Android app.
![graphhopper-cattlegrid](https://user-images.githubusercontent.com/125696109/236784474-bcc6c302-5a62-4688-b5e2-979202d042dc.jpg)

I also use BRouter, and had to modify the profile to take into account level-crossings, which are tagged differently on OSM despite being the same "electronic barrier" type.  Of course there is lack of consistency with people's edits of public data to consider, but what is Graphhopper's "_problem_" with a drive-over cattle-grid?!

I am fairly active on the Cruiser board, and [have written about this situation here](https://github.com/devemux86/cruiser/discussions/56).

**Comment by otbutz** [comment]
Seems to work just fine?

https://graphhopper.com/maps/?point=55.365403%2C-3.851056&point=55.365755%2C-3.849066&profile=car&layer=OpenStreetMap

https://graphhopper.com/maps/?point=55.347399%2C-3.872085&point=55.371413%2C-3.829582&profile=car&layer=OpenStreetMap
