### ISSUE TITLE
vehicle in profile vs graph.vehicles inconsistency

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#2834]
If turn costs is enabled in profile and graph.vehicles is using the same vehicle but without `turn_cost=true` then turn restrictions are not enabled.

Of course we should get rid of graph.vehicles but this is another bigger task :)

**Comment by easbar** [comment]
You mean the setting in the profile should overrule the one in graph.vehicles?

**Comment by easbar** [comment]
Ok, I'll have a look. Actually I'm surprised no exception is thrown currently.
