### ISSUE TITLE
Limit scope of encoded values in a custom model

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#2841]
Currently in a custom model all encoded values are usable for every profile. This makes it nearly impossible to split a server with many profiles into two independent servers e.g. when hardware limits kick in (often RAM) and client code uses various "mixed" custom models. (Same problem for path details.)

**Comment by michaz** [comment]
As usual, I would say that enforcing these restrictions is perhaps not the first or most important step here.

If a user finds an Encoded Value they shouldn't be using -- why not, let them do it for now.

I think more important is to decide what Encoded Values the user _should_ be allowed to use. Then report only those in `/info`. Then see if everything we think custom models are there for are still possible. If not, find different ideas. etc.

**Comment by otbutz** [comment]
"Hiding" some EVs that are considered more of an implementation detail might be useful.

**Comment by michaz** [comment]
Yes I don't deny that
