### ISSUE TITLE
Inspect graph properties

### ISSUE THREAD

**Issue by devemux86** [graphhopper/graphhopper#285]
Is there a way via the API to inspect a graph's properties prior loading it?

`GraphHopper` class has to be initialized properly with `setCHEnable`, `setElevation` (and now with the turn restrictions too) prior calling load method.
Too many combinations, or else the load will fail.

Right now need to catch these exceptions in order to cover all the cases, but is there a more elegant solution?

**Comment by karussell** [comment]
Partially we already do this now via `public static EncodingManager create( String ghLoc )`

**Comment by devemux86** [comment]
Yes that's called from ```GraphHopper.load``` which is already been used.

The thing is that in order to open an unknown graph we need to try multiple combinations and try/catch the exceptions.

**Comment by karussell** [comment]
I see. So with the 'mobile use case' ... you mean we should put those configs in e.g. the properties and init the `GraphHopper` instance from this if possible?

**Comment by devemux86** [comment]
I mean that as GraphHopper evolves, it's natural to use more and more properties.

It would be convenient if it could parse the graphs and by inspecting their properties, could open them without exceptions (as it would know itself what parameters to set at loading).

Only case I can imagine we could have any errors would be the advancement of the nodes/edges versions.
Though it would be marvellous if the backwards compatibility would not break!

**Comment by karussell** [comment]
Regardiong backwards compatiblity: that will break a lot and we should break it :) ! But we could introduce an automated conversion procedure like lucene is doing.

**Comment by karussell** [comment]
@devemux86 why did you close that? I think it might be a valuable feature, i.e. loading a graph without configuring the Java objects before.

**Comment by devemux86** [comment]
GraphHopper has changed a lot all these years.

Now with the profiles, it's more intuitive the lib to automatically create and load profiles when open an unknown graph,
instead of read the properties file in order to create the profiles by hand (with missed info since weighting in unknown).
