### ISSUE TITLE
Via instruction is wrong

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#289]
The first instruction after a via point has to be recalculated in PathMerger. Otherwise we could get e.g. 'continue' when we need 'turn around' like [here](https://graphhopper.com/maps/?point=49.870245%2C11.892602&point=49.870628%2C11.892828&point=49.870245%2C11.892602&layer=Lyrk). Or fix this via merging all edges into one Path object and creating instructions out of that.

And not sure if the following is a bug: the via point should not insert a duplicate point in the pointlist, instead we need an explicit skip of FinishInstructions when adding to the point list. BUT keep in mind that we will have to tweak the code in Instruction.createJson

**Comment by jansoe** [comment]
also include u-turn instructions for start points with direction (once #434 gets merged)

**Comment by boldtrn** [comment]
I will close here as this is a duplicate at #1064 and the issue will be fixed via #1073.
