### ISSUE TITLE
Not Selecting Sea Route between tangier med and elgeciras for Morocco to Spain Route

### ISSUE THREAD

**Issue by MsaidBENJAA** [graphhopper/graphhopper#2944]
![image](https://github.com/graphhopper/graphhopper/assets/136267897/3443b6e4-deaf-496b-8fe8-81f7865053ad)

When attempting to select a route between Morocco and Spain using GraphHopper, the Tangier Med - elgeciras sea route is not being considered as an option.

**Comment by easbar** [comment]
You mean this one: https://www.openstreetmap.org/way/39729370 ?

**Comment by MsaidBENJAA** [comment]
> You mean this one: https://www.openstreetmap.org/way/39729370 ?

yes

**Comment by easbar** [comment]
Apparently it is considered as an option, but the routes still takes the Tanger-Tarifa ferry, because it is assumed to be faster.
In OSM Tanger-Tarifa [link](https://www.openstreetmap.org/way/362003444) is mapped with `duration=0:35` while Algeciras-Tangier Med is mapped with `duration=1:30`.

**Comment by MsaidBENJAA** [comment]
how can we force the API to take the Algeciras-Tangier Med ferry, we need it to take the algeciras-Tangier Med, as it is the one that supports the big trucks transpotaion

**Comment by MsaidBENJAA** [comment]
yes they are not allowed on Tanger-Tarifa. how can we map it in OSM?

**Comment by easbar** [comment]
I'm closing here since this is rather a mapping issue. For further questions related to using GraphHopper please use our forums.
