### ISSUE TITLE
Allow multiple routing requests at the same time

### ISSUE THREAD

**Issue by nijs9** [graphhopper/graphhopper#296]
I developed a Java service (for usage in online routeplanner) with graphhopper, which works fine with this code:

        String path = getServletContext().getRealPath("/WEB-INF/benelux.osm-gh");

        double lat1 = Double.parseDouble(request.getParameter("lat1"));
        double lon1 = Double.parseDouble(request.getParameter("lon1"));
        double lat2 = Double.parseDouble(request.getParameter("lat2"));
        double lon2 = Double.parseDouble(request.getParameter("lon2"));

        GraphHopper tmpHopp = new GraphHopper().forServer();
        //tmpHopp.setGraphHopperLocation("belgium-latst").setEncodingManager(new EncodingManager("CAR"));
        tmpHopp.setEncodingManager(new EncodingManager("FOOT"));
        tmpHopp.setAllowWrites(false);
        tmpHopp.load(path);

        GHRequest req = new GHRequest(lat1, lon1, lat2, lon2).
                setAlgorithm(AlgorithmOptions.ASTAR_BI);
        req.setWeighting("fastest");
        req.setVehicle("FOOT");

        req.getHints().
                put("instructions", "false");
        GHResponse resp = tmpHopp.route(req);

This works fine, but when multiple users try to calculate a route between two points at the same moment, it's not possible. How can I enable this?

**Comment by karussell** [comment]
Please see our web module where this is properly implemented

**Comment by karussell** [comment]
The web module is here: https://github.com/graphhopper/graphhopper/tree/master/web and you can easily start it from command line. documented here: https://github.com/graphhopper/graphhopper/blob/master/docs/web/quickstart.md

**Comment by nijs9** [comment]
Thanks for your answer!

Met vriendelijke groet
Sven Nijs
[cid:image001.png@01CEDEC1.972AEBF0]

2infinIT BVBA
Mortelbroekstraat 32
3271 Averbode
0472 86 67 54

Van: Peter [mailto:notifications@github.com]
Verzonden: dinsdag 6 januari 2015 21:08
Aan: graphhopper/graphhopper
CC: nijs9
Onderwerp: Re: [graphhopper] Allow multiple routing requests at the same time (#296)


The web module is here: https://github.com/graphhopper/graphhopper/tree/master/web and you can easily start it from command line. documented here: https://github.com/graphhopper/graphhopper/blob/master/docs/web/quickstart.md

**Comment by nijs9** [comment]
Thanks for the info! Is the use free?

2015-01-06 21:08 GMT+01:00 Peter <notifications@github.com>:

**Comment by karussell** [comment]
Using the Open Source Version on your own servers is free. Using our Directions API with some more features like the Matrix API and Geocoding is only free for the free package.
