### ISSUE TITLE
should locked=yes have lower priority?

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#2982]
[This node](https://www.openstreetmap.org/node/10720988349) is tagged bicycle=yes and foot=yes and locked=yes. And we [cannot pass it](https://graphhopper.com/maps/?point=52.593502%2C13.249002&point=52.593465%2C13.249132&profile=foot).

Or is this incorrect tagging?

**Comment by bt90** [comment]
An example from the OSM wiki:

![Example](https://wiki.openstreetmap.org/w/images/thumb/9/97/16052010022.JPG/1280px-16052010022.JPG)

It's locked, yet still passable for bikes and pedestrians.

**Comment by bt90** [comment]
Seems like a tagging mistake to me:

https://maps.app.goo.gl/yw1dCcgVTrKYRFBo7

**Comment by BURMAUG** [comment]
If bikes are allowed and pedestrians can walk freely they yes to both but not a vehicle.

**Comment by caspg** [comment]
I asked question about this on forum https://discuss.graphhopper.com/t/barrier-lift-gate-is-blocking-bike/8398
I have similar node near me (Poland) which blocks routing through official cycling route.

I would vote for ignoring `locked=yes` if there is `[access]=yes`.

**Comment by caspg** [comment]
I did this change in my fork to allow bicycles when there is `locked=yes`.  Maybe something like this could go to the main branch?

[commit](https://github.com/caspg/graphhopper/commit/d8eae9499cb5e7803d4eac88eee243328f275956)
```java
        if (restrictedValues.contains(firstValue))
            return true;
        else if (node.hasTag("locked", "yes") && !intendedValues.contains(firstValue))
            return true;
 ```

**Comment by ratrun** [comment]
I think that one also needs to take the transportation mode into regard. See https://github.com/graphhopper/graphhopper/compare/master...ratrun:biketourplanner:issue2982 for a draft

**Comment by caspg** [comment]
@ratrun Don't we already return `restrictionKeys` based on transportation mode?

https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/routing/util/parsers/AbstractAccessParser.java#L37

```java
restrictionKeys.addAll(OSMRoadAccessParser.toOSMRestrictions(transportationMode));
```

Then below lines will return `true` for `bicycle=yes` only for bike profile, right?

```java
String firstValue = node.getFirstValue(restrictionKeys);
intendedValues.contains(firstValue))
```

**Comment by ratrun** [comment]
> Don't we already return `restrictionKeys` based on transportation mode?

Yes, you are right. Thank you! I now simplified my change and created a PR, see #3018

**Comment by caspg** [comment]
@ratrun nice one
