### ISSUE TITLE
Routing of ordinary bicycle over ways tagged mtb:scale really wanted?

### ISSUE THREAD

**Issue by hungerburg** [graphhopper/graphhopper#3049]
**Describe the bug**
I found, the stock bicycle profile routes over mtb:scale tagged ways. A warning is shown, that the route contains "herausfordernde oder gefährliche Abschnitte: mtb_rating: 2".

**To Reproduce**
Sample route https://graphhopper.com/maps/?point=47.285994%2C11.399725&point=47.283385%2C11.412976&profile=bike&layer=TF+Cycle

**Expected behavior**
I'd expect such not suggested at all in the itineraries for ordinary bicycles. Perhaps S0 can be fun on a trekking bike. But likely S1 and up will break the bike or the biker when not experienced in mountainbiking.

**Comment by mprins** [comment]
There is a PR open for `mtb:scale` support in https://github.com/graphhopper/graphhopper/pull/3048

**Comment by hungerburg** [comment]
Cool! https://wiki.openstreetmap.org/wiki/Key:mtb:scale:imba maybe one more contender. https://overpass-turbo.eu/s/1QXd it is used in the wild without the other in places likely not all in a bike park.

**Comment by ratrun** [comment]
Here is the routing result of the example from above using the current state of the PR #3048 with the bike profile without elevation weighting: 
![Bildschirmfoto vom 2024-09-15 06-48-15](https://github.com/user-attachments/assets/b5dd8487-5622-40c5-9813-96ab3b5f87d5)
@hungerburg : Is this the route you are expecting?

**Comment by hungerburg** [comment]
@ratrun This is a good result. The mtb:scale=2 path no longer taken. I would go there on my trekking bike. The steepness warning very much justified! But on this track people can at least push the bike if too demanding for them.

I now see one problem with the sample route: This section https://www.openstreetmap.org/way/1066950456 was marked closed 25 days ago. With up to date data, the detour will get really long, either same as the racing bike route or [like this](https://graphhopper.com/maps/?point=47.285994%2C11.399725&point=47.292691%2C11.416945&point=47.283385%2C11.412976&profile=bike&layer=TF+Cycle).

**Comment by ratrun** [comment]
> now see one problem with the sample route: This section https://www.openstreetmap.org/way/1066950456 was marked closed 25 days ago. With up to date data, the detour will get really long, either same as the racing bike route or [like this](https://graphhopper.com/maps/?point=47.285994%2C11.399725&point=47.292691%2C11.416945&point=47.283385%2C11.412976&profile=bike&layer=TF+Cycle).

This is because I used an OSM extract from 2024-07-12. I didn't expect a change in the data in that region, therefore I didn't update it. The way will also be avoided when using actual data.

**Comment by ratrun** [comment]
@karussell This issue can be closed, thanks!

**Comment by hungerburg** [comment]
Is the change already live on the GraphHopper site? I still see ordinary bicycles routed over mtb:scale=3 paths, eg. here from the outdoor seating to the parking lot:

https://graphhopper.com/maps/?point=47.211323%2C11.333352&point=47.221799%2C11.367835&profile=bike&layer=TF+Cycle

Note there is a mtb:scale=0 route available too, down the "Rodelbahn" https://graphhopper.com/maps/?point=47.211323%2C11.333352&point=47.221799%2C11.367835&profile=foot&layer=TF+Cycle - the 4.5 km alternative

**Comment by ratrun** [comment]
>Is the change already live on the GraphHopper site?

Here is the result using the latest master branch:
![Bildschirmfoto vom 2024-10-25 17-53-45](https://github.com/user-attachments/assets/17f990f6-38f7-4d2d-9843-92176d68db5e)

This result differs from the current online instance. Either the graphhopper online instance is not using the  latest jar file, or the used server side custom bike model was not updated.
