### ISSUE TITLE
Android Improvements

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#305]
We need to improve android support and development:

 - [x] fixed #250
 - [x] create workaround #251
 - [x] check workaround #251
 - [x] use Android Studio (IntelliJ), which introduces gradle for the build tool in android module, see #341 
 - [x] update mapsforge to recently released 0.5.x

**Comment by loffenauer** [comment]
Would also like to see that the library works with app local data
getFilesDir()

Currently, when copying data to that location, the app produces

java.lang.IllegalStateException: Cannot load properties to fetch EncodingManager configuration at
/data/data/<appname>/files/Pforzheim-gh/

Not all devices have SDcards, and this would be possible to bundle the data with the app into a self-contained APK

**Comment by karussell** [comment]
Currently we head towards 0.4 and new bigger features are only likely if they come from the community.
