### ISSUE TITLE
Android / Cannot load graph with custom FlagEncoder

### ISSUE THREAD

**Issue by loffenauer** [graphhopper/graphhopper#307]
Hi-
I have forked graphhopper to work on a WheelChairRouter. See https://github.com/loffenauer/graphhopper which adds a WheelChairFlagEncoder in routing.utils.

All works fine on the server side including the built in Web server.

However, when adding the android JAR produced by 
./graphhopper android

to an android app, the following exception is produced based on the data that works fine on the server side.

 java.lang.IllegalStateException: Cannot load the graph when using instance of com.graphhopper.storage.LevelGraphStorage and location: /mnt/sdcard/Pforzheim-gh/

Any clue what goes wrong here ?

**Comment by devemux86** [comment]
You need to specify the same options while reading the graph, as it had when it was created.
e.g. if the graph has contraction hierarchies, then you need to enable them prior reading it.

Also it's recommended to use the same GraphHopper version at write / read.

**Comment by loffenauer** [comment]
All I do is the same as in the Android example

        GraphHopper tmpHopp = new GraphHopper().forMobile();
        File f =  new File(Environment.getExternalStorageDirectory() , ROUTEFILE);
        tmpHopp.load(f.getAbsolutePath());
        hopper = tmpHopp;

Configuration at creation is


graph.dataaccess=RAM_STORE
prepare.chWeighting=no
osmreader.wayPointMaxDistance=1
omsreader.levelgraph=true
omsreader.chShortcuts=true
graph.flagEncoders=wheelchair

**Comment by devemux86** [comment]
I think you have old and new properties together.
```prepare.chWeighting=no``` is a newer way to handle CH than ```omsreader.chShortcuts```
Check the latest version of properties [here](https://github.com/graphhopper/graphhopper/blob/master/config-example.properties), though it's important what GraphHopper you're using.

In latest code you can handle the CH prior reading with ```graphHopper.setCHEnable```

**Comment by loffenauer** [comment]
I have cloned the repo from main graphhopper repo last night.
Unfortunately the options are not quite clear to me, also from the examples, maybe it would help to document this better

I now used
prepare.chWeighing=no
omsreader.levelgraph = true

in the  configuration at generation time

and 

private void initRouting() {
        GraphHopper tmpHopp = new GraphHopper().forMobile();
        tmpHopp.setCHEnable(false);
        File f =  new File(Environment.getExternalStorageDirectory() , ROUTEFILE);
        tmpHopp.load(f.getAbsolutePath());
        hopper = tmpHopp;
        prepareInProgress = false;
}

This works for me.

**Comment by karussell** [comment]
thanks. this can be removed (and is not valid option) `omsreader.levelgraph = true`
