### ISSUE TITLE
Problem to find nearest nodes with a custom filter for LocationIndex

### ISSUE THREAD

**Issue by crowmagnumb** [graphhopper/graphhopper#317]
I have written custom filters for use with finding the nearest node.   This can cause the search to have to be broadened significantly.  As such I had written a workaround for expanding the search to find the nearest node. Recently, something similar (for expanding the search) was built into the system. In upgrading my code, I've refactored to allow the use of this new system. However, it is a broken as far as I can tell. In particular, the part that returns early if a result was found.  This is currently line 742 of LocationIndexTree.

            if (iteration % 2 == 1)
            {
                // Check if something was found already...
                if (foundEntries.size() > 0)
                {
                    double rMin = calculateRMin(queryLat, queryLon, iteration);
                    double minDistance = calcMinDistance(queryLat, queryLon, foundEntries);

                    if (minDistance < rMin)
                    {   // resultEntries contains a nearest node for sure
                        break;
                    } // else: continue an undetected nearer node may sit in a neighbouring tile.
                    // Now calculate how far we have to look outside to find any hidden nearest nodes
                    // and repeat whole process with wider search area until this distance is covered.
                }
            }

If I comment this out, it works fine again. It is always finding the same set of entries, but my filter is rejecting them over and over again. What I am doing is checking for nearest node which passes my filter. If none, I expand the search, which now means incrementing *maxRegionSearch* and trying again. And repeating this until I find something or I my search area becomes too large to manage (which doesn't happen but I still have a limit in case).

Can someone explain what this check and early exit from the iteration is doing?

Cheers,

Ken

**Comment by karussell** [comment]
Do you have an example where this fails?

See the discussion about these constants in #221, e.g. rMin is the radius to the rectangle and if that is bigger than ALL found entries we do not need the second iteration and it should be possible to leave earlier.

**Comment by KenSoutherland** [comment]
The problem is as I discussed about the filtering. It's not a question of does the expanded search find a node or not, it's does the expanded search find a node that *passes* my filter. Inside of **findClosest** the **findNetworkEntries** returns a set of node ids, then we loop through these nodes using the edge explorer and the supplied filter. The basic search does not find a node that passes my filter so **findClosest** returns a "null" **QueryResult**. If I try and expand the search further I still don't find my node because no matter what value of **maxRegionSearch**, **findNetworkEntries** returns the first set of nodes that it finds but I already know those don't pass my filter, so once again they don't pass my filter and I get a "null" result. Here is the code in my app that I use to wrap **findClosest** to get my result. I feel like this could be easily incorporated into LocationIndexTree itself if it makes sense to others. And then it would be clear that there is a link between the search and the filtering. I would be happy to write this up as a pull request if you agree.

    private QueryResult findClosest( final LatLong pointLL,
                                     final Map<Integer, EdgeIteratorState> toVisit,
                                     final Collection<Integer> exceptions )
    {
        EdgeIteratorState closestEdge = null;
        //
        // Never seen it go near 100 but that is the max I have set just in case something
        // were to go completely wrong.
        //
        int regionSize = MAX_REGION_SEARCH_DEFAULT;
        QueryResult closest = null;
        while ( closestEdge == null && regionSize < 100 ) {
            closest = _locationIndex.findClosest( pointLL.getLatitude(),
                                                  pointLL.getLongitude(),
                                                  new ToVisitEdgeFilter( toVisit,
                                                                         _edgeFilter,
                                                                         exceptions ) );
            closestEdge = closest.getClosestEdge();

            if ( closestEdge == null ) {
                regionSize += MAX_REGION_SEARCH_INCREMENT;
                _locationIndex.setMaxRegionSearch( regionSize );
            }
        }

        if ( regionSize > MAX_REGION_SEARCH_DEFAULT ) {
            if ( _debug ) {
                System.out.println( "Had to go to regionSize [" + regionSize + "] to find closest node." );
            }

            // reset for any other findClosest calls that might occur and for next time.
            _locationIndex.setMaxRegionSearch(MAX_REGION_SEARCH_DEFAULT);
        }

        return closest;
    }

**Comment by karussell** [comment]
The lookup is just not designed for the purpose you are after I think. So if I understand this correctly this is not a bug, it is a feature request :) ? And yes, this would be nice to have! For that to work you would only need a boolean earlyTermination=false or something.

**Comment by KenSoutherland** [comment]
I think it's fine to have that boolean if that is the best solution we can
come up with but I would argue that it is actually a bug since the
filtering and the searching are combined in this function but are at odds
with each other. I will look at a sleaker solution and propose that.

**Comment by KenSoutherland** [comment]
Also, I just realized that the edgeFilter passed into findClosest is completely ignored. It uses the class level edge filter.

**Comment by KenSoutherland** [comment]
I have made pull request [#318](https://github.com/graphhopper/graphhopper/issues/318) to show what I would propose.

**Comment by karussell** [comment]
> that it is actually a bug since the filtering and the searching are combined in this function

No, this is definitely not a bug. The sole purpose of the location index is to find ONE closest matching edge. Even my use case of [map matching](https://github.com/graphhopper/map-matching) is misusage of the index and not really perfect. So, if we want to use the index for other purposes as well, we have to refactor :)

**Comment by KenSoutherland** [comment]
Peter, take a look at my pull request (#315). I think you'll see what I
mean. I too want ONE closest matching edge. And my code in this pull
request does just that. The code as is does not find me anything.

**Comment by karussell** [comment]
I've already commented (on #317) I need your use case

**Comment by karussell** [comment]
As discusses in #318 this is indeed a problem and needs to be fixed.

**Comment by karussell** [comment]
See https://github.com/graphhopper/graphhopper/pull/318#issuecomment-127329395
