### ISSUE TITLE
Version of edges

### ISSUE THREAD

**Issue by mkheyali** [graphhopper/graphhopper#325]
hello everybody
i have a question about Version of edges.
i tried to do all of steps of getting demo of graphhopper from this link
https://github.com/graphhopper/graphhopper/blob/master/docs/android/index.md
and i was succesful to creating graph with maven but when i use my graph in demo graphhopper apk this error occures:
Version of edges unsupported: 5, expected:9
please guide me to create this expected graph.
immediatly help : - (
thank you.

**Comment by devemux86** [comment]
Generally you need to use the same GraphHopper version for building and 
reading your graphs.

-- 
Emux
Cruiser <http://wiki.openstreetmap.org/wiki/Cruiser> - Atlas 
<http://wiki.openstreetmap.org/wiki/Atlas_%28navigation_application%29>

**Comment by devemux86** [comment]
Generally you need to use the same GraphHopper version for building and reading your graphs.

**Comment by mkheyali** [comment]
thanks devemux86.
can you help me more about your suggestion?

**Comment by devemux86** [comment]
I mean, you need to check what GraphHopper version you're using in your application.
And then use the same for building the graph too.

Edge version 5 is from 0.3 GH release I think, version 9 is quite recent.
The latest actually is 10 now.

**Comment by mkheyali** [comment]
ooooohhhhh thank you.
but where can i find this version?

**Comment by devemux86** [comment]
Peter can answer better.
But you can download and build it from this repository.

**Comment by mkheyali** [comment]
ok sir.
when i get this release,how can i use it?
where can i pase it?
sorry i am a biginner.  ;-)

**Comment by karussell** [comment]
Please study the resources more closely:

https://graphhopper.com/#community
https://github.com/graphhopper/graphhopper/blob/0.3/docs/index.md

and avoid creating issues in case of questions

**Comment by karussell** [comment]
There were similar questions to this and maybe the problem was about linking to the unstable documentation where 'git checkout 0.3' is missing? I've fixed this: https://github.com/graphhopper/graphhopper/commit/25f08244b3152343345fa2b01357c08757ef89bf

**Comment by mkheyali** [comment]
hi peter
can you help me to create routing data for my map as version 10 with turncost?

**Comment by karussell** [comment]
See config-example.properties and import your graph with the same version as you use when reading it (e.g. on android or for web)

**Comment by mkheyali** [comment]
Thanks a lot.
i undrestand this about turncost but please guide me what can i do to create routing data for my map as version 10.
:- (

**Comment by karussell** [comment]
Please read the answers again ('use the same for building the graph too.') and see the links!

**Comment by mkheyali** [comment]
ooooh dear,
i read your answer but i am confused yet.
exactly say what things i should be have.
and where should be use them,please.

i replase my pom.xml and graphhopper.sh files with lastest modified them and this error was occured:

C:\Users\M\Documents\GitHub\graphhopper [how-to]> sh ./graphhopper.sh import tehran.osm
## using java  from C:\Program Files\Java\jdk1.7.0_51
## using existing osm file tehran.osm
## now building graphhopper jar: tools/target/graphhopper-tools-0.4-SNAPSHOT-jar-with-dependencies.jar
## using maven at c:\Users\Makeen\Documents\GitHub\maven
## now import. JAVA_OPTS=-Xmx1000m -Xms1000m -server
Error: Could not find or load main class com.graphhopper.tools.Import
