### ISSUE TITLE
Can't run android  demo in eclipse 

### ISSUE THREAD

**Issue by 3c** [graphhopper/graphhopper#328]
in eclipse report :

Unable to execute dex: Multiple dex files define Lorg/slf4j/ILoggerFactory;
Conversion to Dalvik format failed: Unable to execute dex: Multiple dex files define Lorg/slf4j/ILoggerFactory;

I used  graphhopper-0.4-SNAPSHOT-android.jar

**Comment by karussell** [comment]
Maybe #327 will help?

**Comment by 3c** [comment]
I have import project into eclipse .
My problem is when click " Run GraphHopper" 
 if I delete the jar  "slf4j-android-1.6.1-RC1.jar" , the app cun can , but can't route .

**Comment by karussell** [comment]
Well, as this is an eclipse problem I cannot really help you there. Either setup the dependencies via maven or follow this recently added documentation.

**Comment by devemux86** [comment]
This is a build path issue, make sure your classpath doesn't have multiple versions of libraries.

You can try with a combination of ```slf4j-api``` and ```slf4j-android``` jars.

**Comment by 3c** [comment]
Maybe prolbem is in "graphhopper-0.4-SNAPSHOT-android.jar" , the jar has included  something of "slf4j-android-1.6.1-RC1.jar"  ,so error is "Unable to execute dex: Multiple dex files define Lorg/slf4j/ILoggerFactory;.."

I will try with Android studio , use      "./graphhopper.sh android"

**Comment by karussell** [comment]
If you try Android studio you can also have a look into this branch: https://github.com/graphhopper/graphhopper/tree/move_to_android_studio

Feedback is very appreciated for this as we would like to make this the default.

**Comment by 3c** [comment]
Thank you , it's ok , can route with custom map
but there is some little bugs 
1. remote download , eg: hamburg  , has a Toast  :  "An error happened  while ceating graph: Version of edges unsupported:9 , expected:10 "  when start map
2. branch  "move_to_android_studio"  has some problems when import Android studio ,but I'm not sure what  happened after I click some options ,then it's ok

**Comment by karussell** [comment]
> 1.

Yes, the graph files on the server need a reimport ...

> 2.

hmmh, which options :) ?
