### ISSUE TITLE
inconsistent behaviour of InstructionList.find

### ISSUE THREAD

**Issue by jansoe** [graphhopper/graphhopper#331]
In general InstructionList.find(lat, lon, dist) finds the closest point on the route and then yields the upcoming instruction.
In the case the closest point on the route is the start or endpoint of an edge instead the previous instruction is returned.
See: https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/util/InstructionList.java#L319

**Comment by karussell** [comment]
You mean that in the case !validEdgeDistance the index++ could be missing? That would be indeed rare but ugly

**Comment by jansoe** [comment]
yes, thanx for clarification :)

**Comment by karussell** [comment]
Do you have a test case for this?

**Comment by jansoe** [comment]
not yet, but I will write one
