### ISSUE TITLE
Is JSON dependency necessary?

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#332]
For roundabout instructions the json dependency was introduced. I would like to avoid it to make graphhopper easier portable but also more lightweight. JSON belongs to the web module. In the tests we can still use it to verify that real json is produced. I remember that this was introduced as Double.NaN made problems in JSON parsing libraries and we wanted to verify it via 'real' parsing:

```
<dependency>
      <groupId>org.json</groupId>
      <artifactId>json</artifactId>
      <version>20140107</version>
      <scope>test</scope>
</dependency>
```

**Comment by karussell** [comment]
The only necessary change is replacing JSONObject.NULL in RoundaboutInstruction via avoiding the write? E.g.

```java
if (!Double.isNaN(radian))
    tmpMap.put("turn_angle", Helper.round(radian, 2));
```

Also the javadocs for RoundaboutInstruction should be cleaned up (or written ;))

**Comment by karussell** [comment]
> assertEquals("null", json.get("turn_angle").toString());

Indeed, should we prefer a none existing turn_angle?

**Comment by jansoe** [comment]
Yes, I introduced this dependeny soley for cases of undefined turn_angle, but agree that it is perfectly fine to just avoid the write.

**Comment by karussell** [comment]
Ok, I'll fix shortly
