### ISSUE TITLE
graphhopper.sh

### ISSUE THREAD

**Issue by devemux86** [graphhopper/graphhopper#340]
Peter in ```graphhopper.sh``` script at Import action, there is the variable [```$GH_IMPORT_OPTS```](https://github.com/graphhopper/graphhopper/blob/master/graphhopper.sh#L255) which is not filled previously in the script.
Is it needed?

**Comment by devemux86** [comment]
Can you explain also the use of ```printVersion=true``` ?

**Comment by karussell** [comment]
Yes, GH_IMPORT_OPTS is necessary to do e.g. `export GH_IMPORT_OPTS="some.graphhopper.opts"` which could overwrite a main config.properties e.g. to create foot or car profile.

> printVersion=true

looks like it can be removed ;)
