### ISSUE TITLE
CIAT DEM mirror gone

### ISSUE THREAD

**Issue by NopMap** [graphhopper/graphhopper#346]
The class CGIARProvider uses a mirror server for CIAT data at droppr.org/srtm/v4.1/6_5x5_TIFs/.

It appears to me that this server is gone, I cannot find any files at that URL. Can you confirm that the server is gone for you, too?

This can be solved by simply switching back to the original server (commented out in the code). which is working, but much slower.

How did you find this mirror originally? Do you have a contact one could ask whether this is a temporary or permanent loss?

bye, Nop

**Comment by devemux86** [comment]
I can also confirm it.

**Comment by karussell** [comment]
Hmmh, not sure how I found about this URL ... and yes, seems to be down for me too. The best solution would be if someone from the GraphHopper side would host this :). Here are some other alternatives for now:

http://gis-lab.info/data/srtm-tif/
ftp://xftp.jrc.it/pub/srtmV4/tiff/

(ftp://srtm.csi.cgiar.org/SRTM_v41/SRTM_Data_GeoTIFF/)

**Comment by karussell** [comment]
Closing for now, please reopen if the current default is again broken. A lower priority is to improve the download speed via a custom hosting of those files (For now I'won't do this due to time constraints on my side, but maybe others step in).

**Comment by karussell** [comment]
Duplicate: #292

**Comment by karussell** [comment]
> srtm.csi.cgiar.org

This does not work anymore (#1545)

But using http://srtm.csi.cgiar.org/wp-content/uploads/files/srtm_5x5/TIFF/ seems to work
