### ISSUE TITLE
Config properties

### ISSUE THREAD

**Issue by devemux86** [graphhopper/graphhopper#347]
Peter in [```config-example.properties```](https://github.com/graphhopper/graphhopper/blob/master/config-example.properties#L29) you mention ```MMAP_STORE_SYNC``` for memory mapped.
Probably you mean ```MMAP``` ?

**Comment by karussell** [comment]
MMAP alone won't work for a server environment, only for single threaded Android. So with _SYNC it is slower but read-thread-safe.

**Comment by devemux86** [comment]
Shouldn't the ```MMAP_STORE_SYNC``` exist in ```DAType``` class?

**Comment by devemux86** [comment]
Ok I see how you parse it.
I'm closing the issue.

**Comment by devemux86** [comment]
Peter after the latest changes, the config properties file should be updated.
The ```algorithm.defaultVehicle``` appears to redundant now.

**Comment by karussell** [comment]
Indeed - thanks!

**Comment by devemux86** [comment]
Peter I think also the [routing](https://github.com/graphhopper/graphhopper/blob/master/docs/core/routing.md) doc needs updating regarding the default vehicle.

**Comment by karussell** [comment]
Thanks a gain. Fixed.
