### ISSUE TITLE
Store decompressed DEM-info files?

### ISSUE THREAD

**Issue by devemux86** [graphhopper/graphhopper#348]
Could the [dem](https://github.com/graphhopper/graphhopper/tree/master/core/src/main/resources/com/graphhopper/reader/dem) files exist in GH as txt instead of zip (as the [translations](https://github.com/graphhopper/graphhopper/tree/master/core/src/main/resources/com/graphhopper/util) are) ?

(That would be very helpful with tools like ProGuard)

**Comment by karussell** [comment]
Is this [SO question](http://stackoverflow.com/q/27812938/194609) related? Currently I don't see this as a GraphHopper problem. But if you provide a PR and if the test passes and jar is of a similar size we can go for it.

**Comment by devemux86** [comment]
No it's unrelated to that.
It's actually a packaging problem that prevents GH to be used in certain common ways.

**Comment by karussell** [comment]
Please explain what the exact problem is. As I've understood is that proguard takes those zip files and uncompresses them, which is what the SO question described. And why one cannot prevent proguard from doing so?

**Comment by devemux86** [comment]
In that SO question the user mentions that he unzips the zip files in assets folder during runtime. He didn't mention that PG does it, he says instead that it simply fails.

In GH case, the PG process finishes successfully, but it insists to unzip the dem archives to GH root.
I have tried several things to prevent that but without success..

**Comment by karussell** [comment]
So the problem is because the unzipping requires write disc access. We could use some in-memory unzipping, not sure how hard this is probably easier to store them already unzipped.

**Comment by devemux86** [comment]
I'm a bit confused here. I have not said anything about write access, just packaging issues.
Looking at the code probably a replacement of ```ZipInputStream```.

**Comment by karussell** [comment]
Okay, I'm confused too :) as I don't have packaging issues, or issues on Android. And you said that these issues only occur when ProGuard is activated, then why is this a GraphHopper problem?

What is the exact problem you have?

**Comment by devemux86** [comment]
It's a general packaging issue by using ProGuard (the platform is irrelevant as it's Java) as part of an app deploying process.
It probably could be solved by ProGuard side, I have not found the answer :(

My question here is if it's absolutely needed to have in a jar again compressed resources, i.e. dem zip.

**Comment by karussell** [comment]
If you would provide the PR we can test and see if that would work in all scenarios.

**Comment by devemux86** [comment]
Peter I provided the PR https://github.com/graphhopper/graphhopper/pull/378 to see it.
