### ISSUE TITLE
Rare situations let roundabout exit number calculation fail

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#353]
See [here](https://graphhopper.com/maps/?point=54.236042%2C-2.717909&point=54.236779%2C-2.718177) where it says 'Problem occured:RoundaboutInstruction must contain exitNumber>0'

Maybe this is a tagging issue or related to some CH stuff (?)

**Comment by karussell** [comment]
(For switching back on the Directions API / GraphHopper Maps to avoid that exception)

**Comment by jansoe** [comment]
For me it seems  to be a strange tagging http://overpass-turbo.eu/s/7Zv
but I will change the code to handle such cases.

**Comment by karussell** [comment]
Yes, strange but somehow understandable if you look into the [aerial view](https://graphhopper.com/maps/?point=54.236061%2C-2.717839&point=54.236779%2C-2.718177&locale=de&layer=Esri%20Aerial)

**Comment by jansoe** [comment]
now I understand. Actually it's a very nice tagging, to build the correct instructions :)

**Comment by karussell** [comment]
Live again, foot and bike will follow soon
