### ISSUE TITLE
Error in Dijkstra-One-To-Many cache

### ISSUE THREAD

**Issue by thingimon** [graphhopper/graphhopper#362]
As mentioned in issue #239, there was an error in the cache of the Dijkstra-One-To-Many. However, the new version wrongly returns NOT_FOUND when to == currNode (i.e. searching the same path twice in a row). The inequality
```weights[to] < weights[currNode]```
should maybe not be strict?

**Comment by karussell** [comment]
Yes, indeed!

**Comment by karussell** [comment]
Thanks for reporting!
