### ISSUE TITLE
Wrong routing at junction

### ISSUE THREAD

**Issue by escoand** [graphhopper/graphhopper#364]
I've tested the routing but found a small bug:
https://graphhopper.com/maps/?point=50.669824%2C12.451351&point=50.66592%2C12.444549
Maybe it's because the to lanes are not defined as oneway but the correct way is shorter:
https://graphhopper.com/maps/?point=50.670028%2C12.446823&point=50.669708%2C12.442033&point=50.667597%2C12.443701

**Comment by escoand** [comment]
Also this is not possible:
https://graphhopper.com/maps/?point=50.669966%2C12.446828&point=50.668742%2C12.442548&point=50.667597%2C12.443701

**Comment by karussell** [comment]
GraphHopper Maps uses the speed-up mode which currently does not support turn restrictions. See #270
