### ISSUE TITLE
Walking Directions 

### ISSUE THREAD

**Issue by jmunowitch** [graphhopper/graphhopper#366]
It looks like walking directions do not allow routing on Train Platforms:

http://www.openstreetmap.org/directions?engine=graphhopper_foot&route=37.73234%2C-122.43382%3B37.73400%2C-122.43401#map=18/37.73334/-122.43381
vs
http://www.openstreetmap.org/directions?engine=graphhopper_foot&route=37.73242%2C-122.43372%3B37.73400%2C-122.43401#map=18/37.73318/-122.43224

This can be an issue when trying to route to Public Transit stops.

**Comment by karussell** [comment]
Strange, as we do accept them: See FootFlagEncoder: acceptedRailways.add("platform");
Will look into it.

**Comment by karussell** [comment]
Okay, this is fixed and tested in https://github.com/graphhopper/graphhopper/commit/cc4b114272dc37b860ced8bf78b9f558228ead6c will close when deployed and verified. Thanks for reporting!

**Comment by jmunowitch** [comment]
Great! Thanks for the quick response.

**Comment by karussell** [comment]
Deployed.
