### ISSUE TITLE
Speed zero should leed to access=no

### ISSUE THREAD

**Issue by zhiqiangZHAO** [graphhopper/graphhopper#367]
looks like something wrong here:
https://graphhopper.com/maps/?point=38.942477%2C-77.418699&point=38.95018%2C-77.404784&locale=en-US&layer=Lyrk

**Comment by zhiqiangZHAO** [comment]
looks like something wrong with an edge: 
http://www.openstreetmap.org/edit?editor=id&way=141900856#map=18/38.95066/-77.40282

**Comment by zhiqiangZHAO** [comment]
I am test car with turn restriction.

**Comment by zhiqiangZHAO** [comment]
The problem is related speed=0.

**Comment by zhiqiangZHAO** [comment]
https://github.com/graphhopper/graphhopper/issues/242

The original edge has a tag: max_speed=1, I remove it.

There shouldn't be an edge with 1 MPH for car in reality.

In Graphhopper, the speed shouldn't be 0.
If a edge with speed 0, should change it to unnavigable.

**Comment by karussell** [comment]
Thanks for reporting and investigating. I think we should set this as unnavigable in the import if speed is 0, otherwise we would have to check the speed on every read which is too expensive

**Comment by zhiqiangZHAO** [comment]
I prefer to ignore maxspeed=1, it's ridiculous.

Yes. Definitely there shouldn't be an edge with speed=0.
map matching found it as the origin, but it's not searchable due to speed=0.

**Comment by zhiqiangZHAO** [comment]
what I have saw the real maxspeed is 5 MPH.
Usually it's in parking lot.
How could be 1 MPH, it's slower than walk.

**Comment by karussell** [comment]
> I prefer to ignore maxspeed=1, it's ridiculous

Hmmh, not sure. At least we'll set accessibility to no in case of speed is 0

**Comment by zhiqiangZHAO** [comment]
That's also good.
At least the road with very low speed are very rare.

**Comment by zhiqiangZHAO** [comment]
btw, OSRM don't have this problem. 
http://www.openstreetmap.org/directions?engine=osrm_car&route=38.95103%2C-77.40297%3B38.95082%2C-77.40479#map=18/38.95102/-77.40388

http://www.openstreetmap.org/directions?engine=osrm_car&route=38.95111%2C-77.40283%3B38.95082%2C-77.40479#map=18/38.95102/-77.40381

I guess this due to the compression of speed in GH.

**Comment by karussell** [comment]
They do not take into account the road probably due to speed == 0

But again, this is easy to fix directly on import

**Comment by andreaswolf** [comment]
@zhiqiangZHAO just a sidenote: Some people might have used maxspeed=1/0 as a binary flag (“there is a speed restriction”).

**Comment by zhiqiangZHAO** [comment]
@karussell the speed is not 0. the max speed is 1. when GH try to encode it, it turn to 0.

**Comment by zhiqiangZHAO** [comment]
@andreaswolf I don't understand what you mean here. Could you explain what maxspeed=1/0 means?

**Comment by andreaswolf** [comment]
@zhiqiangZHAO I mean that some mappers could use maxspeed as a binary flag: 0 = there is no speed limit, 1 = there is a speed limit (but I don’t know it). This is of course not so clever, but some OSM mappers might still use it. Therefore, I’d not interpret speed limits that low, but only use limits from ~ 5 km/h on.

I tried to filter a map of Germany for such low speed limits, but I did not succeed – either there is no such entry, or I did something wrong. Don’t know, I’m not too much into the details of osmosis.

**Comment by andreaswolf** [comment]
Actually, this does not seem to be a really big problem:

* https://taginfo.openstreetmap.org/tags/maxspeed=1: 114 usages
* https://taginfo.openstreetmap.org/tags/maxspeed=0: 1 usage

**Comment by zhiqiangZHAO** [comment]
Thanks @andreaswolf.
Good to know this interesting convention.

**Comment by andreaswolf** [comment]
@karussell @jansoe any opinion on this? I think this could be dropped, as the mentioned attribute values are nearly unused.

**Comment by karussell** [comment]
Yes, but I think GraphHopper should still properly handle if speed is near 0. E.g. if precision is 5 and speed is 4 then it will set it to 0. In that case it is okayish BUT if this happens in import the access flag has to be set to false.

**Comment by karussell** [comment]
Please review the fix and let me know if this is okay
