### ISSUE TITLE
Shortest vs fastest in CH mode ?

### ISSUE THREAD

**Issue by martinsauvage** [graphhopper/graphhopper#370]
Hello,

I'm evaluating shortest / fastest route on Android using GH 0.4:

hopper = new GraphHopper().forMobile();
hopper.setCHWeighting("shortest");
hopper.load(path);

I don't see real differences between 2 options for short itinerary eg less than 10 or 20 km (by the way shortest option seems to take longer time). Could you tell me if this setting is really operationnal? If so, how do you make decision for fastest option (I guess taking principal road eg OSM: highway=primary)?

Thanks,
Martin

**Comment by karussell** [comment]
For discussion we should really use the mailing list.

> Could you tell me if this setting is really operationnal?

We think so ;) as we have tests for this. Note: you can either operate as shortest or fastest for CH, not both. So once you have prepared the graph (and eg. copied to Android) no change is currently possible.

> if so, how do you make decision for fastest option

Yes, we use the speed according to the highway, see speed map in CarFlagEncoder

**Comment by martinsauvage** [comment]
OK thanks, I will post a message within mailing list for this topic...
Sorry
