### ISSUE TITLE
Routing with disconnected oneway parts

### ISSUE THREAD

**Issue by jtheuer** [graphhopper/graphhopper#373]
This error happened on http://www.openstreetmap.org/directions?engine=osrm_car&route=48.89872%2C9.20377%3B53.55034%2C10.00065#map=19/48.89837/9.20437 but it is a general routing issue:

When i search for "Klinikum Ludwigsburg" as start point, the matched point is a oneway without exit and I therefore cannot find a route.
Should we remove the path during import somehow?

Jan

**Comment by jtheuer** [comment]
Sorry, this is an OSRM issue, I was using the wrong sport type. It works in Graphhopper. How did you fix this?

**Comment by karussell** [comment]
We remove small disconnected areas see #235

This works perfectly for one profile but not for multiple where a different approach is necessary.
