### ISSUE TITLE
GH doesn't respect construction tag?

### ISSUE THREAD

**Issue by zhiqiangZHAO** [graphhopper/graphhopper#375]
http://wiki.openstreetmap.org/wiki/Key:construction

I don't find GH parse construction.

**Comment by karussell** [comment]
As we don't want to route on highway=construction there shouldn't be a problem or do you mean #374?

**Comment by zhiqiangZHAO** [comment]
there are way with construction=yes.

**Comment by karussell** [comment]
Do you have an example or even the count? As the wiki says: "construction=* must be used together with tags such as highway=construction, railway=construction, landuse=construction, and building=construction"

**Comment by zhiqiangZHAO** [comment]
yeah, not too much.

http://www.openstreetmap.org/way/83051200

**Comment by zhiqiangZHAO** [comment]
In my mind, highway= is the road classification.
construction=yes/no is the status.
Shouldn't combine them.
:)

**Comment by karussell** [comment]
The wiki is often confusing but in this case very clear, I would see this as a tagging mistake. Unless there are several hundreds/thausand occurrences. Or maybe we wait a bit what others say.

**Comment by matkoniecz** [comment]
> there are way with construction=yes.

It is a terrible tagging scheme that should be retagged to highway=construction, construction=highway_type

See https://josm.openstreetmap.de/ticket/11232 and https://josm.openstreetmap.de/ticket/11146 for custom validator rules for JOSM allowing detection and/or fixing this problem.

highway=construction is about 20 times more popular, supporting construction=yes is encouraging bad tagging schemes.

**Comment by karussell** [comment]
Thanks for the input! So we should indeed just support conditional #374?

**Comment by matkoniecz** [comment]
Yes, supporting highway=construction and #374 should be enough enough. Supporting construction=yes gives really minor gain at cost of increased complexity of program and harming quality of OSM data in long run.

**Comment by karussell** [comment]
Okay closing here in favour of #374
