### ISSUE TITLE
Ability to load custom FlagEncoders from config was removed. Why?

### ISSUE THREAD

**Issue by crowmagnumb** [graphhopper/graphhopper#389]
I have custom flag encoders that I use for many purposes.

I have my own FootFlagEncoder that allows you to traverse on private property (I use this for GasMain routing).
I have a FeederPatrolCarFlagEncoder that doesn't allow you to drive on highways.

I have a TruckFlagEncoder that doesn't route you on roads that don't allow trucks. hgv=no

And now these don't work anymore when I create my data. What gives with removing this functionality?!

**Comment by karussell** [comment]
A 'don't work' is too broad :)

What is the error message and what do you mean with 'What gives with removing this functionality'?

**Comment by jansoe** [comment]
Do you use the current master? I recently [introduced a new Variable maxPossibleSpeed](https://github.com/graphhopper/graphhopper/commit/24d4c7d20a49904cd90b4ae696a096dd34d68727#diff-fee5b5dbf8714eef63483b55be303d5cR59) which you might have to set in your encoders?

**Comment by karussell** [comment]
Good catch, we should definitely throw an exception in the Encoded(Double)Value if wrong init values (e.g. incorrect intervals like 20->0 or 0->0)

**Comment by crowmagnumb** [comment]
Sorry for my vagueness. I thought you would know what I meant. In commit
XXX a change was made to EncodingManager to take away the parsing of the
config property YYY that allowed you to specify your own FlagEncoder
class.  This code was removed....

try- {- @SuppressWarnings("unchecked")- Class<FlagEncoder> cls = (Class<
FlagEncoder>) Class.forName(className);- FlagEncoder fe = (FlagEncoder) cls.
getDeclaredConstructor().newInstance();- resultEncoders.add(fe);- } catch (
Exception e)- {- throw new IllegalArgumentException("Cannot instantiate
class " + className, e);- }

... and in my config.properties for importing data I have the property ...

graph.flagEncoders=FOOT:com.samsix.graphhopper.S6FootFlagEncoder,CAR:com.samsix.graphhopper.S6CarFlagEncoder

... which used to instantiate my own car encoder for type "CAR" and I was
just about to add another for TRUCK *and* something I was going to call
FEEDERPATROL.

**Comment by karussell** [comment]
> This code was removed....

Ah, yes, now I know what you mean. This was done because we wanted to get rid of reflections in the core. You can easily create your own GraphHopper class and add those encoders to the encoding manager.

**Comment by karussell** [comment]
E.g. see the [import](https://github.com/graphhopper/graphhopper/blob/master/tools/src/main/java/com/graphhopper/tools/Import.java) and additionally do 

`hopper.setEncodingManager(new EncodingManager(new XYFlagEncoder(), new ABFlagEncoder()))`

**Comment by crowmagnumb** [comment]
Ah, OK. I'll give that go. Cheers.

**Comment by karussell** [comment]
I'm closing this. Let me know if you cannot find a solution in your case!

**Comment by crowmagnumb** [comment]
Ah, sorry, forgot to reply that the above idea worked for me. Cheers!
