### ISSUE TITLE
It looks like this is not correct based on method signature

### ISSUE THREAD

**Issue by zhiqiangZHAO** [graphhopper/graphhopper#392]
@Override
    protected AStarEdge createEdgeEntry( int node, double dist )
    {
        return new AStarEdge(EdgeIterator.NO_EDGE, node, dist, dist);
    }

Although it not affect, it's not correct.
the 3rd parameter should be weight to compare.
the 4th parameter should be weight already visited.

Now, they are just distance, not weight at all.

**Comment by karussell** [comment]
it should be renamed to weight, as it is currently only used for the initial edge entry creation where dist=weight=0. Or did you found a bug due to this?

**Comment by zhiqiangZHAO** [comment]
I don't find any buy.
I understand it has no effect on the correctness.
But it's not correct.
:)

**Comment by karussell** [comment]
Please review if this fixes the problem.
