### ISSUE TITLE
Miles instead of Kilometers?

### ISSUE THREAD

**Issue by DenisCarriere** [graphhopper/graphhopper#396]
Is it possible to include the desired measurement unit in the URL parameter?

I am trying to have the output distances as miles instead of kilometers.

Issue #95 mentioned it, but it doesn't seem to work anymore:

> But you can also force the locale via an URL parameter e.g. to show miles vs. km:
> http://graphhopper.com/maps/?point=Kiel&point=M%C3%BCnchen&locale=en_US

**Comment by karussell** [comment]
We decided to do this on the client side but not yet done

**Comment by devemux86** [comment]
I agree with that approach.
I think the internal calculations should be done in the SI system and the clients could convert the values as they like.

**Comment by chimbs86** [comment]
So I was trying my hand at this. I see that the com.graphhopper.routing.Path
has a getDistance() method which returns a distance. And here I can add a getDistanceInImperialUnits() as a wrapper around the getDistance() which will use a metric to impeerial conversion and then modify the web interface to display this. Is that a valid approach? Or would you suggest something else instead

**Comment by chimbs86** [comment]
Alternatively, I could only modify the GHResponse to display the imperial distances and thus not change any underlying functionality. Now that I think about it, that seems like a better alternative. 
res.setDistance(distance).setTime(time); this method called in the graphhopper.java will do just that.

**Comment by karussell** [comment]
Hi, thanks. Just converting this in the web UI would be sufficient, so no server or API change is necessary. For that one would need somehow an options button where the user can change these settings. And by default just using km is fine :)

**Comment by ammagamma** [comment]
#778

**Comment by karussell** [comment]
Fixed - thanks @ammagamma !

**Comment by fbonzon** [comment]
The scale could be updated too, to show only the relevant unit (km or mi) depending on this new units switch, instead of showing both. Sent #782.
