### ISSUE TITLE
GH doesn't respect restriction=only_right_turn?

### ISSUE THREAD

**Issue by zhiqiangZHAO** [graphhopper/graphhopper#398]
Hi,

https://graphhopper.com/maps/?point=53.589197%2C10.057624&point=53.590502%2C10.058069&locale=en-US&layer=Lyrk

And there is a restriction: http://www.openstreetmap.org/relation/51157

**Comment by karussell** [comment]
The speed mode does not support turn restrictions at the moment. Or do you mean that this does not work for the flexibility mode?

**Comment by zhiqiangZHAO** [comment]
You mean https://graphhopper.com/maps/ use speed model by default?
Can I turn of speed model on https://graphhopper.com/maps/ ?

**Comment by karussell** [comment]
Good question, currently it should work to perform normal algorithms on prepared graph, but it won't work here and also the graph has no turn restrictions collected while import.

**Comment by karussell** [comment]
Please reopen if you need such a feature.
