### ISSUE TITLE
Priority bug for WORST value

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#399]
I got an email with:

*I think there may be a bug in the priority weighting (we’ve copied the motorcycle flag encoder) as if the GetDouble method uses the UNCHANGED value if the priority weighting returns zero which is also the weighting value for WORST.  This would mean that WORST roadtypes are treated the same as UNCHANGED.*

**Comment by karussell** [comment]
The problem is that WORST is 0 which is also used for UNCHANGED in the special clause if ret == 0 then return UNCHANGED. Instead we should think about using negative values for bad priorities and still keep the order of the priorities. Then the following test should run through:

```java
@Test public void testUnchangedVersusWorstPriority_issue399()
{
    OSMWay way = new OSMWay(1);
    way.setTag("highway", "tertiary");
    long encoded = encoder.acceptWay(way);
    long flags = encoder.handleWayTags(way, encoded, 0);

    assertEquals(UNCHANGED.getValue(), encoder.getLong(flags, PriorityWeighting.KEY));
    assertEquals((double) UNCHANGED.getValue() / BEST.getValue(), encoder.getDouble(flags, PriorityWeighting.KEY), .1);

    MotorcycleFlagEncoder motorEncoder = new MotorcycleFlagEncoder(5, 5, 0)
    {
        @Override
        protected int calcPriority( OSMWay way, long relationFlags )
        {
            return PriorityCode.WORST.getValue();
        }
    };
    new EncodingManager(motorEncoder);

    encoded = motorEncoder.acceptWay(way);
    flags = motorEncoder.handleWayTags(way, encoded, 0);
    assertEquals(WORST.getValue(), motorEncoder.getLong(flags, PriorityWeighting.KEY));
    assertEquals((double) WORST.getValue() / BEST.getValue(), motorEncoder.getDouble(flags, PriorityWeighting.KEY), .1);
}
```

**Comment by ratrun** [comment]
Why not just remove the value WORST from the PriorityCode enum ? 
This brings the benefit that priority changing upwards and downwards is symmetrical. It is unlogical that there should be 4 values for decreasing the priority down and only 3 values for boosting up.

**Comment by karussell** [comment]
Yes, just removing WORST is also listed as possibility here, not sure. For 3 bits we have 8 possibilities and we should use them

**Comment by karussell** [comment]
Will remove WORST for now as a workaround, still letting this open and postponing.

**Comment by karussell** [comment]
Ok, using now a simple solution: always writing a value - i.e. we do not need a default to retrieve if 'empty'

**Comment by ratrun** [comment]
The change 29dc23a looks a bit strange to me - these two Priority enums have now the same value 7. Is this per intention? I don't think so:
`
    VERY_NICE(7),
    BEST(7);
`
A lots of tests fail and I doubt that they only fail for me.

**Comment by karussell** [comment]
Yes, currently fixing it ...

**Comment by karussell** [comment]
But the problematic change was not introduced here nor in 29dc23a ... see https://github.com/graphhopper/graphhopper/pull/476#issuecomment-129911374
