### ISSUE TITLE
build fails on clean install of jdk1.7, android sdk and android studio

### ISSUE THREAD

**Issue by xtile** [graphhopper/graphhopper#402]
Error:Failed to resolve: com.graphhopper:graphhopper:0.4-SNAPSHOT

where should i look to?

**Comment by devemux86** [comment]
Can you try with GraphHopper 0.4.1 ?

-- 
Emux
Cruiser <http://wiki.openstreetmap.org/wiki/Cruiser> - Atlas 
<http://wiki.openstreetmap.org/wiki/Atlas_%28navigation_application%29>

**Comment by devemux86** [comment]
Can you try with GraphHopper 0.4.1 ?

Also for question please use the mailing list.
https://lists.openstreetmap.org/listinfo/graphhopper

**Comment by karussell** [comment]
Would you please give us the full error message? Also try with 0.5-SNAPSHOT. On travis everything is fine so I expect either some local setup problem or a network issue.

**Comment by xtile** [comment]
Thanks, changing version to 0.4.1 helped (also with changing resp.gettime() to resp.getmillis() in mainactivity.java.

0.5-SNAPSHOT also gives an error
here is it: 
------------
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.graphhopper:graphhopper:0.5-SNAPSHOT.
     Searched in the following locations:
         file:/C:/Users/user/.m2/repository/com/graphhopper/graphhopper/0.5-SNAPSHOT/maven-metadata.xml
         file:/C:/Users/user/.m2/repository/com/graphhopper/graphhopper/0.5-SNAPSHOT/graphhopper-0.5-SNAPSHOT.pom
         file:/C:/Users/user/.m2/repository/com/graphhopper/graphhopper/0.5-SNAPSHOT/graphhopper-0.5-SNAPSHOT.jar
         https://repo1.maven.org/maven2/com/graphhopper/graphhopper/0.5-SNAPSHOT/maven-metadata.xml
         https://repo1.maven.org/maven2/com/graphhopper/graphhopper/0.5-SNAPSHOT/graphhopper-0.5-SNAPSHOT.pom
         https://repo1.maven.org/maven2/com/graphhopper/graphhopper/0.5-SNAPSHOT/graphhopper-0.5-SNAPSHOT.jar
         file:/C:/Users/user/AppData/Local/Android/sdk/extras/android/m2repository/com/graphhopper/graphhopper/0.5-SNAPSHOT/maven-metadata.xml
         file:/C:/Users/user/AppData/Local/Android/sdk/extras/android/m2repository/com/graphhopper/graphhopper/0.5-SNAPSHOT/graphhopper-0.5-SNAPSHOT.pom
         file:/C:/Users/user/AppData/Local/Android/sdk/extras/android/m2repository/com/graphhopper/graphhopper/0.5-SNAPSHOT/graphhopper-0.5-SNAPSHOT.jar
         file:/C:/Users/user/AppData/Local/Android/sdk/extras/google/m2repository/com/graphhopper/graphhopper/0.5-SNAPSHOT/maven-metadata.xml
         file:/C:/Users/user/AppData/Local/Android/sdk/extras/google/m2repository/com/graphhopper/graphhopper/0.5-SNAPSHOT/graphhopper-0.5-SNAPSHOT.pom
         file:/C:/Users/user/AppData/Local/Android/sdk/extras/google/m2repository/com/graphhopper/graphhopper/0.5-SNAPSHOT/graphhopper-0.5-SNAPSHOT.jar
     Required by:
         android:app:unspecified

**Comment by karussell** [comment]
Did you enable this to enable snapshots in gradle?

```
/** only necessary if you need to use latest SNAPSHOT
configurations.all {
    // check for updates every build
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}
 **/
```

**Comment by karussell** [comment]
Closing here ... please reopen if not fixed
