### ISSUE TITLE
OSGI  support

### ISSUE THREAD

**Issue by bhack** [graphhopper/graphhopper#404]
There [was some effort](https://github.com/nicolas-f/osgi-dependencies/blob/master/graphhopper-osgi/pom.xml) to let grapphopper run as an osgi bundle by @nicolas-f.
It could be interesting to have the official version "osgi compatible".

**Comment by karussell** [comment]
Interesting. Lots of questions:
 * Is just the pom change necessary?
 * And can we verify e.g. via a unit test that it still works after changes/refactorings? 
 * Under which license are the changes available?
 * It looks we need trove etc also osgi compatible (?)

**Comment by nicolas-f** [comment]
Hi,

`Is just the pom change necessary?`

Yes. A maven plugin will feed the `MANIFEST.MF` file in the jar with additional information.

`And can we verify e.g. via a unit test that it still works after changes/refactorings?`
This modification doesn't affect the packages or class.

`Under which license are the changes available?`
This is only configuration. But if you update your pom this is not the same configuration as you don't have to embed graphhopper dependency.

`It looks we need trove etc also osgi compatible (?)`

Trove is not OSGi compatible. However this is not a problem.

**Comment by karussell** [comment]
> But if you update your pom this is not the same configuration as you don't have to embed graphhopper dependency.

Ah, okay. Now I also understand this a bit more. So this change does not really belong to graphhopper itself but to applications using graphhopper. So maybe we just mention this pom in the documentation or which change do you propose @bhack ?

**Comment by nicolas-f** [comment]
@karussell The same change I push to @Benoker https://github.com/Benoker/DockingFrames/pull/31 and https://github.com/Benoker/DockingFrames/pull/35

**Comment by karussell** [comment]
If this is just what is needed, please go ahead and create a pull request, would be appreciated!

**Comment by karussell** [comment]
This wasn't a priority until then, so I'm closing here.
