### ISSUE TITLE
Configure GraphHopper to route where bus tag equals yes

### ISSUE THREAD

**Issue by jskidd3** [graphhopper/graphhopper#406]
Our service uses GraphHopper to create a road route for bus services where the bus stops are the waypoints along the route.

We have one problem doing this which commonly happens around busy city centres. Here is an example of a way that causes problems: http://www.openstreetmap.org/way/177087237#map=19/53.37773/-1.46455

You will see that one of its tags allows buses. Is there any way we can configure GraphHopper to allow this tag? Currently the route changes to a very long way around which I assume is because GraphHopper sees `motor_vehicle = no` in its default configuration and finds another route.

I would be very grateful of any help!

**Comment by zhiqiangZHAO** [comment]
read core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java

**Comment by jskidd3** [comment]
@zhiqiangZHAO Thanks so much! I'm assuming I just need to make changes in `acceptWay` which is fine, I can do that. What I'm not sure how to do is then recompile the .jar, do you know if there are any tutorials for that? I'm fairly new to Java. Thanks again

**Comment by zhiqiangZHAO** [comment]
GH use Maven.

It should be:
mvn clean
mvn compile
mvn package

just google it.

**Comment by karussell** [comment]
Please use the mailing list for questions. And any Java IDE will do it.
