### ISSUE TITLE
sac_scale handling for foot routing

### ISSUE THREAD

**Issue by MarkPflug** [graphhopper/graphhopper#416]
I was looking at trails in my area and found a trail that graphhopper refused to route through. I dug into what was going on and discovered it was because the trail was incorrectly labelled with sac_scale=yes. "yes" is not a valid value for the sac_scale. I corrected the way on OSM to not have a sac_scale at all.

Example (still not routing properly, probably due to stale data):
http://www.openstreetmap.org/directions?engine=graphhopper_foot&route=45.57319%2C-122.10815%3B45.57152%2C-122.10707#map=18/45.57240/-122.10835&layers=C

This is the history for the way in question:
http://www.openstreetmap.org/way/144841610/history

I'm not sure how often an incorrect sac_scale value might be applied, but it might be better to invert the condition in FootFlagEncoder class to check for, and prohibit "demanding_alpine_hiking" and "difficult_alpine_hiking" only. Of course this might have the opposite effect of possibly routing people on too-dangerous paths.

**Comment by karussell** [comment]
When did you update it?

> Of course this might have the opposite effect of possibly routing people on too-dangerous paths.

Yeah, we prefer the safe route

**Comment by MarkPflug** [comment]
I edited it about 5h ago. At exactly: Wed, 20 May 2015 02:29:12 PM UTC.

> Yeah, we prefer the safe route.

I don't know how common demanding|difficult_alpine_hiking paths are, I've never heard of the sac scale before now. It seems to me that misunderstanding/misuse of this key would be more likely to cause problems, as was the case for this particular trail. The OSM editing UI doesn't even offer demanding|difficult_alpine_hiking as options for the sac_scale, which makes me think that perhaps the intent is that trails of that grade simply aren't considered "footpaths" any more.

I'm very new to OSM, how difficult is it to discover/query misuse of the sac_scale key? Cleaning up the data seems like the **best** solution, but the easiest solution would still be to change the graphhopper code. The MapQuest foot routing has no issue with pathing on sac_scale=yes, by comparison.

**Comment by MarkPflug** [comment]
I was able to find more info with the overpass tool: http://overpass-turbo.eu/

It looks like this one trail is the *only* instance of sac_scale=yes in North America. There appear to be a lot that are labeled this way in Europe though. Perhaps it would be better to treat sac_scale=yes as equivalent to sac_scale=hiking, which I think is probably the intent?

**Comment by karussell** [comment]
> I edited it about 5h ago. At exactly: Wed, 20 May 2015 02:29:12 PM UTC.

It should be taken into account roughly 1 day afterwards.

> I've never heard of the sac scale before now. 

We've several users and customers that know several areas e.g. in the Alps, so this is important to get right :)

> Perhaps it would be better to treat sac_scale=yes as equivalent to sac_scale=hiking, 
> which I think is probably the intent?

We would need something in the OSM wiki which defines this better, but good to know. Maybe @ratrun knows more about this :) ?

Here is a nice 'counter' application:
http://taginfo.openstreetmap.org/keys/sac_scale#values
http://taginfo.openstreetmap.org/search?q=sac_scale%3Dyes

**Comment by MarkPflug** [comment]
Thanks, the taginfo tools looks useful.
I think I'm convinced now that this is really a data-cleanliness issue in the OSM data.

**Comment by MarkPflug** [comment]
Doing a quick survey of sac_scale misuse in North America and that taginfo tool, I also noticed that there is some usage of semicolon delimited sac_scale values, ie "hiking;mountain_hiking". This tag is applied to section of the Appalachian Trail, which is a pretty major trail system.
http://www.openstreetmap.org/way/236355530

Is this an improper use of the sac_scale key? Should only the most difficult sac value be applied (montain_hiking in this case)? Should GraphHopper be changed to handle this?

**Comment by ratrun** [comment]
I remember that I created this sac_scale handlingbased on the pictures shown on http://wiki.openstreetmap.org/wiki/DE:Key:sac_scale. I was intentionally very cautious not to allow the dangerous sac_scales and also because the code is shorter, I decided to only deal with the easy ones and therefore explicitly listed these two. Every other sac_scale type is also considered as dangerous.
This is the reason that tagging errors like `sac_scale=yes` are considered as dangerous too,

Probably it would be better to revert the logic and define a list of prohibited sac_scale tags and allow all the rest.
Would you accept such a pull request?
The drawback is that if somebody tags a sac_scale as `onlyforprofessionalclimers` we would route over it.

**Comment by karussell** [comment]
I would prefer to keep it as it is: just using safe known values and if some new ones come in the can and will be easily added.

**Comment by MarkPflug** [comment]
Regarding the semicolon delimited values: I think this is probably a result of two ways being merged in the OSM editor. I noticed this when I was editing. So, I think it should be a matter of fixing the way to be tagged with the most difficult sac value from the set of delimited values. I think I agree that nothing should be changed. Thanks for your time.

**Comment by karussell** [comment]
Can we close?

**Comment by ratrun** [comment]
In case that you are happy with the current behaviour then close it.

**Comment by karussell** [comment]
it is not about me, it is about the issue creator and others who disagree
