### ISSUE TITLE
ETA Graphhopper 0.5

### ISSUE THREAD

**Issue by dewos** [graphhopper/graphhopper#418]
Hello there. I'm wondering if there is any ETA for the 0.5 version. Any time frame at all? 
I'm right now on SNAPSHOT lock, but a STABLE version would be much appreciated. Thanks.

**Comment by karussell** [comment]
no, sorry, we cannot give ETAs. It really depends on the community, pull requests and paying customer requests. Even the linked issues for 0.5 are not obligatory and also we could add more to them in the next weeks. We plan something for this year though ;)

**Comment by dewos** [comment]
Good to know. Thanks Peter!
