### ISSUE TITLE
get/setRadians misleading

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#424]
Some minor notes, which I stumbled over when [parsing the turn angle from json response](https://github.com/graphhopper/directions-api-java-client/commit/569d91a004fbf107f8d8579acb501f736f15dc1e#diff-8e8e01ea3bb10fbd1be8f469909ae512R198) in the java client:

 * getRadians should be renamed to getTurnAngle otherwise this is misleading naming. E.g. setRadian(getRadian()) should leave radian unchanged.
 * why are there two methods? .setRadian(deltaInOut).setDirOfRotation(deltaOut)
 * instead of 'double tmpRadian = Math.PI - clockwise * radian; tmpRadian *= clockwise;' shouldn't we do 'double tmpRadian = Math.PI * clockwise - radian;'
 * avoid encoder.K_ROUNDABOUT and use FlagEncoder.K_ROUNDABOUT

assigned @jansoe but of course I also can do this :)

**Comment by jansoe** [comment]
I will do it.

[] rename getRadians to getTurnAngle is important!
[] refactor double tmpRadian = Math.PI * clockwise - radian
[] avoid encoder.K_ROUNDABOUT and use FlagEncoder.K_ROUNDABOUT
[] better documentation 

> why are there two methods? .setRadian(deltaInOut).setDirOfRotation(deltaOut)

set Radian just determines the radian (clockwise) between entrance (in) and exit (out).
setDirOfRotation determines the driving direction. Thus they need different input.

**Comment by karussell** [comment]
@jansoe do you agree with my changes?
