### ISSUE TITLE
graphhopper/web: Downloaded gpx-File is called xxx.gpx.json

### ISSUE THREAD

**Issue by chrissssss** [graphhopper/graphhopper#428]
Tested on https://graphhopper.com/maps/?point=hamburg&point=berlin&point=Frankfurt%20am%20Main%2C%20Deutschland&point=münchen&locale=de-de&layer=Lyrk

CURRENT:
Click Download link for GPX
Resulting file is called xxx.gpx.json

EXPECTED:
Resulting file is called xxx.gpx (without Suffix .json)

**Comment by karussell** [comment]
Strange, for me the file name is always GraphHopper.gpx

What browser and OS are you using?

**Comment by chrissssss** [comment]
It's latest Safari on Mac OS X Yosemite.
Am 31.05.2015 11:46 schrieb "Peter" <notifications@github.com>:

**Comment by karussell** [comment]
Still can't reproduce it on an older mac/safari, but as it prints 'JSON file' in the download dialog something is wrong here.

**Comment by karussell** [comment]
There was a bug I fixed now in our authentication layer for the Directions API which assumed JSON for an empty Content-Type in the request. Can you please verify if this also fixes your problem?

**Comment by karussell** [comment]
Please reopen if not fixed for you.

**Comment by chrissssss** [comment]
Working. File is now called Graphhopper.gpx

**Comment by karussell** [comment]
Perfect - thanks for confirming this!
