### ISSUE TITLE
BikeCommonFlagEncoder should respect  "oneway:bicycle=no" AND  "cycleway=opposite"

### ISSUE THREAD

**Issue by chrissssss** [graphhopper/graphhopper#429]
Currently the bike flag encoder does not respect "cycleway=opposite". 
It should respect both "oneway:bicycle=no" AND "cycleway=opposite"

**Comment by karussell** [comment]
This should be handled - do you have an example where this is failing?

**Comment by chrissssss** [comment]
Hi!
It fails on
https://graphhopper.com/maps/?point=50.167704%2C8.619938&point=50.169628%2C8.622122&vehicle=bike&locale=de-de&elevation=true&layer=Lyrk
I've made a fix on openstreetmap for that, but I think it's better to have
that behaviour inside graphhopper since the suggestion on the wiki also
states that both ways of tagging are valid



Peter <notifications@github.com> schrieb am Mo., 1. Juni 2015 um 13:15 Uhr:

**Comment by karussell** [comment]
Thanks

> I've made a fix on openstreetmap for that

What needed to be fixed here?

Again, it should already support both tags. Would you include the detailed tagging before and after your change?

**Comment by chrissssss** [comment]
Hi! Changeset is at http://www.openstreetmap.org/changeset/31630269

<osmChange version="0.6" generator="OpenStreetMap server"
copyright="OpenStreetMap and contributors" attribution="
http://www.openstreetmap.org/copyright" license="
http://opendatacommons.org/licenses/odbl/1-0/">
<modify>
<way id="28301890" changeset="31630269" timestamp="2015-06-01T10:45:58Z"
version="7" visible="true" user="Chrissssss" uid="2956267">
<nd ref="30431134"/>
<nd ref="697315123"/>
<nd ref="30431137"/>
<nd ref="30431121"/>
<tag k="cycleway" v="opposite"/>
<tag k="highway" v="residential"/>
<tag k="name" v="Spielsgasse"/>
<tag k="oneway" v="yes"/>
<tag k="oneway:bicycle" v="no"/>
</way>
</modify>

<modify>
<way id="25410439" changeset="31630269" timestamp="2015-06-01T10:45:59Z"
version="8" visible="true" user="Chrissssss" uid="2956267">
<nd ref="276935168"/>
<nd ref="401562620"/>
<nd ref="30431133"/>
<tag k="cycleway" v="opposite"/>
<tag k="highway" v="residential"/>
<tag k="maxspeed" v="30"/>
<tag k="name" v="Spielsgasse"/>
<tag k="oneway" v="yes"/>
<tag k="oneway:bicycle" v="no"/>
</way>
</modify>
</osmChange>

It's
<tag k="oneway:bicycle" v="no"/>
what I've added

Peter <notifications@github.com> schrieb am Mo., 1. Juni 2015 um 13:28 Uhr:

**Comment by ratrun** [comment]
The problem occurs in case that both tags `oneway` and `oneway:bicycle` are present. In this case the setting from `oneway:bicycle` should be taken, but this in not the case. I intend to create a pull request.

**Comment by ratrun** [comment]
I added a testcase where both tags are present: `oneway=yes` and `oneway:bicycle=no` and this test passes: `assertTrue(encoder.isForward(flags));  assertTrue(encoder.isBackward(flags));` So I can't see any problem.

**Comment by karussell** [comment]
The problem might be because of cycleway:opposite? If I understand the issue correctly bike is allowed in both directions, right?

**Comment by ratrun** [comment]
I understand it the same way that both directions are allowed for bike. A test `assertTrue(encoder.isForward(flags)); assertTrue(encoder.isBackward(flags))` passes in case of all 3 tags are present: `oneway=yes`, `oneway:bicycle=no` and `cycleway=opposite`.

**Comment by karussell** [comment]
The following did not pass (fixed it):
```java
        way.clearTags();
        way.setTag("highway", "tertiary");
        way.setTag("oneway", "yes");        
        way.setTag("cycleway", "opposite");
        flags = encoder.handleWayTags(way, encoder.acceptWay(way), 0);
        assertFalse(encoder.isForward(flags));
        assertTrue(encoder.isBackward(flags));
```

@chrissssss thanks again for reporting and @ratrun for keeping the thumb on it :) !

@ratrun would you review the fix please? I'm not 100% sure why the oppositeLane check was in the first if

**Comment by ratrun** [comment]
@karussell: I `can't follow your modification. I think that it is wrong and needs to be reverted.

See the description about "opposite" on http://wiki.openstreetmap.org/wiki/Key:cycleway 

The former code was ok, where following test passed:
```
        way.clearTags();
        way.setTag("highway", "tertiary");
        way.setTag("oneway", "yes");        
        way.setTag("cycleway", "opposite");
        flags = encoder.handleWayTags(way, encoder.acceptWay(way), 0);
        assertTrue(encoder.isForward(flags));
        assertTrue(encoder.isBackward(flags));
```
Maybe this test should be added.

**Comment by karussell** [comment]
Strange, I was pretty sure I've read that it should go opposite direction but the wiki is indeed different and says:

> Use cycleway=opposite for situations where cyclists are permitted to travel in both directions on a road which is one-way for normal traffic

But this means that this issue reporter had also the incorrect assumption of opposite (?)

I'll revert!

**Comment by karussell** [comment]
@chrissssss do you agree and we can close?

**Comment by chrissssss** [comment]
Hi @karussell and @ratrun!
I've just made a quick look at the web interface with the following:
./graphhopper.sh extract  8.61635,50.16616,8.62804,50.17143 
The routing is just as it was, but maybe my local git repo is a little weird. I'll have a look at it tomorrow and give you a short reply.

**Comment by chrissssss** [comment]
Hi! 
Sorry, now you've got me confused. 
All is based on:
*Sub keys / exceptions
Oneway can be used in conjunction with vehicle type in order to tag exceptions. I.e. oneway:moped=no for a one-way streets where mopeds are allowed to drive in the opposite direction. Bicycles (oneway:bicycle=no) are handled specially and cycleway=opposite/opposite_lane/opposite_track needs to be added for compatibility: (See Key:access for sub-values or Bicycle for examples).*

Let's summarize:
If a one-way is tagged either *cycleway=opposite* OR *oneway:bicycle=no* it's allowed for cyclists.

That broke with your fix, I think. You (kind of) fixed the test, but luckily ratrun intervened. 

When I'm looking at my issue, it still persists: In the given example there is "Spielsgasse" which is a one-way street with permission to use in both ways for cyclists. Sadly graphhopper does not permit me to cycle through and routes me around. 
So would you reopen it or do I not get the point?

**Comment by chrissssss** [comment]
Well, I think I've made clear what I tried to achieve. Please review the pull request. 
BTW: Is this the preferred way to contribute?

**Comment by chrissssss** [comment]
Finally: can be left closed, forget the pull request because it changed nothing. Having looked at the data the problem was in there.
Should be corrected with https://www.openstreetmap.org/changeset/31957611 where ids 28301888 and 4764754 are now tagged "oneway:bicycle": "no" which was missing before

**Comment by karussell** [comment]
Thanks!
