### ISSUE TITLE
Access on bus-only-street ignored

### ISSUE THREAD

**Issue by michaelkrog** [graphhopper/graphhopper#436]
I have a bus passage nearby at which the access is ignored by graphhopper.

Check out the diff between an openstreet.org link and a graphhopper link:
https://www.openstreetmap.org/directions?engine=osrm_car&route=57.0417%2C9.9341%3B57.0371%2C9.9387#map=16/57.0392/9.9350

https://graphhopper.com/maps/?point=Bornholmsgade%2C%209000%2C%20Aalborg%2C%20Denmark&point=Karnersvej%2C%209000%2C%20Aalborg%2C%20Denmark&locale=da&layer=Lyrk

Graphhopper directions go directly through the access restricted bus passage even though the it has `motor_vehicle=no`set.

![skaermbillede 2015-06-06 kl 09 53 25](https://cloud.githubusercontent.com/assets/681472/8018884/f54524c2-0c31-11e5-8b7a-698c31630881.png)

**Comment by karussell** [comment]
Thanks, this should not happen. Will investigate

**Comment by karussell** [comment]
Fixed, but will be live not before monday (we had some OSM data update issues)

**Comment by michaelkrog** [comment]
Awesome!
