### ISSUE TITLE
Turn Restriction with one or more ways as a via member

### ISSUE THREAD

**Issue by mapsg** [graphhopper/graphhopper#446]
Hello to community
I was using GraphHopper for routing when I noticed that the  Turn Restrictions with one or more ways as a via member do not supported from the routing engine. That's right ? Are you planning to support this feature?
A typical example
http://www.openstreetmap.org/relation/442887

**Comment by karussell** [comment]
Yes, currently only nodes are allowed for the 'via' of the turn restriction. As these kind of turn restrictions do not occur very often we will create additional nodes and ways in a preprocessing to support this.

BTW: in this specific example just forbid the left turn and all is fine ;)

**Comment by devemux86** [comment]
See also http://wiki.openstreetmap.org/wiki/Michigan_Lefts

**Comment by matkoniecz** [comment]
Currently there are more than 50 000 `via` ways (2% of all `via` roles for turn restrictions). See https://taginfo.openstreetmap.org/relations/restriction#roles

**Comment by easbar** [comment]
>  We would have to add turn restrictions to B1 (can only go from C4 to D2),

Ok this would force going from C4 to D2 and we can prevent the u-turn this way (using the artificial edge), but at the same time we cannot go straight (C4-B1-C2) anymore ?!

This problem is also discussed here: 

* https://github.com/valhalla/valhalla/issues/224
* https://github.com/valhalla/valhalla/issues/1801

**Comment by karussell** [comment]
> but at the same time we cannot go straight (C4-B1-C2) anymore ?!

I think the B1-C2 edge is not a oneway one (my explanation was a bit unclear)

**Comment by easbar** [comment]
> I think the B1-C2 edge is not a oneway one

Ok, but you said `We would have to add turn restrictions to B1 (can only go from C4 to D2)` and if we do this the turn restrictions prevent us from going C4-B1-C2 so we can no longer drive on the road normally (go straight on our way from C4 to C1).

**Comment by karussell** [comment]
Oh, I think what I meant is: `add a turn restriction to B1 (can not go from C2->B1->D2)` so C4-B1-C2-C1 should still be possible. I hope this works now :) ?

**Comment by easbar** [comment]
Ok, to summarize:
```
    A1
    | 
C1--C2--B1--C4
    | /
D1--D2--D3
    | 
    E1
```

- we introduced an artificial node B1 and edges C4->B1 and B1->C2
- added an artificial edge (oneway) B1->D2
- we deny the turn B1->C2->D2 (coming from C4 we can still "go left at node C2" to reach E1 by taking the artificial edge B1->D2)
- we deny the turn from the artificial edge B1->D2 onto edge D2->D3 (this makes the overall u-turn when coming from C4 back towards D3 impossible, but at the same time we can still go A1->C2->D2->D3)
- we deny the turn C2->B1->D2, for the very common case where C4->...->C1 and D1->..->D3 are one-ways this is not necessary though

Nice! Now I think this works and it does not require keeping track of the last two edge-states when routing (which would be very complex or maybe not even possible to do with CH).

**Comment by easbar** [comment]
From valhalla (valhalla/valhalla#1801):

> The only way to add penalties for via way Uturns is to track state in the PathAlgorithm and know that 2 successive turns have been made.

I do not think I understand this yet, because even if we wanted to add turn *costs* (not restrictions) we could apply them when taking the turn B1->D2->D3 (whenever we take this turn we *know* we took the via u-turn and can add the according costs) (!?)

Anyway, I think first of all this should be done to apply via u-turn restrictions and this should be done during the map import (?.)

**Comment by karussell** [comment]
> whenever we take this turn we know we took the via u-turn and can add the according costs) (!?)

Yes, I think so too. Maybe if they have no such artificial edges (yet) then they can't easily add the turn costs? When I read this I think they want to solve it in the algorithm. But this is too complicated IMO and so we should try to solve it in the OSM import.

As you already said this is important to make it working in CH and avoiding complexity in other algorithms too.

**Comment by ramen2581** [comment]
https://wiki.openstreetmap.org/wiki/Tagging_for_the_renderer

**Comment by dversaci1** [comment]
@easbar  it seems that Osmosis is in maintenance mode according to Github (https://github.com/openstreetmap/osmosis) so unfortunately the osmosis may not be possible (I did try it, --induce-ways-for-turnrestrictions is listed as a future task, but I assume it is unlikely it will be implemented given the project maintenance mode status).  Out of desperation I tried the new Graphhopper 5.1 release just now but it seems the same behaviour still occurs so I'm a bit stuck now.

**Comment by easbar** [comment]
Unfortunately there hasn't been any progress here yet for 5.1 or current master. But it would be a useful thing to do indeed. Given Osmosis isn't very active did you take a look at Osmium as well?

**Comment by dversaci1** [comment]
Thanks for the tip @easbar . After you mentioned it, I took a look at Osmium and I will try it, but I'm not confident it will help as the documentation https://osmcode.org/osmium-tool/manual.html doesn't mention anything about way conversions for turn restrictions,

**Comment by RezaShahbaz** [comment]
A1
    | 
C1--C2--B1--C4
    | /
D1--D2--D3
    | 
    E1

what if A1>...>E1 was not one-way?

**Comment by easbar** [comment]
Hi @RezaShahbaz, thanks for working on this! The route shown in your screenshot is actually what we should expect, I think. We can see that the big u-turn between the two roads is prevented. And even though the route does *another* u-turn this is fine. We reached the goal to prevent the forbidden u-turn. Whether the *other* u-turn (at the most Southern point of the route) is allowed is another question. 

I think this is the same situation as for standard turn restrictions: Imagine you arrive at a junction and going left is forbidden. You could go straight, take a u-turn, and when you are back at the junction go right. Whether this is better or worse than taking another route without a u-turn depends on the costs for this u-turn.

For example this is what I would expect if the u-turn costs were zero:

![image](https://user-images.githubusercontent.com/17603532/169142521-2a753c88-c3b7-4d0f-b8f2-00b98ec59ee8.png)

compared to something like this if the u-turn was more costly than the detour that goes right and does a few more turns to turn around:

![image](https://user-images.githubusercontent.com/17603532/169142626-1494946f-69f7-4344-99e4-cc1ef735a16f.png)

So actually I think if you increased the u-turn costs your route should look something like this:

![image](https://user-images.githubusercontent.com/17603532/169142798-587f7a2b-7375-4f5d-951d-5e2b49b4178d.png)

**Comment by easbar** [comment]
There is a (hopefully) working implementation here: #2689, feedback is very welcome and helpful.

**Comment by easbar** [comment]
The latest master version can now handle restrictions with single via members: #2689

**Comment by easbar** [comment]
Here is a live example: https://graphhopper.com/maps/?point=37.97265%2C-122.34324&point=37.973489%2C-122.341598&profile=car

![image](https://user-images.githubusercontent.com/17603532/205609256-f1015094-dccb-4875-baa8-f585717ec9fd.png)

**Comment by ramen2581** [comment]
The location I was monitoring is fixed as well.
https://graphhopper.com/maps/?point=43.030672%2C-88.017636&point=43.030525%2C-88.04848&profile=car&layer=Omniscale

**Comment by easbar** [comment]
Some work towards support for multi-way restrictions was done here: https://github.com/graphhopper/graphhopper/pull/2695
