### ISSUE TITLE
graphhopper.sh windows 

### ISSUE THREAD

**Issue by domi-nique** [graphhopper/graphhopper#449]
hi, i have problems with set up graphhopper on windows. 
i've cloned the git repository but when i want to import the map i get a failure 

$ ./graphhopper.sh import europe_germany_berlin.pbf
./graphhopper.sh: Zeile 2: $'\r': Kommando nicht gefunden.
./graphhopper.sh: Zeile 25: Syntaxfehler beim unerwarteten Wort `$'{\r''
'/graphhopper.sh: Zeile 25: `function printUsage {

do you have ideas what i have to do?

**Comment by karussell** [comment]
Did you follow the windows specific documentation and installed cygwin or similar?

**Comment by domi-nique** [comment]
yes, and i did it with cygwin :/

**Comment by mprins** [comment]
you may have cloned with a wrong line ending convention, causing git to do a conversion while getting the files

check `git config -l` output

**Comment by karussell** [comment]
@mprins good idea. Do you know if our settings are wrong? https://github.com/graphhopper/graphhopper/blob/master/.gitattributes

I would prefer if it works out of the box on every OS

**Comment by mprins** [comment]
I'm not sure, there might also be peculiarities between git clients eg. cygwin has a git client that behaves 'unix' but eg toirtoise or another win native client has windows behaviour.

also none of them share the config  afaik. 
Think it's a trial and error thing..

**Comment by devemux86** [comment]
An idea could be to download the GH repository zip from the [main](https://github.com/graphhopper/graphhopper) page and unzip (normally the OS can handle it better this way).

**Comment by mprins** [comment]
for a [project](https://github.com/GeoDienstenCentrum/sass-maven-plugin/blob/master/appveyor.yml) I have building on the [AppVeyor CI](https://ci.appveyor.com/project/mprins/sass-maven-plugin) I do this:

```
  - git config --global core.autocrlf true
  - git config --global core.safecrlf true
```

**Comment by mprins** [comment]
looking at the .gitattributes i notice that ths .sh extension is not listed, so git will just guestimate the appropriate line ending convention to use, maybe adding a line  `*.sh text` will just make it behave properly

**Comment by karussell** [comment]
oh, thanks - fixed!

@domi-nique please drop the checked out repo and try again. If still not working you can also explicitly convert to windows format via the tool unix2dos I think

**Comment by karussell** [comment]
Closing here, if still not fixed - please reopen!

**Comment by karussell** [comment]
Maybe we should use [editorconfig](http://editorconfig.org/) to fix this properly (?)

**Comment by devemux86** [comment]
Isn't that something that depends on various IDE / plugins support?
From a quick look I see not all features (e.g. ```end_of_line```) are supported completely everywhere.

**Comment by karussell** [comment]
> Isn't that something that depends on various IDE / plugins support?

See [download](http://editorconfig.org/#download) - many IDEs have native support

> From a quick look I see not all features (e.g. end_of_line) are supported completely everywhere.

What do you mean? The line ending could be additionally forced this way as it looks that the git-way fails sometimes.

**Comment by devemux86** [comment]
Well the majority works with plugins (Eclipse, NetBeans, etc).
Even then, searching the supported properties sections, not all are there.
Doesn't that mean that essentially we could have missing functionality?

**Comment by karussell** [comment]
I'm only speaking for the line ending ... but yes, the functionality for code formatting is kind of not existing for this

**Comment by karussell** [comment]
Still user experience this issue, and I needed to install a unix environment with unix line endings to fix this. Hmmh.

**Comment by devemux86** [comment]
We could have two batch files (```sh``` and ```bat```), i.e. that's how Gradle wrapper [[1](https://github.com/graphhopper/graphhopper/blob/master/android/gradlew)] [[2](https://github.com/graphhopper/graphhopper/blob/master/android/gradlew.bat)] in GH Android sample works.
More to support but Windows users will not have to setup a Unix-like environment.

**Comment by karussell** [comment]
I wouldn't be able to maintain this.

**Comment by highsource** [comment]
`dos2unix graphhopper.sh` worked for me.

**Comment by zstadler** [comment]
There is a maintenance-free solution, based on [this stackoverflow answer](http://stackoverflow.com/a/14607651).

Adding this line just after the #! line:

```bash
(set -o igncr) 2>/dev/null && set -o igncr; # this comment is required for handling Windows cr/lf
```
Note that the comment is needed in order to ignore the CR in that line, which is read before the option takes effect.

**Comment by zstadler** [comment]
Created PR #816
