### ISSUE TITLE
Barriers are ignored

### ISSUE THREAD

**Issue by NopMap** [graphhopper/graphhopper#45]
There are many route-blocking barriers like gate, lift_gate, cycle_barrier or bollard in the OSM data. Graphhopper does not evaluate them. This will lead to rouiting through the obstacles.

Most of these barriers are tagged on nodes. These nodes are always pillar nodes.

What would be the proper way to introduce such blocks into the graph?
1. unjoin the way at the blocked node and add it as two disconnected ways?
2. split the way in 3 and replace the blocked node with a very short edge which is marked with neither FORWARD nor BACKWARD? (Is it possible to block an edge this way?)
3. Something completely different is required?

If it works, I would suggest 2. as the block can be different for foot, bike and car.

**Comment by alexwong711** [comment]
In the util folder, opening up FootFlagEncoder, there are a lot of references to "safehighwayTags" and "intended/restrictive values". In what directory are these methods defined in their functionality?
