### ISSUE TITLE
Create separate source module for import and core

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#450]
The whole OSM reading stuff should be in a separate source module 'import-osm' which needs a bit refactoring so that we can finally do

```java
hopper = new GraphHopperOSM().setOSMFile(...)
hopper.importOrLoad()
```

and on Android etc we should be able to avoid setting OSM related stuff and just do:
```java
hopper = new GraphHopper();
hopper.load(ghFolder)
```

We should use the change to separate OSM better from the core. Furthermore we could easier integrate other readers like #277 and #616.

**Comment by devemux86** [comment]
You mean like split into modules for graph creation, perform routing etc (like the current ```tools```) ?

**Comment by karussell** [comment]
Yes. Just moving the import code out of `core`, so that Android and iOS does not need to exclude those xml reading stuff. Or if Android at some point implements its, it can just add it as dependency

**Comment by devemux86** [comment]
:+1: 
In mobile platforms the import (aka creation) of graphs is a bit difficult due to devices specifications.

**Comment by devemux86** [comment]
@karussell nice work!
