### ISSUE TITLE
Anounce that a ferry is taken along a route

### ISSUE THREAD

**Issue by jandr** [graphhopper/graphhopper#455]
It would be nice to add a "Take ferry to..." indication when the route goes through these links. An example where this would apply is provided below [1]

[1] https://graphhopper.com/maps/?point=el%20hierro&point=gran%20canaria&locale=de&layer=OpenMapSurfer

Thank you!

**Comment by karussell** [comment]
This is done now "... take the ferry":

https://graphhopper.com/maps/?point=51.502091%2C-0.123076&point=51.501006%2C-0.124492&locale=en&vehicle=foot

Can also be done via path details.
