### ISSUE TITLE
Make Android demo build with hardwareAccelerated="false"

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#458]
this is necessary for mapsforge but failed for API level 10 ... I need to try that compilation against the latest API (22) works

**Comment by devemux86** [comment]
For reference I copy here the official recommendation regarding Android compilation:
```Select a Compile With API version. This setting specifies what version of the SDK to compile your project against. We strongly recommend using the most recent version of the API.```

**Comment by karussell** [comment]
Okay, I should have read [my own docs](https://github.com/graphhopper/graphhopper/blob/master/docs/android/index.md#maven-or-netbeans) on how to setup maven&android. I forgot to install the deployer and also setting the latest API level in the pom.xml

**Comment by devemux86** [comment]
:)
