### ISSUE TITLE
Implement graphhopper map locally (instead of using cygWin)

### ISSUE THREAD

**Issue by doShareIT** [graphhopper/graphhopper#460]
Hi,

I am testing OpenStreetMap in my c# .NET application and works fine:
- .osm  MAP
-  CygWin Console 
-  graphhopper 
-  http://localhost:8989/route?.... 
- read json response from .NET application

Now, I want to know if is it posible to implement my map in a IIS webstie locally instead of run cygWin console before.

Thx in advance

Kind regards

**Comment by karussell** [comment]
Please use the mailing list for questions and feel free to open source your .NET client for the API ;) !

Also a potentially bigger success rate of answering gives you if you include exact problem and not a broad question on how to do this + you should ask .NET experts.
