### ISSUE TITLE
Foot routing not following footway, but bike does?

### ISSUE THREAD

**Issue by neiljp** [graphhopper/graphhopper#461]
Route here:
https://graphhopper.com/maps/?point=57.155703%2C-2.103378&point=57.155109%2C-2.102466&vehicle=foot&locale=en-US&elevation=true&layer=Lyrk
Foot: takes long way round
Cycle: takes footway!

I'm sure that dismounting from the cycle makes sense, but the foot detour less so!

**Comment by karussell** [comment]
Thanks, this looks like a bug - will investigate!

**Comment by karussell** [comment]
This is a data issue, yesterday we had a hickup for the daily updates and car&bike is already filled with the latest data but foot will be updated very soon (in ~3 hours). Please check and close if fixed then.

**Comment by neiljp** [comment]
Thanks for the update; I added the footpath myself, and was waiting as patiently as I could ;)
I know the data normally updated daily, but when bike was different to foot then I thought there might be a problem and wasn't sure where to find this out from.

Have just checked, and this is resolved.

Is there a central location to check update status? That would be very useful to confirm if this is a system or routing issue.

**Comment by karussell** [comment]
Thanks! That is indeed often requested and I created an issue to forward the date currently only available in the json into the UI and make it possible to have different dates per profile, see #462
