### ISSUE TITLE
Make age of data available in the UI

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#462]
Currently the age is included in the info json but not visible to the user. As several profiles can have different dates, we need to extend the json in this direction and e.g. print the oldest date?

**Comment by zhiqiangZHAO** [comment]
what you mean "age"? the date of osm snapshot?

**Comment by karussell** [comment]
The date of the import (could be indirectly the date of the OSM) and/or the date of the CH preparation. See [here](https://github.com/graphhopper/graphhopper/blob/master/web/src/main/java/com/graphhopper/http/InfoServlet.java#L73)
