### ISSUE TITLE
Dimension warning message

### ISSUE THREAD

**Issue by devemux86** [graphhopper/graphhopper#470]
I think that dimension warning [message](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/storage/BaseGraph.java#L452-L454) is a bit confusing.

e.g. we have a graph without elevation and try to load it with ```graphHopper.setElevation(true)```, this produces the warning:
```Configured dimension (2) is not equal to dimension of loaded graph (3)```

The ```configured``` word leads the mind to the ```setter``` configuration (3), though it means the loaded graph properties (2).
And the ```dimension of loaded graph``` leads to loaded graph dimension (2), though it means the ```setter``` (3).

**Comment by karussell** [comment]
Ups, true! So swapping both values should fix the problem (?)

**Comment by devemux86** [comment]
Yes I think that should fix it.
