### ISSUE TITLE
GraphHopper.setCHEnable vs graph CH state

### ISSUE THREAD

**Issue by devemux86** [graphhopper/graphhopper#471]
After #447 the ```setCHEnable(true)``` works also with non CH graphs, that could be a problem.

We should either configure CH automatically or notify the user about the wrong setting.

See also [here](https://github.com/graphhopper/graphhopper/pull/447#issuecomment-123821614) for the conversation.

**Comment by devemux86** [comment]
In my mind that's somehow related to #285 "Inspect graph properties".

I mean in the end we should somehow not rely on setter methods for loading a graph, that could be handled automatically without failures for user convenience.

**Comment by karussell** [comment]
That is true and should be done :)
But automating this is hard and configuring very easy :)

**Comment by devemux86** [comment]
>But automating this is hard and configuring very easy :)

I have to agree to that! :)

**Comment by karussell** [comment]
Will be fixed after #464 is merged

**Comment by devemux86** [comment]
Peter after testing, I confirm that the loading of various graph types is working again fine.

**Comment by karussell** [comment]
Thanks!
