### ISSUE TITLE
Make maximum visited nodes configurable

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#473]
To ensure that one can run none-CH in production we need an option to avoid full graph exploration

**Comment by chimbs86** [comment]
Is anyone working on this? If not, I can try my hand at it. I am new to grasshopper source code, and this looks like a low hanging fruit

**Comment by karussell** [comment]
Not in the next days :)
And yes, it should be very similar if not identical to the weight limit

**Comment by karussell** [comment]
BTW: If you look for other low hanging fruits: have a look into the [good first issues](https://github.com/graphhopper/graphhopper/labels/good%20first%20issue) :)

**Comment by chimbs86** [comment]
Wow, aamazing that you have a tag for this. Definitely helps
