### ISSUE TITLE
Routing round a building

### ISSUE THREAD

**Issue by CMugabi** [graphhopper/graphhopper#474]
Greeting GH Team...
I have a case where i need to route to a person's home. This house is enclosed by a wall fence and has two possible routes to it. The "longer" route goes exactly to the gate but the shorter one stops on the lower side of the fence. This house being on a hill is such that when you acess it from the "shorter" route, you have to go round it (making this route longer in actual sense). However GH routes upto the nearest point to the house using the shorter route (but of course you can't access the house from there). Is there away to tell GH to prefer the route that takes me to the gate? Or do we have to map the houses as points on the prefered road?

**Comment by karussell** [comment]
GraphHopper snaps to the nearest point on its known network. So you could either include the paths of this house in your road network e.g. via adding it to OSM or you could tell your geocoder to map that address to your favourite position when resolving the address.

BTW: please post follow up questions on the mailing list
