### ISSUE TITLE
Execute CH preparation on two or more threads

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#479]
Now with multiple profiles from #464 we can improve overall preparation very easily via a queue and X threads for executing the CH preparation.

Another possibility is to use threads within one preparation which would speed up setups with a single profile too.

**Comment by devemux86** [comment]
:+1: 
CH preparation even for small networks is time consuming, any improvement is welcome.

**Comment by jtheuer** [comment]
Probably the use of threads for one preparation would be most efficient - if memory usage stays constant. However, with only a quick look at https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java#L229 I could not identify an easy way.
Another idea: What about contracting each subnetwork in parallel?

**Comment by karussell** [comment]
> Another idea: What about contracting each subnetwork in parallel?

Sure, you can. You can even split one subnetwork in areas but this all means a lot of effort and not as easy as just executing them in parallel.

**Comment by jtheuer** [comment]
I don't get the areas idea, you mean you would cut the graph into smaller pieces and contract them? Is that the parallelization idea you meant in the first post? I guess it then needs some kind of "reducer" step to path the areas together afterwards? (You obviously wouldn't need that for subnetworks)

**Comment by karussell** [comment]
> I don't get the areas idea, you mean you would cut the graph into smaller pieces and contract them? 

yes

> Is that the parallelization idea you meant in the first post? 

no, I meant doing full contractions in parallel. Easy to do, only problem is RAM usage multiplies as well.

> I guess it then needs some kind of "reducer" step to path the areas together afterwards? (You obviously wouldn't need that for subnetworks)

yes :)

But the subnetwork idea would improve nothing for many GraphHopper users not using world wide deployment. So I would not invest time into it. Also having multiple contractions in parallel, will be more memory intense, even with smaller (sub)networks.

**Comment by karussell** [comment]
For the area of Saxony, 1gb RAM and flagEncoders=car,bike,foot,motorcycle I get on my old dual core (only the preparation):

3 threads => 7min 36sec
2 threads => 6min 9sec
1 threads => 10min 5sec

So obviously there is a sweet spot for 2 threads on my 2 core system.

Now testing for the world wide case with a bit bigger server environment ;)

**Comment by jtheuer** [comment]
Can you roughly outline how "Another possibility is to use threads within one preparation which would speed up setups with a single profile too." would be possible? When I checked the code it looks pretty hard, would need a bunch of refactoring because there are a lot of states (fields and shared variables) but maybe I missed something?

**Comment by karussell** [comment]
I didn't say it is easy :) 
Plus this is only the one drawback, the other is that the algorithm itself is not simple, only read it up in some paper.

Still the same synchronizing complexity you have for separate subnetworks.

**Comment by SabriAl-Safi** [comment]
You're probably aware, but this seems to be in place in OSRM. As far as I can tell the implementation is based on the ideas in Chapters 3 and 4 of this paper: https://algo2.iti.kit.edu/download/vetter_sa.pdf

**Comment by karussell** [comment]
I was aware of this procedure&paper, yes.
