### ISSUE TITLE
Throw exception if using heading for CH graph

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#483]
[as discussed](https://github.com/graphhopper/graphhopper/pull/434#issuecomment-110275256) in #434

Also fastest weighting is necessary for it to work.

**Comment by devemux86** [comment]
>Also fastest weighting is necessary for it to work.

Indeed, are there any plans for support with shortest weighting too?

BTW with shortest, will we have exception throw or simply calculate the route without heading?

**Comment by karussell** [comment]
exception, as API usage is wrong then

> Indeed, are there any plans for support with shortest weighting too?

Shortest weighting is ugly not only here, because it is 'shortest' and nothing else. So would you expect a complete blocking if a heading is forced (won't find any route then in some cases) or just a priority, which is not really 'shortest' then

**Comment by devemux86** [comment]
BTW I just checked [MapQuest](http://open.mapquestapi.com/) implementation of start heading and it works with both route types (fastest / shortest).

**Comment by karussell** [comment]
Hmmh, we could interpret the heading penalty as meter and implement it for shortest too, shouldn't be hard. But 'shortest' path is in general not of much use IMO

**Comment by karussell** [comment]
fixed. for the shortest handling I've created #485

**Comment by devemux86** [comment]
Peter may be I'm missing something, but where the ```force_heading_ch``` is described ?

**Comment by karussell** [comment]
at the moment nowhere, as it shouldn't be officially used IMO (due to strange behaviour sometimes with CH)

we'll see if people need CH and heading

**Comment by echap** [comment]
Hey there, I wanted to do a simple redirection with heading parameter :

` https://graphhopper.com/api/1/route?point=48.87899%2C2.29881779&point=48.87914251522007%2C2.2989351768493407&heading=25.98&weighting=fastest&locale=fr&key=[my_key]` 

But the api returns a hint that brings me here but... I don't see what I'm doing wrong. Any idea ?

**Comment by karussell** [comment]
@echap disable CH via appending &ch.disable=true

**Comment by echap** [comment]
@karussell Awesome ;) It's quite unclear on the api doc then, but it works perfectly fine for my use case :)

**Comment by easbar** [comment]
Added a test to show what the problem of CH with heading is here: e8cdc6fb0afa8810fb4074aafee13fc2c0eb46e3
