### ISSUE TITLE
Add turn instructions at roundabouts (exit number) in the GPX output data

### ISSUE THREAD

**Issue by TrackRanger** [graphhopper/graphhopper#486]
Currently GPX data in <extensions> tag group does not include Turning Directions (i.e. which exit to take) at Roundabouts. The gh:sign tag indicates the presence of the roundabout, but there is no information for the correct exit to use.
An example is shown here:
https://graphhopper.com/maps/?point=-17.956143%2C122.239895&point=-17.955235%2C122.241392&locale=en-US&layer=Omniscale 

The driving directions include which exit to take, but the GPX data does not include this. This would be a valuable addition to the GPX information, and presumably not too difficult to implement.

**Comment by karussell** [comment]
Fixed via #1181
