### ISSUE TITLE
Ensure naming of Weighting for better storage and identity

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#490]
We should ensure on creation that a weighting can only contain lowercase chars and _ to create files from weightings easily and also to make fetching a value from a `Map<Weighting, Value>` more reliable. See ` // TODO too loose matching?` in getWeightingForCH

**Comment by devemux86** [comment]
(@karussell  I'm playing with Android Sample)
It fails loading the downloaded graphs because of this:

`An error happend while creating graph:Configured graph.chWeightings: [fastest|car] is not equal to loaded [FASTEST|car]`

Probably we need updating the provided graphs?

**Comment by karussell** [comment]
Ah, indeed for 0.6

**Comment by karussell** [comment]
Should be fixed now and latest map data is used ...

**Comment by devemux86** [comment]
You updated the graphs? (because I see the same error)

**Comment by karussell** [comment]
uhm, stupid me. Did update the git repo but not called clean ..

**Comment by karussell** [comment]
Now updated maps & tested it ;)

**Comment by devemux86** [comment]
I can confirm that too. :)

**Comment by devemux86** [comment]
Peter a report is in our Mapsforge [forum](https://groups.google.com/forum/#!topic/mapsforge-dev/Ue7o-YRp4pY) regarding the GH Samples app and ```europe_germany_bayern``` map.

It does not work. I downloaded the map and it appears to be invalid (wrong file size). Can you check it?

**Comment by karussell** [comment]
Hmmh, maybe some nginx download limit or another Android limit? Currently the best thing would be to remove this big area as I won't have the capacity to maintain these hosting problems :(
