### ISSUE TITLE
Allow running flexibility queries even if CH enabled for one/all profiles

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#491]
See #464.

But make sure the CH queries cannot be disabled in the default started server. E.g. assume a service running and expecting CH queries but an attacker downgrades to flexibility ("none-CH") and can create high load. I.e. we need a param in config.properties to allow `flexibility=true` as request parameter

Related to #493

**Comment by devemux86** [comment]
Somehow related to #471 regarding the CH on / off mix in the same graph.

**Comment by karussell** [comment]
Kind of, but #471 is more about ensuring the correct load. This here is about querying a CH graph via CH or flexibility

**Comment by karussell** [comment]
This is now integrated via #631 

To use this enable it in the config.properties `routing.flexibleMode.allowed=true` and make sure you specify something like `routing.maxVisitedNodes=1000000`

Then for the routing request use `&routing.flexibleMode.force=true` which makes then all flexible modes possible although CH was prepared.
