### ISSUE TITLE
builddate and version files location

### ISSUE THREAD

**Issue by devemux86** [graphhopper/graphhopper#494]
Peter would be possible to move ```builddate``` and ```version``` files in another location instead of the project / jar root ?

Now during app packaging, they conflict with other libraries having at root the same named files.
i.e. I tend to remove them for such reasons and GH complains later.

A suggested location would be inside package ```com.graphhopper```.

**Comment by karussell** [comment]
Ah, good catch! I would still keep them in root but rename them to graphhopper-builddate etc - would that fix the problem too?

**Comment by devemux86** [comment]
The rename indeed will avoid the conflict with other libraries.

My suggestion would still be to have them inside the library folders.
It's far more clean for an app structure and would help many programs (e.g. Proguard) in their parsing process.

**Comment by devemux86** [comment]
Thanks for that, confirmed that working fine.
