### ISSUE TITLE
Class name in hash code

### ISSUE THREAD

**Issue by devemux86** [graphhopper/graphhopper#495]
Peter I don't know how you'll find this issue but nevertheless I'd like to mention it.

In ```BaseGraph.stringHashCode``` you use the class name for producing the hash.
This has the risk that when using the library in an app passing obfuscation (where class renaming happens) then the check fails and previously built graphs are marked as invalid.

There is solution of course by putting exceptions at the tool, but my suggestion would be to avoid using class names at storable processes like hash productions.

**Comment by karussell** [comment]
Indeed the hashing is no longer necessary. Will remove it as it also made problems with the iOS port.

**Comment by karussell** [comment]
See here https://github.com/graphhopper/graphhopper-ios/issues/2

**Comment by devemux86** [comment]
Tested and working fine.
