### ISSUE TITLE
Apache HTTP Client Removal

### ISSUE THREAD

**Issue by devemux86** [graphhopper/graphhopper#498]
Android 6.0 SDK (API 23) was released and removes some deprecated classes / methods.

In our case it's about the removal of ```Apache HTTP Client``` used in ```AndroidDownloader```.
http://developer.android.com/preview/behavior-changes.html#behavior-apache-http-client

The recommended way is use of ```HttpURLConnection``` as seen in ```Downloader```.

**Comment by karussell** [comment]
The problem is how can we remove it when it causes several issues without it? Should we use something like OkHttp instead for Android? To my knowledge it is based on HttpURLConnection but corrects some limitations regarding certs etc.

**Comment by devemux86** [comment]
The best way would be handling the situation with the recommended Android way (there must be a solution somehow - though I have not managed investing time in it).

https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-apache-http-client
We can continue with Apache HTTP APIs by declaring the folowing:
```gradle
android {
    useLibrary 'org.apache.http.legacy'
}
```

**Comment by karussell** [comment]
As it is only a demo I would prefer a way which won't make problems in a year. So I would prefer to not go the legacy route and use either the Android way or the external okhttp, where I made good experiences with in our [Java/Android clients](https://github.com/graphhopper/directions-api-java-client)

**Comment by devemux86** [comment]
Usually avoiding to load a library/app with too many external dependencies, so I'd first review the official recommendation.
But it's your call at the end. :smile:

**Comment by karussell** [comment]
Well, I do not care that much, as this is a demo and people can choose a different download mechanism. But yes, if there would be a stable and reusable download component without deps this would be best :)

**Comment by devemux86** [comment]
>Also if people use http to download there should not be any problems

So why the ```https``` in Sample if it can solve the situation?

**Comment by karussell** [comment]
https is enforced for everything on GraphHopper.com

I could make an exception for the maps, but it could make problems with the enabled [hsts](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security). Not sure if this applied only to browsers (I don't think so), so if the downloaded fetches once a https site it will never fetch a http site again.

**Comment by devemux86** [comment]
Well not making promises, I can review the ```https``` issue, if another solution doesn't appear in the meantime.

**Comment by karussell** [comment]
I think it has something to do with the certificates or with some ssl ciphers that I did not allow for graphhopper.com and make only problems for older clients. So one would have to add these certs and/or make certain ciphers working BUT this is the work that okhttp already did if I'm not wrong and it is only 300KB ;)

**Comment by devemux86** [comment]
Ok since as you said it's about Samples only, we can go with an external dependency.

**Comment by karussell** [comment]
I'm puzzled. I'ved tried via http (and a subdomain) but it is only working with the modified AndroidDownloader...

**Comment by devemux86** [comment]
Really? I thought now with ```http``` we can use ```Downloader``` again..

**Comment by karussell** [comment]
I'm now very confused. We use setDoOutput in the Downloader which is wrong:
"setDoOutput(true) is used for POST and PUT requests. If it is false then it is for using GET requests."

But it looks from history like we swapped forth and back for those setDoOutput/setDoInput method, see [comment](https://github.com/graphhopper/graphhopper/issues/127#issuecomment-38962291) and [commit1](https://github.com/graphhopper/graphhopper/commit/c1c0498a9173217bce34cbc6f01327954f2bfbb3#diff-e6ac278c3b5b1002f791721a4e3b4c90), [commit2](https://github.com/graphhopper/graphhopper/commit/9d05b02d3ea97cd99596280483dd610529c69731#diff-e6ac278c3b5b1002f791721a4e3b4c90) and [commit3](https://github.com/graphhopper/graphhopper/commit/2dc0be49da80958ec89736df42da6b172d72b691#diff-e6ac278c3b5b1002f791721a4e3b4c90).

So all hassle is probably because of that already fixed (and then accidentally reverted) bug which somehow only appeared for Android.

**Comment by karussell** [comment]
Please see if this fixes the problem for your Android version too :)

**Comment by devemux86** [comment]
I'll intend to PR some updates and will look after this too. :smile:

**Comment by devemux86** [comment]
@karussell I tried the latest changes, it seems to download fine.

**Comment by devemux86** [comment]
I don't remember if we have discussed the possibility of Android [DownloadManager](http://developer.android.com/reference/android/app/DownloadManager.html) system service.

**Comment by karussell** [comment]
Nice, thanks for the feedback! And please go ahead if there is something better/simpler than our current solution for Android :) !

**Comment by devemux86** [comment]
We already use it in Mapsforge [Samples](https://github.com/mapsforge/mapsforge/blob/master/Applications/Android/Samples/src/main/java/org/mapsforge/applications/android/samples/Samples.java#L130-L136) in its simplest form, so it's worth a try.
