### ISSUE TITLE
Android OutOfMemoryError

### ISSUE THREAD

**Issue by devemux86** [graphhopper/graphhopper#499]
Testing the latest GraphHopper on Android, I see often ```OutOfMemoryError``` during route calculations.
I don't remember having these issues with previous GH.

Current tests are with ```GraphHopper().forMobile()``` initialization, non CH graphs and bidirectional A* algorithm.
The routes causing the OOM are mainly country sized.

Will continue to investigate with other settings too, as it's quite serious issue.
(maybe related to #464 needed changes)

**Comment by devemux86** [comment]
I tested also with the default bidirectional Dijkstra, situation is better but OOM exceptions happen again.

@karussell I remember you had mentioned that bidirectional A* is currently the fastest algorithm for non contraction hierarchies, is this still right?

```java
java.lang.OutOfMemoryError
    at gnu.trove.map.hash.TIntObjectHashMap.rehash(TIntObjectHashMap.java:158)
    at gnu.trove.impl.hash.THash.postInsertHook(THash.java:388)
    at gnu.trove.map.hash.TIntObjectHashMap.doPut(TIntObjectHashMap.java:248)
    at gnu.trove.map.hash.TIntObjectHashMap.put(TIntObjectHashMap.java:222)
    at com.graphhopper.routing.DijkstraBidirectionRef.fillEdges(DijkstraBidirectionRef.java:212)
    at com.graphhopper.routing.DijkstraBidirectionRef.fillEdgesFrom(DijkstraBidirectionRef.java:157)
    at com.graphhopper.routing.AbstractBidirAlgo.runAlgo(AbstractBidirAlgo.java:74)
    at com.graphhopper.routing.AbstractBidirAlgo.calcPath(AbstractBidirAlgo.java:63)
    at com.graphhopper.GraphHopper.getPaths(GraphHopper.java:1053)
    at com.graphhopper.GraphHopper.route(GraphHopper.java:924)
```

**Comment by karussell** [comment]
Hmmh, I'm a bit surprised that it has worked before. I do not have something in mind which could cause this problem, as only the memory layout for CH has changed. But maybe you can memory profile both setups in more detail?

Also bidir A* should be the fastest although I noticed some contrary numbers - I have to dig into it the next days. As none CH will be a major focus for 0.6

Also related to our very first issue #1

**Comment by devemux86** [comment]
You mean non CH **large** routing is not supposed to work in memory restricted environments like Android?

You puzzled me! I'm trying to remember if I performed indeed country sized queries on Android with <0.5 versions.. :-)

What we're dealing here is actually the VM heap size that we can use (not device RAM).
And it can differentiate per device and Android version...

@karussell  thanks for answering, I wanted your opinion regarding GH internal memory consumption with the latest major changes.

Of course I'll perform more tests along the way.

**Comment by karussell** [comment]
> You mean non CH large routing is not supposed to work in memory 
> restricted environments like Android?

I think there are tricks like the 'big memory' option and similar stuff where you can make it working even in the current form, but as of today I had major difficulties to make it working without OOMs for none CH routes on my old 2.3 device.

> What we're dealing here is actually the VM heap size that we can use (not device RAM).

Yes and no. Because if you are using the MMAP option (are you?) then some native RAM outside of the heap can be (automatically) utilized for the graph and the VM heap is only used for the algorithm traversal.

The best thing would be if you find the single commit where you observe the dramatic behaviour change. Although I'm pretty sure that this is very time-consuming even with git bisect ... never done so for Android ...

**Comment by devemux86** [comment]
You mean the [android:largeHeap](http://developer.android.com/guide/topics/manifest/application-element.html#largeHeap) directive in manifest.

I didn't prefer the ```MMAP``` option because of the different device storage speeds leading to slow routing, but that's a valid suggestion to put in testing.

**Comment by karussell** [comment]
> You mean the android:largeHeap directive in manifest.

yes :)

> I didn't prefer the MMAP option so far

Oh, wow! So you say you have used the in-memory option without CH on Android? With the largeHeap option? And which country?

**Comment by devemux86** [comment]
[Cruiser](http://wiki.openstreetmap.org/wiki/Cruiser) on Google Play is without ```MMAP``` and ```largeHeap``` options.

And I have not seen so far any user reports regarding OOM, but how many actually perform large country sized routing.

**Comment by devemux86** [comment]
SORRY for the misunderstanding!
Like I said in the 1st post I actually use the ```GraphHopper().forMobile()``` which is ```MMAP```.
(and of course so Cruiser does)

I mistook our conversation and GH options - forgot what the API calls underneath. :(

**Comment by karussell** [comment]
No problem, still would be worth if you can find out the the problematic change or something else

**Comment by devemux86** [comment]
@karussell I performed some quick tests with GH version prior the aforementioned major changes and same client / graph settings.

Again we have Android OOM at large country sized routing, so apparently this is something not new.

**Comment by karussell** [comment]
Ok, so this is nothing newly introduced (?) and we have #1 and can close here?

**Comment by devemux86** [comment]
Yes, you are right, I'm closing this.

**Comment by karussell** [comment]
Speed comparison is now here: #506

**Comment by devemux86** [comment]
:+1:
