### ISSUE TITLE
Routing on UK bridleways

### ISSUE THREAD

**Issue by adrianQwest** [graphhopper/graphhopper#504]
When trying to route for bicycles, GraphHopper will not follow bridleways (highway=bridleway) even if bicycles=yes.

**Comment by karussell** [comment]
This is related to the issue discussed in #469 for foot, but with explicit tagging this should work

**Comment by adrianhyncica** [comment]
Peter,

How long does it take for a change on openstreetmap, a change of tag for example, to propagate to GraphHopper?

Regards,

Adrian

**Comment by karussell** [comment]
Currently roughly 1 day

**Comment by larkang** [comment]
For me routing with bicycle along [this bridleway](https://www.openstreetmap.org/way/35318380) does not work, even though it has "bicycle=yes", while routing by foot does work.

**Comment by karussell** [comment]
Fixed in #2105.
