### ISSUE TITLE
It would be great to have github tags/releases for maven releases

### ISSUE THREAD

**Issue by jtheuer** [graphhopper/graphhopper#508]
In order to debug issues in a certain versions and do fixes or extensions it would be helpful to have github tags/releases that match exactly the released maven version. I can assist with scripting if needed, if you use the maven-release-plugin it should be able to do that for you although I found its git support a bit unstable in the last year.

**Comment by karussell** [comment]
Do you mean git tags? That should be easily doable. Currently just use e.g. the 0.5 branch

**Comment by devemux86** [comment]
Essentially there are two schools for Git releases: tags and branches.
As Peter mentioned, GH uses branches.

**Comment by jtheuer** [comment]
yes, with github tags/releases I ment git tags/releases. I wasn't sure how much the 0.5 branch equals the 0.5.0 release because there have been a lot of commits in the branch recently.

**Comment by karussell** [comment]
Yes, that is the problem and also we cannot differentiate between 0.5.0 and 0.5.1

But currently the master only got changes, the 0.5 is identical (except one doc edit)

So probably we should tag for the minor releases and keep 0.5 branch?

**Comment by jtheuer** [comment]
It makes sense to keep the 0.5 branch for further 0.5.x releases. A tag is just a commit marker for the last commit that made it into a certain release.

@devemux86 sorry, I don't understand your comment. Never heard about the "two schools". What do you refer to?

**Comment by devemux86** [comment]
Using different method per release category could be confusing.

If you want to continue with branches I'd vote to include them all.

Additionally you could add tags too.

**Comment by karussell** [comment]
How do I push a tag? I created a 0.5.0 tag but it does not look like it is separate pushable (?)

> Using different method per release category could be confusing

What different methods? Using a branch is like a river where you can put in more stuff if necessary and @jtheuer now just wants a picture or a 'freezed state' and we can do so with tagging. Makes sense IMO or do I miss something?

**Comment by devemux86** [comment]
@jtheuer releasing in Git can be done in two ways:
- With a tag as a way to mark the release in time at repository
- With a branch to have the release in its own space

Personally I find tagging more convenient, but that's decision of each project manager.
(e.g. in [Mapsforge](https://github.com/mapsforge/mapsforge) we use tags)

**Comment by devemux86** [comment]
@karussell I was meaning a user to search in branches for 0.5.0 and in tags for 0.5.1 code.
Was that your idea or did I get it wrong?

**Comment by jtheuer** [comment]
@devemux86 I refer to https://github.com/graphhopper/graphhopper/releases:

> Releases are powered by tagging specific points of history in a repository. They’re great for marking release points like v1.0.

**Comment by oblonski** [comment]
Here <https://git-scm.com/book/en/v2/Git-Basics-Tagging> you can find
how to push tags.

" By default, the |git push| command doesn’t transfer tags to remote
servers. You will have to explicitly push tags to a shared server after
you have created them. This process is just like sharing remote branches
– you can run |git push origin [tagname]|."


Am 25/08/15 um 15:21 schrieb Peter:

**Comment by karussell** [comment]
@oblonski thanks :) ! Done now

https://github.com/graphhopper/graphhopper/tags

@devemux86 : 
Let me explain the intention behind the branching I currently use, maybe it is completely wrong habit but it does its job okayish:

 * all development work goes into master
 * when all issues are fixed I create a branch 0.5 where we can easily tag release candidates and minor versions like 0.5.1
 * new work which goes into master can be merged into 0.5 easily (as the branch keeps certain things like different version etc). And if breaking changes occured we can only cherry pick single commits

So the master branch but also the 0.5 branch is work in progress where I would then tag a specific release. When using only tagging without branches I'm not sure how I would easily merge only certain changes into a new 0.5.1 release if the master is already say at 0.6-SNAPSHOT like today.

**Comment by karussell** [comment]
@jtheuer Do you know what changes are necessary to make use of the maven-release-plugin? Currently I'm doing it manually in a few simple bash commands (e.g. `mvn -P include-android versions:set -DnewVersion=0.5.0 -DgenerateBackupPoms=false` etc) which does its job too.

**Comment by devemux86** [comment]
@karussell 
I see your point. To explain my view better let me mention how we work in [Mapsforge](https://github.com/mapsforge/mapsforge):

- Two main branches master and dev (besides the feature branches)
- The dev is our workbench which is merged or cherry picked when we think so
- The master is the stable one where the releases take place by tagging
- People can choose between them, what stability level they need (if they don't use releases)

Maybe the two branches is more work, but as you said it's working for us.
I had studied GH branching release method in order to check if we can benefit from it.
BTW in the past I was confused searching 0.4.1 release code and not finding next to 0.4 branch.

**Comment by jtheuer** [comment]
We had so many problems with the git integration of the release plugin that we just created a profile that we enable when we do ```mvn clean deploy```:

```
	<profiles>
		<profile>
			<id>create-release</id>
			<activation>
				<activeByDefault>false</activeByDefault>
			</activation>
			<build>
				<plugins>
					<plugin>
						<artifactId>maven-scm-plugin</artifactId>
						<version>1.9.2</version>
						<configuration>
							<tag>${project.artifactId}-${project.version}</tag>
						</configuration>
						<!-- only tag this module, not each individually -->
						<inherited>false</inherited>
						<executions>
							<execution>
								<id>git-tag</id>
								<goals>
									<goal>tag</goal>
								</goals>
								<phase>deploy</phase>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-enforcer-plugin</artifactId>
						<version>1.4</version>
						<executions>
							<execution>
								<id>enforce-no-snapshots</id>
								<goals>
									<goal>enforce</goal>
								</goals>
								<configuration>
									<rules>
										<requireReleaseVersion>
											<message>No Snapshots Allowed!</message>
										</requireReleaseVersion>
									</rules>
									<fail>true</fail>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
```

If you want to try the release plugin: Your scm config https://github.com/graphhopper/graphhopper/blob/master/pom.xml#L51 is already sufficient, just run ```mvn release:prepare release:perform``` it asks you for the new version

**Comment by karussell** [comment]
@jtheuer thanks for sharing - will keep in mind for the next release
@devemux86 this is a good possibility and now I understand what you mean with mixing branches and tags. Still I'm not sure how you would handle the following case with only 2 branches: 

if you have, say 0.5.0 and 0.4.1 already released and want to backport certain new features or critical bugs into 0.5 and 0.4 to create new releases ala 0.5.1 and 0.4.2

**Comment by devemux86** [comment]
@karussell Interesting question.
You can always make a minor release to last major release (e.g. 0.5.1 to 0.5), by tagging again the master at a later time.
In our work flow we don't backport features in old releases, using new releases for that.
But it can be done via branching 0.4 potential tag, make changes and produce from it the 0.4.2.

**Comment by karussell** [comment]
Currently just tagging releases manually and is working okay so far
