### ISSUE TITLE
Migrate to Java 8

### ISSUE THREAD

**Issue by tomfitzhenry** [graphhopper/graphhopper#512]
Would you be opposed to a PR that bumped graphhopper to Java 8 to benefit from:
* lambda expressions
* improved Collections library
* default methods
* improved type inference

**Comment by tomfitzhenry** [comment]
Ah, this might be tricky, since Android is a target, and Android does not yet support Java 8.

**Comment by devemux86** [comment]
Precisely GraphHopper is used in Android too, which is still in max Java 7 compliance level (and actually not all 7 features).

**Comment by karussell** [comment]
I do not see a reason to move to Java 8. GraphHopper core is really about performance and low memory usage and all the mentioned points do not improve the situation, instead they would make it even worse if applied incorrectly. Also you can use GraphHopper with higher versions if you like. Let me know if I have overlooked something valueable there, besides the massive bugs improvements to the 7+8 JVMs, but I mean on the language level.

Also as emux said, Android would need Java 7.

IF Java 9 e.g. with value types comes out, then this would be a massive improvement for memory usage and simplicity, Then we'll definitely require a more recent Java version, or at least take into consideration.
