### ISSUE TITLE
A feasible route was missing

### ISSUE THREAD

**Issue by jinqianlee** [graphhopper/graphhopper#513]
For the two points below, Graphhopper returns a route via I90 bridge, but ignores the much closer WA520 bridge, which is a toll bridge:

https://graphhopper.com/maps/?point=5146%2025th%20Ave%20NE%2C%20Seattle%2C%20WA%2098105&point=3858%2C%20Hunts%20Point%20Road%2C%20Hunts%20Point%2C%20King%20County%2C%20Washington%2C%2098004%2C%20United%20States%20of%20America&locale=en-US&layer=Omniscale

However, other route planner (OSRM, MapQuest) can still use WA520 bridge:

http://www.openstreetmap.org/directions?engine=mapquest_car&route=47.6677%2C-122.3004%3B47.6462%2C-122.2286#map=14/47.6517/-122.2663

**Comment by karussell** [comment]
Hmmh, sounds odd. Currently we do not take into account toll or bridge. Will investigate.

**Comment by karussell** [comment]
The problem are the two barrier=lift_gate nodes per way: http://www.openstreetmap.org/node/29449063 and http://www.openstreetmap.org/node/29449064 and for 'car' we [block by default](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/routing/util/AbstractFlagEncoder.java#L254) for [potential barriers](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java#L86) currently.

**Comment by jinqianlee** [comment]
Thanks for the update. The bridge is a bascule bridge like the London Tower Bridge. It will stay open for most of the time. I think these liftgate tags are not necessary and should be removed from OSM.

**Comment by karussell** [comment]
I propose not to remove them, as those lift_gates make sense. If you e.g. add `access=true` GH will route through it (see [access wiki](http://wiki.openstreetmap.org/wiki/Key:access)).

**Comment by jinqianlee** [comment]
OK, I added "access=true". Let's keep the default behavior for now.
