### ISSUE TITLE
MotorcycleFlagEncoder: Copy&Paste Issue in defineWayBits()

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#527]
Hi,

I just found a minor Copy Paste Issue (https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/routing/util/MotorcycleFlagEncoder.java#L131)

Should be probably: `shift += priorityWayEncoder.getBits();`

This changed the priorities for motorcycle routes and therefore the defined prefer/avoid sets were probably not calculated correctly.

**Comment by karussell** [comment]
Thanks a lot, already merged! There should be only a problem before IF speedBits<3, so the default should be fine. Or do you have a failing unit test or real life scenario found which runs fine now?

**Comment by boldtrn** [comment]
I changed several things, including the copy&paste issue and afterwards my route was way better. I just checked and it seems that it had to do something with my weighting and not with the priorities itself.
