### ISSUE TITLE
how to achieve google animateCamera like functionality.

### ISSUE THREAD

**Issue by GitPiyush** [graphhopper/graphhopper#532]
Hello,

i want to move the cursor on the map which i am able to do animateTo function but i also want to keep my path north up just like we can do using google animateCamera. is it possible with Graphhopper android since i am exploring it for offline navigation. Please let me know if i can rotate my mapview to do so.

**Comment by devemux86** [comment]
I understand you mean the Android sample of GraphHopper.

This uses [Mapsforge](https://github.com/mapsforge/mapsforge) as map engine, so you need to ask such questions to its [mailing list](https://groups.google.com/forum/#!forum/mapsforge-dev).

BTW we have not released yet native map rotation, but we have an external map rotation example in Mapsforge samples.

**Comment by karussell** [comment]
For questions related to GraphHopper please use our forum.
