### ISSUE TITLE
Elevation data from local files

### ISSUE THREAD

**Issue by HarelM** [graphhopper/graphhopper#537]
Hi, first of all great project, I look forward to use it (currently running the web server for the first time :-))
I looked through the documentation and the issues here at Github and I didn't find an answer.
My question is as follow:
Assuming I have DEM data in a format like SRTM or CGIAR locally (if it is not in the right format I can make it so hopefully) on my server, can I point GH to use it instead of downloading the data?
I'm asking this question since I have data from aster which has a better resolution compared to the above two. The original data is noisy but some one very smart was able to clean it for me and now I have far better DEM data.
I want to use this data for GH, is it possible?

**Comment by karussell** [comment]
Please use the [forum](https://discuss.graphhopper.com/c/graphhopper) for questions.
