### ISSUE TITLE
Disallow routing on access=emergency

### ISSUE THREAD

**Issue by twzkxkan** [graphhopper/graphhopper#539]
motor_vehicle=emergency, etc.

Routing on ways specified for emergency vehicles can be illegal and/or dangerous.

**Comment by karussell** [comment]
Do you have an example where this problem occurs?

**Comment by twzkxkan** [comment]
Often on divided highways for police/ambulance/maintenance use.

[Graphhopper](https://graphhopper.com/maps/?point=40.724242%2C-111.51307&point=40.723567%2C-111.515297&locale=en-US&vehicle=car&weighting=fastest&elevation=true&layer=OpenStreetMap)

OSM Way:https://www.openstreetmap.org/way/36839451

**Comment by karussell** [comment]
Thanks! Do you know if this is only forbidden for motor vehicles or also for bike/foot?

**Comment by karussell** [comment]
Okay, I should just look in the wiki, according to this it is only for motor vehicles

**Comment by twzkxkan** [comment]
No, access tags apply to *every* mode of transportation.

Restrictions on individual modes would be expressed as motor_vehicle=*, bicycle=*, horse=* and so on.

**Comment by karussell** [comment]
Okay. Do you have examples for how this would be mapped?

**Comment by twzkxkan** [comment]
Sorry, I don't quite understand your question. [Here](https://www.openstreetmap.org/way/105407029) is an example of a road that's open to bicycle and foot traffic but only open to emergency motor vehicles.

motor_vehicle=emergency
bicycle=designated
foot=designated

**Comment by karussell** [comment]
I would need a tagging example where bicycle is forbidden due to the emergence. Would this something like:
highway=service
access=emergency
?

**Comment by twzkxkan** [comment]
Since the access key applies to all modes, in that case only emergency bicycles would be permitted.

**Comment by karussell** [comment]
> Any traffic that is not an emergency mode is prohibited.

Hmmh, that could be one interpretation. Another could be: we require here all vehicles to be emergency, except foot and bike. This interpretation seems more logically to me as this is done in other places AND motor_vehicle=emergency but bicycle=yes not e.g. bicycle=emergency

**Comment by twzkxkan** [comment]
> we require here all vehicles to be emergency, except foot and bike

If you wanted to reflect that it could be mapped as

access=emergency
foot=yes
bicycle=yes

or
motor_vehicle=emergency

The foot and bicycle restrictions would depend on the [implicit default value](: we require here all vehicles to be emergency, except foot and bike) of the parent way.

**Comment by karussell** [comment]
So we need more things to cover all situations:
 * emergency=yes
 * other vehicles should be excluded then, not only car and motorcycle

**Comment by twzkxkan** [comment]
emergency=yes seems too ambiguous for routing. Do you have examples of how this would be mapped?

**Comment by karussell** [comment]
Sorry, then I had a misunderstanding as you referenced an example with it:
https://www.openstreetmap.org/way/105407029

so we can ignore this for routing and just use normal access schema?

**Comment by twzkxkan** [comment]
In this example there is no access=* tag so the default restrictions of highway=service apply.

The following restrictions on individual modes are then applied

motor_vehicle=emergency (only emergency motor_vehicles)
foot=designated
bicycle=designated

I didn't notice the emergency=yes tag before, but now I do. This is probably too ambiguous to be used for routing restrictions. It may indicate that emergency vehicles may use the road (which is already implied by the defaults) or that the road has some association with emergency services.

**Comment by karussell** [comment]
Ok, so this makes things a lot easier and I just added the emergency restriction (similar to military) to all the vehicles.

**Comment by karussell** [comment]
I'll soonish deploy a new version to GraphHopper but will keep this here open until it

**Comment by twzkxkan** [comment]
That sounds like the best approach. Access tagging can be tricky and there may be errors in the data itself which makes interpretation more difficult. Thanks for your work.

**Comment by karussell** [comment]
This is now deployed. Please reopen if you still find problems!

**Comment by twzkxkan** [comment]
Thanks again! And double thanks for working through confusing documentation. :)
