### ISSUE TITLE
Unable to compile on windows with maven in program files

### ISSUE THREAD

**Issue by HarelM** [graphhopper/graphhopper#544]
When placing maven in c:\program files\ and running ```graphhopper.sh build``` the build fails - probably something with the grep...
As a work around I place MAVEN_HOME in the environment variables.

**Comment by karussell** [comment]
or probably due to the spaces, please check if quotes help ala `"$MAVEN_HOME/....."`

**Comment by HarelM** [comment]
Nope...
mvn -v | grep "Maven home" | cut -d' ' -f3
returns c:\Program
as expected since the results of the grep is "Maven home: C:\Program Files\apache-maven-3.3.3\bin\.."

**Comment by HarelM** [comment]
The following does work as far as I can tell for windows:
mvn -v | grep "Maven home" | cut -d' ' -f3,4,5,6
it is a bit ugly though... (5,6 are just in case someone is even dumber than me :-)...)

**Comment by devemux86** [comment]
In Windows you could place Maven in a directory without spaces:
https://maven.apache.org/guides/getting-started/windows-prerequisites.html

**Comment by HarelM** [comment]
I could, But I prefer not to place stuff under my C:\ driver directly....
I'll submit a pull request with the fix I made...

**Comment by karussell** [comment]
Okay, probably we should then find a more robust solution to find out the maven home ...
