### ISSUE TITLE
Should bicycle=yes be really stated as cycleway?

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#546]
I got an email stating that [this path](https://graphhopper.com/maps/?point=45.350622%2C11.671686&point=45.351723%2C11.666236&locale=en&vehicle=bike&weighting=fastest&elevation=true&layer=OpenStreetMap) is not a cycleway it is only highway=track|path and bicycle=yes

**Comment by voschix** [comment]
Sorry, the path in question is highway=residential. I am the person who signalled the problem to Peter
It looks as if you are interpreting the combinations highway=unclassified|residential|tertiary|secondary|primary AND bicycle=yes as presence of a cycleway.
The combination highway=path|track AND bicycle=yes is, correctly, not considered as cycleway

**Comment by karussell** [comment]
Although @ratrun seems to have understood your issue I'm not that fast this time :)

So you think all is fine except for highway=residential and bicycle=yes where it should not be a cycleway?

**Comment by ratrun** [comment]
It doesn't look as if @voschix has received your question. The best way to see what was meant is to open the link above, study the directions and in parallel open the area in JOSM to study the tags of the choosen ways. It is valid for all kind oy ways, even for highway=motorway with bicycle=yes. Here the instruction classified such a segement as cycleway - which was not the intended behaviour when I implemented this pretty long ago.

**Comment by buma** [comment]
What about highway=path, bicycle=designated? This is preset tag for tagging combined and segregated cycleways and footways in JOSM. [osm wiki](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dcycleway).

**Comment by ratrun** [comment]
@buma: highway=path, bicycle=designated should be classified as cycleway.
See following test: https://github.com/graphhopper/graphhopper/blob/master/core/src/test/java/com/graphhopper/routing/util/AbstractBikeFlagEncoderTester.java#L306

**Comment by voschix** [comment]
@karussell: Sorry I had overlooked your implied question.

My original warning was (which I had sent via e-mail): 
"When a way is tagged with any of 
        highway=residential|unclassified|tertiary|secondary|primary 
AND 
       bicycle=yes

the turn-by-turn instructions refer to a cycleway (in Italian “pista ciclabile”) on that road. This is not correct. bicycle=yes only states that bicycles are allowed on that road, but it is not a cycleway

Note that the combinations 
    highway=track|path 
AND 
    bicycle=yes 
are correctly not interpreted as cycleway."

(slightly reworded)

**Comment by karussell** [comment]
Thanks again! @ratrun PR is merged now!
