### ISSUE TITLE
graphhopper zoom to current location

### ISSUE THREAD

**Issue by spring1370** [graphhopper/graphhopper#550]
I'm using graphhopper for offline routing in android , How does my program show current location with mobile GPS
and after that zoom to that point (point of my current location ) ?

**Comment by karussell** [comment]
That map issues are unrelated to GraphHopper (probably you are using mapsforge, please ask there). Furthermore if you have questions regarding GraphHopper please use [our forum](https://discuss.graphhopper.com/)

**Comment by spring1370** [comment]
thanks
