### ISSUE TITLE
Trim lines during import of config.properties

### ISSUE THREAD

**Issue by matze09** [graphhopper/graphhopper#551]
Hi,

thanks for the great work on this Java routing library!

I just realised that lines in the `config.properties` containing a leading blank are silently ignored by the library. It seems the lines are not being trimmed within the custom import of the config.properties file in `Helper.java:loadProperties()`.

However, the example config is apt to contain invalid properties if you just uncomment some example properties (e.g. `prepare.chWeighting=no`). A leading blank will remain and the property will not be taken into account. It just took me some debugging to realise that :-)

I think either trimming the lines or reporting to the user in some way that there is a invalid property should be added.

Java 7 also has built-in support for reading properties from properties-files, cf. http://docs.oracle.com/javase/7/docs/api/java/util/Properties.html#load(java.io.InputStream)
Maybe it could be used instead of the custom implementation?

Many thanks,
Matthias

**Comment by karussell** [comment]
Thanks for reporting! Very ugly but fixed now!

> Maybe it could be used instead of the custom implementation?

The core is currently even for 6 :)
But the config will be replaced soon via json (at least planned) so I currently see no need.

**Comment by matze09** [comment]
Cool, thanks for the quick fix.

All right, I thought it was for Java 7. Right, switching to a JSON config seems like a reasonable idea.

Thx,
Matthias
