### ISSUE TITLE
Error in graphhopper for android 

### ISSUE THREAD

**Issue by spring1370** [graphhopper/graphhopper#554]
hi , I'm using graphhopper for android , before I run this project in android studio and every thing was ok. but now I run that project and that have error ,that error is : 
" chweighting [fastest|car] is not equal to [loaded [FASTEST|car]"

what should I do?

**Comment by karussell** [comment]
We changed a bit the format. This is nothing you should mess with, just make sure you do not change the GraphHopper version or reimport the area.

**Comment by spring1370** [comment]
I didn't change Graphhopper version :(
where can I download 0.5 ?

**Comment by spring1370** [comment]
Thanks a lot, I used 0.5 , and it worked correct
