### ISSUE TITLE
Remove LGPL code from core

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#562]
A few places use LGPL, it is not an issue for most users and companies but for some due to restrictiv license obligations. We need to 
- move IntDoubleBinHeap out of the core
- replace trove4j with hppc or similar, see #34 
- can we replace OSM-binary? (this is no longer in the core)

**Comment by devemux86** [comment]
How about separating more clearly ```core``` from ```tools```?
i.e. ```core``` for reading graphs and routing and ```tools``` (or else) for reading osm and creating graphs.
Right now graph creation is integrated in ```core```, so the osm read dependencies.

**Comment by karussell** [comment]
:+1: 
that is the next step :) which will - at the end - move all OSM stuff into `tools` or even better into a new `osm-import` module? Otherwise e.g. web needs a dependency on `tools` which also contains unnecessary swing stuff. 

But e.g. the heap can't be moved up-stream as `core` depends on it. Maybe we'll replace the classes there at some point, but for me this is none critical. Just wanted them separated.

**Comment by karussell** [comment]
The question is also a bit what we do with the GraphHopper class which belongs to the `core` but needs the osm import and we don't want reflection. 

So the result will be something like:
```java
GraphHopper hopper = new GraphHopper() {
     protected DataReader createReader( GraphHopperStorage ghStorage )    {
        return initOSMReader(new OSMReader(ghStorage));
    }
}
...
hopper.importOrLoad();
```

or more explicitely:

```java
GraphHopper hopper = new GraphHopper().setDataReader(new OSMReader(osmFile));
...
hopper.importOrLoad();
```
Both would keep in mind e.g. cases like #277 

Or is this too complex for the normal developer? And we should implement additionally a special GraphHopper subclass?

```java
GraphHopper hopper = new GraphHopperOSM().setOSMFile(file);
...
hopper.importOrLoad();
```

Or even avoid renaming and name the subclass `GraphHopper` and the super class e.g. `GraphHopperCore`?

**Comment by devemux86** [comment]
(I agree that reflection should be avoided)

Your 3rd suggestion with separate classes seems more feasible to normal developers, which separates better the osm import.

**Comment by karussell** [comment]
Have to think about this - just to be sure - you meant the `GraphHopperOSM` style? Let us move to the new #563

**Comment by K-Leon** [comment]
I just had a look in IOS and Android Ports of Graphhopper:

Right now there are dependencies on LGPL Code for both - Android and iOS? 

This results in an incompatibility with usual linking and distribution ( Only static linking possible on IOS and so on ) or am i missing something?

Would love to give this lib a shot, but the dependence on lgpl modules makes this more or less impossible...

**Comment by karussell** [comment]
> Right now there are dependencies on LGPL Code for both - Android and iOS? 

The `tools-lgpl` is indeed not required for both and the trove4J lib is necessary only for Android but could be replaced (#34)

So nothing very problematic IMO

> Would love to give this lib a shot, but the dependence on LGPL modules makes this more or less impossible...

Why?

**Comment by K-Leon** [comment]
This sounds great! I'll have a look into it

> Why?
Just googelt a bit and a key requirement of LGPL License is to dynamically link the library. On IOS this isn't possible and on Android there are a few approaches that are more or less questionable. This is mostly because of app store distribution.

**Comment by karussell** [comment]
I got rid of the separate lgpl module via adapting the binary heap from apache collections to our required interface (just min heap, store keys and elements separately, including update method)

**Comment by karussell** [comment]
@K-Leon the core is now free from LGPL dependencies - thanks to #878. Maybe you have time to update the iOS port :) ?

**Comment by K-Leon** [comment]
Wow! Thank you so much for your hard work! I'll give it a spin next week.
