### ISSUE TITLE
Moving Android downloads to a subdomain

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#565]
Due to the big data size (from the area zip files) we have to avoid that the download goes through our main server.

Keep in mind that downloading from a browser might fail due to hsts but `curl http-url` will do it

**Comment by alFReD-NSH** [comment]
download2.graphhopper.com doesn't work anymore.

**Comment by karussell** [comment]
It works via curl, just not in the browser if you visited graphhopper.com before.

**Comment by alFReD-NSH** [comment]
Yeah, it does. But I'm getting this in android also: `java.io.FileNotFoundException: http://download2.graphhopper.com/public/maps/0.6/`. Any idea why?

**Comment by karussell** [comment]
Hmmh, are you using the latest master? As [this fix](https://github.com/graphhopper/graphhopper/issues/498#issuecomment-158334369) is important.

**Comment by devemux86** [comment]
Just checked again the Android sample (latest master) and downloads the data fine.

**Comment by alFReD-NSH** [comment]
#498 was the problem. Somehow I was using v0.5.0, upgraded to the latest, all fine now. Thanks for your help.

**Comment by karussell** [comment]
@devemux86 & @alFReD-NSH thanks!
