### ISSUE TITLE
funny ferry routing 

### ISSUE THREAD

**Issue by knowname** [graphhopper/graphhopper#570]
https://graphhopper.com/maps/?point=55.721116%2C12.666893&point=55.700614%2C12.586899&locale=de&vehicle=car&weighting=fastest&elevation=true&layer=OpenStreetMap

To prevent that you could check whether its water or land beeing skipped. (start point to next routable point)

**Comment by karussell** [comment]
Thanks. I think this is a duplicate #322?

**Comment by knowname** [comment]
Ah true! my search failed because i only searched for ferry - not ferries.
And i guess its not much of a difference if its foot or car routing.
Thanks for your quick reply

**Comment by karussell** [comment]
No problem and thanks a lot for reporting - do not fear to report duplicates or post suggestions or discuss topics [in our forum](https://discuss.graphhopper.com/)
