### ISSUE TITLE
Escape street names for GPX properly

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#572]
Streets can contain chars like `<` (intended or not) and therefor we should escape them properly when creating xml turn instructions.

[GH maps link](https://graphhopper.com/maps/?point=49.428547%2C11.061087&point=49.427947%2C11.064906)

The ref is tagged as `<`!? http://www.openstreetmap.org/way/251217044

**Comment by karussell** [comment]
Moving to a 'proper' XML writer would be probably the simplest thing and could be even faster (?) but due to portability and less deps we should aim for simplicity here IMO. I.e. simple string replacement.

**Comment by devemux86** [comment]
:+1:

**Comment by karussell** [comment]
I'll create a fix via:
```java
static String simpleXMLEscape( String str )
{
     return str.replaceAll("&", "&amp;").
                // but do not care for:
                replaceAll("[\\<\\>]", "_");
}
```
