### ISSUE TITLE
IntelliJ Formatting

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#576]
Hi,

I use IntelliJ 15 with graphhopper. The given formatting.jar is not matching the current graphhopper formatting (at least in my case). Setting all required settings by hand is a bit frustrating. As current workaround I use Netbeans to fix the formatting (this is very ugly).

Maybe related to: #521

**Comment by karussell** [comment]
Hmmh that is ugly. I was hoping the formatting stuff in IntelliJ is kind of static. The most important thing is the opening bracket on a separate line - is at least that working at all in the new version?

**Comment by boldtrn** [comment]
Yes, if I manually set it. Don't know if anything more than just importing these settings is necessary? I can also select the profile in the formatter, but that didn't change it for me.

**Comment by boldtrn** [comment]
The new IntelliJ profile is merged, so we can probably close this.
