### ISSUE TITLE
Dijkstra potential Optimization

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#577]
Hi,

-- I am not sure if this will work for graphhopper's version of the Dijkstra (both Bi and normal), but I think it should work. It works for the Dijkstra algorithm in general --

Here the remove function is called on the PriorityQueue (https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/routing/Dijkstra.java#L103). The remove function is in `O(n)`.

How about we do not remove the current edge. But update the weight in the map.

If we poll edges from the queue we could check if the weight is greater than the weight in the map. In this case we already updated that edge and can just poll for the next edge. What do you think?

**Comment by karussell** [comment]
I've tried that and it was slower or at least not faster. The queue is not that big. But please try again, maybe it is worth under certain conditions or for the recent version. Such boosts & changes would be highly appreciated!

**Comment by karussell** [comment]
Related to #475 and #489

**Comment by karussell** [comment]
Closing for now.
