### ISSUE TITLE
Duration parsing dependent from current time

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#588]
Currently the parsing of two month is not a fixed amount of days (and a bit too strict), therefor it fails as of today ;)

```java
assertTrue(87840 * 60 <= OSMTagParser.parseDuration("P2M"));
assertTrue(87900 * 60 >= OSMTagParser.parseDuration("P2M"));
```

Should/can we avoid this somehow and always use the same start date?

Otherwise the span can be a bit broader:

```java
// 28+31
assertTrue(2*28*24*60* 60 <= OSMTagParser.parseDuration("P2M"));
// 2*31 (dez+jan!)
assertTrue(2*31*24*60* 60 >= OSMTagParser.parseDuration("P2M"));
```

**Comment by karussell** [comment]
@ratrun do you have an idea? Should we use a fixed date or should we keep interpreting "2 months" dynamically?

**Comment by ratrun** [comment]
The releaxed check looks fine to me. I'm sorry for the inconvenience with this. I didn't expect that the calculation for a duration of 2 months really depends on when you calculate the duration. Obiously this also does not even seem to be that strictly specified, as openJDK and Oracle JDK returned slightly different values from the beginning.

**Comment by karussell** [comment]
> The releaxed check looks fine to me. I'm sorry for the inconvenience with this.

As always: no need to sorry :) ! It is the opposite: I and the other users have to thank for all contributions you made :) ! (Also I avoid to say sorry in github issues if something is broken, because GH is provided "as it, without warranty". Of course, this is different for our commercial offering... )

> openJDK and Oracle JDK returned slightly different values from the beginning.

Interesting! I would like to avoid this dependency. Would you be okay if we specify the 1st Dec 2015 as starting point? This way the maximum length (2*31) is always used.

**Comment by ratrun** [comment]
This of course also would be fine. I you make the I can learn how this can be achieved. I don't know how to do that and would need to search for it.

**Comment by karussell** [comment]
Uhm, the newly introduced fixed date fails on our windows build machine.

**Comment by karussell** [comment]
It looks like this earlier date is running identical on windows machines.

**Comment by zhiqiangZHAO** [comment]
if you consider Daylight Saving Timezone, 1 month could be 31 days and 1 hour...

**Comment by karussell** [comment]
> if you consider Daylight Saving Timezone, 1 month could be 31 days and 1 hour...

Indeed I have not thought about this. But I do not think that this was the issue as the change is not made in December or January :) 
BUT now that I think about it: I used 1.12.2015 and having a different time zone has probably shifted it to 30.11. where it makes sense that we than get just 30+31 days...

**Comment by zhiqiangZHAO** [comment]
maybe a better idea is not convert the duration time to seconds.
For example, it says 2 month, then you store M2.
And you got a start time in Calendar start, 
then start.add(Calendar.Month, 2);

The java.util.Calendar will handle this kind of thing for you. 28 days, 31 days.

**Comment by karussell** [comment]
I would like to stay away from the Calendar stuff in our API :)

But in general you are right, still I cannot think about an example where these mistakes would lead to a real issue where we use the duration stuff in GraphHopper. E.g. if the ferry takes 2 months then the duration itself is not that precise and could be easily improved via specifying the exact days it takes, if at all possible/necessary. Also I don't think a duration of something will change only because it has a different start date.

**Comment by zhiqiangZHAO** [comment]
I agree the 1 hour doesn't mean too much compare to 2 months.
Could I know why you want to keep away from Calendar stuff? too complex?

**Comment by karussell** [comment]
Too complex / error-prone and is replaced with joda implementation in java 8 I think

**Comment by karussell** [comment]
@zhiqiangZHAO would you mind to send me your Email? https://graphhopper.com/#contact
