### ISSUE TITLE
Routing with(Bike/Walk/car)

### ISSUE THREAD

**Issue by coniocharles** [graphhopper/graphhopper#589]
I just used graphhopper this day and implemented it successfully in my application. 
But my app needs to have routing options. Eg. Route using bike, by walking or by car. How can i do that? Cant find tutorials how to implement those. Or i'm just not trying my best to search? Thank you.

**Comment by karussell** [comment]
Please use our forum to ask questions and see the documentation for all the details.
Also tell there exactly what you did
