### ISSUE TITLE
Bike directions should take the motorway

### ISSUE THREAD

**Issue by HelgeKrueger** [graphhopper/graphhopper#592]
When no other street is available, cyclists are often allowed to take motorways (resp. the "Autovia" in this case). An example for such a piece of road is
http://www.openstreetmap.org/way/4988947
There are actually no signs saying it's legal to ride a bike, but very explicit signs you have to get off the Autovia when there is another road available.

I first observed this with the following route
https://graphhopper.com/maps/?point=Morro%20Jable,%20Spain&point=costa%20calma&locale=en-US&vehicle=bike&weighting=fastest&elevation=true&layer=Omniscale
Here Graphhopper suggests taking the ferry twice. Instead it should pretty much show the same directions as for cars.
The following piece of the interstate I-5 has a "bicycle = yes" tag, but also seems to be ignored when querying Graphhopper.
http://www.openstreetmap.org/way/32133206
However, there is the ok-ish alternative here of riding through a military base. This involves showing ID several times, so the I-5 would be preferred. Also bicycle=yes is not documented on http://wiki.openstreetmap.org/wiki/Tag:highway=motorway?uselang=en-US.

I think that Graphhopper should somehow make use of motorways for bicycle directions. At least when the alternative is taking a ferry twice. At least for the RacingBike profile, I would actually put the preference of a motorway with usually a wide shoulder over a dirt road.

**Comment by ratrun** [comment]
These are clearly tagging problems becuase the `bicycle=yes` tag is missing. We are very strict for allowing usage of motorways for bicycles. You referrend wiki link clearly states that motorways are banning none motrized traffic and you might have a look into http://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access-Restrictions . 

As proof that it works in case that `bicycle=yes` is see https://www.graphhopper.com/maps/?point=33.311235%2C-117.480068&point=33.241631%2C-117.415223&locale=de-DE&vehicle=racingbike&weighting=fastest&elevation=true&layer=Omniscale 

@karussell : This ticket can be closed

**Comment by karussell** [comment]
Thanks for this @HelgeKrueger & @ratrun 

What about this - is this solved?

> The following piece of the interstate I-5 has a "bicycle = yes" tag, but also seems to be ignored when querying Graphhopper. http://www.openstreetmap.org/way/32133206
