### ISSUE TITLE
Documentation: How to Deploy Graphhopper

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#593]
Hi,

I just started deploying my own instance of graphhopper to a server. I did as described in the quickstart:  https://github.com/graphhopper/graphhopper/blob/master/docs/core/quickstart-from-source.md

Could we extend this part to create a convenient documentation (probably a separate page).

Things I missed:
* Tokens. You use tokens in the js. They should be changed (or not?). For example I do not have an Omniscale token, therefore I had to remove it from the js.
* Best practices. How to configure the server to create good performance.

**Comment by karussell** [comment]
> Tokens. You use tokens in the js. They should be changed (or not?). For example I do not have an Omniscale token, therefore I had to remove it from the js.

Yes, feel free to add this to the documentation or maybe we should make it part of the change #590?

Also this doc would need it then:
https://github.com/graphhopper/graphhopper/blob/master/docs/web/quickstart.md

> Best practices. How to configure the server to create good performance.

Good performance should be the default.

**Comment by boldtrn** [comment]
> Good performance should be the default.

Don't get me wrong. The performance is great, but I was wondering if there is nothing else I have to setup?

> Yes, feel free to add this to the documentation or maybe we should make it part of the change #590?

I thought it would be nice to have one document that explains the most important things if you want to get started deploying graphhopper.

I can add the part about Omniscale. And the developer Part into a new document and link it from both quickstart documents. Anything else we should add?

**Comment by karussell** [comment]
> Don't get me wrong. The performance is great, but I was wondering if there is nothing else I have to setup?

You can tune a lot, but the defaults should already be the 'best' in general.

> And the developer Part into a new document and link it from both quickstart documents. Anything else we should add?

I would avoid this new document - maybe just this here: https://github.com/graphhopper/graphhopper/blob/master/docs/core/world-wide.md and add a new "UI" topic?

**Comment by boldtrn** [comment]
> I would avoid this new document - maybe just this here: https://github.com/graphhopper/graphhopper/blob/master/docs/core/world-wide.md and add a new "UI" topic?

The name of this document is misleading. If you are looking for deployment information for a single region you would not read that file. I can refactor it and rename it to deployment.md.

**Comment by karussell** [comment]
> I can refactor it and rename it to deployment.md

Good idea, please also put the world wide specific information into yet another topic.

**Comment by karussell** [comment]
It might be also wise to put in the description of the parameters

```
prepare.minNetworkSize=200
prepare.minOneWayNetworkSize=200
```

to avoid all the "route not found" errors questions ;)

**Comment by boldtrn** [comment]
Also, we should link the new deploy.md file from the index (forgot to do this)

**Comment by boldtrn** [comment]
Just two more things. Maybe we should add a part about continous deployment and logging.

Continous Deployment:
How to deploy a new version with minimal downtime. My current script looks like this. Not sure if you have a better version:
```
#!/bin/bash

echo "## CD into Directory"
cd /var/www/[your_application]/

echo "## Exporting Environment Variables"
export GH_FOREGROUND=false
export JETTY_PORT=80

echo "## Clean Jar"
./graphhopper.sh clean

echo "## Build Jar"
./graphhopper.sh build

# Only Valid if you run no other java appliations.
echo "## Kill Java Applications"
pkill -f java
sleep 1

echo "## Start Web Application"
./graphhopper.sh web [your OSM file]
```

Logging:
I run graphopper in background. You will not get logging messages anymore, once you disconnected from the server (at least I don't see them anymore). If you reconnect, they are not printed anymore. I looked up possible solutions and found logentries. It is integreated into log4j config and collects all log entries. They can be viewed online at logentries.

**Comment by karussell** [comment]
> Maybe we should add a part about continous deployment and logging

We have a commercial wrapper around it and also have configured log4j to log directly into the files, but this is not yet a nice solution as we needed log rolling which requires a special add-on etc :(

But we can make a simple and good logging config work, but I have no ready production config yet. For the killing we do e.g.

```bash
nohup bash ./graphhopper.sh web /data/planet.pbf > /dev/null 2> logs/web.err.log &
echo $! > pid.txt
```

But killing via pid is not recommended, instead we should do similar to what elasticsearch is doing via start-stop-daemon or similar techniques: 

http://stackoverflow.com/q/25906020/194609
https://github.com/elastic/elasticsearch/blob/2.1/distribution/deb/src/main/packaging/init.d/elasticsearch#L169

BTW: regarding none-CH tuning - there is indeed some more settings you could change to get better performance -> #506

**Comment by boldtrn** [comment]
> We have a commercial wrapper around it and also have configured log4j to log directly into the files, but this is not yet a nice solution as we needed log rolling which requires a special add-on etc :(

I prefer to do logging with a web provider. I don't like file logging (especially when using several servers, you don't want to check every server). So I thought we could add some recommendations to the documentation.

> But we can make a simple and good logging config work, but I have no ready production config yet.

As I said, I just signed up for a free plan at Logentries and it works. Took me about 5 Minutes to setup. Therefore, I wanted to share it.

> start-stop-daemon or similar techniques

You are right, such a daemon looks good. We should definitely get something like this.

> BTW: regarding none-CH tuning - there is indeed some more settings you could change to get better performance -> #506

Thanks for the link. If I get you right, using A* instead of Dijkstra is faster for non-CH routing?

How do you deploy a new version with minimal downtime? I'd like to have really small downtimes. Currently I have only Server available, therefore the typical scenario using a load balancer is not working for me. Is my script already the "best" approach or is there anything to improve?

**Comment by karussell** [comment]
> I prefer to do logging with a web provider. I don't like file logging (especially when using several servers, you don't want to check every server). 

What do you mean here? You mean logging of the web server? I also do not think that belongs into GraphHopper. We should just make logging config for different cases easy enough and provide a simple file logging.

> Therefore, I wanted to share it.

Sure, share it - e.g. in the forum where it is easy searchable, but I do not see a reason for including it into GraphHopper docs. As logging is a world on its own.

> using A* instead of Dijkstra is faster for non-CH routing?

That is the case but you can also do bidir stuff and enable (and increase) heuristic nature to make speed a lot faster.

> How do you deploy a new version with minimal downtime

Providing two GraphHopper instances or two JVMs or two servers ...

> therefore the typical scenario using a load balancer is not working for me.

Why not? You can either use two GH instances or just run two JVMs on different ports...

**Comment by boldtrn** [comment]
> Sure, share it - e.g. in the forum where it is easy searchable, but I do not see a reason for including it into GraphHopper docs. As logging is a world on its own.

Yes I think you are right. It is better to do this somewhere else.

> That is the case but you can also do bidir stuff and enable (and increase) heuristic nature to make speed a lot faster.

Thanks. I will try the heuristics.

> Why not? You can either use two GH instances or just run two JVMs on different ports...

I am forced to use Port 80. Therefore I cannot setup two instances. If one uses Port 80 the other cannot open 80. That is why I am asking.

**Comment by karussell** [comment]
Regarding the update without downtimes: with a bit coding, you can have two GraphHopper instances swapped out on update. Requires double of the RAM, see for the feature request #211

**Comment by karussell** [comment]
Should we include parts of this discussion into the docs or can we close here?

**Comment by boldtrn** [comment]
Mhm, personally I am fine with it. I think creating a OpenStack plan or installable .deb package is the better solution.

**Comment by karussell** [comment]
Thanks, yes, openstack, docker and/or .deb would be nice to have.
