### ISSUE TITLE
EnableInstructions=false

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#594]
Hi,

if you disable the instructions in the properties, I'd except them to not show up in the UI. Currently they do.

Here Instructions are set to true:
https://github.com/graphhopper/graphhopper/blob/master/web/src/main/java/com/graphhopper/http/GraphHopperServlet.java#L72

Here we get the instruction variable that will be true if not explicitly set to false:
https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/GraphHopper.java#L991

My solution would be to do the following assignment in Graphhopper.java:
`boolean tmpEnableInstructions = enableInstructions && request.getHints().getBool("instructions",true);`

But then we would have to check if there are instructions in the GraphHopperServlet.

**Comment by karussell** [comment]
> I'd except them to not show up in the UI. Currently they do

Do you mean disabling via the config.properties? And if the instructions are not included in the graph storage how would they show up or is there a error involved then?

BTW: why did you disable parsing instructions? As instructions (street information) can be very important for debugging maybe we should we remove this 'feature'?

**Comment by boldtrn** [comment]
> Do you mean disabling via the config.properties?

Exactly

> And if the instructions are not included in the graph storage how would they show up or is there a error involved then?

The do not contain street names e.g.: take 2. exit of the roundabout.

> BTW: why did you disable parsing instructions? As instructions (street information) can be very important for debugging - maybe we should we remove this 'feature'?

I thought this would reduce the storage size, therefore I disabled it. I don't need them right now.

**Comment by karussell** [comment]
> The do not contain street names e.g.: take 2. exit of the roundabout

hmmh, probably we then should rename instructions=false to street_names=false in the config.properties and always use `request.getHints().getBool("instructions",true)`? This would feel more logically to me at the moment.

> I thought this would reduce the storage size, therefore I disabled it. I don't need them right now.

ok, yes.

**Comment by boldtrn** [comment]
The instructions that are shown when instructions=false are not really useful in my opinion. Changing the parameter name will work as well, for saving storage size.

![screen shot 2015-12-07 at 13 51 17](https://cloud.githubusercontent.com/assets/1553525/11627299/b430883e-9ce9-11e5-9be9-1a9ddfff9e88.png)

**Comment by karussell** [comment]
> The instructions that are shown when instructions=false are not really useful in my opinion

Hmmh, only roundabout instructions are shown?

Other instructions should show up there and yes, instructions without street names are not really helpful but better than nothing and the use case is very rare so that we can live with it IMO

**Comment by boldtrn** [comment]
> Hmmh, only roundabout instructions are shown?

Haven't seen anything else, yet.

> Other instructions should show up there and yes, instructions without street names are not really helpful but better than nothing and the use case is very rare so that we can live with it IMO

You are right. If there are instructions without street names, I am fine with it. It shouldn't be too hard to change it for my scenario ;)

**Comment by karussell** [comment]
> > Hmmh, only roundabout instructions are shown?

> Haven't seen anything else, yet.

I fear, this is a bug in the instruction creation checking street names against the empty string "" leading always to roundabout somehow. Hmmh.

**Comment by karussell** [comment]
Probably we should just close here and say without instructions it is no longer supported?

**Comment by boldtrn** [comment]
> Probably we should just close here and say without instructions it is no longer supported?

I am fine with this, but disabling might save some storage space? Maybe we should investigate here a bit more? I think this should be rather easy to implement, if instructions are disabled, we shouldn't add the instruction array to the response, therefore we don't have to call the instruction generation method.

**Comment by karussell** [comment]
No one ever requested this again so I would propose to just close until someone has a real use case.

**Comment by boldtrn** [comment]
Ok, will close this.
