### ISSUE TITLE
Mapsurfer is not working

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#601]
Hi,

I just played around with the tile services of graphhopper. Mapsurfer seems to be not working (currently?).

Even when visiting https://graphhopper.com/maps/ and select Mapsurfer the tiles are not loaded. Not sure if this is a temporary issue.

**Comment by karussell** [comment]
Mapsurfer is an external service and ... ping @MapSurferNET - should we change to the servers you use in your demos or is external usage no longer allowed?

**Comment by karussell** [comment]
Fixed! Thanks for reporting. See also [this tweet](https://twitter.com/maximrylov/status/674553679685525504)
