### ISSUE TITLE
Address Autocompletion using Photon

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#603]
When entering a location to address inputs, a request ist send to: `/geocode...`. Unfortunately this is not found. 

I guess this behaviour is intended? How about enabling https://photon.komoot.de/ as a fallback?

**Comment by karussell** [comment]
GraphHopper is just the routing service, no geocoding or tiles are provided. And we already do a fallback to osm.org if photon auto completion is not usable (locally). If we would enable falling to komoot instance the chances are too high that too many users will deploy this into production.

The easy solution: they grab a free API key from GraphHopper and are done.

BTW: the same is true for the tiles but omniscale was so generous to provide them for the GraphHopper Maps demo for free - but only for the graphhopper.com deployment.

**Comment by boldtrn** [comment]
> And we already do a fallback to osm.org if photon auto completion is not usable (locally).

Really? But not for type-ahead, only for reverse geocoding using nominatim? https://photon.komoot.de/ allow the usage of type-ahead.

> If we would enable falling to komoot instance the chances are too high that too many users will deploy this into production.

Yes you are right.

> The easy solution: they grab a free API key from GraphHopper and are done.

I did that just now and entered it in ghrequest.js: `this.key = "some-key";`. I still get a 404. Do I need to change anything else?

**Comment by karussell** [comment]
> But not for type-ahead, only for reverse geocoding using nominatim?

For both. Clicking on 'search' or enter will trigger a nominatim search instead of photon.

But also nominatim will be replaced soon by our search API. But of course everyone should be able to easily replace their own search server. I just don't want that osm.org etc is queried from too lazy users ... and we had these problems for the routing API too when it was unprotected. Most of the users are nice and replace this in production, but there are always some black sheeps :(

> I did that just now and entered it in ghrequest.js: this.key = "some-key";. I still get a 404. Do I need to change anything else?

Are you using the latest master? Then you'll need to call `npm run bundleUgly` for a deployment or for development do `npm run watch`

**Comment by boldtrn** [comment]
My repository is approximately 2 weeks old. Before the JS modularization. My js is requesting my own server for geocoding and not your Api.

**Comment by karussell** [comment]
> My js is requesting my own server for geocoding and not your Api

Then you'll need to change the host of the Geocoding API, probably also something we need to make easier to configure: https://discuss.graphhopper.com/t/modularize-javascript-code/306/16

**Comment by boldtrn** [comment]
Yes probably. I actually thought there would be some switch/boolean in the code that allows to setup these things. That's why I was asking.

Ok I can verify that if I change my api key and the host the address autocompletion works. I set the host to `"https://graphhopper.com/api/1"`. I guess api version 1 is still the correct version.

Thanks for your help. We should document this #593. Probably we should also make this easier to configure. Thanks for your support this issue seems to be solved.

**Comment by karussell** [comment]
> I guess api version 1 is still the correct version

Yes 

> Thanks for your support this issue seems to be solved.

Thanks! And yes, we should document this better and before we need to make it possible at all with the new NPM infrastructure :)
