### ISSUE TITLE
Indoor  new direction Instruction

### ISSUE THREAD

**Issue by dimohamdy** [graphhopper/graphhopper#607]
indoor need new direction Instruction like images 

![1](https://cloud.githubusercontent.com/assets/1476754/11845212/70350c8e-a41b-11e5-9233-6981c8922f80.png)
![2](https://cloud.githubusercontent.com/assets/1476754/11845213/704158cc-a41b-11e5-8e20-e0cabee76e7d.png)
![3](https://cloud.githubusercontent.com/assets/1476754/11845214/70483052-a41b-11e5-882e-63988406d7aa.png)
![4](https://cloud.githubusercontent.com/assets/1476754/11845215/705741b4-a41b-11e5-8e13-a14c7d290ba6.png)
![7](https://cloud.githubusercontent.com/assets/1476754/11845216/70616bb2-a41b-11e5-830d-7e0899fa55d0.png)

**Comment by karussell** [comment]
What is the issue you have and what do you mean with the images?

**Comment by dimohamdy** [comment]
when the Instruction is left i add <--- image then Instruction is right the image is ---> on map 


the route on map have two image  in the straight route ->---------------------<-
are this clear now?

**Comment by karussell** [comment]
No, I don't understand this. Is this a question or a feature request. Please describe what you need or what is not correctly working with simple words or with a step by step guide

**Comment by dimohamdy** [comment]
the problem is the direction Instruction not from the current position it's depend on the last direction Instruction

**Comment by karussell** [comment]
You mean an instruction like 'go upstairs' instead of 'turn right' is missing? I would not add these instructions before implementing to read the indoor tags.

**Comment by dimohamdy** [comment]
when i use graphhopper in routing in Nutiteq the direction not correct 
![unnamed](https://cloud.githubusercontent.com/assets/1476754/12452297/6b1b90ce-bf96-11e5-94c4-0896be546b89.png)

**Comment by karussell** [comment]
Please describe what your problem is and use the discussion forum to discuss problems: https://discuss.graphhopper.com/

I've opened a new issue #646 indicating the feature request about indoor routing. What you are asking now is about the missing or too many instructions, where already issues exist.
