### ISSUE TITLE
JS Autocomplete - mapLayer is not defined

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#609]
Due to the modularization of the JS we introduced a bug.

In the autocomplete.js we call `mapLayer.focus(req, 15, index);`

However the mapLayer is not defined. If we'd define the mapLayer and call the focus method. The focus method cannot find the method `setFlag` which is defined int the main-template.js.

I am not sure

**Comment by karussell** [comment]
Hmmh, when do you get this bug? What steps do you do to reproduce this?

**Comment by boldtrn** [comment]
You have to enable autocomplete in the main template. Then start typing and select one of the autocomplete items. Now it should focus that location on the map. But you get the exception.

**Comment by karussell** [comment]
Ah, okay. So this does not occur as I've not yet deployed it ... so also kind of related to #611

**Comment by karussell** [comment]
BTW: layer= scheint auch leer zu bleiben ...

**Comment by boldtrn** [comment]
As a quickfix I'd propose to change the autocomplete.js to:

```
if(mapLayer){
   mapLayer.focus(req, 15, index);
}
```

> BTW: layer= scheint auch leer zu bleiben ...

What do you mean here?

**Comment by karussell** [comment]
Ups, I meant to write English ;) and it seems that the layer parameter after the modularization is always empty but should filled with the picked map overlay instead.

**Comment by karussell** [comment]
This is fixed thankfully from @fbonzon in #615

**Comment by boldtrn** [comment]
Works for me now. Thanks @fbonzon .
