### ISSUE TITLE
JS Deployment needs configuration

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#611]
We need to be able to configure some URLs and other variables different for localhost and production. See discussion [here](https://discuss.graphhopper.com/t/modularize-javascript-code/306/18?u=karussell).

@HelgeKrueger would you mind to create the initial architecture e.g. with just the GraphHopper API URL to be configurable? I'll do the rest :) !

**Comment by karussell** [comment]
Implemented this via envify. Will provide a PR soon

**Comment by karussell** [comment]
Implemented this, please enhance if necessary like for nominatim URL etc (put them in the options_dev.js)

**Comment by karussell** [comment]
The PR #590 was therefor easily deployable to GraphHopper Maps. Let me know if there are issues!

**Comment by karussell** [comment]
Reopening due to [error reports](https://discuss.graphhopper.com/t/modularize-javascript-code/306/32?u=karussell)

**Comment by karussell** [comment]
Should be fixed via a new approach.

**Comment by boldtrn** [comment]
Something that should be configured here as well is the CORS handling. If setup my production environment I get the following exception when accessing the geocoding API:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://graphhopper.com/api/1/geocode?limit=6&type=json&key=myKey&q=wer. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
```

**Comment by karussell** [comment]
Maybe http vs. https?

**Comment by boldtrn** [comment]
I was using http to serve my site. 

I guess it is related to the datatype. I found information on the internet that for cross-origin request one should use jsonp.

http://stackoverflow.com/questions/25310450/cross-domain-javascript-cors-concept
http://stackoverflow.com/questions/3506208/jquery-ajax-cross-domain

This is also mentioned in the GHRequest.js at the datatype definition. `// use jsonp here if host allows CORS`.

**Comment by karussell** [comment]
jsonp is something old and should be replaced with CORS. We support CORS on the server side (for geocoding&routing) and so the JS should have no problem with it. Maybe you need to enable it in JS via `$.support.cors = true;`?

> I was using http to serve my site. 

but for geocoding you seem to use http://graphhopper.com?

**Comment by boldtrn** [comment]
Thanks. Using https for the graphopper API fixed my issue.
