### ISSUE TITLE
No turn by turn instruction 

### ISSUE THREAD

**Issue by as206em** [graphhopper/graphhopper#622]
Hi 
thanks for this great work
why there is no turn by turn instruction on this area

https://graphhopper.com/maps/?point=32.038535%2C35.896953&point=32.041995%2C35.903352&locale=en-US&vehicle=car&weighting=fastest&elevation=true&instruction=true&layer=OpenStreetMap

**Comment by karussell** [comment]
Please see the issues about missing or incorrect turn instructions like #94
