### ISSUE TITLE
avoiding toll roads

### ISSUE THREAD

**Issue by trippah** [graphhopper/graphhopper#643]
i was wondering if avoiding toll roads is available with graphhopper, if there is a workaround for it or if/when this option would be available.

thank you

**Comment by karussell** [comment]
Currently that is not possible out of the box but would be an important feature. Related: #311

**Comment by eliboni** [comment]
This seems still in the todo list, but routing API doc (https://graphhopper.com/api/1/docs/routing/) states in flexible features (ch.disable=true) is the option 

> avoid     ferry, motorway, **toll**, tunnel

however I don't seem able to make it working. Could you pls. clarify?

**Comment by boldtrn** [comment]
> I don't seem able to make it working. Could you pls. clarify?

This is not an open source feature at this point. Avoiding Tolls and adding path details for tolls has been included in the commercial offer of the GraphHopper Directions API. The API documentation of the open source project can be found [here](https://github.com/graphhopper/graphhopper/blob/master/docs/web/api-doc.md).

**Comment by karussell** [comment]
The reasoning behind this is that it is relative easy to implement in a "dirty" way (just another bit in the flags) but harder to do it clean without making the flags explode (see DataFlagEncoder and #1112)

**Comment by karussell** [comment]
This is now possible with #1776.
