### ISSUE TITLE
Wrong graph folder unnecessary creation

### ISSUE THREAD

**Issue by devemux86** [graphhopper/graphhopper#644]
When we call `graphHopper.load` with a wrong path that doesn't exist, the process informs us with an exception about that, but also creates unnecessarily the path.

That's inconvenient as we have to remove the unneeded created empty folder afterwards.
Can we skip the `GHDirectory.mkdirs` in case the graph loading has failed?

**Comment by karussell** [comment]
Sure, that is ugly.

**Comment by ammagamma** [comment]
https://github.com/graphhopper/graphhopper/pull/700

**Comment by karussell** [comment]
Should be fixed with #700

**Comment by karussell** [comment]
Found a way to fix this and keep backward compatibility: https://github.com/graphhopper/graphhopper/commit/0de10bfd2ba7bd33c7e9980a73ad00b66b7a6898

More complex than #700 :(. See #724 for discussion why this is still necessary.

**Comment by devemux86** [comment]
Nice! :+1: 
Also the needed removal of the `mkdirs` in `GHDirectory` constructor.
