### ISSUE TITLE
Conditional access intervals should recognize the full month or just the start for the end?

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#645]
If 'Aug 10-Dec' is used then currently all days in December do not lay inside this interval. Is this according to the wiki or do we need to fix this?

Example http://www.openstreetmap.org/way/44158212

**Comment by boldtrn** [comment]
As I understand it all days of Dec should be in this interval. For example if you have a conditional like: no@(Dec), I'd expect that all days of December are used.

**Comment by karussell** [comment]
Okay, then we need to fix this and use the last day of the month if at the end and the first day of a month if a start.

**Comment by boldtrn** [comment]
Mhm, this is implemented: https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/reader/osm/conditional/ParsedCalendar.java#L53

https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/reader/osm/conditional/DateRange.java#L56

This might be related to mixing one date that includes the day and another date that does not include the day. But I am not sure.

**Comment by karussell** [comment]
Thanks for pointing me there. I'll take over when I have time tomorrow or so :)

**Comment by karussell** [comment]
Strange, I cannot reproduce it. My problem I had in 'real world' is probably something else ... will investigate

**Comment by karussell** [comment]
Problem was just a very tiny one: https://github.com/graphhopper/graphhopper/commit/dedd6492afadc35441f6b8715feda903078b1447#diff-3366c19a3222e63106d98dbb75235addR132

**Comment by boldtrn** [comment]
Thanks for the update. But why in the ReverseMethod? This shouldn't be a reverse DateRange.

**Comment by karussell** [comment]
Sorry, it was a different interval which I tried: Aug 10-Jan. I edited this in the OSM data to test if it was blocking. See the new unit test

**Comment by boldtrn** [comment]
Ah ok, makes sense. Thanks for fixing :)
