### ISSUE TITLE
WEB UI support for alternative_route

### ISSUE THREAD

**Issue by ratrun** [graphhopper/graphhopper#660]
With the current master alternative route handling can ony be forced by manually adding of parameters to the URL. 
The avialiablity of the feture on the server side should be announced to the client side similar as the support of elevation. In case that the feature is available, it should be possibly to easily acrivate it via GUI elements. 
Some code from 1a67b6475376f7465909af9d83777fdd5c4cd2bb , which implements the feature on my master fork, may serve as input.

**Comment by carlos-mg89** [comment]
Just figured that it's possible to add a 'hint' with the required parameter:

`ghRequest.hints.put("ch.disable", true)`

So perhaps this issue could be closed, since it's possible to enable the alternative_route algorithm thanks to the hints array.

**Comment by karussell** [comment]
We have support for this in the new UI: https://github.com/graphhopper/graphhopper-maps
