### ISSUE TITLE
Download link in site is still pointing to version 0.5

### ISSUE THREAD

**Issue by HarelM** [graphhopper/graphhopper#663]
The following page had a link to a zip file of version 0.5.
https://graphhopper.com/blog/2016/02/08/releasing-graphhopper-0-6/
look for "or the zip package".
BTW, Thanks for adding my name to the contributors list :-)

**Comment by karussell** [comment]
Ouch - thanks for pointing this out!

**Comment by karussell** [comment]
These copy&paste errors will never stop ;) Fixed now!
