### ISSUE TITLE
On Actual Android Device Draging and Scrolling Crash 

### ISSUE THREAD

**Issue by chathura1** [graphhopper/graphhopper#671]
On real Android device running 5.1.1 scrolling map will cause app to crash.  However, onLongPress works with routing as expected.  I also noticed on AVD API 23 it scrolling works fine.  Also pressing zoom out causes app to crash on the device.

**Comment by devemux86** [comment]
GraphHopper uses [Mapsforge](https://github.com/mapsforge/mapsforge) in its Android sample for offline map rendering.

I tested GraphHopper sample on Android 5 and it works fine.
Can you provide a log of the exception to better understand what happens?

**Comment by karussell** [comment]
Closing here as it does not belong to GraphHopper

**Comment by chathura1** [comment]
I have no direct access to log file in logcat.  Let me send you screenshots as I can.

**Comment by chathura1** [comment]
@karussell 
Here is my locat for crash report::
03-02 10:34:34.101  1027  1057 I ActivityManager: Displayed com.graphhopper.android/.MainActivity: +1s123ms (total +52s647ms)

03-02 10:34:34.111  1027  1057 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{1fe8b388 u0 com.graphhopper.android/.MainActivity t354} time:170620

03-02 10:34:54.591  1027  1671 W InputDispatcher: channel 'ec0f62c com.graphhopper.android/com.graphhopper.android.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0xd

03-02 10:34:54.591  1027  1671 E InputDispatcher: channel 'ec0f62c com.graphhopper.android/com.graphhopper.android.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

03-02 10:34:54.591  1027  2414 W InputDispatcher: Attempted to unregister already unregistered input channel 'ec0f62c com.graphhopper.android/com.graphhopper.android.MainActivity (server)'

03-02 10:34:54.591  1027  2414 I WindowState: WIN DEATH: Window{ec0f62c u0 com.graphhopper.android/com.graphhopper.android.MainActivity}

03-02 10:34:54.601  1027  2430 W ActivityManager: Force removing ActivityRecord{1fe8b388 u0 com.graphhopper.android/.MainActivity t354}: app died, no saved state

03-02 10:34:56.021  1818  1818 W PackageManager: Failure retrieving resources for com.graphhopper.android: Resource ID #0x0

**Comment by chathura1** [comment]
@devemux86 
Here is better logcat report this happened when drag app or click on zoom button on LG Leon running Android 5.1.1:
03-02 11:20:50.191  1027  1057 I ActivityManager: Displayed com.graphhopper.android/.MainActivity: +613ms

03-02 11:20:50.191  1027  1057 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{86ab4d4 u0 com.graphhopper.android/.MainActivity t386} time:2946702

03-02 11:21:00.211  1027  2175 W ActivityManager: Force removing ActivityRecord{86ab4d4 u0 com.graphhopper.android/.MainActivity t386}: app died, no saved state

03-02 11:21:00.211  1027  1671 W InputDispatcher: channel '3402c370 com.graphhopper.android/com.graphhopper.android.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0xd

03-02 11:21:00.211  1027  1671 E InputDispatcher: channel '3402c370 com.graphhopper.android/com.graphhopper.android.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

03-02 11:21:00.221  1027  2126 W InputDispatcher: Attempted to unregister already unregistered input channel '3402c370 com.graphhopper.android/com.graphhopper.android.MainActivity (server)'

03-02 11:21:00.221  1027  2126 I WindowState: WIN DEATH: Window{3402c370 u0 com.graphhopper.android/com.graphhopper.android.MainActivity}

03-02 11:21:02.371  1027  1027 W NotificationService: Object died trying to hide notification android.app.ITransientNotification$Stub$Proxy@1116ce1b in package com.graphhopper.android

03-02 11:21:02.371  1027  1027 W NotificationService: Object died trying to show notification android.app.ITransientNotification$Stub$Proxy@3d642bb8 in package com.graphhopper.android

03-02 11:21:03.141  1818  1818 W PackageManager: Failure retrieving resources for com.graphhopper.android: Resource ID #0x0

Please help.

**Comment by devemux86** [comment]
*We should probably move the discussion in the forum.*

About the exceptions, I'm afraid they are not much enlightening as they seem the result of the actual problem.
Isn't there a more detailed stack trace, maybe without filters on the logcat?

**Comment by chathura1** [comment]
@devemux86 I am using ACRA as crash report on device. According to ACRA developers it does catch and email log reports of library level crashes.  The sample app crash due to library level crash.  I have no filters on logcat.  It is displaying all text available.   Why does this work fine in Emulator?

By the way, I am considering importing graphhoper to Eclipse project, do you have any instructions on importing it  (Not Android Studio)?

Thanks.

**Comment by chathura1** [comment]
Here is possible crash:
03-02 12:22:11.681 18968 18968 F libc    : Fatal signal 11 (SIGSEGV), code 2, fault addr 0xa16df000 in tid 18968 (hhopper.android)

03-02 12:22:11.681 18968 18968 I libc    : Suppressing debuggerd output because prctl(PR_GET_DUMPABLE)==0

attached is complete logcat without filtering.
[Log_2016-03-02_12-26-29.txt](https://github.com/graphhopper/graphhopper/files/155588/Log_2016-03-02_12-26-29.txt)
