### ISSUE TITLE
Slow loading of resources from Tomcat

### ISSUE THREAD

**Issue by gerbsen** [graphhopper/graphhopper#672]
Hey there,
I've installed Graphhopper in Eclipse and started the integrated Tomcat (8). If I go localhost:8080 it takes over 20sec till I receive the first files:
<img width="1277" alt="screenshot 2016-03-02 12 43 13" src="https://cloud.githubusercontent.com/assets/1186245/13459533/990401d4-e074-11e5-90da-51f83a1bec9c.png">
Any idea about the cause?
Cheers, Daniel

**Comment by karussell** [comment]
Would you mind to discuss this in our forum? Tomcat is not something we support out of the box so this is not a 'bug' or an issue

**Comment by gerbsen** [comment]
Ah, interesting. This is new to me. I startet to read through the developers documentation, and it seemed to me that **_the tomcat way_** is the way to go (as also in lots of other projects I've worked in recent years). Since I want to debug me through the code and not use maven on the command line. I just found the GHServer.java class which I can run/debug with `config="/path/to/graphhopper/config.properties" graph.location="/path/to/graphhopper/graph/" osmreader.osm="/path/to/graphhopper/berlin-latest.osm.pbf"` parameter. Awesome!

**Comment by karussell** [comment]
Yes, please look into this: https://github.com/graphhopper/graphhopper/blob/master/docs/web/quickstart.md or this: https://github.com/graphhopper/graphhopper/blob/master/docs/core/quickstart-from-source.md
