### ISSUE TITLE
weird route result

### ISSUE THREAD

**Issue by zhiqiangZHAO** [graphhopper/graphhopper#673]
https://graphhopper.com/maps/?point=39.749405%2C-104.997818&point=39.747693%2C-104.995667&locale=en-US&vehicle=car&weighting=fastest&elevation=true&layer=Omniscale

I think the root cause is 16th street is marked as "motor_vehicle=no".
http://www.openstreetmap.org/way/16987212#map=16/39.7453/-104.9924&layers=ND

**Comment by karussell** [comment]
Thanks - seems indeed like a bug!

It is interesting as edges with restricted access for a vehicle should not get picked up in the look up index. If they are then picked up "somehow" then behaviour is partly explainable as some virtual edges with an infinity/high (?) weight are introduced and the algorithm gets you off the road as fast as possible.

**Comment by karussell** [comment]
Hmmh, it looks now this is working as expected for `car`, which is a bit ugly as we do not find out the real reason.

And at the first view I thought that `bike` has still this problem as `bicycle=no` BUT for bike we can get just off the bike making those edges possible.

Do you had other such examples for this?

**Comment by karussell** [comment]
Closing for now here
