### ISSUE TITLE
Bad routing result, turn restriction ignored

### ISSUE THREAD

**Issue by serafinwoschek** [graphhopper/graphhopper#675]
On road crossing turn restriction from "Kołłątaja" to "Kościuszki" is ignored. The turn is allowed only for public transport, not allowed for other vehicles. 

[https://graphhopper.com/maps/?point=51.102976%2C17.03692&point=51.101602%2C17.038465&locale=en-US&vehicle=car&weighting=fastest&elevation=true&layer=Omniscale](url)

**Comment by karussell** [comment]
Currently turn restrictions are not enabled for GH Maps using the "speed mode" and only possible with the flexibility mode which is not yet production grade, but we are working on both sides.

**Comment by devemux86** [comment]
It's worth mentioning that from my reports the turn restrictions with flexibility mode are working quite well. :+1: 

The most notable is the lack of turn restriction with multiple ways as via member (see #446).
