### ISSUE TITLE
CamelCase vs. under_score notation

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#682]
We should allow both or migrate to just under_score notation. E.g. prepare.ch_weightings vs. prepare.ch_weightings or prepare.minNetworkSize vs. prepare.min_network_size

Also check CH properties for better naming in general:
 * `routing.ch.heading.force`  instead of `force_heading_ch`
 * `prepare.ch.weightings` instead of `prepare.chWeightings`

Others: 

 * a bit ugly: `alternative_route.max_paths` vs. `algorithm=alternativeRoute` 
 * make all routing options with or without a `routing.` prefix. See `alternative_route` vs. `routing.flexMode.xy`
 * what about the names in storableproperties
 * names in measurement properties result
 * translation keys

**Comment by devemux86** [comment]
In long term it'd be probably better to have only one notation.
But what about API current compatibility?

**Comment by karussell** [comment]
At the moment I tend to convert all get and put calls with camelCase to under_score and rewrite all put requests and the config to use under_score. This way we always use one notation internally, but keep compatibility.

**Comment by karussell** [comment]
I'll soon implement this where all of the old settings should work as before (except maybe rarely used like force_heading_ch) or other options introduced in 0.7-SNAPSHOT

The plan is to

 * switch all properties to under score
 * use parameters without `routing.`

for all the areas mentioned above.

What do you think?

**Comment by devemux86** [comment]
I think it's a good plan. :+1:

**Comment by karussell** [comment]
Please have a look into #719
