### ISSUE TITLE
Wrong bounds?

### ISSUE THREAD

**Issue by savurself11** [graphhopper/graphhopper#684]
My bounds information is like this
bounds minlat='34.0662408634219' minlon='-118.736715316772' maxlat='34.0731374116421' maxlon='-118.73122215271' origin='OpenStreetMap server'

but graphhopper says,
 Cannot create location index when graph has invalid bounds: -118.7343501,-118.7343501,34.07234,34.07234

what did I miss?

Thanks in advanced.

**Comment by karussell** [comment]
Your bounds are too small I think where no road or just a single junction is contained. Would you please use our forum for further discussion?
