### ISSUE TITLE
Unable to resove parent POM: org.sonatype.oss link is down

### ISSUE THREAD

**Issue by mmhorii** [graphhopper/graphhopper#687]
Hello, when I go to the link https://repo.maven.apache.org/maven2/org/sonatype/oss, I get a "404 Not Found" message. This is preventing installation using Maven.

**Comment by karussell** [comment]
That is indeed strange. There should be the "oss-parent" project, which we refer to in the root pom.xml

**Comment by karussell** [comment]
What exactly was your command? As you cannot access the folder but the content is possible
https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom

And why are you using apache.org host?

**Comment by mmhorii** [comment]
I'm on a Windows 7 PC, and tried to run "mvn install" on the command line. I got the following error:

[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.graphhopper:graphhopper-parent:0.7-SNAPSHOT: Could not transfer artifact org.sonatype.oss:oss-parent:pom:9 from/to central (https://repo.maven.apache.org/maven2): This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server and 'parent.relativePath' points at wrong local POM @ line 16, column 13

I then tried to go to https://repo.maven.apache.org/maven2/org/sontatype/oss from a web browser, but got a "404 Not Found" error.

**Comment by karussell** [comment]
Can you just try again? And please use `./graphhopper.sh clean` and `./graphhopper.sh build` instead

**Comment by karussell** [comment]
Building locally and on travis succeeded so this must be a local issue. Let us continue discussion on our forum.
