### ISSUE TITLE
bicycle=dismount is not evaluated

### ISSUE THREAD

**Issue by polarbearing** [graphhopper/graphhopper#695]
While graphhopper knows the idea of pushing a bike on ```path, footway, pedestrian and steps```, the explicit access tag ```bicycle=dismount``` (used about [40000 times](http://taginfo.openstreetmap.org/tags/bicycle=dismount)) is not evaluated. If found on any highway, it should create such [pushing section](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/routing/util/BikeFlagEncoder.java#L54). 

E.g. I have a ```highway=secondary``` here which is for a long time ```access=no, foot=yes, bicycle=dismount```.

**Comment by karussell** [comment]
Thanks that is indeed missing!

Regarding your example if access=no and foot=yes is already set GraphHopper should already tell you about getting off the bike. Or do you have a example link?

**Comment by polarbearing** [comment]
See [here](https://graphhopper.com/maps/?point=52.457788%2C13.625622&point=52.457003%2C13.62545&locale=en&vehicle=bike&weighting=fastest&elevation=true&layer=Omniscale) and switch between bike, car and foot.

**Comment by karussell** [comment]
Ah, okay [this way](http://www.openstreetmap.org/way/43167434). Maybe the current implementation would use 'get off the bike' if there is no access=no and just a foot:yes. We need to check this and make it working.

**Comment by polarbearing** [comment]
Yes, I should have given you the way number. 

The evaluation order in OSM is typically that first access=no forbids everything, then individual permissions are opened case by case. Thus you do not need a long list of *=no tags. 
Thanks.

**Comment by polarbearing** [comment]
Just for the records, I just removed a bunch of unnecessary turn restrictions from a newbie a the northern end of the road segment. But it seems the issue is still within the road, if I get the start/stop point [narrower only on the affected segment](https://graphhopper.com/maps/?point=52.457435%2C13.625547&point=52.457055%2C13.625482&locale=en&vehicle=foot&weighting=fastest&elevation=true&layer=Omniscale), I get the same results.

**Comment by ratrun** [comment]
I think that this issue can be closed, it should be solved for a while.
