### ISSUE TITLE
Provide a way to have one or two different weighting limits for routing algorithms.

### ISSUE THREAD

**Issue by alFReD-NSH** [graphhopper/graphhopper#699]
An example use case for me is I want to find the best route with a given custom weighting(not shortest/fastest), that are under 5 minutes(using fastest weighting) and 5 kilometers(using shortest weighting). Right now the only way to implement this easily is to modify Graphhopper.

**Comment by karussell** [comment]
I do not understand your requirements. Do you have an example?

**Comment by alFReD-NSH** [comment]
Given that I have a custom weighting, I want to find a route that is for example no more than 5 kilometers(depending on the request) to the destination

**Comment by karussell** [comment]
But what is the use case for this? Why not e.g. request a few **good** alternatives and let the user decide instead of such artificial limits which could result in arbitrary bad routes.

**Comment by alFReD-NSH** [comment]
Not looking for alternative routes, this is based on the users requirements. For example, user has a limited amount of fuel and wants to get to the fuel station. Although a route might be faster, it might end up using more fuel.  Another example would be that the user wants to get to the destination in one hour, the user wants the route that costs the least.

**Comment by karussell** [comment]
> Although a route might be faster, it might end up using more fuel. 

Then you would need a fuel efficient route and could handle this appropriately in the weighting. 

> Another example would be that the user wants to get to the destination in one hour, the user wants the route that costs the least.

Here you need just a mixture of shortest and fastest.

In both situations you would find the (theoretically) best route but with a limit this would not be the case.

I still do not see a reason to put a limit like this in the core, as you could theoretically handle this in customer algorithms.

**Comment by alFReD-NSH** [comment]
In Malaysia, fastest, cheapest, shortest are not really equal thanks to the traffic and lot's of highways with tolls. Sometimes the users need something in between.

Anyway, I do understand that you wouldn't want to include this in the core. The problem I'm having implementing the algorithm myself is that, I can't just override one or two of the algorithms methods, since a lot of things that the algorithms use are either package private or protected.

**Comment by karussell** [comment]
> Sometimes the users need something in between.

But that is exactly the reason why the weighting is so easy to customize. Just overload createWeighting and you are done.

I'll close here and we should move the discussion to the forum if there are further questions.
