### ISSUE TITLE
Make GraphHopper compiling and running on JDK9

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#701]
Out of couriosity I tried JDK9 and got already lots of success :)
- [x] runs out of the box in JDK9 with jdk8 compiled jars
- [x] Maven compiles with [a small workaround](http://stackoverflow.com/a/36605759/194609) in the parent pom.xml. The workaround won't be necessary for a new maven release I think
- [x] most tests pass
- [x] except the memory mapping tests, which return 'RuntimeException: unable to unmap the mapped buffer'. [Here](http://mail.openjdk.java.net/pipermail/core-libs-dev/2015-September/035055.html) is some discussion about this.

**Comment by mprins** [comment]
You could specify two profiles, one for jdk8 and one for jdk9 and as part of the profile set up includes/excludes for the surefire an failsafe tests. I would not recommend doing it from the commandline.

something like:

```xml
<profiles>
  <profile>
    <id>jdk8</id>
    <activation>
      <activeByDefault>false</activeByDefault>
      <jdk>1.8</jdk>
    </activation>
    <properties />
    <build>
      <plugins>
        <plugin>
          <artifactId>maven-failsafe-plugin</artifactId>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
        </plugin>
      </plugins>
    </build>
  </profile>
  <profile>
    <id>jdk9</id>
    <activation>
      <activeByDefault>false</activeByDefault>
      <jdk>1.9</jdk>
    </activation>
    <properties />
    <build>
      <plugins>
        <plugin>
          <artifactId>maven-failsafe-plugin</artifactId>
          <configuration>
            <systemPropertyVariables />
          </configuration>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <configuration>
           <!-- this uses a method described here: 
                  https://issues.apache.org/jira/browse/SUREFIRE-131 to exclude a singe 
                  test method, ofcourse any config can ce used here -->
            <test>!SomeClassTest#methodtoskipTest</test>
          </configuration>
        </plugin>
      </plugins>
    </build>
  </profile>
</profiles>
```
Will activate the relevant config based on the JDK running the build.

**Comment by karussell** [comment]
Thanks this sounds good. Do you know of an annotation like `@IgnoreIfEnvVarIsXY`?

Also I'll have a look that we can make it running without any tweaks e.g. automated JDK9 detection and disabling the cleaner call (not sure if this is good though).

**Comment by mprins** [comment]
Not sure; you could add an [Assumption](http://junit.sourceforge.net/javadoc/index.html?org/junit/Assume.html) at the start of the failing test method; if the assumption is not met it will ignore the rest of the test.

eg. `assumeTrue(System.getProperty("java.version") != "1.9");`

**Comment by karussell** [comment]
Got the memory mapping finally working with some JDK9 configs, see here #852

**Comment by karussell** [comment]
It looks like something was changed recently which broke our approach: https://travis-ci.org/graphhopper/graphhopper/jobs/190867582

**Comment by karussell** [comment]
Hmmh, the issue [JDK-8171377](https://bugs.openjdk.java.net/browse/JDK-8171377) *Add sun.misc.Unsafe::invokeCleaner*
is related but it is only available in b150

**Comment by karussell** [comment]
It looks like there is another issue [JDK-8171452](https://bugs.openjdk.java.net/browse/JDK-8171452) ( linux io_util_md: Operation not supported exception after [JDK-8168628](https://bugs.openjdk.java.net/browse/JDK-8168628)), the full stack trace:
```
Caused by: java.io.IOException: Operation not supported
	at java.base/sun.nio.ch.FileDispatcherImpl.allocate0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.allocate(FileDispatcherImpl.java:80)
	at java.base/sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:918)
	at com.graphhopper.storage.MMapDataAccess.newByteBuffer(MMapDataAccess.java:160)
```
(I get this even without any clean hack before)

**Comment by karussell** [comment]
Ok, with jdk-9-ea+152 everything seems to work with a small fix that I'll commit shortly.

**Comment by karussell** [comment]
The part that should work is now working as the latest jdk9 (thanks @hotice for the up-to-date apt installer!) is also deployed on travis

**Comment by karussell** [comment]
Still some reflection (hack?) in some test utility is failing :(

```
testBlockAccessViaPoint(com.graphhopper.http.ChangeGraphServletIT)  Time elapsed: 1.634 sec  <<< ERROR!
java.lang.ExceptionInInitializerError
	at com.graphhopper.http.ChangeGraphServletIT.setUp(ChangeGraphServletIT.java:50)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @75f65e45
	at com.graphhopper.http.ChangeGraphServletIT.setUp(ChangeGraphServletIT.java:50)
```

**Comment by karussell** [comment]
We could remove the old `--add-exports` option as the new code does not need this hack. 

Hmmh, the newly added option `--add-opens` to make the reflection stuff working does not seem to work....

btw: this is how I'm calling jdk9 locally:
```
export JAVA_HOME=/path/to/jdk-9/; mvn -P jdk9 clean install
```

**Comment by karussell** [comment]
Got jdk8+9 builds both green again :) https://github.com/graphhopper/graphhopper/commit/768c036ebfcbc61d6e7dc5a9f2ed207605aa1e26
