### ISSUE TITLE
Switch to Gradle?

### ISSUE THREAD

**Issue by IsNull** [graphhopper/graphhopper#706]
I've seen that in the android sub project, Gradle is already in place. So why not switch the rest of the project to Gradle as well?
- It would largely reduce the build (pom.xml) boilerplate
- Custom shell scripts such as `graphhopper.sh` can be replaced by custom Gradle tasks, running on all platforms.
- Integration into the web project (invoking npm / bower) would also be no problem. 

What are your thoughts on this? Is this already planned or are there reasons why you'd rather not switch to Gradle?

Related: http://gradle.org/migrating-a-maven-build-to-gradle/

**Comment by karussell** [comment]
Thanks for this, sounds interesting. Something like this is not yet planned and also quite a bit work. There are mainly historic reasons why we did not yet consider it but also because I do not feel huge pain with maven. Do you know how good the IDE integration with gradle is? Obviously IntelliJ has good integration but NetBeans (critical for me ;)) and Eclipse? And what about releasing to maven central?

**Comment by devemux86** [comment]
I'd vote for such a transition. :+1:

AFAIK Gradle Inc. is a member of the Eclipse Foundation and actually they created the official [Gradle plugin](http://gradle.org/press-release/eclipse-gradle/) which is now part of Eclipse releases.

About Netbeans you can see [here](https://netbeans.org/features/java/build-tools.html) for details.

**Comment by karussell** [comment]
Still I'm hesitating if it is worth the effort. Are multiple and parent projects supported?
BTW: ElasticSearch has done the transition mainly due to large pom file and plugin problems I think, and it is documented here: https://github.com/elastic/elasticsearch/issues/13930 Maybe we should ask them regarding experiences, effort and satisfaction?

**Comment by devemux86** [comment]
>Are multiple and parent projects supported?

Yes, for example in Mapsforge we maintain exactly such a structure of Android and Java modules.

**Comment by IsNull** [comment]
@karussell 

I've switched recently a lot of projects, both small and big from Maven to Gradle.

You can see Gradle as a super set of Maven, there is nothing you can't do with Gradle what Maven can. Gradle supports a wide range of publish/release endpoints, including maven central and bintray.

As an example, I have a project which consists of multiple java sub projects and a web project (npm & bower). Gradle is used to build a fat jar, thin jar & a pom.xml for publish, the thin jar & pom.xml is then deployed to bintray. Have a look how a Gradle scripts looks like which does all that: [build.gradle](https://github.com/ElderByte-/Warden/blob/master/warden-server/build.gradle)

Gradle is also very developer friendly because it has a concept of a Gradle wrapper which supports running Gradle build without anything installed previously. Similar what you have with your shell script comes with maven out of the box. This wrapper will basically check if Gradle is present and download it locally if not. It will also ensure the exact version you specified is present. This leads to highly reproducible builds.

>Are multiple and parent projects supported?

Sure :) Would not be much of an improvement if not, wouldn't it^^

I can give this a shot if you're interested. Since we can invoke scripts with Gradle, we can do a slow transition by just invoking your shell scripts until they have been rewritten in Gradle tasks.

**Comment by karussell** [comment]
Okay. But again: the effort seems to be big as I would make this either for all of our projects or none :)
https://github.com/graphhopper/ (ping @oblonski)

**Comment by IsNull** [comment]
Besides technical reasons some more arguments :)

>But again: the effort seems to be big as I would make this either for all of our projects or none

Well currently you have a mix inside one repository (Gradle & Maven). IMHO it would be more consistent to have only one Java build system inside one repository. 😄 

If the transition to Gradle is successful and you learn the benefits from it, the wish to convert the other projects comes automatically. Since Gradle uses Maven dependencies under the hood, there is no technical limitation in consuming Maven Projects from Gradle. 

I have hesitated for the same reasons as you do: Maven once solved the big pain of manually managing dependencies and I loved it for this. And it still works. But times are changing and in our world of mixed languages (hello web apps), fully automated builds, automated deployments and what not, Gradle has proven to be easier to handle. 

Last but not least, a lot of big projects migrated to Gradle and it is also becoming the industry standard in big Software Development companies (where I once used to work).

>Also I would need to test this with NetBeans as there seems to be only a community contributed plugin where I have made bad experiences with in the past.

I can't say much about NetBeans. But Gradle integration is more or less invoking `./gradlew build` in your project root. This is also what the CI such as Travis will do. There is not much more to it, similar to `maven clean package`

**Comment by karussell** [comment]
> But Gradle integration is more or less invoking ./gradlew build in your project root. 

If that would be the case with the netbeans integration then it would be a lot slower compared to maven.

But besides all arguments: you do not have convince me. I was trying gradle in 2012 to see if it is a viable maven alternative for graphhopper as I liked it a lot more. But the IDE integration was not ready at that time and also some years later. Now I have to try it again ... if I'd have time ;)

**Comment by IsNull** [comment]
Gradle has a small start up performance hit due to its JVM roots. It depends on your system (SSD) if you notice it or not.

Once running, a build is usually faster than Maven because Gradle detects artefacts which have not changed and does not recompile them.

Anyway, if you enable the [Gradle Daemon](https://docs.gradle.org/current/userguide/gradle_daemon.html) on your system performance is your last problem. :)

Maybe give Gradle a try in a small project to test it out and its Netbeans support. 4 years is a long time and Gradle has matured quite a bit since u last tried it. (I use it for about a year now, previously was on Maven)
