### ISSUE TITLE
DijkstraOneToMany cache broken after calcPath(from, to) where from == to

### ISSUE THREAD

**Issue by IsNull** [graphhopper/graphhopper#707]
While working on the distance matrix, I stumbled over a little bug in
DijkstraOneToMany. If you invoke `DijkstraOneToMany.calcPath(from, to)` and from / to is the same node, all future calls to `calcPath(from, to)` will yield a zero path/distance.

This is obviously a rare case, since it does not really make sense to query for a path to itself, but for the sake of a clean framework I think such edge cases should be handled cleanly anyway.

See the pull request #708 which shows the issue.

**Comment by karussell** [comment]
Fixed via #708
