### ISSUE TITLE
Handle sidewalk=none and sidewalk=separate similar to sidewalk=no

### ISSUE THREAD

**Issue by scaidermern** [graphhopper/graphhopper#712]
*sidewalk=none* (currently used 250k times according to [taginfo](https://taginfo.openstreetmap.org/keys/sidewalk#values)) is a synonym for *sidewalk=no* (currently used 115k times). Likewise, *sidewalk=separate* (currently used 12k times) indicates that there is a separately mapped sidewalk, thus the way with a *sidewalk=separate* tag should also get a low priority similar to the values *no* and *none*.

Related issues: #355 #463

**Comment by karussell** [comment]
Thanks for reporting! Please review my fix!
