### ISSUE TITLE
Fail to load ghz data into hopper

### ISSUE THREAD

**Issue by kevincyh** [graphhopper/graphhopper#716]
Currently i working on Android Graphhopper 0.6.0.
I fail to load the data into graph hopper.
http://folk.ntnu.no/weiwe/junjunguo/pocketmaps/maps/  - asia map
^^ Gives me an error stating the edges 13 required but my is 12.

And also the .osm data using wget to download. Any tips on how i can get it loaded into the phone.

**Comment by karussell** [comment]
Please use the forum for questions!
