### ISSUE TITLE
Flexible Mode not allowed for Non-Ch

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#717]
Something I found is that if we do not enable CH. We do not allow the flexible mode. 

So the Server has CH disabled and you query a flexible routing. You get an exception. I have CH disabled for my local development environment but turned on when hosting my application. Therefore I have to check if i query the local environment or the remote server.

I vote for not being that strict in that case. What do you think?

**Comment by karussell** [comment]
You mean you have CH disabled and use 'force flex mode'=true then you get an exception? Indeed this should not be the case and work exactly the same like if CH is disabled and without the parameter.

**Comment by boldtrn** [comment]
Essentially I locally changed that method in the CHDecorator:
```
    public final boolean isForcingFlexibleModeAllowed()
    {
        return forcingFlexibleModeAllowed || !isEnabled();
    }
```

From a logical standpoint. It makes sense that forcing the flexible mode is allowed when ch is disabled, even though it is not needed in this case.

**Comment by boldtrn** [comment]
@karussell Sorry, haven't seen your reply. Yes. We do not check it in the CHDecorator Constructor:

https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/routing/ch/CHAlgoFactoryDecorator.java#L103

**Comment by karussell** [comment]
Okay. I stumbled over similar issues in my local setup with this init code when I tried other stuff. So I'll have a look if I already fixed it there. I have also renamed this setting to `routing.ch.disable` (and `routing.ch.disabling_allowed` in the config) making it better aligned when more algos come into the game.

**Comment by karussell** [comment]
Let me know if this now works for you!

**Comment by boldtrn** [comment]
Thanks @karussell. I will let you know if there is an issue.
