### ISSUE TITLE
Apache license author

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#720]
Copyright of the Apache license is directed towards the individual 'Peter Karich' and we move this here to the company 'GraphHopper GmbH'. New (and old) contributors agree(d) to the [new CLA](https://discuss.graphhopper.com/t/graphhopper-contribution-license-agreement-cla/486)

This effects all GraphHopper projects including jsprit (see the [required license change issue here](https://github.com/graphhopper/jsprit/issues/216)) and map-matching etc.

**Comment by devemux86** [comment]
Two first words of title were a bit scary until the full message is read! :smile:

**Comment by karussell** [comment]
Ups & sorry, will rephrase!!

**Comment by karussell** [comment]
This is done here: https://github.com/graphhopper/graphhopper/commit/c6c18ce28ae1722bfb6338d517ca3093e205d1ac
