### ISSUE TITLE
Make turn costs usage possible via disabling CH

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#725]
If we do CH preparation it would be nice to disable it at runtime and use edge based traversal with the correct turn costs calculation. That is easily possible now but currently the wrong traversal mode is used which we need to fix.

**Comment by devemux86** [comment]
Interesting approach. I suppose it can be used also in other cases where CH does not have yet a flexibility feature?

**Comment by karussell** [comment]
Yes, exactly. See the new web API doc ... this applies to the Java API too
