### ISSUE TITLE
Make EncodingManager final and allow custom FlagEncoder creation

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#726]
Currently adding a new encoder requires one to set the EncodingManager with the FlagEncoder already initialized making it harder to init from string. Instead we should set the EncodingManager once and call the registerFlagEncoder later on where an overwritable method from EncodingManager could be called.

**Comment by devemux86** [comment]
Why this sudden turn in GH on cutting its extend capabilities, is it a management decision?

First was the `GraphHopper` class, noq `EncodingManager` will become final.. :disappointed:

**Comment by karussell** [comment]
There is no management decision or something different then before.

> First was the GraphHopper class, now EncodingManager will become final.. :disappointed: 

Are you referencing #724 ?

I do not have the intend to make GH less flexible and also the 'final' is again a miswritten word. I didn't mean to make the class final but to make the reference final so we can have only one EncodingManager instance. In fact with this issue here I want to make it **more** flexible as subclassing then will allow creating custom flag encoders without writing inside the EncodingManager (see latest hikeFlagEncoder change where this was necessary)

**Comment by devemux86** [comment]
>I do not have the intention to make GH less flexible and also the 'final' is again a miswritten word. I didn't mean to make the class final but to make the reference final so we can have only one EncodingManager instance.

Ok, sorry for the misunderstanding..

But how we'll use a custom `EncodingManager` if the `GraphHopper.setEncodingManager` will be removed (as the reference becomes final) or I'm missing the concept?

**Comment by karussell** [comment]
Not sure :)
I just want to make it somehow working that we initialize the encoding manager once and the creation itself should be customizable, so that we do not need null checks or can just use the existing manager when we call just `load` without import

> Ok, sorry for the misunderstanding..

No problem, I'll take more time with my issue description incl. example.

**Comment by devemux86** [comment]
To put an example in the discussion, a useful override is `EncodingManager.applyWayTags`, where we can intercept and perform custom tag processing (like in `OsmReader`).

**Comment by karussell** [comment]
yes and I want a new overrideable `creatFlagEncoder` factory method

**Comment by karussell** [comment]
I tried to move the registering of the FlagEncoders into a separate `init` method but this requires lots of changes from the calling side, especially in the tests. As one either needs to handle the EncodingManager statefull (i.e. when `init` is called inside GraphHopperStorage.load/create) or one needs to call init explicitely somewhere.

A less invasive change would be to pass a FlagEncoderFactory to the EncodingManager and implement the current behaviour as default:

```java
interface FlagEncoderFactory {
    FlagEncoder createFlagEncoder( String name, PMap configuration )
}
```

**Comment by karussell** [comment]
Please review this change. Already in master branch, but we can revert this at any later time or replace with a different solution of course.

**Comment by devemux86** [comment]
Started testing it, so far things look good! :+1:
