### ISSUE TITLE
JSON output should contain snapped points for start, destination and via points

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#727]
Currently the snapped points are only accessible via the instructions special "via point" sign which makes using the API a bit ugly. A simple array containing all snapped points would be nice e.g. `points_snapped` or `snapped_points` or just `points`?

**Comment by oblonski** [comment]
I like `snapped_points` or `network_points` to differentiate them from input coordinates, i.e. `point`.

**Comment by karussell** [comment]
Ok, also `points` is already used for the output geometry. Another option would be `input_points` or `waypoints`? `waypoints` would be align to the `wpt` of the GPX [here](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/util/InstructionList.java#L222)

**Comment by oblonski** [comment]
`snapped_points` or `waypoints` are fine. `snapped_points` sounds slightly clearer for this purpose to me.

**Comment by karussell** [comment]
The term `snapped` makes it more clear but the underscore makes it very similar to `points` (which should be renamed to `geometry` -> see #437). But maybe for now `snapped_waypoints` could work?

**Comment by karussell** [comment]
Merged into master.

**Comment by boldtrn** [comment]
@karussell Great news, thanks! Just a minor comment: Why do we return each snapped point as an array instead of an object? In my opinion it would be better if each snapped point would be returned as Json Object with lat, lng, height props.

**Comment by karussell** [comment]
We already return locations as arrays in `points` if `encoded_points=false`. Also GeoJSON is similar and it saves a few characters.

**Comment by boldtrn** [comment]
@karussell Yes sorry, you are right. I was probably too fast with that assumption.

**Comment by karussell** [comment]
As writing a good API is nearly impossible I always appreciate all discussion and hints :)

**Comment by boldtrn** [comment]
Something we should consider is the handling of roundtrips. For roundtrips we should add snapped_points per path.

**Comment by karussell** [comment]
The meaning of both is slightly different, not sure if this matters at the end. For normal paths with via points (and also for alternative points?) we always have just snapped points taken from the input (so always the same), whereas for the round trip we would output snapped points of calculated points.

The use case I had in mind was that consuming clients are able to calculate additional time taken from the snapped points to the 'real points'. The use case of the snapped points for the roundtrip is that you want to be able to change the path afterwards with a normal via path - is that correct? The advantage of this would be that then snapped points would be always identical to the instruction its points with sign=VIA

**Comment by boldtrn** [comment]
@karussell Sorry for my belated reply.

> The use case of the snapped points for the roundtrip is that you want to be able to change the path afterwards with a normal via path - is that correct?

Yes that is correct. I think it won't hurt to add it per path. For alternative paths we probably have some duplicated information. But I think this is not too bad.

**Comment by karussell** [comment]
Should we return an encoded string for `snapped_waypoints` if `encoded_points=true`?

**Comment by boldtrn** [comment]
@karussell It would be consistent and would save traffic. On the other hand it will be harder to debug and usually there are not that many snapped points. The size of a snapped waypoint would be about 25 bytes. Even if we have 100 snapped waypoints, that would be about 2kb. A response of a route from Berlin to Munich is 28.8 kb (car) and 158 kb (bicycle). So I guess for most use cases encoding and decoding would be an overhead. But for some, it will will make sense.

BTW: I just saw that we don't GZIP the response. But that is probably a different discussion - and probably there is a discussion about that somewhere, but I couldn't find it.

**Comment by karussell** [comment]
Ok, I'll keep it for now. The encoding makes everything a bit harder and also one cannot easily write a swagger spec for this :/

BTW: Gzipping should be done due to the `GzipHandler`. There is no longer a gzip servlet.

**Comment by boldtrn** [comment]
> Gzipping should be done due to the GzipHandler

If I request a route from GraphHopper Maps the response is not gziped. Interestingly Kurviger gzips the result. But that can have other reasons.

**Comment by karussell** [comment]
Thanks - will have a look & opened this here instead: https://github.com/graphhopper/directions-api/issues/28

**Comment by karussell** [comment]
> Ok, I'll keep it for now. The encoding makes everything a bit harder and also one cannot easily write a swagger spec for this :/

Have to contradict myself: will make this dependent on the `calc_points` parameter to make it more consistent. I know we do not have many things consistent but we should still strive for less inconsistency

**Comment by boldtrn** [comment]
We should also encode the snapped waypoint in JS. 

I think adding this to the GHRequest.js should be enough:

```
var tmpSnappedPoints = graphhopperTools.decodePath(path.snapped_waypoints, that.hasElevation());
path.snapped_waypoints = tmpSnappedPoints;
```

**Comment by karussell** [comment]
:+1: Thanks! Never thought that such a simple feature results in so many considerations one has to make ;)
