### ISSUE TITLE
Grey box on map

### ISSUE THREAD

**Issue by despugin** [graphhopper/graphhopper#731]
Hi,

I really like the https://graphhopper.com/maps/.
Just one small issue: 

When zoomed out to the maximum on the website there es a grey box line around the continents. This doesn't look very nice in my browser. Maybe it would be nicer to limit the borders so one cannot zoom out further than to see all continents only once. Who needs four Worlds next to each other....?

best regards
desputin

**Comment by karussell** [comment]
Should be fixed now - thanks @highsource !

**Comment by despugin** [comment]
Hi Thanks!
But it seems that the grey box is still there at the present...

**Comment by karussell** [comment]
Not yet deployed on GraphHopper Maps ...

**Comment by karussell** [comment]
is now deployed, please refresh. the grey box is still there but not that obvious due to the lower maximum zoom level.

**Comment by devemux86** [comment]
If we start scrolling the map left or right, we loose the box, right?

**Comment by despugin** [comment]
Thanks works! Looks fine!!

**Comment by karussell** [comment]
> If we start scrolling the map left or right, we lose the box, right?

What do you mean?

They grey box is just a hint where the area of routing information is, but it is just a hint.

**Comment by devemux86** [comment]
I mean when we scroll the map left or right by one or more worlds, then we don't have the hint anymore, until we scroll back to original world.

BTW since the hint covers the whole earth, what's its purpose?

**Comment by karussell** [comment]
> I mean when we scroll the map left or right by one or more worlds, 
> then we don't have the hint anymore, until we scroll back to first world.

Yes. 

> BTW since the hint covers the whole earth, what's its purpose?

For the world wide instance this does probably not make much sense, yes. Probably we could detect those cases and just disable the grey box but for me this is fine as it is now.
