### ISSUE TITLE
Using '.' in url parameters

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#732]
I am not sure if this is actually an issue. But at least we should discuss it.

Using e.G. `ch.disable` as a key suggests that in e.G. JSON there is an object `ch` with key `disable`. Maybe we should think about converting the `.`to `_`?

**Comment by karussell** [comment]
This should be properly handled from us (I hope :)). The intention behind this is exactly this: to create an object `ch` with several keys. E.g. in the config we have `routing.xy=1` and `routing.ab=2`, then in a later json config this becomes `routing: {xy=1, ab=2}`

**Comment by boldtrn** [comment]
Ok, then it's fine. I just got an js exception because of that and thought it might be worthwhile to discuss it.

**Comment by karussell** [comment]
Does this exception occur also in our web module and what exactly went wrong?

**Comment by boldtrn** [comment]
No, otherwise I'd reported it. I use a library that expects that json objects (like api params) don't contain  characters like `.`.
