### ISSUE TITLE
Maven badge

### ISSUE THREAD

**Issue by devemux86** [graphhopper/graphhopper#737]
It would be convenient to have a Maven badge on main page (besides Travis), so to know easily what is the last version on Maven central.

I [added](https://github.com/mapsforge/mapsforge/commit/89f440a7fa3f8187d202d42b69a5509726c9039e) it recently in Mapsforge, see below the declaration for GraphHopper:

[![Maven Central](https://maven-badges.herokuapp.com/maven-central/com.graphhopper/graphhopper/badge.svg)](https://maven-badges.herokuapp.com/maven-central/com.graphhopper/graphhopper)

``` groovy
[![Maven Central](https://maven-badges.herokuapp.com/maven-central/com.graphhopper/graphhopper/badge.svg)](https://maven-badges.herokuapp.com/maven-central/com.graphhopper/graphhopper)
```

**Comment by karussell** [comment]
Hmmh, not sure if I like this, as currently it should still show 0.6.0 as stable release

**Comment by devemux86** [comment]
Sorry, not following here. In Maven there is currently the GH 0.7-RC2.
Do you mean showing a specific branch?

**Comment by karussell** [comment]
I just meant that a release candidate is not considered 'stable' for me and I would prefer that people still use 0.6.0 until 0.7.0 is official released.

**Comment by devemux86** [comment]
Yes I understand, even if we query a branch like Travis, then it'll not be automated anymore.
I suppose we can close the issue.

**Comment by karussell** [comment]
Maybe there is a kind of a configuration switch or we ask the repo owner :) ?

**Comment by devemux86** [comment]
There is already a related [question](https://github.com/jirutka/maven-badges/issues/7).
Is that working for you, (e.g. avoiding the RC versions) to post what you mean there?

**Comment by karussell** [comment]
Not sure if this is what the author mean but excluding RC versions would be nice. Or instead of the badge we can just include the full pom snippet in the Readme? Like I do here: https://graphhopper.com/#community

**Comment by devemux86** [comment]
>Or instead of the badge we can just include the full pom snippet in the Readme? Like I do here: https://graphhopper.com/#community

Yes something like that would be convenient. Many come to GitHub repository first, so seeing also there the artifact could help.

**Comment by karussell** [comment]
Added it [here now](https://github.com/graphhopper/graphhopper/blob/master/README.md#maven)
