### ISSUE TITLE
Add Road Type/Info to Garphhopper response

### ISSUE THREAD

**Issue by javierquevedo** [graphhopper/graphhopper#741]
It would be really convenient if Graphhopper provided the road type or the road info as part of the driving instructions. This way it would be possible to display the amount of KM which are highway vs street road for instance, which would definitely allow clients to enhance the user interfaces that use Graphhopper.

The information is already provided in most of the OSM maps and I believe that it is used to calculate the duration of the different segments of the trip, hence it should be quite easy to extend the current graphhopper response for this purpose.

Thanks for your consideration

**Comment by karussell** [comment]
This is something [we also want](https://github.com/graphhopper/graphhopper/pull/730) :)

Kind of duplicate request to #439 - so I would close this if you do think that is the case :)

**Comment by javierquevedo** [comment]
I do not think that it is the same as #439 since that one only asks about the speed for each segment. This new feature request is about adding the road type information, which is different from the speed.
I do think however that both should be included, therefore I suggest that in order to close either of the requests, it would be better to merge both of them, as well as discussing what other additional information it would be wise to add.

**Comment by javierquevedo** [comment]
Could you please add the "new feature" label to this issue?
Also, do you have any idea if this is something you might consider to do in the future?

Thanks!

**Comment by karussell** [comment]
Please see the whole discussion in #439 including my view on how this should be implemented where the requested feature would be only a special case IMO

**Comment by javierquevedo** [comment]
Indeed it appears that you consider my feature request in your response, therefore I suggest to close this one.
Thanks for your quick response.
