### ISSUE TITLE
Snapped_Waypoints - LineString or MultiPoint

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#742]
As discussed here https://github.com/graphhopper/graphhopper/commit/8890b52c83d09c179577a072d296206e6e408a5f#commitcomment-17876754

I think we should set the `snapped_waypoints` as `MultiPoint` instead of `LineString`. The actual content stays the same, so this is basically only semantics. Examples can be found here: http://geojson.org/geojson-spec.html#id3

I just copied both examples for easier discussion:

```
{
   "type": "MultiPoint",
   "coordinates": [ [100.0, 0.0], [101.0, 1.0] ]
}
{ 
   "type": "LineString",
   "coordinates": [ [100.0, 0.0], [101.0, 1.0] ]
}
```

**Comment by karussell** [comment]
Thanks&Done!

**Comment by boldtrn** [comment]
Thanks for the fast fix. So I'll close this issue.

**Comment by boldtrn** [comment]
@karussell I just saw that the tests are failing. But it seems to be unrelated to this issue.

**Comment by karussell** [comment]
Yeah, strange. Happens rarely ... opened an issue
