### ISSUE TITLE
Please clarify project scope in README

### ISSUE THREAD

**Issue by tv42** [graphhopper/graphhopper#745]
The README says

> GraphHopper Maps uses the Directions API for Business under the hood [...]

Please expand on that sentence. Does that mean that the software known as graphhopper/graphhopper makes requests over the network to a service, in order to work? Do I need an API key? Will it cost?

Is graphhopper/graphhopper what graphhopper.com runs as a service, or is graphhopper/graphhopper a client library for using graphhopper.com services?

**Comment by karussell** [comment]
Would you mind to use the forum for questions and link then from here to it?
