### ISSUE TITLE
Interpret traffic lights

### ISSUE THREAD

**Issue by NopMap** [graphhopper/graphhopper#75]
While I was driving through town today, rejecting the routing suggestions of my professional car navigation, I had this idea: The navigation was suggesting a road that looked faster according to distance and street class. But I know that there are a series of traffic lights on that road and it is actually faster to drive around it on a road without lights.

Common navigation systems are usually pretty bad about this, they are too optimistic when you drive downtown. I heard from a navigation guy a while ago that the commercial navigation data does not contain traffic lights.

So basically we should evaluate the (500000) traffic lights in the OSM data and if an edge has a traffic ligth, add a small speed penalty to that edge for car and bike traffic.

Also, I found that there is a tag for pedestrian crossings 
http://wiki.openstreetmap.org/wiki/DE%3ATag%3Ahighway%3Dtraffic_signals

Evaluating this could make a route much safer, but it's rather complicated, I don't have a simple idea on how to do it.
- [ ] clean up import and make node tags influence possible
- [ ] tune speed decrease but keep in mind that traffic lights could be off at night so use a low influence as start.

**Comment by jansoe** [comment]
I implemented a [brach](https://github.com/jansoe/graphhopper/tree/TrafficLights2) to take traffic lights into account. Although this leads to quite realistic travel times, the routing now becomes sometimes a bit arkward, trying to circumvent traffic lights by going around in zick-zack. It seems, that one can only take traffic lights into account, if general turncosts are taken into account.

**Comment by andreaswolf** [comment]
@jansoe I need further information (where on the route are traffic lights, roundabouts, crosswalks, …) for the application in my diploma thesis. As far as I see, your information is added during the prepare step, right? Do you know of a way to preserve that information for later processing? Is there a possibility to extract all this info from a final route?

If you need help with the turncost implementation (which would also be interesting for me), drop me a line.
