### ISSUE TITLE
Retrieve OpenStreetMap node ids in the path of routing result

### ISSUE THREAD

**Issue by frankxu2004** [graphhopper/graphhopper#751]
Is there any way to retrieve OSM node id rather than just coordinates along the path of routing result? That would be very helpful to merge with external data.

**Comment by karussell** [comment]
Please use and search our forum before creating issues :)

**Comment by frankxu2004** [comment]
Yes actually I have done the search and found https://github.com/karussell/graphhopper-osm-id-mapping
However it seems that it is not compatible with 0.7 version. 
`    @Override
    public List<Path> getPaths(GHRequest request, GHResponse rsp) {
        return super.getPaths(request, rsp);
    }
`
got errors since the interface seems changed and no more getPaths method exists.

**Comment by karussell** [comment]
getPaths -> calcPaths

**Comment by frankxu2004** [comment]
Thanks a lot for the updates! I am able to get OSM way id output now.
However as stated in my issue, is it possible to have a list of node ids in OSM along the routing path? The reason for that is, the way is too long sometimes, and the actual routing may only pass through part of them. So I think that representing route as a sequence of OSM nodes is a good idea for external data usage. How would I achieve this, if possible? Thanks!

**Comment by karussell** [comment]
Can we switch to the forum? And use this just if we know what to do :) ?

**Comment by frankxu2004** [comment]
Sure, just posted my question on the forum :)

**Comment by karussell** [comment]
As inbuilt feature #917
