### ISSUE TITLE
GraphHopper interprets OSM vehicle=private as foot=no

### ISSUE THREAD

**Issue by wschenke** [graphhopper/graphhopper#752]
GraphHopper interprets OSM vehicle=private as foot=no.
Example: OSM Residential [Road #37707545](http://www.openstreetmap.org/way/37707545) (you cannot walk through).

Suggested fix: Restore the old code of FootFlagEncoder.java shown in the attached difference of 
23effe6b47da4a631f47640a99675fbff181efc2 (Apr 17, 2016) and 489b977e5799ff1e0f60011f92fcf6942114e4d9 (Apr 30, 2016).
![footflagencoder_diff](https://cloud.githubusercontent.com/assets/20322922/16656862/916adaf6-4460-11e6-9dd9-2c3457d8e4fe.jpg)

**Comment by karussell** [comment]
Why would it make sense to let all pedestrian go through private roads?

**Comment by wschenke** [comment]
The  road is not tagged with "access=private", only the access by vehicles is restricted. The restrictions for pedestrians are either inherited from "access=" or they are explicitly set by "foot=" (and similar the restrictions for horses).

**Comment by karussell** [comment]
Thanks, indeed this makes sense! @ratrun do you know why you introduced 'vehicle' in your commit here https://github.com/graphhopper/graphhopper/commit/1ab8520?

**Comment by karussell** [comment]
In the wiki it is stated that foot is 'moving without a vehicle' https://wiki.openstreetmap.org/wiki/Key:access

**Comment by ratrun** [comment]
I'm sorry for the troubles. The referred modification in 1ab8520 for foot does not make sense for foot. I inserted the 'vehicle' for the foot encoder just in analogy to bike without noting that the vehicle access restrictions does not apply for pedestrians.

**Comment by karussell** [comment]
@ratrun no problem! Appreciate every change as always :)

@wschenke thanks for reporting is now fixed, will be deployed soonish.
