### ISSUE TITLE
Missing way for foot routing?

### ISSUE THREAD

**Issue by jcoupey** [graphhopper/graphhopper#766]
The GraphHopper maps frontend seem unable to route on foot over [way 146171341](http://www.openstreetmap.org/way/146171341). See [the route I get](https://graphhopper.com/maps/?point=45.52799%2C2.814576&point=45.527438%2C2.816636&locale=en-US&vehicle=foot&weighting=fastest&elevation=true&layer=TF%20Outdoors) around this way. 

This doesn't seem to be data-related as the way is tagged `highway=path`, like many other ways that cause no trouble to route through.

Hope this is the right place to post, let me know if https://discuss.graphhopper.com/ should have been preferred.

**Comment by karussell** [comment]
I think we have excluded certain more dangerous paths for foot (sac_scale=difficult_alpine_hiking). If you use hike all should be fine.

**Comment by jcoupey** [comment]
Oh right, I should have guessed, this makes perfectly sense. Thanks for the quick answer!

By the way, I'm really enjoying the elevation display. ;-)

**Comment by karussell** [comment]
Thanks :)

We could potentially enable this in the future, if some kind of warning mechanism is implemented. Something we plan to allow the currently disabled fords (#236)

**Comment by jcoupey** [comment]
Perhaps a warning would be interesting, as the "expected" route would still be displayed. But in my case, I should have been using `hike` over `foot` in the first place.

I suspect this is not that big an issue if not many ways are tagged as difficult (this is the case at least in the area I'm looking). In most of the routes I've tried, no way was ruled out for `foot`, even if some of them were clearly only suitable for `hike`.

**Comment by karussell** [comment]
Yes, indeed we still include tracks which are hiking for foot too. But we currently exclude dangerous hikes for foot. BTW: the conditional tagging could make problems in the mountains too (#621)

**Comment by pathmapper** [comment]
@karussell 

> But we currently exclude dangerous hikes for foot.

Is there somewhere a list which tags are leading to such an exclusion, or is `sac_scale=difficult_alpine_hiking`  the only one?
