### ISSUE TITLE
Change Java coding formatting to standard formatting

### ISSUE THREAD

**Issue by highsource** [graphhopper/graphhopper#770]
I've noticed that my code formatting differs from your standard format. Could you please share the Eclipse code format? Otherwise there's a risk we'll get more conflicts/noise when diffing/merging.

**Comment by karussell** [comment]
That is indeed a problem but here we only use IntelliJ or NetBeans. Probably it would be wise to switch to a more standard format instead of this trouble (?)

**Comment by highsource** [comment]
Or I'd switch to IntelliJ. As far as I know there's no way to import IntelliJ format into Eclipse.

**Comment by karussell** [comment]
I'm really open to switch the format to some more common format as we have e.g. a different setting on the map matching project which is ugly.

**Comment by karussell** [comment]
I'm currently looking how other Java projects are doing this. Of course we can use some post-processing via maven, but I would not rely on this.

**Comment by karussell** [comment]
E.g. ElasticSearch simply relies on some textual guidlines: https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-to-the-elasticsearch-codebase

 * Java indent is 4 spaces
 * Line width is 140 characters
 * The rest is left to Java coding standards
 * Disable “auto-format on save” to prevent unnecessary format changes.
 * Wildcard imports (import foo.bar.baz.*) are forbidden
 * Don't worry too much about import order. Try not to change it

**Comment by highsource** [comment]
We often have dual IDE projects (Eclipse/IntelliJ). So far we've found no way to import code format from IntelliJ into Eclipse. It is, however, possible to import from Eclipse into IntelliJ. There seems to be a some non-official solution for NetBeas [as well](https://netbeans.org/bugzilla/show_bug.cgi?id=197876).

**Comment by devemux86** [comment]
FWIW I always wondered about the "strange" GraphHopper formatting (e.g. with curly brackets).
Meaning why not using the standards, e.g. what Intellij / AS or other IDEs share by default.

**Comment by karussell** [comment]
The "strange" formatting came in the early days where I found brakets where open and close are in the same column more readable especially for beginners and then it stays as changing this is a bit harder as it breaks pull requests etc

But yes, let us change this now to a more standard thing

Still IntelliJ and NetBeans all have still different default settings so we need to define and share these settings somehow to make reformatting in different IDEs possible. Additionally we could run checkstyle. Maybe one could use @highsource suggestion and use an eclipse format (although I would hate to rely on Eclipse somewhere ;)), e.g. libgdx is doing exactly this https://github.com/libgdx/libgdx/wiki/Contributing#eclipse-formatter

Or just some plan textual guides es ElasticSearch is doing.

@oblonski do you know how we could solve this?

**Comment by devemux86** [comment]
>Or just some plan textual guides es ElasticSearch is doing.

I'd vote for that, seems indeed more convenient.
FYI in [Mapsforge](https://github.com/mapsforge/mapsforge) and [VTM](https://github.com/mapsforge/vtm) I use the default Intellij / Android Studio format settings.

**Comment by karussell** [comment]
I have decided to move to standard Java code formatting provided by IntelliJ and provide some compatible Netbeans settings. The move will happen soonish (after a bigger feature merge into master)

**Comment by devemux86** [comment]
@karussell :+1:

**Comment by karussell** [comment]
IntelliJ is just too clever. I was fighting with it and did not understand what was going on until I read [this here](https://blog.jetbrains.com/idea/2014/10/intellij-idea-14-will-detect-code-styles-on-the-fly/)

**Comment by devemux86** [comment]
If you're playing with IntelliJ this [keymap](https://resources.jetbrains.com/assets/products/intellij-idea/IntelliJIDEA_ReferenceCard.pdf) can be handy.

The `Ctrl+Alt+L` (Reformat code) on whole folders / modules combined with `Ctrl+Alt+O`(Optimize imports) helped me organize Mapsforge / VTM repositories. :smile:

**Comment by karussell** [comment]
Yeah, thanks.

Currently trying to make NetBeans config to match this default setting. I find some defaults a bit strange e.g. arrays it puts the opening bracket on a new line, and netbeans gets confused by this ... maybe I'll still use netbeans as default config (as one can encode this in the pom.xml) and IntelliJ picks it up correctly anyway now ;)

**Comment by karussell** [comment]
Ok, this procedure is good enough IMO: I'm using now a NetBeans config in the pom.xml which comes very close to the default IntelliJ formatter but improves things a bit. So the automated configured formatter of IntelliJ should work good enough.

Interesting that I stumbled over limitations in both IDEs. Generally speaking one can say that NetBeans applies the better defaults and IntelliJ is more fine grained configurable. And formatting is faster with NetBeans.

**Comment by devemux86** [comment]
>So if you have problems with IntelliJ formatting. Go to File->Settings->Editor->Code Style and deselect 'detect and use existing file indents for editing'.

I think `Ctrl+Alt+L` (Reformat code) overcomes that?

>Something missing?

You posted a well defined summary (could be posted in contribution guide too).

**Comment by karussell** [comment]
> I think Ctrl+Alt+L (Reformat code) overcomes that?

This works only if autodetected style is disabled.

**Comment by karussell** [comment]
Ok, fixed this and closing here for now.

**Comment by highsource** [comment]
I've started an Eclispe Code Styla Formatter for Graphhopper:
[GraphHopper.Formatter.zip](https://github.com/graphhopper/graphhopper/files/481920/GraphHopper.Formatter.zip)

This is based on Eclipse Built-In settings and [this comment](https://github.com/graphhopper/graphhopper/issues/770#issuecomment-246490515).

**Comment by karussell** [comment]
@highsource thanks - helpful! Maybe we should link in the contribution guide to this for Eclipse users?
