### ISSUE TITLE
replace json.org library with own wrapper

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#773]
Currently we use a json libary with a potential ugly license in web module (_The software shall be used for good, not evil._). [Others](http://blog.sonatype.com/2012/03/use-json-well-youd-better-not-be-evil/) don't like it too. Android has a Apache licensed version of it [here](https://android.googlesource.com/platform/libcore/+/310eafdfeb5db23a4d5e405bbe607cffd1f4b24a/json/src/main/java/org/json/JSONObject.java#26) claiming that: "_this class was written without inspecting the non-free org.json sourcecode_"

So we should look into alternatives to replace this.

Also for several tasks we need a json parser in the **core** in the future. Such a parser should be fast, small, actively maintained, usages according to [this](http://mvnrepository.com), simple to use for basic configuration reading stuff, available on maven central and the Apache License is preferred. Also Java 7 is required for now, reading into POJOs would be good but not required.
- https://github.com/fangyidong/json-simple, this is actually the json.org project?!? 25KB, 200 stars, 420 usages, Apache, seem inactive
- https://github.com/ralfstx/minimal-json 30KB, 340 stars, MIT, 36 usages
- https://github.com/square/moshi ~100KB, 2000 stars, Apache, 16 usages
- https://github.com/jdereg/json-io ~100KB, 170 stars, Apache, 14 usages
- https://github.com/google/gson ~230KB, 5700 stars, Apache, 2360 usages
- http://johnzon.apache.org/index.html 240KB?, does not apply, Apache, <10 usages
- https://github.com/FasterXML/jackson-jr ~300KB (equivalent to databind, jackson core is 280KB), 80 stars, Apache, usages 3K for normal jackson, jackson-jr <20
- https://github.com/owlike/genson ~400KB,120 stars, Apache, <20

Probably a lot simpler would be if we pick one for now, create a simple interface and then could switch afterwards.

**Comment by karussell** [comment]
The size is not that important as on Android side one could use ProGuard, on server side it does not matter and for iOS we probably need a different implementation.

**Comment by devemux86** [comment]
Well Gson has been more than good all this time. :+1: 

Also note that Android has a base [JSON API](https://developer.android.com/reference/org/json/package-summary.html) integrated.

**Comment by karussell** [comment]
Looks like they just copied the JSON lib we are currently using despite the license thing.

**Comment by karussell** [comment]
moshi looks even more streamlined (100KB) and is very similar to gson

**Comment by devemux86** [comment]
Does it [require](https://github.com/square/moshi#built-on-okio) also Okio (75KB)?

**Comment by karussell** [comment]
Ah, indeed. Still looks somehow cleaner: https://github.com/square/moshi#borrows-from-gson and okio is something we potentially need for okhttp at some point when replacing Downloader.

**Comment by karussell** [comment]
But still investigating and jackson seems to be more widespread ... maybe we should wait for the JDK to use some standard json parser? There is already a JSR for it: https://jcp.org/en/jsr/detail?id=353

Potentially the interface is a good idea where we can easily replace the implementation depending on the underlying platform

**Comment by devemux86** [comment]
There are too many comparisons online for the two of them - Gson vs Jackson. :smile: 

When it'll be included, in Java 9? Also then Android is another story.

**Comment by devemux86** [comment]
@karussell can the json stuff be in another module, for not loading `core` with dependencies?

**Comment by karussell** [comment]
I'm not sure about this as we need this as core feature. Probably we can use normal classes but abstracting this away might be too much work - not sure if it is worth the effort.

BTW: see this json stuff implemented in #781

**Comment by karussell** [comment]
Now #781 is merged now. Also I found that something called (a bit misleading if you ask me) JSON-P is already standardized through JCP (`javax.json`), [already present in JavaEE7](http://docs.oracle.com/javaee/7/api/javax/json/package-summary.html) and documented in latest [javamagazine](http://www.javamagazine.mozaicreader.com/JulyAug2016/Twitter#&pageSet=32&page=0)

**Comment by karussell** [comment]
Ok, we now have a simple JSON parsing/writing module and can extend this. In the core module we should probably not use JSON but instead use simple POJOs. Also the XML creation should be probably moved out of the core. So the remaining task is to use our JSON parser/writer interface for all purposes and get rid of the org.json dependency.

**Comment by devemux86** [comment]
@karussell well defined course of actions! :+1:

**Comment by karussell** [comment]
As we use no JSON lib in the core we can also move to the more standard and more powerful jackson library. E.g. #855 adds it already as test dependency for csv parsing.

**Comment by michaz** [comment]
The original goal, getting rid of the json.org library, is now accomplished. We still use gson in ``reader-json`` for now.
