### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#774]
Update docs regarding new Java API (GraphHopperOSM, eclipse, etc)

Rough new structure of index.md:
## Get Started

Link to GraphHopper Maps with picture

Link to Dev setup & User web setup

Introductory slides & videos
## Web

web/quickstart.md
web/api-doc.md
core/deploy.md
## Configuration

explain roughly config.properties or link to source with all parameters?
elevation.md
## Translations

translations.md
## Developers

Maven snippet, snapshots, IDE setup

changelogs
### Technical

quickstart-from-source.md
technical.md 
routing.md
weighting.md
location-index.md
low-level-api.md
ch.md
create-new-flagencoder.md
### Android

Include picture

android/index.md
android/android-studio-setup.md
### Windows

windows-setup.md
### Eclipse

// hmmh I do not like it much that these docs are kind of a workaround where there has to be a better solution. Should we remove them completely?

eclipse-setup.md
eclipse-tomcat-setup.md

**Comment by karussell** [comment]
I'm not that happy with the documentation right now. So if someone has an idea how we can:
 
 * link **inline** in the docs to **up-to-date** code example
 * set up a simpler/better structure e.g. separate in setup, preparation, routing, storage and deployment/web api or something
 * with a navigation/toc on the right side (have seen this somewhere here at github)

this would be awesome!

**Comment by devemux86** [comment]
>with a navigation/toc on the right side (have seen this somewhere here at github)

You mean the GitHub [Wikis](https://help.github.com/categories/wiki/)?

**Comment by karussell** [comment]
Yes. But I do not like github wikis (as we cannot refer to different versions) and so what we could do is use something similar we use for our [Directions API docs](https://graphhopper.com/api/1/docs/): [mkdocs](http://www.mkdocs.org/)

**Comment by kodonnell** [comment]
@karussell - is hosting on github required?

To get inline and up-to-date code documentation, my (little) experience is that it's best to have documentation directives in the code, and then auto-build the documentation (e.g. Sphinx). The reason being that if I'm e.g. developing a function, it's easy enough to just tweak the docstring, but I'm probably going to be too lazy to dig up the documentation file and tweak it.

You could get versioning by using readthedocs etc. I think that's per-release, but you can probably configure something so that the current state of the the master branch is also viewable.

Unfortunately, I'm not familiar enough with Java to recommend which documentation builder to use. (Though I see Sphinx has a java plugin.)

**Comment by karussell** [comment]
Thanks for the input.

> @karussell - is hosting on github required?

It is important that all can read and edit it there, yes. But we could host it somewhere else as 'main entry'.

**Comment by kodonnell** [comment]
All the documentation source would be in git, so they can "read and edit it" - is that what you mean? It wouldn't be pretty (e.g. just markdown), but that's the point of the published version. That'd be a nice separation.

**Comment by karussell** [comment]
Yes, sounds like a similar approach like it would be with the linked mkdocs

> The reason being that if I'm e.g. developing a function, it's easy enough to just tweak the 
> docstring, but I'm probably going to be too lazy to dig up the documentation file and tweak it.

Do you mean one could embed an example of code in the source code and it would 'somehow' appear in the docs?

**Comment by kodonnell** [comment]
Here's an example using javadoc:

- [source code](http://www.docjar.net/html/api/java/util/Collections.java.html) (with inline documentation)
- [generated documentation](https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html)

It's not actually a very nicely presented one - you can usually configure how it looks, including having more generic helpful documentation, etc. 

> Do you mean one could embed an example of code in the source code and it would 'somehow' appear in the docs?

Yes, I think so. Examples are included above (source - line 1554 of above, [doco](https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#synchronizedCollection(java.util.Collection))).

I don't think mkdocs actually strips documentation out from code files.

**Comment by karussell** [comment]
> It's not actually a very nicely presented one - you can usually configure how it looks, including having more generic helpful documentation, etc. 

That is the javadocs that we automatically create already. What I meant is a code snippet that we could directly integrate in the docs and would automatically refresh itself somehow :) if the referenced/underlying code changes.

Examples in javadocs have the same problem: they need to be maintained.

**Comment by karussell** [comment]
I've updated the documentation and introduced a new index.md

https://github.com/graphhopper/graphhopper/blob/master/docs/index.md

**Comment by kodonnell** [comment]
> Examples in javadocs have the same problem: they need to be maintained.

Ah, now I understand. I'm not sure that there's any way to get round the fact that you have to maintain both separately. This strikes me as similar to unit tests: when the API changes you also have to "maintain" them separately. The key difference is that you're reminded/forced to do this when the tests don't pass (which Travis makes obvious). So, maybe there's a way to utilise unit tests to get the same sort of visibility to when documentation is out of date. For example, you could put documentation examples in tests, and have the documentation builder extract them (somehow). How you do this, I don't know = ) With a custom built documentation site it'd be "easy", but I'm not sure you'll find support in existing documentation builders.

**Comment by kodonnell** [comment]
I also considered extracting the examples from the doc strings, and then running them as unit tests (hence equivalent functionality to the above). I didn't mention it as I thought it'd be too messy (and I think it probably still is), though to be fair I just found a python equivalent, [doctest](https://docs.python.org/2/library/doctest.html), so thought I'd mention it.

**Comment by karussell** [comment]
> This strikes me as similar to unit tests: when the API changes you also have to "maintain" them separately

Not really, as both is Java code and automatically refactored and test would fail to compile or run.

> So, maybe there's a way to utilise unit tests to get the same sort of visibility to when documentation is out of date

Yes, somehow I want a unit test inside the documentation

>  though to be fair I just found a python equivalent, doctest, so thought I'd mention it.

Thanks for the pointer - interesting.

**Comment by kodonnell** [comment]
> Not really, as both is Java code and automatically refactored and test would fail to compile or run.

Sure, IDE's can handle trivial refactoring, but much of the time you'll be stuck having to manually maintain them. The fact that tests fail / don't compile is my point: we want that for documentation.

**Comment by kodonnell** [comment]
The lack of clear documentation makes contribution for new developers difficult - see e.g. discussion [here](https://github.com/graphhopper/map-matching/pull/83). So maybe this is higher priority?

**Comment by karussell** [comment]
This issue was more meant to create a better structure of the docs and also make examples in the documentation properly working even after refactoring.

Of course, improving documentation is always good and nice. The best thing is if new developers ask questions and get answers and then they condense their new knowledge into a pull request which we can together improve step by step. If I would just add more docs I would not know which parts are important to go into detail etc

**Comment by stefanholder** [comment]
>the lack of clear documentation makes contribution for new developers difficult

For me, the lack of javadoc documentation made it quite hard. I think what we need are is a javadoc convention that applies to all new contributions. I would suggest to adopt the [javadoc rules from the Google Java Style Guide](https://google.github.io/styleguide/javaguide.html#s7.3-javadoc-where-required). Should we discuss javadoc documentation in a separate issue?

**Comment by mprins** [comment]
> That is the javadocs that we automatically create already. What I meant is a code snippet that we could directly integrate in the docs and would automatically refresh itself somehow :) if the referenced/underlying code changes.

If/when using the Maven site plugin to generate html docs you can use [code snippets](https://maven.apache.org/guides/mini/guide-snippet-macro.html); you add special comments to the source code and create a reference in the doc page source.
I've used this before but only on APT sourced pages, not sure how good the support of macro's is in other supported markup flavors...

**Comment by mprins** [comment]
Apparently current versions of Doxia support macro's in markdown as well:

> Macros are currently only supported for APT, Xdoc and FML formats. Starting with Doxia 1.7 (maven-site-plugin 3.5), macros are also supported for XHTML and Markdown. Macros are not (and probably will never be) supported by Confluence, Docbook and Twiki modules.

 [link](https://maven.apache.org/doxia/macros/index.html)

**Comment by karussell** [comment]
> Should we discuss javadoc documentation in a separate issue?

Yes, but a rule like this sounds really good! 

> If/when using the Maven site plugin to generate html docs you can use code snippets; 

Wow, this looks nice - now the question is: will it be refactored by e.g. IntelliJ or Netbeans :) ? Maybe we should create a separate 'docs module' with sources only for documentation purposes? E.g. how to do simple routing or fetch some results from a LocationIndex or link to already existing unit tests that show these tasks from the docs?

**Comment by karussell** [comment]
Also what to comment and what not is important and this is a good read: https://visualstudiomagazine.com/articles/2013/06/01/roc-rocks.aspx

 * It's important to communicate what the code should be doing. Comments should explain the "why" of the code and stop there. 
 * What comments should never, ever do is explain how the code does its job.

**Comment by stefanholder** [comment]
>Yes, and a rule like this sounds really good!

I just created issue 891, where we can further discuss javadoc documentation.

**Comment by mprins** [comment]
also there's a doclet: https://github.com/jtulach/codesnippet4javadoc to get code snippets in the javadoc, eg from test cases into test javadoc if you will

**Comment by kodonnell** [comment]
Sounds good all round. One comment - when evaluating solutions, we may need to e.g. refer to some GH code from within map-matching, and I'm not sure if that'll be supported. That, or we e.g. [merge map-matching into the GH repo](https://github.com/graphhopper/graphhopper/issues/792).

**Comment by karussell** [comment]
> we may need to e.g. refer to some GH code from within map-matching

You can do this normally with javadocs, e.g. pointing to other classes or method

**Comment by karussell** [comment]
Here is another interesting project: https://github.com/Abnaxos/pegdown-doclet where one can write markdown directly in the javadocs, even with [code blocks known from github](https://github.com/Abnaxos/pegdown-doclet#markdown-extensions)
