### ISSUE TITLE
Block area and roads per request

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#789]
We need a built-in functionality for the [forbiddenEdgeId-Weighting](https://github.com/graphhopper/graphhopper/blob/master/docs/core/weighting.md) to block an area or a list of lookups.

Currently this is only possible as a post processing step before the routing via the [overlay mechanism](https://github.com/graphhopper/graphhopper/pull/781)

**Comment by abxaz92** [comment]
I subscribe too

**Comment by boldtrn** [comment]
How would something like this look like?

The way I understand this issue is, that I would add for example:
- a list of edgeIds that are forbidden or have an massively increased weight for one particular request
- a list of coordinates with distances, e.g. `forbidden_point=lat,lng,radius`, all edges around this point in a certain radius are found ad added as forbidden edgeIds. Radius in this scenario could also be the maxRegion parameter of the LocationIndexTree, so no exact meter requirement but more like a "big area" or "small area".

**Comment by karussell** [comment]
We talked a bit offline about the new Data API I plan to build via POSTing JSON and probably here it would also make more sense to start with the JSON API for the `route` end point and include a more or less identical format but not persistent. What I mean is: the Data API will allow us to disable certain edges or reduce/increase speed in real time but persistent for all following route requests (all non-CH). The format should be the same which is already implemented in the [overlay reader #781. Now a POST request with an identical format against the `route` endpoint would only temporarily limit or change certain edge properties. So then there are three changes possible:
 
 * before an import, also applicable to CH, already implemented with the overlay reader
 * real time permanent update (for all later requests), will be implemented in #845
 * real time temporary update (just per request), should be implemented here, but for now probably the `forbidden_point` style you have in mind is sufficient. And create a new POST API for the `route` endpoint in a different issue. I've also a rough picture for this and its features.

But besides this more intense changes there are several other quirks with this issue: e.g. how to handle a location lookup if the edge is in the forbidden list (?) Also what should we do if the area is too big (i.e. too many edges would be involved)?

**Comment by karussell** [comment]
Fixed via #890

**Comment by jsroyal** [comment]
Is that this problem solved? Can I see the merge ID of PR?

**Comment by boldtrn** [comment]
@jsroyal just look at the comment above and yes it is fixed.

**Comment by jsroyal** [comment]
Thank you! @boldtrn, I went through the code and it is nice implemented.
and I am not able to block the path in web UI  as I can see the given see the ##899 vehicle=generic&ch.disable=true.
after that not able to select the area for the block.
Can please help how can I do that?

![image](https://user-images.githubusercontent.com/10773353/27040220-00446b6e-4fae-11e7-8152-19ea55131b6c.png)

**Comment by boldtrn** [comment]
@jsroyal I think the vehicle generic is not enabled in the API. You can use a different vehicle. Here is an example query:

https://graphhopper.com/maps/?point=50.847573%2C7.558594&point=49.781264%2C7.910156&ch.disable=true&block_area=50.85417,7.60108

**Comment by jsroyal** [comment]
Thank you, sir, for instance, response.
How to block in UI ? Not able to select area .

**Comment by boldtrn** [comment]
@jsroyal, this is not implemented in the UI, yet. Feel free to create a PR for this feature.

**Comment by jsroyal** [comment]
Yes! Sir Will do. Thank you.
