### ISSUE TITLE
Avoiding edges in 0.7.0

### ISSUE THREAD

**Issue by abxaz92** [graphhopper/graphhopper#801]
I try avoid some edges and can't understand your  "Weighting" docs. https://github.com/graphhopper/graphhopper/blob/0.7/docs/core/weighting.md
Because code in .md file not valid for 0.7.0 version, from maven

**Comment by karussell** [comment]
Thanks for your request :) 

Please use the documentation for the master, but even there are some problems, for them see #774 

Also please ask further questions [in our forum](https://discuss.graphhopper.com/)
