### ISSUE TITLE
Android build fails on build server

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#803]
Due to latest android version update we probably need to update the Android SDK there, until then we do not have snapshots of GH :/

**Comment by devemux86** [comment]
What server you mean?

**Comment by karussell** [comment]
Our internal build/dev server ... or we need to somehow make creation of snapshots possible for travis. But this can be more complex due to Android SDK setup. Not sure how others handle this.

**Comment by devemux86** [comment]
If it can help in Mapsforge and VTM I have organized lately their snapshots publishing, but via Gradle (see [here](https://github.com/mapsforge/vtm/blob/master/deploy.gradle)).

**Comment by karussell** [comment]
Is it working on travis?

**Comment by devemux86** [comment]
>Is it working on travis?

What do you mean?
The publishing is on Sonatype ([here](https://oss.sonatype.org/content/repositories/snapshots/org/mapsforge/)), Travis is still used for code testing.

**Comment by karussell** [comment]
When we run tests on travis many people just do the deploy there for the snapshots, are you doing this on travis or on your own machine? On my own machine I had this working with the maven android stuff, just need to update the Android SDK I think

**Comment by devemux86** [comment]
>When we run tests on travis many people just do the deploy there for the snapshots, are you doing this on travis or on your own machine?

You mean the GH `travis-build.sh` script?

>On my own machine I had this working with the maven android stuff, just need to update the Android SDK I think

A lot of things have [broken](https://github.com/simpligility/maven-android-sdk-deployer/issues) lately with Android + Maven, I hope you make it working.

**Comment by karussell** [comment]
> You mean the GH travis-build.sh script?

Yes, if we would add 'deploy' there we would get snapshots deployed (easily) but without android

**Comment by devemux86** [comment]
That's a good thought, but what about Sonatype credentials?

For Android see our [.travis.yml](https://github.com/mapsforge/vtm/blob/master/.travis.yml), very simple and works for both Android and Java modules in the project.

**Comment by karussell** [comment]
> That's a good thought, but what about Sonatype credentials?

There was either some travis magic involved I think

> For Android see our .travis.yml, very simple and works for both Android and Java modules in the project

Ah, this might work for us too. The android part is interesting and wasn't existent when I looked into it the last time I think.

**Comment by devemux86** [comment]
See [here](https://docs.travis-ci.com/user/languages/android) for all options regarding Android.
You can even enable emulators for running tests.

**Comment by mprins** [comment]
You can easily publish maven snapshot artifacts to the (sonatype) central snapshot repository;
you need to:

  - add secure tokens for username and password to your .travis.yml (or environment), eg. https://github.com/GeoDienstenCentrum/sass-maven-plugin/blob/master/.travis.yml#L12
  - add a custom settings with the server specified, eg. https://github.com/GeoDienstenCentrum/sass-maven-plugin/blob/master/.travis/settings.xml#L6
  - add a maven deploy build step in your .travis.yml, eg. https://github.com/GeoDienstenCentrum/sass-maven-plugin/blob/master/.travis.yml#L70

**Comment by karussell** [comment]
@mprins really nice, also the other travis hacking :) ! Especially I always wanted to do a parallel build for JDK9 #701 and you seem to have it there already.

Regarding the security tokens: this means that everyone cloning your repository is able to publish snapshots or are they somehow bound to your travis account? If yes, how can this be done?

**Comment by karussell** [comment]
BTW: turned out to be some missing import statements but still a travis build would have catched this earlier

**Comment by mprins** [comment]
@karussell 

> Regarding the security tokens: this means that everyone cloning your repository is able to publish snapshots or are they somehow bound to your travis account? If yes, how can this be done?

the tokens are repository specific, that is the repo is part of the hash; see: https://docs.travis-ci.com/user/encryption-keys/ and https://docs.travis-ci.com/user/pull-requests#Pull-Requests-and-Security-Restrictions

**Comment by karussell** [comment]
Really nice - thanks! So, yes we need such a magic travis config with snapshot deployment and jdk9 build :) ! Would you have interests in doing this @mprins :) ?

**Comment by mprins** [comment]
I'll see If I can hack it over the weekend

**Comment by karussell** [comment]
Now that we use a script to install the JDKs (and test against them) we could try to switch to the `android` language on travis and build the android apk too: https://docs.travis-ci.com/user/languages/android/

Has someone from the community interests to try this :) ?
