### ISSUE TITLE
NullPointerException at MMapDataAccess.getInt(MMapDataAccess.java:313)

### ISSUE THREAD

**Issue by darek607** [graphhopper/graphhopper#804]
Hello,
On Samsung Galaxy S2, I'm getting SOMETIMES this exception while route calculation.
The exception happens for ASTAR BI algorithm with CH disabled.

I switched to ASTAR BI algorithm, because on DIJKSTRA BI out of memory happened for long routes (>400km) on my SGS2 when CH is disabled (I'm using favored heading)

On Galaxy J5 (more memory, 1.5GB) the error probably never happened (I must test it more times).

When using DIJKSTRA BI with CH enabled I never noticed this error (on both SGS2 and J5)

Summary (exception observed for this settings):
-Graphhopper 0.7
-Android 4.1.2
-weighting: fastest
-vehicle: car
-CH disabled
-max visited nodes: 1000000
-algorithm: ASTAR BI
-2 route points (start, end)
-heading is set for 1'st point

Logs:

> java.lang.RuntimeException: An error occured while executing doInBackground()
>             at android.os.AsyncTask$3.done(AsyncTask.java:299)
>             at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
>             at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
>             at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
>             at java.util.concurrent.FutureTask.run(FutureTask.java:137)
>             at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
>             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
>             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
>             at java.lang.Thread.run(Thread.java:856)
>      Caused by: java.lang.NullPointerException
>             at com.graphhopper.storage.MMapDataAccess.getInt(MMapDataAccess.java:313)
>             at com.graphhopper.storage.EdgeAccess.getOtherNode(EdgeAccess.java:146)
>             at com.graphhopper.storage.BaseGraph$EdgeIterable.next(BaseGraph.java:1036)
>             at com.graphhopper.routing.AStarBidirection.fillEdges(AStarBidirection.java:240)
>             at com.graphhopper.routing.AStarBidirection.fillEdgesTo(AStarBidirection.java:229)
>             at com.graphhopper.routing.AbstractBidirAlgo.runAlgo(AbstractBidirAlgo.java:75)
>             at com.graphhopper.routing.AbstractBidirAlgo.calcPath(AbstractBidirAlgo.java:63)
>             at com.graphhopper.routing.AbstractRoutingAlgorithm.calcPaths(AbstractRoutingAlgorithm.java:120)
>             at com.graphhopper.routing.template.ViaRoutingTemplate.calcPaths(ViaRoutingTemplate.java:110)
>             at com.graphhopper.GraphHopper.calcPaths(GraphHopper.java:1098)
>             at com.graphhopper.GraphHopper.route(GraphHopper.java:1003)
>             at com.darekk.service.nawigacjaoffline.app.tasks.RoutingTask.doInBackground(RoutingTask.java:107)
>             at com.darekk.service.nawigacjaoffline.app.tasks.RoutingTask.doInBackground(RoutingTask.java:21)
>             at android.os.AsyncTask$2.call(AsyncTask.java:287)
>             at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
>             at java.util.concurrent.FutureTask.run(FutureTask.java:137)
>             at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
>             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
>             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
>             at java.lang.Thread.run(Thread.java:856)

**Comment by devemux86** [comment]
How do you initialize GrapHopper, with `GraphHopper().forMobile()`?
See also #499.

Device RAM is fully available if you're using native code, OpenGL, etc.
The smaller [heap size](https://developer.android.com/training/articles/memory.html) is important here and it varies with the devices.

**Comment by darek607** [comment]
Yes, I use GraphHopper().forMobile()

**Comment by karussell** [comment]
Interesting that a reachable reference is nulled although the wrapping class is non-null. Did you switch apps in-between?

**Comment by darek607** [comment]
No, I didn't switch apps.

**Comment by karussell** [comment]
Wasn't reported since then. Closing for now.
