### ISSUE TITLE
Graph not load because of "-gh" elsewhere

### ISSUE THREAD

**Issue by devemux86** [graphhopper/graphhopper#805]
We have 2 folders side by side: one filled with graph named "foo" and another empty named "foo-gh".

When we call `graphHopper.load` with the "foo" folder, the code [here](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/GraphHopper.java#L750-L751) searches also for the "-gh" suffix, finds the empty "foo-gh" and continues to load that instead, failing at the end.

**Comment by karussell** [comment]
So which folder to load :) ? Or do you just mean we should prefer without "-gh" suffix?

**Comment by devemux86** [comment]
I ask the API explicitly to load the "foo" folder, that folder exists. That should be used (either if contains graph or not).

And if the folder does not exist, I'm not sure if such automations help or confuse the user.
e.g. I was searching why my graph was not loading, until I realized that the API persisted on its side folder instead. :smile:

**Comment by karussell** [comment]
Yes, ugly. Problem is that this breaks backward compatibility. But probably the only reason why I did this was the graphhopper.sh script where we can move the `-gh` addition.
