### ISSUE TITLE
Helper method wrong?

### ISSUE THREAD

**Issue by FallenKain** [graphhopper/graphhopper#809]
hey, i try to play with max turn costs in car flag encoder and when i chaged value to 2, get error message from EncodedValue class that say me that value 2 can't be writen by 1 bit, okaaaay lets see where it did...
that's AbstractFlagEncoder's method
```java
public int defineTurnBits( int index, int shift )
    {
        if (maxTurnCosts == 0)
            return shift;
        // optimization for turn restrictions only
        else if (maxTurnCosts == 1)
        {
            turnRestrictionBit = 1L << shift;
            return shift + 1;
        }
        int turnBits = Helper.countBitValue(maxTurnCosts);
        turnCostEncoder = new EncodedValue("TurnCost", shift, turnBits, 1, 0, maxTurnCosts)
        ...
```
and this Helper's method
```java
public static int countBitValue( int maxTurnCosts )
    {
        double val = Math.log(maxTurnCosts) / Math.log(2);
        int intVal = (int) val;
        if (val == intVal)
            return intVal;
        return intVal + 1;
    }
```
and now only example ;)
log(2)/log(2)=1
(int) 1 = 1
1 = 1 => return 1
right?
but "2" is 10 in bit form and has 2 bits, not 1 ¯\_(ツ)_/¯

**Comment by karussell** [comment]
Thanks for spotting! Currently no performance critical path involved so just moved this to a loop.
