### ISSUE TITLE
Right-Clicking multiple times on a marker creates duplicate menu entries

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#818]
Minor UI glitch

**Comment by fbonzon** [comment]
This is fixed by upgrading to the latest version of Leaflet.contextmenu. Verified on my private instance. Preparing a PR here.

(What is a "good first issue" ?)

**Comment by karussell** [comment]
> This is fixed by upgrading to the latest version of Leaflet.contextmenu. Verified on my private instance. Preparing a PR here.

Nice

> (What is a "good first issue" ?)

Issues for potential newcomers, so that they see how they could get started easily. But expert contributors are of course also welcome :) !
