### ISSUE TITLE
U-Turn on highway

### ISSUE THREAD

**Issue by vince1995** [graphhopper/graphhopper#829]
Umm... I think a u-turn on a highway is not a good idea.

[https://graphhopper.com/maps/?point=64.111239%2C-21.78061&point=64.118115%2C-21.78782&locale=de-DE&vehicle=car&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale](https://graphhopper.com/maps/?point=64.111239%2C-21.78061&point=64.118115%2C-21.78782&locale=de-DE&vehicle=car&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale)

**Comment by karussell** [comment]
Two things here: 

 * we do not support turn restrictions for the default and and you have to add `ch.disable=true` to fix this. See #270 
 * Plus the underlying data does not seem to forbid u-turns there otherwise it would work

**Comment by zhiqiangZHAO** [comment]
Interesting highway, which is not double digitized. And literally, it's not a U-turn, just a very sharp turn. Legally, I don't know whether the turn is forbidden by law.

**Comment by highsource** [comment]
[Here](https://www.google.de/maps/place/64%C2%B007'05.2%22N+21%C2%B047'16.1%22W/@64.1150711,-21.7812343,18z/data=!4m5!3m4!1s0x0:0x0!8m2!3d64.1181111!4d-21.7878056) it is. Probably one-way tag is missing.

**Comment by karussell** [comment]
> Probably one-way tag is missing.

The one-way is there - you can switch to OpenStreetMap layer to see it on the map. It is just the missing turn restriction IMO.

> And literally, it's not a U-turn, just a very sharp turn. 

Still I doubt it is legal :)
