### ISSUE TITLE
Bolivia main roads and fords.

### ISSUE THREAD

**Issue by AllroadsNL** [graphhopper/graphhopper#830]
I just searched for ford in the issues
But decided to make a new one.
South America conditions.

If ford is always a no go, this is a big problem in these countries, also for main roads, but local villages it is not possible to reach.

[Just behind a ford](https://graphhopper.com/maps/?point=-18.145362%2C-66.989822&point=-18.635754%2C-66.322489&locale=nl-NL&vehicle=car&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale)
And this is a main road from a city to city.

More local from to a village there a lot of fords.
[example](https://graphhopper.com/maps/?point=-20.257044%2C-66.960125&point=-20.113004%2C-67.040462&locale=nl-NL&vehicle=car&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale )

[example](https://graphhopper.com/maps/?point=-22.061838%2C-65.594194&point=-21.965773%2C-65.723734&locale=nl-NL&vehicle=car&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale)

All fords on node or way ford=yes or with intermittent=yes

It should be better to visualize data on the screen if there are fords in the road.

**Comment by karussell** [comment]
What is the difference to #236?

**Comment by AllroadsNL** [comment]
This one, I does not read it, so close it now.
Now 2016, so after 2014 it is still a major problem.

**Comment by karussell** [comment]
> so after 2014 it is still a major problem

You are invited to provide a fix/PR for it, should not be that difficult :)

**Comment by AllroadsNL** [comment]
fix like a tag on the ford or you mean code for the program, I am more a tagger.
