### ISSUE TITLE
Supported vehicle types in API "info" endpoint

### ISSUE THREAD

**Issue by fbonzon** [graphhopper/graphhopper#838]
It would be nice to know, before sending a routing request to the API, what vehicle types are allowed with our API key. Some GraphHopper account types don't have access to all vehicle types, e.g. free accounts have access only to car, foot and bike.

Currently, there is no way to programmatically know if, say, `mtb` vehicle will be allowed, other than issuing a routing API call and check if it returns an error or not.

From the [documentation](https://graphhopper.com/api/1/docs/routing/#area-information):

> `features` A json object per supported vehicles with name and supported features like elevation

It is not clear if "supported" refers to the API system itself, or to my specific key used to call the `info` endpoint.

Currently, all vehicle types supported by the API are returned, regardless of the given API key.

Expected:
Either only vehicle types supported by the key are returned.
Or a new key is created and returned, telling about allowed vehicles types for the given key.

In all cases, the documentation should be updated and made clear.

**Comment by karussell** [comment]
This is not a graphhopper issue. Please post this here instead where those limits will be handled: https://discuss.graphhopper.com/c/directions-api
