### ISSUE TITLE
Maximum locations per request in API "info" endpoint

### ISSUE THREAD

**Issue by fbonzon** [graphhopper/graphhopper#839]
It would be nice to know, before sending a routing request to the API, what is the maximum locations per request allowed with our API key. This number varies with GraphHopper account types. E.g. 5 with Free accounts, 30 with Basic accounts, etc.

Currently, there is no way to programmatically know if my routing query with _n_ locations will be allowed, other than issuing it and check if it returns an error or not.

My first use case is the GraphHopper Maps UI. Creating a new intermediate point could be disabled once the maximum allowed count of intermediate points is reached.

E.g. if using a free account (max. 5 locations: start, end and 3 intermediates), and you already defined 3 intermediate points, then the **+** icon in the left margin to add a new location would be disabled, as well as the "Add intermediate point" item in the context menu.

You should create and return a new key `max_locations` in the answer to the `info` endpoint calls.

**Comment by karussell** [comment]
This is not a graphhopper issue, the limits should be handled in an upper layer as this cannot be configured once but per user. Please post this here: https://discuss.graphhopper.com/c/directions-api

**Comment by karussell** [comment]
Similarly to #838 both are valid issues and you can immediately report them [here](https://github.com/graphhopper/directions-api/issues)
