### ISSUE TITLE
Improve web API and UI

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#844]
This issue will happen on the `pt` branch and improve the UI and web API so that we can better show public transport routes.

Furthermore we can think about a web service already compatible with the client from PTE, so that it can be consumed from [Transportr](https://github.com/grote/Transportr) or Öffi.

**Comment by karussell** [comment]
Currently we have the following rough structure:

```
routes: [{
   points: <geojson or string>
   instructions:[{
       text: "Turn right onto xy"
       interval: [<points index from>, <points index to>]
       sign: <some number>
```

So it is `routes->instructions` where a special sign==5 occurs in the instructions if a via point is reached, which is a bit suboptimal and could be splitted into `routes->legs->instructions`

Now when we look at comparable services they often directly embed the part of the geometry in the instructions but I still prefer our notation with one geometry (`points`) and a reference into this (`instructions.interval`) which also avoids duplication within the JSON.

Now still the question is how to integration public transport. There are services like Google that do `routes->legs->steps->{step_property_x, transit_details,steps}` which I currently tend to prefer probably without the last `steps` and renaming `steps` into `instructions`.

It could be more generic where also ride sharing operators (not just public transport agencies) could be integrated via:

`routes->legs->steps->{step_property_x, operator, line, stops}`

**Comment by michaz** [comment]
c7d8f06

**Comment by karussell** [comment]
> wasn't so good because I don't want to concurrently work on the website, and it doesn't like new instruction signs.

what do you mean here? I can go ahead to create e.g. new instructions or required changes in JS or the web API ...

**Comment by michaz** [comment]
Would be nice if both the JS and the web API would not crash when I add a new Instruction type. Currently they do (because they don't find the wording or the image). Maybe just output a generic text and no picture in that case?

**Comment by michaz** [comment]
(Or maybe I should just learn to handle the JS part, then I can add it myself.) :-)

**Comment by karussell** [comment]
> Would be nice if both the JS and the web API would not crash when I add a new Instruction type to try something out

Normally adding a new sign to Instruction should be sufficient for the Java side. JS wise you can change it [here](https://github.com/graphhopper/graphhopper/blob/master/web/src/main/webapp/js/messages.js#L17)

> Maybe just output a generic text and no picture in that case?

The case of adding a new instruction is very rare so this is not necessary (at least now) I think.

**Comment by karussell** [comment]
I've just added some more changes (just for better demonstration) in this branch: https://github.com/graphhopper/graphhopper/tree/pt_peter

**Comment by michaz** [comment]
Make instructions which are not "debug" but really for users.

**Comment by michaz** [comment]
@karussell Can we close this for now? I kind of like what I'm seeing at the moment.

**Comment by karussell** [comment]
This this is already improved
