### ISSUE TITLE
Make writes thread-safe

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#845]
The new overlay module should be usable at some point on a per-request method. For that we need as a first step a write-thread-safe handling of graph updates and e.g. apply them permanently.

Potentially we need to break the Java API here to avoid 'flush' for every edge.setXY method and instead flush explicitely only after a certain method call (edge.flush) or automatically after edgeIterator.next calls (which would avoid breaking backward compatibility)

**Comment by karussell** [comment]
This was done in the [change-graph-api branch](https://github.com/graphhopper/graphhopper/commits/change-graph-api). Currently we do not use a per-edge locking but instead use an easier global write lock to make sure that every Dijkstra sees consistent data. When we see that the writes take too long and can't be further optimize we'll need to reinvestigate how to establish per-edge locking, and if it would be faster at all.

**Comment by michaz** [comment]
Roughly, this looks good to me. :-)

I would test it by somehow injecting a fake graph modifier, let that wait, concurrently make a routing request, let the fake graph modifier continue (1), and take care that my routing request doesn't finish before I do (1).

Never done it before, though.

About per-edge locking: I think, no matter how slow global locking is, we need a _theory_ about what changing edges on the fly does to our algorithms. Before that, I think we don't need to investigate performance.

**Comment by michaz** [comment]
To model delays in public transport, we will at some point need to make structural changes to the graph -- changing edge flags will not be enough. 

When a trip is delayed, we must change the to-node of its transfer edge so that it points to the correct point in time.

**Comment by michaz** [comment]
Though it's not clear we have to do any of this in the base graph. Maybe everything delay-related can be in a ``QueryGraph``-like thing which stays wrapped around the base graph.

**Comment by karussell** [comment]
> Though it's not clear we have to do any of this in the base graph.

Yes, we could do this in the QueryGraph. In the base graph disconnecting edges is already possible but adding edges (temporary) to a node leaves gaps in the edge space ... which could be managed by some garbage collector though.

**Comment by karussell** [comment]
Done in #918

**Comment by karussell** [comment]
I stumbled over this project https://github.com/google/thread-weaver (kind of 'stale' status)
