### ISSUE TITLE
Inconsistent handling for PBF: GraphHopperLocation cannot be the OSM file 

### ISSUE THREAD

**Issue by ratrun** [graphhopper/graphhopper#857]
I ran into troubles with this check in Graphhopper.java:

```
        } else if (graphHopperFolder.endsWith(".osm") || graphHopperFolder.endsWith(".xml")) {
            throw new IllegalArgumentException("GraphHopperLocation cannot be the OSM file. Instead you need to use importOrLoad");
```
In BikeTourPlanner I am using the same folder name for the graph folder compared to the input OSM file. This works fine for the '*.pbf' files from GeoFabrik, which come with an extension `*.osm.pbf` . Today I wanted to use an OSM file stored from JOSM and ran into this check. Why is this check necessary? Why isn't there a similar check for `*.pbf` ?

**Comment by karussell** [comment]
This looks inconsistent indeed and seems to be related to #805 

Still I do not understand the exact issue. You have a file named xy.osm and a folder called xy.osm?

**Comment by ratrun** [comment]
Yes, I do have a file called `data/osmfiles/xy.osm` and a folder called `data/graphs/xy.osm`. This works fine with a file `data/osmfiles/xy.osm.pbf` and the folder called `data/graphs/xy.osm.pbf` . As you promised to take a look on my BikeTourPlanner application I would ask you to reproduce by trying to create a graph from an OSM file, which you copy to `data/osmfiles` folder by hand.

**Comment by karussell** [comment]
Ok, understood and makes sense if the path if different :)

Probably we should just remove this if?

**Comment by ratrun** [comment]
Removal of the check was my first idead as well, but I cannot judge if this breaks something, there should have been some motivation for it which I do not understand.

**Comment by karussell** [comment]
> there should have been some motivation for it which I do not understand

someone can confuse the graphhopper location with the datareader.file e.g. in the config. But we should be able to solve this differently
