### ISSUE TITLE
Barriers lead to disconnected areas

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#86]
Currently we completely remove small subnetworks in order to avoid failures when routing (as two disconnected areas won't have a path in between). Those subnetworks exists due to OSM errors or other things (?)

But the barriers can introduce further subnetworks ([example](http://www.openstreetmap.org/edit?lat=51.0757&lon=13.7388&zoom=18)). The problem is that only a subset of the allowed vehicles could be affected by those barriers. E.g. `barrier=bollard` limits cars but not pedestrians. Which means only for cars the disconnected subnetwork exists.

 - [ ] In order to fix that one needs to identify all subnetworks (per vehicle) and restrict access (setting both direction flags to 0). Now, if all allowed vehicles have the same restriction for one edge one can safely remove this edge.
 - [ ] Make this process working for the one way network removal (tarjan algorithm) too
 - [x] But still there will be problems related to this as in some cases an area is only reachable to "go out" or "go in". E.g. [this query](http://graphhopper.com/maps/?point=55.862711%2C-4.432372&point=55.864237%2C-4.251806) or [here](http://graphhopper.com/maps/?point=krakow&point=berlin). This will be fixed via #226

**Comment by Svantulden** [comment]
What could be used as a workaround to allow bike,foot vehicles but also use the `prepare.minOnewayNetworkSize=200` and `prepare.minNetworkSize=100` setting? 

Do I need to prepare one graph for every vehicle with these settings and run them on a different port?

**Comment by karussell** [comment]
Yes, as a workaround something like this would necessary and would be probably the easiest to setup. Or use one JVM with multiple GraphHopper instances. 

The best way of course would be to fix the issue :)

**Comment by karussell** [comment]
Fixed and merged in #487
