### ISSUE TITLE
Create simple walk network from station positions

### ISSUE THREAD

**Issue by michaz** [graphhopper/graphhopper#862]
Write a method which takes all station positions and creates a simple walk network to cover them, e.g. with a spanning tree. Connect it to the time-expanded pt network.

Solves two thing:

a) We know that we can, in principle, combine pt with unrestricted walking.
b) RNV will work, without us having to worry what exactly a station or a stop is.

**Comment by karussell** [comment]
As this under 'done' of the projects' tabs: we can close here?

I would have solved it very stupidly via importing the road network for the gtfs coverage and iterating over all stations and find the closest walking road. Would you mind to clarify your approach? Is the Delaunay triangulation just a workaround for cases when no walking network can be imported and is the estimated travel time from this not just an estimation?

**Comment by michaz** [comment]
Yes, and yes. But that was the scope of the ticket as I meant it. I just wanted a stub walk network so I know I can handle fundamentally different classes of edges.

**Comment by karussell** [comment]
Thanks, understand this now :)

**Comment by michaz** [comment]
..and I apparently thought tickets would.close themselves when I move them right. I see now that this is not true. :)

**Comment by karussell** [comment]
This feature was introduced very recently from github so I expect that they'll support this at some point ;) ... although I'm not sure how they'd implement this, as we can create those columns ourself with any meaning attached to them. E.g. a recent idea I had was to add a review column?
