### ISSUE TITLE
Bike profile avoids cycleway

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#863]
Something is wrong [here](https://graphhopper.com/maps/?point=50.6698%2C10.972338&point=50.667981%2C10.975208&vehicle=bike&layer=TF%20Cycle)

![export](https://cloud.githubusercontent.com/assets/129644/20171591/b59db626-a731-11e6-8fd7-468e851d8ddf.png)

Tagging seems [to be ok](http://www.openstreetmap.org/way/180934291).

Oh, and racingbike takes a huge detour (is this correct?)

**Comment by karussell** [comment]
Maybe railway:razed or vehicle:no makes problems here?

**Comment by karussell** [comment]
Interesting. @ratrun do you think we should allow access if it is tagged highway:cycleway and vehicle:no? I don't think so (or how should we otherwise forbid access to a cycleway in case of a construction?). Instead we should require an additional bicycle=designated or bicycle=yes. But if those things are in place we already pass.

So, as the data was edited how can I find out the previous state to understand if that needs an improvement (and e.g. the OSM change should not have been necessary?)

**Comment by boldtrn** [comment]
> So, as the data was edited how can I find out the previous state to understand if that needs an improvement (and e.g. the OSM change should not have been necessary?)

The history can be viewed using this [link](http://www.openstreetmap.org/way/180934291/history).

**Comment by karussell** [comment]
Thanks a bunch - this helps a lot :) !

**Comment by karussell** [comment]
Strange, cannot reproduce it. Not a failure for the old tagging nor a failure for a fresh import.

**Comment by ratrun** [comment]
I can confirm your obersavtion, it works if you run it locally. The tagging change from yesterday is irrelevant, only 'railway=razed' was added. I observed the same in this discussion on the [forum](https://discuss.graphhopper.com/t/how-does-foot-yes-affect-bike-routing/1166/8) from a case in Sweden.  The problem can only be seen on the online instance.
Anyway, the discussion about the tagging above is valid. I'm going to prepare a change to accept 'highway=cycleway' toghether with 'vechicle=no'. We should allow this for bicyles. Cyceways under contstuction should be tagged with with 'highway=construction' and a note like 'this seem to become a cycleway'.

There is one questions I already wanted to ask for a long time: How do you keep your planet file for the online instance up to date? Are you using the osmosis diff method or something different?

**Comment by karussell** [comment]
>  The problem can only be seen on the online instance.

Strange, but in both cases the OSM data was updated afterwards making guessing a bit harder. We should keep this in mind. Maybe it is something unrelated like a disconnected network or something. Ugly.

> Cycleways under construction should be tagged with with highway=construction

Ok

> How do you keep your planet file for the online instance up to date? Are you using the osmosis diff method or something different?

We download the planet file only if a new is available and for the days in-between we use osmupdate, which could be a potential source for quirks (compared to the full data), although we never had a problem.

**Comment by ratrun** [comment]
>Strange, but in both cases the OSM data was updated afterwards making guessing a bit harder. We should keep this in mind. Maybe it is something unrelated like a disconnected network or something. Ugly.

Reading between the lines this sounds as you also cannot reproduce it any longer also on the online instance. I do still see the problem there, so it is different compared to the Sweden case, where I could not reproduce it with the original tagging and the issue vanished a day after on the online instance when the user has added the 'segregated' tag. I read that there were some problems with the diffs recently, so eventually this might related. You could verify that if you extracted the Langewiesen area from your todays planet.

In the meantime I prepared the announced change here: 7561a08afb57d5b168875f38de8ce29e8ef2626d and ask for a cross-check.

**Comment by karussell** [comment]
> Reading between the lines this sounds as you also cannot reproduce it any longer also on the online instance.

I didn't mean this. I cannot reproduce this locally.

> You could verify that if you extracted the Langewiesen area from your todays planet.

How would I do this easily?

> In the meantime I prepared the announced change here: 7561a08 and ask for a cross-check.

We can discuss this in a separate PR

**Comment by ratrun** [comment]
I am using [osmconvert](https://wiki.openstreetmap.org/wiki/DE:Osmconvert), this is ways faster compared to osmosis. If I didn't mangle up the order of the bounding box it should be easily possible with  a call like 

`osmconvert.exe planet-latest.osm.pbf  -b=10.9710926,50.6668666,10.9775229,50.6707311 -o=d:\temp\extract.pbf`

**Comment by ratrun** [comment]
The command is correct. With the extract from a planet from 28.10.2016 I also cannot reproduce this issue.

**Comment by karussell** [comment]
Thanks, I can now reproduce this with the extract from our servers! There seems to be data missing and the whole osm way consist of just [two nodes](https://graphhopper.com/maps/?point=50.669375%2C10.972745&point=50.669266%2C10.972638&vehicle=bike)

```xml
        <way id="180934291" version="1" timestamp="1970-01-01T00:00:01Z" changeset="1">
                <nd ref="428730778"/>
                <nd ref="1913903626"/>
                <tag k="foot" v="yes"/>
                <tag k="name" v="Ilm-Rennsteig-Radweg"/>
                <tag k="width" v="2.8"/>
                <tag k="bicycle" v="designated"/>
                <tag k="highway" v="cycleway"/>
                <tag k="surface" v="asphalt"/>
                <tag k="vehicle" v="no"/>
                <tag k="maxspeed" v="30"/>
                <tag k="bicycle_road" v="yes"/>
                <tag k="traffic_sign" v="DE:244"/>
                <tag k="source:maxspeed" v="DE:bicycle_road"/>
        </way>
```

There maybe indeed some diff issues. Will close here for now.
