### ISSUE TITLE
Implement profile queries

### ISSUE THREAD

**Issue by michaz** [graphhopper/graphhopper#866]
... by adding "late departure time" as additional optimisation criterion

**Comment by wherbawi** [comment]
Will this be a single objective profile query or combined with multiobjective?

**Comment by michaz** [comment]
> Will this be a single objective profile query or combined with multiobjective?

Combined with multi-objective. I think it can then be turned back into single-objective profile query just by not assigning any cost in "number of transfers" to any edge.

**Comment by wherbawi** [comment]
👍will modify the existing one to a single objective (Lex arrival, number of transfers) profile query variant to get the earliest arrival with the least transfers trips. This should be a bit faster

**Comment by michaz** [comment]
Commit 5f20f89

- adds a field to SPTEntry where the departure time of the first pt leg is collected @wherbawi 
- adds a check on that field to the pruning criterion, bounded by the end of the requested range

**Comment by michaz** [comment]
<img width="1110" alt="screen shot 2016-12-02 at 12 06 56" src="https://cloud.githubusercontent.com/assets/520916/20831968/e410bdd4-b887-11e6-82fe-96d4b12494df.png">

**Comment by karussell** [comment]
Haha, this looks somehow funny and probably needs a visual upgrade too ;)

BTW: see this completely unrelated nice info: https://opentransportdata.swiss/en/dataset where we could test Realtime (soonish)
