### ISSUE TITLE
point_hint improvement

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#876]
The recently introduced point_hint #846 is really useful if using external geocoding. 

Now assume in an external geocoder a street is called 'Rue Notre-Dame O Montréal' but in OSM it is 'Rue Notre-Dame Ouest' (I do not care who is right here). 

Now the snapping incorrectly picks 'Rue Dupre', see [here](https://graphhopper.com/maps/?point=45.500685%2C-73.560628&point=45.497614%2C-73.561734&point_hint=rue%20Notre-Dame%20O%20Montr%C3%A9al&point_hint=). I wouldn't call it bug but we should investigate if we can improve this. E.g. when calculating the longest common substring we would get 'rue notre-dame' which is a lot longer than 'rue'.

The following tests should pass afterwards:

```java
// point hint
edgeFilter = new NameSimilarityEdgeFilter(new DefaultEdgeFilter(new CarFlagEncoder()), "Rue Notre-Dame O Montréal");
// create fake edge
edge = createTestEdgeIterator("Rue Dupré");
// this must not be true
assertFalse(edgeFilter.accept(edge));

edge = createTestEdgeIterator("Rue Notre-Dame Ouest");
// not necessary, can also fail
assertTrue(edgeFilter.accept(edge));
```

**Comment by karussell** [comment]
Maybe @boldtrn can you have a look at my proposed change?

**Comment by karussell** [comment]
Another possibility we should try is a [Jaro-Winkler implementation](https://github.com/tdebatty/java-string-similarity/blob/master/src/main/java/info/debatty/java/stringsimilarity/JaroWinkler.java) (MIT license) according to the author @tdebatty

**Comment by boldtrn** [comment]
> Maybe @boldtrn can you have a look at my proposed change?

Sure, looks good, also see my comments.

> Another possibility we should try is a Jaro-Winkler implementation

This looks very interesting. Right now I see one problem with this approach. The result is normalized, which means that it is between 0-1. Since we ofttimes compare strings with completely different length, this might lead to a problem, since it will be hard to differentiate between the results.

I created a small test (I preprocesed the strings to create real results) the comments show the results of JaroWinkler, where 1.0 would be perfect:

```
JaroWinkler jw = new JaroWinkler();

        // .95
        System.out.println(jw.similarity("mainstcity", "mainst"));

        // .55
        System.out.println(jw.similarity("ruenotredameomontréal", "ruedupré"));

        // .93
        System.out.println(jw.similarity("ruenotredameomontréal", "ruenotredameouest"));

        // .96
        System.out.println(jw.similarity("laufamholzstraßenürnberg", "laufamholzstraße"));

        // .76
        System.out.println(jw.similarity("kaufamholzstraßenürnberg", "laufamholzstraße"));

        // .72
        System.out.println(jw.similarity("kaufamholystraßenürnberg", "laufamholzstraße"));
```

**Comment by boldtrn** [comment]
Ok, so I came up with an idea. The implementation might not be perfect yet, but the results already look promising, IMHO.

So what I did is using the Jaro Winkler implementation, but I compare it for  every word (basically do a String.split(" ")). Now I compare the shorter array to the longer array and check if every word of the shorter occurs in a Jaro Winkler similar way in the longer array. Right now I ignore the order, so this allows us to compare Strings in the wrong order, but obviously increases the computational complexity.

Let me know what you think about this [commit](https://github.com/boldtrn/graphhopper/commit/89edcf9705126bf6bf817fd843065acb9ff8b46e). This fixes all test cases, as far as I can tell.

**Comment by karussell** [comment]
> Ok, so I came up with an idea

Sounds reasonable

> but I compare it for every word (basically do a String.split(" "))

This limits the approach to certain 'western' languages but is okay now (we just need to be aware of it)

Will have an additional thought about this :)

**Comment by boldtrn** [comment]
> This limits the approach to certain 'western' languages but is okay for now (we just need to be aware of it)

Yes this might an issue. I also thought about comparing the whole point hint with the whole edge name first. If they are not equal, we can do the splitting. WDYT?

Should I clean up my changes and create a PR?

**Comment by boldtrn** [comment]
> Yes this might an issue. I also thought about comparing the whole point hint with the whole edge name first. If they are not equal, we can do the splitting. WDYT?

I just updated my branch a bit, first we compare the whole Strings, if they are not similar, we compare the splittet parts. Right now the approach is not really efficient, which shouldn't be an issue now?

**Comment by tdebatty** [comment]
Hi,
I'dont know what the problem precisely is, but just to clarify, JaroWinkler is quite efficient at detecting a substring with a lot of additional characters:

```
// 0.99
System.out.println(jw.similarity("a short string", "a short string++"));
// 0.89
System.out.println(jw.similarity("a short string", "a short string with some letters"));
// 0.83
System.out.println(jw.similarity("a short string", "a short string with a lot of additional letters"));
// 0.57
System.out.println(jw.similarity("a different string", "a short string with a lot of additional letters"));
```

In the third example, even if the second string is much longer then the first one, JW recognizes the common substring, and gives a high similarity score (0.83).

**Comment by karussell** [comment]
@boldtrn when we talked you said you had some changes pushed - would you mind to create a new pull request (just if it is the case of course :))?

**Comment by boldtrn** [comment]
@karussell Sure sorry :).

**Comment by karussell** [comment]
For now this seems to work relative good with the Jaro Winkler approach ... closing here. Thanks @boldtrn and @tdebatty !
