### ISSUE TITLE
vehicle is listed as a restriction item in foot routing

### ISSUE THREAD

**Issue by miklcct** [graphhopper/graphhopper#877]
In com.graphhopper.routing.util.FootFlagEncoder.FootFlagEncoder(int, double), vehicle is listed as a restriction. This is wrong. On foot means not using a vehicle.

**Comment by karussell** [comment]
Do you have an example where this is a problem?

**Comment by miklcct** [comment]
On Sunday 20 November 2016 04:40:43 Peter wrote:
> Do you have an example where this is a problem?

sorry, it seems this is a duplicate of #752 and I forgot to upgrade my server.
-- 
Sent from KMail

**Comment by karussell** [comment]
Thanks, no problem
