### ISSUE TITLE
Easy way to define route preferences for bike through API and web ui

### ISSUE THREAD

**Issue by grinapo** [graphhopper/graphhopper#88]
This is just preference setting I guess, but noting my observation.

I know there are two kinds of cyclists: one goes for whatever the shortest no matter it's going through a pit of crocodiles and the others possibly prefer routes with less crazy altitude variance, lower traffic, paved ways, so in summary designated cycleways. Myself would prefer going 20% longer on a paved cycleway instead of pedaling in the dirt and mud. ;-)
Possibly a difference between bicycle and mtb. ;-)
Right not GH doesn't seem to prefer cycleway for cyclists.

**Comment by karussell** [comment]
Closing in favor of #193
