### ISSUE TITLE
highways.footway doesn't work with generic weighting for roads

### ISSUE THREAD

**Issue by dlu306090** [graphhopper/graphhopper#881]
Routing through footways doesn't work with generic weighting. (i.e. adding the highways.footway=5 hint to the query doesn't do anything, and any time a route must go through two points that are only near footways, it says "connection between locations not found")

**Comment by boldtrn** [comment]
Should be because the DataFlagEncoder only allows Motorvehicle like access right now?

**Comment by dlu306090** [comment]
Right, is there any way I can change that? I'm trying to create an app that routes for wheelchair users and I want to avoid certain types of paths like steps, so I'd like to set the speed on those to very low.

**Comment by boldtrn** [comment]
> Right, is there any way I can change that?

Sure, the DataFlagEncoder is quite new, so there are a lot of architectural decisions you can make. Right now it is designed for motor vehicles. So we would need a way to mark an edge as eiter motor_vehicle acessible, pedestrian accessible, or both (in your case you might also want to define wheelchar accessible, e.g. try to avoid steps).

Maybe this is possible with the highway value or maybe you need to extend the access value or even a new value?

Hope this helps? Keep us updated and feel free to create a PR for you changes :)

**Comment by dlu306090** [comment]
I'm a bit confused on how to do that -- so currently the DataFlagEncoder is set to encode only the car's maximum forward and backward speeds, right? So what I need to do is create a footFwdMaxspeedEncoder and footBwdMaxspeedEncoder and add it to the defineWayBits function, change some other places as necessary, and then call DataFlagEncoder with the accessType "foot" instead of car from GenericWeighting, right? I've changed the files, and but they don't seem to be working. I also don't know where the type of routing is set (car vs. foot except it seems that in the GraphHopper main file, there's a line that says "encodingManager.supports(vehicle);". Currently when I try to run it I can't seem to route on footways at all.

Can you take a look at this and see if I'm doing something wrong or if there are things I've left out? https://github.com/graphhopper/graphhopper/compare/master...dlu306090:master

Thanks!

**Comment by boldtrn** [comment]
@dlu306090 Took a brief look at your branch. The basic approach is correct, I think. You have to set foot  speeds for every edge that you want to allow, not just footways. For a more detailed approach on how to do this, see the FootEncoder. You also have to check for things like sidewalk, and so on. Then you have to setup access for vehicle and for foot, these are two different encoders, I think. We need a request parameter, that states something like transport_mode=foot|car, that does not exist yet. In the GenericWeighting you could then use the different encoded values. That would be probably be my approach.

**Comment by boldtrn** [comment]
Just had a second thought. Maybe it would be easiest for you to just assume the same speed for all edges that are accessible, for example make every edge 5km/h (might be a bit fast on average, especially with a wheelchair). For now just care about accessibility. So basically you need to find out if a way is accessible by pedestrians, if yes set it as acessible, don't set a speed for now. In the GenericWeighting, remove the sppeed for now and only return distance if accessible by pedestrians. I think that will be the fastest approach. Once that works, you can improve. By using all different kinds of speeds and other fancy stuff.

**Comment by dlu306090** [comment]
Thanks for the quick response! So I would write a separate FootFlagDataEncoder and a separate CarFlagDataEncoder? When you say "request parameter," where would that go? Why would we need one if we have two separate encoders and I could just create the respective encoder when I want to enable a specific transport mode? Also, I've currently enabled foot encoding in GenericWeighting but it doesn't work, and I can't seem to figure out why. I suspect it's because setting which encoding is used isn't done in these files? I will eventually add speeds for all the types of edges and sidewalks I want, but I'm currently only trying to make routing on footways work.

When you say "set it as accessible," is that the "ACCESSIBLE" macro you added 6 days ago? I thought that was something else, since it was in response to another problem, but I just wanted to make sure.

**Comment by boldtrn** [comment]
> So I would write a separate FootFlagDataEncoder and a separate CarFlagDataEncoder?

No, we have that already ;). I think the DataFlagEncoder's purpose is to reflect the Data of for example the OsmWay. The weighting would then on the fly "decide" what the weight for the given transportation mode and situation would be.

> When you say "request parameter," where would that go?

I'd put it in the URL.

> Why would we need one if we have two separate encoders and I could just create the respective encoder when I want to enable a specific transport mode?

The idea of the DataFlagEncoder and GenericWeighting is to get rid of all the different Encoders and move more logic into the Weighting.

> I suspect it's because setting which encoding is used isn't done in these files?

I believe the reason for this is that you have not correctly set and read the access and speed properties in the encoder, as described above.

> I will eventually add speeds for all the types of edges and sidewalks I want, but I'm currently only trying to make routing on footways work.

Not sure if there are enough footways available to navigate from A to B, I personally doubt that, for OSM data in general.

> When you say "set it as accessible," is that the "ACCESSIBLE" macro you added 6 days ago?

Yes, related to that. In the GenericWeighting we are checking if an Edge is accessible, if not we add a lot of weight to it, so it won't be taken. You have to make sure that the ways you want to use are accessible.

Anyway, if you only want a fast solution, just use the FootFlagEncoder and FastestWeighting. You will have a working solution straight away and just need to modify it for Wheelchairs.

**Comment by dlu306090** [comment]
Hmm...so my understanding was that the reason I'd use DataFlagEncoder and GenericWeighting is because I want the option for users to select which types of paths they want to avoid, and DataFlagEncoder maintains the tags of the OSMWay after processing, whereas FootFlagEncoder doesn't. So I could technically modify FootFlagEncoder for Wheelchairs, but I wouldn't be able to make things dynamic inside the app, right?

**Comment by boldtrn** [comment]
Exactly, if you want that, you have to use the DataFlagEncoder.

**Comment by dlu306090** [comment]
So I tried to change just the FootFlagEncoder but that seems not to work either. (i.e. taking out safeHighwayTags.add("steps"); and putting in avoidHighwayTags.add("steps"); does nothing.) Would you have any idea why?

**Comment by dlu306090** [comment]
Actually I just realized that commenting out the whole file FootFlagEncoder.java also does nothing; when I run ./graphhopper.sh web new-jersey-latest.osm.pbf everything is still fine. Now I'm really confused - if the graph.flag_encoders=foot in config.properties, isn't it supposed to use the FootFlagEncoder.java file?

**Comment by boldtrn** [comment]
Probably you have to run ./graphopper.sh web clean first. Also another issue is that if you want to change the graph you also have to delete the new-jersey-latest.osm folder for every start. This will read the osm file  and generate the graph. Also I would setup an IDE to do the build process. Have a look at the docs, everything should be there :).

**Comment by karussell** [comment]
This should be now possible with the CustomWeighting (DataFlagEncoder was removed)
