### ISSUE TITLE
Android sample: Quick scale vs Long press

### ISSUE THREAD

**Issue by devemux86** [graphhopper/graphhopper#882]
In Android sample (with [VTM](https://github.com/mapsforge/vtm)) performing the quick scale (double tap + swipe) gesture activates also the long press event on map events receiver, which we use for setting the waypoints.

It's a VTM issue, see https://github.com/mapsforge/vtm/issues/250, I just pushed the fix.
Let's record it for Android sample too in case users wonder (don't know if it's fixable outside).

Sorry @karussell for the after release fix.. :slightly_frowning_face:

**Comment by karussell** [comment]
> Sorry @karussell for the after release fix.. :slightly_frowning_face:

No need to sorry - thanks :) !

**Comment by karussell** [comment]
Is this fixed in your latest vtm release?

**Comment by devemux86** [comment]
I have not made another VTM release, current version is [0.6.0](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.mapsforge%22).

But it's [fixed](https://github.com/mapsforge/vtm/issues/250) in `master-SNAPSHOT`, I'm thinking to proceed with a release soon. :slightly_smiling_face:
