### ISSUE TITLE
Make integration tests work on Travis

### ISSUE THREAD

**Issue by michaz** [graphhopper/graphhopper#896]
Travis currently can't handle our RNV scenario.

I *could* slim it down, but on the other hand, we already have other interesting things to run regularly, automatically, like the diagram generated from @highsource's data.

On what infrastructure can we run automated tests or test-like things which need more computing resources?

**Comment by michaz** [comment]
(There'll definitely be actual tests in the end which *do* run on Travis, that goes without saying.)

**Comment by karussell** [comment]
We could be run this on our infra machine where our current performance tests are executed on.

**Comment by michaz** [comment]
I still don't see what Travis' problem is. The whole process takes way under 1GB on my machine, and the limit on Travis is supposedly 3GB.

**Comment by karussell** [comment]
> The whole process takes way under 1GB on my machine

I think we also have a maven memory limit set for unit tests in the pom.xml somewhere to 200mb (?) ... but maybe it got killed by their container management infrastructure due to heavy CPU utilization?

**Comment by michaz** [comment]
OK, with 77f2a49 I fixed a genuine performance problem with graph building, and with a5779b0 I am Ignoring the single test which now still fails (loading both GTFS feeds at the same time).

**Comment by karussell** [comment]
What exactly was the reason? Or when is the graph storage empty?

**Comment by michaz** [comment]
The graph storage is empty at that point when no OSM files are loaded.

**Comment by karussell** [comment]
How is location lookup handled if the location index is empty? Or is it chained and first tries a pt index and then OSM?

**Comment by michaz** [comment]
It's not *the* location index, it's *a* location index which I am using for intermediate computation (putting stops on the roads).

**Comment by karussell** [comment]
Is it [here](https://github.com/graphhopper/graphhopper/commit/7be9ec05ba3ab35ded6a7f925d3d85f380760d5c#diff-f4e1576ea76bb491169a1a529f21ec28R63) where we put stops on the roads?

**Comment by michaz** [comment]
Yeah. Not in the middle of roads, though. Just connect them to junctions. I haven't started looking into splitting edges in ``GraphHopperStorage`` yet.

**Comment by karussell** [comment]
> I haven't started looking into splitting edges in GraphHopperStorage yet.

That is a current limitation if necessary *after* import. So in general the storage is append only (i.e. just an array) and we would have to implement kind of a garbage collection but changing edgeIds can introduce problems like in #911

**Comment by karussell** [comment]
To close here I would prefer to use a different maven profile for travis (which excludes the one integr. test) and the default profile should include all integration tests.

**Comment by michaz** [comment]
Done, not with profiles but similar.

**Comment by karussell** [comment]
A link for future reference: https://github.com/graphhopper/graphhopper/commit/2a621f4dee90b9d78bffb601bb182730b21828fc
