### ISSUE TITLE
creating graph for android

### ISSUE THREAD

**Issue by martinschaller** [graphhopper/graphhopper#9]
I used the OSMReader (osmreader.graph=sg-sh osmreader.osm=malaysia_singapore_brunei.osm osmreader.size=5000000 osmreader.dataaccess=mmap) to create a graph for android.
But if I want to use this graph with GraphHopper I'm getting following error:
"D/RouteCalculation(2119): An error happend while creating graph: Cannot load the graph - it wasn't create via com.graphhopper.storage.LevelGraphStorage! sdcard/graphhopper/singapore-gh/"

**Comment by zhiqiangZHAO** [comment]
It seems the sortGraph only sort the nodes, the order of edges won't be touched. Is it right?

I noticed the comments
    /**
     * Sorts the graph according to depth-first search traversal. Other traversals have either no
     * significant difference (bfs) for querying or are worse (z-curve).
     */
Do we have an explanation why DFS helps?

**Comment by karussell** [comment]
> It seems the sortGraph only sort the nodes, the order of edges won't be touched. Is it right?

We recreate the entire graph, so both are sorted.

> Do we have an explanation why DFS helps?

Not really - I would have expected BFS. Still some paper mention DFS too.

**Comment by zhiqiangZHAO** [comment]
Thanks!
I re-read the code. For edges, I think the order is kept. Only skip some invalid edge.
For nodes, it's totally re-sorted.

And this change would only improve latency for single thread query? Or it's also valid for multi-thread server scenario?

I assume the change is make the geographical nearby data also close inside disk/memory. So there is high chance the connected edge data is already in high speed cache. Is it right?

**Comment by zhiqiangZHAO** [comment]
Hi Karussell,

Sorry I am still not very clear. Below is the code I looked:
AllEdgesIterator will iterate edge from the beginning to the end.
looks like the below code only read all the edges then translate the nodeID to new nodeID and store the new edge in another graph. So I thought the edge order are kept except some empty entries might be skipped.

static Graph createSortedGraph(Graph fromGraph, Graph toSortedGraph, final IntIndexedContainer oldToNewNodeList) {
        AllEdgesIterator eIter = fromGraph.getAllEdges();
        while (eIter.next()) {
            int base = eIter.getBaseNode();
            int newBaseIndex = oldToNewNodeList.get(base);
            int adj = eIter.getAdjNode();
            int newAdjIndex = oldToNewNodeList.get(adj);

            // ignore empty entries
            if (newBaseIndex < 0 || newAdjIndex < 0)
                continue;

            eIter.copyPropertiesTo(toSortedGraph.edge(newBaseIndex, newAdjIndex));
        }

**Comment by zhiqiangZHAO** [comment]
Hah, usually each CPU core has its own high-speed cache. So the improvement should also work for server scenario. I still feel a little strange. I think the Hilbert curve should works, too. Or even better.
