### ISSUE TITLE
Calculate fares for found solutions

### ISSUE THREAD

**Issue by michaz** [graphhopper/graphhopper#905]

**Comment by michaz** [comment]
An analysis of the problem is here:

http://blog.transittimesapp.com/gtfs-fares/

**Comment by michaz** [comment]
I am looking for a dataset with non-trivial fare information. The German ones, of course, don't have any.

**Comment by michaz** [comment]
Found one:

https://transitfeeds.com/p/trimet/43

**Comment by michaz** [comment]
I test-based-developed all examples from https://code.google.com/archive/p/googletransitdatafeed/wikis/FareExamples.wiki

The result looks more like a separate project than like a part of graphhopper-pt, it doesn't share *any* code with it. Maybe instead of merging it, just pull it out and include it from the web project so the web site can calculate the fares.

Not real-world-data-tested yet.

**Comment by karussell** [comment]
> The result looks more like a separate project than like a part of graphhopper-pt, it doesn't share any code with it.

Ok, sounds reasonable.

**Comment by michaz** [comment]
Implement fare lookup according to GTFS. Make a first try with optimizing for fare.

**Comment by michaz** [comment]
Fare is now (4a12566) being calculated based on GTFS fare rules and included in the response.
