### ISSUE TITLE
Allow to return turn instructions without street names

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#913]
Right now GH returns the translated instruction like "Turn Left onto <Road Name>". However, there are cases when a user only wants to get simple instructions like "Turn Left", "Turn Right". Currently, this is achievable with GH parsing either the String or the sign and create turn instructions using a local TranslationMap. 

Thus, I propose to add a request parameter that allows showing or hiding the street name in the instruction list.

WDYT?

**Comment by karussell** [comment]
What would be a use case behind this?

**Comment by boldtrn** [comment]
Having simpler/shorter turn instructions. One reason would be space. 

For example I want to create a condensed turn instruction list, containing the symbol and the instruction, without the street name.

**Comment by karussell** [comment]
You could combine the sign with the simple instruction string?

**Comment by boldtrn** [comment]
> simple instruction string?

What do you mean by simple instruction string?

Right now an instruction looks like this:
```
distance: 911.477,
sign: -2,
interval: [
19,
27
],
text: "Turn left onto K 3955",
time: 65624
```

**Comment by devemux86** [comment]
I think this happens due to [Instruction.setUseRawName](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/util/Instruction.java#L60) called in e.g. [GraphHopperWeb](https://github.com/graphhopper/graphhopper/blob/master/web/src/main/java/com/graphhopper/http/GraphHopperWeb.java#L150).
That forbids to use properly the [Instruction.getTurnDescription](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/util/Instruction.java#L228) for more customization.

An idea could be to replace the `setUseRawName()` with `setUseRawName(boolean)` allowing users to enable / disable this feature.

**Comment by karussell** [comment]
Ah, yes. In the web UI this is not possible but via Java API it should via calling the translation map without the street name.

**Comment by devemux86** [comment]
Hmm even in directions-api it's not possible as the `setUseRawName()` cannot be undone, or you mean something different?

**Comment by karussell** [comment]
I mean just calling the translationMap.tr("turn_left") etc depending on the returned "sign".

**Comment by devemux86** [comment]
Ah yes already doing that! :slightly_smiling_face:

**Comment by boldtrn** [comment]
> Ah, yes. In the web UI this is not possible

We could add the turn translations to the web translations. This way this could be also done in the web UI.

**Comment by devemux86** [comment]
>You could combine the sign with the simple instruction string?

I'm afraid that doesn't work correctly for all instructions.
Roundabout can return 2 instructions depending on `exited` flag.
And `RoundaboutInstruction` from `InstructionList` has always `isExited() = false` (so we get `roundabout_enter`). :confused:

**Comment by boldtrn** [comment]
> Getting RoundaboutInstruction from InstructionList has always isExited() = false (returns only roundabout_enter)? :confused:

Maybe we have to use the `Instruction.LEAVE_ROUNDABOUT` instruction sign in this case? So this might be an issue of the route serialization? 

As a workaournd you might be able to use the `exit_number` to recognize exit instructions as seen [here](https://github.com/graphhopper/graphhopper/blob/afe285559640259c47a50cc5fd5ea7fecc896dae/web/src/main/java/com/graphhopper/http/GraphHopperWeb.java#L125)?

**Comment by devemux86** [comment]
>As a workaournd you might be able to use the exit_number to recognize exit instructions as seen here?

Nice idea but checking the two variables, we always have `exited = false` and `exitNumber > 0`, regardless if the route ends in roundabout (should be `roundabout_enter`) or route exits roundabout (should be `roundabout_exit`).

**Comment by boldtrn** [comment]
> Nice idea, but checking the two variables, we always have exited = false and exitNumber > 0, regardless if the route ends inside roundabout (should be roundabout_enter) or route exits roundabout (should be roundabout_exit).

Ok, that is unfortunate, in this case I vote for using the `Instruction.LEAVE_ROUNDABOUT` instruction. Is there a reason we do not use it yet @karussell? Otherwise I could add a PR?

**Comment by karussell** [comment]
I do not know a reason except that we also need client support then and not sure how existing clients behave with an unknown sign

**Comment by devemux86** [comment]
The problem exists with web implementation, things seem working fine with regular java client.

Checking the two variables in java client, we always have `exitNumber > 0` (even with no exit!), but at least the `exited` variable has correct value depending if the route ends inside roundabout or route exits roundabout.

So shouldn't we focus to fix (with existing signs) why specifically on web this behavior exists?

**Comment by boldtrn** [comment]
I was just thinking about this issue. How about the inverse of the stated problem? If I want to get only the street name and not the turn description? A use case could be that I only want to show the street name and not the turn description as I can show the symbol next to the turn description.

The benefit of implementing this would be that the clients can create Instruction objects that behave the same as with an offline graph. For example use the Instruction.getName() method. When using this method with the curent client, this return the turn description + name, when using this method with an offline graph it returns the street name.

So I think it would be nice to return two fields for the instruction `turn_description` and `street_name`. This would not break current client implementations, IMHO.

WDYT, does this make sense?

**Comment by devemux86** [comment]
Nice thought @boldtrn, currently in instructions web client behaves differently than offline client and that confuses the user, effectively limiting the options in web development.
It'd be nice if it could be more flexible like with offline graphs.

**Comment by karussell** [comment]
I agree with the street_name and it was also already request, but the turn_description is already separate via the 'sign' (?)

**Comment by devemux86** [comment]
Probably @boldtrn means to have in `turn_description` only the instruction without street name?
(in order to avoid creating instructions from the sign if server's ones are not sufficient enough)

**Comment by karussell** [comment]
What do you mean with not sufficient? Wouldn't the I18NServlet help with the strings?

**Comment by devemux86** [comment]
I mean like discussed [above](https://github.com/graphhopper/graphhopper/issues/913#issuecomment-267810755), that web instructions are fixed with street names and if developer wants to change them, they have to be re-created via their sign.
It's certainly doable, just needs more steps. :slightly_smiling_face:

**Comment by boldtrn** [comment]
> I agree with the street_name and it was also already request, but the turn_description is already separate via the 'sign' (?)

Oh yes sorry. This was mostly about: "how to get only the street name". You are right that we can handle turn instruction via sign.
