### ISSUE TITLE
Implement block_id (staying in a vehicle which goes on another trip)

### ISSUE THREAD

**Issue by michaz** [graphhopper/graphhopper#919]

**Comment by michaz** [comment]
Will probably be implemented as

- an exclusion from the usual transfer rule (does not get a transfer penalty)
- a special instruction ("stay in vehicle, which continues as X towards Y")

Related: #922

**Comment by karussell** [comment]
Not sure if you are still looking for an example for this :) But I think I found something like this in the first route here (VBB+OSM):

http://localhost:5000/?point=52.484453%2C13.311996&point=52.517892%2C13.441772&vehicle=pt&earliestDepartureTime=2017-02-06T09%3A34&layer=OpenStreetMap

S42+S42+U5 but it should be just S42+U5

**Comment by michaz** [comment]
82da121

**Comment by michaz** [comment]
Stay-in-vehicle-transfers must:

- Count as "no transfer" for the solver (so that it dominates solutions with a 'real' transfer which are slower)
- Still produce two PtLegs, because as far as the data model is concerned, we are on another trip with a different id

How this should be displayed to the user (or converted into Instructions) is probably instance-specific, I'm afraid:

In the example by @karussell it should not produce an instruction. For the user, this is just the same S-Bahn.

But there are cases where the bus really makes a turn, changes the head sign and makes an announcement like "Terminus. If you want, you can stay on the bus, but this is a new trip.", and that should produce an instruction.

We can't tell these cases apart from the outside.

For now, we don't give an instruction. :)

**Comment by karussell** [comment]
> We can't tell these cases apart from the outside.
> For now, we don't give an instruction. :)

:+1:
