### ISSUE TITLE
Implement gtfs-realtime

### ISSUE THREAD

**Issue by michaz** [graphhopper/graphhopper#923]
It should be feature-complete, but can otherwise be _completely_ naive, like having a list of all current issues next to the real graph and looking at it at every node.

Then start optimizing from there.

**Comment by michaz** [comment]
Skipping stops is now working.
Next: Delays, including missing transfers.
With that, I would call it a viable prototype already.

**Comment by AAAstorga** [comment]
Hello @michaz! Is there any updates on this. We are looking to use graphhopper as our routing solution, but we would like to implement realtime-gtfs data. 

Thanks!

**Comment by michaz** [comment]
> Next: Delays, including missing transfers.

This works as of yesterday. On at least one dataset. ,-)

**Comment by AAAstorga** [comment]
Awesome! Do you have any documentation on how to use a real-time GTFS feed? Would love to implement it!

**Comment by michaz** [comment]
@AAAstorga Wow, thank's for your interest! :-) At the moment, I can only refer you to the [trimet branch](https://github.com/graphhopper/graphhopper/tree/trimet), which is the test instance I am developing [here](http://d3ko6ohfm7cdx2.cloudfront.net/).

Totally alpha (**do not take the performance seriously**, the thing currently polls the real-time feed from the operator _per request_!), but perhaps a starting point if you're going to set up your own instance?

**Comment by michaz** [comment]
This is now feature-complete, up to lots of testing and verifying that all features work in both search directions and such.

**Comment by karussell** [comment]
Wow, congrats :+1: !

**Comment by AAAstorga** [comment]
This is awesome! Is there any documentation on how to use it? 

Woo!

**Comment by wcypierre** [comment]
Looking for the documentation as well
