### ISSUE TITLE
Bad request when using ch.disable with certain point(s)

### ISSUE THREAD

**Issue by webdevilopers** [graphhopper/graphhopper#930]
So far I've been using the `ch.disable` option set to `true` for `weighting=short_fastest` successfully with all points.

Recently I've been using this ending point:
> https://graphhopper.com/api/1/route?point=53.24043035,7.9338984237623&amp;point=51.0402452,13.7320768&amp;ch.disable=true&amp;weighting=short_fastest&amp;key=...&amp;vehicle=truck&amp;locale=de&amp;debug=true&amp;type=json&amp;instructions=false&amp;calc_points=false

And it suddenly throws:
> Warning: file_get_contents ... failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request

Any idea why this happens with these coordinates? They are the result ofquerying the Geocoder for `01067 Dresden` using the first hit.

If I remove the `&amp;ch.disable=true&amp;weighting=short_fastest` part it works just fine.

**Comment by karussell** [comment]
Please use our forum for questions: [GH Directions API](https://discuss.graphhopper.com/) or [GH](https://discuss.graphhopper.com/c/graphhopper)

**Comment by webdevilopers** [comment]
Sorry @karussell , normally I would use the forum. But my approach seems to be absolutely correct and works with all other points I had so far.

It just fails with these coordinates and setting `ch.disable=true&weighting=short_fastest`.

If I remove the `weighting` only using `ch.disable=true` I even get an Java exception:
> resulted in a `400 Bad Request` response:
{"message":"Bad Request","hints":[{"details":"java.lang.IllegalArgumentException","message":"No path found due to maximu (truncated...)

Are you sure this is no issue? Could you try with your API keys?

**Comment by karussell** [comment]
The points are too far away. This is a current limitation of the Directions API and not related to the software itself.

BTW: Are you truncating this or is there is problem with too early truncating? The full error message reads: [No path found due to maximum nodes exceeded](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/routing/template/ViaRoutingTemplate.java#L134)

**Comment by webdevilopers** [comment]
Truncating comes from Symfony Exception, yes @karussell .

Thanks for clearing this up! Is this documented anywhere?

I hoped there is a parameter to pass to the query that would only calculate the starting and ending point e.g. `instructions=false&amp;calc_points=false`. But this won't help, right? Any other workaround?

**Comment by karussell** [comment]
> Thanks for clearing this up! Is this documented anywhere?

Indeed this is missing.

> I hoped there is a parameter to pass to the query that would only calculate the starting and ending point 

What do you mean? The parameters you used should return just distances and times of the route.
