### ISSUE TITLE
Too many property objects

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#940]
The current state is a bit confusing. We have AlgorithmOptions, PMap (`Map<String, String>`), HintsMap (extends PMap) and ConfigMap (`Map<String, Object>`). Maybe we can merge PMap and ConfigMap somehow and also AlgorithmOptions with HintsMap?

**Comment by boldtrn** [comment]
Would be highly appreciated. I stumbled over that a couple of times as well :).

**Comment by karussell** [comment]
With #1078 ConfigMap is removed

**Comment by karussell** [comment]
With #1934 HintsMap is removed
