### ISSUE TITLE
Destination does not snap correctly to road

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#948]
Something is wrong here (or just junction to junction routing?) - using VBB public transport routing and brandenburg for the walking network:

![pt-snap-to-road](https://cloud.githubusercontent.com/assets/129644/22653673/703f59ba-ec8a-11e6-95d0-0e04fc629e9e.png)

http://localhost/?point=52.498459%2C13.320751&point=52.532393%2C13.427573&locale=de&vehicle=pt&weighting=fastest&elevation=false&ignoreTransfers=true&earliestDepartureTime=2017-02-06T15%3A01&use_miles=false&layer=OpenStreetMap

The start is okay (probably because of being 100% in the walking network)

**Comment by michaz** [comment]
Ah, no, not junction-junction-routing. Just an improperly terminated instruction list.

**Comment by karussell** [comment]
Cool, thanks!

Can we somehow ensure this in a unit test?
