### ISSUE TITLE
Use JTS for polygon and geometry related work

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#956]
We should not reinvent the wheel and also JTS will be soon under the EPL or EDL: https://github.com/locationtech/jts

**Comment by devemux86** [comment]
Like a core dependency?

**Comment by karussell** [comment]
Yes, highly likely we need this at some point in the core. Not sure if it is avoidable and/or necessary to avoid it.

**Comment by boldtrn** [comment]
+1 for not reinventing the wheel. I think the lib is already under dual licensing EDL/EPL. Not an expert on the license details. Is this compatible with Apache2 without restricting use cases?

**Comment by karussell** [comment]
> Is this compatible with Apache2 without restricting use cases?

As the one is like MIT it should be compatible, but have not read the details.

**Comment by karussell** [comment]
#1039
