### ISSUE TITLE
Too many weights were maxed out. Use a bigger factor

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#960]
I was just playing around with the new landmark algorithm. While doing so, I received an interesting log: 
```
landmark 0 -> too many weights were maxed out (1065332/1065333). Use a bigger factor 1.8212685272742498E-4
```

This log was shown twice for all 16 landmarks. The distance heuristic of this weighting is not very good, so my minWeight is rather small. I don't want to change the minWeight, as this might break the a_star. AFAIK this is the only way to change the factor?

The routing for this particular weighting is not faster with landmarks, where it is a lot faster for other weightings I tested.

Is there a way to fix this?

**Comment by karussell** [comment]
Yes, this factor is rather bad in your case. 

> The routing for this particular weighting is not faster with landmarks, where it is a lot faster for other weightings I tested

The factor is indeed approximated via the minWeight value. Instead we more need a maxWeight value for this factor and so I did minWeight*X which seems to fail here. Configuring the factor is a good idea in such cases or some new maxWeight method ...
