### ISSUE TITLE
PointOutOfBoundsException on a sample project

### ISSUE THREAD

**Issue by nselimko** [graphhopper/graphhopper#964]
For general questions or discussion about GraphHopper, please use our [forum](https://discuss.graphhopper.com).

Before creating an issue make sure to read our [contributing guide](https://github.com/graphhopper/graphhopper/blob/master/.github/CONTRIBUTING.md).

The best way to get help about an GraphHopper issue is to create a valid and detailed issue content, preferable with a unit or integration test reproducing the issue. Please include the version of GraphHopper, the JVM and the operating system are you using and in case of a routing problem include a link to [GraphHopper Maps](https://graphhopper.com/maps/). Also tell us your expected routing result via additional markers and screenshots.

If you have an Android application using GraphHopper, please **always** post to the [forum](https://discuss.graphhopper.com/c/graphhopper/graphhopper-ios-and-android) before and include logs and the version of your Android.

**Comment by nselimko** [comment]
Hi,
I followed all the instructions in documentation for Android.
I downloaded the sample project and build it,everything is good,but when i want to draw a route between two points it returns PointOutOfBoundsException.
I downloaded Kosovo map.
My doinBackground code looks like:

 protected PathWrapper doInBackground(Void... v) {

                try
                {

                StopWatch sw = new StopWatch().start();
                GHRequest req = new GHRequest(fromLat, fromLon, toLat, toLon).
                        setAlgorithm(Algorithms.DIJKSTRA_BI);
                req.getHints().
                        put(Routing.INSTRUCTIONS, "false");

                    hopper.setGraphHopperStorage(graphHopperStorage);
                GHResponse resp = hopper.route(req);
                time = sw.stop().getSeconds();
                return resp.getBest();

                }
                catch (Exception e)
                {
                    return  null;
                }
            }

Can anybody help ?

**Comment by karussell** [comment]
As you already wrote: please ask in our forum :)
