### ISSUE TITLE
Cannot correctly build SpatialRuleIndex

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#965]
I just found an ugly bug with the way we [initialize the SpatialRuleLookupBuilder in the DefaultModule](https://github.com/graphhopper/graphhopper/blob/e085c0b3f3b1e8a3b5942d0938218bec40a357f3/web/src/main/java/com/graphhopper/http/DefaultModule.java#L109). The problem is that at this point the graph is not loaded, therefore we cannot get it. Getting the bounds in advance is probably not possible.

For a quick fix, we could simply define the bbox in the config.

The usage itself is a bit inconvenient as well.
You have to define the location of the json file, the number of spatial rules the encoder contains, (and the BBox).

Maybe it would make more sense, to define the names of the SpatialRules by hand? This would remove the need to define the BBox and the number of SpatialRules.

Currently, the usage SpatialRuleIndex is not documented. When fixing this issue and testing if it works, we should document the process, as well.

WDYT?

**Comment by karussell** [comment]
We can also overload the GraphHopper class on do this stuff when the import was done like we do for landmarks too

> Maybe it would make more sense, to define the names of the SpatialRules by hand? This would remove the need to define the BBox and the number of SpatialRules.

What do you mean here?

> Currently, the usage SpatialRuleIndex is not documented. When fixing this issue and testing if it works, we should document the process, as well.

Good idea, yes

> You have to define the location of the json file, the number of spatial rules the encoder contains, (and the BBox).

But we require also these things, no? We need a geojson and the spatial rules. To make the latter a bit more generic we should implement this via reflection in the web module (to avoid reflection in the core) and this way we also have the number of rules.

**Comment by boldtrn** [comment]
> We can also overload the GraphHopper class on do this stuff when the import was done like we do for landmarks too

Is this possible in this case? The problem is that we need the SpatialRuleLookup to exist when we import the edges. So maybe it would be possible to calculate the BBox before importing the edges. Once the graph is imported, we can init the SpatialRuleLookup like we do for LM.

> But we require also these things, no? We need a geojson and the spatial rules. To make the latter a bit more generic we should implement this via reflection in the web module (to avoid reflection in the core) and this way we also have the number of rules.

Yes exactly. We could even estimate the BBox from the selected rules. They have borders and we can just use the outer borders of the rules as BBox. This might not be  perfect if you actually need only a smaller area, but for these cases it might be ok to pass the BBox via the config.

**Comment by karussell** [comment]
Oh, you are right. Those dependencies are ugly. I agree completely: 

> We could even estimate the BBox from the selected rules. They have borders and we can just use the outer borders of the rules as BBox. This might not be perfect

Hmmh...

**Comment by michaz** [comment]
Isn't the more general solution to this to construct ``GraphHopper`` more linearly, i.e. construct everything you need in the correct order and pass it into each other's constructors?

Meaning, get rid of the pattern: ``GraphHopper`` has super-many protected methods which must be overloaded if you want to change something, but you always have to keep initialization order in mind? A bit like I'm trying in the pt branch?

I don't want to be negative, but I'm not sure building a hand-rolled, reflection-based dependency-resolution thing is sustainable... :-/

**Comment by michaz** [comment]
For example: Ideally, a ``SpatialRuleLookup`` instance should only _exist_ when I can actually look up spatial rules on it. A ``GermanySpatialRule`` instance should only _exist_ when it knows what Germany is. How should I know that it knows the speed-limits after construction, but has to be told the borders afterwards? From the interface, it could just as well be the other way round, or both, or none.

**Comment by karussell** [comment]
> and pass it into each other's constructors?

That is also possible, yes: 

new GraphHopper().setEncodingManager(new EncodingManager(new DataFlagEncoder().setSpatialRuleLookup(lookup))).init(args)

But the reflection I'm indeed no longer sure if this is necessary. The idea was that someone else could build a new gh with her classes bundled and automatically used. A similar idea we had initially for FlagEncoders and throw away due to problems on Android&iOS.

> GraphHopper has super-many protected methods which you must overload if you want to change something, but you always have to keep initialization order in mind, which is hard, because it is not really specified and could change any time any one refactors the superclass?

Yes, extendability is definitely something we have to change somehow. Also the GraphHopper class does probably too many things and we have to split it into initial import, algo preparations (kind of separated already), change feeding and query (map matching, one-to-one, ...).

> because I couldn't even figure out what depends on what in a starting GraphHopper because so many things are mutable

Yes, mutability is another weakness/laziness in GraphHopper and we should step by step introduce builders where important.

> Why should it know speed-limits at creation time, but need to be told the borders later, except that this happens to be the order in which stuff is loaded?

That is indeed true (if I understand this correctly) and we should address this in this issue. @boldtrn : to address this the problem I guess is that we store the borders in json and would need a json lib in the core to load it directly at creation time?

**Comment by boldtrn** [comment]
> But regarding the reflection stuff I'm indeed no longer sure if this is necessary. The idea was that someone else could build a new gh with her classes bundled and automatically used.

Why shouldn't we need this anymore? 

> to address this the problem I guess is that we store the borders in json and would need a json lib in the core to load it directly at creation time?

Exactly. Having a json lib in the core would make this very easy. The problem is that we have to "inject" the implementation from outside the core.

**Comment by devemux86** [comment]
> Having a json lib in the core would make this very easy.

Wouldn't it be more convenient we had extension modules (like readers), so not overloading the core with dependencies?

**Comment by michaz** [comment]
> But regarding the reflection stuff I'm indeed no longer sure if this is necessary. The idea was that someone else could build a new gh with her classes bundled and automatically used. A similar idea we had initially for FlagEncoders and throw away due to problems on Android&iOS.

Yeah. The trend in server software seems to be that command line arguments and config files are going away, and that your main-method or startup script _is_ your configuration. Similar to what happened to web servers and Servlets.

Yesterday:

web.xml (fantasy version):
```
<server>
<servlet>
com.wurst.MyServlet
</servlet>
<configuration>
<port>
8080
</port>
</configuration>
</server>
```
start-web-server.sh my-web-project.war

_(reflection-based stuff happens)_

Today:

```
public static void main() {
  Server server = Server.builder().port(80).service(new MyService()).build();
  server.start();
}
```

So I would say that when I'm able to create a ``GraphHopper`` and give it a couple of SpatialRules, in code, that may often be enough.

**Comment by karussell** [comment]
I agree. Still GraphHopper web module is a bit different and we need to support people without Java experience. But when someone is able to change a SpatialRule then we can assume knowledge in Java (and no need to make injecting stuff 'configurable').

@boldtrn it is relative easy to start the GHServer with your own GraphHopper instance. Do you know how or should we include this in the documentation? This way we can avoid the reflection stuff, which is indeed too dirty.

**Comment by karussell** [comment]
> Wouldn't be more convenient having extension modules (as in readers), so not overload the core with dependencies?

Yes and no. Having json in the core would make things sometimes easier but maybe it does not really belong there.

**Comment by boldtrn** [comment]
This should be fixed by now.
