### ISSUE TITLE
prepare.lm.done overwritten on load graph

### ISSUE THREAD

**Issue by devemux86** [graphhopper/graphhopper#968]
The `prepare.lm.done` property appears to be overwritten in [GraphHopper.loadOrPrepareLM](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/GraphHopper.java#L1181) during loading a landmark graph.

The graph properties file has the correct enty `prepare.lm.done=true`.
Reading directly the properties file, the property comes with right `true` value.
But if loading the graph and use the `getProperties()` to retrieve it, then the property comes `false`.

This is probably due to `tmpPrepare` being `false`.

**Comment by karussell** [comment]
Okay, we should do this 'done=true' only if it did some work. The difference here to CH is that CH data is loaded with the graph and for LM we need to load it separately if it was already created.
