### ISSUE TITLE
Estimate lm.maxweight

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#969]
See #963. 

Maybe we can calculate the average maxedout value and show that here (or max maxedout?)?

We can determine the maximum weight ourselfs and add 50%. Would be a heuristic approach, but maybe more convenient for new users.

**Comment by karussell** [comment]
:+1: 

> We can determine the maximum weight ourselfs and add 50%. Would be a heuristic approach, but maybe more convenient for new users.

We already do that in the issue :)

**Comment by boldtrn** [comment]
> We already do that in the issue :)

Oh, you are right, I missed that, sorry.

**Comment by karussell** [comment]
Currently it just picks the last found maxed out value ... not sure if this is the best strategy but probably sufficient for now.

**Comment by boldtrn** [comment]
Ok, so I will leave it open. We can still close it when we don't see any issues with the current approach.

**Comment by karussell** [comment]
After #1080 is merged this is no longer necessary
