### ISSUE TITLE
Disabling of speed and hybrid mode is inconsistent

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#979]
When disabling CH in a request and this is not allowed I get an exception. This makes sense.

When disabling LM and this is not allowed the routing falls back to LM. No exception is thrown, which is inconsistent.

If we throw an exception we have to allow disabling in Measurement.java:
```
routing.lm.disabling_allowed=true
```

**Comment by boldtrn** [comment]
Should be fixed by now?
