### ISSUE TITLE
what to do to use graphhopper in eclipse?

### ISSUE THREAD

**Issue by eveliao** [graphhopper/graphhopper#983]
I got a list of (lat, lng) coordinates and i want to map-match them and export a list of OSM node ids.

so I just follow these two instructions [eclipse-set-up](https://github.com/graphhopper/graphhopper/blob/0.8/docs/core/eclipse-setup.md) and [tomcat-set-up](https://github.com/graphhopper/graphhopper/blob/0.8/docs/core/eclipse-tomcat-setup.md)?

I'm pretty new to java and not able to understand these instructions. I would truly appreciate it if you can give me more specific hints. Thanks a lot.

**Comment by boldtrn** [comment]
Please use the forum to ask questions. AFAIK, Map matching is not part of open source project, so you might want to have a look at the [directions API](https://www.graphhopper.com/pricing/). For the API you don't need any Java Knowledge.

**Comment by karussell** [comment]
Please note: map matching is not yet part of this repo, but it is open source: https://github.com/graphhopper/map-matching 
Still discussion does not happen in issues, also for this repo :)
