### ISSUE TITLE
Performance Problem for Android

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#984]
Have not tested performance on Android for a long time, but this is definitely too slow on my current device with Android 5.1.1. Nearly 60s for just 120km with CH routing. I think on my old device a 500km query was possible in under 30s.

**Comment by karussell** [comment]
Can reproduce this for 0.8.2 too but the 0.7.0 apk is *much* faster: <1s for a route with 120km!

**Comment by devemux86** [comment]
:confused: 
I try Cruiser (with GraphHopper 0.9-SNAPSHOT) on a [Nexus 9](http://www.gsmarena.com/htc_nexus_9-5823.php) for a country sized routing of around 1000Km with a non-CH graph and was performed at ~10sec!
I can try some other devices, what device did you test?

**Comment by karussell** [comment]
I have problems to reproduce this. Maybe there was something other wrong with my device, background process or similar. Will digg into it.

**Comment by karussell** [comment]
Cannot reproduce this, also not with #982

**Comment by devemux86** [comment]
Nice, I was worried we had somewhere a regression! :slightly_smiling_face:
