### ISSUE TITLE
Foot routing ignores a seemingly valid track

### ISSUE THREAD

**Issue by zstadler** [graphhopper/graphhopper#986]
To reproduce, open [this map](https://graphhopper.com/maps/?point=31.948994%2C35.356922&point=31.941438%2C35.363681&locale=en-US&vehicle=foot&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale).

Both start point and end point are on [way 317632042](https://www.openstreetmap.org/way/317632042)

**Comment by karussell** [comment]
This way is not connected to the rest of the road network. E.g. see [this node](http://www.openstreetmap.org/node/4714173004) which has only one way

**Comment by zstadler** [comment]
Let me clarify, I'm looking for a route **within** the way, not between this way and any other way.

**Comment by karussell** [comment]
If a way or a set of ways is completely disconnected from the rest of the network like in this case it is removed. The threshold for such mini islands is about ~200 junctions at the moment and therefor this way is removed.

**Comment by karussell** [comment]
To fix it: just connect this way to the already 'visually connected' ways in the north.
