### ISSUE TITLE
Use highway tag and actual edge speed for Instructions

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#990]
The DataFlagEncoder stores the highway type. The highway type allows us to create fancy instructions like: "leave the highway" or "enter the highway". Since the DFE works a bit different considering storing the speed of edges, we should find a way to calculate the actual speed of the edges for the Instructions calculation.

Also see #955 for some more discussion.

Updated TODOs:

 - [ ] InstructionsFromEdges => should rely on max_speed instead of accessEnc
 - [ ] remove FlagEncoder from InstructionsOutgoingEdges
 - [x] any encoder could be used (we even could remove DataFlagEncoder & GenericWeighting)
 - [x] how to replace encoder.getAnnotation(flags, tr) !?

**Comment by karussell** [comment]
The solution is to use the weighting and not the encoder for calculating the time for an edge IMO (?)

**Comment by boldtrn** [comment]
> The solution is to use the weighting and not the encoder for calculating the time for an edge IMO (?)

For the time, yes. The idea here was to check the speed of the edge. It might be that we don't need this check if we have highway tags.

Consider you are driving on primary and you are in a left curve. Now there is a small road leaving straight (this happens very frequent). The heuristic is, that if the leaving road is 2*slower, and if the left bending road has the same speed as the current edge, then we are probably following the street and are not leaving the road, therefore we don't need an instruction.

We might be able to do the same via highway tags, so maybe speed is not needed here.

**Comment by devemux86** [comment]
> We might be able to do the same via highway tags, so maybe speed is not needed here.

Optimal instructions calculation is usually performed via road types and names, so speed indeed seems superfluous here.

**Comment by boldtrn** [comment]
> so speed indeed seems superfluous here.

Yes, you are right. For encoders other than the DataFlagEncoder we don't have the road type. That's why I came up with the speed heuristic.

**Comment by boldtrn** [comment]
Should be fixed with #1844 :).
