### ISSUE TITLE
Maybe need more smart snapping or routing?

### ISSUE THREAD

**Issue by FallenKain** [graphhopper/graphhopper#996]
Not so long ago find some "not so good" thing that may be improved (i hope, sure :)), this thing is working snapping near cross points where 2 road one under another - example here:

https://graphhopper.com/maps/?point=52.522318%2C13.370871&point=52.523252%2C13.369986&vehicle=car

and now question - is we need to snap this point to upper road or mean lower road?
if we have next points like this:
https://graphhopper.com/maps/?point=52.523252%2C13.369986&point=52.52366%2C13.368891&vehicle=car
in 99% of cases we mean lower road
if next point like this:
https://graphhopper.com/maps/?point=52.523252%2C13.369986&point=52.523484%2C13.371139&vehicle=car
in 99% of cases we mean that point must snap to upper road

So that's why maybe improve snap logic, coz if point comes not so close to needed road routing result may be so bad with long detour for example :)

**Comment by karussell** [comment]
What is the use case behind this requirement? Do you want to find out the taken route from some point or for navigation? Then probably the [map matching component](https://github.com/graphhopper/map-matching) is more appropriate?

**Comment by FallenKain** [comment]
not for navigations, for route geometry from array of points, if some point like in sample has some coordinate lapse then route may calc wrong

**Comment by boldtrn** [comment]
@FallenKain, you could also have a look at the PointHint feature. https://graphhopper.com/maps/?point=52.522318%2C13.370871&point=52.523252%2C13.369986&vehicle=car&point_hint=%22%22&point_hint=Tunnel%20Tiergarten%20Spreebogen

**Comment by FallenKain** [comment]
@boldtrn not so good if sender didn't know is there a tunnel, brigde or simple road

**Comment by FallenKain** [comment]
for example we have a car that travels in city , some db has gps tracks of this car, we want to reproduce how it travels, we don't know all of info, only array of points with some lapse of gps tracker, that's all, in this situation we can get wrong routing result coz point snapped to wrong road

**Comment by boldtrn** [comment]
> for example we have a car that travels in city , some db has gps tracks of this car, we want to reproduce how it travels,

This is a perfect example for map matching. See @karussell comment. You can input a gpx and get the travelled route.
